### ISSUE TITLE
Unhandled error event: ClusterAllFailedError: Failed to refresh slots cache

### ISSUE THREAD

**Issue by fbenielli** [luin/ioredis#1000]
**Error description**

Hello, we are running ioredis 4.14.0 against an AWS ElastiCache replication group with cluster mode on (12 nodes, 3 shard) and using the cluster configuration address to connect to the cluster.

	this._redisClient = new Redis.Cluster([`//${host}:${port}`],
		{
			maxRedirections: process.env.MAX_REDIRECTIONS,
			redisOptions: {
				reconnectOnError: function (err) {
					const targetError = 'READONLY';
					if (err.message.slice(0, targetError.length) === targetError) {
						// Only reconnect when the error starts with "READONLY"
						return 2;
					}

					return false;
				},
			},
		});
	}`

The log of error that we are getting reads by:
`@message
2019-10-30T00:00:06.045Z 2970a6b4-2f41-468a-96f7-96649d690fbc [ioredis] Unhandled error event: ClusterAllFailedError: Failed to refresh slots cache.
at tryNode (/opt/nodejs/node_modules/ioredis/built/cluster/index.js:359:31)
at /opt/nodejs/node_modules/ioredis/built/cluster/index.js:376:21
at Timeout.duplicatedConnection.cluster.utils_2.timeout (/opt/nodejs/node_modules/ioredis/built/cluster/index.js:623:24)
at Timeout.run (/opt/nodejs/node_modules/ioredis/built/utils/index.js:156:22)
at Timeout.<anonymous> (/opt/nodejs/node_modules/async-listener/glue.js:188:31)
at ontimeout (timers.js:486:15)
at tryOnTimeout (timers.js:317:5)
at Timer.listOnTimeout (timers.js:277:5)`

**Error scenario**

We have an AWS Lambda function that connects to said cluster and is instantiated frequently. Sometimes the request is attended by a new container or it reuses an already existing one. The problem happens when the request is made to an alive container where the past request is older than a few minutes.

Example of an AWS Lambda container being reused
![image](https://user-images.githubusercontent.com/41455951/68303955-a2301f80-0083-11ea-908c-19590b5666da.png)

We have set our options.connectTimeout to be 900000 miliseconds (fifteen minutes) to try to avoid reconnecting but this has not been successful.
This is not a problem for us since the cluster does reconnect but we would like to understand why this is happening and if we can avoid having to do the reconnection since it adds time to our whole execution runtime.

**Comment by jp93arg** [comment]
Do you have any news about this issue?

**Comment by fbenielli** [comment]
Any updates on this? @luin

**Comment by jp93arg** [comment]
Any updates on this? @luin 
Thanks,
JP

**Comment by gamache** [comment]
Bump

**Comment by EJKIV** [comment]
Bump. Same issue

**Comment by ninjahsu** [comment]
Any updates on this? @luin
Thanks

**Comment by tommymarshall** [comment]
Bump :(

**Comment by balda** [comment]
Same issue

**Comment by satya-vinay** [comment]
Any updates on this? @luin
Thanks,
SV
