### ISSUE TITLE
Need unlink method on typescript please.

### ISSUE THREAD

**Issue by uniorder** [luin/ioredis#1001]
Need unlink method on typescript please :)

**Comment by eturino** [comment]
could we resurrect this ticket, please?

**Comment by AVVS** [comment]
Feel free to send a PR with the requested improvement :)

**Comment by eturino** [comment]
@AVVS linked PR

**Comment by AVVS** [comment]
I think maintainers would be happy to accept once tests pass https://travis-ci.org/DefinitelyTyped/DefinitelyTyped/builds/646532218?utm_source=github_status&utm_medium=notification

**Comment by eturino** [comment]
weird, it passed in my local. I must have messed something up :) I'll have a look

**Comment by AVVS** [comment]
there is a whitespace issue

**Comment by eturino** [comment]
Yeah, silly silly mistake. Instead of making a proper fork, since it was just one line I edited the file in github directly… which of course added the extra space in the empty line. No formatter there… 🤦‍♂ 

![AjYsTtVxEEBPO](https://media.giphy.com/media/AjYsTtVxEEBPO/giphy.gif)
