### ISSUE TITLE
Reconnecting blocks whole app. 

### ISSUE THREAD

**Issue by aviatrix** [luin/ioredis#1014]
I'm testing the auto reconnect features of ioredis, and i've noticed that everytime ioredis looses connection to the redis server (non cluster, non sentinel), it blocks everything for 1 minute per ioredis request. 
I've managed to cut that down to 1 second by tweaking `maxRetriesPerRequest = 1` and `retryStrategy` to 1s minimum, but when my http request do 10-20-100 redis requests (unable to bundle those into `mget` unfortunately) this slows down everything?

Can i make ioredis reconnect in the background naively, without having to implement custom logic?

**Comment by aviatrix** [comment]
Anyone has any ideas/clues how to prevent blocking?

**Comment by luin** [comment]
Sorry for the late response.

You can set `maxRetriesPerRequest` to 0 so that commands will be rejected when the connection is lost, but the connection will keep reconnecting.
