### ISSUE TITLE
Wiki (Improve Performance) recommends hiredis then says it's not supported

### ISSUE THREAD

**Issue by chang-zhao** [luin/ioredis#1018]
In the [Improve Performance](https://github.com/luin/ioredis/wiki/Improve-Performance), Wiki recommends hiredis in the first part of the article. In the second part it says hiredis support is dropped.

I think the first part should be deleted as outdated, or have I misunderstood something?

**Comment by luin** [comment]
Thank you for pointing this out! Actually both parts are outdated so I've removed the post. The pure JavaScript parser now has overall better performance, and the performance difference between w/ & w/o buffer support is subtle.
