### ISSUE TITLE
Error on title page documentation

### ISSUE THREAD

**Issue by chrisbossard** [luin/ioredis#1019]
Under the redis cluster section (Special note for AWS with TLS), there is a section that reads

> var cluster = new Redis.Cluster(
  [{
    host: 'clustercfg.myCluster.abcdefg.xyz.cache.amazonaws.com',
    port: 6379
  }],
  {
    dnsLookup: (address, callback) => callback(null, address),
    redisOptions: {
      tls: {}
    },
  }
};<

It has an extra '}' at the end where it should be a ')'

This was very useful part for solving a connection issue I had with AWS.

**Comment by luin** [comment]
Nice catch! Could you create a pull request for that?
