### ISSUE TITLE
pipeline.exec() don't execute and resolve with strange response

### ISSUE THREAD

**Issue by ttessarolo** [luin/ioredis#1026]
I've simple pipeline with some .del() and .set() commands that is not executing pointing an ElasticCache service on AWS. Is easy to see that is not executing because commands result are not in Redis.

The strange thing is that:

```
pipeline.exec((err, results) => {
   console.log(err, results)
})
```

prints:

`null [[{}],[{}],[{}]]`

**Comment by kauesedrez** [comment]
Same error here, I'll don't use pipeline anymore.
