### ISSUE TITLE
pfadd has some problem

### ISSUE THREAD

**Issue by nicetomeetnode** [luin/ioredis#1028]
when i use ioredis client to execute
```
for(let i=0;i<10000;i++){

            rs= await client.pfadd("hllt2",`u${i}`);
            if(rs!=1) {
                console.log("fail:",i,"==>",rs);
                arr1.push(i);
            }else{
                arr2.push(i)
            }
        }
```
there are many result return 0 not 1,why?but when i use 
`client.pfcount("hllt2");`
to get final result ,it return 9977,it seems correct.

**Comment by juris** [comment]
Problem still persists by the way.

**Comment by masoud-msk** [comment]
@nicetomeetnode You see that after adding `10000` elements, the count is `9977`. So `23` elements were not added to the HyperLogLog data structure (due to the probabilistic nature of it) and therefore `0` was returned.
