### ISSUE TITLE
Can't resolve redis service name/ IP using Kubernetes and Helm.

### ISSUE THREAD

**Issue by Cali93** [luin/ioredis#1029]
Hi everyone,

We are trying to deploy our app that was running just fine with docker-compose but once we deployed it to our Kubernetes cluster (GKE), the connection configuration started to fail.

`new Redis({
    host: "redis",
    port: 6379,
    password: "asupersecurepassword",
    retryStrategy: retryFn()
  })`

For the host we tried: redis, localhost, cluster IP, pod IP, serviceName, serviceName.namespace.svc.cluster.local,...

Here is how the error always looks like:

`
Error: getaddrinfo ENOTFOUND <servicename>.staging.svc.cluster.local
        at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26)
[ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND <servicename>.staging.svc.cluster.local
`

But when we make a `nslookup <servicename>` within the cluster, it succeeds to resolve with the actual service IP.

We are using the stable/redis Helm chart.

EDIT: I believe this is not an issue with ioredis but more with the fact that we are using a custom namespace so the DNS service is not working as expected maybe because it is on the kube-system namespace.

**Comment by ElMatella** [comment]
Hi, I am having the same issue, how did you solve the problem?

**Comment by JasmeetSinghChhabra** [comment]
Hi, I am having the same issue.

**Comment by shishirkhandelwal29** [comment]
Having the same issue. It works correctly when a Service IP is provided. Can we get an ETA on the fixes for this issue!

**Comment by luin** [comment]
Hi @shishirkhandelwal29 ,

Thanks for raising this! I'm not sure what should we do on ioredis side as it seems to be a network issue. `getaddrinfo ENOTFOUND` is a DNS error, which means ioredis can't resolve the host with the given hostname (via `dns.lookup`). What does `dns.lookup(yourhost, console.log)` print?

**Comment by a-type** [comment]
I'm also having this issue when trying to connect to a Redis instance running inside my cluster (via Bitnami's Redis helm chart).

If I run a standard DNS debugging pod inside my cluster it can resolve the service host:

```
nslookup redis-master.redis

Server:         10.64.0.10
Address:        10.64.0.10#53

Name:   redis-master.redis.svc.cluster.local
Address: 10.64.3.100
```

I tried attaching to the pod running the Node server which fails to connect and doing the lookup via REPL:

```
Welcome to Node.js v16.10.0.
Type ".help" for more information.
> const dns = require('dns');
undefined
> dns.lookup('redis-master.redis', console.log);
GetAddrInfoReqWrap {
  callback: [Function: log],
  family: 0,
  hostname: 'redis-master.redis',
  oncomplete: [Function: onlookup]
}
> null 10.64.3.100 4
```

So it appears to check out just fine. I'm a little stumped.

**Comment by pyk** [comment]
This happen on my deployment too.

DNS is working properly but ioredis always failed

```
kubectl exec -ti dnsutils -- nslookup redis
Server:		10.245.0.10
Address:	10.245.0.10#53

Name:	redis.graphql.svc.cluster.local
Address: 10.245.29.243
```

```
Welcome to Node.js v18.14.1.
Type ".help" for more information.
> const dns = require("dns")
undefined
> dns.lookup("redis", console.log)
GetAddrInfoReqWrap {
  callback: [Function: log],
  family: 0,
  hostname: 'redis',
  oncomplete: [Function: onlookup]
}
> null 10.245.29.243 4
command terminated with exit code 137
```


Removing `family` params fix the problem.

```ts
// from this
export default new Redis({
    host: config.REDIS_HOST,
    port: config.REDIS_PORT,
    password: config.REDIS_PASSWORD,
    family: 6
});

// to this
export default new Redis({
    host: config.REDIS_HOST,
    port: config.REDIS_PORT,
    password: config.REDIS_PASSWORD,
});
```

<img width="1118" alt="Screenshot 2023-02-20 at 00 33 32" src="https://user-images.githubusercontent.com/2213646/219964757-132890c7-8623-4c42-b24e-d23f8def1c1b.png">
