### ISSUE TITLE
Rewrite the JavaScript parser

### ISSUE THREAD

**Issue by luin** [luin/ioredis#103]
The JavaScript parser we're using is ported from node_redis, which has something we can improve:

- [ ] Too many backtracks makes parsing slow.
- [ ] Useless `try`/`catch` makes error stack unclear and also slows down the performance.

**Comment by phlip9** [comment]
If we're trying to improve the performance of the JavaScript parser, it would make sense to start with performance benchmarks comparing the parsers from ioredis, node_redis, and hiredis so we don't end up making inadvertent regressions.

This talk by Felix Geisendörfer seems relevant: [Faster than C](https://vimeo.com/56444583) [(pdf)](https://speakerd.s3.amazonaws.com/presentations/a926c2103ffb0130e97412313b100342/dublin.pdf)
He talks about getting the node-mysql parser up to speed parity (in some cases even exceeding) with the native C bindings.

**Comment by luin** [comment]
Just implemented the new parser: https://github.com/luin/ioredis/blob/new-parser/lib/parsers/ioredis.js. However, the result doesn't show much difference comparing with the current parser. So I'm closing this issue before we have time to revisit it.

The new parser will only be faster when the replies from Redis are broken into many small frames. For example, running the benchmark using the following code:

```javascript
    javascript.execute(new Buffer('$3'));
    javascript.execute(new Buffer('\r'));
    javascript.execute(new Buffer('\n'));
    javascript.execute(new Buffer('f'));
    javascript.execute(new Buffer('o'));
    javascript.execute(new Buffer('o'));
    javascript.execute(new Buffer('\r\n'));
```

And the result will be:
![image](https://cloud.githubusercontent.com/assets/635902/9977147/0eb86a1c-5f30-11e5-8cd3-f72ac53088a4.png)

Which is not going to happen in the real-world environment.

**Comment by AVVS** [comment]
There are a few optimizations that can be done, especially switch-case is best changed to object-based switch clause, then it can be easier optimized by v8

**Comment by BridgeAR** [comment]
Right now most time is spend by concatenating the buffer chunks together. So we'd have to find a way to improve that and that's not an easy task. @luin and me decided to move the parser to a own module so we might have another look at that at some point.
