### ISSUE TITLE
@types/ioredis doesn't support the reply transformer

### ISSUE THREAD

**Issue by edisonator** [luin/ioredis#1030]
I have noticed in `@types/ioredis` that,

the built-in arguments transformer has been supported like this:
```typescript
hmset(key: KeyType, ...args: ValueType[]): Promise<BooleanResponse>;
hmset(key: KeyType, data: object | Map<string, ValueType>): Promise<BooleanResponse>;
```

but the reply transformer hasn't:
```typescript
hgetall(key: KeyType, callback: (err: Error, res: string[]) => void): void;
hgetall(key: KeyType): Promise<string[]>;
```
the `res` data type could only be shown as `string[]` ,but  not transformed  to `object`.

I don't know if the `@types/ioredis`  belongs to official maintenance, or the question above is a bug or designed so.

**Comment by demian85** [comment]
I just added a new comment related to this: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/41085#issuecomment-567490730

I don't think `hgetall` returns numbers, as everything is stored as strings in Redis. Isn't it a mistake in the definition file?
