### ISSUE TITLE
send_command needs to have a type for interface Cluster

### ISSUE THREAD

**Issue by xtianus79** [luin/ioredis#1035]
send_command needs to have a type of interface Cluster so that it can be used. I don't get why you don't make your project a typescript project in general upon build

**Comment by pc-jedi** [comment]
I guess you are referring to `@types/ioredis`, are you?

**Comment by xtianus79** [comment]
@pc-jedi yes

**Comment by pc-jedi** [comment]
A PR to add the missing function is already there https://github.com/DefinitelyTyped/DefinitelyTyped/pull/40887.
The point why ioredis is not exporting the type definitions is detailed out here https://github.com/luin/ioredis/pull/981#issuecomment-538718567
