### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:6379

### ISSUE THREAD

**Issue by hckhanh** [luin/ioredis#1036]
I received this error when I try to start my Node server in k8s

```
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1129:14)
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1129:14)
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1129:14)
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1129:14)
```

I am using bullmq that using ioredis

**Comment by elucidsoft** [comment]
Use 0.0.0.0

**Comment by davalapar** [comment]
in your redis config:

```
bind 0.0.0.0
```

**Comment by hckhanh** [comment]
ok thank you

**Comment by fadel01** [comment]
> Use 0.0.0.0

how ?

**Comment by JoeLago** [comment]
My issue was pretty silly. I didn't realize I needed to install redis and start it on my machine.

**Comment by QUDUSKUNLE** [comment]
While trying to connect to Redis right from inside a container, one can use this `host.docker.internal` as host and `6379` as the port.

**Comment by Arpit6055** [comment]
> host.docker.internal

can you explain a bit, How our we gonna define our hst as host.docker.internal.  I'm building a micrservice(A nodejs app served by nginx). I have .yml with 3 services right now, The 1 for node app, 1 nginx container and 1 redis conatiner, the nginx and nodejs integration is perfectly working But I'm unable t connect to redis container
`

            node:internal/process/promises:265
            triggerUncaughtException(err, true /* fromPromise */);
           ^Error: connect ECONNREFUSED 127.0.0.1:6379

    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16)
    Emitted 'error' event on Commander instance at:
    at RedisSocket.<anonymous> (/usr/src/app/node_modules/@node-redis/client/dist/lib/client/index.js:338:14)
    at RedisSocket.emit (node:events:520:28)
    at RedisSocket._RedisSocket_connect (/usr/src/app/node_modules/@node-redis/client/dist/lib/client/socket.js:119:14)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Commander.connect (/usr/src/app/node_modules/@node-redis/client/dist/lib/client/index.js:162:9) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 6379}`


My  compose.yml file looks like

`version: "3.9"
   
services:
  testRedis:
    image: redis:7.0-rc1-alpine3.15
    expose:
      - "6379"
  nginx:
    build:
      context: ./nginx/
    ports:
      - 3000:80
    depends_on:
      - adminapp 
  app:
    build: .
    volumes:
      - ./:/usr/src/app/
      - /usr/src/app/node_modules
    env_file:
      - ./.env
    ports:
      - "12000:12000"`

and In nodejs I'm connecting to the client like this
`const redis = require("redis");

const client = redis.createClient({
    host: 'testRedis',
    port: 6379
});`

**Comment by Ic3m4n34** [comment]
I'm having the same issue

**Comment by fmainga** [comment]
Make sure you have redis server running

**Comment by Suniron** [comment]
Same probleme here.. A solution ?

**Comment by MorningLightMountain713** [comment]
Same problem... I'm running redis on another server. After I disconnect... it sits there trying to connect to a local redis instance, which will never exist, and which I didn't ask for

**Comment by luin** [comment]
Hey 👋
This is a network error. Very likely it is caused by a misconfiguration. Ex the server is not running, or there are multiple ioredis instances in your app and one of them doesn’t get a correct config. Please double check your code. If you think it is an issue on ioredis side, please provide a minimal reproducible example.

**Comment by MorningLightMountain713** [comment]
Yes - it turns out I'm a moron. As you were.

**Comment by i-in-range** [comment]
In my case I just should to install Redis on my machine.

I use Docker with next command:

`docker run -d --name redis-stack-server -p 6379:6379 redis/redis-stack-server:latest`

Other options are [here](https://redis.io/docs/stack/get-started/install/docker/)

**Comment by vajss** [comment]
For me was that starting container from Docker Desktop was starting all services except redis, so just had to start it separately.

**Comment by marcaureln** [comment]
> > host.docker.internal
> 
> can you explain a bit, How our we gonna define our hst as host.docker.internal. I'm building a micrservice(A nodejs app served by nginx). I have .yml with 3 services right now, The 1 for node app, 1 nginx container and 1 redis conatiner, the nginx and nodejs integration is perfectly working But I'm unable t connect to redis container `
> 
> ```
>         node:internal/process/promises:265
>         triggerUncaughtException(err, true /* fromPromise */);
>        ^Error: connect ECONNREFUSED 127.0.0.1:6379
> 
> at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16)
> Emitted 'error' event on Commander instance at:
> at RedisSocket.<anonymous> (/usr/src/app/node_modules/@node-redis/client/dist/lib/client/index.js:338:14)
> at RedisSocket.emit (node:events:520:28)
> at RedisSocket._RedisSocket_connect (/usr/src/app/node_modules/@node-redis/client/dist/lib/client/socket.js:119:14)
> at processTicksAndRejections (node:internal/process/task_queues:96:5)
> at async Commander.connect (/usr/src/app/node_modules/@node-redis/client/dist/lib/client/index.js:162:9) {
> errno: -111,
> code: 'ECONNREFUSED',
> syscall: 'connect',
> address: '127.0.0.1',
> port: 6379}`
> ```
> 
> My compose.yml file looks like
> 
> `version: "3.9"
> 
> services: testRedis: image: redis:7.0-rc1-alpine3.15 expose: - "6379" nginx: build: context: ./nginx/ ports: - 3000:80 depends_on: - adminapp app: build: . volumes: - ./:/usr/src/app/ - /usr/src/app/node_modules env_file: - ./.env ports: - "12000:12000"`
> 
> and In nodejs I'm connecting to the client like this `const redis = require("redis");
> 
> const client = redis.createClient({ host: 'testRedis', port: 6379 });`

Did you find a solution?

**Comment by DharmnathShinde** [comment]
```
Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
 port: 6379
}
```

I am also facing this issue

**Comment by samuel20miglia** [comment]
me too

Error: connect ECONNREFUSED 127.0.0.1:6379
 |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)

**Comment by Ahmadmidlaj** [comment]
Make sure that your environment variables are being loaded correctly before using them in your Redis configuration.

**Comment by odaytelbany** [comment]
For me it was the env vars, you have to use dotenv if you're configering redis in a seperated file.

**Comment by zhtgeneral** [comment]
I had a similar issue when I didn't specify host in new Redis. I had it like this

```
export const pubServer = new Redis(); 
export const subServer = new Redis(); 
```

and it caused this error

```
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1611:16)
```

but I made this change and now it was fixed

```
export const pubServer = new Redis({ host: 'redis' }); 
export const subServer = new Redis({ host: 'redis' }); 
```

I had redis already running in Docker at the time.

**Comment by baklaci** [comment]
Thanks [zhtgeneral](https://github.com/zhtgeneral). This was the only configuration that got [node-redis](https://github.com/redis/node-redis) (`5.11.0`) connecting:
```
import { createClient } from "redis";
const redisClient = createClient({
  //this setting did the trick
  socket: {
    host: "redis",
  },
})
.on("error", (err) => console.error("Redis Client onError:", err))
.on("connect", () => console.log("Redis Client onconnected   ✅"))
.connect();
```
