### ISSUE TITLE
defined commands don't work the first time within multi

### ISSUE THREAD

**Issue by ehacke** [luin/ioredis#104]
Looks like defined commands cannot be run for the first time inside of a multi block.

```javascript
it('should be able to use defined scripts for the first time within multi', function (done) {
    var redis = new Redis();

    redis.defineCommand('echoDynamicKeyNumber', {
      lua: 'return {KEYS[1],KEYS[2],ARGV[1],ARGV[2]}'
    });
    
    redis.multi({ pipeline: false });
    redis.set('foo', 'bar');
    redis.get('foo');
    redis.echoDynamicKeyNumber(2, 'k1', 'k2', 'a1', 'a2');
    redis.exec(function (err, results) {
      expect(results).to.eql([[null, 'OK'], [null, 'bar'], [null, ['k1', 'k2', 'a1', 'a2']]]);
      done();
    });
  });
```

Produces: `NOSCRIPT No matching script. Please use EVAL.`

Is this intended or necessary behaviour? Seems like there are tests for pipeline, but not multi with no pipeline.

If I load a lua file with defineCommand, and execute the command at least once before the multi block, it works.

**Comment by ehacke** [comment]
Seems to work fine with pipeline enabled.

### Work-around that works for me
I only disabled pipeline because I don't know ahead of time the commands I'll be sending in the multi block. So I can't chain them.

For my purposes, rather than disabling pipeline, I can just build an array of commands and submit them as a batch to the multi constructor.

```javascript
redis.defineCommand('echoDynamicKeyNumber', {
      lua: 'return {KEYS[1],KEYS[2],ARGV[1],ARGV[2]}'
    });

var commands = [];
commands.push(['echoDynamicKeyNumber', 2, 'k1', 'k2', 'a1', 'a2']);
if (somethingExists) {
  commands.push(['conditionalCommand', 'arg1', 'arg2']);
}
...
redis.multi(commands).exec(function(){..});
```

**Comment by luin** [comment]
Hi, `NOSCRIPT` occurs because `exec` is invoking before `eval`. You can refer to my comment to another issue: https://github.com/luin/ioredis/issues/91#issuecomment-118865612. The first time you run the following code:

```javascript
redis.multi({ pipeline: false });
redis.set('foo', 'bar');
redis.get('foo');
redis.echoDynamicKeyNumber(2, 'k1', 'k2', 'a1', 'a2');
redis.exec();
```

Would actually sending commands to Redis server as the following order:

```
MULTI
SET foo bar
GET foo
EVALSHA
EXEC
EVAL
```

Since pipelining in ioredis is very flexible, you can use pipelining this way:

```javascript
var pipeline = redis.multi().echoDynamicKeyNumber(2, 'k1', 'k2', 'a1', 'a2');
if (condition) {
  pipeline.get('foo');
}
pipeline.exec();
```

**Comment by ehacke** [comment]
@luin thanks! That'll work for me.

You can close this if you'd like.
