### ISSUE TITLE
a lot of functions are missing from the cluster Interface for typescript such as pipelone, hmset and etc

### ISSUE THREAD

**Issue by Ray1988** [luin/ioredis#1052]
we are using typescript and need using hmset, pipeline and multi on clusters, but we found all of these methods are missing from the cluster interface of typescript, I wonder is there any work around ? 

thanks

**Comment by BDQ** [comment]
Confirmed, I saw the same issue.

**Comment by Menci** [comment]
Some commands are also missing in `Redis.Redis`'s definitions. e.g. `bzpopmin`. Is it the same issue?

**Comment by luin** [comment]
Solved in v5. ioredis now provides official TypeScript declarations.
