### ISSUE TITLE
Get Call always returns promise{<Pending>}

### ISSUE THREAD

**Issue by gr423** [luin/ioredis#1069]
var Redis = require("ioredis");

function (key)
  {
        let data= this.redis.get(key, function(err, data) {
            if (err) {
              return err;
            } else {
              return  data;
            }
          });
        return data;
    }

The data is always promise{<Pending>}

How do i read the results? 

I expect the result to be immediate  .Please help me here .

Thanks in advance

**Comment by Uzlopak** [comment]
you are mixing callback and Promise usage. You have to await a promise.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await

**Comment by williamgrosset** [comment]
@gr423 This is an async operation, so you should define your function as so:
```js
async function ( key ) { ...}
```
and await your get method:
```js
let data = await this.redit.get(..)
```
