### ISSUE TITLE
Application crash unhandledRejection

### ISSUE THREAD

**Issue by Eomm** [luin/ioredis#1070]
The `v4.16.0` throw an `unhandledRejection` causing my app to crash in conjunction with [`make-promises-safe`](https://github.com/mcollina/make-promises-safe#make-promises-safe-)

Since I managed the error in the callback, I would expect no `unhandledRejection`

I have this minimal setup to reproduce:

```
const Redis = require('ioredis')
const client = new Redis({
  host: 'localhost',
  port: 6379,
  password: '',
  db: 1
})

process.on('unhandledRejection', err => {
  console.error('--> I get an unhandledRejection', err)
})

setTimeout(() => {
  client.quit()
    .then((res) => {
      client.get('key')
        .then((res) => { console.log({ res }) })
        .catch((err) => { console.error('error getting the key.. and it is fine:', err.message) })
    })
    .catch(() => { console.error('error quitting the client') })
})
```

**Comment by luin** [comment]
I can't reproduce this in v5.0.0 so assuming this is already resolved. Sorry for the late response! Feel free to reopen it if the issue still exists.
