### ISSUE TITLE
defineCommand still function after sentinel failover

### ISSUE THREAD

**Issue by wenq1** [luin/ioredis#1081]
After a sentinel failover (from a master to slave/replica), will the customCommand once defined (via defineCommand) on master still automatically work on the replica?

**Comment by luin** [comment]
Hey @wenq1 👋 

Sorry for the late response. It won't but if you define the commands with the `scripts` option introduced in v5.0.0, they should work after a failover.

Merged to #1081.

**Comment by wenq1** [comment]
Thanks
