### ISSUE TITLE
can not set expire time

### ISSUE THREAD

**Issue by ssdk86** [luin/ioredis#1082]
Hi!
I am trying to set expire time in set 
`const Redis = require("ioredis");`
`const redis = new Redis(); // uses defaults unless given configuration object`
`redis.set("key", 100, "EX", 10);`
but have an error
`ERR wrong number of arguments for 'set' command`
so i set expire throw the `redis.expire('key', 20);`

// ioredis supports all Redis commands:
`redis.set` with 2 arguments it is ok
`redis.set("foo", "bar")`; // returns promise which resolves to string, "OK"

**Comment by mr-kapoor** [comment]
you have two variables redis (has `redis` liberary) and Redis (has `ioredis` liberary).

set("key", 100, "EX", 10)
this is the prototype for `ioredis` liberary, but you use with redis not with Redis.

**Comment by luin** [comment]
Hey, thanks for using ioredis!

Redis only supports setting expire time in `SET` command from 2.6.12, so I think that would be your case. Closing this for now, feel free to reopen this if there's any other issue.

**Comment by ssdk86** [comment]
@luin , thanks!
I am realy have the windows redis server version is: `redis-2.4.5-win32-win64`
