### ISSUE TITLE
calling SET removes the TTL of a record

### ISSUE THREAD

**Issue by adonisv79** [luin/ioredis#1094]
I am not sure if this is intentional, if there is a way to change it but the document of ioredis just sucks or is something not really possible with this module. 

I created some record like 
```
await client.setex('key1', 'hello', 10);
const x = await client.ttl('key1')
// x = 10
```
when the code is changed to the following

```
await client.setex('key1', 'hello', 10);
await client.set('key1', 'world');
const x = await client.ttl('key1')
// x = -1
```
just running a set command automatically removes TTL. Now I have tried looking at the types (d.ts) file for anything that I can use and there appears to be something called an "expiryMode" parameter in the set command. looking at possible values for this and wow... ioredis docs denies its existence. It has no default and enumerated values, not even docummented. so what is that for? what I am doing btw is try to update the record without altering the existing TTL value

**Comment by adonisv79** [comment]
ugh! nevermind! you guys should use enums for this on your Typescript...

EX seconds -- Set the specified expire time, in seconds.
PX milliseconds -- Set the specified expire time, in milliseconds.
NX -- Only set the key if it does not already exist.
XX -- Only set the key if it already exist.
KEEPTTL -- Retain the time to live associated with the key

**Comment by adonisv79** [comment]
EX and NX works
```
await client.set('key1', 'world', 'EX', 5);
await client.set('key1', 'world', 'PX', 5000);
```
NX, XX and KEEPTTL errors out
```
await client.set('key1', 'world', 'NX', 5);
await client.set('key1', 'world', 'XX', 5);
await client.set('key1', 'world', 'KEEPTTL');
// result:
at parseError (..\node_modules\redis-parser\lib\parser.js:179:12)
    at parseType ..\node_modules\redis-parser\lib\parser.js:302:14)
```

**Comment by luin** [comment]
Hey @adonisv79!

The error stack you posted omitted the error message so I can’t speak for sure but it is likely due to the Redis server version is older than 6.0 as KEEPTTL is only supported by Redis > 6.0

**Comment by adonisv79** [comment]
ah, there is a version greater than 3.x? 
https://www.npmjs.com/package/redis
it seems that the latest in NPM is 3.0.2
can we add these to the guides? specially how to get the latest redis. thanks

**Comment by luin** [comment]
> ah, there is a version greater than 3.x? 
> 
> https://www.npmjs.com/package/redis
> 
> it seems that the latest in NPM is 3.0.2
> 
> can we add these to the guides? specially how to get the latest redis. thanks

I meant the version of the server, not the driver. Check out https://redis.io

**Comment by adonisv79** [comment]
ah got it! thanks
