### ISSUE TITLE
Add support for Auth with username & password (Redis 6)

### ISSUE THREAD

**Issue by gkorland** [luin/ioredis#1097]

**Comment by techpanga** [comment]
I am able to get this worked by passing below in new Redis({})... Hope this helps.

> password: ['user','password']

**Comment by gkorland** [comment]
@techpanga is seems like it can work as a workaround, but it doesn't feel like good solution for the long term

**Comment by gkorland** [comment]
@techpanga also it seems like all the user must have `+info` on their ACL otherwise it fails when creating the connection.

```
[ioredis] Unhandled error event: ReplyError: NOPERM this user has no permissions to run the 'info' command or its subcommand
    at parseError (/home/guy/redisclients/TestIoRedis/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/home/guy/redisclients/TestIoRedis/node_modules/redis-parser/lib/parser.js:302:14)
```

**Comment by techpanga** [comment]
@gkorland , Yes. it is workaround only. Thank you.

**Comment by luin** [comment]
Hey @gkorland @techpanga, actually giving `password` a `['user', 'password']` does work as expected and I think what we need to do is just documenting this usage.

For the `NOPERM` error, if the user doesn't have `+info` you should disable `enableReadyCheck` option like `new Redis({ enableReadyCheck: false })`.

wdyt?

**Comment by asyrique** [comment]
@luin This workaround only works if you're initializing ioredis using the `new Redis({options})`approach and passing in the `password` key in the options object.

However, we're initializing ioredis using the url string approach, passing in something like `redis://foo:bar@somehost:someport`, and this now fails (previously with Redis <6, we'd pass in the password without a user, i.e. `redis://:bar@somehost:someport`).

I'd be happy to submit a PR for this that would fix the the URL string parsing as well as adding an extra optional option `user` to the options object, if you're not already working on it.

Let me know!

**Comment by luin** [comment]
Yeah gotcha. PR is welcome

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by reshreshus** [comment]
A workaround would be to use a connection string
```ts
    RedisModule.forRoot({
      type: 'single',
      url: 'redis://default:password@localhost:6379',
    }),
```
