### ISSUE TITLE
key include ‘\x00\x15’ can't be worked

### ISSUE THREAD

**Issue by david1025** [luin/ioredis#1099]

**Comment by alavers** [comment]
Hi, do you have any more detail to provide? E.g a code sample that reproduces the issue?

**Comment by david1025** [comment]
> Hi, do you have any more detail to provide? E.g a code sample that reproduces the issue?

ok, first we need create a spring boot project.

pom.xml
```

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-redis</artifactId>
        </dependency>
       
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
```  

test code
```
@Autowired
private RedisTemplate redisTemplate;

redisTemplate.opsForValue().set("allStudents","studentList");
```

second, we use ioredis redis.keys(*), we can see it in the result 。
![image](https://user-images.githubusercontent.com/18585195/79081820-5b8dd200-7d53-11ea-8277-f83c464cd835.png)

**Comment by alavers** [comment]
It seems like whatever is trying to render that key is failing to properly render a string containing 0x00 and 0x15. I'm not sure how you ended up with such a key.

Are you expecting ioredis to behave any different here?

Here's what I observe:
```
> var Redis = require('ioredis')
undefined
> var r = new Redis()
undefined
> r.set(Buffer.from([0x0, 0x15]), 'value')
Promise { <pending> }
> r.scan(0).then(console.log)
Promise { <pending> }
> [ '0', [ '\u0000\u0015' ] ]
```

**Comment by david1025** [comment]
> It seems like whatever is trying to render that key is failing to properly render a string containing 0x00 and 0x15. I'm not sure how you ended up with such a key.
> 
> Are you expecting ioredis to behave any different here?
> 
> Here's what I observe:
> 
> ```
> > var Redis = require('ioredis')
> undefined
> > var r = new Redis()
> undefined
> > r.set(Buffer.from([0x0, 0x15]), 'value')
> Promise { <pending> }
> > r.scan(0).then(console.log)
> Promise { <pending> }
> > [ '0', [ '\u0000\u0015' ] ]
> ```

‘\x00\x15’ just a part of words，you can create a springboot project , save some keys, 

pom.xml
```

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-redis</artifactId>
        </dependency>
       
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
```  

test code  

```
@Autowired
private RedisTemplate redisTemplate;

redisTemplate.opsForValue().set("allStudents","studentList");
```

and you  use 
```
var Redis = require('ioredis')
var r = new Redis()
r.scan(0).then(console.log)
```
you can see ![image](https://user-images.githubusercontent.com/18585195/79081820-5b8dd200-7d53-11ea-8277-f83c464cd835.png)

**Comment by david1025** [comment]
> It seems like whatever is trying to render that key is failing to properly render a string containing 0x00 and 0x15. I'm not sure how you ended up with such a key.
> 
> Are you expecting ioredis to behave any different here?
> 
> Here's what I observe:
> 
> ```
> > var Redis = require('ioredis')
> undefined
> > var r = new Redis()
> undefined
> > r.set(Buffer.from([0x0, 0x15]), 'value')
> Promise { <pending> }
> > r.scan(0).then(console.log)
> Promise { <pending> }
> > [ '0', [ '\u0000\u0015' ] ]
> ```

you can clone this project https://github.com/david1025/redis-test.git , save some key

**Comment by alavers** [comment]
Oh. This has nothing to do with ioredis at all. The spring boot redis lib is inserting garbled key prefixes, presumably because it's trying to serialize java classes. That's an odd default behavior.

Anyway, this should fix your issue:

https://stackoverflow.com/questions/13215024/why-is-data-getting-stored-with-weird-keys-in-redis-when-using-jedis-with-spring/39939701#39939701
