### ISSUE TITLE
built in or externally packaged lua scripts

### ISSUE THREAD

**Issue by jonathanong** [luin/ioredis#11]
would be great to include some useful lua scripts out of the box. in particular, http://stackoverflow.com/a/27561399/927092

could also be a package called `ioredis-extensions` or something!

**Comment by luin** [comment]
make sense. I prefer to create an externally package to include these scripts since it's easy to use them without increasing complexity to ioredis itself:

```javascript
var Redis = require('ioredis');
var redis = new Redis();
require('ioredis-extensions')(redis);
```

**Comment by jonathanong** [comment]
Yup. That would be awesome!

**Comment by perrin4869** [comment]
I actually developed recently a set of tools for easy usage of lua scripts within node.js. Basically I take a lua script, and output a javascript module that can be easily used with `ioredis` or any other redis client: [redis-lua2js](https://github.com/perrin4869/redis-lua2js), [gulp-redis-lua2js](https://github.com/perrin4869/gulp-redis-lua2js), [node-hook-redis-lua](https://github.com/perrin4869/node-hook-redis-lua), and some standalone lua commands using those tools: [redis-pdel](https://github.com/perrin4869/redis-pdel). Maybe these can help solve this issue?
