### ISSUE TITLE
Auto-resubscribe not working in cluster mode

### ISSUE THREAD

**Issue by klinquist** [luin/ioredis#110]
If I get time tomorrow, I'll take a look at the code :).

**Comment by luin** [comment]
Just submitted a pr to fix it.https://github.com/luin/ioredis/pull/112. I'm going to do more testing and write unit tests for it. Welcome to test it if you get time.

**Comment by klinquist** [comment]
Just tested it on my side - seems to be working great!

Thank you!

**Comment by luin** [comment]
Fixed in 1.7.1
