### ISSUE TITLE
Upgrade lodash to >= 4.17.15

### ISSUE THREAD

**Issue by mdikov** [luin/ioredis#1100]
Is there a reason why ioredis cannot upgrade its used version of lodash to 4.17.15? The currently used versions have security issues.

**Comment by luin** [comment]
Hey, Mikhail. ioredis doesn't use lodash package directly, instead, it uses two method modules `lodash.defaults` & `lodash.flatten`, both are the latest versions. For security issues, `npm audit` doesn't report any with the master branch, could you confirm that?

**Comment by mdikov** [comment]
You are correct. I am trying to figure out a deep dependency on lodash that is triggering high severity and the ioredis versions caught my attention, but they are ok since they specify the method modules.
