### ISSUE TITLE
promise is not rejected when connection is impossible

### ISSUE THREAD

**Issue by Auruss** [luin/ioredis#111]
When using for example the get command:
```javascript
client.get('my_key').then(function() {
 /* success*/
}, function() {
 /* failure */
/* not called when connection to the redis server is not possible */
});
```

The failure callback is never called even though on my machine the redis server is currently not running.

**Comment by luin** [comment]
ioredis would keep trying to reconnect until the redis server is available again by default. This behaviour is useful in the production that your commands won't fail for a temporary disconnection.

You can refer to the documentation to disable/customize auto-reconnecting: https://github.com/luin/ioredis#auto-reconnect

**Comment by Auruss** [comment]
Is there a way to check if there is currently one open/valid connection?

**Comment by luin** [comment]
`status` property representing the connection status. It would be `ready` when the connection is active.

**Comment by Auruss** [comment]
ah ok, thanks for your help. :+1: 

So as this is the wanted behavior I will close this issue
