### ISSUE TITLE
Missing command MEMORY USAGE

### ISSUE THREAD

**Issue by LRagji** [luin/ioredis#1112]
Is there any reason why i dont see this command [MEMORY USAGE](https://redis.io/commands/memory-usage) or did i missed it?

**Comment by Rua-Yuki** [comment]
This would be accomplished via the `memory` method:

```js
const Redis = require('ioredis');

const client = new Redis();

client.memory('usage', 'KEY_NAME_HERE').then((bytesUsed) => {
    console.log('Bytes used:', bytesUsed);
});
```

While the docs list `MEMORY USAGE` as its own command, it's effectively the `MEMORY` command with an argument of `USAGE` and the key to be inspected.

**Comment by LRagji** [comment]
Thanks @Rua-Yuki i tried this already but it doesnt accept the SAMPLES count as mentioned in the command document i get a command error:
` return await this._redisClient.memory("usage", this._channelName,"0");` 
I get error "ReplyError: ERR syntax error" any thoughts?

**Comment by Rua-Yuki** [comment]
To accomplish what you're looking for, you've got to include the `SAMPLES` option name in your arguments list like so:

```js
return await this._redisClient.memory("usage", this._channelName, "samples", 0);
```

**Comment by LRagji** [comment]
My bad it works just an observation the numbers returned by lib are a bit different from redis-cli is this expected? lib:567; redis-cli:875 any idea why...

**Comment by Rua-Yuki** [comment]
Glad I could help!

Not sure about the inconsistency you're experiencing between redis-cli and ioredis, but it does seem to work reliably here.

It's definitely worth checking to make sure the same arguments are being applied in both cases. If the argument lists appear to be the same between CLI and your ioredis consumer, it could be that the target key was somehow mutated between testing.

**Comment by yuanchieh-cheng** [comment]
I have tried memory command but got this error
```
UnhandledPromiseRejectionWarning: ReplyError: ERR unknown command 'memory'
```

here is my code and I used 4.17.3
```js
await redis1.memory('usage', 'timer:smd_clotilde.tortora@gmail.com/ivuu12SM-N9005F025B7BC2E7C_934825359125318132');
```

I cannot find memory function declaration in @types as well.

**Comment by Zikoel** [comment]
> This would be accomplished via the `memory` method:
> 
> ```js
> const Redis = require('ioredis');
> 
> const client = new Redis();
> 
> client.memory('usage', 'KEY_NAME_HERE').then((bytesUsed) => {
>     console.log('Bytes used:', bytesUsed);
> });
> ```
> 
> While the docs list `MEMORY USAGE` as its own command, it's effectively the `MEMORY` command with an argument of `USAGE` and the key to be inspected.

I can't see that from typescript! Maybe this method is missing on type declaration ?
