### ISSUE TITLE
Mset with ttl? 

### ISSUE THREAD

**Issue by samuelgjabel** [luin/ioredis#1122]
It is possible to use mset with ttl (expiration time)? If yes how? I cant find docs about it.

Thanks.

**Comment by luin** [comment]
I don’t think it’s possible but you can use pipelining or scripting.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by samuelgjabel** [comment]
Ok thanks..Yea..i found same answer on google...so iam going to close this.
