### ISSUE TITLE
Dump and Restore

### ISSUE THREAD

**Issue by bregard** [luin/ioredis#1131]
Any help on why this simple example would fail with: `ReplyError: ERR DUMP payload version or checksum are wrong`.

```javascript
const Redis = require("ioredis");

(async () => {

  try {
    const redis = new Redis({host: 'localhost'});
    let data = await redis.dump('0000_OLD_KEY');
    await redis.restore('0000_NEW_KEY', 0, data);
    process.exit();
  } catch (err) {
    console.error(err);
    process.exit(1);
  }
})();
```

**Comment by bregard** [comment]
Use `dumpBuffer` not `dump`. Where are the docs for this?

**Comment by naseemkullah** [comment]
Hi @bregard I am running into this same issue, what's this about `dumpBuffer` ?

**Comment by naseemkullah** [comment]
FWIW I get `Property 'dumpBuffer' does not exist on type 'Redis'.`

**Comment by naseemkullah** [comment]
I guess `dumpBuffer` does not exist in latest `ioredis`.

**Comment by naseemkullah** [comment]
`dump` should not exist in it's string form, it seems like we would always want `dumpBuffer`
