### ISSUE TITLE
v4.17.0 breaking change for Redis parser

### ISSUE THREAD

**Issue by jamesjjk** [luin/ioredis#1132]
Release v4.17.0 fails to parse username:password combinations for redis version 5 and lower. The Rediss / Redis URL connection strings are no longer valid.

```
[ERROR] The server returned "wrong number of arguments for 'auth' command". You are probably passing both username and password to Redis version 5 or below. You should only pass the 'password' option for Redis version 5 and under.
[ioredis] Unhandled error event: ReplyError: NOAUTH Authentication required.
```

**Comment by luin** [comment]
Thank you for pointing this out. Could you explain the use case why you specifying username:password combinations for Redis <= 5? Or in your case you just want to ignore `username`?

**Comment by Kikobeats** [comment]
@luin it isn't a thing related with the username: I'm experimenting the same behavior and essentially any URI string like

```
// Connect to 127.0.0.1:6380, db 4, using password "authpassword":
new Redis("redis://:authpassword@127.0.0.1:6380/4");
```

doesn't work using at `v4.17.0`, but works as expected at `v4.16.x`

**Comment by luin** [comment]
@Kikobeats I can't reproduce this issue locally with the following code:

```javascript
const redis = new Redis("redis://:authpassword@127.0.0.1:6379/4");
```

Could you log `redis.options` and post the result here? `username` property should be `null`.

**Comment by Kikobeats** [comment]
```
❯ cat config/staging.yml | grep REDIS_URI
  REDIS_URI: redis://redis-instance.ec2.cloud.redislabs.com:18529
  
❯ cat node_modules/ioredis/package.json | grep version
  "version": "4.17.0"

❯ NODE_ENV=staging node index.js
  microlink-api address=:::3000 node=13.14.0 environment=staging pid=28438 status=listening version=2.17.7 +0ms
Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)

❯ npm i ioredis@4.16 && cat node_modules/ioredis/package.json | grep version
  "version": "4.16.3"

~/Projects/microlink/api next
❯ NODE_ENV=staging node index.js
  microlink-api address=:::3000 node=13.14.0 environment=staging pid=30732 status=listening version=2.17.7 +0ms
```

at `4.17.0`, the parser thinks I'm trying to connect with a local Redis 🤔

**Comment by luin** [comment]
@Kikobeats Hmm...strange. It works for me:

```javascript
const redis = new Redis("redis://redis-instance.ec2.cloud.redislabs.com:18529");
```

And ioredis does connect to redis-instance.ec2.cloud.redislabs.com instead of 127.0.0.1.

**Comment by mrspartak** [comment]
Got this error too with DigitalOcean connect string. It looks like this:
rediss://default:[password]@[host]:[port] 
But without username works fine. 
rediss://:[password]@[host]:[port]

Too bad it broke our containers and whole logs were spamed with `NOAUTH Authentication required` because we use Moleculer

**Comment by luin** [comment]
Fixing this with #1134. Sorry for the inconvenience and thanks for pointing this out!

**Comment by Kikobeats** [comment]
Hello,

unfortunately, this is happening again in the last versions:

ioredis@4.17 -> works fine
ioredis@4.18 -> doesn't work
ioredis@4.19 -> doesn't work

.cc @luin

**Comment by AVVS** [comment]
@Kikobeats are you sure about 4.18? The only change in there was an update to redis-commands module, nothing that touched URI parsing code was affected.

**Comment by Kikobeats** [comment]
@AVVS I'm really sure

<img width="1114" alt="Screen Shot 2020-11-02 at 16 45 46" src="https://user-images.githubusercontent.com/2096101/97887978-e1db2700-1d2a-11eb-988c-b4e2745b1c91.png">

4.17 vs 4.18

**Comment by Kikobeats** [comment]
@AVVS Yes, I'm sure:

<img width="1060" alt="Screen Shot 2020-11-02 at 16 46 35" src="https://user-images.githubusercontent.com/2096101/97888050-f9b2ab00-1d2a-11eb-90a4-d421dbc4ef3e.png">

4.17 vs 4.18

**Comment by AVVS** [comment]
I'm not sure what the cause of this would be though - https://github.com/luin/ioredis/compare/v4.17.3...c016265028d746ab71ab2ad65e49a3fbe8c0f49c is the changelog and nothing affects the parsing here
