### ISSUE TITLE
Possible DNSLookupFunction wrong type

### ISSUE THREAD

**Issue by karlismelderis** [luin/ioredis#1148]
shouldn't err type should be as err is attached only when there is an error
`err: NodeJS.ErrnoException | null,`

I'm refering to DNSLookupFunction type.
```js
export type DNSLookupFunction = (
  hostname: string,
  callback: (
    err: NodeJS.ErrnoException,
    address: string,
    family: number
  ) => void
) => void;
```

**Comment by marcbachmann** [comment]
Apparently that got fixed https://github.com/luin/ioredis/blob/8b19b9623a6aff74d30df3d4b4d40ecbd771e0c0/lib/cluster/ClusterOptions.ts#L17
