### ISSUE TITLE
missing hvalsBuffer and hgetallBuffer

### ISSUE THREAD

**Issue by JonasKruckenberg** [luin/ioredis#1152]
The `redis.hvalsBuffer()` and `redis.getallBuffer()` methods, while existent are marked as nonexistent when using tyescript.
My setup:
ioredis: 4.17.3
typescript 3.9.5

**Comment by luin** [comment]
I think the issue belongs to https://github.com/DefinitelyTyped/DefinitelyTyped so can you create a ticket there?

**Comment by luin** [comment]
ioredis v5 provides official TypeScript declarations so closing this. Sorry for the late response!
