### ISSUE TITLE
不支持 redis cluster 5.x 吗？

### ISSUE THREAD

**Issue by zhoudian2010** [luin/ioredis#1153]
3.2.100、4.0.8 部署的集群，连接没有问题，但是 redis cluster 5.x 部署的集群连接提示：ClusterAllFailedError: Failed to refresh slots cache。

redis cluster 5.x 部署的集群信息如下：
10.2.9.151:7002(5461-10922):0>cluster nodes
"9ddd468040513f933a240663df3ed6031fc1de61 10.2.9.150:7001@17001 myself,master - 0 1592205781000 1 connected 0-5460
ca939936ad371ae55fdb0967280f11a055183f55 10.2.9.152:7001@17001 slave 19a2791454f8ef8df27fc7472b2847c3b49d1d5a 0 1592205783150 5 connected
911fb6e2654d07e718963b59c9e430324281ecdf 10.2.9.152:7002@17002 master - 0 1592205782649 4 connected 10923-16383
19a2791454f8ef8df27fc7472b2847c3b49d1d5a 10.2.9.151:7002@17002 master - 0 1592205782000 2 connected 5461-10922
61e6843963a7be17b1416dbf94297520f17b703e 10.2.9.150:7002@17002 slave 911fb6e2654d07e718963b59c9e430324281ecdf 0 1592205783000 6 connected
bcc18d39512d4da0de80f0d7f0fbb2fc76fdb590 10.2.9.151:7001@17001 slave 9ddd468040513f933a240663df3ed6031fc1de61 0 1592205783651 3 connected

**Comment by luin** [comment]
支持 5.x。可以打开 debug 模式看看错误日志（DEBUG=ioredis:* node yourapp.js）

**Comment by zhoudian2010** [comment]
electron 启动的，不太清楚怎么设置 （DEBUG=ioredis:* node yourapp.js）

**Comment by zhoudian2010** [comment]
目前能确定的是，redis-cli 连接上去是正常的。

**Comment by zhoudian2010** [comment]
另外，连接失败，怎么没有堆栈信息给到调用方？

**Comment by quick123official** [comment]
ClusterAllFailedError: Failed to refresh slots cache 提示不够明确，不知道发生了什么事情。

**Comment by zhoudian2010** [comment]
ClusterAllFailedError: Failed to refresh slots cache 提示不够明确，不知道发生了什么事情。

**Comment by zhoudian2010** [comment]
是我建立连接的方式不对。不过提示不够清楚，不方便定位问题。
