### ISSUE TITLE
Can a multi be exec multiple time like pipeline?

### ISSUE THREAD

**Issue by zyf0330** [luin/ioredis#1154]
A pipeline can exec multiple times one by one after every exec, but it seems that a multi behaviors weird when do this.

**Comment by luin** [comment]
Can you provide a test case for your usage?

**Comment by zyf0330** [comment]
Sorry, I am blind. Itis just calling `multi` after `pipeline`.
But it still behaviors weird between `pipeline` and `multi`. When call another time exec of `pipeline` , it just returns same result like first. As for `multi`, it returns `[null, 'OK']` firstly, and second call returns `[ [ null, "OK" ], [ null, "QUEUED" ], [ null, [ "OK" ] ] ]`.
So is there a mark to check if a pipeline or multi has be `exec`ed?

**Comment by luin** [comment]
No, there isn't. Generally I'd suggest never reusing `pipeline` and `multi` as the behaviors are undefined and there's no extra cost for creating a new `pipeline` or `multi`.

**Comment by zyf0330** [comment]
Can I use `_transactions` of multi to act as this mark?

**Comment by luin** [comment]
You shouldn't. It does work for now but as the name suggests it's a private variable so may be changed in future releases.

**Comment by zyf0330** [comment]
Ok, thanks for your answer.
