### ISSUE TITLE
Link to "benchmark section" in README doesn't point to anywhere

### ISSUE THREAD

**Issue by Tyriar** [luin/ioredis#1156]
![image](https://user-images.githubusercontent.com/2193314/85405011-a62a8800-b514-11ea-91dd-934b36095f29.png)

Points as non-existing hash: https://github.com/luin/ioredis#benchmark

**Comment by danitseitlin** [comment]
@luin I looked into the README and it seems like there is no such section, can you elaborate on the meaning of this link? Did you mean to link to the benchmarks folder maybe?

**Comment by luin** [comment]
There was a benchmark section but the content was outdated so I removed it. It was an oversight I didn't remove the link.
