### ISSUE TITLE
Events and Connection Events tables are almost duplicated in README

### ISSUE THREAD

**Issue by NathanJAdams** [luin/ioredis#1159]
There are 2 almost duplicated tables in the README, Events and Connection Events, the only difference is the Events table has entries to do with Nodes. This might be intentional but it confused me for a minute!

**Comment by luin** [comment]
Yeah it's intentional as one of them describes events for `Redis` and the other for `Redis.Cluster`.

**Comment by marcbachmann** [comment]
Let's close this
