### ISSUE TITLE
How to find an element in a List, I cannot find the lpos command?

### ISSUE THREAD

**Issue by snaplesec** [luin/ioredis#1163]
I'm trying to get the index of an element in a list that I loaded under a key, but cannot figure out how to find it.

**Comment by luin** [comment]
Hi @snaplesec , every command is supported so you can use `redis.lpos('mylist', 'c')`

**Comment by snaplesec** [comment]
Thank you, I will try it like you said.

Sent via the Samsung Galaxy Note10+, an AT&T 5G Evolution capable smartphone
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by luin** [comment]
Actually, I just realized lpos was added in Redis 6.0.6 which ioredis didn't support. I updated ioredis to v4.18.0 and it should provide that command.

**Comment by snaplesec** [comment]
OK, thank you,  I realized that I am running on redis cluster 5.0.6 so I guess it won't matter.  Thank you for looking into that.

Sent via the Samsung Galaxy Note10+, an AT&T 5G Evolution capable smartphone
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by barakplasma** [comment]
I added the LPOS command to the types for v4.19. It's published on version 4.19 of  @types/ioredis
