### ISSUE TITLE
Responses are returned to wrong requests

### ISSUE THREAD

**Issue by danielmoonactive** [luin/ioredis#1166]
ioredis version: 4.6.0

During cluster failover in production, and also reproducible in the lab, we noticed that some responses we get back from ioredis are corrupted. The corruptions include:

- values that are misplaced in wrong keys;
- partial responses than what is expected;
- data mixed up between users.

We enabled ioredis logs and found this happens in the ioredis level, right after the response is returned from Redis. We also noticed that the mixup happens within the same node connection, and not in between streams, which strengthens the suspicions that is has to do with ioredis itself. We also ensured that the business logic saves the data correctly to Redis.

Please assist.

**Comment by ttacon** [comment]
@danielmoonactive Would you be able to share some example configurations under which you saw this issue? We're actively digging into a similar issue and any known reproducible setups would be greatly appreciated.

**Comment by danielmoonactive** [comment]
Apparently it was a bug in a third party vendor that didn't return correctly in a rare case the redis response in a correct format.
