### ISSUE TITLE
Typescript Error: Cannot find module 'ioredis'

### ISSUE THREAD

**Issue by thoratatul** [luin/ioredis#1169]
Hey

- Typescript 3.9.7
- ioredis 4.17.2

Getting Error: Cannot find module 'ioredis'
`import Redis from 'ioredis'
const redis = new Redis();`

Added devDependencies as "@types/ioredis"

if tried 
`import * as Redis from "ioredis";
const redis = new Redis();`

Getting error TS2351: This expression is not constructable

**Comment by luin** [comment]
It should be related to your local setup so not sure what's the reason without more details. Generally, `import Redis from 'ioredis'` should work out-of-box.

**Comment by calebboyd** [comment]
Just noticed this too -- Are the types purposefully maintained separate from the source?
(also noticed there is a definitely typed package) But this project itself doesn't use the `declaration: true` flag in tsconfig to ship types directly.

**Comment by yuwanlan** [comment]
nodeJs v16.5
import Redis from 'ioredis' 
nodeJs  v15.6
import * as Redis from 'ioredis'
