### ISSUE TITLE
Docker redis-cluster not working if node is running on host

### ISSUE THREAD

**Issue by kaufmo** [luin/ioredis#1173]
I've found a strange problem and hope somebody understands it and can help me. 
I switch locally from redis to redis-cluster nodes in docker because I want a setup which will be the same when running in production. 
On linux everything works fine with this setup (because docker is running in kernel) on mac it doesn't work (because docker is running in VM). 
I've found the problem in the code, in docker I'm exposing the redis ports to host system (6381,6382 & 6383) and this config is used for Redis.Cluster connection. 
The first connect works fine on both systems but then the code here (https://github.com/luin/ioredis/blob/master/lib/cluster/index.ts#L749) is called which asks the redis nodes for the other nodes and these are connected inside docker with the docker containername and the default port. 
Then my node application can't connect anymore to the redis nodes on mac.
A workaround for me was to add a natMap but the problem here is that I don't know which IPs my redis nodes will get inside docker. Is it possible to disable this feature for docker development? I can post also more infos if needed.

**Comment by marcbachmann** [comment]
Best practice is probably to configure `cluster-announce-ip` and `cluster-announce-port`, maybe together with static ip addresses in docker: https://github.com/redis/redis/commit/5ac5e3ebd7da8f041ebd7c4d20020208a3066b2d#diff-c683e35ac8c539e4f6c402fc159fe0e57086e3e661dd9ac7e48cedaee2c79c14R867-R869

I'll close this for now as this is a docker for mac networking/reachability problem.
