### ISSUE TITLE
How to use command expireat

### ISSUE THREAD

**Issue by ArminYang** [luin/ioredis#1176]
I dont see the usage

**Comment by simonprickett** [comment]
@ArminYang you supply a key name and a UNIX timestamp that is the time you want the key to expire at.  Example:

```javascript
const Redis = require('ioredis');
const redis = new Redis({
  host: '127.0.0.1',
  port: 6379
});

const redisDemo = async () => {
  await redis.set('mykey', 'testing');
  await redis.expireat('mykey', 1603297274);
};

redisDemo();
```

Looking at this key with `redis-cli` we see the TTL has been set:

```
% redis-cli
127.0.0.1:6379> ttl mykey
(integer) 99967
127.0.0.1:6379> get mykey
"testing"
```

Hope this helps.

**Comment by nickangtc** [comment]
I don't think @simonprickett's suggestion works. `redis.expireat()` is not a method on the Redis instance.

This works, and is documented in this repo:

```js
const THREE_HOURS_IN_SECONDS = 3 * 60 * 60;
await redis.set(
    'exampleKey',
    JSON.stringify(exampleKey),
    'EX',
    THREE_HOURS_IN_SECONDS
);
```

![image](https://user-images.githubusercontent.com/5674362/105732810-2395fb00-5f31-11eb-888f-94735c2f0e72.png)

Source: https://github.com/luin/ioredis#basic-usage

Also, see Redis' (not ioredis) documentation on difference between 'EX' and 'PX' here: https://redis.io/commands/set

**Comment by simonprickett** [comment]
> I don't think @simonprickett's suggestion works. `redis.expireat()` is not a method on the ioredis instance provided by this library.

This works perfectly, ioredis 4.3.1, Redis 6.0.8 open source version:

```javascript
const Redis = require('ioredis');
const redis = new Redis({
  host: '127.0.0.1',
  port: 6379
});

const redisDemo = async () => {
  await redis.set('mykey', 'testing');
  await redis.expireat('mykey', 1611619200);
  redis.quit();
};
```

```bash
$ node index.js
ioredis_expireat $ redis-cli ttl mykey
(integer) 19493
```

**Comment by nickangtc** [comment]
@simonprickett maybe it's the versioning? I'm using ioredis 4.14.1 and it doesn't work (no errors). 

Granted, I only know it doesn't work because in an internal tool at work that's supposed to fetch fresh data from an external API whenever the cache's data is expired, it never fetched the data from the API (but reached into the cache all the time for weeks unnoticed). After I swapped to the documented way (i.e. `redis.set(x, y, 'EX', 3600)`) the cache invalidated every hour according to my logs.

**Comment by luin** [comment]
Sorry for the late response. This is now documented at https://github.com/luin/ioredis/blob/main/examples/ttl.js#L13
