### ISSUE TITLE
Mention support for ACL 

### ISSUE THREAD

**Issue by burzynnn** [luin/ioredis#1185]
# Problem
I was looking for a package to maintain Redis database with support for new Redis ACL feature. By looking at readme and API documentation of your package I thought it is not included. Only testing it out and checking source code made me stay with this package.
# Solution
I suggest adding these informations to make others life easier :)
- Point out ACL support in [features section of readme](https://github.com/luin/ioredis/blob/master/README.md#features),
- Add username field to [documentation of connect options](https://github.com/luin/ioredis/blob/master/API.md#new-redisport-host-options).

**Comment by simonprickett** [comment]
When documenting the username field for connection options, I'd recommend pointing out that the user needs access to run the `INFO` command at the moment, otherwise ioredis will not connect successfully (see https://github.com/luin/ioredis/issues/1211)
