### ISSUE TITLE
does mset supports options like set operation does?

### ISSUE THREAD

**Issue by jagadeeshmeesala** [luin/ioredis#1186]
How to set key expiry while using mset command?

I want to use mset like this, similar to set command.
```
redisClient.mset({'key1': 'value1'}, 'EX', 10);

```
Will mset provides the option to set expiry on multiple keys? If not, can anybody let me know the right way to use it?

**Comment by christopher-caldwell** [comment]
@jagadeeshmeesala 
No. Check out the [closed section of the issues](https://github.com/luin/ioredis/issues?q=is%3Aissue+is%3Aclosed+mset) for the solution. Particularly [this one](https://github.com/luin/ioredis/issues/1133#issuecomment-630351474) seems accepted

**Comment by TysonAndre** [comment]
Calling set multiple times with https://github.com/luin/ioredis#autopipelining is another option, if the only concern is getting a batch of requests finished quickly and not atomicity
