### ISSUE TITLE
Unhandled error event: Error: connect EHOSTDOWN

### ISSUE THREAD

**Issue by OPScorp** [luin/ioredis#1209]
Hi,
I am getting Error: connect EHOSTDOWN and terminating of server process when connecting to unavailable Redis server.
Sometimes on start and sometimes on reconnecting try.

Problem in this file: [StandaloneConnector.js](https://github.com/luin/ioredis/blob/master/lib/connectors/StandaloneConnector.ts)
in function connect.

process.nextTick(() => {
                if (!this.connecting) {
                    reject(new Error(utils_1.CONNECTION_CLOSED_ERROR_MSG));
                    return;
                }
                try {
                    if (options.tls) {
                        this.stream = tls_1.connect(connectionOptions);
                    }
                    else {
                        this.stream = net_1.createConnection(connectionOptions);
                    }
                    // Need to add this code!!
                    this.stream.once("error", err => {
                        reject(err);
                    });
                }
                catch (err) {
                    reject(err);
                    return;
                }
                resolve(this.stream);
            });

P.S.: this is final fix. Hope help someone with this.

**Comment by peteraw77** [comment]
Is there any reason you haven't made a PR with this change? It solved the issue for me and I think it would be good to bring it to the maintainer's attention.

**Comment by andywelters** [comment]
I have the same issue.  Let's make a PR.
