### ISSUE TITLE
Creates multiple connections to slave server which is overhead 

### ISSUE THREAD

**Issue by supriyakhankarnw18** [luin/ioredis#1214]
Hi,
I am using slave redis to read the data. Redis connection is created in main file and all request uses that connection. Redis slave timeout is disabled on server.

Below is the connection code:

let redisSlaveConnectionObj = new IORedis({
    host: host,
    connectTimeout: 3000000,
    retryStrategy: function(times) {
        var delay = Math.min(times * 5, 2000);
        return delay;
    },
    reconnectOnError(err) {
        return true;
    },
});

app.set('redisSlaveConnectionObj',redisSlaveConnectionObj);

In my case max allowed threads are 6. 
After 2-3 when I check number of connection from my IP to slave sever it shows around 400 connection .Unable to understand the reason. 

Please help.

**Comment by luin** [comment]
Hi, sorry for the late response. A single `Redis` instance should only open a single connection. So I think it might be there were many instances created?

Closing this but feel free to reopen if the issue still there.
