### ISSUE TITLE
The dependencie 'p-map' require node >= 10

### ISSUE THREAD

**Issue by Zhouxingzu** [luin/ioredis#1216]
I find that i can't run it in my project, my node is 6,  is it caused by this problem?

**Comment by ShogunPanda** [comment]
Yes, I introduced this dependency in #1201 in order to send scripts to the server in controlled way.
Node 6 has gone End Of Life, I advice to updated it if you can.

**Comment by Zhouxingzu** [comment]
> Yes, I introduced this dependency in #1201 in order to send scripts to the server in controlled way.
> Node 6 has gone End Of Life, I advice to updated it if you can.

Thanks, bro, I see README mentioned (Node.js >= 6) before. I will update my node

**Comment by NicoZelaya** [comment]
The readme should be fixed then and this should be considered a breaking change. Jumping from Node 6 as minimum version to Node 10 is somewhat unexpected for a minor release given this is not new functionality.

**Comment by AVVS** [comment]
@ShogunPanda any chance you'd be able to replace p-map with an utility that supports node 6+ ? I agree with comments re: breaking change, even though nodejs 6 is no longer supported at all

**Comment by ShogunPanda** [comment]
Yes, I can just downgrade `p-map` to `^2.1.0`, which is the last one that supports Node 6.

Also, I'm gonna change the Travis conf to run against all supported Node versions.
