### ISSUE TITLE
geo command missing from typescript types

### ISSUE THREAD

**Issue by plus-** [luin/ioredis#1227]
This was already reported after the following issue was closed https://github.com/luin/ioredis/issues/654

> Property 'geoadd' does not exist on type 'Redis'.ts(2339)
> 
> Property 'geoadd' does not exist on type 'Pipeline'.ts(2339)
>

**Comment by MathieuAA** [comment]
This issue still exists with
  - ioredis: v4.19.4
  - @types/ioredis: 4.17.8

**Comment by plus-** [comment]
I've added part of them in [@types/ioredis: 4.17.9](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/50144)

Notably `GEOSEARCH` and `GEOSEARCHSTORE` is missing.

**Comment by MathieuAA** [comment]
@plus- thanks :)
