### ISSUE TITLE
getBuffer returns string when enableAutoPipelining is true

### ISSUE THREAD

**Issue by adamnoakes** [luin/ioredis#1228]
Hi, firstly, thanks for releasing the new auto pipelining feature.

Whilst testing on my project, I noticed that `getBuffer` returns the result converted to string (rather than a `Buffer`) with `enableAutoPipelining` set to `true`. Is this expected/ a known limitation with the pipelining implementation?

**Comment by adamnoakes** [comment]
Been looking into this a bit further and seems to be caused by *Buffer commands being created with Buffer omitted
https://github.com/luin/ioredis/blob/master/lib/commander.ts#L65-L71
```typescript
commands.forEach(function (commandName) {
  Commander.prototype[commandName] = generateFunction(commandName, "utf8");
  Commander.prototype[commandName + "Buffer"] = generateFunction(
    commandName,
    null
  );
});
```

This `commandName` value is then used for calling the command again from the pipeline
https://github.com/luin/ioredis/blob/master/lib/commander.ts#L110-151
```typescript
...
    // Create a new pipeline and make sure it's scheduled
    return executeWithAutoPipelining(this, commandName, args, callback);
  };
```

At which point the context that it's the Buffer variant of the command (and encoding is null) is lost.

**Comment by mcollina** [comment]
cc @ShogunPanda

**Comment by ShogunPanda** [comment]
I checked the PR. It LGTM!

**Comment by laverdet** [comment]
+1
