### ISSUE TITLE
Error contains password in plaintext

### ISSUE THREAD

**Issue by smartinio** [luin/ioredis#1229]
Hi, I'm using ioredis like this (simplified):
```typescript
import Redis from 'ioredis'

const password = process.env.REDIS_PASSWORD // e.g. 'abc123'
const redis = new Redis({ password })

redis.on('error', (error) => {
  logger.error('Redis error', error)
})
```

Due to a human error, the password used was not the correct one for my service, so ioredis could not connect.
This resulted in the following error:
```typescript
Error {
  command: {
    name: 'auth',
    args: ['abc123']
  }
}
```
Since this error gets emitted and ultimately logged, it ended up in plaintext in my service logs, which for some could equate to a security incident.

I've since made sure to omit`error.command.args` before logging. But is this expected behavior? Is there a better way to handle this?

**Comment by luin** [comment]
Hey Sam, thanks for bringing this to our attention!

To be frank I didn't think about this issue before but it makes sense to avoid logging sensitive data at the library level. I open to any suggestions regarding this.

**Comment by smartinio** [comment]
Hey Luin! Okay, how about this?

### Assuming that the consensus is that *any data* (not just passwords) is potentially sensitive:
Make the existence of `error.command.args` configurable through a flag (e.g. `errorsContainCommandArgs`). This could start as an opt-out, to not break current behavior. If the option is not explicitly set by the user, ioredis can log a warning:

> **[ioredis]** **Command args in errors are deprecated.**
> In the future, command args will not automatically be included in the error object.
> To keep the current behavior, set `errorsContainCommandArgs: true` when configuring ioredis

**Comment by luin** [comment]
Yeah, that sounds reasonable. Can you make a PR for that?

**Comment by smartinio** [comment]
PR is up! :)

**Comment by smartinio** [comment]
@luin Feel free to review #1233 when you have time

**Comment by fmalinowski** [comment]
@luin Hi Zihua, is there a plan to merge #1233 ?
It would be really nice to hide the credentials from the logs when an error occurs.

**Comment by smartinio** [comment]
Closing as I no longer have context on this library. If someone reads this and it is still a problem, open a new issue 👍
