### ISSUE TITLE
ioredis@4.18 or high is not parsing URI properly

### ISSUE THREAD

**Issue by Kikobeats** [luin/ioredis#1230]
This is a thing that happened in the past (#1132) and now I'm trying to figure what's is broken, but the fact is the latest version doesn't work as expected

```
ioredis@4.17 -> works fine
ioredis@4.18 -> doesn't work
ioredis@4.19 -> doesn't work
```

![](https://user-images.githubusercontent.com/2096101/97888050-f9b2ab00-1d2a-11eb-90a4-d421dbc4ef3e.png)

4.17 vs 4.18

**Comment by luin** [comment]
Hi Kiko,

The issue is pretty strange. As @AVVS said we didn't introduce any change related to this part. Can you provide a minimal reproducible example to help us understand the issue? A quick way to do that I can think of is:

```javascript
const redis = new Redis(yourConnectionOptions);
console.log(redis.options); // Will 4.18 give a different result than 4.17?
```

**Comment by Kikobeats** [comment]
Hello,

it was a thing related to a dependency using an ioredis as a dependency

https://github.com/lukechilds/keyv-redis/pull/40

so it isn't an ioredis core thing 🙂

Thanks for the support!
