### ISSUE TITLE
ioredis won't throw errors, prints to console instead - Unhandled error event: Error: connect ECONNREFUSED

### ISSUE THREAD

**Issue by vktrl** [luin/ioredis#1235]
Error handling seems to be broken when trying to query a non-existent database. To reproduce:

```
const Redis = require('ioredis');

const settings = {
  host: "localhost",
  port: 1234 // any invalid port
};

const redis = new Redis(settings);

(async function() {
  try {
    await redis.info()
  } catch (err) {
    // no error is caught, ioredis prints straight to console
    console.log("caught: ", err)
  }
})()
```

Results in console getting flooded with:
```
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
```

Version 4.19.2

**Comment by peteraw77** [comment]
Experiencing the same issue, tried passing a reconnectOnError function but no use

**Comment by peteraw77** [comment]
The proposed solution in #1209 seemed to resolve this for me.

**Comment by vktrl** [comment]
I don't see how this helps. Ioredis should throw an error so I could do something about it.

**Comment by vktrl** [comment]
> The proposed solution in #1209 seemed to resolve this for me.

I don't see how this helps. Ioredis should throw an error so I could do something about it.

**Comment by smartinio** [comment]
@vktrl Redis extends `EventEmitter`, so it doesn't `throw` the error. It `emit`s the error. You need to attach an error handler using e.g:
```typescript
redis.on('error', (e) => doSomething())
```

**Comment by vktrl** [comment]
> @vktrl Redis extends `EventEmitter`, so it doesn't `throw` the error. It `emit`s the error. You need to attach an error handler using e.g:
> 
> ```ts
> redis.on('error', (e) => doSomething())
> ```

Oh, I see, thanks!

**Comment by cope** [comment]
And what can we do in redis.on('error' to make this stop? I tried .disconnect and .quit and nothing helps 😞
