### ISSUE TITLE
The autopipelining reduce the performance by 30% in our benchmark.

### ISSUE THREAD

**Issue by yunnysunny** [luin/ioredis#1239]
We setup a [project](https://github.com/lengyuxuan/redis-benchmark) to test the performance of autopipelining, but found that it reduce the performance by 30%.

**Comment by yunnysunny** [comment]
We found when increase the number of commands in one test loop,  the performance increased.  If you only run one command in one event loop , the performance of using autopipelining is slower. But if you run more commands in one event loop, the performance increase.

**Comment by perry-mitchell** [comment]
@yunnysunny Why did you close this? Were your findings incorrect or did you just not see this issue as being relevant? Interested to know as I'm also seeing poor performance while using auto-pipelining.
