### ISSUE TITLE
duplicate() does not duplicate index selection

### ISSUE THREAD

**Issue by jasonkuhrt** [luin/ioredis#124]
These two clients will be accessing different redis indexes:

```js
let redis = Redis.createClient()
redis.select(5)

let redis2 = redis.duplicate() // This client is using the default index, rather than 5!
```

This was surprising to me. Is there a good justification for this?

**Comment by luin** [comment]
Hi, `Redis#duplicate` only duplicates the options of the Redis. For example the following code should work:

```
let redis = new Redis({ db: 5 })
let redis2 = redis.duplicate()
```

Related code: https://github.com/luin/ioredis/blob/master/lib/redis.js#L318

**Comment by jasonkuhrt** [comment]
Ok I see, thanks.
