### ISSUE TITLE
[Question] Make ioredis connections resilient

### ISSUE THREAD

**Issue by Kikobeats** [luin/ioredis#1241]
Hello,

probably this is a thing that can be achieved right now but I didn't find the way, so I decided to create the issue to get feedback on the current state of the art 🙂

I'm using `ioredis` with a master + replica infrastructure, using it as key/value storage, doing simple `get` and `set` commands.

Sometimes, not too often but definitely a thing that can happen, my Redis instance then to be slow or down for a bit, returning a `connect ETIMEDOUT` error.

https://sentry.io/share/issue/e8ecb95dbd6e4fd1bd231418ea536aa4/

The thing is since Redis is not a critical part of my infrastructure, a best-effort strategy there could be nice.

Ideally, if Redis is not ready to get/set a value, I want to just go ahead without throwing a global error that causes the process to go down completely.

Until now the thing I tried was to wrap `.get` and `.set` into a high-level error to skip the error based on my interests, but since connection error is an internal library thing my error wrapping doesn't work as expected.

Is there a pattern that I can apply here?

**Comment by kapalkat** [comment]
Please check the ioredis docs, all is described there.

You can check my example:

function connectToRedis(redisProps) {
  const redisDefaultProps = {
    host: "127.0.0.1",
    port: "6379",
    db: 1,
    maxRetriesPerRequest: 20,
    retryStrategy(times) {
      console.warn(`Retrying redis connection: attempt ${times}`);
      return Math.min(times * 500, 2000);
    },
  };

  const g_redis = new Redis({ ...redisDefaultProps, ...redisProps });

  g_redis.on("connecting", () => {
    console.log("Connecting to Redis.");
  });
  g_redis.on("connect", () => {
    console.log("Success! Redis connection established.");
  });
  g_redis.on("error", (err) => {
    if (err.name === "MaxRetriesPerRequestError") {
      console.error(`Critical Redis error: ${err.message}. Shutting down.`);
      process.exit(1);
    }
  });
}

**Comment by marcbachmann** [comment]
The `retryStrategy` works well for that.
I suggest to keep the `maxRetriesPerRequest` low to not cause memory issues on non-functional processes. Throwing errors early is better in most cases.
