### ISSUE TITLE
Should the tls option receive a boolean

### ISSUE THREAD

**Issue by sfabriece** [luin/ioredis#1246]
I have seen examples online where the `tls` connection option can be a boolean. 
Should this be added to the type of `tls` if that's the case?

**Comment by dadair-ca** [comment]
I was running into this question as well. For context, it just needs to be a truthy value, so an empty object `{}` works, and is a valid type-match if you are using typescript.

**Comment by luin** [comment]
Sorry for the late response! Although any truthy values work, strickly it should be an object of [options](https://nodejs.org/api/tls.html#tls_tls_createsecurecontext_options) used to create a secure context. So I'd suggest if the default options work for you and you just want to enable tls, `{}` should be used.
