### ISSUE TITLE
Handle never returns if key contains an error

### ISSUE THREAD

**Issue by klodha** [luin/ioredis#125]
Hi,

Just encountered a situation where I was building key using some variables and found that line next to redis.set never get executed as well I don't get any callback from redis. 

My code was like : 

```
app.redis.set('tok:' + user.user_id, function(err, success){
    if(err)
        console.log(err);
    if(success)
        console.log(success);
}

console.log("redis key set");
```

`user` object from which I was trying to access user_id value, was actually null (my flow mistake). However, code written after redis.set (log) never got executed, neither I got any of callback logs. I understand that `user` object being undefined is not an expected situation, however is there some way for redis driver to either raise an error or ignore the 'set' (first would be preferred).

**Comment by luin** [comment]
Hi, access a property(`user_id` here) of a `null` value would lead to an exception and break the application(try the following code). It seems that you wrapped the code with a `try/catch` so you didn't get the exception

```javascript
var Redis = require('ioredis');

var redis = new Redis();
var user = null;

redis.set('tok:' + user.user_id, function (err, success) {
  if(err)
    console.log(err);
  if(success)
    console.log(success);
});

console.log("redis key set");
```

got:

```
ioredis git:master ❯ node test.js                                                                                                                           
/Users/luin/opensource/ioredis/test.js:6
redis.set('tok:' + user.user_id, function (err, success) {
                       ^
TypeError: Cannot read property 'user_id' of null
```
