### ISSUE TITLE
[ioredis] Unhandled error event: ParserError: Protocol error, got "\u0015" as reply type byte. Please report this.

### ISSUE THREAD

**Issue by alexey-ambrozevitch** [luin/ioredis#1262]
Hi, installed 4.17.9 version. Getting the error:

[ioredis] Unhandled error event: ParserError: Protocol error, got "\u0015" as reply type byte. Please report this.
—
(/node_modules/redis-parser/lib/parser.js:190:15)

**Comment by MichielDeMey** [comment]
Was there a resolution to this issue? 🙂

**Comment by ralvarez-globant** [comment]
You are getting a nack, most likely than not your client is using unencrypted against an encrypted server.
Either disable TLS on the server-side (not recommended) or enable encryption on a client basis (download server certificate and reset the connection).
