### ISSUE TITLE
Flush all not working

### ISSUE THREAD

**Issue by RobinSchapendonk** [luin/ioredis#1263]
```
const cluster = new Redis.Cluster([
    {
        port: 6379,
        host: "127.0.0.1",
    },
]);
const databaseOne = new Redis({ db: 0 });
const databaseTwo = new Redis({ db: 1 });

databaseOne.set('x', 'y');

const slaves = cluster.nodes("all");
Promise.all(slaves.map(node => node.flushdb()))

let resOne = await databaseOne.get('x');
message.channel.send(resOne ? resOne : 'none');
```

I tried using `master` and `slave` instead of `all`, but it seems like I can't flush it. What am I doing wrong?

**Comment by luin** [comment]
Sorry for the late response! Did the connection have the permission to flush the database? Or you can run `monitor` on the target node to see whether the command is sent to the node.

Closing this. Feel free to reopen this if there are any issues.
