### ISSUE TITLE
autoPipelining true causes "All keys in the pipeline should belong to the same slots allocation group"

### ISSUE THREAD

**Issue by mohantaylor** [luin/ioredis#1264]
Doing some testing with `autoPipelining` turned on on a cluster with 3 master nodes 3 slaves, we're seeing the error `All keys in the pipeline should belong to the same slots allocation group` being thrown.  As far as I can see the slots cache is successfully refreshed and the shards are well balanced.  Any ideas or thoughts?

Thanks for your help!
Mo

**Comment by Paul-Isache** [comment]
Checked on latest version of ioredis down to 4.19.0, with 3 master and 3 slaves, and I am not able to reproduce it.

Are you still able to reproduce it? If so can you provide additional information like the package version.

**Comment by pietromiottoapl** [comment]
I can confirm this issue happens on version 4.27.9
