### ISSUE TITLE
Any support for 6.2.0 LMOVE ?

### ISSUE THREAD

**Issue by imthatcarlos** [luin/ioredis#1265]
https://redis.io/commands/lmove

**Comment by forgotPassword** [comment]
`zmscore` is also of interest.

#724

**Comment by luin** [comment]
Added in the latest version. Thanks for raising this!

**Comment by apexskier** [comment]
Is this still available in ioredis?

**Comment by luin** [comment]
@apexskier It's available. We don't remove methods unless it's removed from Redis. If you are using TypeScript and it reported an error, then it may be a typing issue that should report on @types/ioredis repo.

**Comment by apexskier** [comment]
Ah, that might be the issue, thanks!
