### ISSUE TITLE
Empty pipeline doesn't resolve when exec() is called

### ISSUE THREAD

**Issue by phlip9** [luin/ioredis#127]
If you create an empty pipeline, it never resolves after calling `exec()`

Here's a failing test case to demonstrate the issue:

```js
// test/functional/pipeline.js
describe('pipeline', function () {
  // ...

  // This test fails with a timeout error
  it('should resolve on an empty pipeline', function(done) {
    var redis = new Redis();
    redis.pipeline().exec(function(err, results) { // This never gets called
      expect(err).to.eql(null);
      expect(results).to.eql([]);
      done(); // This never gets called
    });
  });

  // ...
});
```

A potential solution is checking if `this._queue` is empty in `Pipeline.prototype.exec` and calling `this.resolve([])`. I'm interested to hear any thoughts on this. In particular, whether this should be considered an error, or what the return value should be (an empty array? null? ...?).

Thanks!

**Comment by luin** [comment]
I think we should just return an empty array. Would you like to submit a pull request for this?

**Comment by phlip9** [comment]
Sure, I'll probably get to this later tonight.
