### ISSUE TITLE
ZRANGE with BYSCORE and LIMIT

### ISSUE THREAD

**Issue by wyozi** [luin/ioredis#1271]
Is there a way to do ZRANGE query with BYSCORE and LIMIT, as seen at https://redis.io/commands/zrange?

`ZRANGE myzset (1 +inf BYSCORE LIMIT 1 1 `

**Comment by luin** [comment]
All arguments supported by Redis can be passed as it is to ioredis, so it will look like: `ioredis.zrange('myzset', '(1', '+inf', 'BYSCORE', 'LIMIT', '1', '1')`. Lmk if there are any issues about the usage.
