### ISSUE TITLE
send event when redis machine shutdown

### ISSUE THREAD

**Issue by vskavgaci** [luin/ioredis#1276]
Hi,

i am using ioredis with nuxt.js. i used every event on ioredis (error, close etc) in documentation but couldn't throw error when redis server shutdown.  nothing happening when shutdown redis machine and my app not responding becuse of that.

do you have any suggestion about that problem?

**Comment by Aung-Myint-Thein** [comment]
the nodejs application will exit if the connection has error. I am also still trying to catch the error and fail gracefully but still not available yet...

**Comment by luin** [comment]
Hi @vskavgaci , there should be events when redis server is down. Namely there should be "error" and "close".

```javascript
const redis = new Redis(6399);

redis.on("error", console.error.bind(console, "error"));
redis.on("close", console.error.bind(console, "close"));
```

The above code works for me.

@Aung-Myint-Thein Can you upgrade to the latest version and see if the issue still exists?

Closing this, feel free to reopen if there are still issues.
