### ISSUE TITLE
Pub/Sub example in docs is confusing

### ISSUE THREAD

**Issue by akatechis** [luin/ioredis#1282]
Not sure if it was just me misreading it, but I feel like the pub/sub sample code is a bit confusing.

The sample code shows a call to `subscribe()`, with a pair of `publish` on a different connection inside the callback.
Then, in the top level scope it calls `.on('message', ...)` to listen for messages which it receives from the two publishes inside the `subscribe` callback.

In my case, I was writing two programs in a producer/consumer setup, where producer is simply calling `publish` in a loop, and the consumer was calling `conn.on('message',...)` to listen. However, this isn't enough, because you need to put the connection into subscriber mode, in order to receive messages by calling `.subscribe(topic)`.

**My confusion: I didn't realize .on() requires calling .subscribe() first.**

Proposed solution:
Split the pub from the sub portion of the code, so that someone setting up IPC via redis pub/sub will understand which portions of code are needed for each component:

```js
// consumer.js
// listens for messages on the queue
redis.subscribe(QUEUE_NAME)
redis.on('message', (channel, message) => {
  console.log(`[recv] ${channel} ${message}`)
})
```

```js
// producer.js
// produces messages on the queue
async function main () {
  let i = 1
  while (true) {
    const event = {
      foo: i,
    }
    console.log('Pushing event: ', event)
    redis.publish(QUEUE_NAME, JSON.stringify(event))
    i += 1
    await sleep()
  }
}

main()

function sleep () {
  return new Promise(resolve => {
    setTimeout(() => resolve(), 300)
  })
}
```

Running these snippets as 2 separate programs will more clearly demonstrate how processes can publish/subscribe to a channel.

**Comment by luin** [comment]
Hi Alexandros, thanks for raising this up! I updated the documentation as you suggested. Lmk if there is anything unclear.

**Comment by akatechis** [comment]
Looks great! Thanks for the awesome package, BTW 😄
