### ISSUE TITLE
the wiki have to be updated

### ISSUE THREAD

**Issue by EwenQuim** [luin/ioredis#1291]
It hasn't been updated since 2016 and some information isn't true anymore.

For example the sentence "For compatibility, ioredis supports `var redis = Redis.createClient()` as well" isn't true anymore since it's deprecated as [explained in the API doc](https://github.com/luin/ioredis/blob/master/API.md#Redis.createClient), and this can be misleading.

I personally can't change this, that's why I'm raising this issue, I would have been happy to correct it myself otherwise :)

Thank you

**Comment by luin** [comment]
Hi, thanks for raising this! I've made some changes. LMK if there are anything missing.

**Comment by EwenQuim** [comment]
Thank you very much ! I close the issue because I didn't encounter any other problems.
