### ISSUE TITLE
每次调用 new redis后 连接数就增加  quit() 也貌似不起作用

### ISSUE THREAD

**Issue by Messilimeng** [luin/ioredis#1294]
![image](https://user-images.githubusercontent.com/12272166/110075124-4aabdc00-7dbd-11eb-84fc-3f7db07cd814.png)

**Comment by luin** [comment]
Hey @Messilimeng, can you provide a minimal reproducible example (the code, how you observe the connection count increasing) so I can test on my side?

你好，可以提供一个最小可重现例子（包含代码和怎么观察到的连接数增加）吗？我在本地试试。

**Comment by Messilimeng** [comment]
@luin 你好 我检查了一下代码 是我写的有问题 有的地方遗漏quit了
