### ISSUE TITLE
Seeing redis connections growing rapidly

### ISSUE THREAD

**Issue by dodozhang21** [luin/ioredis#1295]
Hi, is there a way to keep the connection persistent using this lib? I'm currently instantiating the ioredis via

```
new RedisClient.Cluster([
        {
          port: redisPort || 6379,
          host: redisHost,
        },
      ],
      {
        scaleReads: 'slave',
      });
```
We are only instantiating this once but the connections to redis grow rapidly on our server.

Do you have any insights on what we could do to minimize the connections to redis?

**Comment by luin** [comment]
The easiest way would be enabling the debug mode in the development env like `DEBUG=ioredis:* node yourapp`. That will log all details about connection creations and destructions.

**Comment by luin** [comment]
Closing this. Feel free to reopen this if there are any issues.
