### ISSUE TITLE
expire/ttl

### ISSUE THREAD

**Issue by tiefenb** [luin/ioredis#130]
does ioredis support expire and ttl?

http://redis.io/commands/expire
http://redis.io/commands/ttl

**Comment by AVVS** [comment]
it does

**Comment by tiefenb** [comment]
can you give me an code example? i didnt found this functions in the
documentation

Am Freitag, 14. August 2015 schrieb Vitaly Aminev :

**Comment by AVVS** [comment]
all the commands are exactly the same as in the redisio docs on their website

redis.expire(...)
redis.ttl(...)

last arg is callback, if its not - then promise is returned

**Comment by tiefenb** [comment]
thanks!

**Comment by vipreshjha** [comment]
redis.expire command takes the time in Seconds or Milliseconds?
Would be nice if this was also documented somewhere.

**Comment by dirkbonhomme** [comment]
It's using the exact same arguments as Redis does: https://redis.io/commands/expire
So for `expire` it appears to be seconds
