### ISSUE TITLE
CommandQueue starts to grow and redis calls become slow

### ISSUE THREAD

**Issue by aetheon** [luin/ioredis#1300]
Hi there,

I’ve an app running in kubernetes and sometimes I get one pod that becomes very slow to respond. After debugging the problem was traced to redis calls that start to take >5sec. All other pods run just fine while this rogue pod is having problems, and aws elasticcache looks fine.

I’ve enabled auto pipeline but that doesn’t help. The problem is not reproducible, I can provide more details if needed.

Has this issue been reported or does anyone has a debugging suggestion? Tks

**Comment by luin** [comment]
Hi Oscar,

Generally, I think the first step is to confirm whether the growth of CommandQueue size is a cause or a consequence.

If it's a cause, a possibility is there were network issues causing the backlog in the queue. If it's a consequence, could there be other issues in the app that slowed the app down (like memory leaking can make the app busy with GC), making the app too busy to receive Redis replies?

**Comment by aetheon** [comment]
Hi @luin ,

I’ve got heap dumps and cpu profiles and everything looks ok from the node process.

Also, ran redis latency checks in the rogue pod, checked redis slow log and all looks good too. Running redis big keys doesn’t show anything that could clog the downlink.

As mitigation I’m doing a connection restart if the queue averages a certain level and restarting the connection fixes it for a while and the issue sometimes reappear.

My next step is to add artificial js timeouts and fallback to DB as redis is used as a cache, but I’m not sure this will help.

I’m sort of running out of ideas and will start to blame the AWS spot instances, bandwidth, ... 😂

Feel free to close the issue as I have no proof it’s ioredis related. Will welcome any feedback. Tks

**Comment by luin** [comment]
Closing this. Good luck with your debugging! Lmk if there are any updates.

**Comment by aetheon** [comment]
Hi there,

Just an update in case somebody hits the same problem and google this.

Manage to stabilise the system by increasing the number of pods in the system. I haven't figure out the actual problem but my guess is that the rogue pod is not able to handle the traffic and hits some redis connection ceiling. By increasing the number of pods it reduces the traffic in each pod, fixing the issue for now.

My next steps is to create a redis connection pool to leverage pod resources and reduce the need for such a high number. 

Also, an artificial js timeout will be added to let the code fallback to DB if redis takes more than X time to respond. I which there was a better way to achieve connection timeouts and clear the streams.

Tks for the quick triage and response.
