### ISSUE TITLE
Redis.Cluster can't mocked by Jest

### ISSUE THREAD

**Issue by icebob** [luin/ioredis#1308]
Hello,

I struggle with an issue in my unit tests (where Jest mock the ioredis classes) with the latest v4.24.3 version.
In the previous versions the following unit tests pass:
```js
jest.mock("ioredis");

const Redis = require("ioredis");

describe("Test Redis", () => {
	it("create Redis instance", () => {
		const client = new Redis();
		expect(client).toBeInstanceOf(Redis);
		expect(Redis).toBeCalledTimes(1);
	});

	it("create Redis Cluster instance", () => {
		const client = new Redis.Cluster();
		expect(client).toBeInstanceOf(Redis.Cluster);
		expect(Redis.Cluster).toBeCalledTimes(1);
	});
});
```
**Result**
![image](https://user-images.githubusercontent.com/306521/112196360-41b76900-8c0b-11eb-9428-75c4a667476d.png)

But with v4.24.3 I've got errors for the same tests:
![image](https://user-images.githubusercontent.com/306521/112196555-71667100-8c0b-11eb-90a4-a45f025c0a7b.png)

Do you have any idea what is the problem and how can I fix it? Thanks in advance.

**Comment by luin** [comment]
Hi @icebob, what was the ioredis version in the first screenshot?

**Comment by icebob** [comment]
v4.24.2, the previous version.

**Comment by icebob** [comment]
In the meantime, I'm trying debugging the issue and I think the problem comes from this changes: https://github.com/luin/ioredis/commit/bf3fe29ec78df184b359ee29468dbb058e886e59#diff-d5a4b3a0309f2337144861084c1014523cced561eb722cb9684c63f5e41e0567
Because in the compiled JS the `Cluster` changed to a getter and it seems Jest can't traverse the getters.
![image](https://user-images.githubusercontent.com/306521/112199671-ae803280-8c0e-11eb-8d9e-a206e2698755.png)

**Comment by icebob** [comment]
It was quick, thanks @luin, I really appreciate it. Now it works fine.

**Comment by ihsa-tomas** [comment]
I have the same problem with the Redis constructor

![image](https://user-images.githubusercontent.com/77495884/113933667-42372e80-97cb-11eb-8652-fcc1cff966e9.png)

**Comment by tomijais** [comment]
I have the same problem with the Redis constructor in the new version

![image](https://user-images.githubusercontent.com/29215699/113934522-3dbf4580-97cc-11eb-8554-13a17d9056e4.png)
