### ISSUE TITLE
Question sentinel slave

### ISSUE THREAD

**Issue by DarkSorrow** [luin/ioredis#131]
Hello,

I read that when sentinel is used and we put role: 'slave', ioredis will try to connect to the slave available but what happen if no slave is available and only the master is, will ioredis use the master to make its read or will it wait until a slave comes back online? In the case where there is one slave for the master waiting for the slave will stop the ioredis instance for reading anything right?

**Comment by luin** [comment]
If there's no slave available and the `role` option is set to the `'slave'`, then ioredis would retry to reconnect to the sentinel and fetch the slaves info again or just reject with an error according to the value of the `sentinelRetryStrategy` option(Check out README.md for more information). ioredis would never connect to the master when `role` is `slave`.

**Comment by DarkSorrow** [comment]
Would it be bad you think to have an option that would let it log to a master while no slave is available but still try to relog to a slave using the sentinelRetryStrategy to connect to the slave once its available?
Because in case the slave are unavailable application that were just reading from slave won't be able to work anymore. Maybe have an option like 'enforceRole = false'?

**Comment by luin** [comment]
I prefer to implementing this logic on the client side since it's not hard.

**Comment by tangxinfa** [comment]
I already implementing it, see https://github.com/tangxinfa/ioredis_sentinel_connector
# ioredis_sentinel_connector

Best efforts on connect slave with ioredis's SentinelConnector.


WARNING: This module will change the prototype of ioredis's SentinelConnector.


There is no difference when role is "master", but for "slave" following the order:

1. Local slave.

2. Master if no slaves.

3. Local master.

4. Remote slave.
