### ISSUE TITLE
Pipelining custom commands error

### ISSUE THREAD

**Issue by Jav3k** [luin/ioredis#1313]
```js
const res = await redisClient.pipeline([['ft.search', 'idx:cache', '*']]).exec();
```

will cause error:
```
TypeError: Cannot read property 'apply' of undefined
    at Pipeline.addBatch (node_modules/ioredis/built/pipeline.js:192:27)
    at Redis.redis.pipeline (node_modules/ioredis/built/transaction.js:10:22)
    at main (index.ts:109:37)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
```
because Pipeline class does not have 'ft.search' command:
https://github.com/luin/ioredis/blob/afd0c8766c2579b29f6dfa54082f3a8d47939c51/lib/pipeline.ts#L210

"ioredis": "4.24.5",
"@types/ioredis": "4.22.1"

----
duplicate of https://github.com/luin/ioredis/issues/946
but closed

How to pipeline custom commands?

**Comment by luin** [comment]
Hey @Jav3k ,

There's a `call` method that is used to call arbitrary commands. Ex `redis.call('ft.search', 'idx:cache', '*')`. So in a pipeline it should be `redis.pipeline.call('ft.search', 'idx:cache', '*').exec();`

**Comment by Jav3k** [comment]
Thank you. I forgot about call method
