### ISSUE TITLE
[Question] Removing multiple entries using SREM in ioredis?

### ISSUE THREAD

**Issue by kkocel** [luin/ioredis#1317]
I wonder what is the correct syntax to use in order to remove multiple entries using SREM command.

When I call:

```ts
const myKey = "myKey";
const entriesToRemove: string[] = ...

this.redisClient.srem(myKey, entriesToRemove);
```

I get:

`ReplyError: ERR wrong number of arguments for 'srem' command`

**Comment by luin** [comment]
The code is valid. What's the redis version? `SREM` only supports removing multiple entries after 2.4. See more: https://redis.io/commands/srem#history

**Comment by kkocel** [comment]
@luin I use version 6.2.1

**Comment by luin** [comment]
Can you try on redis-cli? The following code works for me:

```javascript
const myKey = "myKey";
const entriesToRemove = ['a', 'b']

redis.srem(myKey, entriesToRemove, console.log);
```

**Comment by kkocel** [comment]
@luin it turns out that this command fails if `entriesToRemove` is empty. I added a check for this before calling `srem`. So I'm closing this!
