### ISSUE TITLE
transaction和pipeline为何回调的机制不一样？

### ISSUE THREAD

**Issue by bluekylin** [luin/ioredis#133]
transaction的回调是queued，好像没有必要，可以在exec中自动调用吗？这样就不用处理queued了

**Comment by luin** [comment]
queued 是什么意思？

**Comment by luin** [comment]
哦啊，transaction 是基于 pipelining 的，每个子命令的回调函数都是返回命令本身的结果。multi 中的子命令结果是命令加入的状态，即 QUEUED 或者 error。这样可以使接口保持统一

**Comment by bluekylin** [comment]
请问transaction的回调函数可以返回命令本身的结果吗？因为实际应用中返回QUEUED没有使用价值，更多的应用是需要命令的结果，否则我们需要在exec的回调函数里去操作results数组，而此时，我们通常不知道transaction的顺序，为此我们需要维护额外一个数组来知道是哪些transaction。是否transaction和pipeline能行为一致？是否可以在multi的exec的回调之前，依次回调每个transaction对应的回调函数？

**Comment by luin** [comment]
嗯嗯我明白你的意思。现在的表现主要是考虑到下面几个因素：

0. 保持接口和 node_redis 兼容；
1. transaction 是基于 pipelining 的，所以返回 QUEUED 是默认的表现，如果修改的话会造成表现不一致；
2. QUEUED 本身是有意义的，这样可以知道一个命令是否成功地被加入到了 transaction 中（如果返回一个错误的话则表示加入失败）；
3. 在 exec 中处理结果大部分情况下并不特别麻烦；

**Comment by bluekylin** [comment]
好的，非常感谢您的解答！
