### ISSUE TITLE
Steams: XGROUP CREATE requires stream to exist 

### ISSUE THREAD

**Issue by rdx95** [luin/ioredis#1332]
XGROUP CREATE Requires a stream to exist.
 It appears that using XGROUP CREATE with stream key that does not exist results in an ERR no such key.

I propose that either:

- XGROUP CREATE should create the key if it does not exist, or
- There should be way to create an empty stream without having to use XADD (which, AFAIK, there is not right now)

**Comment by luin** [comment]
Hi, the issue is out of the scope of ioredis. ioredis is a Node.js client for Redis. I think you may want to create an issue on redis repo? Having said that, there is an argument `MKSTREAM` for the XGROUP command that does exactly as you proposed.

**Comment by rdx95** [comment]
Thank You
