### ISSUE TITLE
nodejs logs getting clobbered with 'ENOTFOUND' errors

### ISSUE THREAD

**Issue by jayceekay** [luin/ioredis#1333]
version stuff:
```
$ npm ls -L 0 ioredis | rg ioredis
│ └── ioredis@4.26.0 deduped
└── ioredis@4.26.0

$ node -v
v12.13.1
```

running a local redis with this:
`$ redis-server /usr/local/etc/redis.conf --loglevel debug` 

start my app, which is simply doing:
`new Redis()` 

tailing the log shows this:
```
32196:M 09 Apr 2021 04:48:42.620 - Accepted 127.0.0.1:51093
32196:M 09 Apr 2021 04:48:43.441 . 1 clients connected (0 replicas), 1080528 bytes in use
```

but my node script is showing this in stdout:
```
< [ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND 127.0.0.1:6379
<     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26)
```
and it's clobbering it every second or so. no disconnect logs are coming through on the redis-server side. any ideas?

i've tried using `{ lazyConnect: true, connectTimeout: 10000 }` but no go.

**Comment by luin** [comment]
The error indicates the address 127.0.0.1:6379 is not reachable (seems you included the port in the host part). You may want to disable auto-reconnect: https://github.com/luin/ioredis#auto-reconnect

**Comment by jayceekay** [comment]
you're right. that was an errant piece of code. apologies. thank you for the amazing piece of software!
