### ISSUE TITLE
Record<string, string> type problem

### ISSUE THREAD

**Issue by paperfella-ceo** [luin/ioredis#1334]
Hello. I'm using Typescript. I've installed `@types/ioredis` package without problems. But it looks like that `hgetall` method returns a type `Record<string, string>` instead of an object containing my interface's fields.
![image](https://user-images.githubusercontent.com/78665890/114243891-d1774a00-9963-11eb-937b-b33e59111e22.png)
![image](https://user-images.githubusercontent.com/78665890/114243651-50b84e00-9963-11eb-878a-98e7d96b2efb.png)

**Comment by BensonBen** [comment]
As far as I know you can't guarantee that the key value pairs returned by Redis will contain the corresponding pairs for your User object. Therefore, `Record<string, string>` is the most correct we can get when using Redis. I suggest you implement up-casting then down-casting like so. `(await redis.hgetall('myKey')) as unknown as User` to get the type error to go away, but introducing a transformation step into your code is typically the way to handle database access when you don't know what you're getting back form redis.

**Comment by luin** [comment]
Thanks for the explanation @BensonBen ! I think we can close this.
