### ISSUE TITLE
Error: All sentinels are unreachable. Retrying from scratch after 100ms. Last error: ERR unknown command `sentinel`, with args beginning with: `get-master-addr-by-name`, `mymaster`,

### ISSUE THREAD

**Issue by nupurrajal** [luin/ioredis#1338]
I'm trying to establish a connectivity but getting error -
Debug log:

_ioredis:redis status[localhost:6379]: [empty] -> connecting +0ms
  ioredis:redis status[127.0.0.1:5000]: [empty] -> connecting +2ms
  ioredis:redis queue command[127.0.0.1:5000]: 0 -> sentinel([ 'get-master-addr-by-name', 'mymaster' ]) +0ms
body-parser deprecated undefined extended: provide extended option index.ts:28:27
⚡️[server]: Server is running at port=8000
  ioredis:redis queue command[localhost:6379]: 0 -> del([ 'last_successful_cache_build_time' ]) +54ms
  ioredis:redis status[127.0.0.1:5000]: connecting -> connect +2ms
  ioredis:redis status[127.0.0.1:5000]: connect -> ready +0ms
  ioredis:connection send 1 commands in offline queue +0ms
  ioredis:redis write command[127.0.0.1:5000]: 0 -> sentinel([ 'get-master-addr-by-name', 'mymaster' ]) +1ms
  ioredis:SentinelConnector failed to connect to sentinel 127.0.0.1:5000 because ERR unknown command `sentinel`, with args beginning with: `get-master-addr-by-name`, `mymaster`,  +0ms
  ioredis:redis status[127.0.0.1:5002]: [empty] -> connecting +3ms
  ioredis:redis queue command[127.0.0.1:5002]: 0 -> sentinel([ 'get-master-addr-by-name', 'mymaster' ]) +0ms
  ioredis:redis status[127.0.0.1:5002]: connecting -> connect +2ms
  ioredis:redis status[127.0.0.1:5002]: connect -> ready +0ms
  ioredis:connection send 1 commands in offline queue +6ms
  ioredis:redis write command[127.0.0.1:5002]: 0 -> sentinel([ 'get-master-addr-by-name', 'mymaster' ]) +0ms
  ioredis:SentinelConnector failed to connect to sentinel 127.0.0.1:5002 because ERR unknown command `sentinel`, with args beginning with: `get-master-addr-by-name`, `mymaster`,  +3ms
  ioredis:redis status[127.0.0.1:5003]: [empty] -> connecting +12ms
  ioredis:redis queue command[127.0.0.1:5003]: 0 -> sentinel([ 'get-master-addr-by-name', 'mymaster' ]) +0ms
  ioredis:redis status[127.0.0.1:5000]: ready -> close +1ms
  ioredis:connection skip reconnecting since the connection is manually closed. +13ms
  ioredis:redis status[127.0.0.1:5000]: close -> end +0ms
  ioredis:redis status[127.0.0.1:5003]: connecting -> connect +1ms
  ioredis:redis status[127.0.0.1:5003]: connect -> ready +0ms
  ioredis:connection send 1 commands in offline queue +1ms
  ioredis:redis write command[127.0.0.1:5003]: 0 -> sentinel([ 'get-master-addr-by-name', 'mymaster' ]) +0ms
  ioredis:SentinelConnector failed to connect to sentinel 127.0.0.1:5003 because ERR unknown command `sentinel`, with args beginning with: `get-master-addr-by-name`, `mymaster`,  +13ms
  ioredis:SentinelConnector All sentinels are unreachable. Retrying from scratch after 10ms. Last error: ERR unknown command `sentinel`, with args beginning with: `get-master-addr-by-name`, `mymaster`,  +1ms
 ERROR
 Error: All sentinels are unreachable. Retrying from scratch after 10ms. Last error: ERR unknown command `sentinel`, with args beginning with: `get-master-addr-by-name`, `mymaster`,_ 

I can see that in beginning it's also trying to connect to port #6379.

Code snippet:

```
const Redis = require("ioredis");
const redis = new Redis({
        sentinels: [{
            port: 5000,
            host: "127.0.0.1"
        },
        {
            port: 5002,
            host: "127.0.0.1"
        },
        {
            port: 5003,
            host: "127.0.0.1"
        }],
        name: "mymaster",
    },
    {
        scaleReads: "slave"
    }
);
  
redis.on("error", function(err) {
    if (err) {
        logger(err, loggingEnum.ERROR);
    }
});
```

**Comment by luin** [comment]
Hey @nupurrajal , thanks for using ioredis.

The error `ERR unknown command sentinel` indicates that the node `127.0.0.1:5000` is not a valid Redis sentinel instance. You can verify that via `redis-cli -p 5000 sentinel`.

**Comment by nupurrajal** [comment]
Thank you. I changed the configuration.

**Comment by akshatBais** [comment]
> Thank you. I changed the configuration.
Hello , Can you please help me with configurations ? I am running redis on local and my strapi by defualt connects to 127.0.0.1:6379 , however I did this in middleware.js file it works , but then it doesn't work inside the docker .

here are the code samples : 

middleware.js
`const Redis = require("ioredis");
const redis = new Redis({
    port : 6378,
    host: "127.0.0.1"
})
module.exports = ({ env }) => ({
    settings: {
        cache: {
            enabled: true,
            type: 'redis',
            maxAge: 3600000,
            redisConfig: redis
          }
    }
  });`

docker-compose

`version: "3"
services:
  cms:
    container_name: cms
    image: cms
    networks:
      - strapi-app-network
    ports:
      - 1337:1337
    links:
      - "redis"
    depends_on: 
      - "redis"
  redis-server:
    image: redis
    container_name: redis-cache
    networks:
      - strapi-app-network
networks:
  strapi-app-network:
    driver: bridge
 
  `

**Comment by maxymapp** [comment]
shot in the dark: pass `password` to redis itself in your IORedis({}) config, even if you use Sentinel.
