### ISSUE TITLE
when `keepAlive` parameter is set, the TCP keep-alive is enabled but the specified timeout is not applied

### ISSUE THREAD

**Issue by ArnoldZokas** [luin/ioredis#1339]
**ioredis version:** 4.26.0
**Node.js version:** 14.16.1
**OS**: Ubuntu 18.04.3 LTS

Setting the `keepAlive` option enables the TCP keep-alive mechanism but does not apply the specified timeout.

This can be reproduced with:
```js
const Redis = require("ioredis");

const redis = new Redis({
  host: 'localhost',
  keepAlive: 30000, // should set socket option TCP_KEEPIDLE=30
});

redis.on('connect', () => {
  console.log('Connected!');
});
```

Running [`knetstat`](https://github.com/veithen/knetstat) to inspect socket options shows the socket was created with `TCP_KEEPIDLE=60` (which is the Node.js default):
```shell
$ cat /proc/net/tcpstat
Recv-Q Send-Q Local Address   Foreign Address  Stat Diag Options
     0      0 127.0.0.1:40792 127.0.0.1:6379   ESTB      SO_REUSEADDR=0,SO_REUSEPORT=0,SO_KEEPALIVE=1,TCP_KEEPIDLE=60,TCP_KEEPCNT=10,TCP_KEEPINTVL=1,TCP_NODELAY=1,TCP_DEFER_ACCEPT=0
```
---
This is likely due to `socket.setKeepAlive()` being called after the connection has been established.
To test this I have created a socket and tried calling `socket.setKeepAlive()` before and after calling `socket.connect()`.

When `socket.setKeepAlive()` is called **before** `socket.connect()`:
```js
const net = require('net');

const socket = new net.Socket();

socket.setKeepAlive(true, 10000);

socket.connect({
  host: 'localhost',
  port: 6379,
});

socket.on('connect', () => {
  console.log('Connected!');
});
```

`knetstat` reports `TCP_KEEPIDLE=10` - keep-alive is enabled and the correct timeout is applied

---
When `socket.setKeepAlive()` is called **after** `socket.connect()`:
```js
const net = require('net');

const socket = new net.Socket();

socket.connect({
  host: 'localhost',
  port: 6379,
});

socket.setKeepAlive(true, 10000);

socket.on('connect', () => {
  console.log('Connected!');
});
```

`knetstat` reports `TCP_KEEPIDLE=60` - keep-alive is enabled but the Node.js default timeout is applied

**Comment by marcbachmann** [comment]
Thanks for the investigation. I think the cause of that issue is https://github.com/nodejs/node/issues/31663
