### ISSUE TITLE
sentinel 要求redis必须 >= 2.8.12 

### ISSUE THREAD

**Issue by pangnate** [luin/ioredis#134]
看到文档写了一句 sentinel 要求 redis 必须 >= 2.8.12 ，是否一定？实测发现在 2.8.8 上的确没有效果，也不报错。这么好的模块，用不了，泪奔！redis 从 2.8 开始支持sentinel ，作者是否考一下？

**Comment by luin** [comment]
是的，只支持 2.8.8。Redis Sentinel 2 确实是 Redis 2.8 发布的，但是 2.8.12 修复了非常多的 Sentinel 问题，可以说 Sentinel 在 2.8.12 前是有问题的。所以 ioredis 只支持 2.8.12。

大部分 Sentinel 功能都能正常的在 2.8.12 前的版本运行，但是 failover 会有问题。

**Comment by kunth** [comment]
我的测试是在redis 2.8.11上，sentinel可以做failover。大概测过百来个case没出现问题。但是在做failover的时候，sentinel将slave提升为master的时间比较长，大概在31s+（从原master挂掉到原slave的状态变为master的时间）。

**Comment by luin** [comment]
31s 的话可能是因为 `sentinel down-after-milliseconds mymaster 30000` 的配置原因，默认 30s 后 redis 才会认为 master 坏掉了。
