### ISSUE TITLE
[Question] Why is the first request always longer than the rest

### ISSUE THREAD

**Issue by ngoxuangiang** [luin/ioredis#1342]
Hello,
I have written a simple code (nodejs) as below

```
async function test() {
    console.log(moment().format('D MMM HH:mm:ss.SSS'), "=============>START");
    for (let index = 0; index < LOOP; index++) {
        await ioredis.get("ioredis:string");
    }
    console.log(moment().format('D MMM HH:mm:ss.SSS'), "=============>DONE", found);
}
setInterval(() => {
    test()
}, 1000);
```

Output:
22 Apr 21:37:13.009 =============>START
22 Apr 21:37:13.050 =============>DONE         (41ms)

22 Apr 21:37:15.011 =============>START
22 Apr 21:37:15.032 =============>DONE         (21ms)

22 Apr 21:37:17.018 =============>START
22 Apr 21:37:17.046 =============>DONE         (28ms)

22 Apr 21:37:19.023 =============>START
22 Apr 21:37:19.048 =============>DONE         (25ms)

I see, the result between LOOP = 1 and LOOP = 100 does not differ much.
And I've noticed that the first request always takes 15-20ms, the following requests are very fast.
Can anyone explain to me why this is happening? 
And how to make every request have response time <1ms?

Thanks everyone.

**Comment by tugrul512bit** [comment]
Isn't this about Javascript engine optimizing things while running? In all benchmarks first step always takes biggest time. 

Also for the sub millisecond query, did you try caching?
