### ISSUE TITLE
Support for GET option in SET command

### ISSUE THREAD

**Issue by iatsiuk** [luin/ioredis#1354]
Are there any plans for adding support for new GET option in SET command?

It was added in redis version 6.2.

Documentation [link](https://redis.io/commands/set).

**Comment by luin** [comment]
Hey @iatsiuk , have you tried `redis.set('foo', 'bar', 'GET')`? It should work as expected as long as the server is >= 6.2.

**Comment by iatsiuk** [comment]
Hi @luin , here is my test code:

`
const Redis = require("ioredis");

const client = new Redis("localhost:16379");

(async () => {
  const info = await client.info();

  console.log(info.match(/redis_version.+$/m)[0]);

  await client.set("foo", "bar", "PX", 100, "NX", "GET");
})();
`

Here is my output:

`
% node ./index.js
redis_version:6.2.2
/Users/me/Devzone/redis-test-get/node_modules/redis-parser/lib/parser.js:179
    return new ReplyError(string)
           ^

ReplyError: ERR syntax error
    at parseError (/Users/me/Devzone/redis-test-get/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/Users/me/Devzone/redis-test-get/node_modules/redis-parser/lib/parser.js:302:14) {
  command: { name: 'set', args: [ 'foo', 'bar', 'PX', '100', 'NX', 'GET' ] }
}
`

Am I miss something?

**Comment by luin** [comment]
I think the reason is just the syntax is not accepted by Redis. ioredis doesn't do any magic things but just pass arguments to Redis directly. You may want to try on redis-cli first to confirm whether the syntax is correct or not. Remove `PX` and `NX` works for me.

**Comment by iatsiuk** [comment]
Looks like combination of options NX and GET are not allowed.

```
127.0.0.1:6379> set foo1 bar PX 500 NX
OK
127.0.0.1:6379> set foo1 bar PX 500 XX GET
(nil)
127.0.0.1:6379> set foo1 bar PX 500 NX GET
(error) ERR syntax error
127.0.0.1:6379>
```

Thanks for your help!
