### ISSUE TITLE
Garbage data returned by getBuffer when enableAutoPipelining is set to true.

### ISSUE THREAD

**Issue by rahbaner** [luin/ioredis#1356]
It has been observed that when enableAutoPipelining is set to true, getBuffer returns garbage data. When I set enableAutoPipelining to false, getBuffer returns proper data.

Would it be possible to have a look at this? Looks like PR https://github.com/luin/ioredis/pull/1231 fixes this. Can this be merged if it look ok @luin ? If there is an alternate way you plan to fix this, that is also perfectly fine. Just needed to for reducing load on redis cluster (so that I dont need to do JSON.stringify on compressed data before setting it to redis.).

**Comment by luin** [comment]
Closed via #1231. Thanks for the heads up!

**Comment by rahbaner** [comment]
Thanks a lot @luin. This indeed works fine.
