### ISSUE TITLE
Cannot use send_command function using "Cluster"

### ISSUE THREAD

**Issue by danitseitlin** [luin/ioredis#1365]
I am attempting to use the send_command under the "Cluster" interface and it seems like it's not defined in the type.

I tried doing:
```
const cluster = new IORedis.Cluster(this.redisOptions);
await cluster.send_command(....);
```

I get the error:
```
Property 'send_command' does not exist on type 'Cluster'. Did you mean 'sendCommand'?
```

**Comment by danitseitlin** [comment]
@luin Can you give me some input on how to fix this or if it's fixable at all?

**Comment by luin** [comment]
Hey @danitseitlin, that sounds like an issue on @types/ioredis side. `send_command` does exist on Cluster though what you may want to use is `Cluster#call` (ex cluster.call('set', 'foo', 'bar')) as `send_command` is used internally and expected slot information of the command.

**Comment by danitseitlin** [comment]
@luin Should it be here: https://github.com/luin/ioredis/blob/master/lib/cluster/index.ts?

**Comment by danitseitlin** [comment]
@luin PING
