### ISSUE TITLE
Add User & Pass in Redis.Cluster

### ISSUE THREAD

**Issue by rupamking1** [luin/ioredis#1367]
const Redis = require("ioredis");

const cluster = Redis.Cluster([
  {
    port: 6380,
    host: "127.0.0.1",
  }, 
  {
    port: 6381,
    host: "127.0.0.1",
  },
]);

how to add username & password in Redis.Cluster([
  {
    port: 6380,
    host: "127.0.0.1",
  },

**Comment by erhangundogan** [comment]
https://redis.io/commands/auth
https://github.com/luin/ioredis/blob/master/lib/redis/RedisOptions.ts#L18
```js
const redis = new Redis.Cluster(
[
  {
    host: 127.0.0.1,
    port: 6379
  }
],
{
  redisOptions: {
    username: 'user',
    password: 'pass'
  }
});
```

**Comment by luin** [comment]
Closing as the solution mentioned by @erhangundogan should work.
