### ISSUE TITLE
6.2 commands (getex etc)

### ISSUE THREAD

**Issue by arcanis** [luin/ioredis#1374]
Redis 6.2 seems to [introduce](https://redislabs.com/blog/redis-6-2-the-community-edition-is-now-available/) a bunch of new commands such as [`getex`](https://redis.io/commands/getex), but they don't seem to be exposed by ioredis just yet.

**Comment by markschmid** [comment]
Indeed, I need [```copy```](https://redis.io/commands/copy)
In [v.4.21.0](https://github.com/luin/ioredis/releases/tag/v4.21.0) it says it introduced these commands.

But even with latest version of ioredis, I get 
```
ReplyError: ERR unknown command `copy`
```

**Comment by gaoyingpei** [comment]
[`zmscore`](https://redis.io/commands/zmscore) and [`zrandmember`](https://redis.io/commands/zrandmember) are not supported too.

**Comment by TysonAndre** [comment]
https://github.com/NodeRedis/redis-commands/issues/40 should have fixed that in 4.21.0. The latest ioredis release is using redis-commands 1.7.0, which supports zmscore

> ReplyError: ERR unknown command `copy`

I'm guessing that sounds like an error from the server (it's a **reply** error) - are you sure your redis server is actually 6.2.0+ https://redis.io/commands/copy

**Comment by gaoyingpei** [comment]
> [NodeRedis/redis-commands#40](https://github.com/NodeRedis/redis-commands/issues/40) should have fixed that in 4.21.0. The latest ioredis release is using redis-commands 1.7.0, which supports zmscore
> 
> > ReplyError: ERR unknown command `copy`
> 
> I'm guessing that sounds like an error from the server (it's a **reply** error) - are you sure your redis server is actually 6.2.0+ https://redis.io/commands/copy

Sorry, it was my mistake. zmscore and zrandmember were supported.

**Comment by ayZagen** [comment]
`getex` makes me remove lots of expire calls, would be great to have

**Comment by luin** [comment]
ioredis provides official TypeScript declarations in v5 so closing this. Sorry for the late response!
