### ISSUE TITLE
By how does ioredis support zlexcount？

### ISSUE THREAD

**Issue by xzg5101** [luin/ioredis#1375]
As my project meet the demand of using zlexcount, a very old yet not so frequently used feature of redis, I noticed that seems like ioredis does not have it as a well packed method, which forcing me to use eval() to call it in an ugly way (it works, just you know):

const Z_LEX_COUNT = `return redis.call('zlexcount', KEYS[1], ARGV[1], '+');`;
redis.eval(Z_LEX_COUNT, 1, key, `[${id}`);

However zlexcount is a feature added to redis in 2.8.9, so it would by very suprising to me if ioredis does not have it by far. I'm wondering did I missed anything? 

Any help or discussion will be appreciated (No better redis support can be found elsewhere anyway).

**Comment by jseagull** [comment]
try `redis.zlexcount(key, '-', '+');`

**Comment by xzg5101** [comment]
> try `redis.zlexcount(key, '-', '+');`

Of course this would be my first choice as what I tried in the beginning. However it told me zlexcount does not exist on type Redis

![image](https://user-images.githubusercontent.com/72267123/124583070-38ce6880-de85-11eb-94a0-048515feada3.png)

**Comment by jseagull** [comment]
This is a typescript types issue see #1053 

For now, you can use any of the blow

- `(redis as any).zlexcount(key, '-', '+');`
- `const redis = new Redis() as any;`
- `// @ts-ignore`

**Comment by xzg5101** [comment]
> This is a typescript types issue see #1053
> 
> For now, you can use any of the blow
> 
> * `(redis as any).zlexcount(key, '-', '+');`
> * `const redis = new Redis() as any;`
> * `// @ts-ignore`

I see, thank you for the information. Have a nice day~
