### ISSUE TITLE
Make Redis.Cluster support non-cluster instances

### ISSUE THREAD

**Issue by shaharmor** [luin/ioredis#138]
Hi,

Is it possible to make Redis.Cluster support non-clustered instances as well?

So we will only have to do
```javascript
new Redis.Cluster();
```

even if the server is not a cluster.

**Comment by luin** [comment]
What's the use case for this? What do you expect when connecting to serval non-clustered instances?

**Comment by shaharmor** [comment]
I don't mean to connect to multiple non-clustered instances, but that if the given hosts array is 1, it will just create a normal Redis instance.

That way i can use the same code for both places where i have a redis cluster and where not. (My hosts array is loaded from a remote source)

**Comment by shaharmor** [comment]
What is the point of having both `new Redis.Cluster` & `new Redis`? We can just merge them together no?

**Comment by shaharmor** [comment]
Maybe make it so ioredis auto-detects if its a cluster instance or not

**Comment by luin** [comment]
You can easily write a wrapper on the client side to detect whether the given hosts are standalone servers or clusters. There are many differences between communicating with a standalone server and a cluster(multiple-keys command, pipelining & scripting). Most of the time, the code that works with a standalone server doesn't work with a cluster, so that it makes sense to have both `new Redis.Cluster` and `new Redis`.

**Comment by joniba** [comment]
> You can easily write a wrapper on the client side to detect whether the given hosts are standalone servers or clusters. There are many differences between communicating with a standalone server and a cluster(multiple-keys command, pipelining & scripting). Most of the time, the code that works with a standalone server doesn't work with a cluster, so that it makes sense to have both `new Redis.Cluster` and `new Redis`.

Hi @luin, any chance you could share how to "write a wrapper on the client side to detect whether the given hosts are standalone servers or clusters"? It would be a great help!

**Comment by Praveen-98cs** [comment]
> Hi @luin, any chance you could share how to "write a wrapper on the client side to detect whether the given hosts are standalone servers or clusters"? It would be a great help!

Hi guys! any update on this? cause I also have a feature that uses the cloud provided standalone redis and the ioredis client is created to work with that only and now we are hoping to move to redis cluster and we need to create a whole new redis client. 

thanks
