### ISSUE TITLE
_addedScriptHashesCleanInterval is not cleared if connection is closed by retryStrategy

### ISSUE THREAD

**Issue by samimakicc** [luin/ioredis#1381]
_addedScriptHashesCleanInterval is not cleared If connection to redis is lost and retryStrategy is not a function or retryStrategy returns something else than a number.
This active timeout/interval causes node process unable to terminate when it should.

#1219 fixed that _addedScriptHashesCleanInterval is cleared when connection is manually closed with redis.disconnect() or redis.quit() but I feel it should also be cleared if the connection is closed by other means.

**Comment by taratyn-tc** [comment]
I'm also experiencing and I can't figure out how to fix this. I'm happy to contribute a code fix, if I can get some advice how to fix it.

**Comment by marcbachmann** [comment]
We've fixed that in ioredis v5 by tracking the scripts per redis connection.
