### ISSUE TITLE
Mass Insert

### ISSUE THREAD

**Issue by IronCrystal** [luin/ioredis#1382]
I apologize if I shouldn't have created a new issue.  https://github.com/luin/ioredis/issues/592 was opened 3 years ago but was auto closed.

Is it possible with ioredis to stream commands to redis like described in this article? https://redis.io/topics/mass-insert

My use case is I need to export data from a database and add it to the same set key (sadd all values to same key).  Preferably without having to load all the data into memory (like read from file on disk and stream to redis server).  Is this possible with ioredis' current feature set?

If not, would a pull request to add this feature be accepted?

**Comment by TysonAndre** [comment]
Not exactly the same, but ioredis supports the `enableAutoPipelining: true` mode, which may speed up your use case (especially with a high round trip time). Batching in a finite but large enough size (in smaller chunks of whatever's fetched from the db if needed, e.g. 100 or 10000) may reduce the overhead of communicating  and avoid slowing down other clients of the same server.

https://github.com/luin/ioredis#autopipelining

**Comment by marcbachmann** [comment]
autopipelining or manual pipelines are the solution here
