### ISSUE TITLE
Error event emitted on NOPERM instead of connection problem

### ISSUE THREAD

**Issue by jweingarten** [luin/ioredis#1394]
In my code I am making a `redisClient.info()` call with a user that does not have rights to make the `info` Redis call. The user was restricted using the `ACL` command in Redis 6. 

My connection uses sentinels and looks something like this
```
new Redis({
        username: uName,
        name: Name
        showFriendlyErrorStack: true,
        password: pwd,
        sentinels: Sentinels,
        sentinelRetryStrategy(times) {
          if (times >= 3) {
            logger.error(` Aborting -sentinelRetryStrategy- after ${times} attempts.`);

            return null;
          }
          logger.info(`-sentinelRetryStrategy- ${times} times`);

          return Math.min(times * 1000, 10000);
        }
      });
```
The user can log in just fine, so I get a valid client and do 

```
redistClient.on('error', function(error) {
        logger.error('error:, error);
      });
```
Now when that connected user/client calls `redisClient.info()` the `redistClient.on('error'` is being called over and over. 

Part of the problem is that inho the `times` parameter is NOT increasing. My logger consistently prints  `-sentinelReconnectStrategy- 1 times`. 
The Abort code, which should happen if `times` >3 is never called because `times` is not increased. 

After a while I see `All sentinels are unreachable. Retrying from scratch after 1000ms`. And it starts all over ... 

To me the flow is not understandable because there was no Connection issue at all. Its just that the user did not have rights to execute a command and an error was thrown by the Redis server.

**Comment by jweingarten** [comment]
Test case error :-( Now I see that the user needs to have rights to actually execute `info` ... that is all ....

**Comment by jweingarten** [comment]
Well ... kind of test case error. We had setup a user with only `read` access to a specific set of keys. The `read` acl group does not include being able to execute `info`. So theoretically the ticket/ask should have been `can the readycheck be implemented without calling "info"` ... anyways ... sorry about the ticket.

**Comment by jweingarten** [comment]
Just to close this ... and maybe somebody finds it helpful eventually ... `ACL SETUSER readonly_user  on >samplepwd ~somekey* allchannels +@read +info` 

This ^ creates a user that has the read category + info rights to all `somekey` values in redis only. 
Note the `+info` is needed for `ioredis` lib to work.

**Comment by rsulzenbacher** [comment]
> Just to close this ... and maybe somebody finds it helpful eventually ... `ACL SETUSER readonly_user on >samplepwd ~somekey* allchannels +@read +info`
> 
> This ^ creates a user that has the read category + info rights to all `somekey` keys in redis only. Note the `+info` is needed for `ioredis` lib to work.
> 
> Maybe we can extend ioredis to allow the command in `readycheck` to be customizable :-)

When using a redis cluster, `+client|setname` ACL is needed too. Without that you can see an increased number of `errorstat_NOPERM` errors. (in my case AWS MemoryDB)
