### ISSUE TITLE
[Bug] slotRangeStart and slotRangeEnd are  wrong type

### ISSUE THREAD

**Issue by thaiwu0107** [luin/ioredis#1395]
ioredis/built/cluster/index.js

this getInfoFromNode func

The slotRangeStart and slotRangeEnd are **string** type need convert to Number 

If it is string type it will not run loop first time
![image](https://user-images.githubusercontent.com/20667425/127457493-4f52f154-28f4-4afb-8e9e-c63e49787008.png)
![image](https://user-images.githubusercontent.com/20667425/127457922-433307f7-e468-45d2-b90b-a8532d4194ab.png)

If convert to Number it will run loop first time
![image](https://user-images.githubusercontent.com/20667425/127457786-4037836c-e0f1-4e81-8ee3-65b5d072db2d.png)
![image](https://user-images.githubusercontent.com/20667425/127457835-3e163524-630c-456f-b52c-5735f36e6419.png)

pull request

https://github.com/luin/ioredis/pull/1396

**Comment by luin** [comment]
Addressed in v5.0.0. Thanks for pointing this out!
