### ISSUE TITLE
一个让我迷糊的小问题~

### ISSUE THREAD

**Issue by changhao970630** [luin/ioredis#1398]
![image](https://user-images.githubusercontent.com/48971545/127727609-76b846c7-d53e-4605-9cd6-be9e6887464f.png)
我在使用redis存储一段信息的时候，发现服务器响应一直超时debug的时候发现通过redis存储我的上传凭证的时候，输出了这个东西，能帮我看看这个是什么问题导致的吗？
![image](https://user-images.githubusercontent.com/48971545/127727691-c090fca0-f1a5-4d1b-9d92-eb9e83cb6679.png)

**Comment by changhao970630** [comment]
奇怪的是我昨天使用的时候不会出现这个问题，今天就会了，~

**Comment by luin** [comment]
Hi, 这里是提交关于 ioredis bug 或者特性需求的地方，问题可以在 StackOverflow 上打上 ioredis 的 tag 询问。感谢使用！
