### ISSUE TITLE
Sending raw command

### ISSUE THREAD

**Issue by Kamil93** [luin/ioredis#1400]
How can we send raw command string to `redis-server` by `ioredis` without creating new objects like `new Command(...)`?
Just sending string command and listening for response.
Thanks :)

**Comment by luin** [comment]
We have `Redis#call()` so it looks like `redis.call('set', 'foo', 'bar')` or `redis.call(['set', 'foo', 'bar'])`

**Comment by Kamil93** [comment]
It doesn't work with lua script registered commands
`ERR unknown command `CLMAN.INITSESS`, with args beginning with: `client:test`, `{}``

**Comment by luin** [comment]
It doesn't. For lua commands you have to call the method directly, but this doesn't prevent you from using syntax like `redis['yourcustomcommand']`.

TS definition issues should go to `@types/ioredis` as this repo doesn't provide types.

**Comment by Kamil93** [comment]
Still doesn't work

```
this.redisClient.defineCommand(`CLMAN_INITSESS`, {lua: luaScript});
const result = await (this.redisClient as any).CLMAN_INITSESS(2, redisSessionKey, JSON.stringify(sessionJson));
```

```
TypeError: this.redisClient.CLMAN_INITSESS is not a function
```

for lower-case variant also the same:
```
const result = await (this.redisClient as any).clman_initsess(2, redisSessionKey, JSON.stringify(sessionJson));
```

**Comment by luin** [comment]
It works perfectly on my side:

```javascript
const redis = new Redis();
redis.defineCommand(`CLMAN_INITSESS`, { lua: "return {KEYS[1]}" });
redis.CLMAN_INITSESS(1, "hi", console.log); // printed null [ 'hi' ]
```

**Comment by Kamil93** [comment]
Thanks, I've had a typo.

**Comment by stavalfi** [comment]
@luin `call` is not defined in the typescript types. Is it a mistake?

**Comment by luin** [comment]
> @luin `call` is not defined in the typescript types. Is it a mistake?

Correct. It should be an issue on @types/ioredis side.

**Comment by stavalfi** [comment]
@luin ioredis is written using typescript. and I have types but not uptpdate. 

why ioredis requires @types/ioredis for typescript users?

**Comment by luin** [comment]
ioredis v5 provides official TypeScript declarations so closing this. Sorry for the late response!
