### ISSUE TITLE
Travis CI not running checks, not automatically publishing releases 

### ISSUE THREAD

**Issue by TysonAndre** [luin/ioredis#1402]
For https://github.com/luin/ioredis/pull/1391 , 0 checks were performed after being open for days. Did the project run out of minutes or not get migrated to travis-ci.com (I'm not sure)?

https://github.com/luin/ioredis/commits/master does not have commits such as `chore(release): 4.27.7 [skip ci]` at the time of writing - in June, it only took 3 minutes to publish a release

I briefly searched the issues and didn't see anything related to Travis or GitHub Actions, sorry if I missed a previous issue:
- It's possible to use GH Actions to perform some of these checks - e.g. GH Actions is able to run arbitrary `docker build` or `docker run` commands, so linting and testing can be run in docker (e.g. with a bash script to install and run redis in the background before running tests, and `trap` to stop the server after tests are finished). E.g. an example (for php, not Node.js) is https://github.com/igbinary/igbinary/blob/3.2.4/.github/workflows/main.yml#L50-L52 - For other checks such as automatic publishing or hooks I'm not familiar with how to set them up but I assume they're possible.

**Comment by luin** [comment]
Thanks for pointing this out! It works now. As you said, the cause is we didn't migrate to .com version.

**Comment by TysonAndre** [comment]
I assume you did migrate from your comment (not 100% sure) and there's no remaining work
