### ISSUE TITLE
Way to handle both Redis 5 and Redis 6 object cration

### ISSUE THREAD

**Issue by rajatagarwal** [luin/ioredis#1406]
Is there a way to handle both Redis 5 and Redis 6 object creation?

Could use the following code to create Redis 5 and Redis 6 objects:

```
// works only for Redis 5
ioRedisObj = new IoRedis(redisUrl, options)

// works only for Redis 6
ioRedisObj = new IoRedis(redisUrl + '?allowUsernameInURI=true', options)
```

where options could be:

```
const options = {
    redisUrl: some-redis-url,
    certificate_base64: some-redis-cert,
    namespace: 'test-',
    timeOut: 2000,
    maxRetriesPerRequest: 1
}

```

So if I got a Redis 6 server and try to create an IoRedis object for Redis 5 (without adding allowUsernameInURI=true, then I get the following error:

`WRONGPASS invalid username-password pair`
And if I got a Redis 5 server and try to create an IoRedis object with Redis 6 settings, I get the following error:

`[ERROR] The server returned "wrong number of arguments for 'auth' command". You are probably passing both username and password to Redis version 5 or below. You should only pass the 'password' option for Redis version 5 and under.
`
Is there a way I can handle both Redis 5 and Redis 6 while creating an IoRedis object?

**Comment by marcbachmann** [comment]
I think this got fixed with v5.
https://github.com/luin/ioredis/wiki/Upgrading-from-v4-to-v5

Please report back if there are issues with it.
