### ISSUE TITLE
Xrange usage

### ISSUE THREAD

**Issue by smolto** [luin/ioredis#1409]
Firstly, hi and thank you for reading this.

I do not have much exprerience with Redis Streams. The thing is that I'm trying to create a little consumer and get from message X to Y from a queue. I saw on official documentation the usage of Xrange (https://redis.io/topics/streams-intro) but, I do not know which params does ioredis.xrange fuction need.

Can anyone help me out with this?

**Comment by luin** [comment]
@nbonbon Added an example for XRANGE: https://github.com/luin/ioredis/blob/main/examples/stream.js#L41
