### ISSUE TITLE
Accesibility of lua custom commands

### ISSUE THREAD

**Issue by Kamil93** [luin/ioredis#1410]
Does definied commands by `redisClient.defineCommand(...)` call is accessible only by this `redisClient`? Or if I run program that creates two `redisClient` and in one of them I register command, and second of them will be able to call them too?

**Comment by TysonAndre** [comment]
It's only on the redisClient instance it was called on. You can confirm this by creating two clients and calling defineCommand and only seeing it on the first

A related issue is https://github.com/luin/ioredis/issues/1027 , a request to make it more convenient to define and evaluate custom scripts without adding dynamic properties

**Comment by marcbachmann** [comment]
I've also opened https://github.com/luin/ioredis/issues/1496 about the inheritance of scripts with `redis.duplicate`. The suggestion is a bit more detailed in there, so I'll close this issue.
