### ISSUE TITLE
Read multiple streams with xread

### ISSUE THREAD

**Issue by KoreLewi** [luin/ioredis#1411]
I have a codesnippet which read from a debezium stream, and forwards the stream data for processing.
`  const xread = ({stream, id}) => {
            redis.xread('BLOCK', 0, 'STREAMS', stream, id, (err, str) => {
                if (err) return console.error('Error reading from stream:', err);
                //processing
                });
                setTimeout(() => xread({stream, id}), 0)
            });
        }`
`await xread({stream: 'mystreamname', id: '$'})`

I'm looking for a solution that allows me to subscribe to multiple streams at once.
This is currently solved as follows:
`await xread({stream: 'stream1', id: '$'})`
` await xread({stream: 'stream2', id: '$'})`

Can i pass multiple stream for the resis.xread? 
`   redis.xread('BLOCK', 0, 'STREAMS', MULTIPLE STREAM NAMES?, id, (err, str) => {}`

**Comment by marcbachmann** [comment]
This will work as documented:
https://redis.io/commands/xread

```js
const res = await redis.xread('BLOCK', 1000, 'STREAMS', 'stream1', 'stream2', stream1offset, stream2offset)
```
