### ISSUE TITLE
Cluster + enableAutoPipelining -> Does it send multiple commands from different slots to same server?

### ISSUE THREAD

**Issue by stavalfi** [luin/ioredis#1412]
Suppose I enabled `enableAutoPipelining` in cluster-mode:

### Questions

1. Suppose `server1` manages slots 10,11,12 and server2 manages slots 20,21. I sent 6 seperate commands with slots: 10,10,10,12,20,21. Does IoRedis will send the first 4 commands to `server1` in the same pipeline and the last 2 commands to `server2` in the same pipeline?
2. If the answer to (1) is true, suppose I send multiple `multi` commands such that each of them contain commands with the same slot (commands from different `multi` belongs to different slots). But, some of the `multi` commands, would reach the same redis-server (because that specific redis-server manages these slots anyways), does IoRedis group by multiple `multi` commands to single pipeline/multi and reach out to redis-server only once?
3. In question (2), is there any difference if I would use `pipeline` over `multi`?

**Comment by jseagull** [comment]
1. Yes.
2. No, see https://github.com/luin/ioredis/blob/17c75955a89fe62cebb1e2ae85f4a2adf4c66b39/lib/autoPipelining.ts#L8-L21
3. No.

**Comment by stavalfi** [comment]
Thanks @jseagull !!
