### ISSUE TITLE
typescript: can't use enableAutoPipelining in Cluster mode

### ISSUE THREAD

**Issue by stavalfi** [luin/ioredis#1413]
![image](https://user-images.githubusercontent.com/12954665/129170670-bb28cb2f-6985-45c7-9af2-f35516d51192.png)

ioredis version: 4.27.7 (latest)

When trying to debug it, I saw that what I have locally is:

![image](https://user-images.githubusercontent.com/12954665/129170825-0afdcd22-c369-4117-8762-efc00488e592.png)

In the Ioredis repository there is a `IClusterIOptions` which cotnains the definitions for `enableAutoPipelining`:

https://github.com/luin/ioredis/blob/17c75955a89fe62cebb1e2ae85f4a2adf4c66b39/lib/cluster/ClusterOptions.ts#L30

https://github.com/luin/ioredis/blob/17c75955a89fe62cebb1e2ae85f4a2adf4c66b39/lib/cluster/ClusterOptions.ts#L175

-----------

Why `IClusterOptions` is not published in npm? Is it a mistake?

**Comment by marcbachmann** [comment]
The upcoming version 5 of ioredis has built-in types instead of https://www.npmjs.com/package/@types/ioredis. 
[`5.0.0-beta.1`](https://www.npmjs.com/package/ioredis/v/5.0.0-beta.1) got released 2 days ago.
