### ISSUE TITLE
Add EXPIREMEMBER for expiring individual keys on sets for KeyDB

### ISSUE THREAD

**Issue by ShivamJoker** [luin/ioredis#1419]
```sh
EXPIREMEMBER key subkey delay [Unit: s,ms]
```

Ref - https://docs.keydb.dev/docs/commands/#expiremember
Redis currently doesn't support this but KeyDB does.

I can try creating a PR if you want for this.

**Comment by TysonAndre** [comment]
You can do that with https://github.com/luin/ioredis/blob/master/API.md#redisaddbuiltincommandcommandname--object already.

It may be possible to create a `class KeyDb extends Redis`, and have that subclass call `this.addBuiltinCommand('expiremember')` in its constructor. (either in your own application, or a standalone library)

Not sure what ioredis's maintainers think, but adding the definition to the Redis class itself seems like users might use it unintentionally for redis servers and get a runtime error (after seeing it in autocompletion, or API documentation). Full KeyDb support may be too large in scope or out of scope; I'm not familiar with KeyDb at all.

**Comment by ShivamJoker** [comment]
I think creating a class and extending it with custom command seems like bit of work.
KeyDB is same as redis with faster and some extra features.

I think we can add an API with JSDoc to indicate it's not built into redis

**Comment by marcbachmann** [comment]
I'd also say this is out of scope at the moment.

Please extend Redis like suggested above. This shouldn't be too complex.
Types also just got refactored and are now properly by ioredis. So you could just extend them too.
```js
class KeyDb extends Redis {
  constructor (...args) {
    super(...args)
    this.addBuiltinCommand('expiremember')
  }
}
```

**Comment by isaadabbasi** [comment]
I am using using `ioredis:4.28.5`
There's no such method as `addBuiltinCommand `.
But only `getBuiltinCommands` and `createBuiltinCommand`
