### ISSUE TITLE
range with "withscores"

### ISSUE THREAD

**Issue by siddo420** [luin/ioredis#142]
Just wanted to know how we specify extra clauses to commands in ioredis. For example, I want to call zrange/zrevrange with "withscores" (see http://redis.io/commands/zrange). 

How would I go about doing that? Please let me know.

Thanks.

**Comment by luin** [comment]
`redis.zrange('foo', 0, 100, 'WITHSCORES');`

**Comment by siddo420** [comment]
Thanks.

Is there an easy way to dynamically add a random (unknown) number of members to sorted set in a single command? I have members in an array but only want to use a single command.

http://redis.io/commands/zadd

**Comment by luin** [comment]
`redis.zadd('key', score1, member1, score2, member2)`
or
`redis.zadd('key', [score1, member1, score2, member2])`

**Comment by siddo420** [comment]
Thanks luin

**Comment by vigneshnrfs** [comment]
How do I use the above with same score? Something like

redis.zadd('key', score, [member1, member2, member3])

**Comment by luin** [comment]
This syntax isn't support by redis natively. However, you can just use `redis.zadd('key', [member1, member2, member3].map(member => [score, member]))`

**Comment by vigneshnrfs** [comment]
Thanks. That works.

**Comment by akshay-kumar11** [comment]
@luin 
client.zrange(key, 0, -1, "REV", "WITHSCORES") is giving following error in ioredis ver: 4.17.3. Redis Server version: 5.0.6 AWS Elastic Cache Redis Cluster.

connection code:
`const client = new Redis.Cluster([
  {
    host: env.redis.host,
    port: env.redis.port,
  }
],{
  redisOptions: {
    tls: { checkServerIdentity: () => undefined }
  }
});`

`ReplyError: ERR syntax error
    at parseError (workspace/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (workspace/node_modules/redis-parser/lib/parser.js:302:14) {
  command: {
    name: 'zrange',
    args: [ 'tophit_hi_IN', '0', '-1', 'REV', 'WITHSCORES' ]
  }
}
`

can you please help.

**Comment by knutole** [comment]
@akshay-kumar11 As per [Redis docs](https://redis.io/commands/zrange/), the `REV` command was added in Redis 6.2 verison. You have v5, so it's not supported.
