### ISSUE TITLE
Make Redis.Cluster work when `Buffer` is used as a key with invalid utf-8 data

### ISSUE THREAD

**Issue by TysonAndre** [luin/ioredis#1428]
Completely unrelated to https://github.com/luin/ioredis/issues/1427 but discovered while investigating it

https://github.com/luin/ioredis/blob/f898672a29753774eeb6e166c28ed6f548533517/lib/command.ts#L194-L196

https://github.com/luin/ioredis/blob/f898672a29753774eeb6e166c28ed6f548533517/lib/autoPipelining.ts#L145-L148
the above snippet has been assuming key prefixes can be prepended to strings and that all values should be stringified

That's not 100% correct, since Buffers might be invalid utf-8

```
> x = Buffer.from('xyz')
<Buffer 78 79 7a>
> x = Buffer.from([0x80]);
<Buffer 80>
> console.log(`${x}`)
� // Literally the codepoint for unencodable data
> console.log(Buffer.from(`${x}`))
<Buffer ef bf bd>
```

It could be fixed by always converting to buffers and concatenating, or by conditionally everything that isn't already a buffer to a string then a Buffer then concatenating those Buffers into another Buffer.

```
> const clusterKeySlot = require('cluster-key-slot');
> clusterKeySlot('a')
15495
> clusterKeySlot(Buffer.from('a'))
15495
```

Very low priority to me since I don't have use cases for invalid utf-8.

**Comment by luin** [comment]
👋 This should have been fixed in v5.0.0 so closing this.
