### ISSUE TITLE
Command SMISMEMBER is missing from types definition

### ISSUE THREAD

**Issue by antoinechampion** [luin/ioredis#1429]
Following #1281, the built-in command SMISMEMBER is in the redis client prototype, but is missing from the @types/ioredis definitions, hence breaking compatibility with TypeScript. Using @ts-ignore as a temporary workaround.

**Comment by TysonAndre** [comment]
This should be done with a PR to the https://github.com/DefinitelyTyped/DefinitelyTyped repo which is not owned by the ioredis maintainers. See https://github.com/luin/ioredis/issues/1424#issuecomment-905599767 for links to previous PRs others have made to the `@types/ioredis` module

**Comment by c1moore** [comment]
This already appears to exist: https://github.com/DefinitelyTyped/DefinitelyTyped/blame/master/types/ioredis/index.d.ts#L383

**Comment by venku122** [comment]
The correct type definition should be 

```
        smismember(key: KeyType, ...members: string[]): Promise<BooleanResponse[]>;
```

I am not super familiar with how callback support is handled for commands so there might be an additional type here.

I went and made a type update pr in DefinitelyTyped
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/56945
