### ISSUE TITLE
Does db: 0 actually work?

### ISSUE THREAD

**Issue by InstanceOfMichael** [luin/ioredis#143]
These docs imply you can pick your DB
```
new Redis({
  port: 6379,          // Redis port
  host: '127.0.0.1',   // Redis host
  family: 4,           // 4 (IPv4) or 6 (IPv6)
  password: 'auth',
  db: 0
})
```
but it is missing here:
https://github.com/luin/ioredis/blob/master/API.md#new_Redis

**Comment by luin** [comment]
Yes, the `db` option is supported, and I just updated the doc for it. Thanks for pointing it out.

**Comment by InstanceOfMichael** [comment]
:+1:
