### ISSUE TITLE
TypeError: Cannot read property 'showFriendlyErrorStack' of undefined

### ISSUE THREAD

**Issue by mfaheemakhtar** [luin/ioredis#1433]
Just for reference since I was unable to find it on Google.

This error occurs when assigning the member function to another variable.

```
export const get = redis.get;
```

Probably, no reason to do it. But, anyway.

**Comment by luin** [comment]
Thanks for raising this. You can go with

```js
export const get = redis.get.bind(redis);
```

Going to close this as it's indexed by Google anyway 😆
