### ISSUE TITLE
pubsub typescript support 

### ISSUE THREAD

**Issue by malsabbagh** [luin/ioredis#1434]
`pubsub` method doesn't have typescript typing support, can we add it? 
I want to avoid doing this in typescript 
`(pubRedisClient as any).pubsub(...)`

**Comment by endel** [comment]
Just stumbled upon this, too, and made a PR here, appreciate if you can review and check if it's okay https://github.com/DefinitelyTyped/DefinitelyTyped/pull/55823

**Comment by malsabbagh** [comment]
I locally extended the type definition 

types/ioredis/index.d.ts
```
// Type definitions for ioredis
import { Redis} from 'ioredis';

declare module 'ioredis' {
  export interface Redis {
    pubsub(subcommand: 'CHANNELS' | 'NUMSUB' | 'channels' | 'numsub', ...args: [...string[], Callback<string[]>]): void;
    pubsub(subcommand: 'CHANNELS' | 'NUMSUB' | 'channels' | 'numsub', ...args: string[]): Promise<string[]>;
    pubsub(subcommand: 'NUMPAT' | 'numpat', callback: Callback<number>): void;
    pubsub(subcommand: 'NUMPAT' | 'numpat'): Promise<number>;
  }
}
```

Make sure `types` folder is referenced in `tsconfig.json` under `typeRoots`

**Comment by luin** [comment]
ioredis v5 provides official TypeScript declarations so closing this. Sorry for the late response!
