### ISSUE TITLE
Issue with Amazon Elasticache failover

### ISSUE THREAD

**Issue by vestly** [luin/ioredis#144]
I'm trying to use ioredis with Amazon Elasticache clusters and am finding it difficult dealing with failover issues. Specifically, when there is a Redis failover, all of my writes continue to be attempted on the slave and return errors: Unhandled rejection ReplyError: READONLY You can't write against a read only slave. I need a way to disconnect and reconnect gracefully after the failover. There's no great way to handle this. I could try to handle the error upon every write using callbacks, but this would be a lot of nasty repeated error checking code. I could use Redis.Promise.onPossiblyUnhandledRejection, but this would mean never being able to check for errors in callbacks - not really a great option, either.

If handling AWS failover natively isn't an option, at least an event emitter for ALL errors would be helpful. This way I could handle these errors in a single place and still use callbacks to handle more specific errors.

Obviously if I'm missing something really stupid, feel free to point me in the right direction. Thanks!

**Comment by luin** [comment]
Hi vestly,
How did you use ioredis to connect to the AWS redis cluster? AWS redis cluster is not as same as the cluster bundled in Redis 3.x. The redis version that AWS provided is 2.6.x & 2.8.x, and failover is handled  on the AWS side. So basically you can only use `new Redis` to connect to the cluster node.

**Comment by vestly** [comment]
I am using `new Redis` to connect to the primary endpoint for the cluster, which always resolves to the master. However, a failover event does not trigger a disconnect of the ioredis client, so my client (an api server that is always running) continues to stay connected to the new slave and throws errors on writes. I am looking for a way for the client to recognize the error and reconnect to the new master.

**Comment by luin** [comment]
I found a related issue: https://github.com/redis/redis-rb/issues/543. IMO, the correct behaviour is to disconnect all client connections after a failover happens, which is as same as Redis Sentinel. However given the current implementation of AWS, I'd like to add a `reconnectOnError` option inspired by the issue above to make it possible to handle the failover.

**Comment by vestly** [comment]
Yes, I think that would be a great solution, especially if it includes offline queuing for minimal data loss.

**Comment by luin** [comment]
Just submitted a pull request for this feature request: https://github.com/luin/ioredis/pull/148. Welcome to test it if you have time.

**Comment by mjmelli** [comment]
This works nicely in my tests with ElastiCache failover. Thank you very much!

**Comment by vestly** [comment]
This works nicely in my tests with ElastiCache failover. Thank you very much!

**Comment by luin** [comment]
Released in 1.9.0 :rocket:

**Comment by soryy708** [comment]
Related:

- https://github.com/redis/ioredis/issues/1907
