### ISSUE TITLE
Question/guidance should I use one client or multiple clients as needed for different purposes?

### ISSUE THREAD

**Issue by AndysonDK** [luin/ioredis#1447]
I'm building a node server where I currently have one ioredis client with the purpose of storing user sessions. I'm also using [mikro-orm](https://mikro-orm.io/) to interact with my database. Mikro-orm can also cache db responses, and I can connect redis to mikro-orm so mikro-orm will store the cache in redis. My question is can I reuse the same client for both purposes, or should I create a new ioredis client for my mikro-orm cache job?

**Comment by luin** [comment]
Generally it doesn't matter unless one of the purposes requires blocking command (eg bloop) or pubsubs. Given the overhead for the connection is little, I'd just not reuse.
