### ISSUE TITLE
recovering from timeout

### ISSUE THREAD

**Issue by amit777** [luin/ioredis#145]
It seems from the documents that if a connection closes or timesout, then ioredis should reconnect to redis.  However, in my logs, I see a timeout error, and then all subsequent requests have a request error.  My process seems to connect to redis after I restart it.  I'm still investigating why the timeout happened to the local redis instance.  But am I mistaken as to how ioredis should behave?

First error message:
```
[Error: Redis connection to 127.0.0.1:6379 failed - connect ETIMEDOUT 127.0.0.1:6379]
```

Then subsequent errors are:
```
[Error: Redis connection error]
```

**Comment by luin** [comment]
Hi amit777,
ioredis doesn't emit `Redis connection error` error. Counld you please turn the debug logs (by `DEBUG=ioredis:* node yourapp.js`) to see what is going on?

**Comment by luin** [comment]
I'm closing this since it seems not a ioredis specified issue. Feel free to reopen it with more information.

**Comment by amit777** [comment]
This error seems to come from the native redis module, not ioredis. Sorry for the false alarm.

**Comment by luin** [comment]
Never mind. Hope you can enjoy ioredis :laughing:
