### ISSUE TITLE
How to flushdb async

### ISSUE THREAD

**Issue by zoeytruong** [luin/ioredis#1453]
I want to use `FLUSHDB ASYNC`, but not sure how to do that with ioredis. I only see `flushdb`. Thanks.

**Comment by luin** [comment]
It should just be redis.flushdb('async')

**Comment by zoeytruong** [comment]
Awesome. Thank you so much. So easy.

**Comment by zoeytruong** [comment]
When I use that, it is saying `Argument of type 'string' is not assignable to parameter of type 'Callback<"OK">'.ts(2345)`. I am using TypeScript. Hmm, do you happen to know why?

**Comment by luin** [comment]
It's an issue on @types/ioredis side that the typing declarations are not correct.

**Comment by zoeytruong** [comment]
Okay. [After this line here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/ioredis/index.d.ts#L1124), we can also add `flushdb(option: 'async' | 'sync'): Promise<Ok>;`?

**Comment by luin** [comment]
Yeah I think so. Can you create a PR on that repo?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by zoeytruong** [comment]
Yes, doing that now.

**Comment by zoeytruong** [comment]
@luin I cannot push to the DefinitelyTyped repo. It said that I don't have permission. Is there any special permission that I need to get?

**Comment by zoeytruong** [comment]
I made the above change and it got merged. When does this [@types/ioredis package](https://www.npmjs.com/package/@types/ioredis) get updated? I can see the changes in the DefinitelyTyped repo. When I use version 4.28.6 for `@types/ioredis`, I don't see that change. I want to know how that npm package get bundled to reflect the change that I merged in. @luin
