### ISSUE TITLE
smismember is not a function

### ISSUE THREAD

**Issue by 1omercohen** [luin/ioredis#1473]
I create a Redis connection using with sets data structure 
the commands ("sadd", "sismember", "srem", "smembers") is working, but not recognize "smismember"

`await cluster.smismember('key', ["value1", "value2"])`

**Comment by TysonAndre** [comment]
Possibly either
1. A duplicate of https://github.com/luin/ioredis/issues/1429
2. You needing a newer version of the redis server. You need 6.2 or newer to run that. Call `console.log(await redis.info('server'))` to see what version you are connected to (I forget if that works for cluster). See https://redis.io/commands/smismember

**Comment by marcbachmann** [comment]
That will be fixed with [v5](https://github.com/luin/ioredis/pull/1504)

**Comment by marcbachmann** [comment]
another update landed with https://github.com/luin/ioredis/pull/153. let's close this
