### ISSUE TITLE
ioredis and tiny-async-pool

### ISSUE THREAD

**Issue by KaranAhlawat** [luin/ioredis#1476]
Hello,

I'm trying to use tiny-async-pool to execute a bunch of redis operations parallely, but evidently multiple connections aren't supported by ioredis in the form of cxn pools, multiplexing or other.

I could not find anything else related to my issue anywhere and the other third party package I happened upon (ioredis-conn-pool) is unmaintained for about two years now, and didn't work.

If anyone is using ioredis in this sort of way, or with tiny-async-pool, please do tell. Any help is appreciated.

Node version :- 12.14.1
npm version :- 6.13.4
ioredis :- 4.28.0

**Comment by TysonAndre** [comment]
https://github.com/luin/ioredis#autopipelining

> In standard mode, when you issue multiple commands, ioredis sends them to the server one by one. As described in Redis pipeline documentation, this is a suboptimal use of the network link, especially when such link is not very performant.
> 
> **The TCP and network overhead negatively affects performance. Commands are stuck in the send queue until the previous ones are correctly delivered to the server. This is a problem known as Head-Of-Line blocking (HOL).**
> 
> ioredis supports a feature called “auto pipelining”. It can be enabled by setting the option enableAutoPipelining to true. No other code change is necessary.
> 
> In auto pipelining mode, all commands issued during an event loop are enqueued in a pipeline automatically managed by ioredis. At the end of the iteration, the pipeline is executed and thus all commands are sent to the server at the same time.
> 
> **This feature can dramatically improve throughput and avoids HOL blocking. In our benchmarks, the improvement was between 35% and 50%.**

(updating patch version of ioredis to 4.28.2 may also help if you use lua scripts, Redis.Cluster, etc - https://github.com/luin/ioredis/blob/master/Changelog.md)

**Comment by KaranAhlawat** [comment]
@TysonAndre Hello, thanks for your quick response! That seems to fix the issue, and also seems to be working as intended, alongside tiny-async-pool. Therefore I'll be marking this issue as closed.
