### ISSUE TITLE
ioredis tries to connect/reconnect to localhost

### ISSUE THREAD

**Issue by Mayhem93** [luin/ioredis#1477]
Hello,

So I'm running a websockets server with redis support on AWS ECS Fargate and the issue I'm reporting only happens during a stress test with thousands of clients connected (otherwise it works perfectly)

Each client creates two redis connections: one for read/write and one for subscribing.

About 12000 clients connect, after a long wait of 40 mins at which point some ioredis clients try to mistakenly connect to localhost (⚠️the **2 connected clients** you are seeing is because it closed all the connections, and these two faulty ones remained):

![image](https://user-images.githubusercontent.com/705289/145034376-bf36b00c-06f4-424a-a6aa-cdb9ab40920c.png)

How and why does it try to connect to localhost ??? The redis error handler is not even triggered, this error comes from somewhere else: **notice that the message "Redis error: " is missing from the output**

```javascript
client.on('error', err => {
	console.log('Redis error: ', err);
});
```

This is how I connect and how I get my db host & password:

```javascript
let dbAuthToken;
let dbEndpoint;

async function createDbConnection () {
	let client = new Redis({
	          port: 6379,
	          host: dbEndpoint,
	          connectTimeout: 20000,
	          enableOfflineQueue: true,
	          password: dbAuthToken,
	          tls: {
		          rejectUnauthorized: false
	          }
          });

	await (new Promise(resolve => {
		client.on('ready', resolve);
	}));

	client.on('error', err => {
		console.log('Redis error: ', err);
	});

	return client;
}

class DBClient {
	async connect () {
		if (!dbAuthToken) {
			dbAuthToken = await getSSMParam('DBAuthKey', true);
			dbEndpoint = await getSSMParam('DBEndpoint', false);
		}

		this.redisClient = await createDbConnection();
		this.subscriberClient = await createDbConnection();
	}

```

On a new websockets connection I instantiate a new DBClient object. And very small connections fail, in my example two out of 12000, because it's trying to connect to localhost. How ??

Can someone help me debug this ?

**Comment by TysonAndre** [comment]
```js
let dbAuthToken;
let dbEndpoint;
// ....
class DBClient {
	async connect () {
		if (!dbAuthToken) {
			dbAuthToken = await getSSMParam('DBAuthKey', true);
			dbEndpoint = await getSSMParam('DBEndpoint', false);
		}
```

It's a bug in your testing code.

1. Task A calls connect
2. Task A sees dbAuthToken is falsey and calls `await getSSMParam('DBAuthKey', true);`, letting other tasks start executing 
3. Task A returns to execution and calls `dbEndpoint = await getSSMParam('DBEndpoint', false);` (letting other tasks start executing ) - dbEndpoint is undefined until it finishes and resumes
4. Task B calls connect and sees dbAuthToken is not falsey. It initializes redisClient with `dbEndpoint=undefined`, `dbAuthToken` initialized
5. In Task B, redis converts undefined to 'localhost'
https://nodejs.org/en/docs/guides/dont-block-the-event-loop/

**Comment by Mayhem93** [comment]
Makes sense @TysonAndre thanks a lot. Another solution would be to get those parameters at server boot, before creating the server.

**Comment by marcbachmann** [comment]
If others have the same need, a `getCredentials` function could be implemented.
Until this comes up again, let's close it.
