### ISSUE TITLE
Container runs out of CPU(100 % CPU usage) with ioredis client

### ISSUE THREAD

**Issue by smriti-d** [luin/ioredis#1485]
We are using ioredis client library (version 4.28.2) to connect with the Redis cluster on the node.js app. However, the CPU usage builds and ramps up to 100% usage in a couple of hours.
Please find attached CPU profile stats. 

The node.js app basically sleeps and wakes up every minute and reconnects to redis to do its processing. 

It would be helpful if you could shed some light on fixing the high CPU problem  or a workaround to it
, thanks.
![cpuProfileTimeout1](https://user-images.githubusercontent.com/9010200/148475192-5277f1f1-4140-436c-b17c-9539558e86a3.png)
![cpuProfileTimeout2](https://user-images.githubusercontent.com/9010200/148475204-1ae8ba1b-6993-444d-8bb4-84de8e7e6503.png)

**Comment by smriti-d** [comment]
@luin do you have any comments on the issue.

**Comment by luin** [comment]
Hi @smriti-d ,

I think it should probably be caused by reconnections to the cluster. ioredis reconnects to the cluster whenever it receives errors like `MOVED`, `CLUSTERDOWN`, and it may consume CPU resources when it sends many commands that causes these errors.

Is it possible to enable the debug mode `DEBUG=ioredis:* node yourapp.js` to see what errors did your app receive?

**Comment by smriti-d** [comment]
Hi @luin , please find attached debug logs of the application. 
[highCPUDebug2.log](https://github.com/luin/ioredis/files/7849454/highCPUDebug2.log)

Below are the configs we use in our Ioredis cluster client 
retryTimeMs=500
retryLimitMs=20,000
```
this.client = new Redis.Cluster([endpoint], {
        clusterRetryStrategy(times) {
          const retry = Math.min(times * retryTimeMs, retryLimitMs);
          logger.info('Error connecting RedisCluster, retrying again for:', times, 'time in', retry, 'ms');
          return retry;
        },
        redisOptions: {
          retryStrategy(times) {
            const retry = Math.min(times * retryTimeMs, retryLimitMs);
            logger.info('Error connecting RedisClient, retrying again for:', times, 'time in', retry, 'ms');
            return retry;
          },
        },
      });
```
Also, our app wakes up every minute and runs for about 100ms periodically. With these ioredis client configs, the docker CPU ramps to 100% in just 3-4 hours, even with minimal load. 

Is there a workaround to avoid/fix high CPU usage?

**Comment by luin** [comment]
That's weird. Can you try out setting the `slotsRefreshInterval` option to a larger number (say `120000`)? Besides that, is there a possibility that you were creating more than one `Redis.Cluster` instance? Too many instances can also consume memory/CPU resources.
