### ISSUE TITLE
TLS Support [request]

### ISSUE THREAD

**Issue by ScheerMT** [luin/ioredis#149]
This is something that was currently considered for node_redis [#246](https://github.com/NodeRedis/node_redis/issues/246).

This feature would be something that would be a nice to have to give people the option if they want/need to use it.

**Comment by luin** [comment]
Yes, I'm going to implement it in the next version.

**Comment by luin** [comment]
Just submitted a pull request for TLS support.

**Comment by luin** [comment]
Released in 1.9.0 :rocket:

**Comment by ScheerMT** [comment]
Thanks! :)
