### ISSUE TITLE
How to use ioredis sentinel with NestJS？

### ISSUE THREAD

**Issue by littleKitchen** [luin/ioredis#1490]
I am working on a nestjs project using Bull queue. In this project, Bull queue need to connect Redis Sentinel (Bull use ioredis), here is my code :

```
   BullModule.registerQueue(
      {
        name: 'message',

        redis: {
          sentinels: [
            {
              host: '...',
              port: 26379,
            },
          ],
          name: 'redismaster',
        },
      },
)
```

I am wondering is this the right way to use it?

**Comment by cedricjacobs** [comment]
BullModule.forRootAsync({
      inject: [ConfigService],
      useFactory: async (configService: ConfigService) => ({
        prefix: configService.get('APP_ENV') || 'dev',
        redis: {
          role: 'master',
          name: configService.get('REDIS_SENTINEL_NAME') || 'mymaster',
          sentinels: [
            {
              host: configService.get('REDIS_HOST'),
              port: configService.get('REDIS_PORT'),
            },
          ],
        },
      }),
    }),

**Comment by marcbachmann** [comment]
The documentation for bull in nestjs is in https://github.com/nestjs/bull
and https://docs.nestjs.com/techniques/queues. According to that they just pass the whole redis object to ioredis, so that should work.
If that's not the case, probably open an issue in the other repo.
