### ISSUE TITLE
为什么不主动关闭连接 连接数会一直增加？

### ISSUE THREAD

**Issue by Messilimeng** [luin/ioredis#1491]
connected_clients:589

when over maxclients:1000 then redis cant work

so need i quit the connect after i get or set commend？

**Comment by Messilimeng** [comment]
![}~T3R~3F _K(OH1%MDP%A4T](https://user-images.githubusercontent.com/12272166/150090217-df61a6f2-5876-4d2f-9abd-2938a10f8ee1.png)
node 执行这个js 脚本 他的连接数就多一个 
但是为什么只有 ctrl +c 停止运行 这个脚本 连接才断开 
不应该是超时 就断开吗？
我的程序现在每次用redis 就会连接数多一个 最终导致连接数过多 奔溃
怎么处理呢

**Comment by luin** [comment]
Hey @Messilimeng,

There is no concept of timeout in Redis connections. So what you may suppose to do is to reuse the same connection instead of creating a new one every time you need it.

Redis连接中没有超时的概念。因此，你可能想做的是重复使用同一个连接，而不是每次需要时都创建一个新的连接。

**Comment by Messilimeng** [comment]
你好 ，代码中 我很难一直复用一个链接 ，我可以理解只要我new 一次 得到一个连接就可以一直用吗？

**Comment by Messilimeng** [comment]
@luin 或者我每次new 一个 用完就quit 对性能影响很大吗？

**Comment by luin** [comment]
对的，只要 new 一次一直用就好。不需要 quit。例如一个 Express 应用：

```js

const redis = new Redis();

router.get('/users/:id', async (req, res) => {
  // DO NOT create a new redis connection here.
  res.json({ name: await redis.get(`user:${req.params.id}.name`) })
});

```

> 一个 用完就quit 对性能影响很大吗？

不是特别大，但是会有一定的开销（一个 TCP 连接和一些轻量的 event handler），除非特定场景，否则要尽量避免。

**Comment by Messilimeng** [comment]
@luin  因为项目中有很多文件很多地方要用redis 所有只能在各个文件里面 new 一次 只要new 就会增加一个连接，你的意思是如果把new 实例化 放到 require 那地方 就会减少实例化连接？

**Comment by luin** [comment]
这里主要解决一些 ioredis 的 bug 或者 feature request，所以很抱歉没有办法回答得很详细（而且需要了解你的项目的具体情况）。

简单来说可以创建一个 redis.js，里面 export 一个创建好的 Redis 实例，其他文件 require 这个文件就可以。

**Comment by Messilimeng** [comment]
@luin 好的 非常感谢 你的讲解， 我按你的思路往下走。
