### ISSUE TITLE
Syntax for utilizing flags with zadd ([NX|XX] [GT|LT] [CH] [INCR])

### ISSUE THREAD

**Issue by IanMontes** [luin/ioredis#1492]
Hi everyone! I couldn't find this anywhere, so I'm just wondering if ioredis has the functionality to use flags ([NX|XX] [GT|LT] [CH] [INCR] - as per https://redis.io/commands/ZADD).

If so, what would be the syntax for doing this? Sorry if this question has been asked before, I hadn't seen anyone mentioning it yet. Thanks!

**Comment by luin** [comment]
The syntax is like `redis.zadd('mykey', 'NX', 'INCR')`. The order doesn't matter.

Basically, ioredis sends the arguments to the server directly, so it supports all commands and arguments as long as the server accepts them. You can assume it works just like redis-cli, with redis-cli, you execute commands like `> zadd mykey NX INCR`, and with ioredis, it works the same way.

**Comment by IanMontes** [comment]
Thanks so much for the fast response Luin, that's pretty intuitive - nice one! I'll go ahead and close this.
