### ISSUE TITLE
ioredis cache not expiring 

### ISSUE THREAD

**Issue by MakarandPundlik** [luin/ioredis#1493]
**ioredis cache not expiring**

I'm building a chatroom cache which should persist for 2 min in redis database, but even after using expireat method cache does not get cleared.

This is my code for storing the cache

**Code**

```
//check whether room already exists or not
//if not set certain expiry timestamp 

 const setMessage = async(room,from,message)=>{
  //check whether room exists or not
  client.lrange(room,0,-1,async(err,replies)=>{
    console.log(err,replies)
    if(replies.length==0)
      {
     
        const when = 24*60*60
        client.set(room,[],'EX',when,(err,ans)=>{//here in seconds
               console.log(`setting expiry at ${ new Date(Date.now() + when*1000)}`) //here in milliseconds 
        })
      }
  })
  
   await client.rpush(room,`${from}:${message}`);
   
}
```

**Expected behavior**
This snippet of code should delete the key(room) from redis cache after completion of 24 hrs. But as a result, cache is persisted even after the completion of 24 hrs.

**Dependencies**
"express": "^4.17.1",
"ioredis": "^4.28.2"

Is there any way to figure this out?

**Comment by luin** [comment]
`expireat` accepts a timestamp that is in seconds instead of ms, so should be like `(Date.now()+1*60*1000) / 1000`

**Comment by MakarandPundlik** [comment]
thank you @luin for you answer, actually i'm looking for set() method, expireat() is commented out. Can you put some light on that ?

**Comment by luin** [comment]
Oh I see. `client.set(room,[],'EX'` here since ioredis flats arguments, so the `[]` will be omitted. You need to provide a valid value ex `client.set(room, 'anyvalue', 'EX', 24 * 3600)`.

**Comment by MakarandPundlik** [comment]
thank you @luin for you answer,it really helped me alot 🥇 💯 .

**Comment by luin** [comment]
No problem! If you are on a macOS can try out a GUI tool ex https://getmedis.com/ to inspect the TTL & value of keys easier.

**Comment by MakarandPundlik** [comment]
Sure !
