### ISSUE TITLE
Node.js process crushes if a user has no permissions to run the 'monitor' command

### ISSUE THREAD

**Issue by artyom-podymov** [luin/ioredis#1498]
1. If create a user that has no permissions to run the `monitor` command
```bash
$ redis-cli 
localhost:6379> ACL SETUSER alice on nopass ~* &* +@all -monitor
OK
```
2. Connect to Redis and call monitor function
```javascript
const Redis = require("ioredis");

var redis = new Redis({host: 'localhost', port: 6379, username: 'alice'});

redis.on("connect", () => {
  console.log('Connected to DB \n');
  redis.monitor((err, monitor) => {
    console.log('Error', err)
    if (!err) {
      monitor.on('monitor', (...args) => console.log(JSON.stringify(args)))
    }
  });
});

```
3. As a result in the callback function we don't see any error and Node.js process just crushes (the same behavior for `async` function implementation)
```
Connected to DB 

Error null                                                                                    
node_modules\redis-parser\lib\parser.js:179    
    return new ReplyError(string)                                                             
           ^                                                                                  
                                                                                              
ReplyError: NOPERM this user has no permissions to run the 'monitor' command or its subcommand
    at parseError (node_modules\redis-parser\lib\parser.js:179:12)
    at parseType (node_modules\redis-parser\lib\parser.js:302:14) {
  command: { name: 'monitor', args: [] }
}

```

Is it possible to handle such cases and properly throw errors without stopping the Node.js process?

**Comment by udochify** [comment]
Attach an event handler to the node.js process like this

```
process.on("uncaughtException", (error) => {
     console.error("Uncaught Exception Description: ", error);
});
```
Just include it anywhere in the global scope of your file (i.e. not inside any function or class).

**Comment by EvilSmile88** [comment]
> Attach an event handler to the node.js process like this
> 
> ```
> process.on("uncaughtException", (error) => {
>      console.error("Uncaught Exception Description: ", error);
>      // process.exit(1); // uncomment this line if you want your application to close gracefully.
> });
> ```
> 
> Just include it anywhere in the global scope of your file (i.e. not inside any function or class). If you leave the last line commented, your node.js process won't crash. But it is really not advisable for production.

@udochify Thanks. But this approach looks like a workaround and I think such cases should be handled on the **ioredis** side.

**Comment by udochify** [comment]
ok. Have you tried putting the part where you call monitor in a try catch block, like this?

```js
const Redis = require("ioredis"); 

var redis = new Redis({host: 'localhost', port: 6379, username: 'alice'}); 

redis.on("connect", () => { 
    console.log('Connected to DB \n'); 
    try {
        redis.monitor((err, monitor) => { 
            console.log('Error', err) // You only logged the error here
            if (!err) { 
                monitor.on('monitor', (...args) => console.log(JSON.stringify(args))) 
            } 
        } catch (error) { // you caught and handled the error here
            console.error("Redis Client Monitor Exception ", error);
        }
    }); 
});
```
Usually, *catching* errors (and not just logging them to the console) handles them and allows execution to continue.

**Comment by EvilSmile88** [comment]
@udochify Yes, I tried) it doesn't help, the error does not fall into the catch block

**Comment by EvilSmile88** [comment]
@udochify By the way, did you manage to reproduce this issue? Or maybe it's just me having this problem?
