### ISSUE TITLE
DEBUG messages

### ISSUE THREAD

**Issue by gagle** [luin/ioredis#15]
This is just a question, it's not a request. Why are you using the `debug` module? IMO this is a really BAD practice. I have my own debugging system usign the DEBUG env variable and I don't want to have another module (`debug`) which I cannot control cluttering the stdout with messages that I have not asked for. Have you considered removing it?

**Comment by luin** [comment]
Hi gagle! I chose the `debug` module because there're already many libraries(3814 currently) depending on it. It's hard to avoid using all of these modules(Koa, Connect,Stylus, etc.) when writing a Node.js app. As for me it has been an accomplished fact to use `DEBUG` env to filter logs. However I'm open to suggestions and keep an open mind if you'd like to persuade me either way :)

**Comment by gagle** [comment]
I don't use Koa or anything related to Express, in fact I hate it. I'm using Hapi.

Personally I don't have any interest in knowing what is doing a module internally. Debugging messages should be controlled by the client because we tipically have a wrapper around these kind of modules to decouple as maximum as possible the cache usage and its actual implementation. One day I could change to node_redis or to memcached or whatever. This message `debug('received connection from sentinel');` doesn't give to me any valuable information, it doesn't help me to debug my server if something goes wrong. When using a third-party module I'm assuming that it is well-tested and is working, so I don't need to know that I'm connected to a "sentinel", in fact I don't know what a sentinel is and I don't care so much, I just want to "connect to redis to cache stuff".

**Comment by dirkbonhomme** [comment]
Correct me if I'm wrong, but this debug library is a noop unless activated right? And it's one of many packages created by TJ so they ain't come any better than this.

**Comment by gagle** [comment]
The problem comes when I want to use the DEBUG environment variable for my own purposes.

**Comment by dirkbonhomme** [comment]
Hmm makes sense. Maybe it's easy to disable the debug module in ioredis with a config flag?

**Comment by MarkHerhold** [comment]
I would like to take the opposite side here and **thank** the author for using the debug module. It makes debugging applications a lot easier and provides very adjustable logging.

Excluding the debug content is trivial. Simply add `-ioredis:*` to your DEBUG environment variable.
e.g. `DEBUG=some:stuff,-ioredis:*`

**Comment by dstroot** [comment]
I agree with @MarkHerhold !!   This is a standard module used in many places and I'm glad it is used here.

**Comment by tipiirai** [comment]
:+1: for using `debug`

**Comment by dginzbourg** [comment]
-ioredis:* didn't work for me, but ioredis:* did
