### ISSUE TITLE
Attempting to find key by value

### ISSUE THREAD

**Issue by HyptexPvP** [luin/ioredis#1508]
Im doing this
` let body = {
      username: req.body.username,
      email: hashedemail,
      password: hashedpassword,
      uuid: randomBytes(8).toString("hex"),
    }
  api.set(req.body.username, JSON.stringify(body))`

But I wanna find the email without the username any ideas?
idk how to use markdown forgive me

**Comment by luin** [comment]
Sorry we track feature requests or bug reports of ioredis here. You may want to post your questions on StackOverflow. Thanks for using ioredis!
