### ISSUE TITLE
keyPrefix and scan command

### ISSUE THREAD

**Issue by rchl** [luin/ioredis#1526]
I've set `keyPrefix` option to have common prefix for all items and not have to care about it but then I ran into an issue where the `scan` command returns items with the prefix included so I can't pass those directly to the `del` command as `del` expects no prefix.

Is that a bug?

**Comment by luin** [comment]
Hey @rchl 👋 

Actually it's the expected behavior and noted on https://github.com/luin/ioredis#transparent-key-prefixing (Please refer to `Warning`).

**Comment by rchl** [comment]
OK, understandable but also inconvenient as that means I have to ditch the `keyPrefix` option due to that.
