### ISSUE TITLE
Handle namespacing all redis commands [request]

### ISSUE THREAD

**Issue by ScheerMT** [luin/ioredis#153]
This was something new to me that I came across..

It is a convention to prefix your keys with some kind of namespace to help sort through them. However.. if you want a namespace across your whole application transparently.. that would be a bit more work.

There is a ruby implementation of this [Here](https://github.com/resque/redis-namespace).
Along with a node clone [Here](https://github.com/arschles/node-redis-namespace). 

Would this be something to be considered being added into the library? I know node's philosophy for packages is to make them small and concentrate on one thing and do it well. This may be breaking that idea to some purists but to many who are dealing with multi tenant redis usage this may help simplify things significantly! 

As always this should be an opt-in feature. Maybe adopt something similar to the ruby version where the existing ```var redis = new Redis();``` could be passed to something like ```var namespaceRedis = new RedisNamespace(redis, 'Appname');```

**Comment by luin** [comment]
Namespace is already supported, check out https://github.com/luin/ioredis#transparent-key-prefixing

**Comment by ScheerMT** [comment]
Yikes! I should have spent more time reading over the documentation. Thanks for making an awesome package :+1:

**Comment by luin** [comment]
:laughing:
