### ISSUE TITLE
API Documentation get 404 error

### ISSUE THREAD

**Issue by umuoy1** [luin/ioredis#1533]
http://luin.github.io/ioredis/

![image](https://user-images.githubusercontent.com/57709713/158338780-489c062e-6355-4ef4-8595-c815997c6f3e.png)

**Comment by marcbachmann** [comment]
@luin Does the setting need an update to reference the main branch? maybe it's still referring to v5.

**Comment by luin** [comment]
Yeah, it was the cause. Just updated the branch to main. @umuoy1 Thanks for pointing this out!

**Comment by umuoy1** [comment]
Thanks, the page was fixed. I will close this issue.
