### ISSUE TITLE
hmset in typescript object

### ISSUE THREAD

**Issue by sumanadak** [luin/ioredis#1536]
I tried to insert one simple object in typescript to ioredis hashmap. I define object like this

interface User {
name : string,
age :string
}

let newUser : User = {
name : "suman",
age :"34"
}
How do I write hmset command ?

**Comment by luin** [comment]
There's an example in README: https://github.com/luin/ioredis/blob/main/examples/hash.js#L13. Prior v5.x.x, you also need to install @types/ioredis since v5.0.0 is the first version ioredis provides native TypeScript declarations.

**Comment by luin** [comment]
```js
const redis = new Redis();

redis.hmset("hash", {
  name: "Bob",
  age: "20",
});
```

It works for me. `Redis` is a constructor so you need to follow the example to create an instance. Does it solve your issue?

**Comment by luin** [comment]
Closing as this should be resolved in v5.0.0. Feel free to reopen if the issue still exists.

**Comment by sumanadak** [comment]
dear luin,
I am sorry for late reply. I was not in town. Here is my problem. I created constructor of redis and tried pass this typescript object like this
interface User {
name : string,
age :string
}

let newUser : User = {
name : "suman",
age :"34"
}
let redis = new Redis()
when I try to do like this redis.hmset("user-hash",newuser)
it gives me a error. Asking either string or map. Cant we pass object like this ? May be I am doing something wrong. Can you please give me some example with typescript object with hmset as example ?

**Comment by luin** [comment]
Thanks for the follow-up. It's actually [a limit on TypeScript side](https://github.com/microsoft/TypeScript/issues/15300#issuecomment-891681234) that you can't assign an interface to a record:

```ts
interface User {
  name: string;
  age: string;
}

let newUser: User = {
  name: "suman",
  age: "34",
};

const record: Record<string, string> = newUser; // Error here
```

ioredis expects a `Record` for the parameter so that's why you got the error. I'm working on making ioredis accept any interface as well.

**Comment by sumanadak** [comment]
Dear luin,
Thanks a lot for this release. 

Thanks
Suman
