### ISSUE TITLE
How to dump key as buffer?

### ISSUE THREAD

**Issue by cweijan** [luin/ioredis#1541]
I need to dump the key as a buffer, but currently there is only an API for dump as a string, the dumped string cannot be used for restore, an error of `ERR DUMP payload version or checksum are wrong` will be occured when restore. 

I saw in this issue https://github.com/luin/ioredis/issues/222#issuecomment-167565186 that it seems to be possible to dump as buffer by api `dumpBuffer`, but I didn't find any code about this API in the code of this repository, whether there is a new alternative API?

**Comment by luin** [comment]
Hey @cweijan 👋 
It's supported and documented: http://luin.github.io/ioredis/classes/default.html#dumpBuffer

<img width="819" alt="CleanShot 2022-03-26 at 17 53 27@2x" src="https://user-images.githubusercontent.com/635902/160234308-648c5f23-46ac-436b-a4e3-0f6c0135be48.png">

If you are using a version prior to v5.0.0, `@types/ioredis` may not provide a declaration for `dumpBuffer`, but the library does support it.

**Comment by cweijan** [comment]
Thanks for the feedback, I do currently use ioredis4, I will try to migrate to ioredis5.

**Comment by cweijan** [comment]
I migrated to ioredis5 and it works perfectly now, Thanks.
