### ISSUE TITLE
The v5 Beta release says that it only works with Redis v3 or newer but it's not mentioned in the stable release anymore

### ISSUE THREAD

**Issue by bttger** [luin/ioredis#1547]
See here: https://github.com/luin/ioredis/releases/tag/v5.0.0-beta.1

The readme, the upgrade guide (v4 -> v5), and the changelog of the stable version 5 do not mention that they only work with Redis v3 or newer. Was this forgotten to update or is the new v5 still compatible with older Redis versions (2.6.12)?

**Comment by luin** [comment]
Updated the release note. Thanks for pointing this out! LMK if there's anything not clear.

**Comment by bttger** [comment]
Ok thanks!
