### ISSUE TITLE
Wrong typing for `maxRetriesPerRequest` in ioredis v5?

### ISSUE THREAD

**Issue by soulchild** [luin/ioredis#1550]
The [documentation states](https://github.com/luin/ioredis#auto-reconnect) that we may set `maxRetriesPerRequest` to `null` to get pre-v4 behaviour:

> Set maxRetriesPerRequest to null to disable this behavior, and every command will wait forever until the connection is alive again (which is the default behavior before ioredis v4).

Unfortunately, the types included in v5 only allow [`number` values](https://github.com/luin/ioredis/blob/2dfda0d2d5e1b01ed37fc5666aa301c9c3a07859/lib/redis/RedisOptions.ts#L89) for this option. Is this a bug?

**Comment by luin** [comment]
Yeah it's a bug. The option should accept `null`. Thanks for pointing this out!
