### ISSUE TITLE
Wrong return type for sendCommand.

### ISSUE THREAD

**Issue by cweijan** [luin/ioredis#1556]
The return value of sendCommand is unknown, but its actual return value is buffer.

![image](https://user-images.githubusercontent.com/27798227/160956845-c0bca1c0-bd44-4ef2-bdf7-c9ab37f74499.png)

**Comment by luin** [comment]
Hey @cweijan 👋 
`sendCommand()` is intended to be an internal method so that's one reason we don't give it a detailed type. Anyway the return type of `sendCommand()` depends on the context, in standalone context, it's a Promise, in pipeline context, it's a Pipeline instance.

**Comment by cweijan** [comment]
In ioredis4 I used send_command, but this method is gone.

**Comment by cweijan** [comment]
Ok, thanks.

**Comment by crobinson42** [comment]
Thanks @luin here's how ioredis@5 works for me after refactoring away from `send_command()`:
```
await redisClient.call('config', [
    'set',
    'notify-keyspace-events',
    'EKxg',
  ])
```
