### ISSUE TITLE
Validate maxRetriesPerRequest for Transactions

### ISSUE THREAD

**Issue by smriti-d** [luin/ioredis#1557]
Our application does 3 types of transactions. These 3 transactions, satisfy [these](https://github.com/luin/ioredis#transaction-and-pipeline-in-cluster-mode) requirements.

Now how to know and validate if maxRetriesPerRequest is valid for these transactions? How to check if these transactions which are critical to the business are actually being retried. 

Based on offline discussion with @luin, Transactions involving WATCH need to be retried on the application side. Not sure about other transactions without WATCH. 

```
// type 1
redis.client.multi([
        ['incrby', someKey, 1],
        ['expire', key, someTIME],
      ]).exec((redisErr, results) => {})

// type 2
redis.client.multi([
      ['set', someKey, 'true'],
      ['rpush', someLIST, 'xxx'],
      ['publish', someCHANNEL, JSON.stringify(xxx)],
    ]).exec((redisErr, results) => {})

// type 3 
WATCH mykey
val = GET mykey
val = val + 1
MULTI
SET mykey $val
EXEC

```

we are using ioredis client in cluster mode.

**Comment by luin** [comment]
You can enable the debug log `DEBUG=ioredis:* node yourapp.js` and try to shut down the Redis server and observe the logs.

I personally don't recommend using `WATCH` as it's pretty tricky. You probably want to use Lua scripting instead.

**Comment by luin** [comment]
`maxRetriesPerRequest` is only evaluated when the underlying connection to the server is down (aka on "close" event). It doesn't kick in in case of a transaction aborts (due to the syntax being wrong or a WATCH condition fails) or command errors (e.g. LPUSH a string key).
