### ISSUE TITLE
v5 does not re-exporting all the types correctly

### ISSUE THREAD

**Issue by abriginets** [luin/ioredis#1559]
Hello. I've recently upgraded to ioredis v5 and mentioned that many types are no longer exported or exported incorectly from the library. For example, I'm using NestJS for the backend and I don't like to make 3rd party library calls directly. Instead I prefer to wrap those calls into a separate injectable class so that there only will be a single instance of redis client for my app. And it's easier to test stuff by to mocking a class instead of 3rd party library calls. Previously I had a following method:
```ts
async set(key: Redis.KeyType, value: Redis.ValueType, expiry?: string, time?: number): Promise<'OK'> {
  if (expiry) {
    return await this.instance.set(key, value, expiry, time);
  }

  return await this.instance.set(key, value);
}
```
I was using `Redis.KeyType` and `Redis.ValueType` which are no longer exported from the library but are actually still defined in the [source code](https://github.com/luin/ioredis/blob/main/lib/utils/RedisCommander.ts#L3-L4).

Also `redis.pipeline()` call was returning `Redis.Pipeline` type which now is called `ChainableCommander`, but when I'm switching from
```ts
pipeline(): Redis.Pipeline {
  return this.instance.pipeline();
}
```
to
```ts
pipeline(): ChainableCommander {
  return this.instance.pipeline();
}
```
VSCode auto-imports it from `ioredis/built/utils/RedisCommander` which really looks ugly.

Is there a way to make new typings to act like those from `@types/ioredis`?

**Comment by luin** [comment]
Hey @abriginets 👋 

Going to expose those types in #1560. Let me know if there are any types missing.

**Comment by jliana-cksource** [comment]
Hi @luin, could you also expose `DNSLookupFunction`?

**Comment by luin** [comment]
Hi @jliana-cksource, just added it in https://github.com/luin/ioredis/pull/1560. Will release it next Monday.
