### ISSUE TITLE
Cluster: automatic nodes discovery not working with remote host

### ISSUE THREAD

**Issue by Adrien-P** [luin/ioredis#156]
My current setup is the following:  
I have a machine on IP 10.0.0.6 which hosts a redis cluster with 3 masters (ports 7000, 7001 and 7002) and 3 slaves (ports 7003, 7004, 7005).  
The client machine is on IP 10.0.0.7 and I pass the configuration:  
```
new Redis.Cluster([{
            port: 7000,
            host: "10.0.0.6"
        }], {db: 0});
```
the issue is that my redis node on port 7000 keeps receiving an unlimited amount of "info" requests but never receives the actual requests made within the client code. Looking at the code I think I found the source of the issue:  
In the method `Cluster.prototype.getInfoFromNode` there is a command `redis.cluster('slots',...` and the results of this command are like this:  
```
[ [ 0, 5460, [ '127.0.0.1', 7000 ], [ '127.0.0.1', 7003 ] ],
  [ 10923, 16383, [ '127.0.0.1', 7002 ], [ '127.0.0.1', 7005 ] ],
  [ 5461, 10922, [ '127.0.0.1', 7001 ], [ '127.0.0.1', 7004 ] ] ]
```
What happens is that the redis node on 10.0.0.6:7000 replies with the list of nodes that are part of the cluster but it reference them with their localhost address (127.0.0.1 instead of 10.0.0.6). Thus, ioredis tries to connect to theses nodes on 127.0.0.1 and keeps getting ECONNREFUSED (because the client machine does not host any redis instance).  

Note: I tried to pass all the nodes to the `Redis.Cluster` constructor and I experienced the same "info" loop issue

**Comment by AVVS** [comment]
Thats likely a problem with setting up your cluster

**Comment by Adrien-P** [comment]
If anyone has managed to setup ioredis with a cluster on another machine, I'd be happy to know your configuration

**Comment by luin** [comment]
Hi @Adrien-P 
Thanks for using ioredis. The redis servers running on the other machines returns 127.0.0.1 is because you bound the redis to the wrong network interface (in this case, `bind 127.0.0.1`).

You can refer to this issue for more details: https://github.com/antirez/redis/pull/1590/files.

**Comment by Adrien-P** [comment]
Hi @luin 

thanks a lot for your answer. `bind` is definitely the option I was looking for.   
For those interested I added this line to my redis.conf files for each node:  
`bind 10.0.0.6 127.0.0.1`

now it works well.
On a side note, we just moved to ioredis from node_redis mostly because of the support of Redis Cluster. The migration has been very easy

**Comment by luin** [comment]
:laughing:
