### ISSUE TITLE
ioredis v5 typescript error

### ISSUE THREAD

**Issue by andrevenancio** [luin/ioredis#1562]
Hi,
I'm using ioredis, upstash and I've updated to latest version. My typescript is flagging the  instance line with an error:
`No overload matches this call.`

```
import Redis from 'ioredis';
const redis = new Redis(process.env.REDIS_CONNECTION_STRING);
export default redis;
```

where `REDIS_CONNECTION_STRING` is following the example on upstash
and rediss://:PASSWORD@REGION-DOMAIN.upstash.io:PORT

I know this is probably an issue with upstash, but can I update my instance to

```
import Redis from 'ioredis';
const redis = new Redis(PORT, process.env.REDIS_CONNECTION_STRING_WITHOUT_PORT);
export default redis;
```

Is this the newest way?

**Comment by luin** [comment]
`process.env.REDIS_CONNECTION_STRING` may be undefined, which will make the statement look like:

```js
const redis = new Redis(undefined)
```

And there is no overload for this.

```js
import Redis from "ioredis";

if (!process.env.REDIS_CONNECTION_STRING) {
  throw new Error("Missing REDIS_CONNECTION_STRING");
}
const redis = new Redis(process.env.REDIS_CONNECTION_STRING);

export default redis;
```

Adding an assert fixes the issue.

Having said that seems we can add the support for `new Redis(undefined)` to make everything default. WDYT?

**Comment by andrevenancio** [comment]
Oh you are right!

I noticed that on upstash they do provide an example for node-redis

```
var client = redis.createClient ({
  host : '',
  port : '',
  password: ''
});
```
But on ioredis api there's no field for password right?

I think the solution you provided is fine, I wish typescript caught the error as a possible `undefined` instead of making me more confused.

Thank you for your help!

**Comment by andrevenancio** [comment]
Ah I missed that! I only say (port, host, options)

Thanks for clarifying.

Can I ask one last question? Did anything else changed on the API? here's an example I had that now complains about the `ex` parameter


```
export const GetCurrencies = async () => {
  const rkey = `${process.env.VERCEL_ENV?.slice(0, 3)}/currencies`;
  const jsonString: string | null = await redis.get(rkey);

  if (jsonString) {
    return JSON.parse(jsonString);
  }

  const response = await request(
    HASURA_ENDPOINT,
    GetCurrenciesQuery,
    {},
    { 'x-hasura-admin-secret': HASURA_SECRET }
  ).then((res) => res);

  if (response) {
    await redis.set(rkey, JSON.stringify(response!), 'ex', 600);
  }

  return response;
};
```

**Comment by andrevenancio** [comment]
Leaving it here for people who might find this. https://github.com/luin/ioredis/wiki/Upgrading-from-v4-to-v5

Thanks @luin you're a ⭐
