### ISSUE TITLE
ERR syntax error using KEEPTTL

### ISSUE THREAD

**Issue by ryanadhibit** [luin/ioredis#1563]
I got issue when using KEEPTTL to set my key with new value and get this message. Is there something that I could do to re-set my value with same key without changing ttl? 

```
ReplyError: ERR syntax error
    at parseError (\node_modules\redis-parser\lib\parser.js:179:12)
    at parseType (\node_modules\redis-parser\lib\parser.js:302:14) {
  command: {
    name: 'set',
    args: [
      'myKey',
      'myValue',
      'KEEPTTL',
      'XX'
    ]
  }
}
```

I am using https://github.com/adonisjs/redis which I believe it is using ioredis 5.0 (https://github.com/adonisjs/redis/releases/tag/v7.2.0)

**Comment by luin** [comment]
KEEPTTL was introduced in Redis 6.0. Using a server prior to that version can cause the issue. Is that your case?
