### ISSUE TITLE
 firstError: 'Error: read ETIMEDOUT\n    at _errnoException (util.js:1024:11)\n    at TCP.onread (net.js:615:25)' },

### ISSUE THREAD

**Issue by wooonhan** [luin/ioredis#1564]

**Comment by luin** [comment]
It's a network issue that is not related to ioredis. If you believe that is not the case, please provide a reproducible example.

**Comment by wooonhan** [comment]
The program has the master monitoring page and other monitoring pages. When the master monitoring page is activated, the other monitoring pages do not refresh data. When I switch to another monitoring page, the data cannot be obtained and is not refreshed. However, I switch back to the main monitoring page and the page is refreshed normally.
