### ISSUE TITLE
Is it possible to set the same ttl on all keys ?

### ISSUE THREAD

**Issue by bacloud22** [luin/ioredis#1565]
After research I think this is not provided by Redis.

Since **ioredis** persists connection, this could be possible technically, but does **ioredis** provides that ?

Thanks a lot 👍🏻

**Comment by luin** [comment]
You can iterate all keys with `redis.scanStream()` and call the `expire` command but they won't get exactly the same ttl as the scanning process takes time.

**Comment by bacloud22** [comment]
thank you @luin !! I'm using a solution that I picked from somewhere else
I'm using a pipeline and running `del` command like this

```js
function purgeRedis() {
    console.log('Redis purge is running')
    redisDB.keys('*').then((keys) => {
        const pipeline = redisDB.pipeline()
        keys.forEach(function (key) {
            pipeline.del(key)
        })
        return pipeline.exec()
    })
    // timeout by 3 hours
    setTimeout(purgeRedis, 3 * 1000 * 60 * 60)
}
if (process.env.worker_id == '1') purgeRedis()
```

Do you think it's fine ??

I'm closing as you already suggested a solution.

ty

**Comment by bacloud22** [comment]
following earlier discussion here I'm using `scan` and `unlink` instead

    function purgeRedis() {
        console.log('Redis purge is running')
        var stream = redisDB.scanStream({ match: '*' })
        stream.on('data', function (resultKeys) {
        // `resultKeys` is an array of strings representing key names.
            redisDB.unlink(resultKeys)
        })
        stream.on('end', function () {
            console.log('all keys have been visited')
        })
        // timeout by 3 hours
        setTimeout(purgeRedis, 3 * 1000 * 60 * 60)
    }
    if (process.env.worker_id == '1') purgeRedis()

Thanks again !

**Comment by luin** [comment]
LGTM. One thing is you may want to pause the stream while unblinking. Search `stream.pause` in the README.md for an example.

**Comment by bacloud22** [comment]
Thanks a lot @luin

**Comment by bacloud22** [comment]
For reference, this is my solution that seems working perfectly
```js
function purgeKeys(redisDB) {
    console.log('Redis purge is running')
    var stream = redisDB.scanStream({ match: '*' })
    stream.on('data', function (resultKeys) {
        stream.pause()
        if (resultKeys.length) {
            redisDB.unlink(resultKeys).then(() => {
                stream.resume()
            })
        }
    })
    stream.on('end', function () {
        console.log('all keys have been visited')
    })
}
```
