### ISSUE TITLE
`NatMap` is not exported properly

### ISSUE THREAD

**Issue by schw4rzlicht** [luin/ioredis#1567]
Hey there,

I am currently migrating from 4.x to 5.x in a typescript project and therefore following the migration guide and its chapter about ts errors.

I need the `NatMap` type and can only import it using

```typescript
import { NatMap } from "ioredis/built/cluster/ClusterOptions";
```

That works but I am unsure whether this could cause some side effects (in the future) or is just an inconvenience compared to importing it together with all other types like

```typescript
import Redis, { Cluster, ClusterOptions, RedisOptions } from "ioredis";
```

**Comment by luin** [comment]
In the latest version, `NatMap` is exported from the top-level so `import { NatMap } from 'ioredis'` should work.

**Comment by schw4rzlicht** [comment]
Yep, sorry to bother, in 5.0.4 everything works fine, thanks! 🙈
