### ISSUE TITLE
Type system disagrees!!!

### ISSUE THREAD

**Issue by LRagji** [luin/ioredis#1572]
Using v5.0.4 with typescript like below and the multi command fails in compilation
```
const y = [
            ["set", "foo", "bar"],
            ["get", "foo"],
        ];

        const result = await this.redisClient.multi(y)
            .exec();
```

Error reported build time:(wigly under y in multi method)

`
No overload matches this call.
  Overload 1 of 4, '(options: { pipeline: false; }): Promise<"OK">', gave the following error.
    Argument of type 'string[][]' is not assignable to parameter of type '{ pipeline: false; }'.
      Property 'pipeline' is missing in type 'string[][]' but required in type '{ pipeline: false; }'.
  Overload 2 of 4, '(options: { pipeline: true; }): ChainableCommander', gave the following error.
    Argument of type 'string[][]' is not assignable to parameter of type '{ pipeline: true; }'.
      Property 'pipeline' is missing in type 'string[][]' but required in type '{ pipeline: true; }'.
  Overload 3 of 4, '(commands?: [name: string, ...args: unknown[]][]): ChainableCommander', gave the following error.
    Argument of type 'string[][]' is not assignable to parameter of type '[name: string, ...args: unknown[]][]'.
      Type 'string[]' is not assignable to type '[name: string, ...args: unknown[]]'.
        Source provides no match for required element at position 0 in target.ts(2769)
`

Where as following works without any issue:

`
 const result = await this.redisClient.multi([
            ["set", "foo", "bar"],
            ["get", "foo"],
        ])
            .exec();
`

What am i doing wrong ?

**Comment by luin** [comment]
Hi @LRagji 👋 

You are not doing anything wrong. It's should be a bug on ioredis's TypeScript declaration. Going to fix it in the next version.

For now, there are two workarounds:

```ts
const y: [name: string, ...args: string[]][] = [
  ["set", "foo", "bar"],
  ["get", "foo"],
];

const result = await this.redisClient.multi(y).exec();
```

Or 

```ts
const result = await this.redisClient.multi([
    ["set", "foo", "bar"],
    ["get", "foo"],
  ])
  .exec();
```

**Comment by LRagji** [comment]
Thanks @luin for confirming, i am using 3rd option `//@ts-ignore` 😜

**Comment by luin** [comment]
Aha I should have mentioned it. Actually you should use `// @ts-expect-error` so you can get notified once it's not needed.
