### ISSUE TITLE
Engine CPU utilization of 1 shard spike upto 100% while load test

### ISSUE THREAD

**Issue by SK-CSE** [luin/ioredis#1574]
i have a clustered Redis in AWS with 3 shard and no replica, while doing load test, Engine CPU utilization of 1 shard spike upto 100% while Engine CPU utilization of the other 2 shards is 4% and 5% respectively. on running Monitor command got the below line very frequently  while count of my GET command is 9318186 while `grep "evalsha" | wc -l` return count of 18479850

` "evalsha" "0f0f23b9048b36752b5be114f35ish083449f908" "1" "undefined" "4db174ac2c7ah6386687727bccdad00f"
16835506623.1783958 [0 lua] "get" "undefined"` i got this very frequently in the 1st shard

while in another shard the count of my GET command is 78527 and `grep "evalsha" | wc -l` return count of 12889
 i'm using ioredis to connect to all my shards tried like below
`const cluster = new Redis.Cluster([
  {
    port: 6380,
    host: "127.0.0.1",
  },
  {
    port: 6381,
    host: "127.0.0.1",
  },
]);`   and redlock to accuire lock on keys

**Comment by SK-CSE** [comment]
i found the root cause of the issue, it was the `retryDelay`  parameter of redlock. so closing this issue

**Comment by wchensc** [comment]
Hi @SK-CSE , could you elaborate more about the `retryDelay` param. What was the issue and how you resolved it. Thanks
