### ISSUE TITLE
hgetall with multi doesn't return hash object but array instead

### ISSUE THREAD

**Issue by morfies** [luin/ioredis#158]
Hi,
if I use only :
redis.hgetall("my key", function(err, obj){
//here  obj is a js Object with key:value pairs. eg. {a:"1", b:"2"}
})
but when I use hgetall with multi:
var multi = redis.multi();
...
multi.hgetall("my key");  //may be in a loop
...
multi.exec(function(err, replies){
//results in replies are not hash Objects but arrays instead. eg: ["a", "1", "b", "2"]
});

Can you tell me if this is a problem or just a design so.
Thanks

**Comment by luin** [comment]
Command replies transforming is not supported in transaction (`multi`) currently. Since this feature breaks backwards compatibility, it will be implemented in 2.0.0
