### ISSUE TITLE
on('messageBuffer', ...)  returns strings

### ISSUE THREAD

**Issue by Jerenaux** [luin/ioredis#1581]
The [documentation](https://github.com/luin/ioredis#pubsub) indicates that when using `on('messageBuffer', (channel, data) => ...)`, "Both `channel` and `message` are buffers.". 

I tried using that, publishing a `Buffer` to a channel:
```
const buffer = Buffer.from("I'm a string!", 'utf-8');
redisPublisher.publish('buffer-test', buffer);
```

But in `on('messageBuffer',`, the types of both `channel` and `data` are strings. This is exactly the same behavior as in `on('message',`, which doesn't seem like the expected behavior?

If it is, I'd be interested in more information about how to pubsub buffers and not having them automatically parsed a strings, in case I want to encode something else than strings.

**Comment by luin** [comment]
Hey @Jerenaux 👋 ,

I just tried but it works as expected on my side:

```js
const sub = new Redis();
const pub = new Redis();

async function main() {
  sub.subscribe("abc");
  sub.on("messageBuffer", console.log);

  pub.publish("abc", Buffer.from("hi"));
}

main();
```

It logs:

```
<Buffer 61 62 63> <Buffer 68 69>
```

My ioredis version is 5.0.0. Did I miss anything?

**Comment by Jerenaux** [comment]
My bad, going over it more systematically starting from your code snippet above, it seems to work, not sure why it failed for me. I think I was mislead by the fact that I was using ```console.log(`... ${data} ... `)``` calls, which automatically converted th buffers to strings, sorry for the inconvenience!

**Comment by luin** [comment]
No worries. Closing.
