### ISSUE TITLE
Typescript woes with Pipeline

### ISSUE THREAD

**Issue by pvogel1967** [luin/ioredis#1584]
ioredis 4, the "Redis.Pipeline" type had a "length" parameter, so I could do things like this:

```
    async executePipeline(pipeline: Redis.Pipeline): Promise<[Error | null, any][]> {
        if (pipeline.length < 1) {
            this.logger.warn('Got zero length pipeline to execute');
        }
        const t0 = performance.now();
        const res = await pipeline.exec();
        const t1 = performance.now();
        Math.random() < 0.1 && this.logger.info({ timeTaken: t1 - t0, length: pipeline.length }, `Executed cache pipeline`);
        return res;
    }
```

In ioredis 5 there doesn't seem to be a way to check the length of the pipeline?  This is a problem because I have several places where I'm doing a bunch of work in a loop, pumping it into a pipeline and when the length hits a threshold doing an `await pipeline.exec()`, then creating a fresh pipeline and the loop continues...

**Comment by luin** [comment]
Hey @pvogel1967 👋 

The `length` parameter still exists on v5 and it's an overlook that we don't provide a declaration for it. You can use it with `// @ts-expect-error` to suppress the warning and we will add the missing declarations in the next version.

**Comment by pvogel1967** [comment]
Thanks @luin!
