### ISSUE TITLE
type declaration of `setBuffer` argument requires 'GET'

### ISSUE THREAD

**Issue by cnwangjie** [luin/ioredis#1586]
The generated type declaration of `setBuffer` method argument requires providing a 'GET'. It should be optional.

https://github.com/luin/ioredis/blob/91ed2d817ac3ca304d6dbe97823594dc5eee2181/lib/utils/RedisCommander.ts#L6611-L6627

current version: 5.0.5

**Comment by luin** [comment]
Hey @cnwangjie 👋 

You can call `set` if you don't need to `GET` parameter. -`Buffer` variant is only used when you need to reply to be returned as a Buffer, whereas without `GET`, the result is always `OK` so there is no need to use the variant.

**Comment by cnwangjie** [comment]
Hi @luin,

Thank you for your prompt reply. It's Helpful that your description of the `Buffer` suffix in README. I guess many people have misunderstood it and made mistakes that they are used to passing a `Buffer` object as an argument. 🤣
