### ISSUE TITLE
Redis#status value not reflecting redis connection status and always remains "connecting"

### ISSUE THREAD

**Issue by ujjwalgarg1995** [luin/ioredis#1597]
We are initiating Redis connection using:

`this._redisClient = new Redis.Cluster(nodes, {
        enableReadyCheck: true
      });
`
No matter what (if connection is closed or ready) `this._redisClient.status` value is "connecting". 

I believe there is some bug in the library.

**Comment by luin** [comment]
Can you enable the debug mode and post the logs here? I got "ready" with following code:

```js
const redis = new Cluster([30001], { enableReadyCheck: true });

async function main() {
  setInterval(() => {
    console.log(redis.status);
  }, 1000);
}

main();
```

**Comment by francescov1** [comment]
Im getting this too. Wondering whats the recommended way to set a timeout so that the connection stops retrying after a certain amount of time. connectTimeout doesnt work for this

**Comment by luin** [comment]
@francescov1 Not sure if you need retryStrategy https://github.com/redis/ioredis#auto-reconnect
