### ISSUE TITLE
'Redis' cannot be used as a value because it was exported using 'export type'

### ISSUE THREAD

**Issue by ansf** [luin/ioredis#1603]
Trying to update my project from ioredis 4.x to ioredis 5.0.6.

Using typescript 4.7.3 I see the following error:

`'Redis' cannot be used as a value because it was exported using 'export type'.ts(1362)`

Reproducer:

```
import { Redis } from "ioredis";

const redis = new Redis();
```

Any idea what I am doing wrong?

**Comment by luin** [comment]
It should be `import Redis from 'ioredis'`. Refer to https://github.com/luin/ioredis/wiki/Upgrading-from-v4-to-v5 for details.

**Comment by ansf** [comment]
Oops, I must have overlooked that part.

Thanks! :)
