### ISSUE TITLE
How to handle expired event with multiple node instances?

### ISSUE THREAD

**Issue by wststone** [luin/ioredis#1609]
Here is an implementation to handle the expired with the pub/sub model
```js
function main() {
	const redisPub = new IORedis();
	const redisSub = new IORedis();
	redisPub.config("SET", "notify-keyspace-events", "KEx");

	redisSub.psubscribe("__keyevent@?__:expired", err => {
		if (err) {
			console.log("err => ", err);
		}
	});

	redisSub.on("pmessage", (pattern,channel, message) => {
		console.log(`Received pattern ${pattern} message ${message} from ${channel}`);
                // Business Logic
	});

        // Tests
	setInterval(() => {
		redisPub.setex(Math.round(Math.random() * 1000).toString(), 3, "123");
	}, 2000);
}
```
the problem is, when i have multiple node instances, i receive the same event on each instance and trigger the event handler multiple times.
Are there any good solution to this?

**Comment by luin** [comment]
Hey @wststone 👋 

This is out of the scope of ioredis. You may want to use an event queue or something to ensure only one instance handles the event.
