### ISSUE TITLE
 [ioredis] Unhandled error event: ParserError: Protocol error, got "\r" as reply type byte. Please report this.

### ISSUE THREAD

**Issue by MariusMez** [luin/ioredis#1617]
Hi, using current version, I have this error, don't know why?

`[ioredis] Unhandled error event: ParserError: Protocol error, got "\r" as reply type byte
        at handleError (/.../node_modules/redis-parser/lib/parser.js:190:15)
        at parseType (/.../node_modules/redis-parser/lib/parser.js:304:14)`

**Comment by brenwell** [comment]
Did you ever discover the cause?

**Comment by luin** [comment]
Hey @MariusMez 👋 

In my experience, most of the time this error is due to some proxies or customized Redis servers. could this be your cause?

**Comment by MariusMez** [comment]
Hi @luin thank you for your answer, I have a standard install on my mac using homebrew.
I don't know why this error occurs, but seems solved for now (maybe an update of redis solve this, current version installed : 7.0.3).

I can close the issue, thanks
