### ISSUE TITLE
classCallCheck.js:3 Uncaught (in promise) TypeError: Cannot call a class as a function

### ISSUE THREAD

**Issue by HongLouyemeng** [luin/ioredis#1623]
I am combining IOredis with streamlit. The execution of a separate script of the code is successful, but the execution will fail after embedding streamlit
```
import Redis from 'ioredis';
let myredis = new Redis(conn)
```

**Comment by luin** [comment]
I don't think this is an issue on ioredis so closing this. Feel free to reopen with more details. Thanks for using ioredis!
