### ISSUE TITLE
Redis parser 'ReplyError: ERR wrong number of arguments for 'spop' command'

### ISSUE THREAD

**Issue by winnie-development** [luin/ioredis#1627]
Hi guys,

I have been having a strange issue with Redis lately. My Redis cache works fine on my Mac (Node v 14.19.0 with npm v6.14.16 and redis 7.0.2)

However, when I revert to Windows with my project (I replicated the environment using node 14.19.0 running Redis on WSL Ubuntu version 7.0.2) - I come across this error when ever I attempt to run a command that attempts to fetch something from my cache:

`ReplyError: ERR wrong number of arguments for 'spop' command
    at parseError (C:\Users\Me\Documents\...\node_modules\redis-parser\lib\parser.js:179:12)
    at parseType (C:\Users\Me\Documents\...\node_modules\redis-parser\lib\parser.js:302:14)
[Nest] 20504  - 30/07/2022, 11:11:22 pm   ERROR [ExceptionsHandler] ERR wrong number of arguments for 'spop' command
ReplyError: ERR wrong number of arguments for 'spop' command
    at parseError (C:\Users\Me\Documents\...\redis-parser\lib\parser.js:179:12)
    at parseType (C:\Users\Me\Documents\...\node_modules\redis-parser\lib\parser.js:302:14)`

It doesn't appear when I run `dbflush` i.e. using an empty Redis db, but something is causing this strange behaviour on my Windows and I am unsure why. I've tried running the same Node, using Docker on my Windows to run Redis amongst other things which have not worked. Any help would be appreciated!

**Comment by winnie-development** [comment]
@luin Thanks for your response. Do you know exactly which redis versions support the `spop` parameters? I did try and go for the same major version but perhaps it also comes down to minor releases as well.

**Comment by luin** [comment]
It was supported back in v3.2.0. https://redis.io/commands/spop/. Closing this.
