### ISSUE TITLE
Pub/Sub bug

### ISSUE THREAD

**Issue by KMatuszak** [luin/ioredis#1629]
Subscribing to the same channel again after unsubscribing from it causes messages being received as many times as subscribed to that channel before.

1. Subscribe
// messages received only one (as expected)
2. Unsubscribe
// messages not received at all (as expected)
3. Subscribe
// messages received twice (expected only one)
4. Unsubscribe
// messages not received at all (as expected)
5. Subscribe
// messages received three times (expected only one)
etc...

**Comment by luin** [comment]
Hey @KMatuszak 👋 

Thanks for the details. I tried to reproduce it on my side but it works as expected. Is there anything I missed? Thanks!


```js
const Redis = require("ioredis");

const sub = new Redis();
const pub = new Redis();

sub.on("message", (channel, message) => {
  console.log(`Received ${message} from ${channel}`);
});

sub.subscribe("abc", () => {
  sub.unsubscribe("abc");
  sub.subscribe("abc", () => {
    console.log("ready");
    pub.publish("abc", "hello");
  });
});
```

I got the following output:

```
ready
Received hello from abc
```

It only logged one "Received".

**Comment by KMatuszak** [comment]
It works using your code, I was using something like:
```js
const Redis = require("ioredis");

const sub = new Redis();
const pub = new Redis();

const test = () => {
  sub.subscribe("abc");
  sub.on("message", (channel, payload) => {
    console.log(channel, payload);
  });
};

test();

setInterval(() => {
  pub.publish("abc", "test" + Date.now());
}, 1000);

setTimeout(() => {
  sub.unsubscribe("abc");
  setTimeout(() => {
    test();
  }, 3000);
}, 3000);
```

Then I realized that what I expected was that after unsubcribing and subscribing again, the callback of `sub.on("message")` from first subscription will not be fired on second subscription, and this probably is wrong expectation. This worked for me on `node-redis` because over there callback is assigned to specific subscription, not to all. Maybe it's worth mentioning about that in the docs?

Anyway sorry about wasting your time.

**Comment by luin** [comment]
That makes sense. `Redis` instance itself is an EventEmitter. `sub.on('message', callback)` is calling a method defined in EventEmitter and has nothing to do with subscription status. You can use `sub.off('message', callback)` to unsubscribe.

Will think about updating the docs. Closing this. Feel free to lmk if there are other questions.
