### ISSUE TITLE
how expire key with callback

### ISSUE THREAD

**Issue by i5ting** [luin/ioredis#163]
```
var Redis        = require('ioredis');
redis = new Redis();

var key = 'expire_test';
var content ='content'
var timeout = 10;

redis.multi()
.set(key, content)
.expire(key, timeout, function(){
  console.log('out');
})
.exec(function(err) {
  if(err) {
    console.error("Failed to publish EXPIRE EVENT for " + content);
    console.error(err);
    return;
  }
});
```

like this?

```
.expire(key, timeout, function(){
  console.log('out');
})
```

**Comment by luin** [comment]
The callback of `expire` will be invoked when the command is queued instead of executed  (so that the result of the callback would always be `QUEUED`). Or you can just set the timeout using the `SET` command:

```javascript
redis.set(key, content, 'EX', timeout, function (err, res) {

});
```

**Comment by i5ting** [comment]
it is a common way with no readability, is it a better way for resolve this problem?

**Comment by luin** [comment]
咦？啥问题？为啥需要 callback 呢

**Comment by i5ting** [comment]
终于逼出中文了，哇哈哈，

expire用法基本就2种吧

- 缓存，限制xx秒，然后判断是否存在即可
- 延时任务,比如10s后干点啥，和Keyspace Notifications类似

**Comment by luin** [comment]
是想通过 callback 获取到键过期的事件吗

**Comment by albin3** [comment]
感觉这里callback的一般理解是expire设置成功了没有…

**Comment by i5ting** [comment]
语义上，expire - n秒 - 到期之后回调处理，这样是合理的吧?

**Comment by luin** [comment]
所有命令的 callback 值都是命令本身的结果，没有对任何命令做特殊化处理，这样有利于保证语义的统一，也和其他的 redis client 对齐。另外 Redis 没法实现 expire 到期后的通知提醒，所以这个理论上也没法实现。

**Comment by albin3** [comment]
redis有个键到期提醒…[这个?](http://redis.io/topics/notifications)，需要自己新建一个redis订阅连接，单连接好像实现不了，可以玩一下。。不知道跟其他定时任务比怎么样…

**Comment by luin** [comment]
这个没法实现到期提醒，只能实现删除提醒。比如 expire 一个键 100 秒过期，Redis 不会恰好在第一百秒删除这个键，而是在下一次访问这个键或者后台垃圾回收时才会真正删除它

**Comment by albin3** [comment]
大神！👍

**Comment by 965283058** [comment]
ioreis API提供 expire这个方法吗？

**Comment by sunheartGH** [comment]
同问，redis删除提醒的api有么？某些键过期后想删除一些关联的数据需要用到这个特性

**Comment by damianobarbati** [comment]
Hey guys, can you explain what's the final behaviour? 

```
redis.set(key, content, 'EX', timeout, function (err, res) {
 is this execute right when the key is EXPIRED?
});
```

**Comment by ccs018** [comment]
The anonymous callback function is executed when the SET command has been completed, not when the key is EXPIRED.  I don't believe that there is any notification available to clients when a key has been expired.

**Comment by luin** [comment]
No. It will be executed immediately right after the redis handled the command.

Get Outlook<https://aka.ms/qtex0l> for iOS
________________________________
