### ISSUE TITLE
Docs examples don't work with Typescript in ESM project

### ISSUE THREAD

**Issue by tobiasmuehl** [luin/ioredis#1632]
I actually had to do this to get started

```ts
import Redis from 'ioredis'
const redis = new Redis.default()
```

or 

```ts
import { default as Redis } from 'ioredis'
const redis = new Redis()
```

using just `new Redis()` results in Typescript error:

```
This expression is not constructable.
  Type 'typeof import("node_modules/ioredis/built/index")' has no construct signatures.ts(2351)
```

**Comment by luin** [comment]
Hey @tobiasmuehl 👋 ?

What ioredis version are you using? If you are using v5.x and have @types/ioredis installed, removing @types/ioredis should fix the issue.

**Comment by tobiasmuehl** [comment]
Woah, that was fast! 🚀 

This is on version ioredis@5.2.2, without having `@types/ioredis` installed.

**Comment by tobiasmuehl** [comment]
In case you want to replicate:

`package.json`
```json
{
  "name": "ioredis-esm-test",
  "version": "0.0.1",
  "main": "index.js",
  "license": "MIT",
  "type": "module",
  "dependencies": {
    "ioredis": "^5.2.2"
  },
  "devDependencies": {
    "@sindresorhus/tsconfig": "^3.0.1"
  }
}

```

`tsconfig.json`
```json
{
	"extends": "@sindresorhus/tsconfig"
}
```


```
❯ tsc -v                   
Version 4.7.4

❯ node -v           
v16.14.2
```

**Comment by luin** [comment]
Oh I see. Your project is ESM so `import Redis from 'ioredis'` will make `Redis` a namespace. You have to use `import { default as Redis } from "ioredis"` as you mentioned. Will think about a fix or add a notice to README.

**Comment by tobiasmuehl** [comment]
Not a big deal we we've already found the solution but hopefully this issue can be helpful for other developers while the fix is in development. Feel free to close this issue.

**Comment by rvrita** [comment]
Thanks for the quick fix, this helped me.
