### ISSUE TITLE
The property 'options.family' must be one of: 0, 4, 6. Received '6'

### ISSUE THREAD

**Issue by dan003400** [luin/ioredis#1633]
We are receiving this error on startup in our latest deploy (we are only seeing this in production).

```js
import IORedis from "ioredis";

const REDIS_URL = process.env.CHECKOUTS_REDIS_URL || "redis://127.0.0.1:6381";

export default new IORedis(REDIS_URL, { family: 6 });
```

The only way I am able to reproduce this is by including `?family=6` in the REDIS_URL

**Comment by luin** [comment]
I think this has already been resolved in https://github.com/luin/ioredis/pull/1673 so closing.
