### ISSUE TITLE
How do I know if I provided an incorrect password?

### ISSUE THREAD

**Issue by naugtur** [luin/ioredis#164]
`new Redis(options)` with options.password being incorrect or missing, doesn't throw (not surprising, AUTH is async) and it doesn't emit `end` nor `close`, nor `error`.

How do I know if the AUTH command that happens in the background failed?

[edit]
It works if I call `.auth` myself, but otherwise, the error is swallowed. I even found one location which might be responsible for swallowing it: https://github.com/luin/ioredis/blob/master/lib/redis.js#L124

But switching to lazyConnect and connecting on my own would also resolve happily without reporting auth issues, so that's not all there is to it.

[one more edit]
Unfortunately, calling `.auth` on my own is not possible, because a "Ready check" is made, and it fails because auth was not made yet... So no workaround here.

**Comment by luin** [comment]
Yes, we may emit an event when the password is wrong. May be `auth error`.

**Comment by naugtur** [comment]
So for the workaround to work:

`enableReadyCheck: false` in options is required, then:
```js
redisInstance.on("connect", function () {
    redisInstance.auth("pawsword", function (err, res) {
        if (err) {
            console.error(err);
            redisInstance.disconnect()
            process.exit();

        }

    })
});
```

But I'd appreciate a way to catch the initial built-in auth failure. 

```js
redisInstance.on("error",function(authError){})
```
^would be the way to go imho

**Comment by luin** [comment]
`error` event is a special event that would crash the app if there's no listener for it. I would go for another event name like `auth error`. :laughing:

**Comment by naugtur** [comment]
Well, I'm on this camp that prefers when errors have to be handled ;) but ok.
If I can suggest something I'd not put a space in the event name for the sake of people coming from jQuery where it means 2 events ;)
