### ISSUE TITLE
zrange rev withscores

### ISSUE THREAD

**Issue by akshay-kumar11** [luin/ioredis#1662]
@luin 
client.zrange(key, 0, -1, "REV", "WITHSCORES") is giving following error in ioredis ver: 4.17.3. Redis Server version: 5.0.6 AWS Elastic Cache Redis Cluster.

connection code:
`const client = new Redis.Cluster([ { host: env.redis.host, port: env.redis.port, } ],{ redisOptions: { tls: { checkServerIdentity: () => undefined } } });`

ReplyError: ERR syntax error at parseError (workspace/node_modules/redis-parser/lib/parser.js:179:12) at parseType (workspace/node_modules/redis-parser/lib/parser.js:302:14) { command: { name: 'zrange', args: [ 'tophit_hi_IN', '0', '-1', 'REV', 'WITHSCORES' ] } }

can you please help.

**Comment by TysonAndre** [comment]
https://redis.io/commands/zrange/ you're using redis server version 5.0.6. You'd need redis server 6.2.0 or newer to use that

Alternately, use https://redis.io/commands/zrevrange/ instead

https://redis.io/commands/zrange/

> History
> **Starting with Redis version 6.2.0: Added the REV,** BYSCORE, BYLEX and LIMIT options.
