### ISSUE TITLE
TTL for every key

### ISSUE THREAD

**Issue by stychu** [luin/ioredis#1666]
Hello, Is it possible to configure ioredis with auto expiry for every created key without explicitly setting expiry key time or expiry with command??

Ideally I would like to set TTL for 24hr when making a connection to redis and every command would be set automatically that 24hr expire time and I would not need to think about it for every command/key.

Is it possible ?

**Comment by luin** [comment]
No you have to do it manually as Redis doesn't support it out of the box.
