### ISSUE TITLE
Get ECONNREFUSED when redis-server master shuts down

### ISSUE THREAD

**Issue by dandanknight** [luin/ioredis#167]
Hi all, probably not a bug, but something strange in my setup/code. I hope you can help anyway.

I've been using Kue with node-redis-sentinel successfully for a while, but recently a PR has appeared on the Kue page adding ioredis support, which I'm excited about as the node-redis-sentinel page itself says they ioredis should be used in it's place.

I'm successfully connecting to the sentinels, and can create/process jobs on the queue, so seems to be working generally. My issue is, when I stop a redis-server instance, so that another becomes master, ioredis is crashing with an ECONNREFUSED.

My connection code is as follows....

```javascript
KueUtils.prototype.connect = function () {
    exports.Queue = q = kue.createQueue({
        redis: {
            createClientFactory: this._createClient

        }
    });
};

KueUtils.prototype._createClient = function () {

    var redis = new Redis(
        {
            sentinels: [
                {
                    host: '192.168.49.49',
                    port: 26379
                },
                {
                    host: '192.168.49.50',
                    port: 26379
                }
            ],
            name     : 'mymaster',
            showFriendlyErrorStack: true
        });

    redis.on('ready', function(){
        console.log("Redis Ready");
    });

    redis.on('reconnecting', function(){
        console.log("Reconnecting to Redis");
    });

    redis.on('connect', function(){
        console.log("Connected to Redis");
    });

    return redis;
};
```

I've enabled debug, and the output is....

```
/Users/dan/WebstormProjects/serviceAPI_ioredis/node_bunyan.sh api/bin/www
[2015-09-30T13:51:26.487Z]  INFO: pdlApi/23859 on Dans-MacBookPro: Logger created - Level 'debug'
Wed, 30 Sep 2015 13:51:26 GMT ioredis:redis status[localhost:6379]: [empty] -> connecting
Wed, 30 Sep 2015 13:51:26 GMT ioredis:redis status[192.168.49.49:26379]: [empty] -> connecting
Wed, 30 Sep 2015 13:51:26 GMT ioredis:redis queue command[0] -> sentinel(get-master-addr-by-name,mymaster)
Wed, 30 Sep 2015 13:51:26 GMT ioredis:redis status[localhost:6379]: [empty] -> connecting
Wed, 30 Sep 2015 13:51:26 GMT ioredis:redis status[192.168.49.49:26379]: [empty] -> connecting
Wed, 30 Sep 2015 13:51:26 GMT ioredis:redis queue command[0] -> sentinel(get-master-addr-by-name,mymaster)
Wed, 30 Sep 2015 13:51:26 GMT ioredis:redis queue command[0] -> subscribe({q}:events)
[2015-09-30T13:51:26.764Z]  INFO: pdlApi/23859 on Dans-MacBookPro: ============================= Service API started ====================================
[2015-09-30T13:51:26.764Z]  INFO: pdlApi/23859 on Dans-MacBookPro: 
[2015-09-30T13:51:26.765Z]  INFO: pdlApi/23859 on Dans-MacBookPro: Version: v0.2.4
[2015-09-30T13:51:26.765Z]  INFO: pdlApi/23859 on Dans-MacBookPro: Config: config/development.json
[2015-09-30T13:51:26.765Z]  INFO: pdlApi/23859 on Dans-MacBookPro: Arch: x64
[2015-09-30T13:51:26.765Z]  INFO: pdlApi/23859 on Dans-MacBookPro: PID: 23859
[2015-09-30T13:51:26.765Z]  INFO: pdlApi/23859 on Dans-MacBookPro: API Port: 3000
[2015-09-30T13:51:26.765Z]  INFO: pdlApi/23859 on Dans-MacBookPro: Hostname: Dans-MacBookPro
[2015-09-30T13:51:26.765Z]  INFO: pdlApi/23859 on Dans-MacBookPro: UberDebug: true
[2015-09-30T13:51:26.765Z]  INFO: pdlApi/23859 on Dans-MacBookPro: Node: v0.12.7
[2015-09-30T13:51:26.765Z]  INFO: pdlApi/23859 on Dans-MacBookPro: 
[2015-09-30T13:51:26.765Z]  INFO: pdlApi/23859 on Dans-MacBookPro: ======================================================================================
Listening on port 3000 as process 23859
Wed, 30 Sep 2015 13:51:26 GMT ioredis:redis status[192.168.49.49:26379]: connecting -> connect
Wed, 30 Sep 2015 13:51:26 GMT ioredis:redis status[192.168.49.49:26379]: connect -> ready
Wed, 30 Sep 2015 13:51:26 GMT ioredis:connection send 1 commands in offline queue
Wed, 30 Sep 2015 13:51:26 GMT ioredis:redis write command[0] -> sentinel(get-master-addr-by-name,mymaster)
Wed, 30 Sep 2015 13:51:26 GMT ioredis:redis status[192.168.49.49:26379]: connecting -> connect
Wed, 30 Sep 2015 13:51:26 GMT ioredis:redis status[192.168.49.49:26379]: connect -> ready
Wed, 30 Sep 2015 13:51:26 GMT ioredis:connection send 1 commands in offline queue
Wed, 30 Sep 2015 13:51:26 GMT ioredis:redis write command[0] -> sentinel(get-master-addr-by-name,mymaster)
Connected to Redis
Redis Ready
Wed, 30 Sep 2015 13:51:26 GMT ioredis:redis status[localhost:6379]: connecting -> connect
Wed, 30 Sep 2015 13:51:26 GMT ioredis:redis write command[0] -> info()
Wed, 30 Sep 2015 13:51:26 GMT ioredis:redis status[192.168.49.49:26379]: ready -> close
Wed, 30 Sep 2015 13:51:26 GMT ioredis:connection skip reconnecting since the connection is manually closed.
Wed, 30 Sep 2015 13:51:26 GMT ioredis:redis status[192.168.49.49:26379]: close -> end
Wed, 30 Sep 2015 13:51:26 GMT ioredis:redis status[192.168.49.49:26379]: ready -> close
Wed, 30 Sep 2015 13:51:26 GMT ioredis:connection skip reconnecting since the connection is manually closed.
Wed, 30 Sep 2015 13:51:26 GMT ioredis:redis status[192.168.49.49:26379]: close -> end
Wed, 30 Sep 2015 13:51:26 GMT ioredis:redis status[localhost:6379]: connect -> ready
Wed, 30 Sep 2015 13:51:26 GMT ioredis:connection send 1 commands in offline queue
Wed, 30 Sep 2015 13:51:26 GMT ioredis:redis write command[0] -> subscribe({q}:events)
Wed, 30 Sep 2015 13:51:27 GMT ioredis:redis status[localhost:6379]: connecting -> connect
Wed, 30 Sep 2015 13:51:27 GMT ioredis:redis write command[0] -> info()
Wed, 30 Sep 2015 13:51:27 GMT ioredis:redis status[localhost:6379]: connect -> ready
Connected to Redis
Redis Ready
close to Redis
Reconnecting to Redis
close to Redis
Reconnecting to Redis
Wed, 30 Sep 2015 13:51:44 GMT ioredis:redis status[localhost:6379]: ready -> close
Wed, 30 Sep 2015 13:51:44 GMT ioredis:connection reconnect in 2ms
Wed, 30 Sep 2015 13:51:44 GMT ioredis:redis status[localhost:6379]: close -> reconnecting
Wed, 30 Sep 2015 13:51:44 GMT ioredis:redis status[localhost:6379]: ready -> close
Wed, 30 Sep 2015 13:51:44 GMT ioredis:connection reconnect in 2ms
Wed, 30 Sep 2015 13:51:44 GMT ioredis:redis status[localhost:6379]: close -> reconnecting
Wed, 30 Sep 2015 13:51:44 GMT ioredis:redis status[localhost:6379]: reconnecting -> connecting
Wed, 30 Sep 2015 13:51:44 GMT ioredis:redis status[192.168.49.50:26379]: [empty] -> connecting
Wed, 30 Sep 2015 13:51:44 GMT ioredis:redis queue command[0] -> sentinel(get-master-addr-by-name,mymaster)
Wed, 30 Sep 2015 13:51:44 GMT ioredis:redis status[localhost:6379]: reconnecting -> connecting
Wed, 30 Sep 2015 13:51:44 GMT ioredis:redis status[192.168.49.50:26379]: [empty] -> connecting
Wed, 30 Sep 2015 13:51:44 GMT ioredis:redis queue command[0] -> sentinel(get-master-addr-by-name,mymaster)
Wed, 30 Sep 2015 13:51:44 GMT ioredis:redis status[192.168.49.50:26379]: connecting -> connect
Wed, 30 Sep 2015 13:51:44 GMT ioredis:redis status[192.168.49.50:26379]: connect -> ready
Wed, 30 Sep 2015 13:51:44 GMT ioredis:connection send 1 commands in offline queue
Wed, 30 Sep 2015 13:51:44 GMT ioredis:redis write command[0] -> sentinel(get-master-addr-by-name,mymaster)
Wed, 30 Sep 2015 13:51:44 GMT ioredis:redis status[192.168.49.50:26379]: connecting -> connect
Wed, 30 Sep 2015 13:51:44 GMT ioredis:redis status[192.168.49.50:26379]: connect -> ready
Wed, 30 Sep 2015 13:51:44 GMT ioredis:connection send 1 commands in offline queue
Wed, 30 Sep 2015 13:51:44 GMT ioredis:redis write command[0] -> sentinel(get-master-addr-by-name,mymaster)
Wed, 30 Sep 2015 13:51:44 GMT ioredis:connection error: Error: connect ECONNREFUSED
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: connect ECONNREFUSED
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1010:19)
ERROR Redis { [Error: connect ECONNREFUSED]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect' }

Process finished with exit code 0
```

I'm confused where the ECONNREFUSED is coming from, as both sentinels are still up and running. Can anyone offer some advice please? I have a feeling it has to do with the ```localhost:6379``` but I'm unsure where this is coming from, as the redis-servers are both on separate servers.

Many thanks.

**Comment by luin** [comment]
It seems a little strange since ioredis doesn't emit error event if there's no listener for it. Which version of Kue (or which git branch) are you using? I'll check it out and see what I can do.

**Comment by dandanknight** [comment]
Hi luin, thanks for taking the time to read and reply. The branch I'm testing against is found at https://github.com/Automattic/kue/tree/b53e4751e1c86a1006380eb07ae1c378865dc7ea

**Comment by luin** [comment]
`ECONNREFUSED` error is caused by connecting to an unreachable address.

In your case, when the master is offline, the sentinel won't promote one of the slaves to the master immediately. Instead, sentinels will wait for several seconds before promoting (see the following config).

So that when the master is down, ioredis will ask the sentinels for the new master address, and still get the address of the offline master, which will cause the `ECONNREFUSED` error when ioredis connect to it.

Normally when connecting failed, ioredis will emit an `error` event [**if there's at lease one listener to it**](https://github.com/luin/ioredis/blob/master/lib/redis/event_handler.js#L94-L99) and reconnect again. When used with kue however, kue would listen to the `error` event of ioredis and [re-emit it](https://github.com/Automattic/kue/blob/master/lib/kue.js#L331-L333), which will crash your application. The workaround is add a listener to the `error` event.

```
# Number of milliseconds the master (or any attached slave or sentinel) should
# be unreachable (as in, not acceptable reply to PING, continuously, for the
# specified period) in order to consider it in S_DOWN state (Subjectively
# Down).
#
# Default is 30 seconds.
sentinel down-after-milliseconds mymaster 30000
```

**Comment by dandanknight** [comment]
Ahhh, ok. Seems so obvious now you explain it like that. Thank you so much for your help. I'll add a handler to the Kue error today and let you know how I get on. Thanks again.

**Comment by dandanknight** [comment]
Hi again, changes made, and works perfectly now. It is successfully failover to the new master after the timeout set in the config, and now, I also have a load of nice events telling me the connection status, unlike the previous module I used! Thanks for your time.

**Comment by luin** [comment]
Cool! :laughing:

**Comment by SainiSK** [comment]
Hi, I am not sure if this relates to here, but I am getting 

> ECONNREFUSED

 error while connecting to Redis server on Windows 10 64-bit. The details are as below:

I have tried below scenarios, with Windows firewall disabled and (all antivirus programs are disabled ):
**Case 1.**

- Redis Server v3.0.501 x64 (build using MSVS 2013 Update 5, taken source code from here)
- Redis config with loglevel = 'debug' 
- Windows 10 x64 updated till date.
- Redis client written for Node.js 'node_redis' (npm install redis@2.5.3).

**Case 2.**

- Redis Server v3.0.501 x64 (build using MSVS 2013 Update 5, taken source code from here)
- Redis config with loglevel = 'debug' 
- Windows 10 x64 updated till date.
- Redis client 'redis-client.exe' x64.


**Case 3.**

- Redis Server v2.8.21 x64
- Redis config with loglevel = 'debug' 
- Windows 10 x64 updated till date.
- Redis client written for Node.js 'node_redis' (npm install redis@2.5.3)


**Case 4.**

- Redis Server v2.8.21 x64
- Redis config with loglevel = 'debug' 
- Windows 10 x64 updated till date.
- Redis client 'redis-client.exe' x64.

**Result:**
Result of all above cases was same as explained below:
 => 0 clients connected in server's debug console.
 => Getting ECONNREFUSED error in client console.
 => Not able to access x64 redis server by any of above mentioned cases
 => Accessing 'localhost:6379' in browser, Server's console displays 1 client connected (which I don't think is a useful to me).

**Case 5.**
 > Redis Server v2.8.21 x64
 > Redis config with loglevel = 'debug' 
 > Windows 7 x64 updated till date.
 > Redis client written for Node.js 'node_redis' (npm install redis@2.5.3). 

**Result:** of this case was successful connection with redis server. But I had to move from Windows 7 x64 to Windows 10 x64 as I upgraded my system. So, I want to access redis server on win 10 x64.

**Case 6.** 
 > Redis Server v3.0.501 (Win32/x86)
 > Redis config with loglevel = 'debug' 
 > Windows 10 x64 updated till date.
 > Redis client written for Node.js 'node_redis' (npm install redis@2.5.3) 
    OR 
    Redis client 'redis-client.exe' x64
    OR
    Redis client 'redis-client.exe' x86

**Result:** I am able to connect and use Redis Server in this case.

COULD YOU PLEASE EXPLAIN A WAY TO USE REDIS SERVER'S 64-BIT VERSION ON WINDOWS 10 X64 MACHINE. I DON'T WANT TO RUN A 32-BIT REDIS SERVER.
