### ISSUE TITLE
Being able to compare response as case insensitive for some cases (where string is returned).

### ISSUE THREAD

**Issue by boazsade** [luin/ioredis#1671]
Hello
I'm a contributor to an open source project called [Dragonfly](https://github.com/dragonflydb/dragonfly).
This project is meant to be the next generation of Redis - in the sense that it would be a drop in replacement for Redis with a modern and better usage of the host resources. 
As part of our efforts we would like to integrate the tests from your project by running you tests as part of the CI pipeline because we see you as a good reference.
Our issue right now is that in same of the tests you are expecting to get in the response, a string returned as lower case (for example you're sending "set foo bar" and on the monitor connection you expecting to see the same list of strings, but in our case, we would return it back as "SET foo bar" - i.e. the command you return always in upper case. 
1. Our understand is that compare should be case insensitive - is this assumption is correct? if not we may need to change on our side, if we are right
2. I have a fix that I can PR on to you code to enable comparing these cases to be case insensitive
3. Please advice
Thanks

**Comment by luin** [comment]
Hey @boazsade 👋 

For my testing, Redis always returns the command as is so if you send `set` you get `set`, and for `Set` you get `Set`. Are you able to mimic the behavior on your side?

**Comment by boazsade** [comment]
Thanks for the replay (did you looked into our project? we would really like to bring someone like you on board). Anyhow, I know that REDIS returns the exact same string case wise, it just that we are working internally a little bit differently than they are, and by the time we are returning the result to the client, the command is change to upper case, I was just wondering whether it is acceptable (you have more experience than me working with Redis), and if it acceptable I can PR a "fix" for this - I don't claim for this to be a bug on your side, Thanks

**Comment by luin** [comment]
Yeah I have heard about Dragonfly and it's great. I'm okay with a PR for that.

**Comment by boazsade** [comment]
Thanks - I will submit soon - very happy to be able to contribute for your great project

**Comment by boazsade** [comment]
thanks
