### ISSUE TITLE
lpush callback - should be optional?

### ISSUE THREAD

**Issue by razboo** [luin/ioredis#1674]
Hi,

I'm using TypeScript and was wondering if lpush callback should be required (like it is now) when I'm using promises, or it's a mistake in the types.

**Comment by luin** [comment]
Hi @razboo 👋 

callbacks are definitely optional when working with Promises, and we have tests for it: https://github.com/luin/ioredis/blob/main/test/typing/commands.test-d.ts#L7-L9. Let me know if that is not your case.

**Comment by razboo** [comment]
Hi @luin,

I'm using lpush command but from what I see in RedisCommander, it seems that the callback param is not optional (as opposed to other commands which have optional callbacks)
![image](https://user-images.githubusercontent.com/6779977/199725995-5c080c9e-76ae-4cec-80e0-be9840185872.png)

I'm getting a compile error there after upgrading from 4 -> 5

**Comment by luin** [comment]
The second lpush signature doesn't have callback so it should fit your need.

**Comment by razboo** [comment]
@luin I missed the usage of the rest parameter. Thanks!
