### ISSUE TITLE
[Question] ioredis vs node_redis syntax

### ISSUE THREAD

**Issue by MrMMorris** [luin/ioredis#168]
Hi,

1. thanks for creating such an awesome, fully featured redis client.
2. Are you aware of any differences in syntax between `ioredis` and https://github.com/NodeRedis/node_redis?

I want sentinel functionality, but I need to know how much refactoring I should expect from the migration.

Thanks!

**Comment by luin** [comment]
You may refer to https://github.com/luin/ioredis/wiki/Migrating-from-node_redis

**Comment by MrMMorris** [comment]
oh well haven't you thought of everything.

Thanks! and sorry for not RTFM
