### ISSUE TITLE
Set & Get atomic operation

### ISSUE THREAD

**Issue by avivshafir** [luin/ioredis#1682]
with `node-redis` I can make the following call
`const val = await client.set("foo", "test", { EX: 10, GET: true });`

and get the old value stored in the foo key.
I tried with this library like this:

`const val = await client.set("foo", "test", "EX", 10, "GET");`
but it doesn't seem to work

**Comment by luin** [comment]
Hey @avivshafir 👋

The command looks correct. Does your Redis server version support the syntax? You can run the monitor command to confirm.

**Comment by avivshafir** [comment]
Redis server v=7.0.5
But as I mentioned the operation works with `node-redis`
I will double check again with `ioredis` just to make sure

**Comment by avivshafir** [comment]
@luin ok thanks, I might had local mistakes because of enabling `enableAutoPipelining`
and the command wasn't actually sent while debugging.
Thanks
