### ISSUE TITLE
Keep alive property is typed as undefined in RedisOptions

### ISSUE THREAD

**Issue by wildewouter** [luin/ioredis#1684]
`RedisOptions` has the `keepAlive` property from `CommonRedisOptions` and from `TcpSocketConnectOpts`

The only overlapping type is `undefined` here so this can not be set on the config.

**Comment by luin** [comment]
Hey @wildewouter 👋 

I don't see `keepAlive` is defined in `TcpSocketConnectOpts` or maybe I missed something?
