### ISSUE TITLE
Mismatch types in set vs get

### ISSUE THREAD

**Issue by davidhu2000** [luin/ioredis#1685]
Looks like `set` allows the value to be `number | string`, but `get` only returns string

```ts
RedisCommander<{ type: "default"; }>.set(key: RedisKey, value: string | number | Buffer, callback?: Callback<"OK"> | undefined): Promise<"OK">
RedisCommander<{ type: "default"; }>.get(key: RedisKey, callback?: Callback<string | null> | undefined): Promise<string | null>
```

a simple repro

```ts
import Redis from 'ioredis';

const redis = new Redis({
  password: process.env.REDIS_PASSWORD,
  host: process.env.REDIS_HOST,
});

redis.set('key', 1);
redis.set('key', 'hi');

const value = await redis.get('key'); // value is string | null
```

I think set and get should match in type, so get should also be returning type number. 

ioredis 5.2.4

I think generics would be great to use here. So when I initialize Redis, I can set a type. for example 

```ts
const redis = new Redis<string>({});
const redis = new Redis<number>({});
```

**Comment by davidhu2000** [comment]
```
127.0.0.1:6379> set key 1
OK
127.0.0.1:6379> get key
"1"
```

learn something new every day. It's all just strings so the type is correct. Altho now I'm wondering if the `set` function shouldn't take number so get/set still match.

**Comment by luin** [comment]
Hey @davidhu2000 👋 

It's for convenience that ioredis accepts numbers and auto converts them to strings before sending to Redis.
