### ISSUE TITLE
scanStream returns full keys with transparent prefix

### ISSUE THREAD

**Issue by nopjmp** [luin/ioredis#169]
data stream even is returning all keys with the prefix in the transparent prefix mode.

    var redis = new Redis({ keyPrefix: "prefix:" })
    redis.set("test1", "test")
    redis.set("test2", "test")
    var stream = redis.scanStream({ match: '*' })
    stream.on('data', (result) => {
        result.forEach(console.log)
    });
    stream.on('end', () => { console.log("done") })

**Comment by luin** [comment]
Hi @nopjmp, the result is correct since the keys in the redis is `prefix:test1` and `prefix:test2` instead of `test1` and `test2`. I don't think ioredis should strip away the prefix before returning since there are many other commands return key names (e.g. `KEYS`), strip away the prefix in only one command will make people confused.

**Comment by nnfans** [comment]
so what is the purpose of having key prefix if the result is not consistent?
and for alternative like `KEYS` command it block the redis since it single threaded

**Comment by nnfans** [comment]
so, if the usage is not consistent between function. What is the purpose of having key prefix in the first place ?
and for alternative like `KEYS` command it block the redis since it single threaded

**Comment by landerton** [comment]
I think the problem is the match doesn't add the prefix, but the data results do.

```
var redis = new Redis({ keyPrefix: "prefix:" })
redis.set("test1", "test")
redis.set("test2", "test")
var stream = redis.scanStream({ match: `prefix:test*` })
stream.on('data', (result) => {
    result.forEach(console.log)
    // prefix:prefix:test1, prefix:prefix:test2
});
stream.on('end', () => { console.log("done") })
```
