### ISSUE TITLE
How can I call a command with redis.call which won't wrap by quotes 

### ISSUE THREAD

**Issue by localhost443** [luin/ioredis#1691]
Hello, I want to write some custom Redis JSON commands and wish to add LIMIT after it. but redis.call command simply wrapping my LIMIT query under quotes too. How to get rid of it. 

My command: FT.SEARCH idx:tasks "@labels:{619f668a333141a9d9a078e3 | 619f668a333141a9d9a078c8}" LIMIT 10 30
in IOREDIS: redis.call("FT.SEARCH", "idx:tasks", "@labels:{619f668a333141a9d9a078e3 | 619f668a333141a9d9a078c8}",  "LIMIT 10 30") which is not working. as LIMIT is being wrapped by a "quotes"

Thank you a lot.

**Comment by luin** [comment]
Hey @localhost443 👋 

It should be `"LIMIT", 10, 30` instead of `"LIMIT 10 30"`.
