### ISSUE TITLE
Can't resolve 'tls', 'net', and 'dns' when connecting to redis host

### ISSUE THREAD

**Issue by NorkzYT** [luin/ioredis#1698]
According to the discussion that follows, build failures prevented me from using the following code.

https://github.com/vercel/next.js/discussions/44435

```js
  const handleApiTokenChange = async (e) => {
    // Set the value of the textarea element in the component's state
    setApiToken(e.target.value);

    // Set the value of the 'apiToken' key in Redis
    const redis = new Redis({
      host: 'redis', // Redis host
      port: '6379', // Redis port
    });

    await redis.set('apiToken', e.target.value);
  };
```

Errors:
```
build: ./node_modules/.pnpm/ioredis@5.2.4/node_modules/ioredis/built/cluster/ClusterOptions.js
build: Module not found: Can't resolve 'dns' in
build: ./node_modules/.pnpm/ioredis@5.2.4/node_modules/ioredis/built/connectors/SentinelConnector/index.js
build: ./node_modules/.pnpm/ioredis@5.2.4/node_modules/ioredis/built/cluster/util.js
build: Module not found: Can't resolve 'net' in 
build: Module not found: Can't resolve 'tls' in
```

What is the proper method to put this up, since I believe I did this incorrectly?

**Comment by luin** [comment]
`dns` module is only available on backend. Does you code run on backend?

**Comment by NorkzYT** [comment]
Understood, I have the code on the FrontEnd. How would I transfer the code to the BackEnd to do what is listed in the following discussion?

I tried using `getServerSideProps`, although I was not able to set the contents of the `textarea` to the Redis Cache for a reason I do not know.

https://github.com/vercel/next.js/discussions/44435

**Comment by luin** [comment]
I have little knowledge of this so maybe you want to refer to Next.js community for suggestions.

**Comment by NorkzYT** [comment]
Understood, thank you mate!

**Comment by Eddie2111** [comment]
terribly sorry for being this late since I didn't tried this. 
If you are using page router on NextJS,
use this approach,

- under API folder, create a folder named `utils` and create a file named Redis.js or Redis.ts 
- use ioRedis to create the connection, and then import the variable (best if you could use singleton approach)
- use it in the api and DO NOT USE the variable outside of API folder.

If you are using App Router,
tons of options, but do this if no other way around,

- create a folder named `util`
- create Redis.ts or Redis.js and create the connection
- only use it in 'Use server'. Do not call it in 'use client' file even if you are using server actions. dns, tls or net is not available there.

**Comment by Phenzic** [comment]
Hi @NorkzYT I'm having the same issue with NextJs.... 
Did [this](https://github.com/redis/ioredis/issues/1698#issuecomment-1858843462) solve the problem

**Comment by NorkzYT** [comment]
@Phenzic 

Yes, it did.

**Comment by Eddie2111** [comment]
> Hi @NorkzYT I'm having the same issue with NextJs.... Did [this](https://github.com/redis/ioredis/issues/1698#issuecomment-1858843462) solve the problem ?

Redis instance has to be connected from server side and not client side. Use "use server" at the top of the file where you redis connection exists.

**Comment by f22hd** [comment]
> terribly sorry for being this late since I didn't tried this. If you are using page router on NextJS, use this approach,
> 
> * under API folder, create a folder named `utils` and create a file named Redis.js or Redis.ts
> * use ioRedis to create the connection, and then import the variable (best if you could use singleton approach)
> * use it in the api and DO NOT USE the variable outside of API folder.
> 
> If you are using App Router, tons of options, but do this if no other way around,
> 
> * create a folder named `util`
> * create Redis.ts or Redis.js and create the connection
> * only use it in 'Use server'. Do not call it in 'use client' file even if you are using server actions. dns, tls or net is not available there.

moving `redis` file to `api` folder has been solved the issue, then you call it as standard endpoint.
