### ISSUE TITLE
what does hget return an array?

### ISSUE THREAD

**Issue by z1haze** [luin/ioredis#1719]
This is more of a question for why hget in ioredis returns an array like it does. Example below.

```js
const x = {id: 1, name: 'z1haze'};
const y = {id: 2, name: 'stephen'};

const pipeline = redis.pipeline();

pipeline.hset('people', x.id, JSON.stringify(x));
pipeline.hset('people', y.id, JSON.stringify(y));

const results = await pipeline.exec(); // [[null, "{"id": 1, "name": "z1haze"}"],[null, "{"id": 2, "name": "stephen"}"]]
```

Why is the result for each hget an array of length 2, where the first index is always null, and the second index always contains the value that I want? This makes for extra processing needing to be done to aggregate everything into an array. I'm new to redis, so please if I'm missing something, let me know, but when I test this in the redis-cli, the response looks just like i'd expect it should (a single value response)

**Comment by luin** [comment]
This first element is the error: https://github.com/luin/ioredis#transaction
