### ISSUE TITLE
How to unbind listener?

### ISSUE THREAD

**Issue by JSteunou** [luin/ioredis#173]
There is a `on` method to listen on some events, but where is the `off` method?

I have to create / destroy / re-create new instance with other parameters. I find a `quit` to proper quit with the first instance, but does it also unbind listeners?

**Comment by luin** [comment]
Redis instance is extended from EventEmitter: https://nodejs.org/api/events.html#events_emitter_removealllisteners_event

**Comment by JSteunou** [comment]
Ho thank you for that quick response, exactly what I needed!
