### ISSUE TITLE
[question|feature] sentinel commands

### ISSUE THREAD

**Issue by UglyBarnacle** [luin/ioredis#1745]
we use the recommended way of connecting to sentinels in Java and just migrated our nodejs wrapper, but couldn't find a function for those commands, so we fell back to the call() command (thanks for that).

https://redis.io/docs/reference/sentinel-clients/

Any plans on andding those commands (sentinel masters, sentinel sentinels master, and so on) to make full featured full featured. Or simply enlighten me if my capabilites are not enough to find the proper function.

**Comment by luin** [comment]
Not sure if it's a documentation issue but `sentinel` commands are available. An example can be found at https://github.com/luin/ioredis/blob/main/lib/connectors/SentinelConnector/index.ts#L245.
