### ISSUE TITLE
Clarification on automatic channel resubscription behavior

### ISSUE THREAD

**Issue by wunderb1t** [luin/ioredis#1760]
I would like to request clarification regarding the automatic channel resubscription behavior in the ioredis library. After reviewing the documentation, I couldn't find explicit information stating that channels will be automatically resubscribed after a reconnection.

Can someone from the community or the ioredis team confirm whether ioredis handles the automatic resubscription of channels after a reconnection? If it does, could you please point me to the relevant documentation or provide an example of how this behavior can be utilized? If automatic resubscription is not supported, what is the recommended approach for handling channel resubscription after a disconnection?

I appreciate any insights or guidance regarding this matter. Thank you!

**Comment by luin** [comment]
There's no documentation for this yet I believe but yeah ioredis resubscribes all channels after a reconnection and there's nothing you need to do explicitly to make it work.

A PR would be welcome to update the documentation.
