### ISSUE TITLE
unexpected that there is no Module entry for "/usr/src/app/node_modules/ioredis/built/index.js" in require.cache

### ISSUE THREAD

**Issue by sibelius** [luin/ioredis#1762]
unexpected that there is no Module entry for "/usr/src/app/node_modules/ioredis/built/index.js" in require.cache

when building with webpack

**Comment by luin** [comment]
Can you create a reproducible example for it? I think there should be some issues in the webpack configuration. Note that ioredis only works in Node.js environment so it's rare that you need to use a bundler to build the project.

**Comment by sibelius** [comment]
it was related to elastic-apm-node
