### ISSUE TITLE
存取中文乱码 ？

### ISSUE THREAD

**Issue by pangguoming** [luin/ioredis#179]
我今天测试了下，将键值都设为中文，出现乱码

**Comment by zhuangya** [comment]
可以贴一下出问题的代码嘛

**Comment by luin** [comment]
node 的字符串都是 utf8 的，而 redis 本身没有字符串的概念。所以可以检查下原始值是不是 utf8 字符串。

```javascript
var redis = new Redis();

redis.set('键', '值');
redis.get('键', console.log); // 值
```

**Comment by pangguoming** [comment]
sorry, 是我用的Redis查看工具乱码。 
@luin  能给我你的QQ吗？ 我从cnodejs.org 上问过你

**Comment by luin** [comment]
有问题可以直接发我邮件，QQ 用的没有邮件频繁，所以邮件回复会快很多

**Comment by pangguoming** [comment]
哦，谢谢
