### ISSUE TITLE
Change of redis cluster master does not update in the node application using ioredis

### ISSUE THREAD

**Issue by saltukalakus** [luin/ioredis#18]
I have a cluster of 3 redis and 3 sentinels. To make the test simple I have installed all of them in the same machine in the following ports

Redis 1,2,3 : localhost 6379, 6380, 6381
Sentinel 1,2,3: localhost 26379, 26380, 26381

Initially redis master is  configured  at port 6379 in redis and sentinel conf files.

To test master fail over to another slave instance say 6380, from redis-client I have configured new master with below command

SLAVEOF localhost 6380

I have configured my app's ioredis setup as below. After SLAVEOF changes Node application does not automatically switch to new master, as I expect this to be transparent to the application

    var options = {sentinels: [{ host: 'localhost', port: 26379 }, { host: 'localhost', port: 26380 },  
    { host:     'localhost', port: 26381 }],
    name: 'mymaster'};

    // required for passport sessions
    app.use(session({
        store: new RedisStore({ client: new Redis(options) }),
        secret: sessionConf.secret
    }));

From redis-client I can observe that the master is now switched to 6380. But from application logs I can see write error as I am trying to write to slave redis in this case at port 6379. I am not sure if this is a problem of ioredis or I am configuring redis incorrectly

I am using the redis and sentinel confs in this location => https://github.com/saltukalakus/xuser/tree/master/infra/redis

**Comment by luin** [comment]
You shouldn't make a master to be a slave of one of it's slaves. Say 6380 is the slave of 6379, you shouldn't call `SLAVEOF localhost 6380` on 6379 because it will make these two nodes both be the slave of each other, which doesn't make any sense.

Actually you shouldn't call `SLAVEOF` manually to trigger a failover in a sentinel cluster, instead you can kill 6379 and the failover will happen automatically.

**Comment by saltukalakus** [comment]
Actually initially I had tried that, but in the same machine killed redis instance quickly gets up so master does not change. I will check in a more real setup, may be more than 1 machine. If I observe an issue I will let you know. Thanks.

**Comment by luin** [comment]
Please also let me know if there's no issue :-)

Sent from Outlook




On Mon, Apr 27, 2015 at 10:50 AM -0700, "Saltuk Alakus" <notifications@github.com> wrote:












Actually initially I had tried that, but in the same machine killed redis instance quickly gets up so master does not change. I will check in a more real setup, may be more than 1 machine. If I observe an issue I will let you know. Thanks.

**Comment by saltukalakus** [comment]
Sure :)
