### ISSUE TITLE
建议提供一个将字符串内嵌入参数的好办法

### ISSUE THREAD

**Issue by pangguoming** [luin/ioredis#181]
像： redis.get(city+":"+busname+":"+id+":DriverId"）；这样连接字符串来拼凑Key很麻烦。

我之前做过一个下面这样项目， 参数值keyword会自动替换query字符串中 {keyword}。这样就不用硬拼字符串了
var cypher_params = {
keyword: params.keyword+’.*’
};

var query = [
    'MATCH (station)',
    'WHERE station.name =~ {keyword}',
    'RETURN station'
].join('\n');

**Comment by luin** [comment]
直接用
```javascript
redis.get(`${city}:${busname}:${id}:DriverId`)
```
就好了，没必要造轮子。

**Comment by pangguoming** [comment]
@luin 
没有看明白 ${} 是什么意思，怎么把变量嵌入到那个字符串中的？ 
var city="北京";
console.log('${city}.......');
这样好像不行， 初学者请指教

**Comment by luin** [comment]
https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/template_strings

**Comment by pangguoming** [comment]
thanks.
