### ISSUE TITLE
command read & write timeout

### ISSUE THREAD

**Issue by senarukana** [luin/ioredis#183]
I don't see timeout configurations in any commands. Am I wrong?

**Comment by luin** [comment]
Per-command timeout is not supported but under discussion. Refer to #61 for more information.

**Comment by senarukana** [comment]
Then do you have any ideas that which nodejs client that supports this feature?

**Comment by luin** [comment]
No client supports this feature as far as I know :-(. Dose `timeout` method provided by bluebird (`redis.set('foo', 'bar').timeout(5000)`) works for you?

**Comment by luin** [comment]
Closing this in favour of #61.
