### ISSUE TITLE
Question: does it work with ES6 promises?

### ISSUE THREAD

**Issue by herby** [luin/ioredis#187]
README says: "works with bluebird promises". Does it mean it is bound to bluebird's imlpementation or does it work with plain ES6 promises available in node4+ / polyfilled via `require('es6-promise').poiyfill()`?

**Comment by luin** [comment]
ioredis use bluebird's Promise implemention instead of the native one for better performance and more features. Since the former is a superset of the latter, it's no problem to use ioredis with ES6 promises.
