### ISSUE TITLE
Publish (possibly other things?) triggers an error if callback argument is explicitly undefined

### ISSUE THREAD

**Issue by dmfay** [luin/ioredis#188]
Code:
```javascript
    var pub = new Redis();
    pub.publish('foo', 'bar', undefined);
```

Stack trace:
```
Unhandled rejection ReplyError: ERR wrong number of arguments for 'publish' command
    at ReplyParser._parseResult (/Users/dianfay/work/ioredis/lib/parsers/javascript.js:39:14)
    at ReplyParser.execute (/Users/dianfay/work/ioredis/lib/parsers/javascript.js:139:20)
    at Socket.<anonymous> (/Users/dianfay/work/ioredis/lib/redis/event_handler.js:90:22)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
```

It looks like `generateFunction` in commander.js could be tweaked to decrease `length` if callback is undefined but I'm not sure what all else that could affect.

**Comment by luin** [comment]
Yes, ioredis considers all `undefined`s as empty strings. What's your use case to explicitly pass an `undefined`?

**Comment by dmfay** [comment]
Rather than make the publisher itself available across our app we've kept it inside a single module which exports a function `publish (channel, message, callback)` that just passes what it gets directly to ioredis (we were formerly using ortoo/node-redis-sentinel which didn't have a problem, but it's deprecated). So if our publish function is invoked with two arguments, it passes `undefined` on to ioredis.

It's easy enough to work around it by checking the callback we're passed and invoking `Redis.publish` with two or three arguments depending, but it is a little annoying.

**Comment by luin** [comment]
That makes sense. However, some people rely on the fact that `undefined` and `null` will consider as empty string. For example, `redis.set('user.name', user.name);`, where `user.name` is `undefined`, sends `SET user.name ""` to redis. If we just pop all `undefined`s, the command will fail.

**Comment by dmfay** [comment]
Yeah, I tried making that change in `generateFunction` myself and it didn't go too well. Your example of `redis.set` is the sort of thing where I'd expect to have to pass an empty string explicitly, although Redis is pretty different from the relational databases I'm more accustomed to working with.

I think it might be possible to support both cases by augmenting the definitions in commands.js: if a command is defined as taking a callback, then in situations where the number of arguments passed matches the already-defined arity *but* the last argument is `undefined` it should be safe to pop that one.

**Comment by luin** [comment]
The arity defined in commands.js is not reliable since it may differ in different Redis versions (commands in newer version may receive more arguments, e.g. `SET`), and some commands' arity are even dynamic.

**Comment by dmfay** [comment]
ah, that's too bad. At least working around it isn't too painful.
