### ISSUE TITLE
高负载的时候会出现数据错误！！

### ISSUE THREAD

**Issue by rrfeng** [luin/ioredis#189]
开始是 ioredis + redis，因为准备加更多的缓存，所以换成了 codis。开始是正常的，直到某次代码更新，增加了大量的缓存数据。然后一直都会出现奇怪的错误，比如 get 一个数字，却返回了一串字符，总之返回的不是想要取的数据。在最简单的 redis.get("key") 代码里也会出现……
同时伴随着 node 内存使用会增加很多（大部分会这样），我们以为是 codis 的问题，于是又把 codis 换回到原生的 redis 了。
这时候已经正常了（或者还有低概率发生这种情况但是没有发现，因为从 redis 取一段数据存到另一个地方可能并不会报错，类型被自动转换了之类的）。

直到昨天服务上整体的访问量翻了 N 倍，突然又爆发出来这个问题。我们用的 sentry，会一直出现各种奇怪的 cast 错误……比如把一串 json string cast 到 _id ，总之是和上面一样的问题。而且会集中爆发在一个或几个特定的 node 实例上，重启即可正常。
现在只能怀疑 ioredis 的 异步处理方式是不是在高负载下并不能保证正确的工作？因为 redis 协议的实现方式正确性基本依赖于一一对应的命令和应答，然而在 ioredis 里接收到应答是放到一个队列里（并没有仔细看源码，但好像大体是这么写的），然后通过 command send 的队列回调取去对应的数据，所以如果中间丢失了一段的话，那么这个 connection 之后的所有数据都会串掉……

这个问题非常可怕。。。。

**Comment by luin** [comment]
出现这种问题时客户端到 Redis 之间没有设置其他代理了吗？Redis 协议必须依赖于服务器能够严格按照请求顺序依次返回处理结果，否则就会出现你说的问题。

就像你说的，ioredis 会把发出的命令存储在队列中，每当收到新回复时就会弹出命令进行处理。这个队列本身是可靠的，不会“中间丢失了一段”。目前 ioredis 还没有收到过直连 Redis 出现类似问题的反馈，你们的 qps 大概是多少呢？换成 hiredis 解析模块（`npm install hiredis` 后，ioredis 会自动使用 hiredis）会有类似的问题吗？

**Comment by rrfeng** [comment]
当时用 codis 的时候 qps 不高，但是串数据的问题十分严重。换掉 codis 之后没再出现，直到昨天推广导致流量翻 N 倍，于是又出现了……

如果是负载高的情况下会出现的话，那么我们用增加 node 数量来缓解这个问题。
可供参考的值应该是一个 node 发往 redis 的 qps 吧，这个并不知道……
如果把 debug 打开，ioredis 输出的 write command 日志是不是就是一次 redis 操作？

**Comment by rrfeng** [comment]
hiredis 并没有装，之前用了一下出现一个错误怀疑是它引起的就删掉了。

**Comment by luin** [comment]
对的，每次 write command 都对应着一次对 socket 的写入（即发送一条 Redis 命令）。如果能得到串数据前的日志就最好了，可以看到那时有没有特殊事件的发生，比如服务器掉线之类的。另外可以考虑再尝试一下使用 hiredis，我这边会尝试构建一个负载测试。

**Comment by rrfeng** [comment]
还有一个状况就是，如果一个进程出现了这个问题，那么肯定就不会是一次，而且这个进程很有可能就不会正常工作了。
另外在现场检查的时候没有发现 redis 里存的不是预期的值的现象，也就是说只有在获取的时候才会出现（但不能严格保证）。
稍后我贴一段代码上来。

**Comment by luin** [comment]
嗯，如果出现这种问题就应该是 ioredis 内部存储的命令顺序和收到的结果顺序不匹配造成的，所以不会影响写操作（也就是说 Redis 里面存的值是没有问题的）。顺便问一下出问题的 ioredis 版本是？

**Comment by rrfeng** [comment]
pub/sub monitor 都没有。只有 hash 和 zset，和 get/set 。

```
 91 function getTopHotEntry() {
 92   return getTopEntryFromRedis().then(function(topId) {
 93     if(!topId) {
 94       return getTopEntryFromMongodb().then(function(topEntry) {
 95         return setTopEntryToRedis(topEntry.entry).then(function() {
 96           return topEntry;
 97         });
 98       });
 99     }
100     return HotEntry.findOne({ entry: topId }).lean().exec();
101   });
102 }
103
104 function getTopEntryFromMongodb() {
105   return HotEntry.findOne().sort({ _id: -1 }).lean().exec();
106 }
107
108 function getTopEntryFromRedis() {
109   return redis.getAsync(HOT_ENTRY_KEY);
110 }
```

这段代码在业务里调用的频率非常高，HOT_ENTRY_KEY 仅存了一个 MongoDB 的 document id。
爆发串数据的情况的时候，第 100 行会出现各种内容 cast to _id  的错误，比如 "OK", null, 1, "{xxxxx: xx}".....总之任何奇怪的东西都有可能……

**Comment by luin** [comment]
看 `redis.getAsync` 好像用的是 node_redis 而不是 ioredis？建议可以用 hiredis 观察一下是不是还会有问题

**Comment by rrfeng** [comment]
是的，现在这里是 node_redis， 是想对比一下是否是 ioredis 的问题。因为不能全部换，就在部分容易串的地方换成了 node_redis。
但是问题就是我描述的那样。
另外 debug 出来的 ioredis write command *** 的日志是不是一条指令输出两次？unique 了一下好像都是 2   条一样的。

**Comment by luin** [comment]
`write command` 只有当写入 socket 时才会出现，所以一条命令只会输出一个。看到的是不是 `queue command`？

**Comment by rrfeng** [comment]
对比了一下数据，有一个共同点，大约在一个 node 分到的请求在 30 qps 的时候，就会出问题。
30qps 转化成 redis 操作的话，只有 1 个月之前的代码有 debug 日志，平均每秒会有 1.2w 次redis 操作……
日志内容是这样的

 `Sun, 01 Nov 2015 07:12:21 GMT ioredis:redis write command[0] -> exists(jwt:UID)`

然后还是说，debug 日志里完全相同的内容（cmd + key）都会出现两次……所以真的不是一个 command 会打印 2 次？6k 和 1.2w 的区别还是很大的……

问我 1.2w/30 就是每个请求会有 400 次 redis 操作（or 200），为什么这么高我也不知道为什么……

**Comment by luin** [comment]
看起来这个频率不是很高，最好还是用 hiredis 观察一下还会不会出现这个问题

**Comment by luin** [comment]
这个频率不是特别高，最好还是用 hiredis 观察看看会不会复现

**Comment by luin** [comment]
一个 command 确实只会打印一次，你可以在本地试一下。

**Comment by rrfeng** [comment]
ok，可能是当时的代码有问题或者统计数据有问题。

刚才打开 debug 看了一下 30min 6500 个请求，redis 操作 20000 次。
昨晚高峰期大约 6-7 倍的流量，也就是说出问题的时候 redis 请求数在 70/s 左右。

**Comment by luin** [comment]
因为没有再收到其他同样的问题，所以先关闭这个 issue，如果仍然遇到问题，欢迎 reopen 这个 issue 继续讨论。

**Comment by zhangucan** [comment]
3.2.X出现了这个问题：
绿圈是从redis取到的值，图二是redis真实存在的值：
![image](https://user-images.githubusercontent.com/26155364/108039925-acf3a580-7077-11eb-9047-f587382a079c.png)
![image](https://user-images.githubusercontent.com/26155364/108039895-a5cc9780-7077-11eb-9fbc-16188839a5cb.png)
