### ISSUE TITLE
Question: speed improvements over node_redis

### ISSUE THREAD

**Issue by dirkbonhomme** [luin/ioredis#19]
I've been following this project with a lot of interest and just saw your benchmarks against node_redis. Can you please explain what causes this improvement? I always had the impression that node_redis focussed a lot on speed as well. Thanks!

**Comment by luin** [comment]
ioredis is developed from scratch and I haven't read all the code of node_redis. So to be frank, I don't know why ioredis has a better performance than node_redis :-)
