### ISSUE TITLE
on('connect') doesn't fire if already connected

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [luin/ioredis#190]
I'm not sure if this is intended functionality; but if it is, I cannot figure out an easy, reliable way to asynchronously connect and start preforming Redis operations once connected:

    redis = new (require 'ioredis')
    redis.on 'connect', -> hapi.start()

If I try to get a promise out of `ioredis` instead, I get told ‘this instance is already connecting’:

    redis = new (require 'ioredis')
    redis.connect().then -> hapi.start()

What's the proper idiom to do this sort of thing with `ioredis`?

**Comment by luin** [comment]
`"connect"` event should be fired when connected. Doesn't the following code work for you?

```javascript
var redis = new Redis();
redis.on('connect', function () {
  // the callback will be invoked once connected
  console.log('connect', arguments);
});
```

**Comment by luin** [comment]
I'm closing this issue. Feel free to reopen it with more information.
