### ISSUE TITLE
Cluster connect issue

### ISSUE THREAD

**Issue by nichliu** [luin/ioredis#192]
Redis cluster include 3 master, 3 slave
Redis 3.0.4
Node: 4.2.1
Ubuntu: 14.04
ioredis: 1.10.0

redisNodes include 3 master

No error output, Also no results output.
key 'test' exist with value 'hello'

I noticed some times 'ready' been print muti times(more than 10 time) on screen, some times only print 1 time

Here is the code
```javascript
var redis = new Redis.Cluster(redisNodes);

redis.on("error", function (err) {
    console.error("Error " + err);
});

redis.on('connect', function () {
    console.log('ready');
    redis.get('test',function(err,res){
        if(err) console.log(err)
        console.log(res)
    })
});
```

**Comment by luin** [comment]
Could you enable the debug info `DEBUG=ioredis:*` and post the logs here?

**Comment by nichliu** [comment]
ioredis:redis queue command[0] -> get(test) +0ms
  ioredis:redis status[xxx.xxx.xxx.xxx:6379]: ready -> close +76ms
  ioredis:connection skip reconnecting since the connection is manually closed. +0ms
  ioredis:redis status[xxx.xxx.xxx.xxx:6379]: close -> end +0ms
  ioredis:redis status[xxx.xxx.xxx.xxx:6379]: ready -> close +0ms
  ioredis:connection skip reconnecting since the connection is manually closed. +1ms
  ioredis:redis status[xxx.xxx.xxx.xxx:6379]: close -> end +0ms
  ioredis:redis status[xxx.xxx.xxx.xxx:6379]: ready -> close +0ms
  ioredis:connection skip reconnecting since the connection is manually closed. +0ms
  ioredis:redis status[xxx.xxx.xxx.xxx:6379]: close -> end +0ms
  ioredis:cluster getting slot cache from xxx.xxx.xxx.xxx:6379 +2s
  ioredis:redis queue command[0] -> cluster(slots) +0ms
  ioredis:redis queue command[0] -> get(test) +0ms
  ioredis:redis queue command[0] -> get(test) +0ms
  ioredis:redis queue command[0] -> get(test) +0ms
  ioredis:redis queue command[0] -> get(test) +0ms
  ioredis:redis queue command[0] -> get(test) +0ms
  ioredis:cluster getting slot cache from xxx.xxx.xxx.xxx:6379 +1s
  ioredis:redis queue command[0] -> cluster(slots) +1ms
  ioredis:redis status[xxx.xxx.xxx.xxx:6379]: connecting -> close +411ms
  ioredis:connection skip reconnecting because `retryStrategy` is not a function +0ms
  ioredis:redis status[xxx.xxx.xxx.xxx:6379]: close -> end +0ms
  ioredis:redis status[xxx.xxx.xxx.xxx:6379]: connecting -> close +1ms
  ioredis:connection skip reconnecting since the connection is manually closed. +0ms
  ioredis:redis status[xxx.xxx.xxx.xxx:6379]: close -> end +0ms
  ioredis:redis status[xxx.xxx.xxx.xxx:6379]: connecting -> close +0ms
  ioredis:connection skip reconnecting because `retryStrategy` is not a function +0ms
  ioredis:redis status[xxx.xxx.xxx.xxx:6379]: close -> end +0ms
  ioredis:cluster status: ready -> close +0ms
  ioredis:cluster status: close -> reconnecting +0ms
  ioredis:cluster getting slot cache from 10.240.0.6:6379 +0ms
  ioredis:cluster Cluster is disconnected. Retrying after 102ms +102ms
  ioredis:cluster status: reconnecting -> connecting +1ms
  ioredis:redis status[xxx.xxx.xxx.xxx:6379]: [empty] -> connecting +0ms
  ioredis:redis status[xxx.xxx.xxx.xxx:6379]: [empty] -> connecting +0ms
  ioredis:redis status[xxx.xxx.xxx.xxx:6379]: [empty] -> connecting +0ms
  ioredis:cluster getting slot cache from xxx.xxx.xxx.xxx:6379 +0ms
  ioredis:redis queue command[0] -> cluster(slots) +0ms
  ioredis:redis status[xxx.xxx.xxx.xxx:6379]: connecting -> connect +79ms
  ioredis:redis write command[0] -> auth(aaaaaaaaaa) +0ms
  ioredis:redis write command[0] -> info() +0ms
  ioredis:redis status[xxx.xxx.xxx.xxx:6379]: connecting -> connect +6ms
  ioredis:redis write command[0] -> auth(aaaaaaaaaa) +0ms
  ioredis:redis write command[0] -> info() +0ms
  ioredis:redis status[xxx.xxx.xxx.xxx:6379]: connecting -> connect +3ms
  ioredis:redis write command[0] -> auth(aaaaaaaaaa) +0ms
  ioredis:redis write command[0] -> info() +0ms
  ioredis:redis status[xxx.xxx.xxx.xxx:6379]: connect -> ready +158ms
  ioredis:redis status[xxx.xxx.xxx.xxx:6379]: connect -> ready +29ms
  ioredis:connection send 1 commands in offline queue +0ms
  ioredis:redis write command[0] -> cluster(slots) +0ms
  ioredis:redis status[xxx.xxx.xxx.xxx:6379]: connect -> ready +4ms
  ioredis:redis status[xxx.xxx.xxx.xxx:6379]: [empty] -> connecting +65ms
  ioredis:redis status[xxx.xxx.xxx.xxx:6379]: [empty] -> connecting +2ms
  ioredis:redis status[xxx.xxx.xxx.xxx:6379]: [empty] -> connecting +1ms
  ioredis:cluster status: connecting -> connect +1ms
  ioredis:cluster status: connect -> ready +0ms
  ioredis:cluster send 1 commands in offline queue +0ms
  ioredis:redis queue command[0] -> get(test) +0ms

**Comment by nichliu** [comment]
I can run redis-cli -c with remote cluster on the same host without any problem

**Comment by luin** [comment]
What about connect to one of the nodes (whether using redis-cli or `new Redis()`) and invoke `CLUSTER slots` to see what's returned/

**Comment by nichliu** [comment]
{ [ReplyError: MOVED 6918 10.x.x.x:6379]
  name: 'ReplyError',
  message: 'MOVED 6918 10.x.x.x:6379',
  command: { name: 'get', args: [ 'test' ] } }

I think what happen might be I have 2 ips for each redis node, 1 is public, another is internal, when move command to another node, it might use internal ip can't be access by outside

**Comment by luin** [comment]
Yes, that's correct. It's required to bind every node to the public network interface to setup a cluster correctly.
