### ISSUE TITLE
Scaling the number of redis connections

### ISSUE THREAD

**Issue by Ovidiu-S** [luin/ioredis#193]
Hi,

We are using ioredis and a redis cluster as our single storage endpoint. We use redis pubsub for pushing db updates to users (every user has his own redis connection for pubsub inside socket.io, witch then pushes the message to the user).

So the question is : Is this implementation horizontally scalable ? (knowing that the default number of max connections is 10k)

**Comment by luin** [comment]
It will be better to share a single redis connection among all users. I'm closing this since it's not a ioredis-specified question.

**Comment by Ovidiu-S** [comment]
Thanks for answering luin. 
Could you provide more details please ? Sharing a single connection with pubsub means one client publishes everything and is subscribed to everything.
Do you foresee an issue with increasing the number of max connections when it is needed ?

**Comment by Ovidiu-S** [comment]
Also, when using cluster, does the number of connections scale when adding more servers ?

**Comment by Ovidiu-S** [comment]
Thank you again for responding. I am confused how a single connection would scale, or how to add additional endpoints to scale horizontally.

I can see how we could use our Kafka queue to decouple, but PubSub seems nicer and faster. I don't yet picture how one connection could handle millions of topics and millions of users.

I understand this is not ioredis specific, but you have helped by confirming there is a number of connection issue, which I appreciate. Could you suggest a better place for me to post these questions?
