### ISSUE TITLE
Race condition when using sentinels

### ISSUE THREAD

**Issue by swaj** [luin/ioredis#198]
So I've found an interesting case.  I'm not sure if you'll consider this a bug or not, but I figured it was worth reporting.

First let's suppose I create a new `Redis` object like so:

```javascript
var client = new Redis({
    name: "mymaster",
    sentinels: { host: "localhost", port: 23679 }
});
```

Given this client, `ioredis` will connect to the socket, and issue a command to find the master:

```
SENTINEL get-master-addr-by-name mymaster
```

The first issue I notice is even if I explicity disable command queues (`enableOfflineQueue`: `false`), this command will always be added to an internal queue so it is the first thing executed once a connection has been made.  I can understand why, though, because of the nature of how sentinels work.  This probably isn't a real issue.

The real issue is that there is a potential for a race condition.  Suppose you create the new `Redis` object, and immediately issue 20 commands (`redis.set("foo", "bar")` for example).  What happens internally is that the command which was originally queued by the `Redis` constructor to find the master (`get-master-addr-by-name`) gets pushed off the back of the queue.  As you can imagine, at this point the `Redis` instance becomes effectively unusable, because it is unable to determine the real master to connect to.

I've fixed this problem by setting `enableReadyCheck` to `true`, and waiting for the `Redis` object to emit the `ready` event.  If you'd like a test case that can trigger this race condition, I'd be happy to provide one.

I'm not sure if you'll consider this a bug, since it's probably just good practice to wait for the `ready` event anyway, but it might be worth pointing out in the documentation if this is intended behavior.  Another possible fix is to either make internal commands (like `get-master-addr-by-name`) unable to be evicted, or even maintain a separate command queue for internal commands vs commands issued by the consumer.

I hope this helps!

**Comment by luin** [comment]
> The first issue I notice is even if I explicity disable command queues (enableOfflineQueue: false), this command will always be added to an internal queue so it is the first thing executed once a connection has been made.

Yes, as you said, this is an intentional behaviour.

>  ..., or even maintain a separate command queue for internal commands vs commands issued by the consumer.

Actually the internal command queue is independent of the normal command queue. I'd like to see a test case if possible.
