### ISSUE TITLE
Few questions regarding library flow in different situtations

### ISSUE THREAD

**Issue by shaharmor** [luin/ioredis#201]
Hi,

I would like to know how the library performs under certain situations if possible: 
Considering a Redis cluster with a master & a slave responsible for X slots.
  - How does the library gets notified when a master goes down?
    - Does it wait for an incoming error?
    - Does it run a periodic cluster slots check?
    - What about requests that were already sent to the dead master?
  - Given that the library knows a master has failed, what will happened until the slave takes over?
    - Will the requests be queued? failed? retried? 
  - In a situation that the slave fails to take over and there are slots not allocated, what happens to requests targeted for those slots?
    - Are they queued until the slots will be allocated? If so, can we limit the queue?
    - What happens if the master never comes back? Will the library just get filled with callbacks waiting for it to come back?

I have more questions but i think we should start a conversation about these first and go from there.

Thanks a lot for the help in advance.

**Comment by luin** [comment]
> How does the library gets notified when a master goes down?

ioredis considers a node is down when receiving a TCP `end` event. What's more, if ioredis receives an specified error (e.g. `CLUSTERDOWN`) when sending a command, it will know the cluster is down.

> What about requests that were already sent to the dead master?

ioredis will retry them when cluster is online again. There are [several options](https://github.com/luin/ioredis#cluster) to adjust this behaviour.

> Given that the library knows a master has failed, what will happened until the slave takes over?
Will the requests be queued? failed? retried?

Again, this requests are queued and will be retried when the new master is online.

> In a situation that the slave fails to take over and there are slots not allocated, what happens to requests targeted for those slots?

> What happens if the master never comes back? Will the library just get filled with callbacks waiting for it to come back?

See `retryDelayOnClusterDown` option.

**Comment by shaharmor** [comment]
@luin thank you for your fast response.

I have some additional questions:

- When a `CLUSTERDOWN` error is received, does ioredis handle other hash slots as usual, or does it affect all the requests? Given that its possible to set `cluster-require-full-coverage no` on redis, its possible that only a part of the cluster will be down. What happens in this case?

- Is it possible to limit the # of times a request will be retried? I have witnessed situations that the cluster was only partially down (Only some of the hash slots were uncovered), but the library was queuing up millions of requests, causing the server to fill its memory usage, eventually causing it to crash.
