### ISSUE TITLE
100% CPU during cluster failover

### ISSUE THREAD

**Issue by shaharmor** [luin/ioredis#203]
Hi,

During a cluster failover, in the duration between the master died and the slave takes over (Basically redis `node-timeout` duration), the library seems to use 100% CPU.

I am obviously talking about loads of a few thousand requests per second.

**Comment by shaharmor** [comment]
After looking at the code a bit, i think that every command that fails calls this line: https://github.com/luin/ioredis/blob/master/lib/cluster.js#L472 which is causing a lot of callbacks and setTimeouts, instead of having a single one call all others when its done.

Also, this causes the `refreshSlotsCache` to be called many many times.

**Comment by shaharmor** [comment]
@luin any chance to release a version with this change?

**Comment by luin** [comment]
I'm writing some tests for it, and I'll release a version once done

**Comment by shaharmor** [comment]
Cool thanks! Also, if you can add me to the contributors list in the README in your next commit it would be great :)

**Comment by luin** [comment]
Of course will do! Actually I regenerate the contributors every time I release a version. :laughing:
