### ISSUE TITLE
Library doesn't handle TRYAGAIN errors

### ISSUE THREAD

**Issue by shaharmor** [luin/ioredis#204]
In redis cluster, when a slot is migrating from one node to the other, all requests that are designated to this slot will receive the TRYAGAIN error.

I think the library should handle this by retrying the request after some time (Preferably configurable time)

**Comment by luin** [comment]
Just a reference here: https://github.com/antirez/redis/blob/cbcffed90792ef83bcba3bfcbbd5e64380d1b0b9/src/cluster.c#L5165. Seems we should send `asking` command before retrying each failed command.

**Comment by luin** [comment]
Closing in favour of #264.
