### ISSUE TITLE
Missing  Error Event  (maybe).

### ISSUE THREAD

**Issue by xxxman2008** [luin/ioredis#207]
ENV:  

     Redis Cluster with  3 master ,no  slave  .(MasterA / MasterB/ MasterC)
     cluster setting :  cluster-require-full-coverage is "no"
  
assume：  key bar (value foo) stored in  MasterB  ,  key  foo (value bar) stored in MasterC
 
if  we stopped MasterA ,and  then 

   ioredis.Cluster.get('bar' ,  function (err,result){
            // I'M  will never run............
})

how  can i do with this situation? any advise??

**Comment by xxxman2008** [comment]
Sorry ,i mistake    "assume： key bar (value foo) stored in MasterB , key foo (value bar) stored in MasterC"

should be "assume： key bar (value foo) stored in MasterA, key foo (value bar) stored in MasterC"

**Comment by luin** [comment]
Could you enable the debug mode and post the logs here (`DEBUG=ioredis:* node yourapp.js`)? If you're using version 1.12.1, the upgrade to 1.12.2 may fix the issue.

**Comment by xxxman2008** [comment]
I upgrade to  1.12.2 , got same result ..

And, i'm  using webstorm  on  windows .....so sorry  ,i don't know  how to  set  Debug= ioredis:* ,althought  i  set it as an  windows  ENV  parameter.

**Comment by luin** [comment]
I'll setup a test environment on my computer ASAP.

**Comment by xxxman2008** [comment]
My, Test Code:


var RedisCache = {

};
var REDIS = require('ioredis');
REDIS.Promise.onPossiblyUnhandledRejection(function (error) {
    console.log(error);
});

RedisCache.connParam = [
    {host: '192.168.1.30', port: 6379},
    {host: '192.168.1.30', port: 6380},
    {host: '192.168.1.30', port: 6381}
];
//RedisCache.connParam = {host: '192.168.1.30', port: 6379};
RedisCache.optionParam = {
    connectTimeout:2000,
    enableOfflineQueue:false,
    autoResendUnfulfilledCommands:false
};
RedisCache.poolSize = 10;
RedisCache.connectionArr = [];
RedisCache.makeConnectionPool = function  (){
    var conn,length,curPoolSize,that=this;
    curPoolSize = this.connectionArr.length;
    length = Math.max(0,this.poolSize - curPoolSize);
    for (var i = 0; i < length; i++) {
        conn = new REDIS.Cluster(this.connParam,this.optionParam);
        conn.on('connect', function () {
            that.connectionArr.push(conn);
        }.bind(conn));
        conn.on('error', function (err) {
            console.log(err);
        }.bind(conn));
        conn.on('close', function (err) {
            console.log(err);
        }.bind(conn));
    }
};
RedisCache.getRedisInstance = function () {
    var conn,that = this;
    if (this.connectionArr.length > 0){
        conn = this.connectionArr.shift();
        this.connectionArr.push(conn);
    }else{
        conn = new REDIS.Cluster(this.connParam,this.optionParam);
        conn.on('connect', function () {
            that.connectionArr.push(conn);
        }.bind(conn));
        //TODO:remember
    }
    if (this.connectionArr.length < this.poolSize){
        this.makeConnectionPool();
    }
    return conn;
};

RedisCache.checkPool = function () {
    var tmpArr = [],client;
    var length = this.connectionArr.length;
    for (var i = 0; i < length; i++) {
        client = this.connectionArr[i];
        if (client.status == 'ready'){
            tmpArr.push(client);
        }else{
            client.disconnect();
            client = null;
        }
    }
    this.connectionArr = tmpArr;
    if (this.connectionArr.length < this.poolSize){
        this.makeConnectionPool();
    }
};
RedisCache.makeConnectionPool();
setInterval(RedisCache.checkPool.bind(RedisCache),60000);
//test code.
setInterval(function () {
    var client = RedisCache.getRedisInstance();
    console.log('Cluster Status: '+client.status);
    client.set('foo', 'bar'+Math.random());
    client.set('bar','foo'+Math.random());
    client.get('foo', function (err, result) {
        !err ? console.log(result):console.log(err);
    }.bind(client));
    client.get('bar', function (err, result) {
        !err ? console.log(result):console.log(err);
    }.bind(client));
},10000);

**Comment by xxxman2008** [comment]
finally ，i  open debug for  ioredis.  Here is the  log:

See attache file .
[IORedis-DebugInfo-01.txt](https://github.com/luin/ioredis/files/53813/IORedis-DebugInfo-01.txt)

**Comment by xxxman2008** [comment]
And  my  Code for your refference.

[RedisCache.js.txt](https://github.com/luin/ioredis/files/53830/RedisCache.js.txt)

**Comment by xxxman2008** [comment]
Something  is  really  confused me.
You can see ,i  make an Option Object  
RedisCache.optionParam = {
    connectTimeout:2000,
    enableOfflineQueue:false,
    autoResendUnfulfilledCommands:false
}; 

And then Creat an Cluster connection  with :  
conn = new REDIS.Cluster(this.connParam,this.optionParam);

I  think  it will  disable the "OfflineQueue"  , Buf ,from  debug log ,you can see :
------------- 
Mon, 07 Dec 2015 10:53:41 GMT ioredis:redis queue command[0] -> set(bar,foo0.86925975442864)
Mon, 07 Dec 2015 10:53:41 GMT ioredis:redis queue command[0] -> get(bar)
------------  seems  the command still  be  queued .

And  sencode , i think  retryStrategy  should have an  Default value , but  we got : 
Mon, 07 Dec 2015 10:53:33 GMT ioredis:connection skip reconnecting because `retryStrategy` is not a function

**Comment by luin** [comment]
Thank you for the details.
First of all, `enableOfflineQueue` specified in the second parameter is used in the cluster internally instead of passing to the `Redis` constructor directly.
Second, `retryStrategy` is disabled in the cluster mode since ioredis will reconnect to the offline node automatically.

The problem you run into is because ioredis is keeping trying to fetch the result from the offline node until getting a response. The callback will be fulfilled when the node is online again. Unfortunately there's not an options to control the retry times, which is been working in the 2.x branch and will be released within two months.

**Comment by xxxman2008** [comment]
OK， thank you .
And  i really think the options  of  single redis connection  and cluster connection  should  be (at least most of them should be ) same ( uniforme? ).

And , if  option "enableOfflineQueue" was not  used in the cluster internally  --  in some situation ,it's waste time --- ,we can resolve the problem ,i guess.

it just need an Event to inform user "we cannot got the key" ,so it's user's responsibility how to proceed. 

In another hand , if  MasterA will never online , the command queue may crash the whole process( also ,i guess).  In the  meantime , the web user will encountered a long long time waiting...

Anyway , thank you  . It seems  IORedis need more time to strong enough to deal with various situations. Best wishes. 

Bye.

**Comment by luin** [comment]
That's correct. In the next major version, the option `enableOfflineQueue` will be renamed to `clusterEnableOfflineQueue` for the sake of unambiguous. The current option `maxRedirections` will be used not only for `MOVED` and `ASK` errors, but also for other errors that may cause redirections, so that it's possible to reject the command after several failures.

**Comment by luin** [comment]
Options updated in 2.0. Closing this issue.
