### ISSUE TITLE
Connection is closed. with default settings

### ISSUE THREAD

**Issue by shaharmor** [luin/ioredis#212]
Hi,

We are using ioredis in cluster mode with the default settings (Not overriding anything).
I went over the code and the only time where a `Connection is closed.` error is returned is when `this.status === end`, which is only being set here:
https://github.com/luin/ioredis/blob/master/lib/cluster.js#L146

But this line should never be executed because this will always return true: https://github.com/luin/ioredis/blob/master/lib/cluster.js#L138

So how come we are receiving these errors:
`Error: Connection is closed.\n    at Cluster.sendCommand (/xxx/ioredis/lib/cluster.js:404:20`

**Comment by luin** [comment]
That's strange. Does enabling debug info `DEBUG=ioredis:* node yourapp` help?

**Comment by shaharmor** [comment]
Unfortunately its not consistent at all, it happened on 1 server out of 50, and once we restarted it it was working again.

I think it somehow got into a bad state that caused him to stay in a Connection Closed mode.

**Comment by luin** [comment]
I'm closing this issue since ioredis v2 is released and there're many code changed. Reopen it if the error still exists.
