### ISSUE TITLE
Redis spop returnin null despite data

### ISSUE THREAD

**Issue by davidgatti** [luin/ioredis#216]
For a while now I'm having this weird problem described on [StackOverflow](http://stackoverflow.com/questions/34315973/redis-spop-returns-null-despite-key-being-present-nodejs/34337030#34337030). 

Now after more testing I'm getting the same issue even with one thread. Where on my local machine no such problem occurs. 

Any idea what is going on? And I'm not imagining the data ;) it is there

![screen shot 2015-12-18 at 4 42 29 pm](https://cloud.githubusercontent.com/assets/411114/11900470/5c69165a-a5a6-11e5-9eac-1e49318458d0.png)

**Comment by luin** [comment]
Are you able to reproduce this problem? What do you get if you use redis-cli (or telnet) to connect to the redis directly.

**Comment by davidgatti** [comment]
I see this same. The data is there. On Mac I replaced the local link to the local Readis with the remote one. And running a local script connected to that Redis database gives the same result. I can count, but I can't `spop`

**Comment by luin** [comment]
Are you spoping a hash key? It looks like `json` is a hash instead of set. However, it doesn't seem to be a ioredis-specified problem since you got  the same result using redis-cli.

**Comment by davidgatti** [comment]
"I see this same" == "I see the same as the Desktop Manager"

**Comment by luin** [comment]
Aha! What about enable the debug mode (`DEBUG=ioredis:* node yourapp`) and see the logs? What's more, running `MONITOR` command in the redis-cli so you can know what commands are sent to the redis server.

**Comment by davidgatti** [comment]
Will try, thank for the debugging tip.
