### ISSUE TITLE
Fails to transform map argument for redis.msetnx({a:123,b:345})

### ISSUE THREAD

**Issue by garkin** [luin/ioredis#218]
Fails to transform map argument for `redis.msetnx({a:123,b:345})`
Somehow related to https://github.com/luin/ioredis/issues/217

Before `this.initPromise()`[#](https://github.com/luin/ioredis/blob/05a61e1c3eecc829a8f609ca7eeb1fa495573a26/lib/command.js#L50):
![image](https://cloud.githubusercontent.com/assets/422774/11917049/6a037298-a721-11e5-9dcf-3964569293f8.png)

After:
![image](https://cloud.githubusercontent.com/assets/422774/11917050/6da19a56-a721-11e5-840d-f6e385ff0337.png)

**Comment by luin** [comment]
There's no argument transformer for `msetnx` yet. The built-in ones can be found here: https://github.com/luin/ioredis/blob/master/lib/command.js#L302-L335, and you can define one yourself for `msetnx`.

However, I think we should have a built-in transformer for `msetnx`.

**Comment by garkin** [comment]
I think it's pretty inconsistent to have `msetnx` API differ from `mset`. 
Since it should be just an `mset` with a blackjack.

**Comment by luin** [comment]
Yes, you're right. Didn't notice this command when I implemented transformers.
