### ISSUE TITLE
Failed to refresh slots cache

### ISSUE THREAD

**Issue by fbacker** [luin/ioredis#220]
Having issues when running clusters. Ports are opened on the server. Cannot find what the error message wants.

	REDIS CONNECT error Error: Failed to refresh slots cache.

The redis server is started with 

	./create-cluster start
	./create-cluster create
	>>> Creating cluster
	>>> Performing hash slots allocation on 6 nodes...
	Using 3 masters:
	127.0.0.1:30001
	127.0.0.1:30002
	127.0.0.1:30003
	Adding replica 127.0.0.1:30004 to 127.0.0.1:30001
	Adding replica 127.0.0.1:30005 to 127.0.0.1:30002
	Adding replica 127.0.0.1:30006 to 127.0.0.1:30003
	M: b52b834a64cd5a5b21143ab04c812280e51c027b 127.0.0.1:30001
	   slots:0-5460 (5461 slots) master
	M: d78d47d58d18432ce24c23a808e5e5910abf9ed2 127.0.0.1:30002
	   slots:5461-10922 (5462 slots) master
	M: d95b9eaac2fcef61e9f8a4b7569c6ce4833224fc 127.0.0.1:30003
	   slots:10923-16383 (5461 slots) master
	S: 9ba310a137f57539b8a5d011cfe7db4e9a7089a9 127.0.0.1:30004
	   replicates b52b834a64cd5a5b21143ab04c812280e51c027b
	S: bebafd0ff37774a5e40dbf959401042e7e39beb9 127.0.0.1:30005
	   replicates d78d47d58d18432ce24c23a808e5e5910abf9ed2
	S: 1bade260c211b59b967fa6d85124deadbfbfafe7 127.0.0.1:30006
	   replicates d95b9eaac2fcef61e9f8a4b7569c6ce4833224fc
	Can I set the above configuration? (type 'yes' to accept): yes
	>>> Nodes configuration updated
	>>> Assign a different config epoch to each node
	>>> Sending CLUSTER MEET messages to join the cluster
	Waiting for the cluster to join..
	>>> Performing Cluster Check (using node 127.0.0.1:30001)
	M: b52b834a64cd5a5b21143ab04c812280e51c027b 127.0.0.1:30001
	   slots:0-5460 (5461 slots) master
	M: d78d47d58d18432ce24c23a808e5e5910abf9ed2 127.0.0.1:30002
	   slots:5461-10922 (5462 slots) master
	M: d95b9eaac2fcef61e9f8a4b7569c6ce4833224fc 127.0.0.1:30003
	   slots:10923-16383 (5461 slots) master
	M: 9ba310a137f57539b8a5d011cfe7db4e9a7089a9 127.0.0.1:30004
	   slots: (0 slots) master
	   replicates b52b834a64cd5a5b21143ab04c812280e51c027b
	M: bebafd0ff37774a5e40dbf959401042e7e39beb9 127.0.0.1:30005
	   slots: (0 slots) master
	   replicates d78d47d58d18432ce24c23a808e5e5910abf9ed2
	M: 1bade260c211b59b967fa6d85124deadbfbfafe7 127.0.0.1:30006
	   slots: (0 slots) master
	   replicates d95b9eaac2fcef61e9f8a4b7569c6ce4833224fc
	[OK] All nodes agree about slots configuration.
	>>> Check for open slots...
	>>> Check slots coverage...
	[OK] All 16384 slots covered.

This is the code used.

	var rClusters = [[{
            port: 30001,
            host: 'xxx.us-west-2.compute.amazonaws.com'
        }, {
            port: 30002,
            host: 'xxx.us-west-2.compute.amazonaws.com'
        }, {
            port: 30003,
            host: 'xxx.us-west-2.compute.amazonaws.com'
        }]],
        Redis = require('ioredis'),
        db = new Redis.Cluster(rClusters),
        pub = new Redis.Cluster(rClusters),
        sub = new Redis.Cluster(rClusters),
        sockets = [];
    sub.subscribe(conf.redisNamespace+ 'chatmessage'); // someone said something
    sub.subscribe(conf.redisNamespace+ 'chatmessage-confirm'); // someone said something confirm back
    sub.subscribe(conf.redisNamespace+ 'presence-friends'); // loop friend id, if publish exist broadcast online state
    sub.subscribe(conf.redisNamespace+ 'user-clear'); // clear user from memory
    sub.subscribe(conf.redisNamespace+ 'process-start'); // gather process info
    sub.subscribe(conf.redisNamespace+ 'process-end'); // has some data
    db.on('connect',function(){
        console.log("REDIS CONNECT");
    });
    db.on('error',function(err){
        console.log("REDIS CONNECT error "+ err);
    });

**Comment by luin** [comment]
ioredis emits `Failed to refresh slots cache` when none of the nodes can be connected to. You may listen to the `node error` event for the detail information or just check the `lastNodeError` property of the `err`:

```javascript
db.on('error',function(err){
    console.log("REDIS CONNECT error "+ err);
    console.log('node error', err.lastNodeError);
});
```

**Comment by fbacker** [comment]
On the redis server I used redis-cli and flushall, created the instances again.

If I'm using redis desktop manager from same computer that runs the node script I can get a connection to port 30001.

But when running the nodejs ioredis code I still get error. Any idéas what's missing? Do I need to configure redis in any other way? I've just downloaded redis, built it and started. No configuration.

    REDIS CONNECT error Error: Failed to refresh slots cache.
    node error { [ReplyError: ERR unknown command 'cluster']
      name: 'ReplyError',
      message: 'ERR unknown command \'cluster\'',
      command: { name: 'cluster', args: [ 'slots' ] } }


When running the nodejs on same server and change the host to 127.0.0.1

    REDIS CONNECT error Error: Failed to refresh slots cache.
    node error [Error: Connection is closed.]

When looking at 30001.log

	3664:M 23 Dec 09:43:08.240 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
	3664:M 23 Dec 09:43:08.240 # Server started, Redis version 3.0.6
	3664:M 23 Dec 09:43:08.240 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
	3664:M 23 Dec 09:43:08.241 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
	3664:M 23 Dec 09:43:08.241 * The server is now ready to accept connections on port 30001
	3664:M 23 Dec 09:43:16.596 # configEpoch set to 1 via CLUSTER SET-CONFIG-EPOCH
	3664:M 23 Dec 09:43:16.655 # IP address for this node updated to 127.0.0.1
	3664:M 23 Dec 09:43:18.560 # Cluster state changed: ok
	3664:M 23 Dec 09:43:19.269 * Slave 127.0.0.1:30004 asks for synchronization
	3664:M 23 Dec 09:43:19.269 * Full resync requested by slave 127.0.0.1:30004
	3664:M 23 Dec 09:43:19.269 * Starting BGSAVE for SYNC with target: disk
	3664:M 23 Dec 09:43:19.269 * Background saving started by pid 3691
	3691:C 23 Dec 09:43:19.272 * DB saved on disk
	3691:C 23 Dec 09:43:19.272 * RDB: 0 MB of memory used by copy-on-write
	3664:M 23 Dec 09:43:19.362 * Background saving terminated with success
	3664:M 23 Dec 09:43:19.363 * Synchronization with slave 127.0.0.1:30004 succeeded

**Comment by luin** [comment]
`ReplyError: ERR unknown command 'cluster` is because the redis server connected to doesn't support cluster (Redis supports cluster after 3.0).
`Connection is closed` is because the server is not reachable.

What about using redis-cli to connect to one of the nodes (e.g. `xxx.us-west-2.compute.amazonaws.com:30002`), invoke `cluster slots` and see what you get.

**Comment by fbacker** [comment]
I'm running redis 3.0.6. And testing with CLI works as it should.

	[ec2-user@ip-172-31-6-207 src]$ ./redis-cli -c -p 30001
	127.0.0.1:30001> set foo bar
	-> Redirected to slot [12182] located at 127.0.0.1:30003
	OK
	127.0.0.1:30003> get foo
	"bar"
	127.0.0.1:30003> set hello world
	-> Redirected to slot [866] located at 127.0.0.1:30001
	OK
	127.0.0.1:30001> get foo
	-> Redirected to slot [12182] located at 127.0.0.1:30003
	"bar"
	127.0.0.1:30003> get hello
	-> Redirected to slot [866] located at 127.0.0.1:30001
	"world"
	127.0.0.1:30001>

**Comment by luin** [comment]
Can you run the following code with debug mode enabled (`DEBUG=ioredis:* node yourapp.js`):

```javascript
var Redis = require('ioredis');
var redis = new Redis.Cluster([{
  port: 30001
}]);

redis.on('error',function (err) {
    console.log("REDIS CONNECT error "+ err);
    console.log('node error', err.lastNodeError);
});
```

and post the logs here?

**Comment by fbacker** [comment]
Now it seems to be working. When I ran it first on local computer I saw that it kept asking for 127.0.0.1 instead of the hostname that was specified. So looked with new eyes on the code and I've somehow managed to put double array [[ ]] where I specify the hosts. Pretty emabbasing yes :(

So now running on same machine with 127.0.0.1 works.

However when running on developer machine and using hostname it's still an issue. Is there more ports that needs to be open on the server?


  	 DEBUG=ioredis:* node -nouse-idle-notification -expose-gc -max-old-space-size=8192 app.js
	info: node environment production
	info: node port. 5224
	info: Configuration environment=production, port=5224, redisNamespace=BingoLottoChat:, mainroom=MainRoom, chatroom=ChatRoom, expireCheck=10000, expireMessage=180, expireProcess=15, facebookTimeout=900
	info: start worker: 0, with port: 5224
	info: node environment production
	info: node port. 5224
	  ioredis:cluster status: [empty] -> connecting +0ms
	  ioredis:redis status[xxx.us-west-2.compute.amazonaws.com:30001]: [empty] -> connecting +5ms
	  ioredis:redis status[xxx.us-west-2.compute.amazonaws.com:30002]: [empty] -> connecting +2ms
	  ioredis:redis status[xxx.us-west-2.compute.amazonaws.com:30003]: [empty] -> connecting +1ms
	  ioredis:cluster getting slot cache from xxx.us-west-2.compute.amazonaws.com:30001 +0ms
	  ioredis:redis queue command[0] -> cluster(slots) +2ms
	  ioredis:cluster status: [empty] -> connecting +1ms
	  ioredis:redis status[xxx.us-west-2.compute.amazonaws.com:30001]: [empty] -> connecting +0ms
	  ioredis:redis status[xxx.us-west-2.compute.amazonaws.com:30002]: [empty] -> connecting +0ms
	  ioredis:redis status[xxx.us-west-2.compute.amazonaws.com:30003]: [empty] -> connecting +1ms
	  ioredis:cluster getting slot cache from xxx.us-west-2.compute.amazonaws.com:30001 +0ms
	  ioredis:redis queue command[0] -> cluster(slots) +1ms
	  ioredis:cluster status: [empty] -> connecting +0ms
	  ioredis:redis status[xxx.us-west-2.compute.amazonaws.com:30001]: [empty] -> connecting +0ms
	  ioredis:redis status[xxx.us-west-2.compute.amazonaws.com:30002]: [empty] -> connecting +1ms
	  ioredis:redis status[xxx.us-west-2.compute.amazonaws.com:30003]: [empty] -> connecting +0ms
	  ioredis:cluster getting slot cache from xxx.us-west-2.compute.amazonaws.com:30002 +0ms
	  ioredis:redis queue command[0] -> cluster(slots) +0ms
	info: Load server pid: 19140, port 5224
	info: Server is up and running
	info: HTTP Listening on *:5224
	  ioredis:redis status[52.11.222.96:30001]: connecting -> connect +412ms
	  ioredis:redis write command[0] -> info() +1ms
	  ioredis:redis status[52.11.222.96:30003]: connecting -> connect +2ms
	  ioredis:redis write command[0] -> info() +0ms
	  ioredis:redis status[52.11.222.96:30002]: connecting -> connect +1ms
	  ioredis:redis write command[0] -> info() +1ms
	  ioredis:redis status[52.11.222.96:30003]: connecting -> connect +4ms
	  ioredis:redis write command[0] -> info() +1ms
	  ioredis:redis status[52.11.222.96:30001]: connecting -> connect +0ms
	  ioredis:redis write command[0] -> info() +0ms
	  ioredis:redis status[52.11.222.96:30002]: connecting -> connect +0ms
	  ioredis:redis write command[0] -> info() +0ms
	  ioredis:redis status[52.11.222.96:30001]: connecting -> connect +8ms
	  ioredis:redis write command[0] -> info() +0ms
	  ioredis:redis status[52.11.222.96:30003]: connecting -> connect +0ms
	  ioredis:redis write command[0] -> info() +0ms
	  ioredis:redis status[52.11.222.96:30002]: connecting -> connect +0ms
	  ioredis:redis write command[0] -> info() +0ms
	  ioredis:redis status[52.11.222.96:30003]: connect -> ready +177ms
	  ioredis:redis status[52.11.222.96:30001]: connect -> ready +1ms
	  ioredis:connection send 1 commands in offline queue +1ms
	  ioredis:redis write command[0] -> cluster(slots) +0ms
	  ioredis:redis status[52.11.222.96:30002]: connect -> ready +0ms
	  ioredis:connection send 1 commands in offline queue +1ms
	  ioredis:redis write command[0] -> cluster(slots) +0ms
	  ioredis:redis status[52.11.222.96:30003]: connect -> ready +10ms
	  ioredis:redis status[52.11.222.96:30001]: connect -> ready +5ms
	  ioredis:connection send 1 commands in offline queue +0ms
	  ioredis:redis write command[0] -> cluster(slots) +1ms
	  ioredis:redis status[52.11.222.96:30002]: connect -> ready +4ms
	  ioredis:redis status[52.11.222.96:30001]: connect -> ready +7ms
	  ioredis:redis status[52.11.222.96:30003]: connect -> ready +5ms
	  ioredis:redis status[52.11.222.96:30002]: connect -> ready +2ms
	  ioredis:redis status[127.0.0.1:30002]: [empty] -> connecting +157ms
	  ioredis:redis status[127.0.0.1:30003]: [empty] -> connecting +1ms
	  ioredis:redis status[127.0.0.1:30001]: [empty] -> connecting +1ms
	  ioredis:cluster status: connecting -> connect +1ms
	  ioredis:cluster status: connect -> ready +0ms
	REDIS CONNECT
	  ioredis:connection error: Error: connect ECONNREFUSED +2ms
	  ioredis:connection error: Error: connect ECONNREFUSED +0ms
	  ioredis:connection error: Error: connect ECONNREFUSED +0ms
	  ioredis:redis status[127.0.0.1:30001]: [empty] -> connecting +1ms
	  ioredis:redis status[127.0.0.1:30003]: [empty] -> connecting +0ms
	  ioredis:redis status[127.0.0.1:30002]: [empty] -> connecting +2ms
	  ioredis:cluster status: connecting -> connect +1ms
	  ioredis:cluster status: connect -> ready +0ms
	  ioredis:cluster send 6 commands in offline queue +0ms
	  ioredis:redis queue command[0] -> subscribe(BingoLottoChat:chatmessage) +0ms
	  ioredis:redis queue command[0] -> subscribe(BingoLottoChat:chatmessage-confirm) +0ms
	  ioredis:redis queue command[0] -> subscribe(BingoLottoChat:presence-friends) +0ms
	  ioredis:redis queue command[0] -> subscribe(BingoLottoChat:user-clear) +0ms
	  ioredis:redis queue command[0] -> subscribe(BingoLottoChat:process-start) +0ms
	  ioredis:redis queue command[0] -> subscribe(BingoLottoChat:process-end) +0ms
	  ioredis:redis status[127.0.0.1:30001]: connecting -> close +1ms
	  ioredis:connection skip reconnecting because `retryStrategy` is not a function +0ms
	  ioredis:redis status[127.0.0.1:30001]: close -> end +0ms
	  ioredis:redis status[127.0.0.1:30003]: connecting -> close +1ms
	  ioredis:connection skip reconnecting because `retryStrategy` is not a function +0ms
	  ioredis:redis status[127.0.0.1:30003]: close -> end +0ms
	  ioredis:redis status[127.0.0.1:30002]: connecting -> close +0ms
	  ioredis:connection skip reconnecting because `retryStrategy` is not a function +0ms
	  ioredis:redis status[127.0.0.1:30002]: close -> end +0ms
	  ioredis:connection error: Error: connect ECONNREFUSED +0ms
	  ioredis:connection error: Error: connect ECONNREFUSED +1ms
	  ioredis:connection error: Error: connect ECONNREFUSED +0ms
	  ioredis:redis status[127.0.0.1:30002]: connecting -> close +0ms
	  ioredis:connection skip reconnecting because `retryStrategy` is not a function +0ms
	  ioredis:redis status[127.0.0.1:30002]: close -> end +0ms
	  ioredis:redis status[127.0.0.1:30003]: connecting -> close +0ms
	  ioredis:connection skip reconnecting because `retryStrategy` is not a function +0ms
	  ioredis:redis status[127.0.0.1:30003]: close -> end +0ms
	  ioredis:redis status[127.0.0.1:30001]: connecting -> close +0ms
	  ioredis:connection skip reconnecting because `retryStrategy` is not a function +0ms
	  ioredis:redis status[127.0.0.1:30001]: close -> end +0ms
	  ioredis:redis status[127.0.0.1:30002]: [empty] -> connecting +18ms
	  ioredis:redis status[127.0.0.1:30003]: [empty] -> connecting +3ms
	  ioredis:redis status[127.0.0.1:30001]: [empty] -> connecting +3ms
	  ioredis:cluster status: connecting -> connect +0ms
	  ioredis:cluster status: connect -> ready +0ms
	  ioredis:connection error: Error: connect ECONNREFUSED +2ms
	  ioredis:connection error: Error: connect ECONNREFUSED +0ms
	  ioredis:connection error: Error: connect ECONNREFUSED +0ms
	  ioredis:redis status[127.0.0.1:30001]: connecting -> close +0ms
	  ioredis:connection skip reconnecting because `retryStrategy` is not a function +0ms
	  ioredis:redis status[127.0.0.1:30001]: close -> end +0ms
	  ioredis:redis status[127.0.0.1:30003]: connecting -> close +0ms
	  ioredis:connection skip reconnecting because `retryStrategy` is not a function +0ms
	  ioredis:redis status[127.0.0.1:30003]: close -> end +0ms
	  ioredis:redis status[127.0.0.1:30002]: connecting -> close +1ms
	  ioredis:connection skip reconnecting because `retryStrategy` is not a function +0ms
	  ioredis:redis status[127.0.0.1:30002]: close -> end +0ms
	  ioredis:redis status[xxx.us-west-2.compute.amazonaws.com:30001]: ready -> close +156ms
	  ioredis:connection skip reconnecting since the connection is manually closed. +0ms
	  ioredis:redis status[xxx.us-west-2.compute.amazonaws.com:30001]: close -> end +0ms
	  ioredis:redis status[xxx.us-west-2.compute.amazonaws.com:30002]: ready -> close +5ms
	  ioredis:connection skip reconnecting since the connection is manually closed. +1ms
	  ioredis:redis status[xxx.us-west-2.compute.amazonaws.com:30002]: close -> end +2ms
	  ioredis:redis status[xxx.us-west-2.compute.amazonaws.com:30002]: ready -> close +2ms
	  ioredis:connection skip reconnecting since the connection is manually closed. +0ms
	  ioredis:redis status[xxx.us-west-2.compute.amazonaws.com:30002]: close -> end +0ms
	  ioredis:redis status[xxx.us-west-2.compute.amazonaws.com:30003]: ready -> close +1ms
	  ioredis:connection skip reconnecting since the connection is manually closed. +0ms
	  ioredis:redis status[xxx.us-west-2.compute.amazonaws.com:30003]: close -> end +1ms
	  ioredis:redis status[xxx.us-west-2.compute.amazonaws.com:30003]: ready -> close +4ms
	  ioredis:connection skip reconnecting since the connection is manually closed. +1ms
	  ioredis:redis status[xxx.us-west-2.compute.amazonaws.com:30003]: close -> end +0ms
	  ioredis:cluster status: ready -> close +0ms
	  ioredis:cluster status: close -> reconnecting +0ms
	  ioredis:redis status[xxx.us-west-2.compute.amazonaws.com:30001]: ready -> close +2ms
	  ioredis:connection skip reconnecting since the connection is manually closed. +1ms
	  ioredis:redis status[xxx.us-west-2.compute.amazonaws.com:30001]: close -> end +0ms
	  ioredis:cluster status: ready -> close +0ms
	  ioredis:cluster status: close -> reconnecting +0ms
	  ioredis:redis status[xxx.us-west-2.compute.amazonaws.com:30003]: ready -> close +11ms
	  ioredis:connection skip reconnecting since the connection is manually closed. +0ms
	  ioredis:redis status[xxx.us-west-2.compute.amazonaws.com:30003]: close -> end +1ms
	  ioredis:redis status[xxx.us-west-2.compute.amazonaws.com:30001]: ready -> close +8ms
	  ioredis:connection skip reconnecting since the connection is manually closed. +0ms
	  ioredis:redis status[xxx.us-west-2.compute.amazonaws.com:30001]: close -> end +0ms
	  ioredis:redis status[xxx.us-west-2.compute.amazonaws.com:30002]: ready -> close +8ms
	  ioredis:connection skip reconnecting since the connection is manually closed. +0ms
	  ioredis:redis status[xxx.us-west-2.compute.amazonaws.com:30002]: close -> end +0ms
	  ioredis:cluster status: ready -> close +1ms
	  ioredis:cluster status: close -> reconnecting +0ms
	  ioredis:cluster Cluster is disconnected. Retrying after 102ms +77ms
	  ioredis:cluster status: reconnecting -> connecting +0ms
	  ioredis:redis status[xxx.us-west-2.compute.amazonaws.com:30001]: [empty] -> connecting +1ms
	  ioredis:redis status[xxx.us-west-2.compute.amazonaws.com:30002]: [empty] -> connecting +0ms
	  ioredis:redis status[xxx.us-west-2.compute.amazonaws.com:30003]: [empty] -> connecting +0ms
	  ioredis:cluster getting slot cache from xxx.us-west-2.compute.amazonaws.com:30001 +0ms
	  ioredis:redis queue command[0] -> cluster(slots) +5ms
	  ioredis:cluster Cluster is disconnected. Retrying after 102ms +0ms
	  ioredis:cluster status: reconnecting -> connecting +0ms
	  ioredis:redis status[xxx.us-west-2.compute.amazonaws.com:30001]: [empty] -> connecting +0ms
	  ioredis:redis status[xxx.us-west-2.compute.amazonaws.com:30002]: [empty] -> connecting +0ms
	  ioredis:redis status[xxx.us-west-2.compute.amazonaws.com:30003]: [empty] -> connecting +1ms
	  ioredis:cluster getting slot cache from xxx.us-west-2.compute.amazonaws.com:30001 +0ms
	  ioredis:redis queue command[0] -> cluster(slots) +0ms
	  ioredis:cluster Cluster is disconnected. Retrying after 102ms +29ms
	  ioredis:cluster status: reconnecting -> connecting +1ms
	  ioredis:redis status[xxx.us-west-2.compute.amazonaws.com:30001]: [empty] -> connecting +0ms
	  ioredis:redis status[xxx.us-west-2.compute.amazonaws.com:30002]: [empty] -> connecting +0ms
	  ioredis:redis status[xxx.us-west-2.compute.amazonaws.com:30003]: [empty] -> connecting +0ms
	  ioredis:cluster getting slot cache from xxx.us-west-2.compute.amazonaws.com:30002 +1ms
	  ioredis:redis queue command[0] -> cluster(slots) +0ms

**Comment by fbacker** [comment]
Looks like it goes from the host I wanted to 127.0.0.1 in the end?
I've installed redis locally so now it works but might want to check into using redis cluster with another hostname.
