### ISSUE TITLE
Cluster: cannot know the number of clients that received the message

### ISSUE THREAD

**Issue by inaferando** [luin/ioredis#221]
I have one test script that publishes a message and another one that receives them. Receiver script gets all messages, but publishing script passes unpredictable value to result callback.

```
var Redis = require('ioredis');
var cluster = new Redis.Cluster([...]);

cluster.publish('mychannel', 'mymessage').then(function(result) {
  console.log(result);
});
```

In the code above the value of `result` can be 1 or 0 from time to time, while all message are being delivered to one subscriber.

redis version is 3.0.5
ioredis version is 1.13.1
hiredis version is 0.4.1

**Comment by luin** [comment]
It's because the `result` is returned by redis, and you'll get the same result when using redis-cli.
