### ISSUE TITLE
TypeError on dumpBuffer to restore

### ISSUE THREAD

**Issue by genediazjr** [luin/ioredis#222]
```javascript
originRedisClient.dumpBuffer(key, function (err, value) {
  targetRedisClient.restore(key, 0, value, function (err) {
    // TypeError: must start with number, buffer, array or string
  });
});
```
I'm getting `TypeError: must start with number, buffer, array or string` on restore of buffer from dump.
I used `dumpBuffer` because `dump` gives me `ERR DUMP payload version or checksum are wrong`

**Comment by luin** [comment]
Are `originRedisClient` and `targetRedisClient` connected to redis servers with different versions? I tried with two server with the same version and it worked:

```javascript
var redis = new Redis();
var redis2 = new Redis(6909);

var key = 'foo';
redis.dumpBuffer(key, function () {
  redis2.restore(key, 0, value, function (err, res) {
    console.log(err, res); // err is null and res is 'OK'
  });
});
```

**Comment by genediazjr** [comment]
No, origin and target are connected on the same redis server but on a different db
```javascript
var originRedisClient = new Redis({db: 0});
var targetRedisClient = new Redis({db: 1});
```
I'm testing dump and restore from db to db.

**Comment by genediazjr** [comment]
The problem was due to my nodejs installation. I got it working.
