### ISSUE TITLE
Remove event handler after is set

### ISSUE THREAD

**Issue by pensierinmusica** [luin/ioredis#224]
Hi,

Thanks for developing this amazing module!

Just a quick question: is there any way to remove an event handler after it's set?

For example:

```js
redis.on('ready', function () {
  console.log('hello');
});

// Later on somewhere in the code...

redis.on('ready', null);
```

In some cases I need to remove the handler, and I wouldn't like to leave a "dead" function there like:

```js
redis.on('ready', function () {});
```

Is there any way to achieve this? Thanks!

**Comment by luin** [comment]
`redis` is just an instance of the built-in EventEmitter module. You can refer to the official documentation here: https://nodejs.org/dist/latest-v4.x/docs/api/events.html#events_emitter_removelistener_event_listener

**Comment by pensierinmusica** [comment]
Thanks! Cheers  :)
