### ISSUE TITLE
Cluster emits 'ready' when not connected.

### ISSUE THREAD

**Issue by Salakar** [luin/ioredis#225]
When using cluster, the `ready` event is emitted even if the connection is invalid or not connected.

The readme says that `ready` fires after `connect`. Is that correct?

Was getting this when my cluster was down. Also happens if I just put in a couple random hosts that don't exist - still get a ready event.

When I try running any commands I get `Connection is closed` errors.

**Comment by luin** [comment]
`ready` fires right after fetching the slot information of the cluster by sending `CLUSTER SLOTS` to one of the nodes in the cluster, so that `ready` means there's at least one node is accessible and ioredis has already known where the other nodes are.

`Connection is closed` is because all nodes are down and `clusterRetryStrategy` is disabled.

However, it's strange to get `ready` event when you put in a couple random hosts that don't exist. Could you please enable the debug mode (`DEBUG=ioredis:* node yourapp.js`) and post the logs here?

**Comment by Salakar** [comment]
When i tried with just one cluster node, which was in a `CLUSTER DOWN` state it still emits ready. But there's no connections. 

i.e:

```javascript
this.client = new Redis.Cluster([
        {host: '127.0.0.1', port: 6379}  // in a CLUSTER DOWN state
      ]);
```

I'm using default settings, so not touched `clusterRetryStrategy` yet.

**Comment by luin** [comment]
That's correct. `CLUSTER SLOTS` command returns successfully even if the cluster in the `CLUSTER DOWN` state. In that case, when emits `ready`, ioredis has already connected to a node and fetch the information of the cluster successfully.

**Comment by Salakar** [comment]
Should it not check that the cluster can receive commands?

The readme says `ready` is emitted when the server is ready to receive commands, doesn't `CLUSTER DOWN` count as not ready to receive commands (as in userland ones, as apposed to info commands ioredis uses to check state)?

**Comment by Salakar** [comment]
```javascript
import Redis from 'ioredis';

const client = new Redis.Cluster([
  {host: '127.0.0.1', port: 7777}
]);

client.on('error', function (error) {
  console.dir(error);
});

client.on('ready', function () {
  console.log('****** READY ******'); // getting spammed

  client.get('ABCD', function (err) {
    // never calls back - stuck in offline queue i guess?
    console.error(err);
  });
});
```

It also spams ready loads when cluster is down.

![image](https://cloud.githubusercontent.com/assets/5347038/12197876/d2cf7dea-b602-11e5-9afd-f44970014882.png)

**Comment by luin** [comment]
yeah, you're right. `ready` event is a little misleading here. I'm going to make some changes on this in 2.0.

**Comment by Salakar** [comment]
Ok, thanks. Other than that though, ioredis is awesome :+1:

**Comment by luin** [comment]
Closing this issue in favour of #261
