### ISSUE TITLE
Do I need to close connections manually?

### ISSUE THREAD

**Issue by thelinuxlich** [luin/ioredis#23]

**Comment by luin** [comment]
In most situations you don't, since connections to redis is lightweight and will be closed when your program exits.

**Comment by mertonium** [comment]
Would you need to close the connections in the case where one has, let's say, an express app and different routes open redis connections? Since the app doesn't exit very often.

**Comment by klinquist** [comment]
@mertonium 
I would recommend keeping the connection open and sharing it across all of your routes.  Simply add a "redisConnector.js"  that exports the connection  and include it in all of your routes.

**Comment by mertonium** [comment]
Thanks for the response @klinquist ! In my case I thought I'd done that. Then, after my question here, I realized we had an errant `.quit()` in the code that was closing the connection.  Got rid of it an all was well :)
