### ISSUE TITLE
Synchronous Functions?

### ISSUE THREAD

**Issue by RyanMcDonald** [luin/ioredis#230]
I have the following code in my application:
```
redis.client('setname', 'application name');
```

Is this a synchronous call? Since I haven't specified a callback or used a promise? Similar to how the documentation just has:
```
redis.set('foo', 'bar');
```
which also doesn't specify a callback or promise. Is this how these functions should be used? Or is it asynchronous and I should be specifying a callback or promise?

**Comment by klinquist** [comment]
They are async calls in which a callback is optional.  The last parameter is always the optional callback.
You should specify a callback if you want to check for error/results!

**Comment by BridgeAR** [comment]
To handle errors properly it is best to use promises. If you do not set a callback a promise will be returned by the call. The call itself is async but redis works sync so it is possible to fire multiple calls without waiting for the response but this is not recommended in most cases.

**Comment by RyanMcDonald** [comment]
Thanks guys. That helps a lot!
