### ISSUE TITLE
on 'subscribe' event

### ISSUE THREAD

**Issue by ORESoftware** [luin/ioredis#232]
Hi there

Quick question for yall

is there an `on('subscribe')` event?

or should I do this instead?

``` js
var EE = require('events');
var ee = new EE();

var sub = new Redis();

sub.subscribe('xyz',function(err){
     if(err){
           ee.emit('error', {});
       }
      else{
           ee.emit('subscribe','xyz');
    }
});
```

**Comment by luin** [comment]
The callback of `subscribe` command is invoked when all channels are subscribed successfully. ioredis won't emit `subscribe` event, so your code seems to be a solution.

**Comment by ORESoftware** [comment]
humma, it seems like an on('subscribe') event would be useful to have in the library itself...am I missing something?

**Comment by luin** [comment]
Yes, that makes sense.

**Comment by ORESoftware** [comment]
ok thanks for understanding, I look forward to the feature and let me know if you wish for me to make a PR

**Comment by ORESoftware** [comment]
any update on this one? thanks for your help

**Comment by luin** [comment]
A little busy these days, will get time to implement it this weekend. Pull request is welcome before that.

**Comment by ORESoftware** [comment]
for sure, will give it a shot
