### ISSUE TITLE
how to detect dead subscribe connections?

### ISSUE THREAD

**Issue by xpiwo** [luin/ioredis#240]
I am subscribing to a channel, how can ioredis auto-reconnect in case of silent connection drop?

eg network failure / iptables block (takes a few seconds to kick in)

iptables -A OUTPUT -p tcp --destination-port 6379 -j DROP

the message(s) event stops firing, but ioredis still considers it a valid connection.

ping-ing the same connection does not seem to work ('ERR only (P)SUBSCRIBE / (P)UNSUBSCRIBE / QUIT allowed in this context').

Thanks.

**Comment by luin** [comment]
ioredis enables tcp keep alive by default, so that dead connections should be detected after a while.

**Comment by xpiwo** [comment]
right, looks like [10 minutes](http://stackoverflow.com/questions/18614176/why-nodejs-keepalive-does-not-seem-to-work-as-expected).

**Comment by xpiwo** [comment]
upgrading to a newer redis version also works, 2.8+ allows ping in subscription mode.

**Comment by xpiwo** [comment]
in theory even older redis error-response can be considered PONG.

however even when pinging, ioredis just tries to ping and never gets the response back, so that does not help much.

10 minutes is a lot of time. i guess i can keep track of the last PONG received. is there a command to force ioredos to re-connect?

**Comment by luin** [comment]
You may config the `TCP_KEEPINTVL` and `TCP_KEEPCNT` options at sysctl level to make system detect dead connection more quick. Or you can send `ping` command periodically and reconnect the connection when the command timed out.

The following code sends `ping` every 500ms and will force ioredis to reconnect if not receiving a response after one second. I haven't tested the code but it should work.

```javascript
var redis = new Redis();
setInterval(function () {
  redis.ping().timeout(1000).catch(function () {
    redis.disconnect(true); // true indicates we need reconnect
  });
}, 500);
```

**Comment by luin** [comment]
@BridgeAR What do you think about adding a built-in heartbeat support similar to the above code? It seems to be a common requirement given Node.js doesn't support specifying `TCP_KEEPINTVL` and `TCP_KEEPCNT` per socket (https://github.com/nodejs/node/issues/4048).

**Comment by BridgeAR** [comment]
This might not be a bad idea. I have to think about it when I'm more awake though. I just realized I just wrote total nonsense somewhere else ;)

**Comment by BridgeAR** [comment]
So after looking at it I see the following issues: if a command takes longer than 500ms on Redis, all fired commands are "failing". That is not intended, so the timeout should be more like 15 seconds or something really "safe" and some people might even want to raise that value further. It is definitely a weighing up for the user: do I want to be sure heavy commands don't trigger a reconnect or do I want to detect timeouts faster.
The client allows all kinds of different use cases and some might really on heavy commands.
But this is not the only downside: the ping may not be fired by the user client as that client might be used as a queue with blocking commands that wait for a arbitrary time. Starting a keep alive client for each user client might not be a good option either (some people use lots of connections and there is a maximum clients per server limit) but it is the only safe way that comes to my mind.

Sadly implementing this in NodeJS would not help us all that much right now, as the feature would not be backported to the LTS versions.

So this might be added as a opt-in option but it is definitely not ideal :/
