### ISSUE TITLE
Weird crash with ioredis

### ISSUE THREAD

**Issue by lejoix** [luin/ioredis#244]
Hi,

First of all you have a great thing going on here, so keep up the good work!

Now for my problem. I have a rest api with express.js. I didn't use promises throughout my project because I wanted the throw error (catch in a more general way) not check for errors in every call approach also async and callback combination works better for us. And for most of the project this is fine. But when I get to Ioredis, there is a weird issue. If I myself throw an error inside a callback of an ioredis operation the normal error catching middleware doesn't catch it but the app crashes with the really annoying message:
"```
ioredis/node_modules/bluebird/js/main/async.js:43
        fn = function () { throw arg; };
Invalid profile id
```" <------my throw message

Code sample:
use(connect-domain) middleware
.....
```
    DBHelper.getConn()
        .get(DBHelper.profilePath(profileId), (err, response) => {
            if (response == null) {
                throw('Invalid profile id');
            }

            if (err != null) {
                throw(err);
            }

            return callback();
```
...
use.(errorcatchingmiddlweare) -> send error response

For the same code where ioredis is not used (even through a chain of callbacks) the error is of course properly catched and handled. 

I am struggling with this error for a while now and will probably need to drop ioredis if we cannot find a solution (with node_redis this doesn't happen, and I am suspecting that promises is the cause of this, I have seen a similar "weird" behaviour when I tried to implement promises in other parts of the project, but as I said I don't want to use promises, the codebase is pretty big and there is no time for a change this amplitude).

Please give me some advice if you have any ideas.

Thank you!

**Comment by luin** [comment]
Hi @lejoix, thank you for using ioredis.
It's not possible to catch a error in an async callback:

```javascript
var redis = new Redis();
try {
  redis.get('foo', function () {
    throw new Error('sync error here');
  });
} catch (e) {
  // The error won't be caught, instead it will crash the process.
}
```

I don't think there's any difference between node_redis and ioredis here, or are you using the [`domain` module](https://nodejs.org/api/domain.html) or something similar?

**Comment by lejoix** [comment]
Hi,

Thank you for your response. Yes of course I am using domains. I put it wrapped around the code in the description. As you said try catch of course doesn't work with async code, but connect-domain handles that.

**Comment by luin** [comment]
Could you use the following code to reproduce the problem?

```javascirpt
var connect = require('connect');
var connectDomain = require('connect-domain');

var Redis = require('ioredis');
var redis = new Redis();

var app = connect()
    .use(connectDomain())
    .use(function(req, res){
      redis.get('foo', function () {
        throw new Error('hi');
      });
    })
    .use(function(err, req, res, next) {
        res.end(err.message);
    });

app.listen(3001);
```

I got "hi" when running with the latest version of ioredis and node v0.10.14

 ioredis doesn't bind the callback to the current active domain explicitly since bluebird (a dependency of ioredis) should handle the binding.

**Comment by lejoix** [comment]
Yes I can try, although at first sight a problem could be I am using node 4.2.1 (supposedly LTS version). To complicate things even more, the same code, same installation is working on an installation and not on another. So this of course can lead to other discussions, but I am trying a go here because it's crashing in ioredis module. Will come back with feedback

**Comment by lejoix** [comment]
So, of course this part of code is working, also in my earlier tests something similar it was. However I cannot see any part of the app, that could change this and crash it in ioredis. And since the behaviour is not the same either for my local installation and for the remote intstallation ( I am managing both) I am suspecting also a versioning issue of one of the module dependencies. I am really desperate with this and depleted most of the ideas the I found on the net.

**Comment by lejoix** [comment]
OK I did some more extensive tests. It is actually related to https! I have in my app http AND https termination and it is related to https it seems, bacuse on http it's ok but on https it's still crashing inside ioredis.

**Comment by luin** [comment]
Hmm...That's strange. Domain is hard to debug, and IMO that's why it's deprecated for a while. 😄

Let me know if I can help anyway.

**Comment by lejoix** [comment]
Just as an idea, do you know a better errorhandling approach for async calls than domains ?

**Comment by luin** [comment]
As for me, Promise is good enough, especially when working with async/await (or generator and co module). Refer to the generator and ES7 async/await part: https://strongloop.com/strongblog/async-error-handling-expressjs-es7-promises-generators/.

Here's an example:

```javascript
const Redis = require('ioredis');
const redis = new Redis();
function *() {
  try {
    const bar = redis.get('foo');
    if (bar !== 'bar') {
      throw new Error('bar is not bar');
    }
  } catch (err) {
    // handle errors here
  }
}
```

**Comment by lejoix** [comment]
Thank you, for your patience and responses. It seems that domain is not the way to go (unfrotunately this has become clearonly now when the app is big and complex). With a simple application (like your example I cannot crash it), but with a big and complex handling a lot of requests at once, if requests that throw inside come in fast enough, domain somehow "loose" the context, So for exmaple if I slowly make the same requests it's fine it's caught if I make it really fast, after 10th or so request it crashes. That's why it only popped up now. Also it happen on http also of course. Erm need to find a better way then promises, I really cannot rewrite the app at this point :)

Thanks, keep it up!
