### ISSUE TITLE
ioredis 2: custom filter predicates for "scaleReads" 

### ISSUE THREAD

**Issue by ramonsnir** [luin/ioredis#250]
Great job, btw, both on ioredis 1 and ioredis 2!

It would be really great if it would be possible to give the "scaleReads" option a custom function that filters which nodes are applicable to be read from, in case not all nodes are born equal (e.g. some are closer to the application than others, network-wise).

Thinking about it, even a bit more:

1. Giving 2 functions: one for readonly commands and one for readwrite commands.
2. Supporting not only a yes/no boolean, but a 0-9 priority (so ioredis would prefer those with 9 over those with 8, etc. etc., but never those with 0). This is for more complicated Redis Cluster topologies.

If you agree that this is at least an acceptable feature, I could open a PR for you into the 2.x branch.

P.S.: shouldn't there be a way to mark eval/evalsha as readonly - so reading lua scripts won't be redirected to a master?

**Comment by luin** [comment]
Sounds interesting. Could you give me an example about the custom function case?

P.S. It seems that redis always consider `EVAL` and `EVALSHA` as writes, so the slaves will not handle them (https://github.com/antirez/redis/blob/unstable/src/cluster.c#L5178-L5184).

**Comment by ramonsnir** [comment]
The one I'm personally having at the moment is that my cluster spans across multiple network subnets, and the latency between them is relatively large. So my function would take the node's IP, check if it's in the "local subnet IP range", and return a lower priority if it isn't. This would lower significantly the read times, as otherwise reads would go to a random slave which may or may not be nearby (i.e. 50ms latency instead of 1ms latency).

P.S.: That is too bad :disappointed: Yet another regression from classic Redis.

**Comment by luin** [comment]
That makes sense. What about a function with two parameters `slaves` and `command`? `slaves` is an array of the slaves serving the slot. Return an index of the array to send the command to the specified slave, or return a `false` value to send to master.

```javascript
new Redis.Cluster([/* nodes */], {
  scaleReads: function (slaves, command) {
    if (command.name === 'get') {
      return 0;
    }
  }
});
```

**Comment by ramonsnir** [comment]
That could work, although I thought that you'd prefer to keep as much logic as possible inside the library, just letting the custom function filter out low-prioritized nodes.

Your suggestion 100% solves the problem.

**Comment by luin** [comment]
Closing this issue in favour of #252.
