### ISSUE TITLE
Getting Master Address from Sentinal Connection

### ISSUE THREAD

**Issue by jrzesz33** [luin/ioredis#253]
First off, I really like this client, super easy to get going and solid API. I was building a test application to test some strange behavior, the client appears to take care of identifying the master when connecting thru a sentinal and I was curious if there was anything in the io redis api that would return the master ip address? The redis command only displays localhost within the host attribute.

**Comment by luin** [comment]
Check out `redis.stream` after `connect` event:

```javascript
var redis = new Redis();
redis.on('connect', function () {
  console.log(redis.stream.remoteAddress);
  console.log(redis.stream.remoteFamily);
  console.log(redis.stream.remotePort);
});
```
