### ISSUE TITLE
keyPrefix in 'redis.keys' command

### ISSUE THREAD

**Issue by apostopher** [luin/ioredis#254]
The following code snippet returns empty array for 'keys' command.
```JavaScript
    const Redis = require('ioredis');
    const redis = new Redis({keyPrefix: 'foo:'}); // set the namespace
    redis.set('bar:baz', 1).then(()=> {
      return redis.keys('bar:*').then((keys)=>{
        console.log(keys); // output is []. shouldn't it be ["foo:bar:baz"] ?
      });
    }).catch((error)=> {
      console.log(error);
    });
```
It appears that `redis.keys` command does not add `foo:` namespace.

**Comment by luin** [comment]
Duplicate of #239.
The first argument of `KEYS` command is a pattern rather than key name, so we don't prefix it with `keyPrefix`.

**Comment by apostopher** [comment]
ok. got it! closing this issue. thanks!
