### ISSUE TITLE
Multiple notifications for the same keyspace event if subscribe is called multiple times

### ISSUE THREAD

**Issue by jomeier** [luin/ioredis#257]
Hi,

I want to get notified by redis if keys change. I use 'subscribe' with the keyspace event system on several keys to get notified if they change. The client can dynamically subscribe on keys. 

My problem is, that if I try to change the subscriptions by calling 'subscribe' N times with different keyspace event names, and a keyspace event is triggered by writing to a subscribed key in the database, I get a notification for the same keyspace event N times.

Maybe 'subscription' can be called only once? How do I change the subscriptions dynamically then?

Thanks a lot and best regards,

Josef

**Comment by luin** [comment]
Did you unsubscribe the previous channels?

**Comment by jomeier** [comment]
Found the problem in my own code:

I was calling this code:
```
redis.on('message', function(channel, message) {
  // only got one message when updating "Example:Meas"
});
```

every time when I called ```subscribe()```.
