### ISSUE TITLE
no error if password not provided but is required

### ISSUE THREAD

**Issue by mkozjak** [luin/ioredis#258]
Nothing comes up if we don't provide a password while the server demands it.

```
'use strict'

var co = require('co')
var Redis = require('ioredis')
Redis.Promise.onPossiblyUnhandledRejection(function(error) {
  console.log('unh error:', error)
})

// this one raises authError
co(function*() {
  var r = new Redis({
    port: 6379,
    host: '127.0.0.1',
    password: 'foo',
    autoResendUnfulfilledCommands: false
  })

  r.on('ready', () => console.log('ready'))
  r.on('error', (error) => console.log('error:', error))
  r.on('authError', (error) => console.log('authError:', error))
})

// this one doesn't
co(function*() {
  var r = new Redis({
    port: 6379,
    host: '127.0.0.1',
    password: '',
    autoResendUnfulfilledCommands: false
  })

  r.on('ready', () => console.log('ready'))
  r.on('error', (error) => console.log('error:', error))
  r.on('authError', (error) => console.log('authError:', error))
})
```

node v 5.6.0, OS X 10.11, ioredis 1.12.2

Am I doing something wrong?

**Comment by luin** [comment]
`authError` event is only emitted when the password provided is wrong. If the password is empty, ioredis won't send the `AUTH` command to the Redis, so that there's no chance can ioredis know the password is wrong.
However, if you send any command manually, you'll get the `NOAUTH` error returned by Redis server.

**Comment by mkozjak** [comment]
Thanks for responding so quickly, @luin :)

This works, yes. I'll try sending some info request if available, right after connecting to check up on that.

But why aren't you emitting a new error upon this? Or an authError? Since you emit it if the password is wrong, you should emit it when there's no password, but it's required.

Regards!

**Comment by luin** [comment]
@mkozjak That makes sense. I added it to the 2.x list. Thank you for pointing this out!

**Comment by mkozjak** [comment]
Thanks!

**Comment by luin** [comment]
Closing this issue in favour of #246.
