### ISSUE TITLE
Multiple transactions with .multi()

### ISSUE THREAD

**Issue by lwhorton** [luin/ioredis#26]
I may just be missing something obvious, but I'm having trouble performing multiple `.multi()` calls.

```javascript
return redis.multi()
    .sismember('test-set', someID)
    .sismember('another-test-set', someID)
    .exec(function (err, results) {
        var exists = results.reduce(function (prev, curr, i) {
            return (curr[1] === 1 || prev)
        }, false)

        if (exists === false) {
            return redis.multi()
                .sadd('test-set', someID)
                .sadd('another-test-set', someID)
                .exec()
        }
    })
```

Given this snippet (ignoring the uselessness of the actual inserts, obviously redis won't allow duplicate entries), I would expect the behavior of the `redis.multi() ` to chain the promises such that the first `.exec()` invocation doesn't resolve/reject anything until after the second call to `redis.multi()` has finished its `exec()`.

That is not the case however. I currently have to wrap the whole block in my own `new Promise(function (resolve, reject) { }` and invoke `resolve()` manually in the second `.exec()` callback.

```javascript
return new Promise(function (resolve, reject) {
    return redis.multi()
        .sismember('test-set', someID)
        .sismember('another-test-set', someID)
        .exec(function (err, results) {
            var exists = results.reduce(function (prev, curr, i) {
                return (curr[1] === 1 || prev)
            }, false)

            if (exists === false) {
                return redis.multi()
                    .sadd('test-set', someID)
                    .sadd('another-test-set', someID)
                    .exec(function (err, results) {
                        resolve()
                    })
            }
            resolve()
        })
})
```

Is this intentional behavior? Perhaps this is just a wont-fix issue we could leave around for other's benefit?

**Comment by luin** [comment]
ioredis works with node-style callback and promise. However in you case, you mix them up. The following code should work as you expect:
```javascript
return redis.multi()
    .sismember('test-set', someID)
    .sismember('another-test-set', someID)
    .exec().then(function (results) {
      var exists = results.reduce(function (prev, curr, i) {
          return (curr[1] === 1 || prev)
      }, false)

      if (exists === false) {
          return redis.multi()
              .sadd('test-set', someID)
              .sadd('another-test-set', someID)
              .exec()
      }
    });
```

**Comment by lwhorton** [comment]
Hah, oops. It was something simple... thanks.

**Comment by joshuairl** [comment]
I seem to be having a lot of errors that look similar to this:
```
/node_modules/ioredis/node_modules/bluebird/js/main/async.js:43
        fn = function () { throw arg; };
```
Having to do with async.js:43

Is this something similar to this issue?

**Comment by luin** [comment]
This error stack doesn't help much. Could you please enable `showFriendlyErrorStack` (described in https://github.com/luin/ioredis#error-handling) and give me a full error stack.
