### ISSUE TITLE
ioredis + newrelic transaction bug

### ISSUE THREAD

**Issue by guilhermef** [luin/ioredis#260]
When using ioredis with newrelic,
it loses track of the current transaction inside a redis callback.
It doesn't happen when using just a bluebird promise.
You can tell by the `"msg":"No transaction found for custom parameters."` log.
I've made a repo to reproduce the test:
https://github.com/guilhermef/ioredis_newrelic_bug

**Comment by luin** [comment]
I'm not familiar with newrelic. But I think the problem may on the newrelic side.

**Comment by guilhermef** [comment]
You're right, they're not instrumenting iorelic the right way.
I've opened a ticket on NewRelic too,
but I just left this issue as a reminder for others.

**Comment by luin** [comment]
Cool. Let me know if there's any update or anything I can help.

**Comment by guilhermef** [comment]
I've started a PR on node-newrelic to add ioredis support: https://github.com/newrelic/node-newrelic/pull/212
A few tests aren't passing, but I'm already trying to fix it.

**Comment by luin** [comment]
Great work!

**Comment by guilhermef** [comment]
It's done, now new relic supports ioredis, I just need them to accept the PR.

**Comment by pwnsrma** [comment]
Great work @guilhermef, now this support is live in node-newrelic v1.26.2

**Comment by luin** [comment]
🎉
