### ISSUE TITLE
issue connecting to azure redis cache

### ISSUE THREAD

**Issue by jamesdixon** [luin/ioredis#267]
Hello!

I just switched from `node-redis` to `ioredis` and am getting errors when attempting to connect to my Azure Redis Cache. I was previously able to connect to the cache when using `node-redis`. I was also able to connect via the RDM desktop client, but not the Medis client, which also appears to be dependent on `ioredis`. In debug mode, I see the following when starting my server:

```
ioredis:redis status[scout-staging.redis.cache.windows.net:6380]: [empty] -> connecting +0ms
  ioredis:redis status[104.43.163.85:6380]: connecting -> connect +255ms
  ioredis:redis write command[0] -> info() +2ms
  ioredis:connection error: Error: read ECONNRESET +9s
  ioredis:redis status[104.43.163.85:6380]: connect -> close +1ms
  ioredis:connection reconnect in 2ms +1ms
  ioredis:redis status[104.43.163.85:6380]: close -> reconnecting +0ms
  ioredis:redis status[104.43.163.85:6380]: reconnecting -> connecting +2ms
  ioredis:redis status[104.43.163.85:6380]: connecting -> connect +40ms
  ioredis:redis write command[0] -> info() +1ms
  ioredis:connection error: Error: read ECONNRESET +39s
  ioredis:redis status[104.43.163.85:6380]: connect -> close +1ms
  ioredis:connection reconnect in 4ms +0ms
  ioredis:redis status[104.43.163.85:6380]: close -> reconnecting +0ms
  ioredis:redis status[104.43.163.85:6380]: reconnecting -> connecting +5ms
  ioredis:redis status[104.43.163.85:6380]: connecting -> connect +32ms
  ioredis:redis write command[0] -> info() +1ms
  ioredis:connection error: Error: read ECONNRESET +14s
  ioredis:redis status[104.43.163.85:6380]: connect -> close +1ms
  ioredis:connection reconnect in 6ms +0ms
  ioredis:redis status[104.43.163.85:6380]: close -> reconnecting +0ms
```

I've attempted to connect on both non-SSL (6379) and TLS (6380) ports with no luck. 

In terms of configuration, I'm using the bare basics: host, port and password.

I'd really appreciate any assistance you can offer!

Thank you,
James

**Comment by luin** [comment]
It seems you didn't provided a password. The option name for password is `password` in ioredis instead of `auth_pass`. However for Medis, since the option name is correct, it's strange that your connection is rejected. Could you show me the error message you got from Medis?

**Comment by jamesdixon** [comment]
I double checked and a password is definitely being set. Here's the options being passed into the constructor:

```javascript
{ 
  host: 'scout-staging.redis.cache.windows.net',
  port: '6379',
  options: { password: 'CUV8YV3X6Pl9qGd6ICbywk0rKVMrxPjQTO8wdhieIh8=' } 
}
```

If you'd like to try it, you can use those credentials to see if you can reproduce. There's nothing on there that's sensitive at the moment and I'll reset the key later.

As for Medis, my mistake - I accidentally had the SSL port entered. I verified that I am able to connect with Medis using the credentials above.

**Comment by jamesdixon** [comment]
Note that I'm using `ioredis` through a `hapi.js` plugin called [hapi-ioredis](https://github.com/cilindrox/hapi-ioredis). If you're able to reproduce without the plugin, there could be another issue. However, I am able to connect to my local Redis instance, so not sure what the the problem could be.

**Comment by luin** [comment]
The password option should be passed at the same level as `host` and `port`:

```javascript
'use strict';

var Redis = require('ioredis');
var redis = new Redis({
  host: 'scout-staging.redis.cache.windows.net',
  port: 6379,
  password: 'CUV8YV3X6Pl9qGd6ICbywk0rKVMrxPjQTO8wdhieIh8='
});

redis.info(console.log);
```

**Comment by jamesdixon** [comment]
Yikes. My apologies. When I read the docs, I was reading it as passing `host`, `port`, and then an `options` object with `password`, forgetting the fact that I was passing an object and not explictly passing params to the constructor. Very sorry, but thank you for your help!

**Comment by luin** [comment]
:laughing:
