### ISSUE TITLE
The .del method is not accepting callbacks

### ISSUE THREAD

**Issue by flaviolivolsi** [luin/ioredis#269]
Hello,

I'm trying out ioredis and I got an issue. I'm using the .del method like this:

```javascript
redis.del(key)
.then(function() {
  console.log('No errors');
})
.catch(function(error) {
  console.log('Got an error');
});
```

But I'm not getting logs at all, while there is no problem for the .setex method.

Do you know if the .del method actually supports callbacks?

Thank you,
Flavio

**Comment by luin** [comment]
Every command (including `del`) accepts a callback. Could you please enable the debug mode (`DEBUG=ioredis:* node yourapp.js`) and post the logs here?

**Comment by flaviolivolsi** [comment]
Thank you @luin and forgive me for opening this issue, I found that it wasn't related to redis but to the gulp task. The process.exit() prevented the callback from executing. Thank you anyway!
