### ISSUE TITLE
How to handle errors?

### ISSUE THREAD

**Issue by thelinuxlich** [luin/ioredis#27]
Like these:
```
Unhandled rejection ReplyError: CLUSTERDOWN The cluster is down
Unhandled rejection ReplyError: UNBLOCKED force unblock from blocking operation, instance state changed (master -> slave?)
```

**Comment by luin** [comment]
https://github.com/luin/ioredis#error-handling

**Comment by thelinuxlich** [comment]
But what should I do to avoid these errors?

**Comment by luin** [comment]
What do you mean by "avoid"? If you don't want see these errors in the log, just give every command a callback or use `onPossiblyUnhandledRejection` to catch errors globally.

**Comment by thelinuxlich** [comment]
I thought there was a configuration to avoid UNBLOCKED, for example

**Comment by luin** [comment]
Not possible with ioredis. For instance `CLUSTERDOWN The cluster is down` is because not all slots are served by the cluster, which can be avoided by config Redis properly.
