### ISSUE TITLE
Parser: auto is no longer a valid option

### ISSUE THREAD

**Issue by shaharmor** [luin/ioredis#271]
Hi,

Starting from this commit on the `redis-parser` module: https://github.com/NodeRedis/node-redis-parser/commit/595d3e89e45a02ddd278d335d7c341a31f832035

The `parser: auto` option here: https://github.com/luin/ioredis/blob/master/lib/redis.js#L164 is invalid and will result in using the javascript parser. It should be changed to `hiredis`

**Comment by shaharmor** [comment]
Why use the `javascript` default? You can use `hiredis` and it will fallback to `javascript` if its not installed

**Comment by shaharmor** [comment]
The only thing that wasn't working is the `auto`

**Comment by luin** [comment]
Oh, my bad. I thought most people will use the `javascript` parser so I used it as default. After looking the changes on redis-parser, seems setting the default parser option to `null` is same to `"auto"` in the previous versions of redis-parser.

**Comment by BridgeAR** [comment]
It was late in the night when I changed that and the "default" parser (as stated in the README) should be chosen (so first hiredis and if not available the js parser) instead. Nevertheless I'd like to keep the warning to make sure it's properly implemented and therefore how the fallback mode works is not that important.

@luin Sorry for not checking your code before releasing the new version, I'll do that next time! I was not aware that ioredis used the word "auto" and yes, my way of implementing auto was to pass `null` or `undefined` to the parser.

**Comment by luin** [comment]
@BridgeAR Aha, never mind. I didn't read the changed carefully (`"auto"` is indeed a tricky default value :laughing: ).

I opened a pull request #272 for this.

@shaharmor I also added you as a collaborator.

**Comment by shaharmor** [comment]
@luin thanks a lot, i appreciate it!
Any specific guidelines you are following i should know about?

**Comment by luin** [comment]
@shaharmor Not much, just submit a pull request for every bugfix and feature so that we don't need to revert a commit on the master branch like me. :joy:

**Comment by BridgeAR** [comment]
The parser change yesterday: http://www.commitstrip.com/en/2014/05/07/the-truth-behind-open-source-apps/ :laughing: 

[v.1.3](https://github.com/NodeRedis/node-redis-parser/releases/tag/v.1.3.0) knows 'auto' from now on too and falls back into that mode if it does not know what parser was requested instead of always choosing the JS parser (in the later case it'll print a warning though).

**Comment by luin** [comment]
:clap:
