### ISSUE TITLE
[question] Redis sentinal connect

### ISSUE THREAD

**Issue by shiraaa** [luin/ioredis#274]
Hi guys,
I tried to connect Sentinel with the following code:(I added password argument)
var redis = new Redis({
  sentinels: [{ host: 'localhost', port: 26379 }, { host: 'localhost', port: 26380 }],
  name: 'mymaster',
{password: ****}
});

it didn't work , I validated all the arguments a few times. I also checked the sentinel configurations,
I checked that the the name is of the master node. (our IT admin configured it.)
my question is how can I debug it? is it the correct syntax?  maybe there are known pitfalls regarding redis config that prevent the connection.
Thanks,
Shira

**Comment by luin** [comment]
It looks correct. You can enable the debug mode to see what happened (`DEBUG=ioredis:* yourapp.js`).

**Comment by shiraaa** [comment]
Thank u very much!
