### ISSUE TITLE
a question about heartbeat (or tcp-keepalive) and reconnect api

### ISSUE THREAD

**Issue by kunth** [luin/ioredis#275]
As we need use ioredis and redis sentinel in our production environment, I have two questions:

1. In general we use heartbeat in application layer to detect whether the app(redis master) is active, instead of tcp keepalive, which is in tcp layer. ~~I have tested the "tcp-keepalive" parameters in redis, it turns out good. I am still confused about that whether we should use application-layer heartbeat.~~

2. Based on question 1, ioredis have no api to actively detect dead connections(such as network failures), although the sentinels know that and already do a failover, but the sentinels cannot actively contact the ioredis, so in this situation ioredis need actively detect the ping timeout and reach sentinel again. This is some alike the [issue](https://github.com/luin/ioredis/issues/240) . Why not writing a redis.reconnect() function, I think, in that case we can actively detect a dead connection through PING command and do a redis.connect() operation(my redis instance is created from sentinel, so I can always get a master), at the same time the commands would not be lost.

If not clear about my questions, I can describe it in CHINESE.

**Comment by luin** [comment]
1. client side heartheat is useful since TCP keepalive options supported by Node.js is not flexible enough.

2. `redis.disconnect(true)` will reconnect to the Redis (https://github.com/luin/ioredis/blob/master/lib/redis.js#L302).

**Comment by kunth** [comment]
Hi luin, redis.disconnect(true) may not work for me since

1. As I disable the INPUT and OUTPUT packets of redis-server's port(using iptables), redis.disconnect(true) would make origin tcp connection FIN_WAIT_1 state, the connection is not closed, neither nor the new connection created.

2. What's more, I do not want to lose any pending commands in ioredis client.

**Comment by kunth** [comment]
I had made a [**roughly** modification](https://github.com/kunth/ioredis/commit/cc3157b71d9178559ee46fd2b7ab4093a9c5938f) which meets my own requirements(after detecting that master is down, get a new connection from sentinel, not losing any commands at the same time), but I do not kown whether it is good enough.

**Comment by luin** [comment]
I looked into your modification, but I don't see where you reuse the original stream and reconnect again since `Connector#reconnect` doesn't call `Connector#connect`. Should `process.nextTick` be `this.connect` in `Connector#reconnect`?

**Comment by kunth** [comment]
Well, I do not look deep into the code, previously what I want to do in Connector#reconnect is to replace Connector#connect. So does the Redis#reconnect. But my experiments turn out that the procedures is as follows:

(1)The app detects that current ioredis client() cannot connect to redis
    ↓
(2)client.reconnect();  // client is an obj created like var client = new Redis{sentinels: "xxx" , name: "yyy"}
    ↓
(3)Redis#reconnect() // [use original connector obj as a param](https://github.com/kunth/ioredis/commit/cc3157b71d9178559ee46fd2b7ab4093a9c5938f#diff-29082f5e41ec25b946c4be3903c9cf39R317)
   ↓
(4)[orginal stream is copied](https://github.com/kunth/ioredis/commit/cc3157b71d9178559ee46fd2b7ab4093a9c5938f#diff-29082f5e41ec25b946c4be3903c9cf39R327)
   ↓
(5)[orginal stream is destroyed](https://github.com/kunth/ioredis/commit/cc3157b71d9178559ee46fd2b7ab4093a9c5938f#diff-29082f5e41ec25b946c4be3903c9cf39R340), and [connectionCloseHandler](https://github.com/kunth/ioredis/commit/cc3157b71d9178559ee46fd2b7ab4093a9c5938f#diff-29082f5e41ec25b946c4be3903c9cf39R351) being called.
  ↓
(6) a new Redis#Redis() object is created, and Redis#connect() beging called.
  ↓
(7) All right. using netstat command we can see a new connection to current master(original slave) being established and all redis commands being executed correctly.

The 6th procedure may be executed many times as sentinels have not done the failover. Anyway the result turn out right after the failover.

I am confused about why a new Redis object would be created, what I intend to do is same Redis object with a new connector(with the same stream which guarantees no losing commands ).

I would take a good look at the related codes in later days.

**Comment by kunth** [comment]
I add two functions in [this commit](https://github.com/kunth/ioredis/commit/3ac0fcb3ca7f66cb87e8717d6e8f99fe120ac2b9). I have made some test and not found any errors as far as I am concerned.
Look forward to hearing your advice.

**Comment by luin** [comment]
I'm wondering whether just calling `redis.stream.destroy()` instead of adding two more functions does the trick, since if the socket is destroyed, a reconnection will be triggered automatically.

**Comment by kunth** [comment]
Oh yeah only stream.destroy() works.
You are awesome.
