### ISSUE TITLE
[question] Disconnect from cluster

### ISSUE THREAD

**Issue by devnetf** [luin/ioredis#277]
Hello,
         I have the following test code: 
        `cluster.get('status').then(function(res){
     console.log(res);
     console.log(cluster.status);
     cluster.disconnect(); 
});

setInterval(function(){
    console.log(cluster.status);
}, 1000);`

After cluster.disconnect(); is called, cluster.status still give me "ready". How should I disconnect from the cluster? 

Thanks!

**Comment by devnetf** [comment]
Anyone help please?

**Comment by luin** [comment]
Sorry I didn't notice this issue. Could you enable the debug mode (`DEBUG=ioredis:* node yourapp.js`) to see the logs?

**Comment by devnetf** [comment]
![ioredis_log](https://cloud.githubusercontent.com/assets/4071282/14357643/8447c0e6-fcb7-11e5-8902-8fac8f49aab6.png)

Here is the debug log. I am using the newest version: "2.0.0-rc1"

Thanks!

**Comment by luin** [comment]
Thank you for the details. It seems that hosts `uco-dev***` are resolved to internal ips `10.149.*.*`. Did you create the cluster with the hosts rather than the ips? What about using IP address instead?

**Comment by devnetf** [comment]
Thanks for the quick reply. I am not sure about the cluster setup because it is our system admins who set it up. However, when I change the version to "1.15.1". The exact same code works. Could it be a bug in v2.0.0?

**Comment by luin** [comment]
Yes, it might be a bug if the code works with v1.15.1. I'll look into it this weekend.

**Comment by luin** [comment]
@devnetf This issue should be fixed in v2.0.0-rc2. Feel free to reopen it if the issue still exists. Thank you for the feedback!
