### ISSUE TITLE
Client reply off

### ISSUE THREAD

**Issue by shaharmor** [luin/ioredis#278]
Hey,

Its possible to tell Redis to **not** reply to commands of a certain client by using the `client reply off` command (http://redis.io/commands/client-reply).

I wonder how will the library behave in this situation, considering its possibly waiting for a response from the server for each request.

**Comment by luin** [comment]
It's indeed a interesting command...To support it, maybe we can add a flag to the `Redis#condition` variable to indicate the status of client reply. If the status is not `ON`, then we just don't add the command to the command queue.

**Comment by gcleaves** [comment]
Hello. Can ioredis be used when setting client reply off ?
