### ISSUE TITLE
[question] redis.set is asyncronous?

### ISSUE THREAD

**Issue by alebacca89** [luin/ioredis#279]
Hi, I've a question:
In the example below

```
var Redis = require('ioredis');
var redis = new Redis();

redis.set('foo', 'bar');
redis.get('foo', function (err, result) {
  console.log(result);
});

// Or using a promise if the last argument isn't a function
redis.get('foo').then(function (result) {
  console.log(result);
});

// Arguments to commands are flattened, so the following are the same:
redis.sadd('set', 1, 3, 5, 7);
redis.sadd('set', [1, 3, 5, 7]);

// All arguments are passed directly to the redis server:
redis.set('key', 100, 'EX', 10);
```

it appears that the redis.set function is synchronous, otherwise the redis.get should be in the redis.set callback.

In this example the get function, if function set is asynchronous, may return or bar or null.

The set function is therefore synchronous or asynchronous?
if it is asynchronous you could change the example to make it clearer?

Thanks

**Comment by luin** [comment]
Every command is asynchronous. However, since redis uses a single thread model and all commands are sent one by one, when `get` command is invoked, `set` command should already be executed.

So that in most cases, the following code will always prints "bar":

```javascript
redis.set('foo', 'bar');
redis.get('foo', console.log);
```
