### ISSUE TITLE
How to avoid CLUSTERDOWN and UNBLOCKED?

### ISSUE THREAD

**Issue by thelinuxlich** [luin/ioredis#28]
Revisiting this problem, I asked on the redis google group about it and here it is what @antirez said:

```
Hello,

CLUSTERDOWN is a transient error that happens when at least one master
node is down. If you want the partial portion of the cluster which is
still up to run regardless of a set of hash slots not covered, there
is an option inside the example "redis.conf" file, doing exactly this.

UNBLOCKED is unavoidable since it is delivered to clients that are
blocked into lists that are moved from a different master because of
resharding. We don't want them to wait forever for something that will
never happen, since those lists are not moved into a different master.

So CLUSTERDOWN should be handled by the application and or at client
level directly by retrying. UNBLOCKED should be handled rescanning the
config with CLUSTER SLOTS and connecting to the right node.

Cheers,
Salvatore
```

Configuration-wise, I've set my cluster with "cluster-require-full-coverage" to "no" so I just need to know how to cover this on the application side

**Comment by luin** [comment]
It seems that we can just resend the command when a CLUSTERDOWN error is received. Thank you for the information.

If you want to handle CLUSTERDOWN on the application side, you have to catch all errors returned from Redis and resend the command if the error is CLUSTERDOWN.

**Comment by thelinuxlich** [comment]
I'm also getting a lot of these:

```
ReplyError: EXECABORT Transaction discarded because of previous errors.
```

**Comment by luin** [comment]
You can get previous errors by `error.previousErrors` to see what they are. For instance:

```javascript
redis.multi().set('foo').get('foo').exec().catch(function (err) {
  console.log(err.previousErrors);
});
```

**Comment by thelinuxlich** [comment]
And by the way, if the library has the autoResendUnfulfilledCommands option enabled by default, shouldn't it resend automatically after recovering from CLUSTERDOWN?

**Comment by luin** [comment]
`autoResendUnfulfilledCommands` is used to send unfulfilled commands after a **reconnection**. Since `CLUSTERDOWN` is caused by a master's being offline, we may use `clusterRetryStrategy` option to retry the node.

**Comment by thelinuxlich** [comment]
Now I have 3 masters and 9 slaves, let's keep this open for some days so I can see if those errors persist. I've also configured the cluster with "cluster-slave-validity-factor 0" and "cluster-migration-barrier 1"

**Comment by thelinuxlich** [comment]
good reference: http://redis.io/presentation/Redis_Cluster.pdf

**Comment by thelinuxlich** [comment]
even after increasing slaves and changing config to be more available, I'm receiving EXECABORT ocasionally with this previousErrors:

```
previousErrors:
 [ { [ReplyError: MOVED 1684 192.168.0.1:7000]
 name: 'ReplyError',
 message: 'MOVED 1684 192.168.0.1:7000',
command: [Object] },
{ [ReplyError: MOVED 1684 192.168.0.1:7000]
name: 'ReplyError',
 message: 'MOVED 1684 192.168.0.1:7000',
 command: [Object] } ] } 
```

**Comment by AVVS** [comment]
@thelinuxlich I believe you are trying to perform multi-key operations on the cluster, therefore you get the following errors

**Comment by thelinuxlich** [comment]
You mean, using multi(), right?

**Comment by thelinuxlich** [comment]
My code has one transaction:

```
redis.multi().setnx(new_key, possible_new_session_id).expire(new_key, 1800).exec()
```

**Comment by luin** [comment]
Is there a resharding or failover happens after cluster has been initialized?

**Comment by thelinuxlich** [comment]
no, probably the multi() is not going to the right node

**Comment by AVVS** [comment]
In that case multi() is fine (same key -> `new_key`), but the error says that the hash, that was resolved to new_key is now on another machine in the cluster. These errors should really be handled by the library. What the error says is that, hey, your hash slot caching is wrong, it needs to be updated and the operation needs to be retried.

@luin, please take a look at this, as I believe it needs to be improved. IE, `MOVED` reply must be handled.

**Comment by thelinuxlich** [comment]
By the way, I didn't have this problem with a similar library: https://github.com/thunks/thunk-redis

Their API forces you to set the key explicitly on the multi() and exec() methods

**Comment by luin** [comment]
Yes, you are right. ioredis should be able to handle thess `MOVED` errors. I'll try to fix these errors.

**Comment by AVVS** [comment]
@thelinuxlich thunk-redis takes hash from the first key, and then applies it to all the operations in the multi, but they don't make use of pipeline. Here the first key from pipeline is taken and then the hash is applied to the whole pipeline.

Beside that its pretty much the same, except that ioredis seems cleaner (and with a bug not handling `MOVED` operations :dash:)

**Comment by luin** [comment]
@thelinuxlich As stated in the [README](https://github.com/luin/ioredis#transaction-and-pipeline-in-cluster-mode), ioredis will use the first key in the pipeline queue to calculate the slot. So the problem here isn't ioredis use the wrong key, instead is ioredis doesn't handle `MOVED` errors properly in the transaction.

**Comment by thelinuxlich** [comment]
ok, maybe refreshAfterFails = 1 can solve the issue?

**Comment by luin** [comment]
@thelinuxlich No, it doesn't help since it's a bug of ioredis. I'll fix it soon :-)

**Comment by thelinuxlich** [comment]
Dont know if it is luck, but since setting refreshAfterFails to 1 no error happened

**Comment by luin** [comment]
@thelinuxlich That's interesting. However I'm implementing a more stable transaction strategy in cluster mode.

**Comment by thelinuxlich** [comment]
let's test it ;)

**Comment by thelinuxlich** [comment]
still getting MOVED errors :(

**Comment by luin** [comment]
@thelinuxlich Yes, this commit just fixed CLUSTERDOWN errors, and I'm still working on handling MOVED errors :-)

**Comment by luin** [comment]
There is lot of work to do to implement a stable transaction in cluster mode. However the job is getting done :-)
The pr #33 should handle `MOVED`, `ASK` and `CLUSTERDOWN` error properly.

**Comment by thelinuxlich** [comment]
Great, every new release I'm always testing :)

**Comment by luin** [comment]
Released in 1.3.0

**Comment by thelinuxlich** [comment]
No errors so far...

**Comment by thelinuxlich** [comment]
Seems fixed!
