### ISSUE TITLE
Error handling doesn't catch connect errors?

### ISSUE THREAD

**Issue by mperham** [luin/ioredis#283]
If I stop Redis, this code does not print any sort of error:

```js
var Redis = require('ioredis');
Redis.Promise.onPossiblyUnhandledRejection(function (error) {
  console.log(error)
});
var redis = new Redis({
  connectTimeout: 2,
  showFriendlyErrorStack: true
});
redis.set('foo');
```

Should it?

**Comment by mperham** [comment]
I'm new to the JS world and trying to track down where this error is being swallowed.  The code appears to handle the connect and error events but doesn't seem to call the Promise's reject callback when processing the error here.

https://github.com/luin/ioredis/blob/master/lib/redis.js#L271

**Comment by luin** [comment]
You should listen to the error event instead:

```javascript
redis.on('error', function () {});
```

**Comment by mperham** [comment]
Ok, I'm just pointing out that the readme says to use that onPossiblyUnhandledRejection code to get unhandled errors.  It does not work for this error.

**Comment by luin** [comment]
`onPossiblyUnhandledRejection` is only used to handle uncaught command error (e.g. `redis.set('foo')`). `Redis` class itself is an instance of `EventEmitter`, the connection errors will be emitted in `error` event.
