### ISSUE TITLE
[Suggestion] Not the whole lodash as a dependency, use modularized lodash

### ISSUE THREAD

**Issue by plantain-00** [luin/ioredis#286]
Main reason:
There are about 300 functions in the full lodash, I think less than 20 of them are used here.

for example:

```
npm i --save lodash.defaults

var defaults = require('lodash.defaults');
defaults({ 'user': 'barney' }, { 'age': 36 }, { 'user': 'fred' });
```

**Comment by luin** [comment]
It shouldn't be a problem to include the whole lodash module because the package size isn't sensitive for the backend side IMO.
ioredis uses about 10 methods of lodash. We would have too many dependencies if we have each lodash method as a single dependency.

**Comment by plantain-00** [comment]
I checked the size of the full lodash: about 500kB.
Not only backend, some client programs, for example, electron.js, can use this library too.
I think it may reduce the size about 0.4MB.

An interesting thing is, the node_redis library doesn't use any lodash functions.
