### ISSUE TITLE
error events cannot handle the wrong host error

### ISSUE THREAD

**Issue by kenticny** [luin/ioredis#287]
I try to make the wrong host to connect, and listening the error events, like below:

```javascript
var Redis = require('ioredis');

var redis = new Redis({
  host: '127.10.0.1', //  wrong host
  port: 6379,
  db: 1
});

redis.on('error', function(err) {

  // it should be timeout or connect error
  // but cannot handle the error
  console.log(err);
});

```

and I try to make the wrong port, and the event could handle the connect error 
`[Error: connect ECONNREFUSED 127.0.0.1:16379]`

Is there any way to handle the wrong host connect error ?

**Comment by luin** [comment]
Currently you can use `connectTimeout` option to specify a timeout for connection, and ioredis will reconnect to the server when reaching timeout.

However no error will be emitted in case of timeout. I'll fix this soon.
