### ISSUE TITLE
Sentinels set up with wrong master password not throwing when authentication fails 

### ISSUE THREAD

**Issue by claudio-viola** [luin/ioredis#289]
So not sure how to explain this quickly and cleanly but basically this is roughly the case scenario that happened due to some configuration not being (automatically) deployed correctly:
3 redis servers UP
   ips: 1, 2, 3 port 6379  
   server 1 is master (protected with password: password)
   server 2,3 slaves  (correctly configured to be slave of server 1)
3 sentinels UP 
 ips: 1,2,3 port 26379

Sentinels are badly configured  /etc/sentinel.conf 
sentinel 1 monitor master 1  (correctly configured to monitor the master with the right password)
sentinel 2 monitor master 2 (2 is not a master)  <- bad configuration (master ip is that of the  slave ip )
sentinel 3 monitor master 3 (3 is not a master)  <- bad configuration (master ip is that of the  slave ip )
with quorum set to 2 

With this set up
```
var redis = new Redis({
  sentinels: [{ host: '1', port: 26379 }, { host: '2', port: 26379 }. { host: '3', port 26379 ] }
  name: 'master',
  password: 'password'
});
  redis.on('ready', () => {
   'NOT EMITTED"

  });

  redis.on('close', () => {
  });

  redis.on('error',  err => {
   'NO ERRORS RAISED"
  });
  redis.on('connect', () => {
    'CONNECTED'
  });

```
The connect event is being raised (Right we can connect to the sentinels)
The Ready event is never being raised (Right  the sentinels cannot communicate / agree / authenticate to the master )

However no error event being raised....  Hence we don't know from a client side perspective what it is wrong even though the connection to sentinels is established

Sending set redis commands also results in no errors being raised and (nothing actually gets set in the cache)

Does this mean that we always have to wait for the ready event before actually trying to send a command when connected to sentinels?

sorry if its configuration is not properly detailed I will try to do so soon.

Does this make sense to you?

**Comment by claudio-viola** [comment]
Actually there is also another issue.
It seems the event ready is not being raised even with what i believe is a valid configuration....
Do you know why this could happen or Is it a bug?
Perhaps network level issues? Sentinels unable to communicate correctly ? 
Why is there no error being raised?

**Comment by luin** [comment]
Could you please enable debug mode (`DEBUG=ioredis:* node yourapp.js`) and put the logs here?

**Comment by claudio-viola** [comment]
Hi There ,
so yes I have been doing investigations and I would say there are a few things that may need to be fixed or improved on:
1) No errors being thrown when failing to authenticate in sentinels mode
2) No errors being thrown when sentinels are not working correctly? Is quorum reached? Are they agreeing on a master
3) If the connection is not ready (in this case due to authentication that did not work and ready event not  not set to true) any get operation should probably better fail immediately instead of being added to a queue?
How does the client now if there is a problem otherwise? Things keep getting added in the queue..

  ioredis:redis status[localhost:6379]: [empty] -> connecting +0ms
  ioredis:redis status[localhost:26379]: [empty] -> connecting +5ms
  ioredis:redis queue command[0] -> sentinel(get-master-addr-by-name,master) +2ms
  ioredis:redis status[localhost:26379]: connecting -> connect +671ms
  ioredis:redis status[localhost:26379]: connect -> ready +1ms
  ioredis:connection send 1 commands in offline queue +0ms
  ioredis:redis write command[0] -> sentinel(get-master-addr-by-name,master) +0ms
  ioredis:redis status[localhost:26379]: ready -> close +354ms
  ioredis:connection skip reconnecting since the connection is manually closed. +0ms
  ioredis:redis status[localhost:26379]: close -> end +0ms
  ioredis:redis status[localhost:6379]: connecting -> connect +0ms
  ioredis:redis write command[1] -> auth(WRONG_PASSWORD) +1ms
  ioredis:redis write command[1] -> info() +0ms
  redis.on('connect') [ 
    connect event emitted 
]
<---- No error thrown failed to authenticate?

  ioredis:redis queue command[1] -> get(SOMEKEY) +14m  <---- Should fail immediately?
  ioredis:redis queue command[1] -> get(SOMEKEY2) +1ms   <---- Should fail immediately?

**Comment by claudio-viola** [comment]
Forgot to mention version 1.15.0

**Comment by luin** [comment]
Hi, sorry for the late response.

1. auth error will be emitted as `"authError"` event instead of `"error"` event.
2. It's hard to tell if a sentinel works correctly on the client side.
3. You may change the password or just disconnect from the Redis server in the `"authError"` event.

**Comment by claudio-viola** [comment]
1) Ok strangely when your password is not valid and you are not connecting to sentinels the error is emitted with the "error" event as well.. thaths why it was hard to spot.. I will check if I can see it in the authErrro.
2) Ok but thats something that you could possibly achieve through sentinel commands cant you?
3) Not really sure about point 3.. when would you disconnect and how do you know that you have to disconnect if there is a error emitted elsewhere and you are trying to do a get? 
in this case the error is an authError however connection is OK hence ioredis just queues the commands and never tell you that you will never be able to get/set since the authentication failed?

**Comment by luin** [comment]
1. I just checked the code, and it would be strange if the wrong password error is emitted with `error` event. Related code: https://github.com/luin/ioredis/blob/4e4f5e2628c63c68556c12b8f7d4e91008407de4/lib/redis/event_handler.js#L17

2. It's possible by connecting to the sentinel servers directly and subscribing related events: http://redis.io/topics/sentinel#pubsub-messages.

3. You may disconnect in the handler of the `authError` event. Here's an example:

```javascript
var redis = new Redis({ password: 'wrongpassword' });

redis.on('authError', function () {
  // Set to the correct password
  redis.options.password = 'test';

  // and reconnect
  redis.disconnect(true);
});

redis.get('foo', console.log); // Will be rejected with auth error

setTimeout(function () {
  redis.get('foo', console.log);
}, 1000);
```


> in this case the error is an authError however connection is OK hence ioredis just queues the commands and never tell you that you will never be able to get/set since the authentication failed?

I agree with you that it's a little strange, may be we should just reject all commands if the password is wrong.

**Comment by claudio-viola** [comment]
thanks for the explanation!
3) I was  also actually  listening for the AuthError event but wasn't really doing anything there as I thought that failure to authenticate would not require any action aside from logging the error

Don't you think ioredis should emit both authError and error,  or otherwise only error events?
What was the reason to decide to have to separate events for authentication errors and errors?
```
onAuthError() {
emit('authError')
emit('error)
}
vs
onAuthError() { 
  emit('error',errorCode,errorMessage) 
}
```
2) I haven't tried but I wonder what happens when one or more of the sentinel go down and the quorum is not reached on who is the master. Would ioredis handle this or raise an event?

**Comment by claudio-viola** [comment]
Oh Sorry I just saw you made a PR about emitting both errors under error :) Forget previous comment!

**Comment by luin** [comment]
The latest pre-release version v2.0.0-rc4 will emit error of wrong password with "error" event. All commands will be rejected with the same error and a reconnection will be made.

**Comment by luin** [comment]
I'm closing this issue since ioredis v2 is released. Feel free to reopen it if you think problem still exists.
