### ISSUE TITLE
module for acquiring locks

### ISSUE THREAD

**Issue by AVVS** [luin/ioredis#29]
I've forked https://github.com/danielstjules/redislock into https://github.com/AVVS/redislock and rewritten the core a bit to use ioredis inside. So if anyone needs it, you are welcome

**Comment by ndgibson** [comment]
https://github.com/thedeveloper/warlock seems to work on ioredis as well. Just pass it an ioredis client.

**Comment by AVVS** [comment]
It uses node-redis-scripty for lua management, which is an extra module and imo is not needed, since ioredis incorporates these features already

**Comment by ScheerMT** [comment]
Maybe including a list of working redis modules like this should be added to the documentation to gain exposure to these?

**Comment by luin** [comment]
@ScheerMT I second that idea. If someone writes a package that works with ioredis, just post it to this issue. I'd like to add these packages to the readme (or wiki) sometime.

**Comment by behrad** [comment]
+1 for https://github.com/AVVS/redislock

**Comment by thelinuxlich** [comment]
Bee-queue on ioredis would be awesome https://github.com/LewisJEllis/bee-queue

**Comment by thelinuxlich** [comment]
I wrote a PR but there are some small things I'm unable to work around:

https://github.com/LewisJEllis/bee-queue/pull/21

**Comment by manast** [comment]
Bull uses many of ioredis features: https://github.com/OptimalBits/bull
