### ISSUE TITLE
Feature Request: GET command stream

### ISSUE THREAD

**Issue by tutman96** [luin/ioredis#296]
I think that it would be useful if we could use node.js streams to get the data from a redis key. That would allow for piping into other native streams and could reduce the memory overhead of large pulls. Just like the `*Buffer`, there could be something like a `*Stream` that would return a readable streamable object. I think the only commands this would be useful for would be the "GET" and "HGET". There could also be an implementation of a writable stream for commands like "SET" and "HSET". I don't know how feasible this would be, but I appreciate the time you have put into this module and how fantastic it works already!

**Comment by luin** [comment]
I considered this feature when I wrote the first version of ioredis. I have to say it's not easy to implement a streaming parser for Redis protocol. Given that Redis is a in-memory database, typically it won't hold large data per key, so I won't consider it as a high priority feature.

**Comment by tutman96** [comment]
Very well, thanks for the explanation.

**Comment by ancms2600** [comment]
Additional explanation for posterity: Redis executes as if single-threaded, so a streaming GET command would block all other queries until the received value stream was closed. It forces the client to receive the full value as fast as possible to avoid blocking other requests.
