### ISSUE TITLE
[question] dropBufferSupport & JSON.parse

### ISSUE THREAD

**Issue by AVVS** [luin/ioredis#298]
JSON.parse is highly optimized in V8 and works on a buffer. Lets assume we have hiredis parser, were there any measurements on `hiredis -> buffer -> js code -> JSON.parse` vs `hiredis -> utf-8 -> js code -> JSON.parse` performance?

Lets look at the following snippet:

```js
const data = new Buffer('{"very":"good","json":true}', 'utf-8');

const sampleOne = JSON.parse(data);
const sampleTwo = JSON.parse(data.toString());
```

Doing sampleOne is always faster because we avoid parsing buffer into utf-8 and pass it directly to JSON.parse. Wouldn't it be the same for hiredis?

**Comment by shaharmor** [comment]
Anyone ever tested this thoroughly?

**Comment by AVVS** [comment]
@trevnorris could you give some input here? I remember your optimization talk during one of the the first nodeconfeu

**Comment by trevnorris** [comment]
Have any benchmarks been done with this? There is no API that allows passing a `char*` (though I wish there was). The call to `JSON.parse()` would automatically call `.toString()` on the Buffer. Example of what's happening:
```js
 var b = { toString: () => '{"foo":"bar"}' };
JSON.parse(b);
// output: { foo: 'bar' }
```
So I'm honestly unsure how one could be faster than the other.

**Comment by AVVS** [comment]
I must be confusing this with 1-byte strings and trick to decode it to binary representation before json.parse and then creating a buffer before we put to to db. Likely doesnt apply here because of inapplicable assumptions

Thanks!

**Comment by trevnorris** [comment]
@AVVS 
> I must be confusing this with 1-byte strings and trick to decode it to binary representation before json.parse and then creating a buffer before we put to to db.

Never thought about using it that way. If you could tell your source for the data to encode in one-byte (i.e. latin1 or iso-8859-1, _not_ win-1252) then converting to JS string from Buffer would be faster.
