### ISSUE TITLE
sentinel mode failover by hand, how can ioredis know

### ISSUE THREAD

**Issue by hzxuzhonghu** [luin/ioredis#305]
If i use sentinel mode, and connected with host1 (master node), and then I exec a failover cmd on a sentinel node.  In this condition, my client will get a READONLY ERROR when i still write host1.
Should I check this error in another way or does ioredis support?

**Comment by luin** [comment]
ioredis should be able to handle the failover so you don't have to. When a failover happens, Redis will disconnect all the client that connected to the old master and the new master, so ioredis will ask the sentinel servers again for the new master node. Didn't it work for you?

Get Outlook for iOS




On Fri, May 13, 2016 at 11:22 PM -0700, "hzxuzhonghu" <notifications@github.com> wrote:












If i use sentinel mode, and connected with host1 (master node), and then I exec a failover cmd on a sentinel node.  In this condition, my client will get a READONLY ERROR when i still write host1.

Should I check this error in another way or does ioredis support?

**Comment by hzxuzhonghu** [comment]
I know what you mean. But what I said is faillover by hand, connection between client and redis master is alive and how client know?

**Comment by luin** [comment]
No matter what causing the failover, Redis always disconnects all clients so that clients are able to know whether a failover happens. Refer to http://redis.io/topics/sentinel-clients#sentinel-failover-disconnection for details.

**Comment by hzxuzhonghu** [comment]
Ok， get  it. Thanks !

**Comment by tangxinfa** [comment]
Becarefull, according to http://redis.io/topics/sentinel-clients#sentinel-failover-disconnection, Sentinel failover disconnection require at least Redis 2.8.12(ioredis already point out in the documention), if you use low redis versions(like me 2.8.7), application will broken after redis failover.

I already use "reconnectOnError" options to force reconnect if READONLY, and ask op to upgrade redis.
