### ISSUE TITLE
Is having no keys for a Lua script supported?

### ISSUE THREAD

**Issue by WaldoHatesYou** [luin/ioredis#31]
Hi, I just wanted to check if this issue is an actual problem with the code. So, I define the command below.
```javascript
redis.defineCommand('randomKeyValues',{
	numberOfKeys:0,
	lua:"return ARGV[1]"
});
```
Then, I set up the following call.
```javascript
redis.randomKeyValues("25",function(err,result) {
		if(err){
			console.log(err);
		}else{
			console.log(result);
			res.send(JSON.stringify(result));
		}
	});
```
Upon execution, I receive the following error message.
```javascript
{ [ReplyError: ERR Number of keys can't be greater than number of args]
  name: 'ReplyError',
  message: 'ERR Number of keys can\'t be greater than number of args',
  command: 
   { name: 'evalsha',
     args: [ '8d962c3bde43d4d0c42bde6c2148c3c626a4541d', '25' ] } }
```
I worked around this issue by defining the command to have a single key and then ignoring the key in my Lua script but I would like to know if I made some kind of mistake.

**Comment by luin** [comment]
Hi @WaldoHatesYou, It's a bug introduced recently.

Fixed in 1.2.3. Thank you for pointing this out.
