### ISSUE TITLE
How do I use the exists command?

### ISSUE THREAD

**Issue by snig-b** [luin/ioredis#310]
REDIS provides the EXISTS command that returns a boolean. 
ioredis' exists() command returns a method. I have tried using a callback also to no avail. 
I can see in the commands page that ofcourse this command is supported but how to use this?

**Comment by luin** [comment]
Just check out the example: https://github.com/luin/ioredis/blob/master/examples/basic_operations.js

**Comment by enst** [comment]
The example doesn't mention the Redis command "EXISTS".

**Comment by luin** [comment]
@enst There're hundreds of Redis commands available, we just can't mention all of them. However, the usages of them are similar.

**Comment by dansaferide** [comment]
redis.exists('myKey').then( exists => { console.log('Does it exist?', (exists === 1)) }
