### ISSUE TITLE
Disconnecting from Cluster while waiting for all pending commands

### ISSUE THREAD

**Issue by shaharmor** [luin/ioredis#315]
Hi,

Is it possible today to disconnect (or quit) a Redis Cluster while waiting for all pending commands to finish?

I know that i can do `redis.quit()` on a single instance, but what about Cluster?
Should i just do `cluster.nodes()` and run `redis.quit()` on each?

I tried that but the cluster keeps reconnecting. Should it somehow detect that we called `.quit()` and not try to reconnect?

**Comment by luin** [comment]
Hmm...Currently `Cluster#disconnect()` will disconnect all nodes, but it won't wait for all pending commands.

I've not tried but setting `this.manuallyClosing` to `true` and calling `this.setStatus('disconnecting')` before invoking `redis.quit()` for each `cluster.nodes()` should be about to prevent nodes from reconnecting.

Seems we can add a `Cluster#quit()` method to do this for users.

**Comment by shaharmor** [comment]
That would be awesome 👍

**Comment by shaharmor** [comment]
hey @luin, any chance to get this implemented?

**Comment by luin** [comment]
A little busy these two weeks. I'll revisit this issue this weekend. 🚴
