### ISSUE TITLE
Unable to subscribe to channels using wildcards?

### ISSUE THREAD

**Issue by carterfort** [luin/ioredis#316]
I'm attempting to subscribe to a channel with a wildcard name, and it seems to treat the `*` as just another character. Is there a way to do this?

```
redis.subscribe('sqc-client-channel*'); //responds only to messages posted to `sqc-client-channel*'`
```

Thanks for this library. It's incredibly useful.

**Comment by BridgeAR** [comment]
You're looking for [psubscribe](https://redis.io/commands/psubscribe). Be aware that you also have to listen to pmessage / pmessageBuffer in that case.

**Comment by carterfort** [comment]
That's perfect, thank you.
