### ISSUE TITLE
Auto pipelining?

### ISSUE THREAD

**Issue by an-sh** [luin/ioredis#317]
Is it possible to use pipelinng internally to send command queues
larger than some limit to redis (or a cluster node)? So it can give the
same performance boost without manual code optimizing (as in node.js
async event model the command queue seems the only right place to do
it anyway). As far as i understand, currently all node redis clients
are just single connects and are very dependent on node to redis ping
time, e.g. even a 1ms rtt will bound performance just to 1000 ops/sec
(instead of 10K-100K). And if node application is scaled on some
overseas server with 100ms rtt, that will be just only 10 ops/sec (am i missing smth?)

P.S. It may be a good alternative to using redis connection pools (or
a part of a mixed strategy).

**Comment by luin** [comment]
Why don't just use the pipeline given it pretty easy to use:

```javascript
redis.pipeline().set('foo', 'bar').get('foo').exec();
```

Auto pipelining is a little tricky IMO.

**Comment by an-sh** [comment]
The first reason, there is no way to run application logic inside
it. So there is always tradeoff to consider about getting data ahead
of time and a redis server load (and changing more code if something
new is added).

But the main reason, there is no way an easy to use pipeline across
event handlers. So, for example, we have:

```javascript
function handler(eventData) {
  redis.pipeline().SOMECOMMANDS.exec().then(results => {
    runAppLogic(eventData, results);
  });
}
```

Just one pipeline per event (http request, websocket message, etc). If
there is no many events - it is ok. But if there is just:

```javascript
function handler(eventData) {
  redis.get('key').then(results => {
    runAppLogic(eventData, results);
  });
}
```

And lots of events? There is no transparent way to use a pipeline in
that case, beside reimplementing a command queue inside an
application.

Auto pipelining will eliminate the need to consider low level things
inside an application logic, and moreover will give an optimal result
in any case. Like pooling in pg/mysql node clients, you can just
enable it, and get a much better performance, without any need of low
level connection stuff management/optimisations.

Auto pipelining addressing exactly the same issue as connection
pooling(in redis case), but with a different approach. I'm not sure
which one is the best. There is an open issue about Connection
Pooling, so probably these two should be merge somehow.

**Comment by gbaquedano** [comment]
I was about to write a similar thread. In my scenario I have plenty of objects that get randomly updated and each one of them raises an event with the new data. I dont find an easy way to use pipeline in this scenario. I was even thinking to push all the updates to a buffer and then pipeline it all together for every fixed interval of time, but I thought someone had already faced this with ioredis.

**Comment by AVVS** [comment]
@gbaquedano take a look at https://github.com/twitter/twemproxy, you can use this for scaling, but you would sacrifice a lot of functionality. As for connection pooling, thats a nice feature for sure, but would be somewhat out of scope here

**Comment by DyncKevin** [comment]
Hi, I have an question, for example, I use pipeline like this, 
redis.pipeline().set('foo', 'bar').get('foo').exec();
what happen if cmd 'set' failed? does cmd 'get' continue exec? will the pipeline return or continue?
the 'failed' I mean in the callback, 'err' is not null
