### ISSUE TITLE
[QUESTION | FR] Auto compression/decompression

### ISSUE THREAD

**Issue by oaleynik** [luin/ioredis#319]
Hi there!

Are there any plans to add support of snappy or deflate compression/decompression?

**Comment by luin** [comment]
IMO it would be better to use a tunnel that supports compression/decompression.

**Comment by oaleynik** [comment]
@luin can you please explain what do you mean under "tunnel"?

**Comment by luin** [comment]
[stunnel](https://www.stunnel.org) for example. It doesn't make sense to add compression support to ioredis since Redis doesn't support decompression.

**Comment by oaleynik** [comment]
I think it makes sense (unless we talk about different things). Let me explain what I mean. To save some memory (actually - a lot of memory) prior saving value to redis I usually compress it and encode as base64 string. When I fetch it back I decode and uncompress it. In the case if original value is serialized JSON string (which is very usual) - such transformation allows to transfer and store up to ten times less data.

Would be nice to have support of such transformation. For instance by passing `snappy: true` via options to Redis constructor.

Quick example:
```javascript
function pack (value) {
  return new Promise((resolve, reject) => {
    snappy.compress(JSON.stringify(value), (err, packed) => {
      if (err) {
        return reject(err);
      }

      resolve(packed.toString('base64'));
    });
  });
}

function unpack (value) {
  return new Promise((resolve, reject) => {
    snappy.uncompress(Buffer.from(value, 'base64'), (err, unpacked) => {
      if (err) {
        return reject(err);
      }

      const unpackedString = unpacked.toString();

      resolve(JSON.parse(unpackedString));
    });
  });
}
```

**Comment by luin** [comment]
Aha, I got your point and yes it does make sense. I thought you meant compress the TCP buffer to save the bandwidth.

You can monkey-patch the redis commands you need to implement pack & unpack currently. I think adding the support for async hooks can make things easier and more flexible than just offering compression support.

For example:

```javascript
const redis = new Redis({
  hooks: {
    beforeSend(command, args, done) {
      if (command.name === 'set') {
        compress(args[1], function (err, res) {
          args[1] = res;
          done();
        });
      } else {
        done();
      }
    },
    afterFetch() { /* ... */ }
  }
});

**Comment by oaleynik** [comment]
@luin Yep! Exactly what I'm looking for. I was thinking to somehow use transformers for this purpose, but I didn't figure out how to friend them with promisified API and extract into something reusable. But hooks sounds great! Or maybe some plugins ecosystem when you can do something like `client.use(redisSnappy | redisDeflate | whatever)`.

**Comment by luin** [comment]
Closing this in favour of #347.
