### ISSUE TITLE
Fail if connecting to non-cluster server using Redis.Cluster

### ISSUE THREAD

**Issue by shaharmor** [luin/ioredis#320]
Today its possible to connect to a standalone Redis server with the `Redis.Cluster` class.

I think that in most of the times it will be a developer error and should be errored in some way.

Thoughts?

**Comment by shaharmor** [comment]
@luin What do you think?

**Comment by luin** [comment]
It also possible that people disable the cluster mode temporarily. In this case, ioredis will keep retrying and the connection will be alive again when the cluster mode is enabled. If we just throw an error when connecting to a standalone Redis server, the connection will not be recovered in this case.

**Comment by haozxuan** [comment]
其实我认为该问题可以改为“cluster模式下，是否允许用户只提供一个连接节点”。
当我看到ioredis支持给自己发现剩余节点时，我第一时间想到了mongodb驱动程序，当初他也是允许只提供一个节点，然后自己发现其余节点，but，好景不长，没过多久就出现了单节点的拓扑结构和副本集的拓扑结构不同造成找不到主节点的问题，于是官方取消了只提供一个节点的方式。从整个交替过程来看，虽然只提供一个节点看起来更smart，but，逻辑不够清晰（指，驱动层面要自识别部署架构，可能会造成不必要的开销），所以还是更偏向于cluster就至少提供2个node，如果提供一个node，去连接cluster，还是抛异常的好，避免开发者盲目的相信该连接方式；
