### ISSUE TITLE
question: 2.x buffer to String, string to buffer encoding/decoding mutates content

### ISSUE THREAD

**Issue by AVVS** [luin/ioredis#329]
I'm using [scrypt](https://github.com/barrysteyn/node-scrypt) to encode passwords, it generates passwords like `736372797074000f0000000800000001a551a6340a62c761e1fa98c6fb242f2777a3709b525df8d60036d0be97bbe0a24dd53ca55cebf4a704a8c55cb95f8fb9e5785b28851b55d460f1334544934e174f8bf4e98f61eea1fe9ee18a83e3e56e` - hex representation of `nicepassword1` with the following snippet

``` js
const scryptParams = scrypt.paramsSync(0.1, bytes('32mb'));
return scrypt.kdf(Buffer.from(password), scryptParams);
```

Before v2 I used buffers directly to store and retrieve data, pseudo-code below:

``` js
// save pwd
redis.hset('user-data', 'password', scryptPasswordBuffer);

// verify pwd
redis.hgetBuffer('user-data', 'password')
  .then(hash => scrypt.kdfVerify(hash, 'nicepassword1'))
  .then(result => {
      // truthy means match
   });
```

When switching to v2, and using `Buffer.from(hash, 'utf8')` and `redis.hget` (or just dropBufferSupport: true) I cant get buffer thats encoded in the same way as before. For instance, I can get smth like this:

`736372797074000f0000000800000001637e062881229578016355fbecd82b841bd22143ed25893c839d97f7ad7a9badc031ac5ee76e52341f42eb5e7dc798ff70a1d2ae7cd36c239a7fd66dcc843a76da9b2715a4d664cb3c73e9769e85cb45`

Anyway, long story short, that happens because at decoding time it uses incorrect encoding ('utf8') and that messes everything up. It can be fixed by manually transforming string to hex and saving it that way, or using buffer. 

Also, it doesn't really matter whether I use hiredis or js, it will still call toString('utf8') and mess evereything up.

Now, to sum up, proposed solution to the problem:
1. use https://www.npmjs.com/package/deprecate or similar - otherwise I get everything messed up with tons of deprecation warnings when I use `hiredis` as a parser
2. allow one to specify encoding when transforming data that comes from redis and dropBufferSupport is 'true' - but that could be incredibly tricky with the current API
## 

I might be wrong in my assumptions, if so - please point out how my code can be changed in order to support 2.x properly

**Comment by luin** [comment]
Another workaround is to use a separate `Redis` instance with `dropBufferSupport` to `false` and use the JavaScript parser to deal with the buffer.

Since node-redis-parser 2.x (which will be included in ioredis v3.0) has deprecated the hiredis parser, we can just remove the warning of `dropBufferSupport` option.

**Comment by AVVS** [comment]
as for `dropBufferSupport` warning - could you limit it to only 1 invocation? It's extremely annoying to have that and I don't see an extra connection being an option, since its used with a buffer only once in the 2.5k LOC application

**Comment by luin** [comment]
The warning will only be displayed when creating parsers: https://github.com/luin/ioredis/blob/master/lib/redis/parser.js#L38-L40. Did your connection often reconnect?

**Comment by AVVS** [comment]
@luin that was my bad indeed - I was staring at the tests and it cleans up after every test to make the idempotent, therefore recreating the parser/connection each test. Thanks for clearing that up.
