### ISSUE TITLE
Setup non-localhost ip but Redis.Cluster always connect to localhost

### ISSUE THREAD

**Issue by gohiei** [luin/ioredis#330]
I setup three nodes for my redis cluster, and use new Redis.Cluster.
There are 127.0.0.1 connections in DEBUG mode.
Maybe someone can figure out what it happened...

var redis = new Redis.Cluster([
    'redis://192.168.1.101:30001',
    'redis://192.168.1.101:30002',
    'redis://192.168.1.101:30003'
])

DEBUG=ioredis:* node server.js
  ioredis:cluster status: [empty] -> connecting +0ms
  ioredis:redis status[192.168.1.101:30001]: [empty] -> connecting +3ms
  ioredis:redis status[192.168.1.101:30002]: [empty] -> connecting +3ms
  ioredis:redis status[192.168.1.101:30003]: [empty] -> connecting +0ms
  ioredis:cluster getting slot cache from 192.168.1.101:30002 +1ms
  ioredis:redis queue command[0] -> cluster(slots) +1ms
  ioredis:redis status[192.168.1.101:30001]: connecting -> connect +132ms
  ioredis:redis write command[0] -> info() +1ms
  ioredis:redis status[192.168.1.101:30002]: connecting -> connect +2ms
  ioredis:redis write command[0] -> info() +0ms
  ioredis:redis status[192.168.1.101:30003]: connecting -> connect +0ms
  ioredis:redis write command[0] -> info() +0ms
  ioredis:redis status[192.168.1.101:30001]: connect -> ready +4ms
  ioredis:redis status[192.168.1.101:30002]: connect -> ready +0ms
  ioredis:connection send 1 commands in offline queue +1ms
  ioredis:redis write command[0] -> cluster(slots) +0ms
  ioredis:redis status[192.168.1.101:30003]: connect -> ready +0ms
  ioredis:redis status[127.0.0.1:30001]: [empty] -> connecting +2ms
  ioredis:redis status[127.0.0.1:30003]: [empty] -> connecting +1ms
  ioredis:redis status[127.0.0.1:30002]: [empty] -> connecting +3ms
  ioredis:cluster status: connecting -> connect +2ms
  ioredis:cluster status: connect -> ready +0ms
  ioredis:redis status[127.0.0.1:30001]: connecting -> connect +1ms
  ioredis:redis write command[0] -> info() +0ms
  ioredis:redis status[127.0.0.1:30003]: connecting -> connect +0ms
  ioredis:redis write command[0] -> info() +0ms
  ioredis:redis status[127.0.0.1:30002]: connecting -> connect +1ms
  ioredis:redis write command[0] -> info() +0ms
  ioredis:redis status[127.0.0.1:30001]: connect -> ready +1ms
  ioredis:redis status[127.0.0.1:30003]: connect -> ready +0ms
  ioredis:redis status[192.168.1.101:30003]: ready -> close +0ms
  ioredis:connection skip reconnecting since the connection is manually closed. +0ms
  ioredis:redis status[192.168.1.101:30003]: close -> end +1ms
  ioredis:redis status[192.168.1.101:30002]: ready -> close +0ms
  ioredis:connection skip reconnecting since the connection is manually closed. +0ms
  ioredis:redis status[192.168.1.101:30002]: close -> end +0ms
  ioredis:redis status[192.168.1.101:30001]: ready -> close +0ms
  ioredis:connection skip reconnecting since the connection is manually closed. +0ms
  ioredis:redis status[192.168.1.101:30001]: close -> end +0ms
  ioredis:redis status[127.0.0.1:30002]: connect -> ready +1ms
^C  ioredis:redis write command[0] -> quit() +3s

**Comment by luin** [comment]
Did you bind your cluster to the right interface?

**Comment by gohiei** [comment]
There are some problem in my cluster configuration.
The connections between nodes depends on 127.0.0.1.

After I fixed to 192.168.1.101, the problem is solved.

Before
---------------------------
f2b443faf4e2624fa54fd6ca2a79b378b7ce9593 127.0.0.1:30004 slave 8fb9494ecd03e21a7d95e815ff427f2e3de2e14c 0 1465829431475 4 connected
ee3275cbf1c7947392f69a31526fb153fae31a29 127.0.0.1:30002 master - 0 1465829431677 2 connected 5461-10922
d01224ff1ae0ee1affc71d2b89ebb00b31257951 127.0.0.1:30006 slave 1e7d13ff56299ff871913e6e2e1e4c0287b220dd 0 1465829431375 6 connected
8fb9494ecd03e21a7d95e815ff427f2e3de2e14c 127.0.0.1:30001 myself,master - 0 0 1 connected 0-5460
927c7951e5892390df848bafc0a550df35f15280 127.0.0.1:30005 slave ee3275cbf1c7947392f69a31526fb153fae31a29 0 1465829431677 5 connected
1e7d13ff56299ff871913e6e2e1e4c0287b220dd 127.0.0.1:30003 master - 0 1465829431375 3 connected 10923-16383

After
--------------------
f283f6dba4bfdbeefe7db33e8bd71546491531d6 192.168.1.101:30003 master - 0 1465829358324 3 connected 10923-16383
412dd386085bed79ab0e33b76e82a4a31391e793 192.168.1.101:30004 slave b4c8f465245db8b204bd6c8e0f427c9810950692 0 1465829358324 4 connected
b4c8f465245db8b204bd6c8e0f427c9810950692 192.168.1.101:30001 myself,master - 0 0 1 connected 0-5460
17781a506cfae8bd4db929f893905ca42118e720 192.168.1.101:30002 master - 0 1465829358324 2 connected 5461-10922
92a8f8925ba4fec80f17ea00603760c4a1af383b 192.168.1.101:30005 slave 17781a506cfae8bd4db929f893905ca42118e720 0 1465829358324 5 connected
7378315b05b38388e293cff14588ba48b4cfc8dc 192.168.1.101:30006 slave f283f6dba4bfdbeefe7db33e8bd71546491531d6 0 1465829358324 6 connected
