### ISSUE TITLE
IOREDIS Pool. is it missing???

### ISSUE THREAD

**Issue by panbhatt** [luin/ioredis#331]
Is there is a way in IOREDIS to specify the pool settings, so that automatically it takes care whether we are working in a cluster, or in a sentinel. 
I found another library ioredis-pool, that doesn't look impressive. Any suggestion will help.

**Comment by olglay** [comment]
We are using generic-pool

**Comment by luin** [comment]
A generic pool like https://github.com/coopernurse/node-pool should be enough.
