### ISSUE TITLE
redis cluster如何使用keys命令

### ISSUE THREAD

**Issue by huangyingjie** [luin/ioredis#334]
api虽然有keys函数，但一执行就报错：
````js
ERR! ReplyError: ERR unknown command 'keys'
````
其它命令正常，如: set、get、hget、hset等

**Comment by huangyingjie** [comment]
登录redis 客户端手动执行也不支持，应该是redis本身就不支持，有变通的办法吗

**Comment by luin** [comment]
如果是这样那就没有变通方法了。不过 Redis Cluster 自身是支持 keys 命令的，应该是代理或者修改版的问题。

Get Outlook for iOS




On Thu, Jun 16, 2016 at 8:48 PM +0800, "huangyingjie" <notifications@github.com> wrote:












登录redis 客户端手动执行也不支持，应该是redis本身就不支持，有变通的办法吗

**Comment by stranger520** [comment]
基于jedis 2.9.0 
可以用scan 方法，但这个方法也是坑。看了他的源码 ，简直了，判断pattern 是否是 {} 包裹的，如果是，就说明这个 pattern 传的正确，但是 取值的时候，竟然 没有 把{} 去掉。比如 我redis 里有 test_1,test_2,test_3 这三个key，用的时候他让你这样 穿 正则 {test_*} ,要用 {}包裹。but ,严重的but 就是 ，他取值的时候，竟然没有 把 {} 去掉， 直接用{test_*} 取值，这能取到值啊？！ 我debug的时候，把 {}去掉就可以了。哎，无力说作者的意图了。哎，我想降低版本！！

**Comment by luin** [comment]
@stranger520 发错地方了，这个是 ioredis 的 repo
