### ISSUE TITLE
Cannot get slave nodes with cluster.nodes() function.

### ISSUE THREAD

**Issue by SacDin** [luin/ioredis#336]
I have setup of 3 master and 3 replicaset all bind to private IP. To connect to cluster i am using below code:
```
var cluster = new Redis.Cluster([{ port: 6381, host: '192.168.1.10'},
                                          { port: 6382, host: '192.168.1.10'},
                                          { port: 6383, host: '192.168.1.10'}]);
```

The issue is basically any two of the master fails slave takes over and all load goes to the remaining master. 
I tried to check with cluster.nodes() function to get all nodes details but all I get is given instances of Redis.Cluster([nodes object]) as all master and cluster.nodes('slave') gives blank array.

Is Redis.cluster not detecting master nodes automatically or am I missing something?

Thanks.

**Comment by luin** [comment]
Could you enable the debug mode and post the logs here? `DEBUG=ioredis:* node yourapp.js`

**Comment by SacDin** [comment]
`root@local:/home/local/app# DEBUG=ioredis:* node app.js
  ioredis:cluster status: [empty] -> connecting +0ms
  ioredis:redis status[192.168.1.6:6381]: [empty] -> wait +4ms
  ioredis:redis status[192.168.1.6:6382]: [empty] -> wait +2ms
  ioredis:redis status[192.168.1.6:6383]: [empty] -> wait +0ms
  ioredis:cluster getting slot cache from 192.168.1.6:6382 +1ms
  ioredis:redis status[192.168.1.6:6382]: wait -> connecting +1ms
  ioredis:redis queue command[0] -> cluster(slots) +1ms
  ioredis:redis status[192.168.1.6:6383]: wait -> connecting +0ms
  ioredis:redis status[192.168.1.6:6382]: connecting -> connect +6ms
  ioredis:redis write command[0] -> info() +1ms
  ioredis:redis status[192.168.1.6:6383]: connecting -> connect +1ms
  ioredis:redis write command[0] -> info() +0ms
  ioredis:redis status[192.168.1.6:6382]: connect -> ready +3ms
  ioredis:connection send 1 commands in offline queue +0ms
  ioredis:redis write command[0] -> cluster(slots) +1ms
  ioredis:redis status[192.168.1.6:6383]: connect -> ready +0ms
  ioredis:redis status[192.168.1.6:6384]: [empty] -> wait +1ms
  ioredis:redis status[192.168.1.6:6386]: [empty] -> wait +1ms
  ioredis:redis status[192.168.1.6:6385]: [empty] -> wait +0ms
  ioredis:cluster status: connecting -> connect +0ms
  ioredis:redis status[192.168.1.6:6381]: wait -> connecting +1ms
  ioredis:redis queue command[0] -> cluster(info) +0ms
  ioredis:redis status[192.168.1.6:6381]: connecting -> connect +0ms
  ioredis:redis write command[0] -> info() +0ms
  ioredis:redis status[192.168.1.6:6381]: connect -> ready +1ms
  ioredis:connection send 1 commands in offline queue +0ms
  ioredis:redis write command[0] -> cluster(info) +0ms
  ioredis:cluster status: connect -> ready +0ms`

**Comment by luin** [comment]
I got the correct results with my setup:

My code:
```javascript
'use strict';

var Cluster = require('ioredis').Cluster;

var cluster = new Cluster([
  { host: '127.0.0.1', port: '7000' },
  { host: '127.0.0.1', port: '7001' },
  { host: '127.0.0.1', port: '7002' }
]);

cluster.on('ready', function () {
  console.log(cluster.nodes().length);
  console.log(cluster.nodes('slave').length);
});

```

The logs:

```shell
ioredis git:master ❯ DEBUG=ioredis:* node test
  ioredis:cluster status: [empty] -> connecting +0ms
  ioredis:redis status[127.0.0.1:7000]: [empty] -> wait +3ms
  ioredis:redis status[127.0.0.1:7001]: [empty] -> wait +2ms
  ioredis:redis status[127.0.0.1:7002]: [empty] -> wait +0ms
  ioredis:cluster getting slot cache from 127.0.0.1:7000 +1ms
  ioredis:redis status[127.0.0.1:7000]: wait -> connecting +2ms
  ioredis:redis queue command[0] -> cluster(slots) +0ms
  ioredis:redis status[127.0.0.1:7002]: wait -> connecting +1ms
  ioredis:redis status[127.0.0.1:7000]: connecting -> connect +5ms
  ioredis:redis write command[0] -> info() +1ms
  ioredis:redis status[127.0.0.1:7002]: connecting -> connect +1ms
  ioredis:redis write command[0] -> info() +1ms
  ioredis:redis status[127.0.0.1:7000]: connect -> ready +3ms
  ioredis:connection send 1 commands in offline queue +0ms
  ioredis:redis write command[0] -> cluster(slots) +0ms
  ioredis:redis status[127.0.0.1:7002]: connect -> ready +0ms
  ioredis:redis status[127.0.0.1:7003]: [empty] -> wait +3ms
  ioredis:redis status[127.0.0.1:7005]: [empty] -> wait +0ms
  ioredis:redis status[127.0.0.1:7004]: [empty] -> wait +0ms
  ioredis:cluster status: connecting -> connect +0ms
  ioredis:redis write command[0] -> cluster(info) +1ms
  ioredis:cluster status: connect -> ready +1ms
6
3
```

And the redis cluster setup: https://github.com/Grokzen/docker-redis-cluster/blob/master/Dockerfile

**Comment by luin** [comment]
Closing this issue. Feel free to reopen it with more information if the problem still exists.
