### ISSUE TITLE
Setting an expire (TTL) with an undefined value cause instant deletion of the element

### ISSUE THREAD

**Issue by etiennechabert** [luin/ioredis#338]
"ioredis": "^2.0.1"

Today I experienced a difficult bug to solve, I changed few config files in my project, some of them are defining the TTL value of my HASH, SET, LIST for Redis.

I messed up with one file, for this reason the TTL value of one of my collections was undefined, and I was not able to found this collection anymore in my Redis. I finally debugged it by running my project step by step, this is what I discovered :

`
var ttl_value = undefined;
redisClient.expire(key, ttl_value) `

The result is an instant deletion of the redisElement corresponding to ‘key', without any error, warning or whatever.

Apparently undefined is considered as 0, which is probably unwanted and dangerous for most of the users.

Best regards,

**Comment by luin** [comment]
Good catch! Actually ioredis sends `undefined` to the Redis server directly without converting it to a `0`. However Redis considers empty values as zero: https://github.com/antirez/redis/blob/226f679651ca62394021738af0ce467a290c7b90/src/object.c#L639-L641.

**Comment by etiennechabert** [comment]
@luin thank's for the explanation, it's making sense now. But I am still convinced this behavior is bad (not only because I wasted 3h of my day debugging my server on this case). Btw, IORedis is probably not supposed to avoid this case himself by changing the value of the user. I probably should create the same ticket in the official Redis repository.

**Comment by luin** [comment]
Yes, it seems not good as a default behaviour to handle with `undefined` value. I think this issue should be resolved by Redis itself (e.g. returning an error when the parameter of `expire` is not a integer) instead of ioredis.

**Comment by etiennechabert** [comment]
@luin I am going to follow the evolution of this request on the official Redis repo. Btw, thank's for your quick answers.
