### ISSUE TITLE
Cluster pubsub optimizations

### ISSUE THREAD

**Issue by shaharmor** [luin/ioredis#340]
As it works today, Redis Cluster is configured to publish every message it receives to each and every node in the cluster.
The specific line that does that is this one: https://github.com/antirez/redis/blob/unstable/src/pubsub.c#L320
Following this thread: https://github.com/antirez/redis/issues/2672 and my suggestion here: https://github.com/antirez/redis/issues/3346, i recommend changing `ioredis` `Redis.Cluster` logic to send pubsub requests to the appropriate node according to the cluster-slots map (Or at least add a config option to make it like this).
That way, it will be possible to have large scale Redis Cluster pubsub.

I understand that it will mean that instead of having just 1 subscriber connection, we will need to have 1 for each node in the cluster.

P.S.
Its also possible to just rebuild redis with this line commented to get the same affect as my suggestion.

@luin what do you think?

**Comment by luin** [comment]
As far as I understand, even we just send messages to a specified ndoe, Redis will eventually send them to all other nodes of the cluster. I don't think there's anything we can do on the client side to solve the problem.

**Comment by shaharmor** [comment]
Yea i know that, thats exactly why i opened this: https://github.com/antirez/redis/issues/3346
In addition, its possible to build a custom version of `redis` and comment out this line: https://github.com/antirez/redis/blob/unstable/src/pubsub.c#L320 and that will stop propagation.

**Comment by shaharmor** [comment]
Following the issue i linked above, I have created a PR on https://github.com/antirez/redis/pull/3381 that enables a user to disable cluster pubsub propagation.

I honestly don't think it will be merged because the owner of redis have different ideas for pubsub, but it still shows how it can be done.

My question remains: do you think its possible to change ioredis pubsub handling to subscribe/publish to a node based on the slots map?
I understand that:
1. it will only be effective for users that really disable cluster pubsub propagation
2. it will require 2x more redis connections, because each node will require both a subscriber and a normal client. (Unlike today that there is just 1 subscriber)

I just want to see if its feasible, if its something that more users other than me require, and how long you think it'll be to change.

**Comment by luin** [comment]
Actually I also think the current way of handling cluster pubsub is not effective, and your proposal looks good to me. However, given that sending messages to specified nodes based on the slots map is not a standard that Redis has implemented, I'm hesitating to introduce this to ioredis.

Since it's not hard to implement on the client side, what do you think about creating a wrapper for that on top of ioredis?

**Comment by shaharmor** [comment]
I'll see if i can find some spare time for this

**Comment by andreimavenhut** [comment]
*bump* anyone had the time to implement this?
