### ISSUE TITLE
.quit() on cluster sometimes causes exceptions

### ISSUE THREAD

**Issue by AVVS** [luin/ioredis#344]
When calling `cluster.quit()`

```
     Error: Connection is closed.
      at close (node_modules/ioredis/lib/redis/event_handler.js:100:21)
      at Socket.<anonymous> (node_modules/ioredis/lib/redis/event_handler.js:80:14)
      at TCP._handle.close [as _onclose] (net.js:492:12)
```

**Comment by luin** [comment]
Could you reproduce the error?

**Comment by AVVS** [comment]
yeah, doesn't happen all the time, but frequently enough to post it here. Thought it was a bug in my code, but that didn't happen in 1.x versions, first I noticed it in 2.2, but then rolled back to 2.1 and it was also happening there.

**Comment by luin** [comment]
Is the error returned by the `quit()` method? The behaviours of `Cluster#quit()` between 2.1 and 2.2 are different that 2.1 sends `QUIT` to a random node while 2.2 sends `QUIT` to every node.

Is it possible to provide a minimal reproducible example for this issue?

**Comment by AVVS** [comment]
https://github.com/makeomatic/mservice/blob/master/src/plugins/redisCluster.js#L21-L82

you can see `catchReturn` - this is how I mitigate the issue for now.

**Comment by shaharmor** [comment]
I have encountered it as well, i think it happens when calling `cluster.quit()` multiple times

**Comment by luin** [comment]
Calling `quit()` when some nodes are not connected may cause this error, haven't dug into the problem though.
