### ISSUE TITLE
flexbuffer missing license

### ISSUE THREAD

**Issue by pavanratnakar** [luin/ioredis#349]
Hi,

One of the dependent module flexbuffer has missing license.  In corporate environment, we are unable to use ioredis due to missing license in dependent module. Is there any work around?

**Comment by luin** [comment]
My apologies for not reviewing the license before using it. I've sent an email to the contributors of the flexbuffer module.

I'll replace the flexbuffer module if there's no response.

**Comment by Salakar** [comment]
I tweeted both the contributors, should hopefully get their attention 👍 

![image](https://cloud.githubusercontent.com/assets/5347038/16835619/711c4eb4-49b1-11e6-845a-fbb89d829544.png)

**Comment by Salakar** [comment]
License has been added, MIT.

**Comment by pavanratnakar** [comment]
Thank you very much. Thank was really quick.
