### ISSUE TITLE
repeated code in the lib/commander, not recommended arguments use

### ISSUE THREAD

**Issue by AVVS** [luin/ioredis#35]
There are code parts like this https://github.com/luin/ioredis/blob/master/lib/commander.js#L43-L53

```js
      var args = _.toArray(arguments);
      var callback;

      if (typeof args[args.length - 1] === 'function') {
        callback = args.pop();
      }

      var options = { replyEncoding: 'utf8' };
      if (this.options.showFriendlyErrorStack) {
        options.errorStack = new Error().stack;
      }
```

Part about the arguments: https://github.com/petkaantonov/bluebird/wiki/Optimization-killers#32-leaking-arguments

I understand that there is lots of boilerplate code, but it is supposed to speed up the module quite a bit

```js
smth: function() {
   var length = arguments.length;
   var lastArgIndex = length - 1;
   var callback = arguments[lastArgIndex];
   if (typeof callback !== 'function') {
      callback = undefined;
   } else {
      length = lastArgIndex;
   }
   var args = new Array(length);
   for (var i = 0; i < length; i++) {
      args[i] = arguments[i];
   }

   // .... options part

   var command = new Command(commandName, args, options, callback);
   return this.sendCommand(command);
}
```

**Comment by luin** [comment]
Released in 1.3.1. These changes improves the performance [a lot](https://github.com/luin/ioredis/commit/20df742f7e5df53e5a4f8f7e2793d14702c97f4b?short_path=04c6e90#diff-04c6e90faac2675aa89e2176d2eec7d8). Thank you for pointing this out :-).
