### ISSUE TITLE
Add config option to not connect in the constructor

### ISSUE THREAD

**Issue by shaharmor** [luin/ioredis#350]
Hi,

Can we add a config option to the constructor so that it will **not** try to connect until manually calling `.connect()`?

**Comment by luin** [comment]
Seems `lazyConnect` option should do the trick.

**Comment by shaharmor** [comment]
Does it work in Cluster mode as well? I want to do something like this:
```js
var redis = new Redis.Cluster();

// then sometime later
redis.connect().then(() => ...)
```

**Comment by luin** [comment]
hmm...It doesn't work in cluster mode. What's your use case?

**Comment by shaharmor** [comment]
I just want to have the redis instance created in the constructor of my own class, and then make sure it connects before using it.

We can just wrap this line: https://github.com/luin/ioredis/blob/master/lib/cluster/index.js#L83
in an `if` statement with `lazyConnect` no?

**Comment by luin** [comment]
Yeah, should be pretty similar to the standalone version: https://github.com/luin/ioredis/blob/master/lib/redis.js#L126-L131

**Comment by Jokero** [comment]
For me it also looks very strange that instantiation does some connections.
I like how it did in `mongoose`. You need to connect explicitly:
```js
mongoose.connect('mongodb://localhost/myapp');
var MyModel = mongoose.model('Test', new Schema({ name: String }));
// Works
MyModel.findOne(function(error, result) { /* ... */ });
```
Yes, I can `lazyConnect` option, but anyway it looks like antipattern
