### ISSUE TITLE
getting error while connecting to cluster 

### ISSUE THREAD

**Issue by Anandesi** [luin/ioredis#351]
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1061:14)

**Comment by luin** [comment]
Did you bind the redis nodes to the wrong interfaces?

**Comment by Anandesi** [comment]
i set the bind address as 0.0.0.0 so that it can be access any where . and
enabled cluster. and formed cluster using cluster meet command

my cluster will be

1master  1slave
1m 2s
1m 3s

and getting throughput same for all

**Comment by luin** [comment]
I believe that's not a ioredis specified issue. Refer to http://stackoverflow.com/questions/37341646/redis-cli-redirected-to-127-0-0-1 for details.

**Comment by luin** [comment]
I'm closing this issue. Feel free to reopen it with more information.

**Comment by PhilTheAir** [comment]
I came across the same issue only to find out the reason had nothing to do with ioredis.
I used EventEmitter in Node.js but did not place "eventEmitter.emit('start');" in the last line. That is, placed "eventEmitter.emit('start');" in the front of many "eventEmitter.on('...');" codes. Hence the redis ECONNREFUSED  error...
