### ISSUE TITLE
How to get `client list` from redis

### ISSUE THREAD

**Issue by danilvalov** [luin/ioredis#355]
I need to get [client list](http://redis.io/commands/client-list) from Redis. But if i write:
```
var Redis = require('ioredis');
var redis = new Redis();

var clientList = new Redis.Command('client list', null, function (err, result) {
  console.log(result);
});

redis.sendCommand(clientList);
```
i see:
```
Unhandled rejection ReplyError: ERR unknown command 'client list'
    at JavascriptReplyParser.replyParser.Parser.returnError (node_modules/ioredis/lib/redis/parser.js:25:25)
```

P.S. If i use redis-cli then i can to get client list:

![](https://cl.ly/3T1J3g342r0e/Image%202016-08-08%20at%208.09.59%20PM.png)

**Comment by luin** [comment]
Just `redis.client('list', function (err, result) {});` should work. ioredis supports all redis commands so that you don't need to create new `Redis.Command` instances yourself.

**Comment by danilvalov** [comment]
@luin Thank you! It works!

But perhaps it is worth adding a parser for `redis.client('list')` from returned string:
```
id=112 addr=127.0.0.1:55153 fd=6 name= age=0 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=32768 obl=0 oll=0 omem=0 events=r cmd=client
```

**Comment by luin** [comment]
You can define your own reply transformer to parse it (https://github.com/luin/ioredis#transforming-arguments--replies) or simply parse it on the client side.

**Comment by danilvalov** [comment]
Thank you!
