### ISSUE TITLE
Support for node_redis arrays of commands

### ISSUE THREAD

**Issue by johnlogsdon** [luin/ioredis#36]
We've looked at this project as a replacement for our current library for node redis support, as it supports cluster, but we heavily use passing arrays of flattened commands to multi() and cannot see how to do this with ioredis:
https://github.com/mranney/node_redis#multiexec-callback-
Specifically:
```
client.multi([
        ["mget", "multifoo", "multibar", redis.print],
        ["incr", "multifoo"],
        ["incr", "multibar"]
    ]).exec(function (err, replies) {
        console.log(replies);
    });

```
Is it possible?

Thanks

John

**Comment by luin** [comment]
Yes, it's possible. However you still need migrate your code since the results of `exec` are different between ioredis and node_redis. For more information: https://github.com/luin/ioredis/wiki/Migrating-from-node_redis

**Comment by johnlogsdon** [comment]
Thanks for a really quick detailed response however can you confirm that ioredis supports the specific case I showed above as I dont seem to be able to get that to work i.e. instead of multi.mget(),incr(),incr() you can do multi([['mget',...], ['incr', ...],['incr',...]]

**Comment by luin** [comment]
Hi, I just implement this API and ship it in 1.3.2

**Comment by johnlogsdon** [comment]
You may have set a record for quickest project update! Thanks very much for doing this as I'm up and running now, all good!
