### ISSUE TITLE
a default options of  ttl  is need?

### ISSUE THREAD

**Issue by jaylinwang** [luin/ioredis#362]
i think a default options of ttl is necessary,are you ? 😄

**Comment by luin** [comment]
Which ttl did you mean? Could you provide an example?

**Comment by jaylinwang** [comment]
Redis session TTL (expiration) in seconds.

**Comment by luin** [comment]
Redis session? Do you mean the arguments of the `EXPIRE` command?

**Comment by jaylinwang** [comment]
yeah,it's right. description indeterminacy,i'm so sorry 🎅

**Comment by luin** [comment]
Aha. What value of the default ttl do you want? You can define a new command with a default ttl set:

```javascript
redis.exipreWithDefaultTTL = function (key, seconds) {
  seconds  = seconds || 0;
  return redis.expire(key, seconds);
};
```
