### ISSUE TITLE
How to user thread-pool when i use cluster  to connect to ?

### ISSUE THREAD

**Issue by majintao** [luin/ioredis#363]
Is cluster support thread-pool?

**Comment by luin** [comment]
I've not used thread-pool, did you get any errors when using ioredis with thread-pool?

**Comment by majintao** [comment]
Can i user this for thread-pool?
https://github.com/coopernurse/node-pool

**Comment by luin** [comment]
Do you mean generic-pool or thread-pool? For the former one, you should be able to use it with ioredis.
