### ISSUE TITLE
Handle "not found" and "connection/client errors" in one .then()

### ISSUE THREAD

**Issue by dvp0** [luin/ioredis#364]
Handle "not found" and "connection/client errors" in one place when using promise. I have a same fallback of those two scenarios but I have to use promises.
```javascript
return romis.getAsync("amazon")
                .then(function (amazonSTR) {
                      //THEN ONE
                      console.log(amazonSTR); // will be undefined if not found
                      return doManualDBProcedure();
                 })
                 .catch(function (err) {
                      // CATCH ONE
                      console.log(err);
                      return doManualDBProcedure();
                 });
```
Is there any way I can handle both errors in //THEN ONE  ?

**Comment by AVVS** [comment]
Throw error in then if its empty and handle it in catch. Logic seem to be flawed though

**Comment by luin** [comment]
This shouldn't be handled inside the ioredis since getting an inexistent key will receive an empty value instead of throwing an error. You may, as @AVVS said, just throw an error when `amazonSTR` is null.

**Comment by dvp0** [comment]
Thanks folks for your input. That solves my problem partly. 

 @AVVS Any reason you find the logic flowed ? I am new to node and redis, anything will help :)

**Comment by AVVS** [comment]
doing the same operation on internal redis error (connection flipped, invalid key, etc) and missing key is somewhat weird. Key might exist just fine
