### ISSUE TITLE
Connection level transformer settings

### ISSUE THREAD

**Issue by mklilley** [luin/ioredis#366]
Hi,

I am working on a project that needs several ioredis connections. I encountered a problem very recently because I added a replyTransformer, working on zrangebyscore, which was fine for one connection by inappropriate for another.  Unless I am mistaken ioredis does not support transformers at the connection level.  My solution right now is add the transformer and then clear the require cache before using ioredis for the next connection, but I have been advised that is not a good solution. I think this would be a useful addition to the capabilities of ioredis.

Thanks,

Best regards,

Matt

**Comment by luin** [comment]
Global level transformations will be deprecated in the 3.0 version and hooks will be introduced. Currently connection-level transformers are not supported. Two workarounds may be used before 3.0:

1. Your approach, clear the require cache to force node.js requires a isolate ioredis instance for each connection.
2. Simply override the command like:

```javascript
const Redis = require('ioredis');
const redis = new Redis();
const zrangebyscore = redis.zrangebyscore.bind(redis);
redis.zrangebyscore = function (args, /* other arguments...*/) {
  return zrangebyscore(args,  /* other arguments...*/).then((reply) => {
    // transform reply here
    return reply;
  });
};
```

See https://github.com/luin/ioredis/issues/347 for details.

**Comment by mklilley** [comment]
Thanks @luin , really appreciate your quick response,

**Comment by loucadufault** [comment]
We also have a use case for this functionality.

Can one of this issue or #347 be reopened considering the feature is not implemented.
