### ISSUE TITLE
Returning initial data from subscribed channel.

### ISSUE THREAD

**Issue by dmason30** [luin/ioredis#368]
I have the below basic block of code subscribing to a channel on my server. 

The issue I am facing is that the channel it is subscribed to is updated anywhere from every second to hourly, yet this only emits the data when it has changed (as expected). 

**How to I get it to emit the current data in the channel on connection?**
  
    var app = require('express')();
    var http = require('http').Server(app);
    var io = require('socket.io')(http);
    var Redis = require('ioredis');
    var redis = new Redis();
    //Connected
    io.on('connection', function(socket){
        //Subscribe to channel
        redis.subscribe('exchange_rates', function (err, count) {});
    
        //Emit messages
        redis.on('message', function (channel, message) {
            message = JSON.parse(message);
            console.log(channel + ':' + message.event + ':data: ' + JSON.stringify(message.data));
            socket.emit(channel + ':' + message.event, message.data);
        });
    });
    
    //Allow connections on port 3000 if not connecting check firewall
    http.listen(3000, function () {
        console.log('Listening on Port 3000');
    });

**Comment by luin** [comment]
Hi @dmason30!
What do you mean by "initial data"? If you mean the message that emitted before the connection is established, than the answer is you can't because redis's pub/sub is fire and forget, the message will not be stored in the memory.

**Comment by dmason30** [comment]
Hi @luin, 

I have a laravel application broadcasting this data to the redis cache. When the user connects and there is already data in redis under this channel I want it to, on connection, emit this data (message) to the client. 

Currently it appears that is only gets the data (message) when channel is updated so it sits there without any data waiting for the update.

**Comment by luin** [comment]
Yes, this is the expected behaviour. Because redis doesn't store the published messages in the memory/disk. Refer to http://redis.io/topics/pubsub for details.
