### ISSUE TITLE
consider using SRV records for redis & sentinel hosts

### ISSUE THREAD

**Issue by jedi4ever** [luin/ioredis#37]
In an ever changing world like docker & microservices , the IP-adresses + PORTS of hosts change.
Traditionally only DNS takes care of the hostname->IP

- Ideally on connection failure the client would lookup the DNS & Port again.
- On redis-sentinel topology change it could lookup the master & slave DNS & Port again.

We could leverage the SRV record to find the current redis host & port instead of a regular dns lookup.

This ticket is to ask if you will find the useful, and would be willing to accept a pullrequest for implementing this.

**Comment by luin** [comment]
It sounds useful. How would the syntax look? Is it something like `new Redis('@hostname')`?

**Comment by jedi4ever** [comment]
Alternative could be:

- `new Redis({ srv: 'redis.consul' })` : specific srv specification
- `new Redis({ host: 'redis.consul' , srv:true }) : toggle between regular host and port or read srv record

**Comment by luin** [comment]
Sounds great! I would like to have this feature :-)

**Comment by jedi4ever** [comment]
great ! which syntax do you prefer?

**Comment by luin** [comment]
I prefer `new Redis({ srv: 'redis.consul' })`.

**Comment by AVVS** [comment]
any plans to add this?

**Comment by luin** [comment]
pr is still welcomed

**Comment by AVVS** [comment]
Ok, I'll try to get something done

**Comment by nunofgs** [comment]
@AVVS: any news on this?

**Comment by MrPink** [comment]
@jedi4ever did you ever get anywhere with this?

**Comment by JCMais** [comment]
just in case this is added someday, for inspiration, mongodb uses `mongodb+srv://` for srv

**Comment by LipingSun** [comment]
any update for this feature?
