### ISSUE TITLE
get issue with high concurrency

### ISSUE THREAD

**Issue by sea-yang** [luin/ioredis#371]
I try to set 1 ~ 5000 in advance,  key and value are same as below. (easy to test)
key : value
1    :   1 
2    :   2
3    :   3
n    :   n

then get and print the value with concurrency.
as the result, I find sometimes the result value will be out of sync with the key.

```
function myGet(i) {
  redis.get(i)
  .then(result => {
    if (result != i) {
      console.log('error value')
    }
    if (i < 5000) {
      myGet(++i);
    } else {
      console.log('complete');
    }
  });
}

myGet(1);
myGet(1);
myGet(1);
myGet(1);
```

**Comment by luin** [comment]
Could you confirm whether the data stored in the database is correct? Did you try logging the `result` and `i` when they were not same (`console.log('error value', result, i)`)?

**Comment by luin** [comment]
I'm closing this for now. Feel free to reopen this issue with more details.

**Comment by sea-yang** [comment]
yes. I'm sure. the data stored in db is correct. 
if I only launch one and two functions 'myGet(1)', the results are all right.
```
myGet(1);
myGet(1);
``` 
but if I try to launch more functions(> 3) , the error result will be coming.  
```
myGet(1);
myGet(1);
myGet(1);
myGet(1);
....
```

**Comment by luin** [comment]
Could you please enable the debug mode (DEBUG=ioredis:* node yourapp.js) and post the logs here? Also remember to print the unexpected values (by `console.log('error value', result, i)`).

Btw, what's your Redis setup? Standalone or Cluster? Are you using the official Redis version or a SaaS Redis service? Which Redis server and ioredis versions are you using?

**Comment by sea-yang** [comment]
thanks for your feedback soon. 
I think it should be our inside proxy issue. 

In one connection, we can send async get concurrently
I think ioredis can make sure we can get the corresponding return value exactly in async get.
right？

**Comment by luin** [comment]
> I think ioredis can make sure we can get the corresponding return value exactly in async get.
right？

This is the most basic requirement for a redis client. So the answer is definitely yes.
