### ISSUE TITLE
主从集群链接失败

### ISSUE THREAD

**Issue by gillgong** [luin/ioredis#374]
let client = new Redis.Cluster(
      [
		{
			port:6307,
			host:'127.0.0.1'
		},
		{
			port:6308,
			host:'127.0.0.1'
		}],
      {
      scaleReads: 'all'
     }
);

报错是： Failed to refresh slots cache.

怎么解决啊

**Comment by luin** [comment]
看看 err 的 `lastNodeError` 属性。麻烦问题都提到 StackOverflow 吧，这里只供 bug 和 feature 交流。多谢了
