### ISSUE TITLE
how to use the sort function corresponding the redis sort command ?

### ISSUE THREAD

**Issue by fwjieok** [luin/ioredis#376]
how to use the sort function corresponding the redis sort command ?
where the ioredis api doc ?  I want to get the detailed document to know how to user any api function.

**Comment by luin** [comment]
ioredis simply, [as documented](https://github.com/luin/ioredis#basic-usage), passed all arguments to Redis directly. Refer to the official documentation for the usage of each command: http://redis.io/commands.

**Comment by fwjieok** [comment]
我的用法如下：
redis .sort("newuserlist").then(function (result) {                     
    console.log(result);      
}); 
这样是可以获取我想要的数据的。
然而如下写法是不行的：
redis .sort("newuserlist get user:userid:*:username").then(function (result) {     
    console.log(result);       
});               

在redis-cli中执行sort newuserlist get user:userid:*:username   是可以获取我想要的数据的，我的写法有问题吗？
sort函数到底怎样用？

**Comment by luin** [comment]
```javascript
redis.sort('newuserlist', 'get', 'user:userid:*:username');
```

**Comment by fwjieok** [comment]
Thanks Very Much, I complete my function!  use:
redis.sort('newuserlist', 'get', 'user:userid:*:username', 'desc', 'limit', 0 , 5);
