### ISSUE TITLE
Amazon Elasticache failover in case of Pub/Sub

### ISSUE THREAD

**Issue by jeanadrien** [luin/ioredis#379]
Hello,

I'm using ioredis with AWS elasticache, and I'm facing a master/slave failover issue comparable to the one described in this ticket: https://github.com/luin/ioredis/issues/144

Except that, in my case, I'm using PUB/SUB and the PUBLISH command issued to a non-master node does not return any error. Thus I can't use the `reconnectOnError` feature. The result is that old clients publishing on slave, do not reach new subscribers connected on master, and this is happening silently.

I also wrote to AWS support. It's probably not something which can be fixed in ioredis code, but I was wondering if you know a way to detect the master/slave change from the publisher client. Or any other strategy to avoid this situation.

**Comment by luin** [comment]
A workaround is sending `ROLE` command every second (or shorter depending on your need), and disconnect manually when the result changed to `slave`. However, messages will still be lost when published before heartbeat detecting the failover.

**Comment by jeanadrien** [comment]
Yes, that can do the trick, thanks. According to this Redis ticket https://github.com/antirez/redis/issues/2942 it's not really an option that PUBLISH on a readonly slave returns an error, but they suggest another approach: to pair the PUBLISH command with a random SET command in a pipeline, and this way the master role is checked with a negligible performance cost and no data loss.

**Comment by luin** [comment]
Aha, Nice solution! Thank you for sharing this.
