### ISSUE TITLE
does not parse URL connection strings that have passwords with /s

### ISSUE THREAD

**Issue by jonathanong** [luin/ioredis#380]
because base64 includes `/`s.

For example, using the connection string `redis://:base64/klajsdflkjasdf@localhost:6379/0` yields the following options:

```json
{ db: NaN,
  port: 6379,
  host: 'localhost',
  family: 4,
  connectTimeout: 3000,
  retryStrategy: [Function: retryStrategy],
  keepAlive: 0,
  connectionName: null,
  sentinels: null,
  name: null,
  role: 'master',
  sentinelRetryStrategy: [Function: sentinelRetryStrategy],
  password: null,
  parser: null,
  dropBufferSupport: false,
  enableOfflineQueue: true,
  enableReadyCheck: true,
  autoResubscribe: true,
  autoResendUnfulfilledCommands: true,
  lazyConnect: false,
  keyPrefix: '',
  reconnectOnError: null,
  readOnly: false,
  stringNumbers: false }
```

**Comment by luin** [comment]
It seems the auth info part should be encoded (`encodeURIComponent`) before put into the url.
Details:
https://github.com/nodejs/node/blob/master/lib/url.js#L561
https://www.ietf.org/rfc/rfc3986.txt

**Comment by jonathanong** [comment]
Ah ok. Feel free to close then :)

**Comment by ddennis** [comment]
I also had this issue - using Azure Redis Cache from a linux VM.
Could this info maybe be part of the README under [Error handling](https://github.com/luin/ioredis#error-handling)

Thank you for a great library.
