### ISSUE TITLE
使用ioredis.cluster时报错

### ISSUE THREAD

**Issue by 16boke** [luin/ioredis#382]
配置信息如下：
{ domain: null,
     _events: { refresh: [Object], close: [Object] },
     _maxListeners: 10,
     options:
      { showFriendlyErrorStack: false,
        clusterRetryStrategy: [Function],
        enableOfflineQueue: true,
        enableReadyCheck: true,
        scaleReads: 'master',
        maxRedirections: 16,
        retryDelayOnFailover: 100,
        retryDelayOnClusterDown: 100,
        retryDelayOnTryAgain: 100 },
     scriptsSet: {},
     connectionPool:
      { domain: null,
        _events: [Object],
        _maxListeners: 10,
        redisOptions: undefined,
        nodes: [Object],
        specifiedOptions: [Object] },
     startupNodes: [ [Object] ],
     slots: [],
     retryAttempts: 0,
     offlineQueue: { _capacity: 16, _length: 0, _front: 0 },
     delayQueue: { queues: {}, timeouts: {} },
     subscriber:
      { domain: null,
        _events: [Object],
        _maxListeners: 10,
        options: [Object],
        scriptsSet: {},
        commandQueue: [Object],
        offlineQueue: [Object],
        connector: [Object],
        retryAttempts: 0,
        status: 'connecting',
        condition: [Object] },
     status: 'connecting',
     isRefreshing: true,
     lastActiveSubscriber:
      { domain: null,
        _events: [Object],
        _maxListeners: 10,
        options: [Object],
        scriptsSet: {},
        commandQueue: [Object],
        offlineQueue: [Object],
        connector: [Object],
        retryAttempts: 0,
        status: 'connecting',
        condition: [Object] } } }
报错信息如下：
[ioredis] Unhandled error event: Error: Failed to refresh slots cache.

**Comment by 16boke** [comment]
ioredis的cluster是不是只支持redis3.0以上的cluster?
是否支持codis集群？

**Comment by luin** [comment]
只支持 Redis 3.0 之后的官方 Cluster。Codis 我记得是做了透明代理，直接用 `new Redis()` 连就行
