### ISSUE TITLE
Can't connect to cluster (constantly reconnecting) and usable no feedback.

### ISSUE THREAD

**Issue by allthetime** [luin/ioredis#384]
Hi, I'm trying to connect to a cluster.

I can reach each node by doing

`redis-cli -h HOST -p PORT`

but using the same hosts and ports as nodes with ioredis I am stuck with `cluster.status` always being `reconnecting`

I was able to connect with ioredis to localhost using the exact same code, but I am trying to use a separate server now.

First of all, any idea why this would happen?

Second, can I get more detailed information about why the connection is failing somehow?

**Comment by luin** [comment]
The cluster nodes may have been bound to the wrong interface (so they returned local address like `127.0.0.1` which ioredis can't connect to), you can check this by running `CLUSTER NODES` in the redis-cli.

Debug mode can be enabled by `DEBUG=ioredis:* yourapp.js`.

**Comment by allthetime** [comment]
@luin

I just found all the events to use to detect connection errors and it looks like even though I am setting `host` explicitly, it is still trying to connect to localhost (127.0.0.1)

Oh.... so, I might have to re-run my cluster setup to use the proper addresses?

Thank you so much.

**Comment by luin** [comment]
Related issue: https://github.com/luin/ioredis/issues/330

**Comment by allthetime** [comment]
Yup that was the problem exactly. 

Needed to use explicit/external addresses in the redis cluster node configuration instead of 127.0.0.1
