### ISSUE TITLE
您好，正在学习使用ioredis，取数据的时候，result为字符串，是使用的姿势不对么？

### ISSUE THREAD

**Issue by zdy23216340** [luin/ioredis#388]
var Redis = require('ioredis');

var redisMgr = module.exports = {};

redisMgr.playerClient = new Redis({
  port: 6379,          // Redis port
  host: '127.0.0.1',   // Redis host
  db: 1
});

redisMgr.playerClient.mset(45,{aa:30,bb:'40'});

redisMgr.playerClient.get(45,function(err,result){
	console.log(result);
    //  result -> [Object,Object]
});

**Comment by luin** [comment]
`mset` 不支持这样用，具体可以查一下相关文档。你可能需要 `hmset` 或者 `mset(45,JSON.stringify({aa:30,bb:'40'}))`

**Comment by zdy23216340** [comment]
好的，谢谢～ @luin
