### ISSUE TITLE
Multi-exec issue on result

### ISSUE THREAD

**Issue by kelchy** [luin/ioredis#389]
most of the times during the start of my node instance, I get this
`[ [ null, 'OK' ], [ null, '{"base":[{"base_id":1}]}' ] ]`
for this command
`redisClient.multi().select(5).get(key).exec()`

but for some, I get this
`[ [ null, 'O' ], [ null, 'K' ] ]`

looks like the result of  select is being broken into 2.
any ideas where this problem might be?

**Comment by luin** [comment]
Did your redis server run behind any proxies (SaaS services, codis or something)? Which ioredis and Redis version are you using?

**Comment by kelchy** [comment]
"ioredis": "^2.4.0"

no proxies, just sentinel 
redis 3:3.0.6-1chl1~trusty1

**Comment by luin** [comment]
Could you please try to reproduce the problem so I can debug locally?

**Comment by kelchy** [comment]
I can reproduce this problem 100%

**Comment by luin** [comment]
How can I reproduce it locally?

**Comment by kelchy** [comment]
i am trying to isolate code since project is quite big.

if i isolate, the problem does not exist. but if i run it together with
everything else, problem shows up 100%
I am inclined to think that there might be other stuff causing this but it
is difficult to trace. it only shows up during
startup, where the server tries to do lot of initialization like fetching a
bunch of wsdl for a SOAP feature.

strange enough, when i put a 2seconds timeout before fetching from redis,
it works. this is not ideal as i need
the cache as early as possible during startup. any clue on how to dig
deeper?

Kelvin Chua

**Comment by luin** [comment]
I'm not sure but it may be related with your codebase. I'm willing to help if you have further information for this issue.

**Comment by kelchy** [comment]
Yes it was indeed related. I was able to find the real reason.

In my code base, initialization is very heavy. so redis takes more than 1 second to emit "ready"
In this situation, somewhere somehow, when I fetch a key from redis, it returns this erroneous response. I have patched my code to wait for "ready" before proceeding and it works.

however, I think this behaviour is incorrect in a way that ioredis should have returned error instead
of providing
`[ [ null, 'O' ], [ null, 'K' ] ]`

**Comment by luin** [comment]
Yes, the result of `[ [ null, 'O' ], [ null, 'K' ] ]` should not be returned, but I still can't find out where the result comes from. Let me know if you are able to provide a self-contained code to reproduce the problem. I'll keep looking into this issue.
