### ISSUE TITLE
scaleReads only for cluster?

### ISSUE THREAD

**Issue by Somebi** [luin/ioredis#391]
scaleReads is working only for cluster or with replication/sentinels setup too?
scaleReads should be then passed as second argument inside object or can be passed into first argument too, along with database index?

**Comment by luin** [comment]
Related issue: https://github.com/luin/ioredis/issues/387.
`scaleReads` can be only passed via the second argument.

**Comment by luin** [comment]
Currently nope. Please refer to #387 for details.
