### ISSUE TITLE
大数据下pipeline() 慢并且导致内存不足

### ISSUE THREAD

**Issue by subo-romens** [luin/ioredis#392]
我需要在初始化服务时 获取大量数据代码 测试如下
  var authedRedis= _redisHelper.client;
         var  firstcount=5000000;
         for (var i=0;i<firstcount;i++) {
             authedRedis.pipeline().set('GUID:'+ i, 'bar1');

         }
         console.log('ioRedis set 完成');
         pipeline.exec(function (err, results) {
             if(err)
                 throw err;
             console.log('ioRedis 完成');
         });
大约过了10分钟提示内存不足，请问怎么处理大数据导入
FATAL ERROR: Committing semi space failed. Allocation failed - process out of memory

**Comment by sumeet559** [comment]
The doc in the link says http://redis.io/topics/pipelining.
I guess you need to split the task in batches.

**Snippet from the doc**
IMPORTANT NOTE: While the client sends commands using pipelining, the server will be forced to queue the replies, using memory. **So if you need to send a lot of commands with pipelining, it is better to send them as batches having a reasonable number, for instance 10k commands, read the replies, and then send another 10k commands again, and so forth.** The speed will be nearly the same, but the additional memory used will be at max the amount needed to queue the replies for this 10k commands.

**Comment by luin** [comment]
Pipeline is designed to reduce the network latency of sending/receiving many small commands. All commands in a pipeline have to be stored in the memory before sending them off, so it would require huge memory if your commands contain large data.

Pipeline 是为了减少发送很多小命令导致的网络延迟而设计的。通过 Pipeline 发送的所有命令都必须先存储到内存中，所以如果你的命令中包含很多大数据时，就会消耗很多内存。
