### ISSUE TITLE
Async prefferedSlaves function

### ISSUE THREAD

**Issue by Nepoxx** [luin/ioredis#394]
What would be a good way to select a slave asynchronously? Right now the `preferedSlaves` takes in either an array or a synchronous function. I would like to select the "closest" slave (lowest latency), for instance, so I need to ping all of them then return the best one.

**Comment by luin** [comment]
Synchronous function option makes sure no additional IO operation is required when selecting slaves. Just keep pinging the slaves in your app and maintain a table to store the best one. Then return it in `preferredSlaves` synchronously.

**Comment by Nepoxx** [comment]
I'm not sure I understand. If I keep a table with the slaves in order of ping, they're going to get selected correctly next time there's a reconnection? What about the first time?

**Comment by luin** [comment]
@Nepoxx Yes, that's correct. Just chose a slave randomly at the first time.
