### ISSUE TITLE
How do I keep my connection alive?

### ISSUE THREAD

**Issue by seanlindo** [luin/ioredis#395]
I'm attempting to use this client with Kue. Compose has informed me that they timeout connections every 5 minutes and that this value is hardcoded. I need some way to keeping the connection alive and perhaps pinging it every 2-3 minutes. 

It does not appear Kue will give me access to the underlying client. If I create a separate ioredis client and execute a ping in a `setTimeout`, will it keep all connections alive or just that one instance?

**Comment by luin** [comment]
Create a separate ioredis client and ping periodically may be not able to keep other connections alive.
Kue provides the `client` member to access the underlying redis instance.

**Comment by seanlindo** [comment]
Thanks for the response. I'm using ioredis for interacting with a cache now and the default keepalive settings worked perfectly-- in my case, queuing has been best left to SQS :)
