### ISSUE TITLE
redis断开重连逻辑

### ISSUE THREAD

**Issue by diamont1001** [luin/ioredis#398]
没有设置 `retryStrategy`

```js
const redisClient = new Redis(6379, '127.0.0.1');
```

```js
const value = yield redisClient.get('key');
```
这里如果redis服务器断开了，redisClient.get 这句会阻塞住，然后开始不断重连。

能不能让 `redisClient` 的重连跟业务逻辑区分开来？比如 `redisClient` 自己单独另开个线程去重连，然后 `redisClient.get` 这些方法在调用的时候，检测如果没连接成功就直接返回“redis未连接”错误码，这样才不会因为重连的逻辑而阻塞到业务逻辑。

**Comment by luin** [comment]
可以直接禁用默认的自动重连，改成监听 end 事件并在其中重新 connect

Get Outlook for iOS

		_____________________________

**Comment by diamont1001** [comment]
OK了，谢谢
