### ISSUE TITLE
DeprecationWarning Error

### ISSUE THREAD

**Issue by omidh28** [luin/ioredis#399]
I'm getting this error when I'm trying to set a buffer using ioredis

`const result = await this.redisConnection.set(key, bufferData);`

> (node:2529) DeprecationWarning: Using Buffer without `new` will soon stop working. Use `new Buffer()`, or preferably `Buffer.from()`, `Buffer.allocUnsafe()` or `Buffer.alloc()` instead.

**Comment by luin** [comment]
Which ioredis version are you using?

**Comment by omidh28** [comment]
@luin I'm using latest one, 2.4.0

**Comment by shaharmor** [comment]
Buffer changed in new Node version, need to update the library accordingly

**Comment by AVVS** [comment]
Its an error from flexbuffer lib

**Comment by AVVS** [comment]
https://github.com/mercadolibre/flexbuffer-node/issues/2

**Comment by luin** [comment]
I'm closing this since the warning has been reverted in the latest Node.js version.
