### ISSUE TITLE
logs to console directly, would like user-specified option

### ISSUE THREAD

**Issue by pszabop** [luin/ioredis#400]
**Feature request:**

Currently the code logs to console.error() directly, and it's not easy to override.

Please consider adding an option to log to a user-specified destination.  Leaving the default as console is preferred.

**Comment by luin** [comment]
It's recommended to listen to the `error` event and handle the errors explicitly, otherwise ioredis will logs the error the `stderr`.

**Comment by pszabop** [comment]
My apologies.  Reading too fast. The behavior you describe is documented [here](https://github.com/luin/ioredis#error-handling):
