### ISSUE TITLE
Support for hmget?

### ISSUE THREAD

**Issue by LukeNZ** [luin/ioredis#401]
Does ioredis support `hmget`? I don't see any indication of it being usable in the documentation, nor does the codebase appear to contain a reference to `hmget` on a quick search. Thanks.

**Comment by luin** [comment]
ioredis supports all Redis commands. Try `redis.hmget()`.

**Comment by LukeNZ** [comment]
No indication whatsoever on how to use it, poor documentation. I will have to assume it does not exist.
