### ISSUE TITLE
Detecting the state of a connection

### ISSUE THREAD

**Issue by nicholasf** [luin/ioredis#403]
Hi,

I want to ensure that every connection my codebase forms to Redis has a `quit` called on it. We are covering this in the code itself - create a connection, do something, call `quit` - but I would like the option of having a backup plan in case the quit does not get called. Especially when keeping in mind ioredis' keepalive policy. 

So, I'm thinking about wrapping ioredis with a layer that can check on the status of the connection and close it, if it is found to be open after `n` seconds. 

I have found the status flag.

```
> r = new ioredis()
...
> r.status
'ready'

> r.quit((e, o) => {console.log('done: ', o) })
 ... 

> done:  OK

> r.status
'end'
```

Is this the best field for the check? Could my logic be as simple as if the status is not 'end' after `n` seconds, call quit?

Thanks,
Nicholas

**Comment by luin** [comment]
Yes, `status` shows the connection status of a connection, and it's documented on the README.md.

**Comment by nicholasf** [comment]
Thanks luin.
