### ISSUE TITLE
Perf: after creating connection enable tcp_nodelay

### ISSUE THREAD

**Issue by AVVS** [luin/ioredis#405]
As in put stream.setNoDelay() on the socket
Will decrease latency in most cases

**Comment by luin** [comment]
Thank you for addressing that! I've added you as the contributor, please review & merge the pull request above.

**Comment by AVVS** [comment]
Thanks, will do

**Comment by AVVS** [comment]
Closed by #406

**Comment by AVVS** [comment]
We also might want to add that if somebody does bulk export/import and its important to increase _throughput_, whereas latency doesn't matter as much - `noDelay` should be set to `false`, because while this decreases latency, it reduces maximum throughput

**Comment by AVVS** [comment]
@luin can you release the latest version?

**Comment by luin** [comment]
v2.4.1 released. 😆
