### ISSUE TITLE
hgetall return {} rather than nil when no key found

### ISSUE THREAD

**Issue by RuofeiLv** [luin/ioredis#407]
I have seen the same issue submitted before, but it still existed, hope to fix it. Return nil would be easy to code. Thanks

**Comment by luin** [comment]
ioredis follows exactly what Redis server returns. If you try to `hgetall` a non-existent key, Redis will return an empty list instead of nil. Given that, ioredis returns an empty object instead of null.

**Comment by wangkunmeng** [comment]
const _ = require('lodash');
Redis.Command.setReplyTransformer('hgetall', (result) => {
  if (_.isEmpty(result)) {
    return null;
  }
  return result;
});

**Comment by wangkunmeng** [comment]
``` js
const _ = require('lodash');

// Here's the built-in reply transformer converting the HGETALL reply
// {}
// into
// null
let lastFunc = Redis.Command._transformer.reply['hgetall'];
Redis.Command.setReplyTransformer('hgetall', (result) => {
  if (typeof lastFunc === 'function') {
    result = lastFunc(result);
  }
  if (_.isEqual(result, {})) {
    return null;
  }
  return result;
});
```
