### ISSUE TITLE
What is the time Unit of Expire command Seconds or Milliseconds?

### ISSUE THREAD

**Issue by vipreshjha** [luin/ioredis#415]
redis.expire command takes the time in Seconds or Milliseconds?
 Would be nice if this was also documented somewhere.

**Comment by luin** [comment]
It's a redis command so you can check out the redis official document. The unit of expire is second  while pexpire is ms.

Get Outlook for iOS




On Wed, Dec 21, 2016 at 9:44 PM +0800, "vipreshjha" <notifications@github.com> wrote:












redis.expire command takes the time in Seconds or Milliseconds?

Would be nice if this was also documented somewhere.

**Comment by andr0s** [comment]
This is actually a very important thing, but the official documentation doesn't seem to state it clearly.

**Comment by shetshrikant** [comment]
This has still not been documented.

**Comment by luin** [comment]
Hi @shetshrikant, I think it's already documented on https://redis.io/commands/expire. It says the second argument is `seconds`. Did I miss something? Or you expect we document this on ioredis's README?

**Comment by shetshrikant** [comment]
The documentation [](https://redis.io/commands/expire) starts with the heading "EXPIRE key seconds". It can be inferred from the example in the section "Pattern: Navigation session". In fact, the documentation states clearly the accuracy for the expiry but does not explicitly state that the value is in seconds. I feel it should have been explicitly stated.
