### ISSUE TITLE
Multi or Pipeline in Cluster mode

### ISSUE THREAD

**Issue by imsrini-m** [luin/ioredis#417]
For implementing multi with redis, we are having a sample implementation at 
https://github.com/luin/ioredis#transaction .

In a similar way, I have tried like cluster.multi() and cluster.pipeline() by creating the cluster object. But, it is not working as expected.
 
Is there any sample code?
Can someone help on How to use multi in cluster mode?

**Comment by imsrini-m** [comment]
Getting the following issue while running the below code block.

**Comment by luin** [comment]
Hi, sorry for the late response. You must make sure all keys belong to the same slot when using pipeline in the cluster mode.

For example:

```javascript
cluster.pipeline().set('{foo}1', 'bar').set('{foo}2', 'bar').exec()
```

**Comment by kiko35** [comment]
> Hi, sorry for the late response. You must make sure all keys belong to the same slot when using pipeline in the cluster mode.
> 
> For example:
> 
> ```js
> cluster.pipeline().set('{foo}1', 'bar').set('{foo}2', 'bar').exec()
> ```

How can we do that please? Because I don't know if all the keys of my transaction belong to the same node.
