### ISSUE TITLE
georadius: ERR syntax error

### ISSUE THREAD

**Issue by TangMonk** [luin/ioredis#418]
if specify `count` parameter:
```
const result = await redis.georadius('car', request.query.lng, request.query.lat, '50', 'km', 'WITHDIST', 'COUNT 10')
```
redis will throw me error:

```
ERR syntax error
```

if without `count` parameter will works fine

**Comment by luin** [comment]
`COUNT 10` should be specified as two arguments. Try `'COUNT', 10`

**Comment by TangMonk** [comment]
@luin sorry, that's my problem, and thanks for quickly reply!
