### ISSUE TITLE
Empty arrays/objects cause commands to fail (ex: "mset({})")

### ISSUE THREAD

**Issue by ide** [luin/ioredis#419]
Some Redis commands that operate on collections, like mset, fail when no arguments are provided:
```sh
redis:6379> mset
(error) ERR wrong number of arguments for 'mset' command
```

This causes `redis.mset({})` (which is transformed to `redis.mset()`) to fail because the underlying Redis implementation expects at least one key-value pair. So this bug isn't really ioredis's fault but it could be convenient for ioredis to offer a more natural API by default.

From a programmer's perspective, I've found it common to build up a map or array of values to pass to Redis:
```js
let keys = [];
for (let key of ...) {
  if (...) {
    keys.push(key);
  }
}

let values = await redis.mget(keys);
```

Sometimes the map or array might be empty, so you currently need to guard every call to ioredis that's written in this style:
```js
let values = [];
if (keys.length) {
  values = await redis.mget(keys);
}
```

So for this scenario I want a wrapper API that can handle empty objects/arrays and just returns an empty result set right away. Since ioredis already provides a convenience API (the transformers) for some commands like mset, would you want to extend the API to support empty objects/arrays for convenience too?

**Comment by luin** [comment]
Makes sense to me. However this change will break BC so this feature may be shipped with v3.0.

**Comment by philraj** [comment]
Was there ever any movement on this? The ioredis API would be much nicer to use if you didn't have to explicitly check whether arguments are empty when calling commands.

**Comment by Sorosliu1029** [comment]
It seems this issue remains in v4.9.0 ioredis
