### ISSUE TITLE
Unfulfilled commands sent on wrong database after reconnection

### ISSUE THREAD

**Issue by jnackman** [luin/ioredis#42]
Using sentinel, unfulfilled commands are resent before the database has been reselected, causing them to run against the wrong database.  This is reproducible with the following code, killing the master before the command has completed:

```javascript
var Redis = require("ioredis");
var redis = new Redis({
    sentinels: [...],
    name: "mastername",
    db: 1
});

redis.blpop("some-absent-key", 30, function(){});
```

The output of MONITOR shows the following:

```
On master:
1432220467.655639 [0 xxx:39015] "info"
1432220467.659202 [0 xxx:39015] "select" "1"
1432220522.605756 [1 xxx:39015] "blpop" "some-absent-key" "30"

... master killed ...

On new master:
1432220532.258167 [0 xxx:60414] "info"
1432220532.258962 [0 xxx:60414] "blpop" "some-absent-key" "30"
1432220563.055939 [0 xxx:60414] "select" "1"
```

The unfulfilled BLPOP command is executed before the correct database is reselected.  Expected behavior is for the correct database to be selected before running the command.

The code responsible for this behavior appears to be in [`event_handler.js`](https://github.com/luin/ioredis/blob/master/lib/redis/event_handler.js#L102-131).  The correct database is selected for items in `offlineQueue` (when necessary), but not for items in `prevCommandQueue`.

**Comment by luin** [comment]
Released in 1.3.6
