### ISSUE TITLE
#Psubscribe pattern for keyspace-events notification Not working in Java cluster using redisLettuce

### ISSUE THREAD

**Issue by govind213** [luin/ioredis#421]
This is my subscriber Code :- 

String redisNodes = "redis://IP1:9014,redis://IP2:9006,redis://IP1:9006,redis://IP2:9014,redis://IP3:9006,redis://IP3:9015";
	String[] redisNodeStringArray = redisNodes.split(",");
	
	List<RedisURI> redisURIList = new ArrayList<RedisURI>();
   
	for(String redisMasterNodeString : redisNodeStringArray) {
		redisURIList.add(RedisURI.create(redisMasterNodeString));
	}
	
	RedisClusterClient redisClusterClient = RedisClusterClient.create(redisURIList);      
	StatefulRedisPubSubConnection<String, String> connection = redisClusterClient.connectPubSub();
	RedisPubSubAsyncCommands<String, String> async = connection.async();
	async.addListener(new RedisPubSubListener<String, String>() {
		@Override
		public void message(String s, String s2) {
			System.out.println("Message1: " + s + " : " + s2);
		}

		@Override
		public void message(String s, String k1, String s2) {
			System.out.println("Message: "+s+" Key Changed :" + s2 + " , Event : " + k1.split(":")[1] );
		}
         
		@Override
		public void psubscribed(String s, long l) {
			System.out.println("Subscriber");
		}

		@Override
		public void punsubscribed(String arg0, long arg1) {
			// TODO Auto-generated method stub
			
		}

		@Override
		public void subscribed(String arg0, long arg1) {
			// TODO Auto-generated method stub
			System.out.println("Message: Key Changed :" + arg0 + " , Event : " + arg1 );
			
		}

		@Override
		public void unsubscribed(String arg0, long arg1) {
			// TODO Auto-generated method stub
			
		}

	});
    async.psubscribe("__key*__:*");

_______________

This is my Publisher code 👎 

String redisMasterNodes = "redis://IP1:9014,redis://IP2:9006,redis://IP1:9006,redis://IP2:9014,redis://IP3:9006,redis://IP3:9015
";
    
    List<RedisURI> redisMasterURIList = new ArrayList<RedisURI>();
    String[] redisMasterNodeStringArray = redisMasterNodes.split(",");
	for(String redisMasterNodeString : redisMasterNodeStringArray) {
		redisMasterURIList.add(RedisURI.create(redisMasterNodeString));
	}
    
	RedisClusterClient redisMasterClusterClient = RedisClusterClient.create(redisMasterURIList);      
	RedisPubSubAsyncCommands<String, String> connection1 = redisMasterClusterClient.connectPubSub().async();
 
    int i = 0;
    while (i<4){
    	
    	String key = "#test"+new Integer(i).toString(); String value = new Integer(i).toString();
    	System.out.println("Sending data : Key - " + key + "value  - " + value);
    	
    	connection1.set(key,value);
    	
    	i++;
    	Thread.sleep(1000);
    }

I set "config set notify-keyspace-events KEA" on all nodes (Set events put data on __key*__:*  channel )
Here in RedisURIList contains 3 masters and 3 slaves. All nodes are connected to each other.
After running this code , publisher is able to set 2 keys in 1 master server and other 2 keys in other masters but notification is coming from one master only not from others.  Same thing happens when i am setting keys from redis client tool on respective master.

Can anyone please help me why I am not getting notifications from other masters.

Thanks

**Comment by luin** [comment]
This repo is the redis client for Node.js. Please refer to the lettuce repo.
