### ISSUE TITLE
hiredis

### ISSUE THREAD

**Issue by AdriVanHoudt** [luin/ioredis#422]
I saw that the readme suggests using hiredis for better perf but the node binding's version of hiredis is outdated (see https://github.com/redis/hiredis-node/issues/129) and v2 of the js parser seems to be up to speed as well (see https://github.com/luin/ioredis/issues/342) does it still make sense to recommend it?
I would suggest to keep it in the docs but if v2 of the node parser gets merged I see no reason to recommend it anymore.

**Comment by luin** [comment]
The v2 of the js parser had performance issues when parsing big chunk of data (https://github.com/NodeRedis/node_redis/pull/900#issuecomment-259638072) but it seems this problem has already been fixed. I'll do some benchmarks on it and will switch to it if the performance go better. At that time the recommendation will be definitely removed from the docs.

Thank you for bring this up!

**Comment by AdriVanHoudt** [comment]
@luin thanks for looking into this!

**Comment by luin** [comment]
Closing this since #425 has been merged.

**Comment by AdriVanHoudt** [comment]
Thanks a lot! @luin
