### ISSUE TITLE
Inexplicable Connectivity

### ISSUE THREAD

**Issue by moconchobhair** [luin/ioredis#426]
I have a server setup with three nodes, each running redis and sentinel. I can connect to the redis and sentinel instances using redis-cli, switching between them by changing the port number.  I can run commands to see keys, the client list, etc.

When using ioredis from our nodeJS project I can connect to redis nodes and run queries. However, when I use the sentinel port number it never responds.  No errors, it takes whatever get/set commands I send but never returns anything. If I set "enableOfflineQueue" to false I get back "Error: Stream isn't writeable and enableOfflineQueue options is false".  

So it appears to me I have a connectivity problem from code (but redis-cli works) but this is the only error message I've been able to coax out of it.  I also subscribed to the "connect", "ready" and "error" events but they never return when using the Sentinel address.

I've been poring through what info I can find for quite a while, would really appreciate any tips you might have on connectivity issues or just better error messages. I am new to redis, having learned what I know digging through code I inherited.  

thanks!

**Comment by luin** [comment]
Could you enable the debug mode `DEBUG=ioredis:* node yourapp.js` and post the logs here?

**Comment by luin** [comment]
I'm closing this. Feel free to reopen it with details.
