### ISSUE TITLE
Redis status

### ISSUE THREAD

**Issue by almoghaimo** [luin/ioredis#429]
I want to get error when I call the set / get methods and the redis status is not "ready" or "connect", 
Instead I get the error only in the event handler, but I can't catch it as part of my flow.

my work around is to wrap the set and get methods, and to check the redis status property and if it's not "ready" or "connect" I'm not trying to call the methods.

There is any problem to that by myself? why I'm not getting error by default?

**Comment by luin** [comment]
By default offline queue is enabled to keep the commands sent during disconnected. Disabling it should solve your problem.

**Comment by almoghaimo** [comment]
Thanks, that help :)
