### ISSUE TITLE
ZRANGEBYLEX usage

### ISSUE THREAD

**Issue by CaptaiNapalm** [luin/ioredis#430]
Hi :)

I am sorry to bother you, but I cannot figure how to use zrangebylex in ioredis.
I found the command using ioredis-command but I can't come around with the proper function call.

In my redis console I can input 
`zrangebylex _gpu [GTI "[GTI\xff"`

And get an array of results, how can I do this with your awesome lib ?

Where can I look to find every command available and their signature in ioredis ?

Thanks a lot for your time and your work!
Cheers :]

**Comment by luin** [comment]
Just pass the arguments correspondingly:

```
> redis-cli
zrangebylex myzset [aaa (g
```


```javascript
redis.zrangebylex('myzset', '[aaa', '(g')
```
