### ISSUE TITLE
[Cluster] Failed to refresh slots cache

### ISSUE THREAD

**Issue by PhillippOhlandt** [luin/ioredis#431]
Hey,

I am using [this](https://hub.docker.com/r/bitnami/redis/) docker image to setup my redis cluster. When I connect via a desktop client (Medis), everything is working fine.

When I try to connect [deepstream.io](http://deepstream.io) (which uses`ioredis`) to the cluster, I get the `Failed to refresh slots cache` error. I know there are other issues with the same error, but none of them provided a solution to solve this problem. The fact that I can connect via my desktop tool and not via `ioredis` is pretty weird.

**Comment by luin** [comment]
What's the `lastNodeError` property of the `Failed to refresh slots cache` error?

**Comment by PhillippOhlandt** [comment]
@luin 

```
deepstream_1         |   lastNodeError:
deepstream_1         |    { ReplyError: ERR This instance has cluster support disabled
deepstream_1         |        at JavascriptRedisParser.returnError (/var/lib/deepstream/deepstream.io-msg-redis/node_modules/ioredis/lib/redis/parser.js:24:25)
deepstream_1         |        at JavascriptRedisParser.execute (/var/lib/deepstream/deepstream.io-msg-redis/node_modules/redis-parser/lib/parser.js:558:12)
deepstream_1         |        at Socket.<anonymous> (/var/lib/deepstream/deepstream.io-msg-redis/node_modules/ioredis/lib/redis/event_handler.js:107:22)
deepstream_1         |        at emitOne (events.js:96:13)
deepstream_1         |        at Socket.emit (events.js:188:7)
deepstream_1         |        at readableAddChunk (_stream_readable.js:176:18)
deepstream_1         |        at Socket.Readable.push (_stream_readable.js:134:10)
deepstream_1         |        at TCP.onread (net.js:548:20)
deepstream_1         |      name: 'ReplyError',
deepstream_1         |      message: 'ERR This instance has cluster support disabled',
deepstream_1         |      command: { name: 'cluster', args: [Object] } } }
```

However, the cluster works fine. I already tried turning it on in the config of the master server, without any luck.

**Comment by luin** [comment]
Hmm...This error indicates cluster is disabled for the Redis server you connected to. Could you check again whether the `cluster-enabled` is enabled?

**Comment by PhillippOhlandt** [comment]
It was commented. I uncommented and now its value is `yes`.

I still get the same error but now the `lastNodeError` is:

```
deepstreamprivate_1  |   lastNodeError:
deepstreamprivate_1  |    Error: Connection is closed.
deepstreamprivate_1  |        at close (/var/lib/deepstream/deepstream.io-msg-redis/node_modules/ioredis/lib/redis/event_handler.js:101:21)
deepstreamprivate_1  |        at Socket.<anonymous> (/var/lib/deepstream/deepstream.io-msg-redis/node_modules/ioredis/lib/redis/event_handler.js:81:14)
deepstreamprivate_1  |        at Socket.g (events.js:291:16)
deepstreamprivate_1  |        at emitOne (events.js:96:13)
deepstreamprivate_1  |        at Socket.emit (events.js:188:7)
deepstreamprivate_1  |        at TCP._handle.close [as _onclose] (net.js:498:12) }
```

**Comment by PhillippOhlandt** [comment]
I set the log level to `debug` on the redis master. Seems like deepstream is connecting and disconnecting all the time:

```
34:M 13 Feb 11:46:33.629 - Accepted 172.23.0.7:46448
34:M 13 Feb 11:46:33.633 - Client closed connection
34:M 13 Feb 11:46:33.650 - Accepted 172.23.0.7:46452
34:M 13 Feb 11:46:33.652 - Client closed connection
34:M 13 Feb 11:46:33.830 - Accepted 172.23.0.7:46456
34:M 13 Feb 11:46:33.918 - Client closed connection
```

**Comment by luin** [comment]
The `Connection is closed` error means the node you connected to closed the connection for some reason (e.g. misconfigure of the cluster). Try to enable the debug mode `DEBUG=ioredis:* node yourapp.js` may show you the direction where the problem is.

**Comment by PhillippOhlandt** [comment]
Doesn't give me much more information. Deepstreams connector receives the error from `ioredis` and passes it to Deepstream, which then throws it. I also created an issue in the connector repo (linked below my initial post) with my connector configuration.

**Comment by PhillippOhlandt** [comment]
Side note: It just does it on the master redis. The slave redis doesn't even get a connection yet.

**Comment by PhillippOhlandt** [comment]
Hey @luin, I created a little demo to show the issue. You can find it here: https://github.com/PhillippOhlandt/deepstream-redis-cluster Maybe you can successful debug it.

**Comment by AVVS** [comment]
@PhillippOhlandt I might be missing something, but your example contains master/slave, which is not really a cluster. Use this https://github.com/makeomatic/docker-redis-cluster for pre-bootstrapped testing cluster if you want

**Comment by PhillippOhlandt** [comment]
Why is it not a cluster? Scale them up to 20 instances and you are fine. Your linked image is the same, except that it's not scalable and therefore not usable in production.

**Comment by AVVS** [comment]
mine isn't - just for testing. But I've noticed there is master+slave, but no script for distributing slots (which is what makes redis a cluster) and minimal setup is 3 masters. But I might be wrong and simply missed the boot script

**Comment by PhillippOhlandt** [comment]
The used image handles the roles on its own. And you can just scale the master service to 3. I don't see the problem. I just want to write to master and read from slaves.

**Comment by AVVS** [comment]
Well, thats the problem - you cant use ioredis cluster because it relies on slots and you simply dont have them. https://redis.io/topics/cluster-tutorial should have enough information. All you have is separate redis instances and their slaves

**Comment by PhillippOhlandt** [comment]
The problem is, there aren't any examples or tutorials on a proper docker setup for redis. The best image I found is the one I use. I would like to scale redis with the built in docker tools (scaling a service) but that doesn't seem to work.

**Comment by AVVS** [comment]
yeah, well, not going to happen until v4 redis cluster at least, because of a) redis cluster doesnt support docker yet (unless you do host networking) b) doesnt autoscale either

**Comment by PhillippOhlandt** [comment]
Do you know if there is a planned release date? This is a big blocker for us because we don't want to go with a single redis instance online.

**Comment by AVVS** [comment]
use sentinel, 1 master + slaves + automatic failover. Works just fine - you still can scale reads, and if need be you can have multiple sentinel groups for manual write splitting, which you were aiming to do anyway

**Comment by PhillippOhlandt** [comment]
Does that work with docker? Do you have a example setup?
