### ISSUE TITLE
actions in a promise emit unhandled errors

### ISSUE THREAD

**Issue by jayjanssen** [luin/ioredis#433]
```
client = (require 'ioredis') 'redis:/127.0.0.1:6379/0', {
	connectTimeout: 1000
	lazyConnect: true
	retryStrategy: () -> false
	reconnectOnError: (err) -> false
}

client.get 'key'
.then (value) ->
	console.log value
.catch (err) ->
	console.error "Caught error where I expect it"
	console.error err.message
```

My output is:

```
[ioredis] Unhandled error event: Error: connect ENOENT /127.0.0.1:6379/0
  at Object.exports._errnoException (util.js:1023:11)
  at exports._exceptionWithHostPort (util.js:1046:20)
  at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)

Caught error where I expect it
Connection is closed.
```

How can I avoid the Unhandled error event?

**Comment by luin** [comment]
"error" event is emitted when the connection is failed. The best practice is to handle the error explicitly, for instance:

```javascript
redis.on('error', error => {
  logServer.send('redis connection error', error)
  // reconnect or simply exit the application
})
```

By this way, ioredis won't log "Unhandled error event".

**Comment by jayjanssen** [comment]
Thanks for the reply.  What about this:

```
client = (require 'ioredis') 'redis://127.0.0.1:6379/0', {
	connectTimeout: 1000
	lazyConnect: true
	retryStrategy: () -> false
	reconnectOnError: (err) -> false
}

client.on 'error', (err) ->
	console.error "Event emitter: #{err.message}"

client.get 'key'
.then (value) ->
	console.log value
.catch (err) ->
	console.error "Promise error catch: #{err.message}"
.delay 1000, () ->
	client.get 'key2'
.then (value) ->
	console.log 'Promise2 then'
.catch (err) ->
	console.error "Promise2 error catch: #{err.message}"
```

Output:
```
Event emitter: connect ECONNREFUSED 127.0.0.1:6379
Promise error catch: Connection is closed.
Promise2 then
```

If I do the same thing without the delay, I do get the Promise 2 error properly.

**Comment by luin** [comment]
It's not an ioredis related issue. `Promise#delay` only receives one parameter. Refer to http://bluebirdjs.com/docs/api/promise.delay.html for details.

**Comment by jayjanssen** [comment]
Ah, sorry.  I'm not trying to be a pain, I was just seeing some issues in a more complex piece of code that I couldn't pin down.  I'm going to try again to adopt that code to ioredis and see if I can get it working and/or find something a little better to report.  Sorry for the noise.

**Comment by jayjanssen** [comment]
Ok, I'm struggling a bit with retries.  What I want is for ioredis to try to reconnect on a down redis server on every operation, but not get blocked by retries.  I've been playing with retryStrategy and reconnectionOnError, but to no avail.  The specific use case is for the second 'client.get' to reconnect and work if I bring the redis server up during the delay:

```
client = (require 'ioredis') 'redis://127.0.0.1:6379/0', {
	connectTimeout: 1000
	lazyConnect: true
	retryStrategy: (t) -> false
	reconnectOnError: (err) -> true
}

client.on 'error', (err) ->
	console.error "Event emitter: #{err.message}"

client.get 'key'
.then (value) ->
	console.log value
.catch (err) ->
	console.error "Promise error catch: #{err.message}"
.delay 10000
.then () ->
	client.get 'key2'
.then (value) ->
	console.log 'Promise2 then'
.catch (err) ->
	console.error "Promise2 error catch: #{err.message}"
```

I'm getting:

```
Event emitter: connect ECONNREFUSED 127.0.0.1:6379
Promise error catch: Connection is closed.
### Redis comes up here ###
Promise2 error catch: Connection is closed.
```

Is there a set of ioredis options that will produce this?  Or, should I be using something like a Promise disposer instead?

**Comment by luin** [comment]
Nope. Reconnecting when invoking commands is not supported, though you can write a wrapper for that. I recommend using the `retryStrategy` option for reconnecting.

**Comment by jayjanssen** [comment]
All my attempts at playing with retryStrategy seem to block the app until the retries are done.  I'm fine with a background retry, but I need the workflow to continue.  In that case, it seems my only option is to use disposable connections.

**Comment by luin** [comment]
Or only allow limited reconnecting attempts, and reconnect on disconnected:

```javascript
const redis = new Redis({
  retryStrategy(attempts) {
    if (attempts < 3) {
      return 100
    }
    // otherwise just disconnect from the server to let all the error handlers
    // of commands get involved. 
  }
})

redis.on('end', () => {
  redis.connect()
})
```
