### ISSUE TITLE
Race condition when multiple requests hit the same worker at the same time

### ISSUE THREAD

**Issue by marvel308** [luin/ioredis#435]
Given a situation when multiple requests hit the same worker at the same time, a race condition is reached and the results of the multiple requests are overlapped, generally each request gives the same output, each request performs a multi exec operation

**Comment by tuananh** [comment]
@marvel308 maybe you can use something like redlock (so you don't have to introduce sth new to the stack). each request upon writing to redis must require lock beforehand.

**Comment by luin** [comment]
@marvel308 Could you provide your code to reproduce the issue?

**Comment by luin** [comment]
I'm closing this. Feel free to reopen it with details.
