### ISSUE TITLE
Question - single instance of Redis for an app?

### ISSUE THREAD

**Issue by agmcleod** [luin/ioredis#436]
I've been trying to debug a 504 issue on one of the endpoints of an app I'm working on. While I haven't found any evidence of the fact, I wonder if having a Redis instance setup in this manner would be a problem:

```
// lib/redis.js

var Redis = require('ioredis')
var config = require('config')
var prefix = config.get('redis.prefix')
var host = config.get('redis.host')
var log = require('./logger')('lib/redis')

var redisConfig = {}

if (prefix) redisConfig.keyPrefix = prefix

redisConfig.host = host

var redis = new Redis(redisConfig)

redis.on('error', function (err) {
  log.error({ op: 'redisError', err: err })
  throw new Error('Unable to connect to Redis host: ' + err.hostname)
})

module.exports = redis
```

I then require that file, and use it for doing reads and writes throughout the app.

```
var redis = require('lib/redis')

function foo() {
  return redis.get('thing')
}
```

In the operation that's timing out, I happen to do a read & write to compare a date, and store the larger date back in redis. This logic succeeds, as i can check redis via cli and see the value updated. Though I wonder if the promise isn't coming back, and it's causing a timeout. I'd like to use the ioredis debug env variable, but i've only seen this issue happen in a prod, and it's a bit intermittent.

**Comment by luin** [comment]
Using a single instance of Redis for an app is the recommend way (instead of creating a new instance for each request/operation). Multiple operations can be invoked at the same time without any problem.

**Comment by agmcleod** [comment]
@luin i figured as much, just wanted to confirm :). Thanks a bunch, and sorry for flooding your inbox!
