### ISSUE TITLE
Could this be a bug?

### ISSUE THREAD

**Issue by efkan** [luin/ioredis#437]
[These lines](https://github.com/luin/ioredis/blob/b216e4eb61d05ff639b162f23751acb111dde6e8/lib/transaction.js#L39-L43) consist of the following code:

          for (var i = 0; i < result.length - 1; ++i) {
            if (result[i][0]) {
              execResult[0].previousErrors.push(result[i][0]);
            }
          }

Really I don't know the logic of this code. I just want to point it out even so I think there should be a valid reason for the code.

If `result.length` is 10, the for loop turns only 9 times.

If it is wanted for loop turns 10 times then the line of for loop might be changed as follows:

          for (var i = 0; i < result.length; ++i) {

**Comment by luin** [comment]
The last element is the result of the pipeline itself.
