### ISSUE TITLE
Master | Slave | Sentinel - Ambigous problem

### ISSUE THREAD

**Issue by migounette** [luin/ioredis#440]
io-redis version 2.5.0

When we use the sentinel option, we have a callback indicating that we are connected to the master (if success).

Question #1:
I am trying to get information on the master, I would like to be sure that we can safely use the this.serverInformation object from this returned when the callback is returned. 
I didn't find any information mentioning it.

Question #2:
How can I get the master/slave list or execute a sentinel command, the object returned is the redis server not the sentinel connection ? do I am right ?

var redis = new Redis({
  sentinels: [{ host: 'localhost', port: 26379 }, { host: 'localhost', port: 26380 }],
  name: 'mymaster'
});

I would like to execute some commands to the active sentinel selected (26379 or 26380)

SENTINEL get-master-addr-by-name redis-site-one
1) "w.x.y.z"
2) "6382"

Based on your answer I will update the wiki and the example section.

Thanks

**Comment by luin** [comment]
A1:
Where's `this.serverInformation`? I searched the whole repo but didn't find the property.

A2:
You can't currently. ioredis will disconnected with the active sentinel when the master/slave address has been resolved.

**Comment by migounette** [comment]
@luin Thanks for this quick reply:

Eg. 
    var redisCnx = new Redis({
        'sentinels': [ { 'host': redisInfo.hostname, 'port': redisInfo.port } ],
        'name': config.master
    });

    redisCnx.on('ready', function() {
      this.serverInfo.xxxx
    }

![io-redis-dump](https://cloud.githubusercontent.com/assets/1232978/24044131/35cc527a-0b1a-11e7-9fb9-eac4f51f4b3f.png)

This structure is certainly a return of INFO method from redis.

A2: In fact I am trying to identify the master IP and port, I looked at the code and I found that you already use get-master-addr-by-name, what about returning the information from the connected callback ?

    redisCnx.on('ready', function(server) { 
      if (server !== undefined) {
           _self.logger.info(server.ip + ':' + server.port);
      }
   }

Just let me know I can create a PR if you agree.

My 2 cents
