### ISSUE TITLE
Representing Amazon ElasticCache (no cluster)

### ISSUE THREAD

**Issue by sanket-naik-zocdoc** [luin/ioredis#447]
I have AWS ElasticCache Redis (no cluster) with replications. I have an application that needs to connect only to slaves for reads and scale reads across the multiple slaves.
I read through your API and it seems to me that I should list all slaves as sentinels and specify role as slave? I couldn't figure out how to scale reads across slaves; is this supported?

```
var redis = new Redis({
  sentinels: [{ host: '127.0.0.1', port: 26379 }, { host: '127.0.0.1', port: 26380 }],
  name: 'mymaster',
  role: 'slave',
 readOnly: true
});
```

**Comment by sanket-naik-zocdoc** [comment]
I don't understand how `name` is used here.
Also, what does this line do? https://github.com/luin/ioredis/blob/master/lib/connectors/sentinel_connector.js#L135
I couldn't find definition of method 'sentinel'

**Comment by luin** [comment]
Sentinel is a high availability solution for Redis. ioredis supports read-scales by leveraging the features that provided by sentinel. Refer to https://redis.io/topics/sentinel for details.

It seems Amazon Elasticache Redis doesn't use sentinel in their replication implementation, so in this case ioredis can't scale reads since there's no official interface offered by AWS for fetching the list of slaves.

**Comment by sanket-naik-zocdoc** [comment]
@luin thanks for the details. One last question before I close this issue; is there a way to use any of the existing api in ioredis to scale reads if I can provide list of slaves (AWS replications)?

**Comment by luin** [comment]
No, there's no built-in way for this. However, it's possible for you to create multiple connections to your replication (each for a slave), and route the queries to random connections. For example:

```javascript
const slaves = [
  new Redis(/**/),
  new Redis(/**/),
  new Redis(/**/)
]

import {sample} from 'lodash'
sample(slaves).get('foo')
```

**Comment by sanket-naik-zocdoc** [comment]
That is a really good alternative.. thanks for the suggestion!  
I would close this issue
