### ISSUE TITLE
SINTER support?

### ISSUE THREAD

**Issue by zbmowrey** [luin/ioredis#448]
Does ioredis support the SINTER command? 

I tried 
`Redis.sinter(key1,key2).then(....`

and it returns [].

In redis-cli, doing `sinter key1 key2` returns a value to me. Does the client support this command? I can't find any documentation of this command in this github or on the web in general that relate specifically to ioredis. Maybe there's a syntax or command issue I'm missing?

**Comment by luin** [comment]
Hi @zbmowrey, the usage above of `sinter` is correct. Could you confirm you connected to the same Redis instance as redis-cli? Try to run `monitor` command in the redis-cli and run the code again to see whether the command and arguments sent to Redis are correct.

**Comment by zbmowrey** [comment]
Closing issue - I was trying to access the Promise object rather than the value. Thanks for the response, the tip to check 'monitor' is something I won't soon forget! :)
