### ISSUE TITLE
Use of console.error

### ISSUE THREAD

**Issue by ty10r** [luin/ioredis#449]
In `Redis.prototype.connect`, if I haven't set a `.on('error', ...)` listener myself while expecting a connection timeout (I'm testing), I am seeing a `console.error` call. [The lines causing this are here](https://github.com/luin/ioredis/blob/master/lib/redis.js#L289-L293)

Is the call to `console.error` meant to signify a bug in `ioredis`? If it is not meant to call out a bug in the package, shouldn't it be done in the DEBUG module?

Using `console` logging directly is a bad decision. Anything outside of debug logging should be decided by consumers of the package. 

I think:
- If this was not intended to be seen by consumers of ioredis, then error handling for the case of ETIMEDOUT should be fixed.

- If this was intended to be seen by consumers of ioredis, `debug` should be used.

Let me know what you think and I might be able to send a PR if we decide something should be done.

**Comment by luin** [comment]
Hi @ty10r, thank you for bringing this up.

Typically an "error" event in Node.js crashes the current process if there's no listener attaching on it. However, when comes to the production environment, crashing the whole application in the case of network issues definitely to be a bad default behavior.

Instead, by default we `console.error` errors to let developers know they should handle the "error" events explicitly (logging errors to databases or their log centers).

**Comment by luin** [comment]
I'm closing this. Feel free to reopen it for further questions.
