### ISSUE TITLE
Is it async to get keys?

### ISSUE THREAD

**Issue by cmhsu-cs** [luin/ioredis#450]
I have a redis database with 11 million rows. In my server, I want to load this data into memory. Would this be a blocking operation? I don't want to block the main node.js event loop.

**Comment by luin** [comment]
@cmhsu-cs 11 million rows may consume large memory (GC getting involved) and require CPU for parsing them. It pretty depends on what data does each row has, so just try with your own data.

**Comment by cmhsu-cs** [comment]
@luin Got it. If I were to get all the values of a redis sorted set (11 million values) and 11 million hashes, would the operation be async? Meaning would it block or not block the main event loop for my Node.js server?

**Comment by luin** [comment]
All IO operations are async (won't block the main event loop), while the parsing process happens on the main event loop.

**Comment by cmhsu-cs** [comment]
@luin Sorry what do you mean by the parsing process?

**Comment by luin** [comment]
@cmhsu-cs  Parsing replies to JavaScript data structures.
