### ISSUE TITLE
How to increase lua script time?

### ISSUE THREAD

**Issue by cmhsu-cs** [luin/ioredis#454]
According to the redis doc, the default time is 5 seconds. Is there any way to increase this? 

"It is possible to modify the maximum time a script can be executed with millisecond precision, either via redis.conf or using the CONFIG GET / CONFIG SET command. The configuration parameter affecting max execution time is called lua-time-limit."

Thanks!

**Comment by luin** [comment]
Didn't the quoted documentation answer the question?
