### ISSUE TITLE
从node_redis迁移至ioredis的请教

### ISSUE THREAD

**Issue by mopduan** [luin/ioredis#459]
正考虑从node_redis迁移到ioredis请教两个问题：

（1） 使用ioredis执行完set、get命令后，是否需要显式调用quit结束当前连接？如果不需要的话，那么ioredis是否是使用了连接池？

（2） node_redis是否使用了连接池？

谢谢！

**Comment by luin** [comment]
1. Redis 是单进程服务器，所以 ioredis 没有使用连接池。执行完命令后无需 QUIT，进程退出时会自动释放。
2. 没有使用

**Comment by mopduan** [comment]
再请教下，也就是说node_redis也无需显式使用quit？

谢谢！

**Comment by luin** [comment]
是的，都一样

**Comment by mopduan** [comment]
多谢！
