### ISSUE TITLE
error handle in specific command

### ISSUE THREAD

**Issue by sophister** [luin/ioredis#465]
when redis is down, how can I handle this error in specific command, such as:

```javascript
client.set(name, value).then().catch( function(err){
    //can I handle disconnect error here??
});
```
my problem is, when redis is down, previous code **will not** trigger `catch` callback, and my server hangs ...

**Comment by luin** [comment]
You may want to disable `retryStrategy` if it's required to make every command be aware of the server's offline.

**Comment by sophister** [comment]
@luin  thx! BTW, when ioredis stops reconnecting according to `retryStrategy`, how can I make it retry again after some time when redis is up? Manually restart server is not cool you know, :)

**Comment by luin** [comment]
Calling `redis.connect()` when the server is ready.

**Comment by sophister** [comment]
Got it, thx!
