### ISSUE TITLE
question on multiple databases

### ISSUE THREAD

**Issue by jamesdixon** [luin/ioredis#466]
Hi, I have a globally available instance of the ioredis client available to my app. I recently added another redis database that stores different data. Would you recommend that I create two separate clients to handle operations on different databases rather than using `select()`?

Thanks!

**Comment by luin** [comment]
I would recommend you create two separate clients each connect to a different database instead of using `select` to avoid potential conflictions.

**Comment by jamesdixon** [comment]
Thank you!
