### ISSUE TITLE
ArgumentTransformer for zadd

### ISSUE THREAD

**Issue by taichunmin** [luin/ioredis#468]
Doc for zadd: https://redis.io/commands/zadd

Hello,
The zadd command can accept endless `score member [score member ...]`. May I have a default ArgumentTransformer for zadd? I can create a PR for that.

My code:
```js
function convertFilpObjectToArray (obj) {
  var result = []
  for (var key in obj) {
    result.push(obj[key], key)
  }
  return result
}

Redis.Command.setArgumentTransformer('zadd', args => {
  if (args.length > 1) {
    let last = args.pop()
    if (typeof last === 'object' && last !== null) {
      args.concat(convertFilpObjectToArray(last))
    } else args.push(last)
  }
  return args
})
```

**Comment by luin** [comment]
It's a little confused whether `score` should be the key or the value of an object (at least more confused than `mset` for a hash key).

Since ioredis flattens arguments, the following form is supported:

```javascript
redis.zadd('key', [17, 'a'], [18, 'b'], [19, 'c'])
```

Given that I don't think the transformer is necessary.

**Comment by taichunmin** [comment]
Score can be duplicate, but member should be unique. So score must be value, member should be key.
A real use case is sortin score in a game. Every player will have a score, but some people may have the same score (and have same rank).

**Comment by luin** [comment]
I'm aware of this fact. It's just not straightforward compared with the transformer of `hmset` for the hash key, which itself is an object.

Anyway, I'd like to accept a PR for that, as long as the transformer keeps the same format with `hmset` that only takes effect when the argument length is 2 and supports both Map and plain object.

**Comment by taichunmin** [comment]
I'd like to write PR, but I still have some question:

1. zadd not only have 2 argument, so may I only check the last args?
```js
ZADD key [NX|XX] [CH] [INCR] score member [score member ...]
```
2. Order in plain object is obvious, But I have no idea which order is better in Map:
  * `myMap.set("member", "score");`
  * `myMap.set("score", "member");`

**Comment by yunnysunny** [comment]
If you want to add multi data to a sorted set, you may write such code:
```javascript
const len = 5;//The length may be the count of some records getten from some db
const originalData = [
{score:1,value:'a'},
{score:2,value:'x'},
{score:3,value:'f'},
{score:4,value:'e'},
{score:5,value:'j'},
];

var params = new Array(len+2);
params[0] = 'a_sorted_redis_key';
var i = 1;
for (var item of originalData ) {
    params[i++] = [item.score,item.value];
}
params[i] = function(err) {
    console.log(err);
}
redis.zadd.apply(redis,params);
```
