### ISSUE TITLE
wrong result with  cluster.nodes("master")

### ISSUE THREAD

**Issue by weconquered** [luin/ioredis#471]
my code as below:
`var Redis = require('ioredis');
var cluster = new Redis.Cluster([{
    port: 6379,
    host: '192.168.30.91'
}, {
    port: 6379,
    host: '192.168.30.92'
},{
    port: 6379,
    host: '192.168.30.93'
},{
    port: 6379,
    host: '192.168.30.94'
},{
    port: 6379,
    host: '192.168.30.97'
},{
    port: 6379,
    host: '192.168.30.98'
}
]);

console.log(cluster.nodes("master").length)`

the result is  6.
however i get the result by :   cluster nodes .  there are 3 master and 3 slave

192.168.30.92:6379 myself,master - 0 0 41 connected 5461-10922
 192.168.30.93:6379 slave 7326b8056677fa6121e205074a71a581df72052c 0 1495801814808 29 connected
 192.168.30.98:6379 master - 0 1495801816817 29 connected 0-5460
 192.168.30.94:6379 master - 0 1495801817820 42 connected 10923-16383
 192.168.30.91:6379 slave 7e9a018015678699ecba3d8d89b3d4ccfdb1fc53 0 1495801811795 42 connected
 192.168.30.97:6379 slave 33c352babcb9795381fb877376760ca46e07105e 0 1495801815812 41 connected

**Comment by luin** [comment]
What did you get when executing `cluster slots` with redis-cli?

**Comment by weconquered** [comment]
1) 1) (integer) 5461
   2) (integer) 10922
   3) 1) "192.168.30.92"
      2) (integer) 6379
      3) "33c352babcb9795381fb877376760ca46e07105e"
   4) 1) "192.168.30.97"
      2) (integer) 6379
      3) "bdcb1b5d60d5a72bdfac947cedbbea93ac53f125"
2) 1) (integer) 0
   2) (integer) 5460
   3) 1) "192.168.30.98"
      2) (integer) 6379
      3) "7326b8056677fa6121e205074a71a581df72052c"
   4) 1) "192.168.30.93"
      2) (integer) 6379
      3) "f952594ea555482cd42f944572c520ffb29fc773"
3) 1) (integer) 10923
   2) (integer) 16383
   3) 1) "192.168.30.94"
      2) (integer) 6379
      3) "7e9a018015678699ecba3d8d89b3d4ccfdb1fc53"
   4) 1) "192.168.30.91"
      2) (integer) 6379
      3) "4990051c2e6f55484e07e8493cd9c5d67283f4ab"

**Comment by luin** [comment]
Try getting masters after the `ready` event:

```javascript
var cluster = new Redis.Cluster(/*...*/)
cluster.on('ready', function () {
  console.log(cluster.nodes("master").length)
})
```

**Comment by weconquered** [comment]
thank you , it's ok as you say.
