### ISSUE TITLE
Failed to refresh slots cache

### ISSUE THREAD

**Issue by damianhodgkiss** [luin/ioredis#474]
yep, have read the other issues.. we are using AWS redis CLUSTER and it does work fine after the initial attempts.. our issue is we are seeing Failed to refresh slots cache the first time our scripts run because of a low timeout (we are connecting to multiple redis stores for different purposes which may be contributing to needing a slightly higher timeout)

https://github.com/luin/ioredis/blob/master/lib/cluster/index.js#L585-L612

the slots command being issued has a hardcoded 1,000ms timeout which doesn't seem to be enough in some cases.  Modifying the timeout in node_modules... to 10,000ms rids the error but doesn't work for our deployment scenario unless we fork the module so just wondering if we can get a config variable for this timeout?

**Comment by shaharmor** [comment]
Sound reasonable. Care to make a PR?

**Comment by damianhodgkiss** [comment]
can do.. any preferences what you'd like the option called so it keeps with your option naming?  else maybe just connectTimeout (on the main cluster config/options)

**Comment by shaharmor** [comment]
`slotsRefreshTimeout` should be good. @luin ?

**Comment by luin** [comment]
@shaharmor Sounds good to me.

**Comment by luin** [comment]
Released with v3.1.0 🍻
