### ISSUE TITLE
[Question] Can I use pipeline with lua script (defineCommand)?

### ISSUE THREAD

**Issue by tuananh** [luin/ioredis#476]
Is it possible to use pipeline with custom lua script?

```
var redis = new Redis();

// This will define a command echo:
redis.defineCommand('echo', {
  numberOfKeys: 2,
  lua: 'return {KEYS[1],KEYS[2],ARGV[1],ARGV[2]}'
});

// Now `echo` can be used just like any other ordinary command,
// and ioredis will try to use `EVALSHA` internally when possible for better performance.
redis.echo('k1', 'k2', 'a1', 'a2', function (err, result) {
  // result === ['k1', 'k2', 'a1', 'a2']
});
```

**Comment by luin** [comment]
Yes, custom commands are supported to be sent within pipelines. See https://github.com/luin/ioredis/blob/master/test/functional/pipeline.js#L103 for details.

**Comment by tuananh** [comment]
Thank you.

**Comment by MichelDiz** [comment]
Is there any documentation that I can put together a test of this feature?
Do I have to do a Lua Script?
`Unhandled rejection ReplyError: ERR unknown command 'GRAPH.CREATENODE'`

**Comment by bradennapier** [comment]
This does not appear to work with multi?  My custom command is returning a promise and executing things.
