### ISSUE TITLE
[suggestion] use docker to isolate tests + redis

### ISSUE THREAD

**Issue by transitive-bullshit** [luin/ioredis#479]
It's dangerous to require connecting unit tests to an external redis instance, as it breaks encapsulation and would be fairly easy to accidentally overwrite important data.

Docker allows for a safer, isolated test environment and would even allow you to run all unit tests against multiple versions of redis if desired.

For a drop-in example of what this might look like, check out my work on [id-shortener](https://github.com/fisch0920/id-shortener) which runs all tests and redis itself via docker-compose (specifically the [scripts](https://github.com/fisch0920/id-shortener/tree/master/scripts) directory).

I would be happy to work on a related PR if there's interest in this direction.

As an aside, I love ioredis and use it every day ✌️

**Comment by luin** [comment]
Sounds good! A PR is welcome.
