### ISSUE TITLE
[suggestion] Standard coding style

### ISSUE THREAD

**Issue by taichunmin** [luin/ioredis#481]
How about apply the Standard coding style to this project?
There are auto fix tool to use.

https://github.com/feross/standard

# The Rules

* 2 spaces – for indentation
* Single quotes for strings – except to avoid escaping
* No unused variables – this one catches tons of bugs!
* No semicolons – It's fine. Really!
* Never start a line with (, [, or `
  * This is the only gotcha with omitting semicolons – automatically checked for you!
  * [More details](https://github.com/feross/standard/blob/master/RULES.md#semicolons)
* Space after keywords if (condition) { ... }
* Space after function name function name (arg) { ... }
* Always use === instead of == – but obj == null is allowed to check * null || undefined.
* Always handle the node.js err function parameter
* Always prefix browser globals with window – except document and navigator are okay
  * Prevents accidental use of poorly-named browser globals like open, length, event, and name.

**Comment by tuananh** [comment]
What's the issue with eslint?

**Comment by taichunmin** [comment]
I only compare the stars on there Github Repo.
https://github.com/eslint/eslint - 7778 stars
https://github.com/feross/standard - 11979 stars

**Comment by nesukun** [comment]
Not trying to start anything, but if the measure of a package's worth is by popularity:
https://www.npmjs.com/package/eslint
```
Stats
101,063 downloads in the last day
1,551,452 downloads in the last week
6,284,460 downloads in the last month
```
https://www.npmjs.com/package/standard
```
Stats
9,973 downloads in the last day
80,024 downloads in the last week
357,807 downloads in the last month
```
Code style will always be a touchy subject. If the mantainers are happy with the current solution and is also the most commonly accepted one I don't see a compelling reason to change. (Disclaimer, I don't use either currently)

**Comment by SimenB** [comment]
Standard uses eslint under the hood.

I'd suggest doing `eslint:recommended` and (prettier)[https://github.com/prettier/prettier]

**Comment by andros705** [comment]
I personally prefer standard, it's more strict but I am not working on this project :man_facepalming:
