### ISSUE TITLE
getting number of active subscribers

### ISSUE THREAD

**Issue by jehy** [luin/ioredis#483]
Hi! I am a bit stuck on getting a number of active subscribers to channel. It should be possible with [`PUBSUB NUMSUB [channel]` ](https://redis.io/commands/pubsub)but I can't find interface for this in ioredis :(

**Comment by luin** [comment]
redis.pubsub('NUMSUB', channelName)

Get Outlook for iOS<https://aka.ms/o0ukef>
_____________________________

**Comment by jeotte** [comment]
This seems to be missing from the typescript interface

**Comment by Rush** [comment]
Indeed. I just found this issue.
