### ISSUE TITLE
[Cluster] one question for Cluster#nodes()

### ISSUE THREAD

**Issue by joze2016** [luin/ioredis#484]
My cluster info as below:
master 1: 127.0.0.1:7001
master 2: 127.0.0.1:7002
master 3: 127.0.0.1:7003
slave 1: 127.0.0.1:7004
slave 2: 127.0.0.1:7005
slave 3: 127.0.0.1:7006

I create cluster as below:
var cluster = new Redis.Cluster([{
  port: 7001,
  host: '127.0.0.1'
}, {
  port: 7002,
  host: '127.0.0.1'
}, {
  port: 7003,
  host: '127.0.0.1'
}, {
  port: 7004,
  host: '127.0.0.1'
}, {
  port: 7005,
  host: '127.0.0.1'
}, {
  port: 7006,
  host: '127.0.0.1'
}]);

Result of cluster.nodes() as below:
cluster.nodes("all")  // return 6 array
cluster.nodes("master")  // return 6 array
cluster.nodes("slave")  // return 0 array

The nodes() can't discern master and slave. This cause I can't get all master node keys. Is this a issue of Cluster#nodes()?

**Comment by luin** [comment]
ioredis fetches the role of nodes asynchronously and will emit "ready" when successful. So `Cluster#nodes()` may not return the correct roles if called before the "ready" event.

**Comment by joze2016** [comment]
Yes, you're right, thanks.
