### ISSUE TITLE
ReplyError: ERR SELECT is not allowed in cluster mode

### ISSUE THREAD

**Issue by vdixit14** [luin/ioredis#485]
Seeing SELECT not allowed in cluster mode every time we connect to Redis.
Exact Error Seen
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
ReplyError: ERR SELECT is not allowed in cluster mode
    at JavascriptRedisParser.replyParser.Parser.returnError (/opt/app/node_modules/ioredis/lib/redis/parser.js:25:25)
    at JavascriptRedisParser.execute (/opt/app/node_modules/ioredis/node_modules/redis-parser/lib/parser.js:572:12)
    at Socket.<anonymous> (/opt/app/node_modules/ioredis/lib/redis/event_handler.js:107:22)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:540:20)

**Comment by luin** [comment]
Did you invoke SELECT command or set the "db" option explicitly?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by vdixit14** [comment]
Hi, No we are not invoking SELECT or setting DB option explicitly. We are using 3.1.1. Pastebin of our cache code https://pastebin.com/g4MbNXEk

**Comment by luin** [comment]
Thank you for the report! Could you please enable the `showFriendlyErrorStack` option so we can see where the `SELECT` command is sent via error stack?

Here's the example code:

```javascript
new Redis.Cluster(yournodes, {
  redisOptions: {
    showFriendlyErrorStack: true
  }
})
```

**Comment by vdixit14** [comment]
The error message shared in the first comment is with "showFriendlyErrorStack" enabled. I had manually enabled and got the same message.
Exact Error Seen
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
ReplyError: ERR SELECT is not allowed in cluster mode
at JavascriptRedisParser.replyParser.Parser.returnError (/opt/app/node_modules/ioredis/lib/redis/parser.js:25:25)
at JavascriptRedisParser.execute (/opt/app/node_modules/ioredis/node_modules/redis-parser/lib/parser.js:572:12)
at Socket. (/opt/app/node_modules/ioredis/lib/redis/event_handler.js:107:22)
at Socket.emit (events.js:107:17)
at readableAddChunk (_stream_readable.js:163:16)
at Socket.Readable.push (_stream_readable.js:126:10)
at TCP.onread (net.js:540:20)

**Comment by luin** [comment]
That's strange. Are you running other Redis instances at the same time causing the error? Anyway, I'll use the code you provided and try to reproduce the problem.

**Comment by vdixit14** [comment]
We checked and no other Redis instance is running. Will wait for your feedback from code review.

**Comment by luin** [comment]
@vdixit14 I did some trivial modifies on your code to use multiple redis instances in the same host: https://gist.github.com/luin/69d40a36c7466793c934172382e04ea9. I used https://github.com/Grokzen/docker-redis-cluster for running six cluster nodes and here's the output I got:

```
Redis host: 127.0.0.1 port: 7000
Redis host: 127.0.0.1 port: 7001
Redis host: 127.0.0.1 port: 7002
Redis host: 127.0.0.1 port: 7003
Redis host: 127.0.0.1 port: 7004
Redis host: 127.0.0.1 port: 7005
Using redis cluster connection with 6 nodes
Redis is ready to work hard!
```

I didn't see any error in my setup. Do I miss something?

**Comment by Angus-Accedo** [comment]
Hi luin

I'm a friend of vdixit14.

We would like to use a Master/Read Replica set for a test on its ability to handle large scale loads.

We can see that the documentation focuses mainly on the configuration parameters (eg ScaleReads)  for the Single and Cluster scenarios.

Could you confirm the configuration requirements when targeting a  Read Replica set ?


thanks.

**Comment by luin** [comment]
Read/Write scaling is only supported in the Cluster mode. However, you may use sentinels options for the failover support of a Sentinel setup.

**Comment by omi07** [comment]
source : redis_version:6.0.13
target: redis_version:7.0.3

./bin/redis-shake redis-shake.toml
redisWriter received error. error=[**ERR SELECT is not allowed in cluster mode**]
