### ISSUE TITLE
spop get null second time

### ISSUE THREAD

**Issue by JohnLou** [luin/ioredis#488]
In my case, single server, single client. Nesting function call spop to get item from set. It's run well in the first time, but gets null nexts.
Get arguments:
{ '0': null, '1': null }. 

the connect is:
`
_ioredis = new Redis({
      port: config.ioreids_port,
      host: config.ioredis_host,
      family: 4,
      password: config.ioredis_auth,
      db: 3,
});
`
How can I troubleshoot the problem?

**Comment by luin** [comment]
You may try running the `MONITOR` command on a redis-cli to see whether the commands sent to the Redis server are correct.

**Comment by JohnLou** [comment]
@luin 
OK, I get it. It's a mistake in my program. 
Thanks!
