### ISSUE TITLE
Batch of Cluster.sets Not Completing Before Lambda Ends

### ISSUE THREAD

**Issue by gheidorn** [luin/ioredis#489]
I have an AWS Lambda writing 100 key-value pairs to an AWS Elasticache cluster.  I am using the async.map to perform 100 cluster.set calls.  The code runs as expected but only 5-12 keys make it into the cluster (2 nodes).

```
async.map(records, function(record, next) {
  cluster.set(record.key, record.value, 'EX', expiry);
  i++;
  next(false, record);
}, 
function(err, results) {
  if(err) {
    console.log(err);
    callback(err, 'cached update failed for ' + records.length + ' records');
  } else {
    console.log(results.length);
    callback(null, 'cached updated for ' + records.length + ' records');
  }
});
```

Is there a feature I am missing that will let me test if the sets are complete/successful before I allow the Lambda to complete?

**Comment by luin** [comment]
It seems you used async.map in a wrong way. The code should be:

```javascript
async.map(records, function(record, next) {
  cluster.set(record.key, record.value, 'EX', expiry, next);
}, 
```

**Comment by gheidorn** [comment]
That was it!  Thank you so much for your help.
