### ISSUE TITLE
opentracing implementation

### ISSUE THREAD

**Issue by AVVS** [luin/ioredis#490]
opentracing.io

It's likely creating wrapper package would be the easiest way to handle this, as it should extend most of the standard commands

The most challenging part is extracting parent context as current command semantics don't really allow for an arbitrary object with span reference to fly around. Could be that before passing args to new Command() last argument after callback cleanup is checked for instanceof `tracer.Span` and then pulled from args if that is the case, creating childOf relation

When all of that is said and done - can get something nice like jaeger.readthedocs.io working

**Comment by AVVS** [comment]
I've spent some time coding instrumentation trying to get least intrusive API, I've ended up monkey-patching `Command.initPromise()` and `Script.execute()`- code is located here - https://github.com/makeomatic/opentracing-js-ioredis/blob/master/index.js

I'll add docs & more tests in the next couple of days

Current implementation is lacking individual tracking for multi / pipeline calls - it will only track initiation of pipeline

**Comment by AVVS** [comment]
After a bit more research I have an idea about using https://nodejs.org/dist/latest-v8.x/docs/api/async_hooks.html, but that really limits it to recent nodejs versions, so unlikely to be of use for the next year or so.

But when in the future there could literally be no need to use any wrapper methods as tracing could be performed with the async hooks completely hidden from the userland code

**Comment by ebuildy** [comment]
You can see the elastic APM implementation using hook:

https://github.com/elastic/apm-agent-nodejs/blob/master/lib/instrumentation/modules/ioredis.js

They dev a small library around nodejs hook:

https://github.com/elastic/require-in-the-middle/
