### ISSUE TITLE
Password is not filtered on error logs (solution)

### ISSUE THREAD

**Issue by rubens21** [luin/ioredis#491]
Hi folks,

Did you guys already noticed that the Redis' password may be visible on npm error log in some cases?

It is caused by the method returnError declared at https://github.com/luin/ioredis/blob/master/lib/redis/parser.js#L37. It handles the connection errors, and send all arguments to npm log.

I believe there are more ways to reproduce it. This is the way it happened with me:
Setps to reproduce the error:

connect to a server using password (I am almost sure this server must not be localhost)
keep something reading/writing in Redis server.
stop the Redis server
wait a little, maybe 10 sec. If this time is to short the connection may be not lost.
Look for "auth" in the npm log (do not watch mp2 log, for some reasons this kind of log is not sent to there)
I do not know how much important it may be for your team, so I did not create a PR with a solution. However I am posting here in case it is useful for someone else.

```
let ioredisFix = require('ioredis');
let originalReturn = ioredisFix.prototype.returnError;
ioredisFix.prototype.returnError = function(err) {
  let item = this.commandQueue.shift();
  if (item.command.name === 'auth') {
    item.command.args[0] = '[FILTERED]';
  }
  this.commandQueue.push(item);
  originalReturn.apply(this, [err]);
};
module.exports = ioredisFix;
```

**Comment by luin** [comment]
Nice catch! As for me, it makes sense to hide all passwords in the logs. What do you think @shaharmor @AVVS ?

**Comment by AVVS** [comment]
I don't mind the reasoning behind the change, but would hide it behind a setting just to be on the safe side

**Comment by shaharmor** [comment]
Sounds reasonable.
I would set it on a setting which defaults to the current behavior (show the password), and in the next version change the default to hide the password.

Maybe use `****` instead of `[FILTERED]` too

**Comment by rubens21** [comment]
Hi guys,

I am happy this tip is useful. It was not catch by myself, but for my work mate. I was the responsible for finding a solution though.

So, If you guys don't mind I would be happy if I could work on it and create a PR. 
However, I would need some further explanation about what @shaharmor means with "hide it behind a setting".

**Comment by oCHRISo** [comment]
Was there a PR for this afterwards?
