### ISSUE TITLE
Operations blocking if there's no node available

### ISSUE THREAD

**Issue by synologic** [luin/ioredis#492]
Is it normal that operations block if there's no node available to perform the operations on ?

Shouldn't that return something in the error parameter of the callback, because we don't like to get blocked, or maybe i'm missing something

**Comment by tuananh** [comment]
You're talking about this? https://github.com/luin/ioredis#offline-queue

> var redis = new Redis({ enableOfflineQueue: false });

**Comment by synologic** [comment]
Exactly, thanks for pointing that out ...
