### ISSUE TITLE
`createClient` - Am I meant to use this?

### ISSUE THREAD

**Issue by SamuelMarks** [luin/ioredis#496]
`createClient` works and is convenient. I'm moving from the regular [redis npm library](https://www.npmjs.com/package/redis).

I ask because the current master TypeScript doesn't have `createClient`: [types/ioredis/index.d.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/ioredis/index.d.ts) (https://github.com/DefinitelyTyped/DefinitelyTyped/commit/50ae147fbb0fe209664c81d48ba6c16feaababb1), and it's not mentioned in the ioredis README.

**Comment by luin** [comment]
`createClient` is an alias for `new Redis` to stay compatible with the redis module. It's deprecated and may be removed in the future major updates.

It's recommended to use `new Redis` instead for the new code.

**Comment by SamuelMarks** [comment]
Sure thing. Good to have clarification.

**Comment by miguelmota** [comment]
May be a good idea to throw a console log warning mentioning it might deprecated in the future.
