### ISSUE TITLE
wildcard channel doesn't work

### ISSUE THREAD

**Issue by normanaranez** [luin/ioredis#498]
my wildcard doesn't work using laravel 5.4 framework. here's my code

note: 
- i already run the socket server
- it works if the redis.subscribe set to specific channel. i want it to be wildcard so that i don't add channel everytime i create new one.

my route

Route::get('event', function(){

	$data = [
		'event' => 'BwesitTestEvent',
		'data' => [
			'name' => 'peste ka'
		]
	];

	Redis::publish('bwesit-channel', json_encode($data));

});

socket.io server

`var app = require('express')();

var server = require('http').Server(app);

var io = require('socket.io')(server);

var Redis = require('ioredis');

var redis = new Redis();

redis.subscribe(['*'], function(err, count){

});

redis.on('message', function(channel, message){
    
    console.log('message received');
    console.log(message);

    message = JSON.parse(message);

    io.emit(channel + ':' + message.event, message.data);

});

server.listen(3000, function(){
  console.log('server run at port 3000 to stop ctr + c');
});

io.on('connection', function (socket) {

    console.log('a user connected');
    socket.on('disconnect', function(){
        console.log('user disconnected');
    });
});`

**Comment by luin** [comment]
`redis.subscribe` doesn't support wildcard. psubscribe should do the trick. Refer to https://redis.io/commands/psubscribe for details.
