### ISSUE TITLE
Scan Steams emits the 'data' 2 times

### ISSUE THREAD

**Issue by TomerAmirV** [luin/ioredis#499]
Hi,

I am trying to use `scanStream` to find all keys and iterate over them.
The problem is that the `on('data')` event is emitted twice, which breaks my logic.

here is my code:

```
let steam = redis.scanStream({ match: this.prefix + '*' });

steam.on('data', (keys) => {
    // iterate over keys and do some aggregation
});
```

Am I doing something wrong, or I should expect the `data` event to be emitted multiple times? if so, how can I know when I have all the data?

Thanks

**Comment by luin** [comment]
`scanStream` returns a typical Node.js stream. So, of course 'data' event will be emitted multiple times. When all data are received, "end" event will be emitted. Refer to https://github.com/luin/ioredis#streamify-scanning for details.

**Comment by TomerAmirV** [comment]
Thanks!
That worked!
didn't understand that part in the documentation... 😅
