### ISSUE TITLE
SET key value [EX seconds] [PX milliseconds] [NX|XX]

### ISSUE THREAD

**Issue by chrishiestand** [luin/ioredis#50]
Does ioredis support the extended options in set (EX, PX, NX, XX)? It doesn't seem to, I'd just like to verify.

**Comment by luin** [comment]
Yes, ioredis does support these options. Actually ioredis just passes all arguments to the Redis server directly.

**Comment by chrishiestand** [comment]
Well that's great to hear. Sorry for the simple question, but I'm relatively new to using redis and ioredis. What is the correct syntax for writing such a command?

`redis.set('mykey', 'blah', 'EX 10')` gets me `Possibly unhandled ReplyError: ERR syntax error`

**Comment by luin** [comment]
it should be `redis.set('mykey', 'blah', 'EX', '10');`

**Comment by chrishiestand** [comment]
Ah, thank you that works. That makes much more sense :-)
