### ISSUE TITLE
How to call functions from redis modules using ioredis?

### ISSUE THREAD

**Issue by chameleonbr** [luin/ioredis#500]
Hi, how I could call functions from redis modules using ioredis?

**Comment by luin** [comment]
Redis Modules should provide commands with the similar interface with the native commands. For example, redis-graph offers `GRAPH.CREATENODE` command, so in ioredis, you should be able to use it via `call` method:

```javascript
redis.call('GRAPH.CREATENODE', 'graph', 'label')
```

**Comment by chameleonbr** [comment]
Thanks!!!

**Comment by MichelDiz** [comment]
Is there any documentation that I can put together a test of this feature?
Do I have to do a Lua Script?
`Unhandled rejection ReplyError: ERR unknown command 'GRAPH.CREATENODE'`

**Comment by tuananh** [comment]
@MichelDiz you need to compile redis with the module you want to use (prior redis 4)

**Comment by MichelDiz** [comment]
Okay, I'm using Redis on Docker. I have to figure out how to do it through (local) Docker. I would have to create a new image in that case.

**Comment by tuananh** [comment]
@MichelDiz i played with redisearch before and wrote a dockerfile for it. you may want to take a look and see https://github.com/tuananh/Dockerfile/tree/master/redisearch
