### ISSUE TITLE
geolocation

### ISSUE THREAD

**Issue by madbean** [luin/ioredis#501]
Hello

Thank for this client !
In the readme you are talking about geo function but i can't find documentation.
can you tell me how to use geoadd and georaddius please.

Thanks

**Comment by luin** [comment]
Just like other commands: `redis.geoadd('l', 'a')`. Did you get any error?

**Comment by madbean** [comment]
hello no it works, thx
great ! have nice day.
`
redis.geoadd(id, latitude, longitude, key);
 redis.georadius(id, latitude, longitude, distance, unit, 'WITHCOORD');
`
