### ISSUE TITLE
Bad Performance

### ISSUE THREAD

**Issue by shaylevi2** [luin/ioredis#505]
The performance of sending commands and receiving results seems to be very bad.
I have a heavy-load highly concurrent server and the profiling shows the ioredis functions are taking almost 90% of the CPU usage.

## Profiling result:

[Bottom up (heavy) profile]:

   ticks parent  name
  72399   29.4%  write
  29443   40.7%    LazyCompile: *Command.transformReply /app/node_modules/ioredis/lib/command.js:207:45
  29443  100.0%      LazyCompile: ~<anonymous> /app/node_modules/ioredis/lib/command.js:191:19
  26560   90.2%        LazyCompile: *exports.returnReply /app/node_modules/ioredis/lib/redis/parser.js:76:32
  26560  100.0%          LazyCompile: *returnReply /app/node_modules/ioredis/lib/redis/parser.js:26:27
  26560  100.0%            LazyCompile: *execute /app/node_modules/redis-parser/lib/parser.js:521:60
   2883    9.8%        LazyCompile: ~exports.returnReply /app/node_modules/ioredis/lib/redis/parser.js:76:32
   2746   95.2%          LazyCompile: *returnReply /app/node_modules/ioredis/lib/redis/parser.js:26:27
   2100   76.5%            LazyCompile: *execute /app/node_modules/redis-parser/lib/parser.js:521:60
    646   23.5%            LazyCompile: ~execute /app/node_modules/redis-parser/lib/parser.js:521:60
    137    4.8%          LazyCompile: ~returnReply /app/node_modules/ioredis/lib/redis/parser.js:26:27
    137  100.0%            LazyCompile: ~execute /app/node_modules/redis-parser/lib/parser.js:521:60
   6449    8.9%    LazyCompile: *byteLength buffer.js:355:20
   6038   93.6%      LazyCompile: *Command.toWritable /app/node_modules/ioredis/lib/command.js:135:41
   6038  100.0%        LazyCompile: *Redis.sendCommand /app/node_modules/ioredis/lib/redis.js:553:40
   6038  100.0%          LazyCompile: ~tryConnection /app/node_modules/ioredis/lib/cluster/index.js:478:25
   6038  100.0%            LazyCompile: *Cluster.sendCommand /app/node_modules/ioredis/lib/cluster/index.js:421:42

**Comment by luin** [comment]
Does upgrading to redis-parser 3.0 reduce the CPU usage?

**Comment by shaylevi2** [comment]
No :( tried that

I don't know where it's coming from.

**Comment by luin** [comment]
Could you please post the .cpuprofile files here for analyzing?

**Comment by shaylevi2** [comment]
[prof.txt](https://github.com/luin/ioredis/files/1185747/prof.txt)

Profiler output file attached.

**Comment by luin** [comment]
I recommend you to use https://github.com/node-inspector/v8-profiler for profiling JavaScript code:

```javascript
const profiler = require('v8-profiler');
profiler.startProfiling('1');
// Your code here
const profile1 = profiler.stopProfiling();
profile1.export(function(error, result) {
  fs.writeFileSync('profile.cpuprofile', result);
  profile1.delete();
});
```

Post the profile.cpuprofile here and I'd like to help you find which part of your code slow down the program.

**Comment by shaylevi2** [comment]
Why would I use that? 
Node has a built in profiler... node --prof which is statistical and way more informative.

**Comment by luin** [comment]
Well...since what it provided is not only showing the CPU usage of JavaScript code but as well as C++ code.

From the summary:

```
 [Summary]:
   ticks  total  nonlib   name
  55221   22.4%   24.0%  JavaScript
  161754   65.7%   70.2%  C++
   9564    3.9%    4.1%  GC
  15573    6.3%          Shared libraries
  13483    5.5%          Unaccounted
```

It shows that the major CPU usage (65.7%) occurred in C++ code. And for the C++ part:

```
 [C++]:
   ticks  total  nonlib   name
  72399   29.4%   31.4%  write
  31416   12.8%   13.6%  syscall
   3456    1.4%    1.5%  v8::internal::IncrementalMarking::Step(unsigned long, v8::internal::IncrementalMarking::CompletionAction, v8::internal::IncrementalMarking::ForceCompletionAction, v8::internal::StepOrigin)
```

`write` cost many ticks, and "Bottom up" section showed where did these `write` came from. So it doesn't mean `LazyCompile: *Command.transformReply /app/node_modules/ioredis/lib/command.js:207:45` takes 29443 ticks here.

**Comment by shaylevi2** [comment]
But if I'm not mistaken, these writes seem to have come from ioredis

**Comment by luin** [comment]
@shaylevi2 Yes, that's correct. For the log, 40.7% + 8.9% writes came from ioredis. It happens when converting buffers to strings (which is necessary since the data from the socket is buffer).

Hope that answers your question.

**Comment by luin** [comment]
Closing this. Let me know if there are further questions.
