### ISSUE TITLE
Vue中使用ioredis的问题

### ISSUE THREAD

**Issue by ShadowMurloc** [luin/ioredis#506]
![image](https://user-images.githubusercontent.com/16248989/28768814-b26ea04c-760b-11e7-8e19-219821cfa905.png)
单独运行这个js，是没有问题的，可以set、get。
如果在Vue中引入并init(),就会报下面的那个错误
![image](https://user-images.githubusercontent.com/16248989/28768954-2ca681ae-760c-11e7-8847-3e080dc21e30.png)
![image](https://user-images.githubusercontent.com/16248989/28768957-342c5fd4-760c-11e7-8818-713ce30f7e2e.png)

**Comment by luin** [comment]
数据库操作只能在后端实现，没有办法在前端操作的。

**Comment by ShadowMurloc** [comment]
@luin  知道了  多谢多谢
