### ISSUE TITLE
Memory improvements

### ISSUE THREAD

**Issue by shaharmor** [luin/ioredis#509]
Hey,

While trying to diagnose a memory issue we had in one of our servers, I noticed the `ioredis` keeps a lot of book-keeping for no obvious reasons.

Specifically what I found is that each `Command` instance keeps the `args` & `keys` arrays for as long as it is active, while not really being used after the command is sent, maybe only for error reporting but not for general use.
This causes a big increase in memory usage under very heavy load where the server has a lot of commands in the `commandQueue`.

I'm pretty sure there are more locations like this, but I didn't get the time to look.

**Comment by shaharmor** [comment]
@luin what do you think?

**Comment by luin** [comment]
We are using ioredis connecting to tens of Redis instances (each instance has 256GB memory allocated) and the load is pretty heavy. However, we haven't met the memory issue caused by `args` & `keys` properties.

Anyway, I'll try to remove these properties from the `commandQueue` this weekend.

**Comment by shaharmor** [comment]
The issue is not with the Redis instances, its with the node instances.

**Comment by luin** [comment]
Finding out several features depends on the `args`. For example, the `autoResendUnfulfilledCommands` option, the `reconnectOnError` option and the `fillSubCommand` function in the reply handler. It's a little tricky to delete this property before pushing commands into the `commandQueue`.

**Comment by shaharmor** [comment]
bummer

**Comment by cuddeford** [comment]
bummer :(
