### ISSUE TITLE
redis.keys() ignores keyPrefix

### ISSUE THREAD

**Issue by minemidnight** [luin/ioredis#511]
Using redis.keys() ignores the "keyPrefix" field set in options when creating a new redis instance. It also returns keys including the prefix in the key, resulting in code as such:

```
let keys = await redis.keys(`${redis.options.keyPrefix}queue.*`);
keys = keys.map(key => key.substring(redis.options.keyPrefix.length));
```

**Comment by luin** [comment]
Thank you for reporting this. This issue has been discussed and noted on the README: https://github.com/luin/ioredis#transparent-key-prefixing.
