### ISSUE TITLE
cluster connect question 

### ISSUE THREAD

**Issue by LastKing** [luin/ioredis#512]
redis config file  must bind public ip?  If I write nothing , just write 
#bind 127.0.0.1
bind 0.0.0.0   !== write nothing?

**Comment by luin** [comment]
没太看懂...要不说中文... bind 0.0.0.0 应该就可以了，遇到什么问题了吗

**Comment by LastKing** [comment]
。。。我这英文。。。我的意思是 redis我本地连不上服务器的集群，服务器的redis 配置是
两个注释的bind 127.0.0.1 ，没有其他的。这样不写难道不等于bind 0.0.0.0么？
我连接的时候用的是公网ip，但是爆出来的错误全部指向了127.0.0.1 不知道为什么

**Comment by luin** [comment]
哦啊明白了，Redis 的集群要求绑定到外部访问的网络 interface。比如如果是内网访问，就绑定到内网地址，如果是外网访问，就绑定到外网地址。因为这个绑定的地址不仅是用来内部通讯的，而且还要返回给客户端，由客户端直连。不写 bind 的话需要查一下对应 Redis 版本的官方文档了，我这边记不太清了
