### ISSUE TITLE
Server Blocked Upon Redis Failure

### ISSUE THREAD

**Issue by aspdev91** [luin/ioredis#514]
Hi,

I noticed when my Redis server fails or shuts down unexpectedly, my server is unable to accept any requests. It seems like the event loop is blocked with retry attempts to reconnect to Redis. Is there a way the server can continue to process requests/responses while periodically attempting to reconnect to the Redis server? Thanks!

[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:1041:11)
    at _exceptionWithHostPort (util.js:1064:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1153:14)

**Comment by luin** [comment]
Refer to the retryStrategy option for details. By the way, the event loop was probably not blocked (if it was, you should notice the CPU usage of the process reached nearly 100%). Check the middleware or HTTP callbacks in your App to see whether the request handler will keep waiting for redis commands.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by betweenbrain** [comment]
@luin Do you happen to have a simple example the shows

> HTTP callbacks in your App to see whether the request handler will keep waiting for redis commands
