### ISSUE TITLE
Alternatively return redis result as ES6 Map/Set in callback/promise.

### ISSUE THREAD

**Issue by aojiaotage** [luin/ioredis#515]
Hi there, I wonder if anyone would +1 if the returned value of some certain method like `smembers`  and `hgetall` could be ES6 Set and Map? 
This could be alternative like using `redis.smembers().asSet()` and wouldn't break the original structure.
I'd like to make a PR if you guys agree to it.

**Comment by AVVS** [comment]
I think you should simply use response transformers, that would lead to the desired result

**Comment by aojiaotage** [comment]
Thank you for replying!
I'm a little confused about the response transformers you kindly mentioned. Did you mean the wrapping work I did my self after getting the result?
IMHO, wrapping the result in a way that meets the ES standard could be a little more better than getting the 'raw' data.

**Comment by luin** [comment]
It's pretty straight to wrap the result of `smembers` in a Set:

```javascript
const set = new Set(await redis.smembers())
```

Does this work for you?
