### ISSUE TITLE
canceling BRPOP gracefully

### ISSUE THREAD

**Issue by kabalage** [luin/ioredis#516]
Hi,

I use redis as a lightweight message queue with `BRPOP`. I would like to disconnect redis on SIGTERM, so I call `client.quit()` on the client that is listening for the messages with `BRPOP`. The problem is that the promise returned by `client.quit()` is never resolved. `client.disconnect()` works but I would not like to lose a payload that's on it's way to the client.

Is this behaviour intentional? My guess is that `QUIT` waits for `BRPOP` to complete but is there a way to end a `BRPOP` safely?

I would not like to use timeout and periodically resending `BRPOP` just to handle process shutdowns gracefully.

Thanks for the help!

**Comment by luin** [comment]
I'm afraid there's no way to cancel `BRPOP` since Redis doesn't provide an interface for it. The `timeout` argument of `BRPOP` is designed for this use case as for me 😆

**Comment by kabalage** [comment]
Thank you for your response! Is the underlying connection reused for multiple subsequent timeouted `BRPOP`-s?

**Comment by luin** [comment]
A client only has a single connection to Redis. If a `BRPOP` timeouts, the connection is able to process subsequent commands (e.g. another `BRPOP`).

**Comment by kabalage** [comment]
Ok, thanks!
