### ISSUE TITLE
AWS ElasticCache Redis Cluster Host Port ignored

### ISSUE THREAD

**Issue by elelement** [luin/ioredis#524]
Hi, this is more a **question** than an issue, because it's probably a problem with my code. I have a class encapsulating the client creation like this:
```
class RedisClient extends MyClient {
    constructor() {
        super();
        const Redis = require('ioredis');
        this.client = new Redis.Cluster(redisConfig.cluster);
    }

    get(data) {
        return this.client.get(data).then(function(res) {
            console.log(res);
            return JSON.parse(res);
        });
    }
}
```

This is what redisConfig.cluster contains:
```
{
    "cluster": [
            {"host": "<my-cache-host-001>.cache.amazonaws.com",  "port": 6379},
            {"host": "<my-cache-host-002>.cache.amazonaws.com",  "port": 6379},
            {"host": "<my-cache-host-003>.cache.amazonaws.com",  "port": 6379},
            {"host": "<my-cache-host-004>.cache.amazonaws.com",  "port": 6379}
    ]
}
```

But when I run it, I'm getting this:
```
Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)
```

It's trying to connect to Localhost?? I think I've tried everything and, frankly, I don't understand what's happening. When I print the object (the this.client of my RedisClient class) I can see in the cluster's configuration all the hosts passed by parameter. 

Thank you

**Comment by luin** [comment]
Maybe `this.client = new Redis.Cluster(redisConfig.cluster.cluster)`?

**Comment by elelement** [comment]
Sorry. when I said:

> This is what redisConfig.cluster contains:

I meant:

> This is what redisConfig contains:

**Comment by elelement** [comment]
OMG. I had a self developed module included in my application that was using another ioredis client instance, with 127.0.0.1 hardcoded and thus, causing the whole program to fail (without telling me where in the code). Sorry for the issue, but I really didn't know what was happening. Thanks!
