### ISSUE TITLE
del key in Transaction, return error result

### ISSUE THREAD

**Issue by legolasNg** [luin/ioredis#526]
when i ran this code, something wrong will be returned

```javascript
    redis.multi()
           .get(key)
           .del(key)
           .exec(console.log)
```
result
```
null [ [ null, null ], [ null, 0 ] ]
```

i can confirm the key exsist in redis, but i can't get correct result in above sample.
ioredis: 2.5.0   use redis sentinel

**Comment by luin** [comment]
Could you confirm whether this issue is transaction related? What about a single `redis.get(key)` before transaction?

**Comment by legolasNg** [comment]
sorry to trouble you, it's my fault, not the multi()
