### ISSUE TITLE
Connect through SSH tunnel

### ISSUE THREAD

**Issue by stephan-nordnes-eriksen** [luin/ioredis#527]
I am trying to figure out how I can use ioredis to connect to a redis server through a bastion (ssh tunnel).

I have been looking at the source code for medis (https://github.com/luin/medis/blob/b36a4374c94bea86f95f8022ca17d034b3433701/client/redux/actions/connection.js) to see if I was able to reverse-engineer that, but I have not had any luck yet.

I have been looking at https://github.com/agebrock/tunnel-ssh to see if I maybe was able to use that, but again, no luck thus far.

I would love to be able to set up a ssh-tunnel right in the ioredis config, or perhaps an example of how to achieve this in some kind of doc would be awesome.

My particular setup;
I have a redis server behind a security group in AWS ElastiCache. I have a bastion using a ssh-cert for connection, which is able to talk to this redis server directly.

My attempt with `tunnel-ssh`:

```
var config = {
    username: username,
    host: ip_address_of_bastion,
    port: 22,
    privateKey: fs.readFileSync('/somewhere/bastion.pem'),

    dstHost: "something.like.this.cache.amazonaws.com",
    dstPort: 6379,
    
    localHost:'127.0.0.1',
    localPort: 6380,//also tried 6379
};

var tunnel = require('tunnel-ssh');
tunnel(config, function (error, server) {
    if(error){
        //catch configuration and startup errors here.
        console.log("Error", error);
    }

    const redisInstance = new Redis({
        host: "127.0.0.1",// I have also tried"something.like.this.cache.amazonaws.com",
        port: 6380, //also tried 6379
        showFriendlyErrorStack: true,
        retryStrategy: function (times) {
            var delay = Math.min(times * 100, 3000);
            console.log("reconnect attempt", times); //This will run because I am unable to connect
            return delay;
        },
        reconnectOnError: function (err) {
            var targetError = 'READONLY';
            if (err.message.slice(0, targetError.length) === targetError) {
                return true;
            }
        }
    });
});
```

**Comment by luin** [comment]
Haven't used the tunnel-ssh module before, but the code looks good to me. What error did you get?

**Comment by stephan-nordnes-eriksen** [comment]
I am getting:
```
Error: Timed out while waiting for handshake
    at Timeout._onTimeout (/Users/stephan/kudos/node-util-notification-status/node_modules/ssh2/lib/client.js:683:19)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
```

**Comment by stephan-nordnes-eriksen** [comment]
I found the issue. I had, for some reason, linked to the wrong redis instance. Correcting that successfully made the connection, with the approach above. For anyone looking to do this in the future, this would probably be the easiest way to achieve the ssh tunneling.

**Comment by allfornaruto** [comment]
It's helpful.
