### ISSUE TITLE
Cluster mode not fetching any data.

### ISSUE THREAD

**Issue by pranavsreedhar92** [luin/ioredis#528]
Able to get data when connected to single instance. But when connecting to cluster not able to fetch any data.
var Redis = require('ioredis');
var cluster = new Redis.Cluster([
  { 
    port: "<PORT>",
    host: "<HOST>",
    password: "<PASSWORD>"
  }
]);

cluster.zrangebyscore(redisKey, sTimetoUtcMilli, eTimetoUtcMilli, function (err, reply) {
            
            if (reply) {
                console.log('Success from zrangebyscore');
                console.log(reply);
            } else {
                console.log(err);
                callback(err);
            }
        });

Thanks in advance.

**Comment by luin** [comment]
Could you enable the debug mode and post the logs here?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by pranavsreedhar92** [comment]
Thu, 05 Oct 2017 09:17:01 GMT ioredis:connection skip reconnecting since the connection is manually closed.
Thu, 05 Oct 2017 09:17:01 GMT ioredis:redis status[ip]: close -> end
Thu, 05 Oct 2017 09:17:01 GMT ioredis:redis status[ip]: wait -> close
Thu, 05 Oct 2017 09:17:01 GMT ioredis:connection skip reconnecting since the connection is manually closed.
Thu, 05 Oct 2017 09:17:01 GMT ioredis:redis status[ip]: close -> end
Thu, 05 Oct 2017 09:17:01 GMT ioredis:redis status[ip]: connect -> close
Thu, 05 Oct 2017 09:17:01 GMT ioredis:connection skip reconnecting since the connection is manually closed.
Thu, 05 Oct 2017 09:17:01 GMT ioredis:redis status[ip]: close -> end
Thu, 05 Oct 2017 09:17:01 GMT ioredis:cluster status: disconnecting -> close
Thu, 05 Oct 2017 09:17:01 GMT ioredis:cluster status: close -> reconnecting
Thu, 05 Oct 2017 09:17:02 GMT ioredis:cluster Cluster is disconnected. Retrying after 444ms
Thu, 05 Oct 2017 09:17:02 GMT ioredis:cluster status: reconnecting -> connecting
Thu, 05 Oct 2017 09:17:02 GMT ioredis:redis status[HOST: [empty] -> wait
Thu, 05 Oct 2017 09:17:02 GMT ioredis:cluster getting slot cache from HOST
Thu, 05 Oct 2017 09:17:02 GMT ioredis:redis status[[HOST]]: wait -> connecting
Thu, 05 Oct 2017 09:17:02 GMT ioredis:redis queue command[0] -> cluster(slots)
Thu, 05 Oct 2017 09:17:02 GMT ioredis:redis status[[IP]]: connecting -> connect
Thu, 05 Oct 2017 09:17:02 GMT ioredis:redis write command[0] -> auth([Password])
Thu, 05 Oct 2017 09:17:02 GMT ioredis:redis write command[0] -> info()
Thu, 05 Oct 2017 09:17:02 GMT ioredis:redis status[[IP]]: connect -> ready
Thu, 05 Oct 2017 09:17:02 GMT ioredis:connection send 1 commands in offline queue
Thu, 05 Oct 2017 09:17:02 GMT ioredis:redis write command[0] -> cluster(slots)
Thu, 05 Oct 2017 09:17:02 GMT ioredis:redis status[ip Adderess]: [empty] -> wait
Thu, 05 Oct 2017 09:17:02 GMT ioredis:redis status[ip Adderess]: [empty] -> wait
Thu, 05 Oct 2017 09:17:02 GMT ioredis:redis status[ip Adderess]: [empty] -> wait
Thu, 05 Oct 2017 09:17:02 GMT ioredis:redis status[ip Adderess]: [empty] -> wait
Thu, 05 Oct 2017 09:17:02 GMT ioredis:redis status[ip Adderess]: [empty] -> wait
Thu, 05 Oct 2017 09:17:02 GMT ioredis:redis status[ip Adderess]: [empty] -> wait
Thu, 05 Oct 2017 09:17:02 GMT ioredis:cluster status: connecting -> connect
Thu, 05 Oct 2017 09:17:02 GMT ioredis:redis status[ip]: wait -> connecting
Thu, 05 Oct 2017 09:17:02 GMT ioredis:redis queue command[0] -> cluster(info)
Thu, 05 Oct 2017 09:17:02 GMT ioredis:redis status[ip]: connecting -> connect
Thu, 05 Oct 2017 09:17:02 GMT ioredis:redis write command[0] -> info()
Thu, 05 Oct 2017 09:17:02 GMT ioredis:redis status[[IP]]: ready -> close
Thu, 05 Oct 2017 09:17:02 GMT ioredis:connection skip reconnecting since the connection is manually closed.
Thu, 05 Oct 2017 09:17:02 GMT ioredis:redis status[[IP]]: close -> end
Thu, 05 Oct 2017 09:17:02 GMT ioredis:cluster status: connect -> disconnecting
Thu, 05 Oct 2017 09:17:02 GMT ioredis:redis status[ip]: wait -> close
Thu, 05 Oct 2017 09:17:02 GMT ioredis:connection skip reconnecting since the connection is manually closed.
Thu, 05 Oct 2017 09:17:02 GMT ioredis:redis status[ip]: close -> end
Thu, 05 Oct 2017 09:17:02 GMT ioredis:redis status[ip]: wait -> close
Thu, 05 Oct 2017 09:17:02 GMT ioredis:connection skip reconnecting since the connection is manually closed.
Thu, 05 Oct 2017 09:17:02 GMT ioredis:redis status[ip]: close -> end
Thu, 05 Oct 2017 09:17:02 GMT ioredis:redis status[ip]: wait -> close
Thu, 05 Oct 2017 09:17:02 GMT ioredis:connection skip reconnecting since the connection is manually closed.
Thu, 05 Oct 2017 09:17:02 GMT ioredis:redis status[ip]: close -> end
Thu, 05 Oct 2017 09:17:02 GMT ioredis:redis status[ip]: wait -> close
Thu, 05 Oct 2017 09:17:02 GMT ioredis:connection skip reconnecting since the connection is manually closed.
Thu, 05 Oct 2017 09:17:02 GMT ioredis:redis status[ip]: close -> end
Thu, 05 Oct 2017 09:17:02 GMT ioredis:redis status[ip]: wait -> close
Thu, 05 Oct 2017 09:17:02 GMT ioredis:connection skip reconnecting since the connection is manually closed.
Thu, 05 Oct 2017 09:17:02 GMT ioredis:redis status[ip]: close -> end
Thu, 05 Oct 2017 09:17:02 GMT ioredis:redis status[ip]: connect -> close
Thu, 05 Oct 2017 09:17:02 GMT ioredis:connection skip reconnecting since the connection is manually closed.
Thu, 05 Oct 2017 09:17:02 GMT ioredis:redis status[ip]: close -> end
Thu, 05 Oct 2017 09:17:02 GMT ioredis:cluster status: disconnecting -> close
Thu, 05 Oct 2017 09:17:02 GMT ioredis:cluster status: close -> reconnecting
Thu, 05 Oct 2017 09:17:02 GMT ioredis:cluster Cluster is disconnected. Retrying after 446ms
Thu, 05 Oct 2017 09:17:02 GMT ioredis:cluster status: reconnecting -> connecting
Thu, 05 Oct 2017 09:17:02 GMT ioredis:redis status[[HOST]]: [empty] -> wait

**Comment by luin** [comment]
The logs didn't show anything helpful. It seems there are some issues in the cluster setup. Could you try to run `cluster info` in one of the nodes in the cluster and show me the result?

**Comment by pranavsreedhar92** [comment]
cluster_state:ok
cluster_slots_assigned:16384
cluster_slots_ok:16384
cluster_slots_pfail:0
cluster_slots_fail:0
cluster_known_nodes:6
cluster_size:3
cluster_current_epoch:12
cluster_my_epoch:11
cluster_stats_messages_ping_sent:139414
cluster_stats_messages_pong_sent:138627
cluster_stats_messages_sent:278041
cluster_stats_messages_ping_received:138627
cluster_stats_messages_pong_received:139414
cluster_stats_messages_received:278041

**Comment by luin** [comment]
Did you call `cluster.disconnect()` or `cluster.quit()` manually? It helps if you could provide a minimal reproducible example.
