### ISSUE TITLE
Ordering guarantees for pipeline

### ISSUE THREAD

**Issue by anurag108** [luin/ioredis#532]
If I use redis pipeline like this

const keys = ['key1', 'key2'];
const pipeline = redis.pipeline();
keys.forEach(key, pipeline.get(key));
const results = await pipeline.exec();

I get an array of results. I wanted to know if the order of the commands I set with pipeline and order of results I get are same or not?

I have tested with a few examples and I got results in the same order but that could just be a chance. I checked the documentation but couldn't find information related to this.

**Comment by luin** [comment]
Ordering is guaranteed by Redis. You can rely on the order of the results.
