### ISSUE TITLE
Cluster keys command round robins across cluster nodes

### ISSUE THREAD

**Issue by mjh1** [luin/ioredis#533]
I created a cluster with nodes A,B,C and added some keys with the assignment like:
A keys: []
B keys: [ 'fab', 'foos' ]
C keys: [ 'foo' ]

Then I wrote a small node script:

```
const Redis = require('ioredis');

var redisClusterConn = {
            "host": "localhost",
                        "port": 7000
};
var redisCluster = new Redis.Cluster([redisClusterConn]);

redisCluster.keys('*', function (err, result) {
    if (err)
        console.log(err);

    console.log(result);
});
```

If you run this multiple times it outputs different results:

```
➜  node-client node cluster-keys-test.js
[]
^C
➜  node-client node cluster-keys-test.js
[ 'fab', 'foos' ]
^C
➜  node-client node cluster-keys-test.js
[ 'foo' ]
```

Should the ioredis client not aggregate results over the entire cluster?

**Comment by luin** [comment]
Hi @mjh1 ! This is the expected result and documented in https://github.com/luin/ioredis#running-commands-to-multiple-nodes. Refer to the examples of the above link for how to aggregate results on the client side.

**Comment by mjh1** [comment]
Thanks, looks good.
