### ISSUE TITLE
ERR syntax error when using MIGRATE 

### ISSUE THREAD

**Issue by MR4online** [luin/ioredis#534]
I try to migrate keys from one Redis instance to another one using "migrate".
my Code looks like:
`redis.migrate(targetConnection.host,targetConnection.port,'""', fromDB, 10000, 'COPY', 'REPLACE', 'KEYS '+ copyKeys.join(' '));`

this should create the following query (for 1 element in the Array):

> MIGRATE 192.168.57.2 6379 "" 3 10000 COPY REPLACE KEYS foo:ID:4e97f878

When I copy the Query in Medis, everthing works.
When the code above is executed, it throws the following Error:

`{
        "name": "ReplyError",
        "message": "ERR syntax error",
        "command": {
            "name": "migrate",
            "args": [
                "192.168.57.2",
                "6379",
                "\"\"",
                "3",
                "10000",
                "COPY",
                "REPLACE",
                "KEYS foo:ID:4e97f878"
            ]
        }
    }`

I tried serveral versions of giving parameters to redis.migrate(): all as array, serveral arrays,  ... evertime the same Error, except:
- when I split "KEYS" from the copyKeys value. Error: "ERR When using MIGRATE KEYS option, the key argument must be set to the empty string"
- when I write the whole query as one string. Error: "ERR wrong number of arguments for 'migrate' command"

So, am I'm doing something wrong? 
Thanks for your Help!

**Comment by luin** [comment]
`'""'` should simply be `''`. The former one is a non-empty string which content is `""`.

**Comment by MR4online** [comment]
thanks! now it works
