### ISSUE TITLE
Sentinel retry logic

### ISSUE THREAD

**Issue by bheema01** [luin/ioredis#537]
Currently, I have the following Redis setup on 3 different hosts.

    Host1: sentinel on port 26379, master on port 6379
    Host2: sentinel on port 26479, slave on port 6479
    Host3: sentinel on port 26579, slave on port 6579

I am using socket.io-redis with ioredis adapter<br>
**Sample code with the above setup**

    const io = require('socket.io')(server);
    const socketredis = require('socket.io-redis');
    const ioredis = require('ioredis');
    
    let redis = new ioredis({
      sentinels: [{ host: 'machine-1.test.com', port: 26379},{ host: 'machine-2.test.com', port: 26479}, { host: 'machine-3.test.com', port: 26579}],
      name: 'master01',
      showFriendlyErrorStack: true,
      retryStrategy: function (times) {
        Logger.info(`Redis: Connection retry #${times}`);
        if(times < 10) {
          return 20000;
        } else {
          Logger.error(`Redis reconnect max retry limit reached...aborting app`);
          process.exit(1);
        }
      },
      sentinelRetryStrategy: function (times) {
        Logger.info(`Redis Sentinel: Connection retry #${times}`);
        if(times < 3) {
          return 3000;
        } else {
          Logger.error(`Redis Sentinel reconnect max retry limit reached...aborting app`);
          process.exit(1);
       }
      }
    });
    
    io.adapter(socketredis(redis));
    
    redis.on('connect', () => {
      console.log('Connected to Redis --->');
    });

 - With the above sample code, I have no issue with the node app when the master redis instance (6379) is running where the node app is running - say I have node app running on host:1 
 - When I shutdown the Redis instance on port 6379 on host:1 (where the node app is running), I don't see the retry logic kicking in and I see the node app shuts down with the error message **Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379**

Here is some error log with the above setup.

    Exiting...listener count 1
    events.js:182
          throw er; // Unhandled 'error' event
          ^
    
    Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
        at Object.exports._errnoException (util.js:1022:11)
        at exports._exceptionWithHostPort (util.js:1045:20)
        at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:14)

 Any thoughts on why the app would shutdown with the ECONNREFUSED 127.0.0.1:6379 message and/or modifying the adapter code so that the retry logic would work?

**Comment by luin** [comment]
I'm not sure but should this be `io.adapter(socketredis({pubClient: redis, subClient: redis}))` instead of `io.adapter(socketredis(redis))`?

**Comment by bheema01** [comment]
Thanks for your quick response @luin 
Your suggestion on using pubClient/subClient seems to be keeping the node app UP without shutting it down.

**Comment by bheema01** [comment]
Another related question  - so keeping it in the same thread.

Continuing to test the retry logic with just one redis instance and one sentinel. The idea is to see the retryStrategy in action by setting the failover-timeout to 30000 and down-after-milliseconds to 3000 in the sentinel config

```javascript
let redis = new IOredis({
  sentinels: [{ host: 'abc.xyz.com', port: 26379 }],
  name: 'master01',
  showFriendlyErrorStack: true,
  retryStrategy: function (times) {
    Logger.info(`Redis: Connection retry #${times}`);
    if (times < 20) {
      return 5000;
    } else {
      Logger.error(`Redis reconnect max retry limit reached...aborting app`);
      process.exit(1);
    }
  },
  sentinelRetryStrategy: function (times) {
    Logger.info(`Redis Sentinel: Connection retry #${times}`);
    if (times < 50) {
      return 5000;
    } else {
      Logger.error(`Redis Sentinel reconnect max retry limit reached...aborting app`);
      process.exit(1);
    }
  },
  reconnectOnError: function (err) {
    var targetError = 'READONLY';
    if (err.message.slice(0, targetError.length) === targetError) {
      // Only reconnect when the error starts with "READONLY"
      return true; // or `return 1;`
    }
    console.log(err);
  }
});

io.adapter(socketredis({pubClient: redis, subClient: redis}));
```

Interestingly, when I bring the only redis instance down, the node app seems to fail with the error message "All Sentinels are unreachable. Retrying from scratch after 5000ms" - even though the redis-sentinel is still UP.

Any thoughts on what I could be missing?

**Comment by bheema01** [comment]
Re-opening this issue to see if you have any thoughts on this. 

Continuing to test the retry logic with just one redis instance and one sentinel - I understand, I need at least one redis slave for failover to happen. The idea is to see the retryStrategy in action by setting the failover-timeout to 30000 and down-after-milliseconds to 3000 in the sentinel config

Currently using pubClient/subClient, like so

`io.adapter(socketredis({pubClient: redis, subClient: redis}))`

The node app gets shut down when I bring the only redis instance down and the node app seems to fail with the error message **All Sentinels are unreachable. Retrying from scratch after 5000ms** - even though the redis-sentinel is still UP.

Any thoughts/suggestions?

**Comment by GD-Dheer** [comment]
This issue is everywhere with this package..... Cant find a solution yet

**Comment by Kev1ntan** [comment]
@GD-Dheer do you find out the solution?
