### ISSUE TITLE
"message" Event is not fired in Cluster mode

### ISSUE THREAD

**Issue by dg3feiko** [luin/ioredis#54]
Problem should be here:

https://github.com/luin/ioredis/blob/master/lib/redis/prototype/parser.js#L78

```js
this.listeners('message').length is 0
```

I tried same piece of code in single redis mode and it worked.

Here is my snippet:

```js

var cluster = new Redis.Cluster(
	[
		{
			port: 30001,
			host: '127.0.0.1'
		}
	]);


cluster.subscribe('news', function (err, count) {
    // this is called
});



cluster.on('message', function (channel, message) {
        // this is not fired
	console.log('Receive message %s from channel %s', message, channel);
});
```

I publish message via redis-cli
```
PUBLISH news something
```

**Comment by luin** [comment]
Codes in the master branch should fix this issue. I'm implementing auto-resubscribe and doing more tests before release a new version.

**Comment by dg3feiko** [comment]
it works now
