### ISSUE TITLE
[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 10ms Last error: Connection is closed.

### ISSUE THREAD

**Issue by penglinjiang** [luin/ioredis#540]
遇到一个问题，主库master（ 192.16.8.1:6380， sentinel:192.16.8.1:26379）和 从库(slave 192.16.8.2:6380, sentinel:192.16.8.1:26379), 还有一个哨兵（192.16.8.3:26379）。

ioredis配置
```
let redis = new Redis({
    sentinels: [{host: '192.16.8.1', port: 26379}, {host: '192.16.8.2', port: 26379}, {host: '192.16.8.3', port: 26379}],
    name: 'mymaster'
}); 
```
redis 版本 4.0.2
当我在kill 掉主库192.16.8.1上面的 redis-server和sentinel进程时，虽然也报很多```[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 10ms Last error: Connection is closed.```，但发现ioredis能重连成功。但如果我直接宕掉主库192.16.8.1,在从库192.16.8.2上使用redis-cli -p 26379 sentinel get-master-addr-by-name mymaster发现主库已经切换到192.16.8.2，ioredis却一直都没有重连成功。一直报“[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 10ms Last error: Connection is closed.”
是ioredis配置有问题吗？ @luin

**Comment by yiting007** [comment]
+1, I have the same issue.

**Comment by luin** [comment]
可以贴一下 `sentinel down-after-milliseconds mymaster` 的配置，如果是 `60000`，那么需要等待 1 分钟的时间所有 Sentinel 才能进行 failover。可以连接不同的哨兵确认每个哨兵是否都返回了新的地址。另外可以打开 DEBUG=ioredis:* 来查看日志信息
