### ISSUE TITLE
ETIMEDOUT when node is idle for a while

### ISSUE THREAD

**Issue by admirkadriu** [luin/ioredis#542]
I'm getting this error after node has had no need for redis for some amount of time. I read some issues related to this, and decided to add a setInterval that basically sets a key on redis every 1 min.  This fixed it. But, is this OK? Is there any other way to fix this issue?

**Comment by luin** [comment]
Did you disable the `keepAlive` option? Seems that enabling `keepAlive` (which is default) should solve the problem.

**Comment by admirkadriu** [comment]
@luin thank you for the replay. No it`s not disabled on my ioRedis configurations. Config contains only host, password, password and database.

**Comment by shudingbo** [comment]
me too， this problem

**Comment by up73k** [comment]
After update to v4.2.0, ioredis began to disconnect without any load operations: 

> stack=Error: read ETIMEDOUT
>    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)

How can I find any reasons of this? May be devs have some magic recipe? )

**Comment by 592da** [comment]
having the same issues with lambda on node 12 runtimes.
happens for idle connections.

any solution ?

**Comment by arifinoid** [comment]
> After update to v4.2.0, ioredis began to disconnect without any load operations:
> 
> > stack=Error: read ETIMEDOUT
> > at TCP.onStreamRead (internal/stream_base_commons.js:111:27)
> 
> How can I find any reasons of this? May be devs have some magic recipe? )

Me too,

> > [ioredis] Unhandled error event: Error: read ETIMEDOUT at TCP.onStreamRead (internal/stream_base_commons.js:205:27)

using ioredis: ^4.17.3
Please help @luin, guys, everyone.. Thank you 🙏

**Comment by KingPuiWong** [comment]
> @luin thank you for the replay. No it`s not disabled on my ioRedis configurations. Config contains only host, password, port and database.

keepAlive 默认是0，是关闭的。

**Comment by KingPuiWong** [comment]
> @luin thank you for the replay. No it`s not disabled on my ioRedis configurations. Config contains only host, password, port and database.

Keepalive is 0 by default, which is closed.
