### ISSUE TITLE
Pipeline benchmark issues

### ISSUE THREAD

**Issue by slavaGanzin** [luin/ioredis#548]
Hello @luin.

I'm using ioredis for a long time and think it's flawless module. Thanks
But I found that pipeline/multi is way to slow:

```
==========================
ioredis: 3.2.1
CPU: 4
OS: linux x64
node version: v9.2.0
current commit: ba851eb

==========================

                      pipeline: SET foo bar
             156 op/s » javascript parser + dropBufferSupport: true
             155 op/s » javascript parser

                      SET foo bar
          86,388 op/s » javascript parser + dropBufferSupport: true
          60,107 op/s » javascript parser

                      LRANGE foo 0 99
          26,474 op/s » javascript parser + dropBufferSupport: true
          16,931 op/s » javascript parser


  Suites:  3
  Benches: 6
  Elapsed: 44,941.67 ms
```

Code I use for testing: https://github.com/slavaGanzin/ioredis/blob/master/benchmarks/single_node.js#L34-L56

As I understand from ioredis code this slowdown caused by parsing/validating commands. Which I think is redundant for pipeline query. Because you use it when performance is a must. So I think it should be a way  to suppress validation or any other bottlenecks.

 I, personally, see this as additional function ```unsafePipeline```, or additional argument ```pipeline(query, {unsafe: true})```. Maybe you'll see it another way?

**Comment by luin** [comment]
Hi @slavaGanzin, it seems the benchmark is a little not fair that the "pipeline" group sends 1000 commands per test while the "set" group sends only 1.

```javascript
var pipelineQuery = []
for (let i = 0; i < 100; i++) {
  pipelineQuery.push(['set', 'foo', 'bar'])
}

suite('multi: SET foo bar', function () {
  set('mintime', 5000);
  set('concurrency', 300);

  before(function (start) {
    waitReady(start);
  });

  bench('javascript parser + dropBufferSupport: true', function (next) {
    redisJD.multi(pipelineQuery).exec(next);
  });

  after(quit);
})

suite('SET foo bar', function () {
  set('mintime', 5000);
  set('concurrency', 300);
  before(function (start) {
    waitReady(start);
  });

  bench('javascript parser + dropBufferSupport: true', function (next) {
    let pending = pipelineQuery.length
    pipelineQuery.forEach(([command, arg1, arg2]) => {
      redisJD[command](arg1, arg2, () => {
        if (!--pending) {
          next()
        }
      });
    })
  });

  after(quit);
});
```

The above code shows the following result:

```
                      multi: SET foo bar
           1,067 op/s » javascript parser + dropBufferSupport: true

                      SET foo bar
             632 op/s » javascript parser + dropBufferSupport: true
```

What's more, pipeline guarantees commands in a pipeline will be executed in order.

**Comment by slavaGanzin** [comment]
Thanks for clarifications. I misinterpret my results

**Comment by julienvincent** [comment]
@luin I am running into some performance issues while using pipeline.

In my use case I am wanting to pipe ~1000 redis commands together using something similar to the below pseudo code:
```js
console.time("gen")
arr.forEach(i => {
  pipeline.hgetall(`key:${i}`)
})
console.timeEnd("gen")

console.time("exec")
await pipeline.exec()
console.timeEnd("exec")
```
Execution of the above produces timestamps roughly equal to 
```
gen: 900.00 ms
exec: 55.00 ms
```

The fact that it takes `900ms` to loop a `1000` length array seems a bit odd to me and makes pipelining u-usable. It would almost be faster to make 1000 individual parallel reads to redis.

Is there perhaps something I can do to increase performance over here?
