### ISSUE TITLE
Raw query

### ISSUE THREAD

**Issue by slavaGanzin** [luin/ioredis#549]
In relation to #548 

I want to test raw pipeline using ioredis:
```
MULTI
SET foo bar
SET foo bar
SET foo bar
...
EXEC
```

But I can't find any way to run in.
```client.call``` and ```client.send_command``` fails on validating.
It's unfair to restrict user not using plain text for redis *text protocol*.

**Comment by luin** [comment]
What's your test code? Here's mine which works:

```javascript
const redis = new Redis()

redis.call('multi', console.log)
redis.call('set', 'foo', 'bar', console.log)
redis.call('get', 'foo', console.log)
redis.call('exec', console.log)

```

Logs:

```
null 'OK'
null 'QUEUED'
null 'QUEUED'
null [ 'OK', 'bar' ]
```

**Comment by slavaGanzin** [comment]
I want to use it like:
```
redis.call(`MULTI
SET foo bar
SET foo bar
SET foo bar
EXEC`)
```

But as I understand now it's redundant, because validation doesn't slowdown query execution, as I thought before.
