### ISSUE TITLE
node 版本 v0.10.25不支持sentinel

### ISSUE THREAD

**Issue by kobehaha** [luin/ioredis#550]
readme中显示Supports Redis >= 2.6.12 and (Node.js >= 0.10.16 or io.js).

显示我使用 node v0.10.25连接 redis sentinel 会连接不上，显示没有可用连接，而通过net 是可以通的,后来我换用高一点的node版本就不存在这个问题了，你可以测试一下呢

**Comment by luin** [comment]
这样啊...后来换了什么版本呢？自动化测试是在 0.10.16 环境下跑的，我手工再试试看。

**Comment by kobehaha** [comment]
后来我直接换的高版本node8了
