### ISSUE TITLE
How to timeout when Sentinel Master is unreachable

### ISSUE THREAD

**Issue by willrstern** [luin/ioredis#556]
**Is there a way to add a timeout to a get/set action?**
I'm looking for this in the docs and it's either not there, or I'm somehow not seeing it.

I'm connecting `ioredis` to 3 sentinels using a master/slave setup.
I can trigger a failover manually and everything works perfectly on the next request.

But, when I tell the current master to simulate an "unreachable" status:
`redis-cli -p 6379 DEBUG sleep 30`
- the sentinels notice and elect a new master
- but the app waits for 30sec until the master is reachable again (now as a slave), then reconnects to the new sentinel master

My config is
```
{
    sentinels: [...the 3 sentinels],
    name: "mymaster",
    reconnectOnError: err => /^READONLY/.test(err.message),
}
```

**Comment by willrstern** [comment]
Also, here's the Redis docs that show that `sleep` is a good way to simulate a master hanging. https://redis.io/topics/sentinel#testing-the-failover

**Comment by super86** [comment]
I have the same problem,when the read or write actions take long time,the Sentinel will chose to switch master/slave

**Comment by toredash** [comment]
Hi @willrstern,

I'm not sure if this is a ioredis issue, but a redis sentinel configuration issue.

Your sentinels have voting power of who is the current master and also electing a new master if the current master is down/unreachable. Your sentinels configration entry `down-after-milliseconds` (https://redis.io/topics/sentinel) defines "is the time in milliseconds an instance should not be reachable (either does not reply to our PINGs or it is replying with an error) for a Sentinel starting to think it is down".

If `down-after-milliseconds` is set to 60000, that translates to 60s. The redis-master needs to be down for 60s before your sentinels will vote for a new master. Your client application will not be able to issue commands to redis during that time.

If you want your queries to fail right away, I think you could disable offlineQueue as described here: https://github.com/luin/ioredis#offline-queue - I haven't tested it but I assume your client application will fail at the very moment your redis master is not functonal.

If you want your read operations to work while the master is down, you could use two sentinel connections (https://github.com/luin/ioredis#sentinel) where one specifies the `role: slave` options, while the other don't. The former will only connect to slaves instances as reported by your sentinel, and the latter will only connect to the master instance as reported by your sentinel.

Also have a look at Auto-reconnect and Reconnect on error (https://github.com/luin/ioredis#auto-reconnect) - those might provide an alternative approach to solve your use-case.

**Comment by kapalkat** [comment]
So I have also followed described scenario and in my opinion this bug needs to be reopened.
My setup: 3 sentinels, 3 redis slaves, 1 redis master.
Sentinels env_vars: "REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS": "10000".
I am simulating Redis master down with command: redis-cli -p 6379 DEBUG sleep 60.
Whats going on is:
After 10 seconds, sentinels know right a way about the failure and elects new master.
ioredis does NOT detect that! No error is passed. ioredis is still connected to the old master and my app hangs...
After 60 seconds when its back, ioredis detects that old master is not a master anymore and tries to reconnect to the new one with a success. 
The question is: why ioredis does not get new master from sentinels?
