### ISSUE TITLE
Will it support creating redis with redis-sentinel:// URL

### ISSUE THREAD

**Issue by KJlmfe** [luin/ioredis#557]
Hi @luin  Do you have a plan to support creating redis with `redis-sentinel:// URL`?

Example:

`redis-sentinel://no-user-name-for-redis:password@10.11.32.32:26379,10.11.32.33:26379,10.11.32.34:26379#mymaste`

**Comment by luin** [comment]
Is there a standard for this URL schema? For example, this is what ioredis follows for the `redis://` schema: https://www.iana.org/assignments/uri-schemes/prov/redis
