### ISSUE TITLE
sentinel偶尔连接异常

### ISSUE THREAD

**Issue by kobehaha** [luin/ioredis#558]
我这边配置了4个sentinel , 都是通过专线连接，偶尔就要报出2017-12-12 08:18:22: [ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 10ms， 这是由于连接的问题吗,或则是检测频率？还是真的连接不上？我用java也是同样的配置就没问题?

**Comment by luin** [comment]
出现这种问题是由于 client <--> redis server 的连接断开，这时 ioredis 会重新从 sentinels 中取 master 地址，如果 4 个 sentinel 都不能连接就会报这个错误。应该是网络问题，如果想深入了解可以通过 `DEBUG=ioredis:* node yourapp.js` 来打开日志。

**Comment by kobehaha** [comment]
好的，我这边再观察下。client<--->是保持长连接吧，能用类似连接池的概念保持多个连接，可能会好一些
