### ISSUE TITLE
API问题

### ISSUE THREAD

**Issue by xdsCoding** [luin/ioredis#566]
ioredis没有直接透传命令的api么，比如set test aaa命令，以redis协议传过来就是*3\r\n$3\r\nset\r\n$4\r\ntest\r\n$3\r\naaa\r\n，直接执行此命令得到结果，这样的功能是不是不具备啊

**Comment by luin** [comment]
嗯是的，不支持这个功能。是什么场景需要这个呢？

**Comment by xdsCoding** [comment]
我们做了一个redis中间代理，客户端是c的，使用hiredis客户端接口传过来的原始请求就是这种，如果有透传的话就不需要解析命令了，可以直接传到redis里面执行命令了
