### ISSUE TITLE
127.0.0.1 override every host set in constructor

### ISSUE THREAD

**Issue by Mokto** [luin/ioredis#568]
Hi,

With ioredis > 3.1.2, it is not possible to connect to adresses other than 127.0.0.1. The host is automatically replaced by 127.0.0.1.

I tried to use new Redis(object), new Redis(6379, host). Both are being replaced.

Thanks.

**Comment by divmgl** [comment]
Can we get a response on this? I'm just now facing this issue as well. Is the solution to downgrade?
