### ISSUE TITLE
 ioredis:connection skip reconnecting since the connection is manually closed.

### ISSUE THREAD

**Issue by kerrop33** [luin/ioredis#571]
I run a cluster like:
```
  const Redis = require('ioredis')
  const cluster = new Redis.Cluster([
    {
      port: 6379,
      host: '127.0.0.1'
    },
    {
      port: 6380,
      host: '127.0.0.1'
    }
  ])
  var i = 0
  const adapter = require('socket.io-redis')
  io.adapter(adapter({ pubClient: cluster, subClient: cluster }))
```
with ioredis 3.2.2, redis: 3.2.100 and redis-server configuration: cluster-enabled yes, ports 6379 and 6380.
My issue is when i start the app it spam

> cluster connect
> cluster -node
> cluster -node
> cluster reconnecting
> cluster +node
> cluster +node
> cluster -node
> cluster connect
> cluster -node
> cluster reconnecting

I try to run in debug mode  DEBUG=ioredis:* and this is the output(part of it):
> Sat, 13 Jan 2018 20:17:40 GMT ioredis:cluster status: [empty] -> connecting
> Sat, 13 Jan 2018 20:17:40 GMT ioredis:redis status[127.0.0.1:6379]: [empty] -> wait
> Sat, 13 Jan 2018 20:17:40 GMT ioredis:redis status[127.0.0.1:6380]: [empty] -> wait
> Sat, 13 Jan 2018 20:17:40 GMT ioredis:cluster getting slot cache from 127.0.0.1:6379
> Sat, 13 Jan 2018 20:17:40 GMT ioredis:redis status[127.0.0.1:6379]: wait -> connecting
> Sat, 13 Jan 2018 20:17:40 GMT ioredis:redis queue command[0] -> cluster(slots)
> Sat, 13 Jan 2018 20:17:40 GMT ioredis:redis status[127.0.0.1:6380]: wait -> connecting
> Sat, 13 Jan 2018 20:17:40 GMT ioredis:redis status[localhost:6379]: [empty] -> connecting
> Server running on port 3000
> Sat, 13 Jan 2018 20:17:40 GMT ioredis:redis status[127.0.0.1:6379]: connecting -> connect
> Sat, 13 Jan 2018 20:17:40 GMT ioredis:redis write command[0] -> info()
> Sat, 13 Jan 2018 20:17:40 GMT ioredis:redis status[127.0.0.1:6380]: connecting -> connect
> Sat, 13 Jan 2018 20:17:40 GMT ioredis:redis write command[0] -> info()
> Sat, 13 Jan 2018 20:17:40 GMT ioredis:redis status[127.0.0.1:6379]: connecting -> connect
> Sat, 13 Jan 2018 20:17:40 GMT ioredis:redis write command[0] -> info()
> Sat, 13 Jan 2018 20:17:40 GMT ioredis:redis status[127.0.0.1:6379]: connect -> ready
> Sat, 13 Jan 2018 20:17:40 GMT ioredis:connection send 1 commands in offline queue
> Sat, 13 Jan 2018 20:17:40 GMT ioredis:redis write command[0] -> cluster(slots)
> Sat, 13 Jan 2018 20:17:40 GMT ioredis:redis status[127.0.0.1:6380]: connect -> ready
> Sat, 13 Jan 2018 20:17:40 GMT ioredis:redis status[127.0.0.1:6379]: connect -> ready
> Sat, 13 Jan 2018 20:17:40 GMT ioredis:cluster status: connecting -> connect
> Sat, 13 Jan 2018 20:17:40 GMT ioredis:redis queue command[0] -> cluster(info)
> Sat, 13 Jan 2018 20:17:40 GMT ioredis:redis status[127.0.0.1:6380]: ready -> close
> Sat, 13 Jan 2018 20:17:40 GMT ioredis:connection skip reconnecting since the connection is manually closed.
> Sat, 13 Jan 2018 20:17:40 GMT ioredis:redis status[127.0.0.1:6380]: close -> end
> Sat, 13 Jan 2018 20:17:40 GMT ioredis:redis status[127.0.0.1:6379]: ready -> close
> Sat, 13 Jan 2018 20:17:40 GMT ioredis:connection skip reconnecting since the connection is manually closed.
> Sat, 13 Jan 2018 20:17:40 GMT ioredis:redis status[127.0.0.1:6379]: close -> end
> Sat, 13 Jan 2018 20:17:40 GMT ioredis:cluster status: connect -> close
> Sat, 13 Jan 2018 20:17:40 GMT ioredis:cluster status: close -> reconnecting
> Sat, 13 Jan 2018 20:17:40 GMT ioredis:delayqueue send 1 commands in failover queue
> Sat, 13 Jan 2018 20:17:40 GMT ioredis:cluster Cluster is disconnected. Retrying after 102ms
> Sat, 13 Jan 2018 20:17:40 GMT ioredis:cluster status: reconnecting -> connecting
> Sat, 13 Jan 2018 20:17:40 GMT ioredis:redis status[127.0.0.1:6379]: [empty] -> wait
> Sat, 13 Jan 2018 20:17:40 GMT ioredis:redis status[127.0.0.1:6380]: [empty] -> wait
> Sat, 13 Jan 2018 20:17:40 GMT ioredis:cluster getting slot cache from 127.0.0.1:6380
> Sat, 13 Jan 2018 20:17:40 GMT ioredis:redis status[127.0.0.1:6380]: wait -> connecting
> Sat, 13 Jan 2018 20:17:40 GMT ioredis:redis queue command[0] -> cluster(slots)
> Sat, 13 Jan 2018 20:17:40 GMT ioredis:redis status[127.0.0.1:6380]: connecting -> connect
> Sat, 13 Jan 2018 20:17:40 GMT ioredis:redis write command[0] -> info()
> Sat, 13 Jan 2018 20:17:40 GMT ioredis:redis status[127.0.0.1:6380]: connect -> ready
> Sat, 13 Jan 2018 20:17:40 GMT ioredis:connection send 1 commands in offline queue
> Sat, 13 Jan 2018 20:17:40 GMT ioredis:redis write command[0] -> cluster(slots)
> Sat, 13 Jan 2018 20:17:40 GMT ioredis:redis status[127.0.0.1:6379]: wait -> close
> Sat, 13 Jan 2018 20:17:40 GMT ioredis:connection skip reconnecting since the connection is manually closed.
> Sat, 13 Jan 2018 20:17:40 GMT ioredis:redis status[127.0.0.1:6379]: close -> end
> Sat, 13 Jan 2018 20:17:40 GMT ioredis:cluster status: connecting -> connect
> Sat, 13 Jan 2018 20:17:40 GMT ioredis:redis status[127.0.0.1:6380]: ready -> close
> Sat, 13 Jan 2018 20:17:40 GMT ioredis:connection skip reconnecting since the connection is manually closed.
> Sat, 13 Jan 2018 20:17:40 GMT ioredis:redis status[127.0.0.1:6380]: close -> end
> Sat, 13 Jan 2018 20:17:40 GMT ioredis:cluster status: connect -> close
> Sat, 13 Jan 2018 20:17:40 GMT ioredis:cluster status: close -> reconnecting
> Sat, 13 Jan 2018 20:17:40 GMT ioredis:delayqueue send 1 commands in failover queue
> Sat, 13 Jan 2018 20:17:40 GMT ioredis:cluster Cluster is disconnected. Retrying after 104ms
> Sat, 13 Jan 2018 20:17:40 GMT ioredis:cluster status: reconnecting -> connecting
> Sat, 13 Jan 2018 20:17:40 GMT ioredis:redis status[127.0.0.1:6379]: [empty] -> wait
> Sat, 13 Jan 2018 20:17:40 GMT ioredis:redis status[127.0.0.1:6380]: [empty] -> wait
> Sat, 13 Jan 2018 20:17:40 GMT ioredis:cluster getting slot cache from 127.0.0.1:6380
> Sat, 13 Jan 2018 20:17:40 GMT ioredis:redis status[127.0.0.1:6380]: wait -> connecting
> Sat, 13 Jan 2018 20:17:40 GMT ioredis:redis queue command[0] -> cluster(slots)
> Sat, 13 Jan 2018 20:17:40 GMT ioredis:redis status[127.0.0.1:6379]: wait -> connecting
> Sat, 13 Jan 2018 20:17:40 GMT ioredis:redis status[127.0.0.1:6380]: connecting -> connect
> Sat, 13 Jan 2018 20:17:40 GMT ioredis:redis write command[0] -> info()
> Sat, 13 Jan 2018 20:17:40 GMT ioredis:redis status[127.0.0.1:6379]: connecting -> connect
> Sat, 13 Jan 2018 20:17:40 GMT ioredis:redis write command[0] -> info()
> Sat, 13 Jan 2018 20:17:40 GMT ioredis:redis status[127.0.0.1:6380]: connect -> ready
> Sat, 13 Jan 2018 20:17:40 GMT ioredis:connection send 1 commands in offline queue
> Sat, 13 Jan 2018 20:17:40 GMT ioredis:redis write command[0] -> cluster(slots)
> Sat, 13 Jan 2018 20:17:40 GMT ioredis:redis status[127.0.0.1:6379]: connect -> ready
> Sat, 13 Jan 2018 20:17:40 GMT ioredis:cluster status: connecting -> connect
> Sat, 13 Jan 2018 20:17:40 GMT ioredis:redis queue command[0] -> cluster(info)
> Sat, 13 Jan 2018 20:17:40 GMT ioredis:redis status[127.0.0.1:6380]: ready -> close
> Sat, 13 Jan 2018 20:17:40 GMT ioredis:connection skip reconnecting since the connection is manually closed.
> Sat, 13 Jan 2018 20:17:40 GMT ioredis:redis status[127.0.0.1:6380]: close -> end
> Sat, 13 Jan 2018 20:17:40 GMT ioredis:redis status[127.0.0.1:6379]: ready -> close
> Sat, 13 Jan 2018 20:17:40 GMT ioredis:connection skip reconnecting since the connection is manually closed.
> Sat, 13 Jan 2018 20:17:40 GMT ioredis:redis status[127.0.0.1:6379]: close -> end
> Sat, 13 Jan 2018 20:17:40 GMT ioredis:cluster status: connect -> close
> Sat, 13 Jan 2018 20:17:40 GMT ioredis:cluster status: close -> reconnecting
> Sat, 13 Jan 2018 20:17:41 GMT ioredis:delayqueue send 1 commands in failover queue
> Sat, 13 Jan 2018 20:17:41 GMT ioredis:cluster Cluster is disconnected. Retrying after 106ms
> Sat, 13 Jan 2018 20:17:41 GMT ioredis:cluster status: reconnecting -> connecting
> Sat, 13 Jan 2018 20:17:41 GMT ioredis:redis status[127.0.0.1:6379]: [empty] -> wait
> Sat, 13 Jan 2018 20:17:41 GMT ioredis:redis status[127.0.0.1:6380]: [empty] -> wait
> Sat, 13 Jan 2018 20:17:41 GMT ioredis:cluster getting slot cache from 127.0.0.1:6380
> Sat, 13 Jan 2018 20:17:41 GMT ioredis:redis status[127.0.0.1:6380]: wait -> connecting
> Sat, 13 Jan 2018 20:17:41 GMT ioredis:redis queue command[0] -> cluster(slots)
> Sat, 13 Jan 2018 20:17:41 GMT ioredis:redis status[127.0.0.1:6379]: wait -> connecting
> Sat, 13 Jan 2018 20:17:41 GMT ioredis:redis status[127.0.0.1:6380]: connecting -> connect
> Sat, 13 Jan 2018 20:17:41 GMT ioredis:redis write command[0] -> info()
> Sat, 13 Jan 2018 20:17:41 GMT ioredis:redis status[127.0.0.1:6379]: connecting -> connect
> Sat, 13 Jan 2018 20:17:41 GMT ioredis:redis write command[0] -> info()
> Sat, 13 Jan 2018 20:17:41 GMT ioredis:redis status[127.0.0.1:6380]: connect -> ready
> Sat, 13 Jan 2018 20:17:41 GMT ioredis:connection send 1 commands in offline queue
> Sat, 13 Jan 2018 20:17:41 GMT ioredis:redis write command[0] -> cluster(slots)
> Sat, 13 Jan 2018 20:17:41 GMT ioredis:redis status[127.0.0.1:6379]: connect -> ready
> Sat, 13 Jan 2018 20:17:41 GMT ioredis:cluster status: connecting -> connect
> Sat, 13 Jan 2018 20:17:41 GMT ioredis:redis queue command[0] -> cluster(info)
> Sat, 13 Jan 2018 20:17:41 GMT ioredis:redis status[127.0.0.1:6379]: ready -> close
> Sat, 13 Jan 2018 20:17:41 GMT ioredis:connection skip reconnecting since the connection is manually closed.
> Sat, 13 Jan 2018 20:17:41 GMT ioredis:redis status[127.0.0.1:6379]: close -> end
> Sat, 13 Jan 2018 20:17:41 GMT ioredis:redis status[127.0.0.1:6380]: ready -> close
> Sat, 13 Jan 2018 20:17:41 GMT ioredis:connection skip reconnecting since the connection is manually closed.
> Sat, 13 Jan 2018 20:17:41 GMT ioredis:redis status[127.0.0.1:6380]: close -> end
> Sat, 13 Jan 2018 20:17:41 GMT ioredis:cluster status: connect -> close
> Sat, 13 Jan 2018 20:17:41 GMT ioredis:cluster status: close -> reconnecting

I think I miss something on redis-server settings of the cluster and I don't figure out what, or ioredis is making all the configuration needed ?
127.0.0.1 6379 cluster info:

> cluster_state:fail
> cluster_slots_assigned:0
> cluster_slots_ok:0
> cluster_slots_pfail:0
> cluster_slots_fail:0
> cluster_known_nodes:2
> cluster_size:0
> cluster_current_epoch:1
> cluster_my_epoch:1
> cluster_stats_messages_sent:0
> cluster_stats_messages_received:0

and for port 6380

> cluster_state:fail
> cluster_slots_assigned:0
> cluster_slots_ok:0
> cluster_slots_pfail:0
> cluster_slots_fail:0
> cluster_known_nodes:2
> cluster_size:0
> cluster_current_epoch:1
> cluster_my_epoch:1
> cluster_stats_messages_sent:0
> cluster_stats_messages_received:0

**Comment by GoBrianGo** [comment]
I have the same problem,too. Is it solved?

**Comment by gigi** [comment]
Same issue. Any updates?

**Comment by luin** [comment]
Hi @gigi, Could you post the debug logs here? The issues may be different since the cluster state is failed in the original poster's case.

**Comment by igorlimansky** [comment]
@luin 
hello, I'm experiencing same issue while trying to connect to redis-cluster which is port-forwarded to localhost from kubernetes ( redis cluster deployed via kubedb redis )
https://pastebin.com/5vy64G8J

here is how I'm trying to connect to it from code:
```
client = new Redis.Cluster(
  nodes.map(n => {
    const [ip, port] = n.split(':')
    return ({
      host: ip,
      port,
    })
  }),
  {
    enableOfflineQueue: true,
    natMapping: {
      '10.12.5.52:6379': { host: 'localhost', port: 6380 },
      '10.12.10.28:6379': { host: 'localhost', port: 6381 },
      '10.12.3.29:6379': { host: 'localhost', port: 6382 },
      '10.12.5.53:6379': { host: 'localhost', port: 6383 },
      '10.12.5.54:6379': { host: 'localhost', port: 6384 },
      '10.12.5.55:6379': { host: 'localhost', port: 6385 },
    },
    dnsLookup: async (address, callback) => {
      // const ip = await dns.lookupAsync(address)
      // console.log(address, '=>', ip)
      callback(null, address)
    },
  })
```

**Comment by igorlimansky** [comment]
ok, so I recreated redis cluster, now all slots are in right places and cluster info shows 'ok', but errors still the same, it keeps connecting and disconnecting because `Disconnect 127.0.0.1:6385 because the node does not hold any slot`

```
/data # redis-cli -c cluster slots
1) 1) (integer) 0
   2) (integer) 5460
   3) 1) "10.12.10.56"
      2) (integer) 6379
      3) "89689b18c44b74a75d0084ae87e8cfd2e968d1a1"
   4) 1) "10.12.5.88"
      2) (integer) 6379
      3) "170835484932d492ed4cec66e4d1c29975ddb2ae"
2) 1) (integer) 10923
   2) (integer) 16383
   3) 1) "10.12.12.33"
      2) (integer) 6379
      3) "9f73dc3f93225d302e70ad5e662be6fd8c3222e6"
   4) 1) "10.12.3.49"
      2) (integer) 6379
      3) "d5cd41c28a605b93e22cf85759cd70708ac8b883"
3) 1) (integer) 5461
   2) (integer) 10922
   3) 1) "10.12.2.34"
      2) (integer) 6379
      3) "49fa10062ecb102071208d811f791c6513faeda5"
   4) 1) "10.12.11.43"
      2) (integer) 6379
      3) "9d04fdee6848fe66980c257c05ec7d7b01e931a3"
/data # exit
➜  kubectl exec -it redis-cluster2-shard0-0 -c redis -- sh
/data # redis-cli -c cluster slots
1) 1) (integer) 0
   2) (integer) 5460
   3) 1) "10.12.10.56"
      2) (integer) 6379
      3) "89689b18c44b74a75d0084ae87e8cfd2e968d1a1"
   4) 1) "10.12.5.88"
      2) (integer) 6379
      3) "170835484932d492ed4cec66e4d1c29975ddb2ae"
2) 1) (integer) 10923
   2) (integer) 16383
   3) 1) "10.12.12.33"
      2) (integer) 6379
      3) "9f73dc3f93225d302e70ad5e662be6fd8c3222e6"
   4) 1) "10.12.3.49"
      2) (integer) 6379
      3) "d5cd41c28a605b93e22cf85759cd70708ac8b883"
3) 1) (integer) 5461
   2) (integer) 10922
   3) 1) "10.12.2.34"
      2) (integer) 6379
      3) "49fa10062ecb102071208d811f791c6513faeda5"
   4) 1) "10.12.11.43"
      2) (integer) 6379
      3) "9d04fdee6848fe66980c257c05ec7d7b01e931a3"
/data # exit
➜  kubectl exec -it redis-cluster2-shard1-0 -c redis -- sh
/data # redis-cli -c cluster slots
1) 1) (integer) 5461
   2) (integer) 10922
   3) 1) "10.12.2.34"
      2) (integer) 6379
      3) "49fa10062ecb102071208d811f791c6513faeda5"
   4) 1) "10.12.11.43"
      2) (integer) 6379
      3) "9d04fdee6848fe66980c257c05ec7d7b01e931a3"
2) 1) (integer) 10923
   2) (integer) 16383
   3) 1) "10.12.12.33"
      2) (integer) 6379
      3) "9f73dc3f93225d302e70ad5e662be6fd8c3222e6"
   4) 1) "10.12.3.49"
      2) (integer) 6379
      3) "d5cd41c28a605b93e22cf85759cd70708ac8b883"
3) 1) (integer) 0
   2) (integer) 5460
   3) 1) "10.12.10.56"
      2) (integer) 6379
      3) "89689b18c44b74a75d0084ae87e8cfd2e968d1a1"
   4) 1) "10.12.5.88"
      2) (integer) 6379
      3) "170835484932d492ed4cec66e4d1c29975ddb2ae"
/data # redis-cli -c cluster info
cluster_state:ok
cluster_slots_assigned:16384
cluster_slots_ok:16384
cluster_slots_pfail:0
cluster_slots_fail:0
cluster_known_nodes:6
cluster_size:3
cluster_current_epoch:3
cluster_my_epoch:2
cluster_stats_messages_ping_sent:4520
cluster_stats_messages_pong_sent:4523
cluster_stats_messages_meet_sent:2
cluster_stats_messages_sent:9045
cluster_stats_messages_ping_received:4520
cluster_stats_messages_pong_received:4522
cluster_stats_messages_meet_received:3
cluster_stats_messages_received:9045
```
