### ISSUE TITLE
Will enableOfflineQueue:false conflict when it's in both cluster config and redisOptions?

### ISSUE THREAD

**Issue by Zetazzz** [luin/ioredis#575]
There are two "enableOfflineQueue: false" in both cluster config and redisOptions.

```
const ioredis = require('ioredis');
const redis = new ioredis.Cluster([
  { host: 'xxx', port: xxx },
  { host: 'xxx', port: xxx },
  { host: 'xxx', port: xxx }
], {
    enableOfflineQueue: false,   --enableOfflineQueue: false in cluster config
    enableReadyCheck: true,
    redisOptions: {
      family: 4,
      dropBufferSupport: true,
      enableReadyCheck: true,
      enableOfflineQueue: false  --enableOfflineQueue: false in redisOptions
    }
  });
redis.on('error', (e) => {
  console.log('Error: %s', e.message);
  console.log('NodeError: %s', e.lastNodeError.message);
});
redis.once('ready', () => {
  console.log('redis ready');
});
```

after running the code above, there's an error: Stream isn't writeable and enableOfflineQueue options is false. 

Is there conflict with these config?

Thank you very much!

**Comment by Zetazzz** [comment]
Forgot one thing.

"redis.once('ready' ..."  was not executed. "on error" was executed and print "node error Error: Stream isn't writeable and enableOfflineQueue options is false"

**Comment by ccs018** [comment]
I having a similar issue, but I'm getting a different failure - the client never connects to the cluster.  See issue #581.  Maybe it's a dupe, but these need investigation.

**Comment by ccs018** [comment]
Keep alive.

**Comment by ccs018** [comment]
Keep alive. This issue still needs to be resolved.

**Comment by ccs018** [comment]
freshbot

**Comment by ccs018** [comment]
Can it be clarified how these two options interact or don't interact?

**Comment by luin** [comment]
`enableOfflineQueue` in `redisOptions` is set to `true` by default and can't be changed in v4. It has no connection with `enableOfflineQueue` in the cluster options.
