### ISSUE TITLE
[Cluster] Failed to load script by sha1

### ISSUE THREAD

**Issue by dg3feiko** [luin/ioredis#58]
```js
require("co")(function *() {
  try
  {    
    var sha1 = yield cluster.script("load","return {KEYS[1],ARGV[1],ARGV[2]}  ");
    console.log(sha1);
    var res = yield cluster.evalsha(sha1, 1, "hello","world","1234");
    console.log(res);
    
  }catch(e)
  {
    console.error(e)  
  }
  
})
```

result
```js

6c93d86d0ba4c64778fe11439a0aa890a1425097 //sha1


{ [ReplyError: NOSCRIPT No matching script. Please use EVAL.]
  name: 'ReplyError',
  message: 'NOSCRIPT No matching script. Please use EVAL.',
  command:
   { name: 'evalsha',
     args:
      [ '6c93d86d0ba4c64778fe11439a0aa890a1425097',
        '1',
        'hello',
        'world',
        '1234' ] } }
```

It doesn't always have such error, depends on the content of script, so I suspect it depends on the sha1 key is in the instance (which is client connecting for turning to) or not.

**Comment by luin** [comment]
When invoking a command without a key associated(like `script load`, `info` etc.), the command will be sent to a random node. In your case, `script load` and `evalsha` may be sent to the different nodes.

You can use custom commands instead:

```javascript
redis.defineCommand('echo', {
  numberOfKeys: 1,
  lua: 'return {KEYS[1],ARGV[1],ARGV[2]}  '
});

require('co')(function *() {
  var res = yield redis.echo('hello', 'world', '1234');
  console.log(res);
});
```

You can also use pipelining to send multiple commands to the same node.

REF:
https://github.com/luin/ioredis#lua-scripting
https://github.com/luin/ioredis#pipelining
https://github.com/luin/ioredis#transaction-and-pipeline-in-cluster-mode

**Comment by dg3feiko** [comment]
Thank you for responsive reply, but actually there are so many npm modules using `load` then `evalsha` to perform their functionalities, changing syntax is hard for them (and us). 

Could u make it support script load/eval to/from all nodes?

**Comment by luin** [comment]
Dealing with a cluster is not as same as dealing with a single redis node. It's inevitable to make some changes on the application side in order to migrate to a Redis cluster.
I'm considering add a `broadcast` method to send commands to all of the nodes though:

```javascript
cluster.broadcast().script('load', 'return {KEYS[1],ARGV[1],ARGV[2]}');
```

**Comment by dg3feiko** [comment]
That's nice and at least make something work at this moment

**Comment by luin** [comment]
Btw, you can access nodes in the cluster via `cluster.nodes` and send commands to all of them yourself:

```javascript
yield Promise.all(Object.keys(cluster.nodes).map(function (nodeName) {
  var node = cluster.nodes[nodeName];
  return node.script('load');
}));
```
