### ISSUE TITLE
Connection pooling

### ISSUE THREAD

**Issue by billybonks** [luin/ioredis#580]
I read through the code, and from what I can gather with a single Redis instance when I connect ioredis. It opens a connection with the KEEP_ALIVE flag. From that point on it streams commands through the connection.

1. your code manages a queue, does that mean that it wait's for the last command to return before sending another command.

2. what performance improvements would you see in having connection pooling for a single Redis client?

Ideally, I would like that commands to get sent to Redis asap so that when Redis completes processing of the current command it can start processing the next one right away instead of waiting for the next command.

**Comment by garthk** [comment]
Dup of #123, closed as `wontfix`.
