### ISSUE TITLE
redis server连接不上如何错误处理

### ISSUE THREAD

**Issue by tftiancai** [luin/ioredis#59]
请问下如果redis服务器连接不上，ioredis针对这种error如何获取？

**Comment by luin** [comment]
可以参考这里：
https://github.com/luin/ioredis#auto-reconnect
https://github.com/luin/ioredis#connection-events

当连接不上时，ioredis 会发出 `close` 事件，并调用 `retryStrategy`，如果返回数字则重试，否则发出 `end` 事件。

**Comment by tftiancai** [comment]
retryStrategy 如果没有设置，会不停的发出error事件？
```
var client = new Redis(redisConfig.port, redisConfig.ip);
  client.on('error',function(error){
    console.log("error:"+ error);
  });
````

这样会不停的打印出

Error: connect ECONNREFUSED

**Comment by luin** [comment]
retryStrategy 是有默认值的，文档里有写，所以不设置 retryStrategy 的话会不断进行重连。如果无法连接会报错然后断开，即先发出 `error` 事件，再发出 `close` 事件。

**Comment by tftiancai** [comment]
ok，client放置在request中
```
var client = new Redis(redisConfig.port, redisConfig.ip);
```

每次用完需要quit或者disconnect吗？

**Comment by luin** [comment]
这个要取决于你的应用场景，如果不 quit 的话连接会一直保持。一个应用保持十几个连接是没问题的，当进程退出后，所有连接都会自动断开。但如果每次请求都创建一个新连接，连接数量无限上涨肯定就不行了，要手动 quit。

**Comment by tftiancai** [comment]
这么说应该是应用级别，应该有个类似连接池的概念

1、怎么初始化多个连接

     var client_1 = new Redis(redisConfig.port, redisConfig.ip);
     var client_2 = new Redis(redisConfig.port, redisConfig.ip);
     ....

2、每次连接都需要手动指定哪个吗？

**Comment by luin** [comment]
这个与你的应用逻辑相关，Redis 是单进程的，所以建立多个连接没必要

**Comment by tftiancai** [comment]
ioredis是node的client，最佳实践是？
1、放在node的server进程里面，随着server的启动创建多个连接，server的关闭也自动将所有的连接关闭；
2、放置请求过程当中，每次随着请求创建连接，请求结束关闭连接；

**Comment by luin** [comment]
肯定是第一个

**Comment by tftiancai** [comment]
非常感谢！ioredis本身有连接池的设计吗？它是始终只有一个连接还是会自动维护多个？

**Comment by luin** [comment]
没有连接池的设计

**Comment by tftiancai** [comment]
多谢回馈哈！
