### ISSUE TITLE
how to know which key exist in `exists`'s callback?

### ISSUE THREAD

**Issue by bi-kai** [luin/ioredis#591]
Query 10 key in a DB, I want to know if they are existed before query, I use `exists` api in a for loop, but I can only get 0 or 1 in `exists`'s callback, I do not know which key it belongs to, how to solve this situation?
AKA, wanna query many key in a DB, remove unavailable ones, the result is real key list in redis.

Should I use `pipline` or `promise.all` with this?

**Comment by ccs018** [comment]
This is a Redis API question, not ioredis.  The Redis API does not inform you which key or keys exists.  It reports how many of the specified keys exist.  See the Redis API documentation:  https://redis.io/commands/exists.  If you want to know which specific keys exists or not, then you need to check each key one-by-one.

Though I don't understand why you would want to first check if a key exists before querying.  If they key doesn't exist, then the response to the query will be null.  Why make it a 2-step process when the query would be sufficient?

**Comment by bi-kai** [comment]
@ccs018 hi, I just want to get all the key and value in a DB.
Before get the value, I need to know what keys it holds.

**Comment by ccs018** [comment]
Then use the KEYS command.  https://redis.io/commands/keys
"keys *" will return all of the keys in the database.
You can also try the SCAN command. https://redis.io/commands/keys

**Comment by bi-kai** [comment]
@ccs018 yes, I am using `keys *` now, #590. 
The codes are quite long to solve:
1. async;
2. query results are in different callback;
If it's sync, code will be more cleaner.
