### ISSUE TITLE
Redis mass insert

### ISSUE THREAD

**Issue by subesokun** [luin/ioredis#592]
I need to create a big amount of keys (~ 1,000,000) as fast as possible and so far I was experimenting with `node_redis` but it didn't perform that well with so many keys. While looking for optimizations I came across this topic https://redis.io/topics/mass-insert and was wondering if `ioredis` supports such piping feature like in the redis-cli. Ideally I would like to stream the data directly from a file into Redis via `ioredis` to avoid loading everything into RAM.

Thanks a lot for any hints!

**Comment by yan-foto** [comment]
This would be a nice feature, for example, for tests, where you'd want to use the API to mass insert data sets (from an appendonly file) to your redis instance.
