### ISSUE TITLE
Sending a number type argument for Lua-scripted commands

### ISSUE THREAD

**Issue by zeodtr** [luin/ioredis#598]
Currently, ioredis converts all arguments for a command to strings. It seems Ok for built-in commands. But for a Lua-scripted commands created by defineCommand(), it's somewhat inconvenient when a number-type argument is needed for a Lua statement.

For example, one cannot write Lua script like this:

`if redis.call("zrank", KEYS[1], ARGV[2]) < ARGV[1] then`

Instead, it should be written as follows:

`if redis.call("zrank", KEYS[1], ARGV[2]) < tonumber(ARGV[1]) then`

It would be great if there is a way to send a number type argument for Lua-scripted commands.

**Comment by luin** [comment]
Thank you for the pull request! I'm not sure whether it is valid to send arguments with the type of number. According to the RESP documentation: https://redis.io/topics/protocol:

    A client sends to the Redis server a RESP Array consisting of just Bulk Strings.

**Comment by zeodtr** [comment]
@luin Thank you for your response.
I see that's the limitation of Redis.
I will close this issue.
