### ISSUE TITLE
Lazily connect to the Redis

### ISSUE THREAD

**Issue by luin** [luin/ioredis#6]
Currently when a Redis instance is created, a connection to Redis server is established at the same time. Let's add an option to enable lazy connecting that the connection wouldn't be established until a command is invoked.

**Comment by adoyle-h** [comment]
The feature has been implemented?

**Comment by luin** [comment]
@adoyle-h Yes, refer to https://github.com/luin/ioredis/blob/master/API.md for `lazyConnect`

**Comment by adoyle-h** [comment]
I get it. thanks

**Comment by Kamil93** [comment]
There is a bug right now, if u set `lazyConnect = true`, still Redis can connect itself without you calling `.connect()`, just use any redis commands.
