### ISSUE TITLE
support for lua script keys/args as array

### ISSUE THREAD

**Issue by bendpx** [luin/ioredis#60]
My script support dynamic number of keys/agrs, so I want to be able and do something like this:

redis.defineCommand('echo', {
  lua: ''
});

var KEYS = ['k1', 'k2'];
var ARGS = ['a1', 'a2', 'a3'];

redis.echo(KEYS, ARGS, function (err, result) {
});

KEYS = ['k1', 'k2', 'k3'];
ARGS = ['a1', 'a2', 'a3', 'a4'];

redis.echo(KEYS, ARGS, function (err, result) { 
});

any chance?

**Comment by luin** [comment]
Either
```javascript
redis.echo(3, 'k1', 'k2', 'k3', 'a1', 'a2', 'a3', 'a4', function() {});
```
or
```javascript
redis.echo(3, KEYS, ARGS, function() {});
```
works.

**Comment by bendpx** [comment]
second option is perfect. thanks
