### ISSUE TITLE
ioredis keeps connecting to 127.0.0.1 even though host is different

### ISSUE THREAD

**Issue by divmgl** [luin/ioredis#601]
I'm having an issue connecting to a Redis instance that is not bound to 127.0.0.1. Even after verifying that the configuration is correct and specifying different IPs, I'm getting the following error:

```
error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
```

I'm pretty much dead in the water here as the entire app is written in ioredis. It was working fine a few days ago. Did something change? Thanks.

edit:

The options seem correct for the client as well, which is baffling.

```
   { host: 'ion_redis_1',
     port: 6379,
     family: 4,
     connectTimeout: 10000,
     retryStrategy: [Function: retryStrategy],
     keepAlive: 0,
     noDelay: true,
     connectionName: null,
     sentinels: null,
     name: null,
     role: 'master',
     sentinelRetryStrategy: [Function: sentinelRetryStrategy],
     password: null,
     db: 0,
     dropBufferSupport: false,
     enableOfflineQueue: true,
     enableReadyCheck: true,
     autoResubscribe: true,
     autoResendUnfulfilledCommands: true,
     lazyConnect: false,
     keyPrefix: '',
     reconnectOnError: null,
     readOnly: false,
     stringNumbers: false,
     showFriendlyErrorStack: false }
```

I've already checked and `ion_redis_1` does NOT point to `127.0.0.1`. Changing the port also doesn't work (always tries 6379).

**Comment by ivanvanderbyl** [comment]
@divmgl did you resolve this? I'm having the same issue, as soon as the library is required it tries to connect to `localhost:0`
```
  ioredis:redis status[localhost:0]: [empty] -> connecting +0ms
  ioredis:redis status[localhost:0]: [empty] -> connecting +2ms

  ioredis:connection error: Error: connect EADDRNOTAVAIL 127.0.0.1 - Local (0.0.0.0:61722) +437ms
{ Error: connect EADDRNOTAVAIL 127.0.0.1 - Local (0.0.0.0:61722)
    at Object._errnoException (util.js:1031:13)
    at _exceptionWithHostPort (util.js:1052:20)
    at internalConnect (net.js:977:16)
    at GetAddrInfoReqWrap.emitLookup [as callback] (net.js:1119:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:100:10)
  errno: 'EADDRNOTAVAIL',
  code: 'EADDRNOTAVAIL',
  syscall: 'connect',
  address: '127.0.0.1' }
```

Strangely this only happens when in test mode and using Mocha/Chai.

**Comment by divmgl** [comment]
The issue was actually not with `ioredis` but with `redfour` which doesn't support using `ioredis` as a client. `ioredis` was working just fine.

Not sure if this will help, but check that the environment variable in the context of the **running** application is correctly set. Usually that resolves issues for me.

**Comment by tomharrison** [comment]
You can be affected by this if you pass the port as an environment variable. [Redis.prototype.parseOption] has different behavior](https://github.com/luin/ioredis/blob/622975d9d454eca6a9c495d35f5638d68e2662f2/lib/redis.js#L207) depending on the arity of the constructor. It tests if `(typeof port === 'number')` however the values in `process.env` are going to be strings. Try using `parseInt` on the port before passing it into ioredis.
