### ISSUE TITLE
Allow round robin cluster node seleciton

### ISSUE THREAD

**Issue by elliotttf** [luin/ioredis#608]
I've noticed while load testing the ioredis cluster functionality with a two shard, three replica cluster that a significantly higher portion of traffic is being directed at one master vs the other. Some of this may have to do with the traffic shape, but regardless I think it'd be a good improvement to allow round robin node selection rather than random node selection as random will most likely not be evenly distributed among the cluster.

**Comment by ccs018** [comment]
Are you sure you're really using a Redis Cluster?  First, per the Redis
documentation (https://redis.io/topics/cluster-tutorial), a Redis Cluster
is required to have a minimum of 3 shards:

"Note that the minimal cluster that works as expected requires to contain
at least three master nodes."

Second, per the Redis Cluster specifications, data is sharded based on a
specific hash function on the keys being used.  A Redis Cluster client does
not decide on its own to which shard to direct traffic to - it is
determined by the keys being used.

I highly recommend you read up on the documentation describing how a Redis
Cluster works.  What you're suggesting ioredis do completely violates that
specification.

**Comment by elliotttf** [comment]
Yes I'm sure. I am using an elasticache cluster with two shards and three replicas each. It seems that the three node configuration is not a hard requirement but a very strong recommendation to allow HA during node failures. Regardless, I will update my configuration.

I should have been more specific in my original comment, the selection of where to send writes to isn't what I want to round robin as that is clearly determined by the cluster. What I'd like to change is the selection of which node within a cluster a read command is sent to. Currently, this is selected [at random](https://github.com/luin/ioredis/blob/v3.2.2/lib/cluster/index.js#L512-L515) for read-safe commands. I feel allowing this selection to be round robin rather than random would allow for a more even distribution of commands within a cluster.
