### ISSUE TITLE
how to del key?

### ISSUE THREAD

**Issue by tunglunnho** [luin/ioredis#609]
this.redis.del(key);
I want to delete key, should i do the way?

**Comment by luin** [comment]
Yes.

**Comment by GeniusBrother** [comment]
@luin ioredis support unlink? i can't find this command

**Comment by luin** [comment]
> @luin ioredis support unlink? i can't find this command

Where can't you find this command? Have you tried `redis.unlink`?

**Comment by GeniusBrother** [comment]
@luin i use typescript, may be not the declare

**Comment by GeniusBrother** [comment]
Does ioredis has method of sending arbitrary commands? just like send_command of node_redis

**Comment by luin** [comment]
Check out redis.call

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________
