### ISSUE TITLE
Set command converts the value to string by default

### ISSUE THREAD

**Issue by gaowhen** [luin/ioredis#612]
if one JSON object is stringfied by  `JSON.stringify`  and saved to redis by `set`. When it is `get` and been `JSON.parse`, it's still string.

Then by testing I find the value is converted to string by default, I don't know if this is a feature by design. there're no description in API document.

**Comment by ccs018** [comment]
Using `JSON.stringify()` and `JSON.parse()` is exactly how I'm using ioredis/redis and when I get the value and pass it through `JSON.parse()` I get an object.  `JSON.parse()` returns an object and does not modify the original input.

```
origValue = { a: 1, b: 2 };
key = 'abc';
redis.set(key, JSON.stingify(origValue));
value = redis.get(key);
parsedValue = JSON.parse(value);
```

`value` is still a string.  `parsedValue` equals `origValue`.
