### ISSUE TITLE
redis.status is still `ready` after `redis.quit()` resolves

### ISSUE THREAD

**Issue by LewisJEllis** [luin/ioredis#614]
I'm not certain that this is a bug, but it definitely surprised me while migrating from node_redis. I would not expect the second console log to still be `ready` in this example:
```js
const Redis = require('ioredis');
const client = new Redis();

async function run() {
  await new Promise(resolve => setTimeout(resolve, 100)); // make sure we're connected
  console.log('initial', client.status); // 'ready'
  client.quit().then(() => {
    console.log('quit resolve', client.status); // still 'ready' :/
    setTimeout(() => console.log('timeout', client.status), 0); // but now 'end'
  });
}
run();
```
In node_redis the `client.ready` boolean (which ioredis' `client.status` seems to parallel) will be false by the same point, so I would expect here that `client.status` would no longer be `ready`.

Full debug output:
```
$ DEBUG=ioredis:* node test.js
  ioredis:redis status[localhost:6379]: [empty] -> connecting +0ms
  ioredis:redis status[127.0.0.1:6379]: connecting -> connect +7ms
  ioredis:redis write command[0] -> info() +1ms
  ioredis:redis status[127.0.0.1:6379]: connect -> ready +4ms
initial ready
  ioredis:redis write command[0] -> quit() +97ms
quit resolve ready
  ioredis:redis status[127.0.0.1:6379]: ready -> close +2ms
  ioredis:connection skip reconnecting since the connection is manually closed. +0ms
  ioredis:redis status[127.0.0.1:6379]: close -> end +0ms
timeout end
```

After `redis.quit()` resolves, how would you recommend inspecting that the client is, in fact, in a non-ready state? Do I need to `quit()` and then also wait for a `redis.on('close')` event, or should the `quit()` command instead not resolve until `redis.status` has been updated?

**Comment by skeggse** [comment]
One workaround, if you're looking to determine whether the connection is still good-to-use (synchronously - not by issuing a command), is to check the private `manuallyClosing` field. It would be really nice if this was accurately and consistently reflected in the `status` field; the cluster implementation sets the `status` to `closing`.
