### ISSUE TITLE
Values serialization when using hmset

### ISSUE THREAD

**Issue by Shahor** [luin/ioredis#616]
Hello,

Is there a way to store `null` values in an `hash` in a way that we get the `null` in return when querying Redis?

```js
const redis = new require('ioredis')()

async function main() {
  await redis.hmset('foo', {
    a: true,
    b: false,
    c: undefined,
    d: null,
  })

  const values = await redis.hgetall('foo')

  console.log(values)
  process.exit()
}

main()
```

Result
```sh
{ a: 'true', b: 'false', c: '', d: '' }
```

I added `c: undefined` for the sake of the example.

As you can see `d` here is an empty string, which is different from `null`.

Is there any workaround this?

**Comment by luin** [comment]
Actually, you can't. The value of each field in a hash key should be a string. Redis doesn't support other data types other than that.

You may want to use `JSON.stringify({/* your object */})` and store the result in Redis.

**Comment by Shahor** [comment]
I went that way indeed.

Thanks for your answer :)

**Comment by lixaotec** [comment]
What about running a Faceted counters agains json data? is it the best way to do?
