### ISSUE TITLE
关于您源码中的一些疑问？

### ISSUE THREAD

**Issue by LastKing** [luin/ioredis#617]
作者您好，本人英文不好，怕不能正确的表达意思，所以采用中文提问
最近在阅读您的源码，阅读到关于您的代码处理结果这一块
```
parse.js 中
 item = this.commandQueue.shift();
从commandQueue中拉出最新的那一条命令resolve结果，并且返回给前台
```
我知道node和redis是单线程的，但是不用考虑它们两网络延迟的原因么？
就比如以下情况：
同事有两个2请求 一个`get test1` 一个`get test2`
这样直接从queue中获取返回结果reslove能保证结果的数据绝对的顺序么？

ioredis所有的连接是建立在一条tcp连接上的，我看了源码就是`net.creaateServer `，这样就能保证数据的顺序性么？
我都是猜的。。。如果您觉得我以上观点有什么问题，或者能告诉我上面知识我需要从网络的那一部分补齐。
敬请您的指教，谢谢~！~！~

**Comment by luin** [comment]
嗯，是可以保证顺序的。因为是单链接，所以先发的会先到 Redis，也会被先处理并返回。

**Comment by GeniusBrother** [comment]
先处理的一定会先到达吗？
