### ISSUE TITLE
README leaves open question about node_redis

### ISSUE THREAD

**Issue by fgarcia** [luin/ioredis#618]
The current README [mentions](https://github.com/luin/ioredis#consolidation-its-time-for-celebration) the work coordination with node_redis

Reading that section is not clear if:
1. The libraries will merge in the long run
2. The libraries will just share code but coexist to provide two API flavors that developers can choose.

I really like how ioredis handles promises but I was wondering about future API break if/during a merge

**Comment by fgarcia** [comment]
the issue still needs an answer

**Comment by ccs018** [comment]
Any update???
