### ISSUE TITLE
LUA eval not recognizing key slot

### ISSUE THREAD

**Issue by knguyen2525** [luin/ioredis#62]
I am using the cluster access capabilities of ioredis. Running scripts that SET data are working, but when trying to run a simple GET:
"return redis.call('GET', 'foo')"
the client is not able to recognize where the key "foo" is stored in the cluster.

Is there a way to do this besides parsing CLUSTER SLOTS to find the keyslot for foo manually?

**Comment by AVVS** [comment]
you cant really do that, you need to supply keys amount to defineCommand, all the keys passed to LUA script must be on the same machine and this is the only way you can use lua scripts on the cluster, you cant make calls to other machines from lua scripts either, check the tutorial on the redis cluster

**Comment by knguyen2525** [comment]
Oh I see. I just read the documentation more closely and get your point.

Thanks

**Comment by thelinuxlich** [comment]
coming back to this issue, @AVVS are you sure all the keys explicitly declared on EVAL command need to be on the same machine? According to EVAL docs:

```
All Redis commands must be analyzed before execution to determine which keys the command will operate on. In order for this to be true for EVAL, keys must be passed explicitly. This is useful in many ways, but especially to make sure Redis Cluster can forward your request to the appropriate cluster node.
```

**Comment by AVVS** [comment]
Just try calling redis.call("get", key) from lua with key that is not on an executing cluster machine. Standard multi-key cluster constraints are applicable here. So yes, I'm sure

**Comment by thelinuxlich** [comment]
redis.call("get",KEYS[1]) you mean?

**Comment by AVVS** [comment]
No, key must be from another machine.

KEYS[1] must be on master A, 
ARGV[1] should be on master that is not A, call redis.call("get", ARGV[1])

**Comment by thelinuxlich** [comment]
but if it is on the KEYS array it should work, right?

**Comment by AVVS** [comment]
Only if all keys belong to a single machine, otherwise it wont

**Comment by thelinuxlich** [comment]
This seems impracticable, how should I know that in advance?

**Comment by AVVS** [comment]
Use prefix that gives you constant hash values, like {xxx}

**Comment by thelinuxlich** [comment]
Understood
