### ISSUE TITLE
Adding new builtin commands and transformers

### ISSUE THREAD

**Issue by ksmithut** [luin/ioredis#621]
I am currently playing around with [redis streams](https://gist.github.com/antirez/4e7049ce4fce4aa61bf0cfbc3672e64d) (and [here](https://gist.github.com/antirez/68e67f3251d10f026861be2d0fe0d2f4) which add some new commands. I don't think these commands are available for production use, but I assume they'll be added to the list of commands currently in the `redis-commands` module when they're ready.

Until then, I'm currently looking to add these commands to my ioredis instance. What is the best way to do this that will support things like pipelines and transactions? The way I got it to work seems hacky (using and overriding prototypes), but this is what I've got so far:

```js
const { string, buffer } = Redis.prototype.createBuiltinCommand('xadd')
Redis.prototype.xadd = string
Redis.prototype.xaddBuffer = buffer
Redis.Command.setArgumentTransformer('xadd', args => /* TODO */ args)
Redis.Command.setReplyTransformer('xadd', reply => /* TODO */ reply)
```

**Comment by ksmithut** [comment]
It appears that this doesn't add it to the multi pipelining. It would be great to have an answer for this, even if the answer is "we don't support adding custom commands".

**Comment by ksmithut** [comment]
```js

**Comment by luin** [comment]
Sorry for the late response! Yes, adding commands to pipeline directly should do the trick. XADD command will be added as soon as it's added into the redis-commands package.

**Comment by ksmithut** [comment]
Awesome, thanks :)
