### ISSUE TITLE
How to subscribe by patern?

### ISSUE THREAD

**Issue by Sailor20** [luin/ioredis#629]
For example, I want subscribe the channel by start of price_*,what should i do?

**Comment by Sailor20** [comment]
`this.subClient.psubscribe('price_*', (err, count) => {
      console.warn(`subscribe worker pid: ${process.pid} subscribe: message count：${count}`);
    });`

**Comment by luin** [comment]
This code is correct. What problem did you encounter?

**Comment by Sailor20** [comment]
the patern price_* was not work, my redis version is 2.8, but I edit 

```
    this.subClient.psubscribe('price_*', (err, count) => {
      console.warn(`subscribe worker pid: ${process.pid} subscribe: message count：${count}`);
    });
```
to
```
    this.subClient.subscribe('price_kline', (err, count) => {
      console.warn(`subscribe worker pid: ${process.pid} subscribe: message count：${count}`);
    });
```

It  can be work! what should i do?

**Comment by roccomuso** [comment]
did you solve?
