### ISSUE TITLE
Flow type error:  Cannot call redis.rpoplpush(...).then because property then is missing in undefined

### ISSUE THREAD

**Issue by tchiss** [luin/ioredis#631]
Hi,
I'm having a flow check error when I call `rpoplpush`method.
Here is the line:
`return redis.rpoplpush(config.mq.topics.queue, config.mq.topics.processing).then((data) => (typeof data === 'string' ? Promise.resolve(data) : Promise.resolve('')));`

Here is the error:
`Cannot call redis.rpoplpush(...).then because property then is missing in undefined [1].`

I checked the `flow-type` definition file of ioredis and I saw this:

`rpoplpush(args: any[], callback: ResCallbackT<any>): void;`
`rpoplpush(...args: any[]): Promise<any>;`

How can I specify to flow that I want to use the second method (`rpoplpush(...args: any[]): Promise<any>`) ?

Thanks

**Comment by luin** [comment]
The definition may be out of date. Every command returns a Promise no matter whether the last argument is a function.
