### ISSUE TITLE
Unable to connect to sentinel using jedissentinelpool

### ISSUE THREAD

**Issue by ManasSaxenaTil** [luin/ioredis#632]
I am trying to connect to redis sentinel using JedisSentinelPool

private static final JedisSentinelPool pool = new JedisSentinelPool("mymaster", getSentinels());
private static Set getSentinels(){

    Set<String> mysentinels = new HashSet<>();
    mysentinels.add(new HostAndPort("localhost", 26379).toString());
    return mysentinels;
}

This gives me following error :

"Caused by: redis.clients.jedis.exceptions.JedisConnectionException: All sentinels down, cannot determine where is mymaster master is running..."

However, i can see my sentinel is running . So referring to this post: https://github.com/luin/ioredis/issues/64 I tried the below command on my redis master server

./redis-cli -h redis-1 -p 26379

I got following error : Could not connect to Redis at redis-1:26379: nodename nor servname provided, or not known

PS: I have my master running and sentinel both runnign in localhost , master port: 6379 , sentinel port: 26379 and i am using mac

What is the issue here?

**Comment by luin** [comment]
It seems to be a issue on Jedis, not ioredis. Closing

**Comment by ManasSaxenaTil** [comment]
but even redis cli is giving this error ./redis-cli -h redis-1 -p 26379

I got following error : Could not connect to Redis at redis-1:26379: nodename nor servname provided, or not known
