### ISSUE TITLE
Is there a unified way to connect to Redis regardless of weather it's a cluster or single server?

### ISSUE THREAD

**Issue by aalexgabi** [luin/ioredis#638]
I had to add an if to handle the both the cluster mode and the single node mode:
```js
let redis = null;
if (program.cluster) {
    redis = new Redis.Cluster([
        {
            port: program.port,
            host: program.hostname,
        },
    ]);
} else {
    redis = new Redis(program.hostname, program.port);
}
```
Is there a unified way to connect to Redis regardless of weather it's a cluster or single server?

**Comment by shaharmor** [comment]
Hey @aalexgabi , at the moment there is no such way. We'll welcome a PR if you want to make one

**Comment by luin** [comment]
I'm not sure if it's possible to do that since Redis Cluster isn't a black box to the developers (unlike twemproxy & codis) since there're many things developers should care about when using cluster (e.g. multiple-key operations, so developers should redesign there's key schema when switching to the cluster). Thus there are two separated classes `Redis` & `Redis.Cluster` for the two situations. I'm afraid providing an unified way may mislead developers into thinking they are transparent to the developers.

**Comment by aalexgabi** [comment]
@luin I agree that Redis cluster does not work the same way as a single node and developers need to be aware of this.

Having two classes makes it obvious that something is different but not exactly what is different.

The `redis-cli` provides a `-c` option for cluster mode. I'm thinking of something similar: adding a flag `clusterMode: true` or `followRedirects: true`.

This would have allowed me to do something like this
```js
redis = new Redis.Cluster([
    {
        port: program.port,
        host: program.hostname,
        cluster: program.cluster,
    },
]);
```

**Comment by ccs018** [comment]
> Having two classes makes it obvious that something is different but not exactly what is different.

If that's all the developer is aware of (that there are two classes), then they're mostly likely going to use Redis incorrectly.  As @luin points out, if a developer doesn't know the differences between a standalone redis instance and redis cluster, then the developer is likely going to create problems for themselves.  In particular, multi-key operations (such as mget or multi/exec operations) can only be executed if all of the keys in those operations map to the same hash slot. This is described at https://github.com/luin/ioredis#transaction-and-pipeline-in-cluster-mode and https://redis.io/topics/cluster-tutorial#migrating-to-redis-cluster. An application may work just fine when using a standalone instance, but if you try to transparently replace that standalone instance with a cluster - and not examine the application design and use of redis - then developers will have no idea why certain operations start to fail.  You generally can't simply "flip a switch" and move to using a redis cluster without making sure your application is using it correctly - this goes beyond simply switching which class you use to instantiate the client.

Any developer wanting to use redis needs to know if they are using a standalone redis instance or a redis cluster and familiar with the redis documentation that describes the differences between them.  If they're relying simply on which class is being used to instantiate the client, it's not going to go well.  At a minimum they really need to read through the redis cluster tutorial:  https://redis.io/topics/cluster-tutorial.

In addition, when connecting to a redis cluster, it is a good idea to list more than one node when instantiating the client.  While the client can auto-discover all of the nodes in the cluster, if the one node you've configured your client with happens to down for whatever reason (upgrade, h/w fault, etc), then your application won't be able to connect and you've a complete outage.  If you specify multiple nodes (not necessarily all, but say 3), then the chances of not being able to connect are generally drastically reduced.  So again, the application code needs to know if there is one node (standalone) or multiple nodes (cluster).
