### ISSUE TITLE
Connecting to redis sentinel troubleshooting

### ISSUE THREAD

**Issue by bendpx** [luin/ioredis#64]
I'm trying to use this configuration for a sentinal connection

    var REDIS_CONFIG = {
        sentinels: [{ host: 'redis-1', port: 26379},
                    { host: 'redis-2', port: 26379},
                    { host: 'redis-3', port: 26379}],
        name: 'redismastert',
        db: 0
    };

    var REDIS_CLIENT = new Redis(REDIS_CONFIG);

But connection fail to establish due to:

    info: connected to sentinel redis-1:26379 successfully, but got a invalid reply: null
    info: connected to sentinel redis-2:26379 successfully, but got a invalid reply: null
    info: connected to sentinel redis-3:26379 successfully, but got a invalid reply: null

what is this invalid reply and how can i solve it?

thanks luin, love this library

**Comment by luin** [comment]
It's because sentinel nodes didn't return the master address.
Could you please use redis-cli to connect to one of the sentinel and see what does it return?

```shell
$ redis-cli -h redis-1 -p 26379
redis-1:26379> sentinel get-master-addr-by-name redismastert
```

I guess you misspelled the master name which should be `redismaster` instead of `redismastert`

**Comment by luin** [comment]
I'm closing the issue. Feel free to reopen it if the problem still here :-)
