### ISSUE TITLE
Cluster. Issues when a node goes down

### ISSUE THREAD

**Issue by finalclass** [luin/ioredis#643]
We are migrating to redis cluster.
During our tests we have noticed that when we take one redis node down these errors appear:

```
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 10.85.44.82:7000
at Object._errnoException (util.js:1041:11)
at _exceptionWithHostPort (util.js:1064:20)
```

and later:

```
[ioredis] Unhandled error event: Error: connect ETIMEDOUT
at Socket.<anonymous> (/home/node/dist/backend/3.10.0-feat-redis-cluster-migration/node_modules/ioredis/lib/redis.js:289:21)
at Object.onceWrapper (events.js:314:30)
at emitNone (events.js:105:13)
at Socket.emit (events.js:207:7)
at Socket._onTimeout (net.js:398:8)
at ontimeout (timers.js:469:11)
at tryOnTimeout (timers.js:304:5)
at Timer.listOnTimeout (timers.js:264:5)
[ioredis] Unhandled error event: Error: connect ETIMEDOUT
```

Just after instantiating the node we have this:

```js
redis.on('error',function (err) {
        console.error("REDIS CONNECT error "+ err);
        console.error('node error', err.lastNodeError);
    });
```

So I wonder why these errors are not handled? Also why don't we see simply `CLUSTERDOWN` event?
Do we have to check manually before the startup (`new Redis.Cluster([...])`) if all the nodes are online to avoid these errors? 

Our configuration is a simple list of nodes:

```
new Redis.Cluster([
{host: "...", port: ...}
...
])
```
without any additional options. Maybe we are missing something in the configuration?
Any guidance would be greatly appreciated.

**Comment by luin** [comment]
Did ioredis try to reconnect to the cluster when the error happened? Could you enable the debug logs (DEBUG=ioredis:* node yourapp.js) and post the logs here?

**Comment by ccs018** [comment]
While you've got
```
redis.on('error',function (err) { ... });
```
There should also be
```
redis.on('node error',function (err) { ... });
```

Here's all of the events that I'm catching:
```
    redisCluster.on('+node', function (data) { ... });
    redisCluster.on('-node', function (data) { ... });
    redisCluster.on('connect', function () { ... });
    redisCluster.on('ready', function () { ... });
    redisCluster.on('error', function (err) { ... });
    redisCluster.on('node error', function (err) { ... });
    redisCluster.on('close', function () { ... });
    redisCluster.on('reconnecting', function (delay) { ... });
    redisCluster.on('end', function () { ... });
```

**Comment by finalclass** [comment]
Thank you for your tips. I've followed your advice with some more extensive error handling and figured out that my app is making some additional connections during page refreshes. I have to sort that out first to see if this will solve my issues. Will let you know about my progress.

**Comment by finalclass** [comment]
Limiting the number of connections has helped me solving these issues. In our app we were making new connections each time a request is made and that's why we saw a lot of disconnects.
The issue can be closed now. Thank you for your help.
