### ISSUE TITLE
redis reconnect

### ISSUE THREAD

**Issue by GoBrianGo** [luin/ioredis#644]
我想问问我链接redis总是断开重连，是什么原因呢。下面是输出日志
ioredis:redis status[10.12.34.21:6379]: reconnecting -> connecting +55ms
  ioredis:redis status[10.12.34.22:26379]: [empty] -> connecting +0ms
  ioredis:redis queue command[0] -> sentinel(get-master-addr-by-name,mymaster) +0ms
  ioredis:redis status[10.12.34.22:26379]: connecting -> connect +18ms
  ioredis:redis status[10.12.34.22:26379]: connect -> ready +0ms
  ioredis:connection send 1 commands in offline queue +0ms
  ioredis:redis write command[0] -> sentinel(get-master-addr-by-name,mymaster) +1ms
  ioredis:redis write command[0] -> sentinel(sentinels,mymaster) +17ms
  ioredis:SentinelConnector sentinels [ { host: '10.12.34.21', port: '26379' },
  { host: '10.12.34.22', port: 26379 },
  { host: '10.12.34.21', port: 26379 } ] +20ms
  ioredis:SentinelConnector resolved: 10.12.34.21:6379 +0ms
  ioredis:redis status[10.12.34.22:26379]: ready -> close +17ms
  ioredis:connection skip reconnecting since the connection is manually closed. +0ms
  ioredis:redis status[10.12.34.22:26379]: close -> end +0ms
  ioredis:redis status[10.12.34.21:6379]: connecting -> connect +3ms
  ioredis:redis write command[0] -> info() +0ms

**Comment by luin** [comment]
看状态是正常的。sentinel 模式下，每次连接哨兵获取到 master 地址后，就会断开和哨兵的链接。

Get Outlook<https://aka.ms/qtex0l> for iOS
________________________________

**Comment by GoBrianGo** [comment]
知道原因了，因为redis-server那边设置了30s闲置超时，所以如果我30s没操作就会断开，然后node redis这边因为有自动重连机制，所以空闲的时候就这样不断重连。还有个问题想问下，我用redis-benchmark测试redis读写速度的时候，发现当connection是1的时候每秒读写比较慢，可是我们node redis就是一直只有一个链接，可是这样当并发高的时候读写redis效率岂不是会很低？因为java那些都是有连接池，可能同时有很多个🔗在用呢。

**Comment by luin** [comment]
ioredis 有 pipeline 的功能，可以优化批量的命令。因为 Redis 是单线程模型，连接池只能缓解发送命令的开销，在 Node.js 场景下优化不大

**Comment by MinStenve** [comment]
@GoBrianGo 知道原因了，因为redis-server那边设置了30s闲置超时，所以如果我30s没操作就会断开，然后node redis这边因为有自动重连机制，所以空闲的时候就这样不断重连。后面如何解决的呢, 修改闲置超时时间?

**Comment by GoBrianGo** [comment]
@MinStenve 修改闲置超时时间是可以的，不过这个要修改redis那边的设置，或者就是保持30s的闲置时间，redis每次断开后会自动重连的。
