### ISSUE TITLE
Maxmemory error 

### ISSUE THREAD

**Issue by eladror** [luin/ioredis#646]
Im using ioredis to set 3 strings.

The first string length is 25,107,140.
The second string length is 82,990.
And the third string length is 19.

My code looks like this- 

Redis.set("key1", string1);
Redis.set("key2", string2);
Redis.set("key3", string3);

The third string fails, with the error: 
"oom command not allowed when used memory 'maxmemory' but there enough memory".

In addition, this lines work just fine: 

Redis.set("key3", string3);
Redis.set("key2", string2);
Redis.set("key1", string1);

In the INFO in redis-cli my redis server: 
used_memory_human: 1.98M
maxmemory_human: 10.00G
maxmemory_policy:allkeys-lru

What am i doing wrong?

**Comment by luin** [comment]
Can setting the three keys via redis-cli reproduce the problem?

**Comment by eladror** [comment]
No, in redis-cli it worked. 

The error didn't accured when i was Adding .then statement to each string, or debugging it. So i assume this has something to do with the strings set at the same time.

**Comment by luin** [comment]
Well, that's strange. I don't think this problem is related with ioredis. Maybe asking in the redis repo? Run `monitor` in a redis-cli may help you debug the issue.

**Comment by eladror** [comment]
I finally succeeded to create thie error in redis-cli, so i will ask in the redis repo. 
Thank you!
