### ISSUE TITLE
Keepalive connection to Sentinel

### ISSUE THREAD

**Issue by jfjm** [luin/ioredis#651]
Currently we are setting up a cluster of 120 Redis nodes and 20 nodes of Sentinel.  Everything seems to be working fine except periodically we see the following message:
[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 10ms

After some digging, we noticed the connections to Redis are "long-lived", but the connections to Sentinel are on-demand. We see there are times many (or all) of the clients running ioredis simultaneously trying to connect to Sentinel, unfortunately Sentinel is hard coded to have 511 backlog queue. As a result, the system think there is a SYN flood.

Can ioredis use "long live" connection to Sentinel instead of on-demand?

**Comment by luin** [comment]
Hi, it seems that the default backlog can be changed at https://github.com/antirez/redis/blob/94658303e9ec5050189728fb8bc514ee682dd5fe/redis.conf#L101.

**Comment by jfjm** [comment]
Redis instances can be, but Sentinels can not. The flood we experienced was with Sentinels.

**Comment by luin** [comment]
Not sure but I thought sentinels and typical redis servers share the same code according to the backlog part.

Keeping a long live connection to sentinels is possible but is not trivial to implement. We'll think about that.

**Comment by jfjm** [comment]
Hi, although it's not in the document, but after reading your post, we decided to to create the setting for Sentinel, and it worked. Thanks! We will monitor and see if this address the connection issue we had.

If long live connection to sentinels is not trivial to implement, how about subscribe to Sentinel to receive any changes.

**Comment by kdekooter** [comment]
@jfjm could you expand a bit on how you did that? It might be useful for my project as well.

**Comment by jfjm** [comment]
Add the following to your sentinel.conf:
tcp-backlog <num>
