### ISSUE TITLE
Problem with TypeScript

### ISSUE THREAD

**Issue by vladlavrik** [luin/ioredis#653]
I'm trying to use ioredis in my TypeScript Project.
I met with a problem that [@types/ioredis](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/ioredis/index.d.ts) describes a response of called redis methods as "`Promise<0|1>`", but real response is string "`OK`".  

Example: method HMSET, type definition here(https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/ioredis/index.d.ts#L250)

![image](https://user-images.githubusercontent.com/10566567/42181177-a58dcc46-7e42-11e8-8e05-014c0843bb58.png)

Since I did not find a discussion of this problem, I want to ask for your help and find out what I'm doing wrong.
P.S. I suspect that this may be a problem of the TypeScript project, if this is really so inform me about it.

**Comment by luin** [comment]
This is an issue on the TypeScript project. The response type should be `Promise<'OK'>`.

**Comment by vladlavrik** [comment]
@luin Thanks for the quick response. I created a pull request on DefinitelyTyped project.
