### ISSUE TITLE
Geo support missing

### ISSUE THREAD

**Issue by zunder** [luin/ioredis#654]
Documentation states that:
```
10. Support for GEO commands (Redis 3.2 Unstable).
```
I am not seeing any function which would provide such commands, e.g. no GEOADD command. Am I missing something?

**Comment by luin** [comment]
Which version of ioredis did you use? There should be `GEOADD` command.

```javascript
const Redis = require('ioredis')
const redis = new Redis()

console.log(redis.geoadd)
```

**Comment by vcfvct** [comment]
Looks like the geo related commands are not in the `@types/ioredis`.

**Comment by seekcx** [comment]
@luin Has anyone maintained @types?

**Comment by BlenderDude** [comment]
This library is written in Typescript. Is there any particular reason the types are not emitted to NPM? Seems kind of off to keep `@types/ioredis`. This is a server library too where tree-shaking and bundle size is not particularly a concern.

**Comment by ahl5esoft** [comment]
commands are not in the @types/ioredis.

**Comment by TrejGun** [comment]
:(
