### ISSUE TITLE
In cluster mode, command  "keys" returns result from random shard 

### ISSUE THREAD

**Issue by JoeriMalmberg** [luin/ioredis#66]
Using a cluster, when I issue the command `keys()`
```coffee-script
redis.keys "*", (error, result) -> console.log result
```
I get the result from a **random** single shard only (and I need to concat the result off all shards)

What am I doing wrong?

**Comment by luin** [comment]
Commands that are not associated with specific keys(e.g. `keys`, `info`) are sent to a random node of the cluster.

Currently you may use:

```javascript
Promise.all(Object.keys(cluster.nodes).map(function (nodeName) {
  return cluster.nodes[nodeName].keys('*');
}));
```

I'm considering add a `broadcast` method though.
