### ISSUE TITLE
执行_multi.exec()多次，数据会重复提交

### ISSUE THREAD

**Issue by bi-kai** [luin/ioredis#666]
执行_multi.exec()多次，push进multi的数据会重复提交，为什么exec完没有清空缓存或者该如何清空呢。
我用于并发的场景，每个进程_multi.rpush()数据结束时调用_multi.exec()，exec()被执行多次，数据就多次全量push，该怎么用呢？
```javascript
var _multi = redis.multi();

_multi.rpush("a", "1").exec();
_multi.exec();
```
![image](https://user-images.githubusercontent.com/15070379/42928810-e34711a2-8b6a-11e8-907d-84ddf9e2c3ac.png)

**Comment by luin** [comment]
需要启动多个 multi。

```javascript
redis.multi().rpush('a', '1').exec()
redis.multi().rpush('a', '1').exec()
```

**Comment by bi-kai** [comment]
嗯 我测试也是这样。
exec后为什么还存储着这些数据呢，是否是资源浪费还是有什么别的用途？
