### ISSUE TITLE
4.0.0-3 broken single connection with ECONNREFUSED

### ISSUE THREAD

**Issue by Delagen** [luin/ioredis#668]
connect to single node at 127.0.0.1 with auth.
version 4.0.0-2 works as expected.

**Comment by luin** [comment]
Hi, could you enable the logs (DEBUG=ioredis:* node yourapp.js) and post the logs here?

**Comment by Delagen** [comment]
[DEBUG] status[redis-wal.colvir.ru:6379]: connecting -> close +9ms
[DEBUG] reconnect in 36ms +2ms
[DEBUG] status[redis-wal.colvir.ru:6379]: close -> reconnecting +1ms
[DEBUG] error: Error: connect EADDRNOTAVAIL 127.0.0.1 - Local (0.0
.0.0:55277) +5ms
[ERROR] Error: connect EADDRNOTAVAIL 127.0.0.1
- Local (0.0.0.0:55277)
    at internalConnect (net.js:932:16)
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:294:19)
    at GetAddrInfoReqWrap.emitLookup [as callback] (net.js:1081:9)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:61:10)

**Comment by Delagen** [comment]
This is due 
```
function isIIpcConnectionOptions(value) {
    return value.hasOwnProperty('path');
}
```
because I supply property `path` with null value

**Comment by luin** [comment]
Fixed. Will be releaseed in the next version. Thanks for pointing this out!

**Comment by luin** [comment]
Fixed. Will be releaseed in the next version. Thanks for pointing this out!

**Comment by luin** [comment]
Fixed. Will be releaseed in the next version. Thanks for pointing this out!

**Comment by luin** [comment]
Fixed. Will be releaseed in the next version. Thanks for pointing this out!

**Comment by luin** [comment]
Fixed. Will be releaseed in the next version. Thanks for pointing this out!
