### ISSUE TITLE
add option maxRetryTimes

### ISSUE THREAD

**Issue by coderhaoxin** [luin/ioredis#67]
for `auto-reconnect`

**Comment by luin** [comment]
`retryStrategy` should satisfy your needs. For instance you want to limit retry times to `3`:

```javascript
var redis = new Redis({
  retryStrategy: function (times) {
    if (times <= 3) {
      return 200;
    }
  }
});
```

**Comment by coderhaoxin** [comment]
yes, I know. But I think this is a very normal option.

**Comment by luin** [comment]
It makes people confused to have multiple options for the same purpose IMHO(most glaring example is the priority of these options). `retryStrategy` is more relevant to the demands of the production environment than `maxRetryTimes` and `maxRetryDelay`.

**Comment by coderhaoxin** [comment]
got it.
