### ISSUE TITLE
Docs for SCAN-family commands don't mention duplicate items

### ISSUE THREAD

**Issue by philraj** [luin/ioredis#678]
The docs for how to use the scan streams are helpful but the example code seems to ignore the fact that SCAN may return a given element multiple times, and that you need to handle duplicate items in your application code. Were the scan streams in ioredis built to automatically cull duplicates, or do the docs need to be updated?

**Comment by luin** [comment]
ioredis doesn't remove duplicated keys. Would you like make a pull request to add a note on the README?

**Comment by philraj** [comment]
Thanks for the info, I'll try to at some point but at the moment my hands are tied.

**Comment by philraj** [comment]
Done in https://github.com/luin/ioredis/pull/681
