### ISSUE TITLE
how to catch `connect` error

### ISSUE THREAD

**Issue by coderhaoxin** [luin/ioredis#68]
https://github.com/luin/ioredis/blob/master/lib/redis/event_handler.js#L76

the default error handler is just `noop`

**Comment by coderhaoxin** [comment]
If `enableOfflineQueue` is `false`, should we just throw error when `connect` failed?

**Comment by luin** [comment]
Events could be caught by listening to the specified events of `Redis` instances. Say you can catch `connect` errors by listen to `error` and `close`. it's just a matter of convenience to return a promise of `connect` methods for developers to catch connect errors easier.

**Comment by luin** [comment]
`connect` always throws when the connection is failed regardless of the value of `enableOfflineQueue`:

```javascript
var redis = new Redis({
  host: 'non-exists host',
  lazyConnect: true,
  enableOfflineQueue: false
});
redis.connect().catch(function () {
  console.log('should throw');
});
```

**Comment by coderhaoxin** [comment]
:smile: yeah, got it.

**Comment by knoxcard** [comment]
Oh my sweet Jesus! I finally got this working...it would not work with all those fancy attributes inside of new Redis().  Kept it simple and it's finally doing what daddy wants!

```
console.time('Redis')
var Redis = require('ioredis'),
  redis = new Redis()
redis.on('error', err => {
  // console.log('redis err: ' + err)
  console.log(app.get('colors').whiteBright('Redis: ' + app.get('colors').redBright('FAILED')))
  process.exit(0)
})
redis.on('connect', () => {
  app.set('redis', redis)
  console.timeEnd('Redis')
})
```
