### ISSUE TITLE
Type definitions for keys as Buffers

### ISSUE THREAD

**Issue by yuricodes** [luin/ioredis#684]
I know redis client can handle `key` argument as Buffer. I can't use them in typescript environment though. Can we update type definitions for all methods to use `string | Buffer`? I can make a pull request if it would be accepted.

**Comment by luin** [comment]
Hi @yuricodes! Are you using @types/ioredis? If you are, you may submit an issue on https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/ioredis.

**Comment by yuricodes** [comment]
Of course. Thanks

**Comment by scf4** [comment]
Hey guys, any update on this?

**Comment by luin** [comment]
It seems the problem has been solved on https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/ioredis/index.d.ts#L47 @scf4
