### ISSUE TITLE
About redis cluster

### ISSUE THREAD

**Issue by Runrioter** [luin/ioredis#687]
* client-side sharding across your nodes
* native Redis clustering

What are the configuration of the above two cases? What is the difference?

**Comment by ccs018** [comment]
Are you asking how to configure the ioredis client or how to configure
redis itself?

**Comment by ccs018** [comment]
These are not two different options.  Redis Clustering uses client-side
sharding.  There is lots of documentation available describing how Redis
Clustering works and how to configure Redis itself to operate in cluster
mode.  See:

https://redis.io/topics/cluster-tutorial
https://redis.io/topics/cluster-spec
