### ISSUE TITLE
Lists backing up with ioredis 4.0

### ISSUE THREAD

**Issue by klinquist** [luin/ioredis#688]
We use a microservices architecture with everything listening on its own redis list (things LPUSH onto a list and BRPOP off of a list).  I have a list monitor which monitors the oldest item in a list to determine when things need to be scaled.

I recently noticed that lists were "backing up."  Some services had 1 item in the list but it was 10 minutes old... it's like the service wasn't BRPOPing anymore.  Then, all of the sudden, it would continue working normally.   It seemed to happen with lists that were hash mapped to a single server pair (master+slave) in our redis cluster, so I suspected something was wrong with that server.   After some time, I realized it was also only happening to microservices that had been re-deployed recently, using ioredis 4.0.

I reverted these services to ioredis 3.2.2 and all of the problems went away.

Node 6.x
Redis 3.0.7, 3x master 3x slave.

I know this may be a hard thing to troubleshoot :(.

**Comment by klinquist** [comment]
I didn't actually check the version we had deployed, but it was @latest as of a few days ago, so it might have been 4.0.0-1.
We saw this issue every few hours.  
Unfortunately I won't be much help troubleshooting as this is a system that I can't have down :(.

**Comment by luin** [comment]
What else commands besides `LPUSH` & `BRPOP` are used on the list? Did you notice any reconnections between apps and Redis server during that time?

**Comment by klinquist** [comment]
The microservices open up several redis connections (clones of each other), but the one that does BRPOP is dedicated to BRPOP only.
I did not notice any reconnections.  I was able to BRPOP myself manually from the redis server no problem.

**Comment by luin** [comment]
I'm running a sample that does `lpush` and `brpop`, hoping we can reproduce the issue.

The major difference between v4 & v3 is that when a Redis server goes down, v3 will wait forever until the server goes back, while v4 only wait for ~20s and will emit an error after that. However, when the server goes back, both v3 and v4 will continue to work automatically. I'm wondering whether it is possible that the error handler in your app prevents self-healing happens (e.g. restarting the app by calling `process.exit()`).

What's the typical qps of `lpush`? And are you using the official cluster (that need client-side sharding) or Sentinel?

**Comment by klinquist** [comment]
Hm.. I'd have to see if that one server is failing master>slave, I haven't looked.  We aren't calling process.exit().
Using the official cluster, not sentinel.

**Comment by klinquist** [comment]
qps can be ... "tens"

**Comment by luin** [comment]
Thank you for the information. Still not sure about that, but it may be related with the cluster setup. bgsave shouldn't be a problem unless it blocks IO for 10+ seconds, which is not possible with a 9gb instance.
