### ISSUE TITLE
connecting to AWS ElasticCache

### ISSUE THREAD

**Issue by jamesdixon** [luin/ioredis#689]
Hi, I'm moving resources from Azure to AWS and am having trouble connecting to Elasticache through ioredis.

Here's my basic config:
```js
const redisClient = new Redis({
  port: process.env.REDIS_PORT,
  host: process.env.REDIS_HOST
})
```

Here's my Elasticache instance:

![image](https://user-images.githubusercontent.com/110114/44694844-2d983480-aa2d-11e8-8a81-2bc6a8ba410d.png)

When trying to connect, it just times out. The strange thing is that if I use `node-redis` with essentially the same config, it connects immediately.

Anything special that needs to be done?

Thx!

**Comment by luin** [comment]
Could you enable the debug mode (DEBUG=ioredis:* node yourapp) and post logs here?

Get Outlook<https://aka.ms/qtex0l> for iOS
________________________________

**Comment by jamesdixon** [comment]
Not sure what happened but it's working now 👍

**Comment by renarsvilnis** [comment]
Had the same "problem" yesterday, solved it by a coworker who had gone through the same problem some time ago. Posting my solution, maybe it helps out someone else.

You need to add `tls: {}` to the options, which is a bit counter-intuitive given the API docs and examples.

```
const Redis = require("ioredis");
const redis = new Redis({
  host: "master.prodGETFROMENVSECRETS.amazonaws.com",
  port: 6379,
  password: "myl33tpa5w00rd",
  tls: {}
});
```

**Comment by malimccalla** [comment]
Ran into this today setting up on Digital Oceans new managed Redis. The only way to get a connection working was to use @renarsvilnis's solution of adding `tls: {}`. However adding this prevented a connection to localhost for development/test envs so had to only set in production

**Comment by andreasadelino** [comment]
Use `lazyConnect: true` and connect manually with `await redis.connect();`
