### ISSUE TITLE
Refreshing nodes on interval timer breaks socket.io pubsub adapter

### ISSUE THREAD

**Issue by jeremytm** [luin/ioredis#696]
Using socket.io-adapter causes the redis connection to enter subscriber only mode, any other command causes an error, and a reconnect.

> Error: Connection in subscriber mode, only subscriber commands may be used

Therefore the ioredis interval timer which refreshes cluster nodes every 5 seconds causes an error, and continual reconnections due to the fact that is runs `CLUSTER NODES` which is not allowed.

Not sure how to resolve this, given the purpose of the interval – but I thought you should be aware.

**Comment by luin** [comment]
A fix (WIP) is here https://github.com/luin/ioredis/pull/697. Waiting for tests to be added.
