### ISSUE TITLE
ioredis with multi returns null along with value when using hget on hash data type

### ISSUE THREAD

**Issue by javadeveloper080** [luin/ioredis#698]
[ **null**,
  '{"agentId":"agentId1234","propertyId":"propertyId1234","noteText":"test2","noteType":"TOUR_NOTES","sharingStatusType":"PRIVATE","isApproved":"YES","approvedOn":"2018-9-18","createdOn":"2018-9-18","updatedOn":"2018-9-18","id":1}' ]

Code snippet:
var Redis = require('ioredis');
var redisClient = new Redis();

var keys=[1];

    redisMulti = redisClient.multi();

    keys.forEach(function(key){
        console.log(key);
        redisMulti.hget(NOTES_RECORD,key);
    });

    redisMulti.exec(function(err, result){
        console.log(result);
    });

**Comment by luin** [comment]
This is the expected result format that has been documented here: https://github.com/luin/ioredis#transaction.
