### ISSUE TITLE
Weird authentication error

### ISSUE THREAD

**Issue by szenciattila** [luin/ioredis#699]
Greetings!

I'm added password authorization to Redis and got the following error: 

> [ioredis] Unhandled error event: ReplyError: NOAUTH Authentication required.

But when I remove authentication from redis config I got the following warning:

> [WARN] Redis server does not require a password, but a password was supplied.

For me this is completely nonsense

I'm using the 4.0.0 version. Below you can find the code snippet.

var IORedis = require('ioredis') 
var redis = new IORedis(6379,"localhost", { password:"123456" })

Do I make mistakes?

Thanks!

**Comment by luin** [comment]
Hi, the first error can be caused by the supplied password is incorrect, and the second warning is seen because a password is supplied but the redis server doesn't require a password.

**Comment by szenciattila** [comment]
Thank you for the answer!

But the password is 100% correct and with incorrect password the error message is other.
So i think something is ignoring the password.

**Comment by EmpariCursos** [comment]
+1

**Comment by fulvi0** [comment]
Hi, I feel I'm facing the same issue as @szenciattila,

versions
- `"ioredis": "^4.27.6",`
- Redis `6.2`

I creating a `redisClient` like: 

```javascript

const Redis = require('ioredis');
...
const { redis } = require('../config/config');

const createClient = () => {
  try {
    let redisClient;
    redisClient = new Redis({
      port: redis.redisPort,
      host: redis.redisHost,
      family: 4,
      password: redis.redisPass,
    });
    return redisClient;
  } catch (error) {
    logger.log('error', modules.ServiceModules.REDIS, "Error creating Redis Client", `${error}`);
  }
};

module.exports = {
  createClient,
};

````

And getting the following error.

```log
{"timestamp":"2021-08-01T00:22:05.375Z","level":"info","hostname":"20a9165bfd1b","service":"APP_MFA_BACKEND","module":"EXPRESS","versionService":"1.0.0","versionModule":"1.0","operation":"INITIALIZING SERVER","description":"","operationChannel":"SERVER","entity":"EXPRESS","message":"Server is already listening, on PORT: 4602; and redis pass is = superapassword"}
[ioredis] Unhandled error event: ReplyError: NOAUTH Authentication required.
    at parseError (/usr/src/app/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/usr/src/app/node_modules/redis-parser/lib/parser.js:302:14)

```

Note: I double-check the password and tested using a GUI Client, and the password is the correct one.

Thank u!
