### ISSUE TITLE
Issue in connecting ioredis with AWS elastic cache cluster on docker

### ISSUE THREAD

**Issue by khanna91** [luin/ioredis#701]
Hello Guys,

I am trying to connect the AWS elastic cache (cluster). When using ioredis in cluster mode locally its working fine. Its able to connect and all. But as soon as I put it on docker, it connection refused. I checked everything, env variables are setting properly, the values passing to library are same as of local vs docker.

Can anyone help?

Thanks in advance

**Comment by luin** [comment]
Refer to https://get-reddie.com/blog/redis4-cluster-docker-compose/ for details on how to connect to a redis server inside a docker. Let me know if it helps.
