### ISSUE TITLE
Maximum

### ISSUE THREAD

**Issue by simondutertre** [luin/ioredis#702]
Hi,
@luin 

I see here https://github.com/luin/ioredis/blob/f0f791c4c4e6a881b12d3ee86d3acff7964110e3/lib/redis.js  that maxOfflineQueueSize default option is set to Infinity.
Is this really a good idea ?

What value would you recommand for a high traffic on AWS ? 

Thanks !

**Comment by luin** [comment]
It really depends on your use case. If you don't want to lose any command and connection is pretty stable, keeping `maxOfflineQueueSize` to `Infinity` should not be a problem.

**Comment by edevil** [comment]
Is the option `maxOfflineQueueSize` available? It seems the PR was not merged. :(
