### ISSUE TITLE
How to configure ioredis not to emit "ready" status for a slave instance that is in the readonly mode?

### ISSUE THREAD

**Issue by denigmus** [luin/ioredis#708]
The doc says  that status ready is emitted immediately after connect event. This ready status is used by other apps to write to redis. How to configure ioredis not to emit "ready" status for a slave instance that is in the readonly mode?

**Comment by luin** [comment]
That's not possible. What the use case that you want to pass a readonly connection to apps that want to write data to?

**Comment by denigmus** [comment]
bee-queue dev2.0 will write inrespectfully to the status of redis, because ioredis emits "ready" without respect "role" or "slave_read_only" flags of the instance. So any app that uses that status will attempt to write to READONLY redis, not just the bee-queue.  It would be good if ioredis could check "slave_read_only" flag with INFO command before report ready and report readonly instead in case when slave_read_only=1.

**Comment by luin** [comment]
How do bee-queue work with a Redis connection which is read-only?
