### ISSUE TITLE
Typescript definition is broken

### ISSUE THREAD

**Issue by KromDaniel** [luin/ioredis#712]
Hey

- Typescript 3.0.3
- ioredis 4.0.0

Typescript definition throws an error not matter what combination of import I'm trying

```tsc
import * as Redis from "ioredis";
const redis = new Redis();
```

> error TS2351: Cannot use 'new' with an expression whose type lacks a call or construct signature.

When trying
```tsc
import Redis from "ioredis";
const redis = new Redis();
```

Getting the error 

> TS1192: Module '"node_modules/@types/ioredis/index"' has no default export.

Any ideas? 
thanks!

**Comment by luin** [comment]
Would you try to upgrade @types/ioredis package to see whether the problem still exists? The package is located in another repo: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/8fb0189dd4432b854d72d9e78fcdea53829b24fe/types/ioredis/index.d.ts.

**Comment by KromDaniel** [comment]
@luin  thanks, unfortunately I'm up to-date

```
// Type definitions for ioredis 4.0
// Project: https://github.com/luin/ioredis
// Definitions by: York Yao <https://github.com/plantain-00>
//                 Christopher Eck <https://github.com/chrisleck>
//                 Yoga Aliarham <https://github.com/aliarham11>
//                 Ebrahim <https://github.com/br8h>
//                 Shahar Mor <https://github.com/shaharmor>
//                 Whemoon Jang <https://github.com/palindrom615>
//                 Francis Gulotta <https://github.com/reconbot>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped
// TypeScript Version: 2.8

/* =================== USAGE ===================
    import * as Redis from "ioredis";
    const redis = new Redis();
 =============================================== */
```

**Comment by luin** [comment]
Not sure where the problem is. Here's my setup:

@types/ioredis: 4.0.3
ioredis: 4.0.0

![image](https://user-images.githubusercontent.com/635902/46574380-b7480400-c9d4-11e8-85b4-56e062fb327f.png)

**Comment by KromDaniel** [comment]
what is your TS version? :)

**Comment by KromDaniel** [comment]
It seems that the `tsconfig.json` file didn't have the key `allowSyntheticDefaultImports` set for true, now it's fixed
