### ISSUE TITLE
semantic-release, etc

### ISSUE THREAD

**Issue by AVVS** [luin/ioredis#713]
@luin if you want, I can setup https://github.com/semantic-release/semantic-release in a separate PR, which make maintaining this much easier, let me know

**Comment by luin** [comment]
Sounds interesting. I'm just wondering how to release a beta version (e.g. v4.0.0-0) if we are using semantic-release? It seems this lib will publish every change to the npm.

**Comment by AVVS** [comment]
They don’t have support for multi-branch yet, but you can do 2 branch release with publishing from a specific branch

Ie master = no release, just tests and can manually trigger a release via semantic-release + tags (from your laptop, for instance) - thats for beta releases

And once master is pushed to, lets say “release”, branch - semantic will do all the automatic work

Took a stab at it while trying out fixes for the cluster connect race conditions here: https://github.com/makeomatic/ioredis/blob/canary/.releaserc.json

**Comment by luin** [comment]
That two branch workflow makes sense. PR is welcome.

**Comment by AVVS** [comment]
ok, I'll work on that

**Comment by luin** [comment]
Closing 👍
