### ISSUE TITLE
AWS Elasticache Redis & TLS 

### ISSUE THREAD

**Issue by frank-liu** [luin/ioredis#714]
Hello 

I setup an AWS Elasticache redis node with auth enabled. I try to connect it using ioredis, but it fails. 

I can connect it using another module 'redis' as below:

redis.createClient(
			{
				host: 'master.xxx-test-redis.xxxx.cache.amazonaws.com', 
				port: 6379, 
				auth_pass: '123456789', 
				tls: { checkServerIdentity: () => undefined }
			}

However, when I try the below connector with ioredis, I failed.
var client = new Redis({
            host: 'master.xxx-test-redis.xxxx.cache.amazonaws.com',   
            port: 6379,                                                    
            password: '123456789',                                
        });
I have spent 2 days on this issue, could anyone help me out?!

Many thanks for your help.

**Comment by luin** [comment]
Could you enable the debug mode (`DEBUG=ioredis:* node yourapp.js`) and post the logs here?

**Comment by luin** [comment]
ioredis 4 只支持 node.js 6 以上版本

Get Outlook<https://aka.ms/qtex0l> for iOS
________________________________

**Comment by frank-liu** [comment]
Thank you for your reply. My node js version is v4.2.6. I will try to upgrade it.
