### ISSUE TITLE
if connect to redis cluster which is NOT properly configured, 'connect' event is keep fired forever

### ISSUE THREAD

**Issue by Bossa573** [luin/ioredis#72]
I tried to connect to a redis cluster with 6 redis process inside,
but the cluster is NOT configured properly:

```
my-ip:6379> cluster nodes
bf2fad0bef66b71ae09c7c7c4bbc11c67f7f692a :6379 myself,master - 0 0 0 connected
```

and the code:

```
var redis = new Redis.Cluster([
{ port: 6379, host: 'my-ip' },
  { port: 6380, host: 'my-ip' },
  { port: 6381, host: 'my-ip' },
  { port: 6382, host: 'my-ip' },
  { port: 6383, host: 'my-ip' },
  { port: 6384, host: 'my-ip' }
]);

redis.on('connect', function() {
	console.log('connected');
});
```

and the output:

```
connected
connected
connected
connected
connected
....
```

I will keep receiving the callback from `connect` forever,
I don't think it's normal, 
is there any other event handler I should use?

**Comment by luin** [comment]
When connected to the one of the nodes in cluster, ioredis emits `connect` event and sends `CLUSTER SLOTS` to get all nodes that is responsible for at least one slot. If the result is empty(which is your situation), ioredis would disconnect from the cluster(emitting `close`) and try to reconnect.

If you listen to the `close` event, the result would be:

```
ioredis git:e323df0 ❯ node test
connected
closed
connected
closed
connected
closed
```

To limit the retry times, setting the `clusterRetryStrategy` option.

**Comment by Bossa573** [comment]
will try `clusterRetryStrategy`, thanks
