### ISSUE TITLE
zpopmin not supported?

### ISSUE THREAD

**Issue by ashamia** [luin/ioredis#724]
when trying to use zpopmin(key):
1. ioredis throws an error 'zpopmin is not a function' 
2. the IDE autocomplete does not provide any arguments list for zpopmin (but does provide argument lists for all other sorted set commands)

can it be the zpopmin is not (yet) supported? 
what would be a workaround?

**Comment by luin** [comment]
The latest version of ioredis should support `zpopmin`. Note that ioredis depends on redis-commands v1.3.6 for the support for this command (https://github.com/luin/ioredis/blob/master/package.json#L37).

**Comment by luin** [comment]
Just released v4.1.0 that supports this command.

**Comment by ashamia** [comment]
thanks for the quick response. 

updated to the latest but still get an error: "ReplyError: ERR unknown command `zpopmin`"

**Comment by luin** [comment]
Could you run `npm ls` to see what the version of ioredis & redis-commands?

**Comment by ashamia** [comment]
└─┬ ioredis@4.1.0
  └── redis-commands@1.4.0

**Comment by ashamia** [comment]
Could you please confirm that zpopmin works with the latest ioredis/redis-commands?

I tested the newest versions and they work with ALL sorted sets commands EXCEPT zpopmin and zpopmax!

**Comment by ashamia** [comment]
blocking pop ops on sorted sets was only introduced in redis v5 so upgrading redis server to v5 solved it...

**Comment by khaNuri** [comment]
@ashamia We use Redis as a service on Azure.  We couldn't see any upgrade. Do you have any advice?
