### ISSUE TITLE
.quit() not documented

### ISSUE THREAD

**Issue by kimmobrunfeldt** [luin/ioredis#73]
In .disconnect() method documentation, there is a reference to use .quit() to close redis cleanly. However .quit() is not documented.

**Comment by kimmobrunfeldt** [comment]
It seems that .quit() method is not defined in the code either.

**Comment by luin** [comment]
`quit` is a redis command just like `get`/`set` etc.

http://redis.io/commands/quit

**Comment by kimmobrunfeldt** [comment]
Ok thanks. Didn't realize that.

**Comment by ben-turner** [comment]
Going to necro this since I was also confused by this. Might be worth adding something to the docs so future users don't have to time travel back to 2015 :)
