### ISSUE TITLE
redis connection event not working

### ISSUE THREAD

**Issue by acuervof** [luin/ioredis#731]
Hi everyone!

I have these event listeners in order to log redis connection

```
const cluster = new Redis.Cluster(clusterEndpoints);

cluster.on('connect', function() {
    logger.info('Redis connection for cluster established');
});

cluster.on('error',function(err) {
    logger.error('Redis connection for cluster error: ' + err);
});

cluster.on('close', function(){
    logger.info('Redis connection for cluster closed');
});
```
In **3.x.x** version with this code, console always prints
Redis connection for cluster established

In **4.0.x** and **4.1.0**
Redis connection for cluster established
Redis connection for cluster closed
Redis connection for cluster established
(a bit random, sometimes 2-3 times, sometimes just one)

In **4.2.0**
Nothing is printed

It works fine although it doesn't print nothing

**Comment by luin** [comment]
@acuervof Thank you for the details. I tested with 4.2.0 and "Redis connection for cluster established" is printed to the console. Could you enable the debug mode with 4.2.0 (DEBUG=ioredis:* node yourapp.js) and post the logs here?
