### ISSUE TITLE
proposition: cluster client SCAN method scan on all cluster nodes

### ISSUE THREAD

**Issue by funduck** [luin/ioredis#736]
I implemented this for my work, it works as if there is no cluster behind  
Does the project need it?

**Comment by luin** [comment]
What will happen when a failover happens in the Cluster while scanning?

**Comment by funduck** [comment]
Well, I still have to do something about it, I'll write then.  
How do you think it should behave? the easiest is to throw an error..

**Comment by funduck** [comment]
well, that sounds right, I didn't need 'perfect' implementation and it was not hard to make one, so others can do too.   
thanks for replies!
