### ISSUE TITLE
Unexpected results from Multi Exec block

### ISSUE THREAD

**Issue by jakedipity** [luin/ioredis#739]
In the following piece of code, the multi exec block sometimes returns `null` and `null` for err and results respectively.

```
const AUTO_EXPIRE = 90;
let redisKey = 'semaphore';
redis.llen(redisKey, (err, results) => {
  if (err) return console.log(err);
  if (results === 0) {
    redis.multi().rpush(redisKey, 'wakeup').expire(redisKey, AUTO_EXPIRE).exec((err, results) => {
      if ((err = err || results[0][0] || results[1][0])) return console.log(err);
    });
  }
});
```

Most of the time, `err` is null and `results` is [[null, 1], [null, 1]], but sometimes the `results` is just null and it causes my program to crash. Also, from what I'm seeing, it doesn't seem like the rpush or expire commands get through to redis.

There really isn't any reason for this to be occurring, no disconnects from redis. I am using sentinels. Running ioredis 4.0.1

I also have other multi exec blocks in various places doing different things, but none of those experienced any of the same problems.

**Comment by jakedipity** [comment]
You can safely ignore this issue. I mistakenly thought ioredis will give me an error when a transaction is invalidated by a watch command, but the result is just null.

**Comment by luin** [comment]
Closing this issue then.
