### ISSUE TITLE
error: Error: connect ETIMEDOUT

### ISSUE THREAD

**Issue by kasarlashushruth** [luin/ioredis#740]
This the sample code i am using
node version v9.2.0
ioredis version 4.2.0
express 4.16.3

var ssl = {
    key: privatekey,
    // secureProtocol: 'TLSv1_method',
    // strictSSL: false,
    passphrase: pass,
    cert: certificate,
    ca
};
var sentinel_list = [
    { host: 'host', port: port_number }
];
bd_name = 'some name';
var client = new Redis({
    sentinels: sentinel_list,
    password: "password",
    // socket_keepalive: true,
    name: bd_name,
    // showFriendlyErrorStack: true,
    connectTimeout: 10000,
    tls: ssl
});
client.on('error', function(err){
    console.log('Something went wrong ', err);
});
client.on('connect', function() {
    console.log('Connected to Redis');
});
set and get methods bellow

When ever i try to connect it gives "error: Error: connect ETIMEDOUT"
Trials i have done
1) Increased connectTimeout from 3 sec to 1 hour same error
2) The certs are working if connect with java jedis
3) Tried lot combinations of sending certs and key with or without encryption and chained etc one time just key and ca one time with all key cert and ca , chained once but same error

The ioredis Debug logs are bellow

> DEBUG=ioredis:* node app.js

  ioredis:redis status[localhost:6379]: [empty] -> connecting +0ms
  ioredis:redis status[host:port]: [empty] -> connecting +2ms
  ioredis:redis queue command[host:port]: 0 -> sentinel([ 'get-master-addr-by-name', 'name' ]) +1ms
  ioredis:redis queue command[localhost:6379]: 0 -> set([ 'foo1', 'shushruth' ]) +1ms
  ioredis:redis queue command[localhost:6379]: 0 -> get([ 'foo1' ]) +0ms
  ioredis:redis status[ip]: connecting -> connect +249ms
  ioredis:redis status[ip]: connect -> ready +1ms
  ioredis:connection send 1 commands in offline queue +0ms
  ioredis:redis write command[ip]: 0 -> sentinel([ 'get-master-addr-by-name', 'name' ]) +0ms
  ioredis:redis write command[ip]: 0 -> sentinel([ 'sentinels', 'name' ]) +39ms
  ioredis:SentinelConnector Updated internal sentinels: [{"host":"host","port":port}] @1 +0ms
  ioredis:SentinelConnector resolved: ip +1ms
  ioredis:redis status[ip]: ready -> close +187ms
  ioredis:connection skip reconnecting since the connection is manually closed. +226ms
  ioredis:redis status[ip]: close -> end +0ms
  ioredis:connection error: Error: connect ETIMEDOUT +10s
Something went wrong  { Error: connect ETIMEDOUT
    at Socket.<anonymous> (/Users/sredd140/Research/redis1/node_modules/ioredis/built/redis.js:273:31)
    at Object.onceWrapper (events.js:254:19)
    at Socket.emit (events.js:159:13)
    at Socket._onTimeout (net.js:411:8)
    at ontimeout (timers.js:478:11)
    at tryOnTimeout (timers.js:302:5)
    at Timer.listOnTimeout (timers.js:262:5) errorno: 'ETIMEDOUT', code: 'ETIMEDOUT', syscall: 'connect' }
  ioredis:redis status[localhost:6379]: connecting -> close +10s
  ioredis:connection reconnect in 50ms +1ms
  ioredis:redis status[localhost:6379]: close -> reconnecting +0ms
  ioredis:redis status[localhost:6379]: reconnecting -> connecting +53ms
  ioredis:redis status[host:port]: [empty] -> connecting +0ms
  ioredis:redis queue commandhost:port]: 0 -> sentinel([ 'get-master-addr-by-name', 'name' ]) +0ms
  ioredis:redis status[ip]: connecting -> connect +272ms
  ioredis:redis status[ip]: connect -> ready +0ms
  ioredis:connection send 1 commands in offline queue +326ms
  ioredis:redis write command[ip]: 0 -> sentinel([ 'get-master-addr-by-name', 'name' ]) +1ms
  ioredis:redis write command[ip]: 0 -> sentinel([ 'sentinels', 'name' ]) +37ms
  ioredis:SentinelConnector Updated internal sentinels: [{"host":"host","port":port}] @1 +11s
  ioredis:SentinelConnector resolved: ip +1ms
  ioredis:redis status[ip]: ready -> close +370ms
  ioredis:connection skip reconnecting since the connection is manually closed. +407ms
  ioredis:redis status[ip]: close -> end +0ms
  ioredis:connection error: Error: connect ETIMEDOUT +10s
Something went wrong  { Error: connect ETIMEDOUT
    at Socket.<anonymous> (/Users/sredd140/Research/redis1/node_modules/ioredis/built/redis.js:273:31)
    at Object.onceWrapper (events.js:254:19)
    at Socket.emit (events.js:159:13)
    at Socket._onTimeout (net.js:411:8)
    at ontimeout (timers.js:478:11)
    at tryOnTimeout (timers.js:302:5)
    at Timer.listOnTimeout (timers.js:262:5) errorno: 'ETIMEDOUT', code: 'ETIMEDOUT', syscall: 'connect' }
  ioredis:redis status[localhost:6379]: connecting -> close +10s
  ioredis:connection reconnect in 100ms +0ms
  ioredis:redis status[localhost:6379]: close -> reconnecting +0ms
  ioredis:redis status[localhost:6379]: reconnecting -> connecting +102ms
  ioredis:redis status[host:port]: [empty] -> connecting +0ms
  ioredis:redis queue command[host:port]: 0 -> sentinel([ 'get-master-addr-by-name', 'name' ]) +0ms
  ioredis:redis status[ip]: connecting -> connect +40ms
  ioredis:redis status[ip]: connect -> ready +0ms
  ioredis:connection send 1 commands in offline queue +142ms
  ioredis:redis write command[ip]: 0 -> sentinel([ 'get-master-addr-by-name', 'name' ]) +0ms
  ioredis:redis write command[ip]: 0 -> sentinel([ 'sentinels', 'name' ]) +66ms
  ioredis:SentinelConnector Updated internal sentinels: [{"host":"host","port":port}] @1 +11s
  ioredis:SentinelConnector resolved: ip +0ms
  ioredis:redis status[ip]: ready -> close +256ms
  ioredis:connection skip reconnecting since the connection is manually closed. +322ms
  ioredis:redis status[ip]: close -> end +0ms

Please help me with the issue.
Feel free if needed any more details

Thanks for the help

**Comment by luin** [comment]
Does it work that connecting to the ip that returned by `ioredis:SentinelConnector resolved: ip` directly?

**Comment by kasarlashushruth** [comment]
When i use the resolved ip,
With out ssl its working but when i turn on ssl and try to connect it not.

FYI, the key is client private key
cert is client public cert
CA is a chained cert of Client public cert, intermediate cert and trust root

i tried passing only key and ca
or passing key, cert and ca with out client public cert and other time with ca with client public cert

**Comment by fenichelar** [comment]
I think I'm seeing the same issue. I'm using Redis Enterprise from Redis Labs.

Without TLS, I can connect directly to the IP of the master node or I can connect using sentinel.

With TLS, I can only connect directly to the IP of the master node. When attempting to use sentinel, I see the same error described above:

`DEBUG=* node app.js`

```
ioredis:redis status[localhost:6379]: [empty] -> connecting +0ms
ioredis:redis status[10.0.11.99:8001]: [empty] -> connecting +2ms
ioredis:redis queue command[10.0.11.99:8001]: 0 -> sentinel([ 'get-master-addr-by-name', 'clearip' ]) +1ms
ioredis:redis status[10.0.11.99:8001]: connecting -> connect +4ms
ioredis:redis status[10.0.11.99:8001]: connect -> ready +1ms
ioredis:connection send 1 commands in offline queue +0ms
ioredis:redis write command[10.0.11.99:8001]: 0 -> sentinel([ 'get-master-addr-by-name', 'clearip' ]) +0ms
ioredis:redis write command[10.0.11.99:8001]: 0 -> sentinel([ 'sentinels', 'clearip' ]) +2ms
ioredis:SentinelConnector Updated internal sentinels: [{"host":"10.0.11.99","port":8001},{"host":"10.0.12.99","port":8001},{"host":"10.0.13.99","port":8001}] @1 +0ms
ioredis:SentinelConnector resolved: 10.0.11.99:11000 +0ms
ioredis:redis status[10.0.11.99:8001]: ready -> close +2ms
ioredis:connection skip reconnecting since the connection is manually closed. +4ms
ioredis:redis status[10.0.11.99:8001]: close -> end +1ms
```

**Comment by fenichelar** [comment]
@luin Looking at the sentinel connector, it does not appear to support connecting using TLS. Would you be open to a PR to add support for TLS when sentinel is used? Also, would you reopen this issue? Thanks.

**Comment by fenichelar** [comment]
https://github.com/luin/ioredis/pull/772

@luin Please let me know if there is something that needs changing.
