### ISSUE TITLE
Redis cluster and transactions

### ISSUE THREAD

**Issue by kiko35** [luin/ioredis#742]
from https://github.com/luin/ioredis/issues/417

Hi, sorry for the late response. You must make sure all keys belong to the same slot when using pipeline in the cluster mode.

For example:

```javascript
cluster.pipeline().set('{foo}1', 'bar').set('{foo}2', 'bar').exec()
```

_Originally posted by @luin in https://github.com/luin/ioredis/issues/417#issuecomment-275303869_

How can we do that please? Because I don't know if all the keys of my transaction belong to the same node.

**Comment by luin** [comment]
@kiko35 Either make sure that there's only one key in the pipeline or make sure that all keys in the pipeline have the same part that surrounds by brackets (like the example above).

**Comment by kiko35** [comment]
Ok thanks.
