### ISSUE TITLE
codebase

### ISSUE THREAD

**Issue by ORESoftware** [luin/ioredis#75]
Just for my own sake:

how is this different:

```javascript
exports = module.exports = require('./lib/redis');

exports.ReplyError = require('./lib/reply_error');
exports.Promise = require('bluebird');
exports.Cluster = require('./lib/cluster');

exports.print = function (err, reply) {
  if (err) {
    console.log('Error: ' + err);
  } else {
    console.log('Reply: ' + reply);
  }
};
```

from this?

```javascript
var ioredisExports = require('./lib/redis');

ioredisExports.ReplyError = require('./lib/reply_error');
ioredisExports.Promise = require('bluebird');
ioredisExports.Cluster = require('./lib/cluster');
ioredisExports.print = function (err, reply) {
  if (err) {
    console.log('Error: ' + err);
  } else {
    console.log('Reply: ' + reply);
  }
};

module.exports = ioredisExports;
```

exports is already defined as module.exports, there is no need to redefine it.

this call is just bad

```
exports = module.exports = ....
```
don't do that

your code is so confusing. make it easier for people to understand. I won't trust the library with stuff like this.

**Comment by luin** [comment]
Thank you for reviewing the code. IMHO `exports = module.exports` is a convention that used in many node modules(e.g. Express).

Let me know if there's anything that I can help you. Thanks again for using ioredis.

**Comment by ORESoftware** [comment]
exports = module.exports is totally redundant, I don't care who uses it!

**Comment by AVVS** [comment]
I don't really see your point. This is a common convention and effectively does exactly the same as your "optimized" code. Furthermore, for the sake of it one might want to be politer when expressing his or her opinion

**Comment by ORESoftware** [comment]
Sorry, one cannot be polite when criticizing code, you just have to have a thick skin

the point is it took me too much time to figure out what your index.js was doing.
it should not be that hard.
your code is a mess in that file, which makes me doubt the other stuff.

**Comment by AVVS** [comment]
First of all code isn’t mine, I just happen to not like when people use OSS and complain. Create a PR, explain the reasoning, it will get merged and everybody will be happy, just my few cents

**Comment by ORESoftware** [comment]
My point is this:

var ioredis = require('ioredis');
console.log(ioredis.print());

your attaching a bunch of crap to the export object, either it's just wrong or it's bad design or both.

your index.js file should look like this:

```javascript
module.exports = require('./lib/redis');
```

the way it is now, when I require('ioredis'), attached to that object I am also getting Promise, Bluebird, Cluster.

It's just wrong guys, sorry.

**Comment by ORESoftware** [comment]
@AVVS sure, I understand. I just want to make sure my point makes any sense before I create some PR that is useless

**Comment by ORESoftware** [comment]
if I am wrong please let me know, if I am more correct than not, I would happy to spend 20 hours refactoring the code

**Comment by luin** [comment]
Sorry for my late response, I was on the plane. Exporting multiple object via `exports` is absolutely not a bad design. In fact the most natural way to exports values in Node.js is assigning them to the `exports` instead of re-assigning `module.exports`. For instance ioredis may exports values by:

```javascript
exports.Redis = // xxx
exports.Cluster = // xxx
exports.ReplyError = // xxx
```

This way when people want to init a new `Redis` instance to connect to the Redis server, they have to:

```javascript
var ioredis = require('ioredis')
var redis = new ioredis.Redis()
```

However almost 90% developer may care only the `Redis` class, it's a little redundant to write `ioredis.Redis` every time. So this library exports the `Redis` class as a default value and on the other hand, still exports the other values(`Cluster`, `ReplyError`) via `exports`.

`exports = module.exports` is used to make sure `exports` point to the `module.exports`.

Your way exporting values by using `ioredisExports` has the same result as the library current does. But semantically `ioredisExports` makes people confused. Think about the following two code snippets:

```javascript
import Redis, { Cluster, ReplyError } from 'ioredis';
```

```javascript
import Redis from 'ioredis';
let Cluster = Redis.Cluster;
let ReplyError = Redis.ReplyError;
```

**Comment by ORESoftware** [comment]
have a look at the Express NPM module

they have the same thing as you

```javascript
var express = require('express');
var app = express();
```

you should make the export functionality so that ioredis =~ express

so you can return a function from the express module, but also attach properties to that function.

that's why we can call express() but also call express.static or express.Router

Frankly, the Express library doesn't do it right either. but you can make your index.js file simpler, by modeling it like the Express module. your library and the Express module are overcomplicating things.

exports = module.exports ...

that is bad

do this instead

```javascript
function IORedis(){

}

IORedis.luin = function(){

}

IORedis.overcomplicateEverything = function(){

}

module.exports = IORedis;
```


this is SOOOOO much clear. Do you want to be like those assholes that wrote Express or do you want to think for yourself and help the community? :)

**Comment by luin** [comment]
Exporting multiple objects and having one of them as the default value of the module are different from exporting an object(`IORedis`) that has multiple objects as its properties, semantically.

**Comment by ORESoftware** [comment]
I don't think so, can you prove that?

**Comment by ORESoftware** [comment]
yes syntactically it is different, but semantically it is not different
