### ISSUE TITLE
blocking in redis command when redis disconnect

### ISSUE THREAD

**Issue by alansmith18** [luin/ioredis#751]
_**### I use ioredis as a cluster. as follow:**_
const logger = require('../../log/logger.js').getLogger('util/redis/redis-pool.js');
const Redis = require('ioredis');
const host1 = "127.0.0.1";
const redisClusterServerList = [host1];
const redisClusterPortList = [6379, 6380, 6381, 6382, 6383, 6384, 6385, 6386];
const redisClusterNode = [];
for (const serverVar of redisClusterServerList) {
    for (const portVar of redisClusterPortList) {
        redisClusterNode.push({host: serverVar, port: portVar});
    }
}

const cluster = new Redis.Cluster(redisClusterNode,
    {
        dropBufferSupport: true,
        maxRetriesPerRequest: 1,
        scaleReads: "all"
        ,
        redisOptions: {
            db: 0,
            password: 'redispwd'
        }
    });
module.exports = cluster;

### **_Suppose that at this time I kill redis-server process on the server, the connection instance of the cluster is disconnected from redis._**
Then I execute the command as es6，follow：
try {
            let result = await redis.hmset(`${ServerSocketService.USER_KEY_PREFIX_FOR_REDIS()}${session.id}`, session);
        } catch (e) {
            log.error(e);
        }

### **_Then the code is blocked in：_**
 await redis.hmset(`${ServerSocketService.USER_KEY_PREFIX_FOR_REDIS()}${session.id}`, session);

### **_How can I avoid blocking here, but let the code be caught by the try-catch block?_**

**Comment by luin** [comment]
You can disable the `clusterRetryStrategy` option. See readme for details.

**Comment by alansmith18** [comment]
> You can disable the `clusterRetryStrategy` option. See readme for details.

thank you
