### ISSUE TITLE
Support for Elastiche Redis with cluster mode disabled.

### ISSUE THREAD

**Issue by vanrysss** [luin/ioredis#755]
Is there any chance this feature will be added? It seems like a pretty common use case for folks who don't need sharding but do want a read backup.

**Comment by luin** [comment]
Hi @vanrysss , what problem did you experience when using ioredis with Elastiche Redis?

**Comment by emadum** [comment]
Hi @luin, I came across this ticket while evaluating ioredis for use with Elasticache with cluster mode disabled, and can provide some more details.

Elasticache supports two types of replication, Cluster Mode enabled/disabled. With cluster mode disabled, attempting to connect via ioredis yields the unsurprising error of:

`ERR This instance has cluster support disabled`

However, it would be nice if we could bypass the majority of the cluster-mode code, and just take advantage of the read-write splitting feature.

This could potentially be achieved by manually specifying the master/slave roles in the nodes array when initializing the cluster. E.g.,

```
const cluster = new Redis.Cluster([
  {host: 'primary endpoint', port: 6379, role: 'master'},
  {host: 'r/o slave endpoint 1', port: 6379, role: 'slave'}
  {host: 'r/o slave endpoint 2', port: 6379, role: 'slave'}
]);
```

**Comment by luin** [comment]
@emadum Thanks for suggesting! `Redis.Cluster` is designed to communicate with the official Redis cluster (https://redis.io/topics/cluster-spec, cluster mode enabled with Elasticache), so we may have another class (like `Redis.ReplicaGroup`) for that use case. Currently there's no plan to implement that, but I'll revisit this about two or three months later. Pull requests for this feature will be always welcome.

**Comment by MatteoGioioso** [comment]
@luin is there a workaround? Or we can just instantiate two separate clients and use them for writes and reads separately?

**Comment by luin** [comment]
> @luin is there a workaround? Or we can just instantiate two separate clients and use them for writes and reads separately?

Yeah the possible workaround would be using two client instances, one for master and the other for slave.

**Comment by IgorEulalio** [comment]
This feature have been added?

**Comment by ductran-ms** [comment]
Hello, can someone give a recommendation on how to connect to Elasticache with cluster mode disable? Ideally, all reads should be distributed automatically among the replicas. Thank you.
