### ISSUE TITLE
How to use Hooks with Redis Cluster on ioredis

### ISSUE THREAD

**Issue by willemevenwel** [luin/ioredis#757]
Hi,

I've been going thru previous issues and feature requests regarding this, but I can not for the life of me get it to work as I thought it should.

Using ioredis in my package.json:
    "ioredis": "^4.2.0",

My Code:

```
const Redis  = require(ioredis);
const redisCluster = new Redis.Cluster(config.REDIS.CLUSTER, {
    keyPrefix: ${prefix},
    hooks: {
        beforeSend(command, args) {
            console.log(${command} - ${args});
        },
        afterFetch(command, replies) {
            console.log(${command} - ${replies});
        }
    }
});
```

But upon executing any commands, set or red on my cluster instance: redisCluster

The beforeSend and afterFetch delegates are NOT firing (console.logs not printing out). My redis instances are valid instances, the writing and reading works fine without issue.

Please could someone advise or assist.

**Comment by luin** [comment]
The feature of hooks hasn't been implemented yet.
