### ISSUE TITLE
[Cluster] refresh slots after promotion with public/private ip addresses

### ISSUE THREAD

**Issue by jayflo** [luin/ioredis#760]
The nodes in our redis cluster have public/private ip addresses.  When the cluster is setup, the nodes.conf contains all the public ip addresses for each node and everything works fine.  However, during the process of replica being promoted to master, the replica updates its nodes.conf file and uses private ip address for itself, i.e. the `myself` entry.  Once this happens the ioredis client will start to have connectivity problems.

I'd guess the problem has to do with the refreshing the slots:

https://github.com/luin/ioredis/blob/3702d67e0a243d87ca40b7b096a0c9c8a41ee705/lib/cluster/index.ts#L343

which happens periodically (https://github.com/luin/ioredis/blob/77231b588393e56f3605ae8305853a8f9059f021/lib/cluster/index.ts#L110) and in reaction to some redis responses.

I'm not too sure of this implications at this point, but if there were an option to disable all `CLUSTER SLOTS` commands, would this avoid the issue (and have the client continue to work correctly)?

**Comment by luin** [comment]
ioredis provides nat option that should solve your problem (by mapping private addresses to the public addresses): https://github.com/luin/ioredis#nat-mapping.

**Comment by jayflo** [comment]
Ah, thanks.
