### ISSUE TITLE
【Non-technology】How is the progress for merging with node_redis?

### ISSUE THREAD

**Issue by libook** [luin/ioredis#761]
I found that there were declarations that ioredis and node_redis have been merging.
So how is the progress?
Is there any plan or milestone?
How can the community help?

**Comment by luin** [comment]
Thank you for asking! There's not much progress on this issue currently. Maintainers of both projects are been busy, and the merge process will introduce breaking changes, which will be pretty bothersome to the developers.

Having said that, the two projects have already shared a lot of important code (say redis-parser & redis-commands) and may find more common modules to share in future.

**Comment by libook** [comment]
Thanks for your time for replying this.

It's a big job. If you feel hard, many hands make light work.

Have a good day!
