### ISSUE TITLE
QUESTION: Is it possible to use SCAN and/or scanStream in Redis Cluster?

### ISSUE THREAD

**Issue by Pistacchione** [luin/ioredis#764]
Hi,

is it possible to use `scan` and/or `scanStream` in redis cluster?
And if it's possible, the scan command will scan all redis nodes?

Thanks

**Comment by skyzenr** [comment]
Hi @Pistacchione ,
I faced the same problem few days ago.

To the best of my knowledge, the SCAN operation iterates over all keys on a single Redis node.

Take a look at #175 or [https://paluch.biz/blog/162-iterate-over-all-keys-in-a-redis-cluster.html](https://paluch.biz/blog/162-iterate-over-all-keys-in-a-redis-cluster.html).

Hope it helps.
Roberto

**Comment by swetha21** [comment]
HI,

How to query keys from redis.cluster by using specific pattern (using scanStream).
Please do needful.

Thanks,
Swetha

**Comment by QuanTran91** [comment]
Hi guys, we should open this issue. I cannot get all keys with patterns in all nodes.
