### ISSUE TITLE
Promise.onPossiblyUnhandledRejection is not a function ERROR

### ISSUE THREAD

**Issue by WuStardust** [luin/ioredis#767]
I have used to handle errors in the version of 3.2.2 by using code like below
``` node
const Redis = require('ioredis');

Redis.Promise.onPossiblyUnhandledRejection((error) => {
  console.logr('ioredis onPossiblyUnhandledRejection:', error);
});
```
  
Recently I upgraded the version to 4.3.0. 
Then I tried to run my app, it didn't work and told me ```Redis.Promise.onPossiblyUnhandledRejection is not a function```
It seems that the **README** also has deleted related descriptions. Is there any more information about this change? Has this method been deprecated or replaced by other ones?   
  
**Thanks a lot~ ^_^**

**Comment by btd** [comment]
ioredis 3.x used `bluebird` as Promise lib underhood (which has huge number of extensions to Promise). and at 4.x they switched to use native promises.

**Comment by WuStardust** [comment]
OK then that make sense. 
Thanks~

**Comment by RifeWang** [comment]
so how to fix this ? @btd

**Comment by WuStardust** [comment]
> so how to fix this ? @btd

just use the native promise handler
```
process.on('unhandledRejection', (reason, p) => {
  console.log('Unhandled Rejection:', reason, p);
});

process.on('uncaughtException', (reason, p) => {
  console.log('uncaught Exception:', reason, p);
});
```
