### ISSUE TITLE
Uncaught TypeError: Cannot read property 'charCodeAt' of undefined

### ISSUE THREAD

**Issue by darweshsinghcgi** [luin/ioredis#769]
Uncaught TypeError: Cannot read property 'charCodeAt' of undefined
    at Object.eval (index.js?f3c2:3)
    at eval (index.js:9)
    at Object../node_modules/redis-errors/index.js (app.js:6641)
    at __webpack_require__ (app.js:725)
    at fn (app.js:102)
    at eval (MaxRetriesPerRequestError.js?95d5:3)
    at Object../node_modules/ioredis/built/errors/MaxRetriesPerRequestError.js (app.js:5721)
    at __webpack_require__ (app.js:725)
    at fn (app.js:102)
    at eval (index.js?a335:3)

Using `ioredis` inside a Vue.js web-app (with webpack). The error appears even when only this line is present: `const Redis = require('ioredis')`.

**Comment by darweshsinghcgi** [comment]
This is an issue with a lack of process.env availability for the webapp, and not with ioredis. Closing.

**Comment by Garry14** [comment]
I have same error.. 
If you have solved it, tell me please..

**Comment by tuananh** [comment]
ioredis can be used from backend only

**Comment by TimonPeng** [comment]
This is also happened when called from nextjs middleware

**Comment by gaoconggit** [comment]
我也遇到了同样的问题。 这个有优雅的解决方案吗

**Comment by kstratis** [comment]
Exactly @TimonPeng. 
I'm also using redis in middleware and get the same error. 

Does this mean that we can't have redis on middleware or is there any way to signal that we're specifically using node js to get rid of the error?

**Comment by Tobjoern** [comment]
> Exactly @TimonPeng. I'm also using redis in middleware and get the same error.
> 
> Does this mean that we can't have redis on middleware or is there any way to signal that we're specifically using node js to get rid of the error?

So from my understanding, this library actually needs various node.js modules, which aren't available in the next.js middleware runtime.
One solution seems to be a version of redis, which is compatible with this runtime, like the one upstash provides: https://www.tuomokankaanpaa.com/blog/nextjs-middleware-save-data-to-redis.
