### ISSUE TITLE
Disabled ready_check on MONITOR

### ISSUE THREAD

**Issue by nakulgan** [luin/ioredis#77]
Is there a reason why `enableReadyCheck` is set to false on MONITOR?
[redis.js](https://github.com/luin/ioredis/blob/master/lib/redis.js#L421)

The behaviour I've observed so far is, MONITOR issued while `loading=1` fails.

**Comment by luin** [comment]
Code in the master branch should fix this bug. Thank you for letting me know.

**Comment by nakulgan** [comment]
Great! Thanks for quick fix.
