### ISSUE TITLE
 zrevrange() gives empty results

### ISSUE THREAD

**Issue by privateOmega** [luin/ioredis#782]
* **Version**: 5.0.3(Linux on Docker)
* **Platform**: Node.js v8.12.0 on Windows 10
* **Description**: zrevrange() returns [] even though on redis-cli it gives non-empty array as result.

> let idList = await this.client.zrevrange(`${this.exactStore}:${word}`, 0, -1);

Output from Code:
> console.log(`ZREVRANGE ${this.exactStore}:${word} 0 -1`);
produces the following
> ZREVRANGE exactstore:rse:frank⁠ 0 -1
> []

Output from Redis-Cli:
> 127.0.0.1:6379> ZREVRANGE exactstore:rse:frank 0 -1
> 1) "aG2_aHKvxFEzE9CeUlo_y"
> 2) "JHihXTds2T0cNnr4er0D1"

Please take a look at [node_redis](https://github.com/NodeRedis/node_redis/issues/1407) for the same issue in node_redis libary.

**Comment by luin** [comment]
Hi @privateOmega. I wonder if the command was sent to the correct db (that same one redis-cli connected to). Could you please run `monitor` on the redis-cli and execute the program again to see whether the command is sent to the correct db?

**Comment by privateOmega** [comment]
@luin Thanks for the important information. I got the commands back and is being executed on same db, but I found out that there's a word joiner unicode character `\xe2\x81\xa0` present in the strings which are actually present in the db. I will debug my code to find if it had something to do with my code.

**Comment by privateOmega** [comment]
@luin do you know what could be the reason for it?

**Comment by luin** [comment]
@privateOmega I don't think it's a problem on the ioredis side. You may want to create a minimal demo that can reproduce the issue to see where the problem is. For example:

```javascript
const Redis = require('ioredis')
new Redis().zrevrange('exactstore:rse:frank', 0, -1, console.log);
```

**Comment by privateOmega** [comment]
@luin yes ofcourse, after identifying that an extra unicode character is present, I got the idea that it had nothing to do with neither redis client nor redis itself. I was asking that doubt in general.
