### ISSUE TITLE
Error: Too many Cluster redirections

### ISSUE THREAD

**Issue by lakano** [luin/ioredis#787]
Hello!

I've upgraded ioredis from 4.2.3 to 4.5.1 and now I have this kind of errors.
I've also tried to move to 4.6.0
If I revert back to 4.2.3, I doesn't have this problem.

If you have any idea to help me to fix that, thanks ! :)

```
{"log":"  Error: Too many Cluster redirections. Last error: Error: Connection is closed.\n","stream":"stdout","time":"2019-01-24T16:41:14.457716816Z"}
{"log":"      at Cluster.handleError (/home/node/node_modules/ioredis/built/cluster/index.js:531:38)\n","stream":"stdout","time":"2019-01-24T16:41:14.45772379Z"}
{"log":"      at Command.command.reject (/home/node/node_modules/ioredis/built/cluster/index.js:410:23)\n","stream":"stdout","time":"2019-01-24T16:41:14.45772891Z"}
{"log":"      at Redis.flushQueue (/home/node/node_modules/ioredis/built/redis.js:384:26)\n","stream":"stdout","time":"2019-01-24T16:41:14.457733731Z"}
{"log":"      at close (/home/node/node_modules/ioredis/built/redis/event_handler.js:102:14)\n","stream":"stdout","time":"2019-01-24T16:41:14.457738482Z"}
{"log":"      at Socket.\u003canonymous\u003e (/home/node/node_modules/ioredis/built/redis/event_handler.js:69:20)\n","stream":"stdout","time":"2019-01-24T16:41:14.457743188Z"}
{"log":"      at Object.onceWrapper (events.js:273:13)\n","stream":"stdout","time":"2019-01-24T16:41:14.457748452Z"}
{"log":"      at Socket.emit (events.js:182:13)\n","stream":"stdout","time":"2019-01-24T16:41:14.457753123Z"}
{"log":"      at TCP._handle.close (net.js:606:12),\n","stream":"stdout","time":"2019-01-24T16:41:14.457757466Z"}
{"log":"  [ null, null ] ]\n","stream":"stdout","time":"2019-01-24T16:41:14.457761851Z"}
{"log":"(node:8) UnhandledPromiseRejectionWarning: ReplyError: ERR value is not a valid float\n","stream":"stderr","time":"2019-01-24T16:41:24.596806401Z"}
{"log":"    at parseError (/home/node/node_modules/redis-parser/lib/parser.js:179:12)\n","stream":"stderr","time":"2019-01-24T16:41:24.59685172Z"}
{"log":"    at parseType (/home/node/node_modules/redis-parser/lib/parser.js:302:14)\n","stream":"stderr","time":"2019-01-24T16:41:24.596856275Z"}
{"log":"(node:8) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)\n","stream":"stderr","time":"2019-01-24T16:41:24.596859821Z"}
{"log":"(node:8) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.\n","stream":"stderr","time":"2019-01-24T16:41:24.59686564Z"}

```

**Comment by luin** [comment]
Could you please enable the debug mode (DEBUG=ioredis:* node yourapp.js) and run the program with 4.5.1 and post the logs here?

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by lakano** [comment]
This is an extract, until the Error: Too many Cluster redirections ( sorry for the log format )

https://pastebin.com/qBWw2eux

**Comment by lakano** [comment]
Humm just revert back to 4.2.3, and I still have the same issue, so it's not caused by the version of ioredis (sorry for my previous wrong test !)
Do you have any idea that could help us to solve this cluster connection problem please?

**Comment by luin** [comment]
Thank you for the further information. According to the logs, the cluster gives different results for the command `cluster slots`, especially for the slot range "10923~16383 ". Sometimes the node `10.42.10.43:6379` was returned, but sometimes `10.42.10.43:6379` was given, leading ioredis sends the command to different node every time.

I noticed there are some timeout errors in the log. Is there any network issue in the cluster?

**Comment by lakano** [comment]
You right, this was a network DNS resolution problem ( k8s configuration related )

**Comment by alizeyj** [comment]
> You right, this was a network DNS resolution problem ( k8s configuration related )

What was the k8s config which went wrong? We are also facing a similar issue at the moment.

**Comment by tushardunzo** [comment]
Would be interested in knowing this. We’re seeing a similar issue but there have been no changes in our k8s configurations. We also tried reducing the TTL for dns caching and scaling kube-dns pods, that didn’t help.

**Comment by mkumar-tc** [comment]
@tushardunzo @alizeyj @lakano 
Were you guys able to make any further findings on it? I see an intermittent issue coming up and then resolved under seconds.

**Comment by lakano** [comment]
Sorry guys for the silent, I've not seen the previews notifications. 
I haven't found any solution. I also tried with KeyDB (Redis alternative) and still have connection issues. So we finally change to a single stronger node rather than a Redis cluster.

**Comment by mkumar-tc** [comment]
I happen to find this issue relevant with the case where I saw the **"Error: Too many Cluster redirections"**
https://github.com/redis/redis/issues/1154 @lakano
