### ISSUE TITLE
Cannot BRPOP from multiple lists in cluster mode

### ISSUE THREAD

**Issue by klinquist** [luin/ioredis#79]
```
clusterClient.brpop('list1', 'list2', function(err, data){

});
```

This works fine in standalone mode, but now that I've moved to cluster mode, I get err back as {};

**Comment by luin** [comment]
According to redis cluster spec, keys in a command should belong to the same slot. That means you can't brpop two lists belong to the different slots.

The following code works:

```javascript
clusterClient.brpop('{list}1', '{list}2', function(err, data){
});
```

However ioredis definitely need to show a more friendly error info in this case.

**Comment by luin** [comment]
hi, I just did some tests and what I get is a `ReplyError` instead of `{}`. Can you reproduce it?

**Comment by luin** [comment]
I'm closing the issue. If there's any problem related to it, feel free to reopen it.
