### ISSUE TITLE
Cluster subscribe does not work when TLS is enabled for AWS Redis Cluster

### ISSUE THREAD

**Issue by andrewm42** [luin/ioredis#791]
<h2>Tested Using</h2>

* Node.js v10.13.0
* ioredis v4.5.1
* AWS Clustered Redis Elasticache  (3 nodes, in-transit and at-rest encryption enabled)

<h2>Problem</h2>

Disabling TLS breaks the pub/sub subscribe functions for me. I have tried everything in this post: https://github.com/luin/ioredis/issues/754 to resolve it but I always get this error:

> MaxRetriesPerRequestError: Reached the max retries per request limit (which is 20). Refer to "maxRetriesPerRequest" option for details

<h2>Example</h2>

This occurs when using the simple example below:

```
  const nodes = [{
      host: ...,
      port: ...,
  }];
  const redisOptions = {
      tls: {},
  };
  const clusterOptions = {
      redisOptions: redisOptions,
      dnsLookup: (address, callback) => callback(null, address),
  };

  const redis = new Redis.Cluster(nodes, clusterOptions);
  const pub = new Redis.Cluster(nodes, clusterOptions);

  redis.subscribe('mychannel1', (err, count) => {
    console.log(err);
    pub.publish('mychannel1', 'Hello world!');
  });

  redis.on('message', (channel, message) => {
    console.log(`Received message ${message} from channel ${channel}`);
  });
```

Publish works fine. Subscribe does not. Has anyone else encountered this error?

**Comment by r3b-fish** [comment]
It's possible solution but I think instantiation of subscriber should be more elegant

```diff
diff --git a/lib/cluster/ClusterSubscriber.ts b/lib/cluster/ClusterSubscriber.ts
index 11c1e0b..c176bec 100644
--- a/lib/cluster/ClusterSubscriber.ts
+++ b/lib/cluster/ClusterSubscriber.ts
@@ -71,7 +71,8 @@ export default class ClusterSubscriber {
       password: options.password,
       enableReadyCheck: true,
       connectionName: SUBSCRIBER_CONNECTION_NAME,
-      lazyConnect: true
+      lazyConnect: true,
+      tls: options.tls
     })
```
