### ISSUE TITLE
ioredis:SentinelConnector should not add localhost sentinels

### ISSUE THREAD

**Issue by sawan-rana** [luin/ioredis#796]
Hi All,

Using sentinel feature of ioredis. 
Problem: sentinel connector adding localhost ports even though remote host is provided inside sentinel config. 

 var rConfig = {
    name: 'mymaster',
    sentinels: [{host: '10.254.16.40', port: 26379},{host: '10.254.16.40', port: 26380},{host: '10.254.16.40', port: 26381}],
  }

DEBUG ioredis log:
ioredis:redis status[10.254.16.40:26379]: connecting -> connect +2s
ioredis:redis status[10.254.16.40:26379]: connect -> ready +1ms
ioredis:connection send 1 commands in offline queue +0ms
ioredis:redis write command[10.254.16.40:26379]: 0 -> sentinel([ 'get-master-addr-by-name', 'mymaster' ]) +1ms
ioredis:redis write command[10.254.16.40:26379]: 0 -> sentinel([ 'sentinels', 'mymaster' ]) +173ms
ioredis:SentinelConnector adding sentinel 127.0.0.1:26380 +0ms
ioredis:SentinelConnector adding sentinel 127.0.0.1:26381 +0ms
ioredis:SentinelConnector Updated internal sentinels: {"sentinels":[{"host":"10.254.16.40","port":26379},{"host":"10.254.16.40","port":26380},{"host":"10.254.16.40","port":26381},{"host":"127.0.0.1","port":26380},{"host":"127.0.0.1","port":26381 ... <REDACTED full-length="214"> +0ms
ioredis:SentinelConnector resolved: 127.0.0.1:6379 +2ms
ioredis:redis status[127.0.0.1:6379]: connecting -> connect +114ms
ioredis:redis write command[127.0.0.1:6379]: 0 -> info([]) +1ms
ioredis:redis status[127.0.0.1:6379]: connect -> ready +3ms
ioredis:redis status[10.254.16.40:26379]: ready -> close +214ms
ioredis:connection skip reconnecting since the connection is manually closed. +506ms
ioredis:redis status[10.254.16.40:26379]: close -> end +0ms

Any help  would be appreciated.

**Comment by luin** [comment]
What do you get when invoking `sentinel sentinels mymaster` on redis-cli? It seems the result contains a server whose host is 127.0.0.1.

**Comment by sawan-rana** [comment]
@luin Yes, result of **sentinel sentinels mymaster**  gives 127.0.0.1

**Comment by sawan-rana** [comment]
@luin Thanks!

**Comment by amanjain7838** [comment]
@luin 
Is there any flag for not checking the hosts from the list and take the options given during the initialization.
