### ISSUE TITLE
commandQueue state is corrupted when connection closes while processing pipeline reply

### ISSUE THREAD

**Issue by paulmelliere** [luin/ioredis#800]
The issue here seems to be that if the client loses connection while having processed only a portion of replies from a pipeline, on re-connect the `commandQueue` will contain commands from the pipeline that were never re-sent to Redis. Subsequent replies for commands that _were_ sent to Redis are delivered to the incorrect command promise.

Scenario:
1. Using multi w/ pipeline, execute this pipeline:
  `redis.multi().set('foo', 'a').get('foo').exec(callback);`
2. The responses to MULTI and SET ("OK" and "QUEUED" respectively) are successfully processed. The commands are popped off of the `commandQueue` and the results stored in the pipeline's internal `_result` array.
3. The client disconnects -> ioredis processes a connction close which saves the 2 remaining commands (`GET foo`, `EXEC`) to the `prevCommandQueue`.
4. The client reconnects -> ioredis processes a connect which re-executes the (`GET foo`, `EXEC`) and restores them into the `commandQueue`. Re-sending `EXEC` in this case does not result in re-sending the pipelined command, because the pipeline is expecting 4 commands to be written and only the 2 failed ones were written. i.e. The `writePending` variable in `execPipeline` never reaches 0 so the command is never sent to Redis. _After this point, the commandQueue state is corrupted and all results are "shifted" by 2 commands, meaning the result received for any given command will actually be the result for the command sent 2 after it._ 
5. The next command is executed and sent to redis:
  `redis.get('bar');` 
6. The reply from `GET bar` is processed -> the head of the `commandQueue` still contains the promise for `GET foo` from the pipeline, so the response from `GET bar` is delivered to the pipeline instead of to the promise returned by `redis.get('bar')`.

I'm working to create a test that demonstrates the issue in case the description isn't enough to understand what's happening. We're using ElastiCache Redis and notice this issue regularly during promotion of a slave to master. We see the SET command from the pipeline return a READONLY error, followed by a connection close, a connect, then commandQueue corruption. This seems to only be an issue when **autoResendUnfulfilledCommands** is true (the default). When **autoResendUnfulfilledCommands** is false, the unprocessed pipeline commands are not put back into the commandQueue.

**Comment by paulmelliere** [comment]
I created a branch with some failing tests demonstrating the issue: https://github.com/luin/ioredis/compare/master...paulmelliere:test/commandQueue-after-reconnect

As a workaround, we've disabled **autoResendUnfulfilledCommands** for now.

**Comment by areese159** [comment]
I have experienced the exact same issue and would love to see a fix for this.

**Comment by jpdutoit** [comment]
This is still important, stale-bot.
