### ISSUE TITLE
issue with elasticache on aws

### ISSUE THREAD

**Issue by yiwong2001** [luin/ioredis#804]
Hi,

I am running ioredis against an AWS ElastiCache cluster (5.0 version). I have one master node and two slaves. Iam using the cluster configuration endpoint to connect to the cluster.

```
client = new Redis.Cluster([config.redis],{slotsRefreshTimeout:5000});
```
I got two issues:

1.  I can see  Error ClusterAllFailedError: Failed to refresh slots cache.
2. It is fine to run write task, but when it run read methods like llen, get, then it hangs there.

client.llen(vkey, function (err, sum) {  // it is stopped at this stage
      console.log("sum..."+sum);
       client.set(key, JSON.stringify(i), 'EX', 60); // it can be run if it is not inside of llen method.
});

I also tried elasticache with cluster enabled to have 3 shards and 3 replica for each. It got same issue to run read method. 

Same code works when it is not cluster. 

Can you guide me please?

**Comment by yiwong2001** [comment]
Do you support scan, llen methods?

**Comment by luin** [comment]
Yes, almost all redis commands including scan & llen are supported with cluster mode. It seems to be a nat problem. Refer to https://github.com/luin/ioredis#nat-mapping for details.

**Comment by yiwong2001** [comment]
Hi @luin ,

Can I both for one question?  

It seems scan cmd can only return keys from one shard in cluster environment.  How can I get all keys in redis cluster?

In my test, I can see that the keys are on different shard nodes, when I query the primary endpoint it is returning the value from one node and not the other.

Do you have some good idea how to handle it?  

Thanks.

**Comment by luin** [comment]
There's no built-in way for that, but you can run command on each node and aggregate them manually. Refer to https://github.com/luin/ioredis#running-commands-to-multiple-nodes for details.

**Comment by yiwong2001** [comment]
Hi Luin,

thank you for your reply.

Is it same way for shards? 

I tried to configure each of shard urls instead of the primary endpoint. It seems I can get results by scan from different shards (can not if I use primary nodes), but I can not get results by mget with returned keys.

var nodes = [
{
host: 'test4abc-0001-001.jwkwktaab.0001.euw1.cache.amazonaws.com',
port: 6379,
},
{
host: 'test4abc-0002-001.jwkwktaab.0001.euw1.cache.amazonaws.com',
port: 6379,
}
];

//nodes = [{host:'test4abc.jwkwktaab.clustercfg.euw1.cache.amazonaws.com',port:6379}];
