### ISSUE TITLE
Synchronous execution of SUBSCRIBE and PUBSUB CHANNELS

### ISSUE THREAD

**Issue by iatsiuk** [luin/ioredis#805]
ioredis version: 4.6.2

I'm trying to achieve synchronous execution of SUBSCRIBE and PUBSUB CHANNELS commands; so PUBSUB CHANNELS command should receive channel i subscribed to in the SUBSCRIBE command. As for now, sometimes I get an empty reply, sometimes - subscribed channels.

Here is my code:
```js
const Redis = require('ioredis');

(async () => {
  const cluster = new Redis.Cluster(
    [
      'redis://172.18.0.11:7000',
      'redis://172.18.0.11:7001',
      'redis://172.18.0.11:7002'
    ],
    { enableOfflineQueue: false }
  );

  cluster.on('ready', async () => {
    await cluster.subscribe('ch');
    const reply = await cluster.pubsub('CHANNELS');

    console.log(reply);
  });
})();
```

Output:
```sh
~/application $ node ./src/redis-cluster.js
[]
~/application $ node ./src/redis-cluster.js
[]
~/application $ node ./src/redis-cluster.js
[ 'ch' ]
~/application $ node ./src/redis-cluster.js
[]
```

Could you please advice me on how to change my code to always get the list of subscribed channels?

**Comment by luin** [comment]
It's a limitation on the redis server side. When subscribing a channel, ioredis will only subscribe on a single node of the cluster. Redis server won't sync the subscription to other nodes, so when running `.pubsub`, the command may be sent to a different node, in which case an empty array will be returned.

As a workaround, there's a private variable that recording the subscribed channels on the client side: 

```javascript
await cluster.subscribe('ch');
console.log(cluster.subscriber.subscriber.condition.subscriber.set)`
```

But this may change in the later version.

**Comment by iatsiuk** [comment]
Thank you for your detailed explanation.
