### ISSUE TITLE
Redis.Cluster.get and .set Properties do not exist on type 'Cluster'

### ISSUE THREAD

**Issue by amelialaundy** [luin/ioredis#807]
When trying to call `get` or `set` on a cluster using "@types/ioredis": "^4.0.9" and typescript there is no definition for Cluster.set or .get:
![image](https://user-images.githubusercontent.com/7699279/53714015-c367bd00-3eb1-11e9-98e3-3b1c07b922e4.png)

as per docs it says you can do this:
https://github.com/luin/ioredis#cluster

I assume the type files are incorrect in @types/ioredis, I can't find an easy way to fix them. (would rather open issue here than in the behemoth that is the @types repo)

**Comment by adamhathcock** [comment]
This PR broke you like it did me: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/33315

Pin to 4.0.8 instead of updating to 4.0.9

**Comment by nickroberts** [comment]
I created a new PR to add the get / set methods: DefinitelyTyped/DefinitelyTyped#33655

**Comment by amelialaundy** [comment]
Awesome thanks so much @adamhathcock I obviously missed that when looking at the PR diffs. 
Thanks @nickroberts for quick fix!

**Comment by joshrp** [comment]
Good work stale bot. This is still broken and still and an issue. Is it possible to just publish the generated definitions instead of the global ones just being broken and out of date?

**Comment by thetutlage** [comment]
Hahaha. I have spent hours reading, why the normal Redis methods are missing on the Cluster, I though, this maybe a limitation from `redis` itself. Finally landed here.

So for anyone else. All the commands from the normal Redis client are fully supported by Redis cluster too, it's just missing in types.

**Comment by sophister** [comment]
Same problem and still broken

**Comment by stringang** [comment]
I use @types/ioredis version 4.14.1, TS compilation fails, there is no hdel Property on the Cluster type.

Is there any better solution than rolling back @types/ioredis to 4.0.8 version?
