### ISSUE TITLE
 ERR max number of clients reached

### ISSUE THREAD

**Issue by fuyangclj** [luin/ioredis#809]
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
 ReplyError: ERR max number of clients reached

**Comment by luin** [comment]
Refer to `maxclients` option in redis.conf for details.

**Comment by ile** [comment]
I'm getting a ton of these errors, even though the `INFO` or `CLIENT LIST` shows only 8 clients. Wonder why?

**Comment by keshav-gaur** [comment]
@ile How did you solve this?
