### ISSUE TITLE
[ioredis] Unhandled error event:Error:read ECONNRESET

### ISSUE THREAD

**Issue by leafmen** [luin/ioredis#810]
[ioredis] Unhandled error event:Error:read ECONNRESET
at _errnoException (util.js:1024:11)
at TCP.onread(net.js:615:25)

  let cfg = {
        port: 6379, // Redis port
        host: '127.0.0.1', // Redis host
        family: 4, // 4 (IPv4) or 6 (IPv6)
        db: 0, // Database index to use.
        connectTimeout: 100000, //100秒
        retryStrategy: function(times) {
            if (times < 3) {
                return 200;
            }
            var delay = Math.min(times * 20, 2000);
            return delay;
        }
    }

    let redis = new Redis(cfg);
    redis.get('a1').then(function(result) {
            res.send({
                data: JSON.parse(result),
                status: 1,
                message: msgtip.MSG_CODE_0000
            });
            res.end();
    });

**Comment by luin** [comment]
It seems to be a network problem which is not related with ioredis. Try if telent works.
