### ISSUE TITLE
proposal: split commands for cluster mode

### ISSUE THREAD

**Issue by Eywek** [luin/ioredis#811]
Hello,

At my job, we want to use Redis Cluster in our production environment (for scaling purpose) but we've hit some limitations with ioredis. Indeed, we're using `multi` and `mget` commands with multiple keys (not in the same slot ofc), so we're wondering if ioredis can't do some command splitting (like https://github.com/eleme/corvus#commands for example) to send the right command to the right node.

We're not using `corvus` to avoid deploying a new service and because it don't support streams commands or pubsub.

Thanks

**Comment by luin** [comment]
I'm wondering why do you use `multi` in the cluster setup when the commands inside it belong to different slots? ioredis will distribute commands to the correct node as long as pipeline & multi are not used.

**Comment by Eywek** [comment]
We were using `multi` before the requirement of using Redis Cluster, and sometimes we send a large amount of commands to the redis instance so multi is useful.

So, if I use a command like `zadd` with multiple keys (not in the same slot), ioredis will distribute commands to the correct node for each key?

**Comment by luin** [comment]
@Eywek Aha, I got the point. Indeed the commands with keys belonging to different slots will not work (e.g. `mget`) with `Redis.Cluster`. We may have another class for that feature to avoid breaking backward compatibility.

**Comment by cocobiz** [comment]
@luin Hi master, what's the road map about this feature? has any schedules?

**Comment by luin** [comment]
@cocobiz Pull request is welcome currently.

**Comment by dineshS-dentsu** [comment]
How to overide RedisCache if it fails to connect to the server ?
