### ISSUE TITLE
Error: Ready check failed: NOAUTH Authentication required.

### ISSUE THREAD

**Issue by joshhopkins** [luin/ioredis#812]
It appears that any password of a decent length causes connection issues. No problem using the `auth` command within `redis-cli` so assuming it's a bug with this library.

```bash
# redis.config
requirepass f9e0fwpoefpowef0e0fefwleek9ewl
```

```js
new Redis({
    port: 6379,
    host: '127.0.0.1',
    password: 'f9e0fwpoefpowef0e0fefwleek9ewl',
})
```

At times the connection is made initially, but for the most part throws the following error:

```js 
Error: Ready check failed: NOAUTH Authentication required.
```

**Comment by luin** [comment]
Did you connect to the correct node? You can enable the debug mode (`DEBUG=ioredis:* node yourapp.js`) for detail logs. I tested on my side with Redis v5 and things worked correctly:

```javascript
const Redis = require('ioredis')

const redis = new Redis({
  port: 5555,
  password: 'f9e0fwpoefpowef0e0fefwleek9ewl'
})

redis.get('foo', console.log)

```

**Comment by joshhopkins** [comment]
Thanks for the quick response. Revisiting the logs and it turns out that another service was trying to connect and empty an offline queue, while being pointed to the wrong env variables. If the correct password was more complex and took a little longer to authorise, it was just enough time for the other client to attempt to connect and throw the error (I guess). My bad!
