### ISSUE TITLE
Add support for bigint

### ISSUE THREAD

**Issue by lenovouser** [luin/ioredis#813]
I saw that `stringNumbers` was added as a workaround for numbers that are bigger than `Number.MAX_SAFE_INTEGER` in #282. Node supports [BigInt's](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt) since [`v10.4.0`](https://nodejs.org/en/blog/release/v10.4.0) I think. It'd be nice if there was an option like `stringNumbers` for BigInt's

**Comment by luin** [comment]
A pull request will be welcome.

**Comment by tuananh** [comment]
i suppose one must submit a PR to `node-redis-parser` first ?

**Comment by lenovouser** [comment]
@tuananh I don't know, does `ioredis` use `node-redis-parser` under the hood?
