### ISSUE TITLE
flexbuffer unmaintained / license not declared in package.json

### ISSUE THREAD

**Issue by dantman** [luin/ioredis#815]
ioredis depends on the `flexbuffer` package. Which is missing a `license` declaration in the package.json resulting in it being flagged in license validators.

I see in the past (#349) @luin got them to fix the missing LICENSE file. However I'm not sure it will work out this time since someone else already reported this (mercadolibre/flexbuffer-node#5) 5 months ago and there has been no response.

**Comment by gabegorelick** [comment]
License issue is fixed by https://github.com/luin/ioredis/pull/821. 

Also, see discussion in #824 about removing flexbuffer entirely.
