### ISSUE TITLE
Cluster constructor ignores config and keeps connecting on localhost:6379

### ISSUE THREAD

**Issue by igorlimansky** [luin/ioredis#819]
```
const redisClient = new redis.Cluster([{
  host: '127.0.0.1',
  port: parseInt(6389, 10),
}, {
  host: '127.0.0.1',
  port: parseInt(6390, 10),
}, {
  host:  '127.0.0.1',
  port: parseInt(6391, 10),
},
]);
```

gives `Error Error: Redis connection to localhost:6379 failed - connect ECONNREFUSED 127.0.0.1:6379`

**Comment by luin** [comment]
Could you enable the debug mode (DEBUG:ioredis:* node yourapp) and post the logs here?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by igorlimansky** [comment]
sorry, I resolved it, my sub-dependency was trying to connect to redis as well, didnt notice it
