### ISSUE TITLE
Silent error when redis server has cluster support disabled

### ISSUE THREAD

**Issue by Volune** [luin/ioredis#82]
With ioredis@1.5.5

When I try to connect to a (misconfigured) redis server with cluster support disabled, using `new Redis.Cluster(redisNodes)`: the client keeps retrying to connect, without informing the user that the server is misconfigured.

The server error was `ERR This instance has cluster support disabled`. Sending an error would allow to fallback on a non-cluster redis client.

**Comment by luin** [comment]
makes sense

**Comment by luin** [comment]
Added in 1.5.6
