### ISSUE TITLE
unlink

### ISSUE THREAD

**Issue by liuxg** [luin/ioredis#822]
I use redis.unlink('abc') in redis 5.0 get ReplyError: ERR unknown command 'unlink'.
Does ioredis don't support unlink?

**Comment by maheshsetti** [comment]
Did you find how `redis.unlink()`  works? I'm also getting the same error.

**Comment by luin** [comment]
This error indicates the Redis server doesn't support unlink command.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by maheshsetti** [comment]
Yes, I'm having `Redis server v=3.0.504` on windows. So its available above v4

**Comment by liuxg** [comment]
you redis version need to be 4 or above




At 2019-07-15 20:57:22, "Mahesh setti" <notifications@github.com> wrote:


Did you find how redis.unlink() works? I'm also getting the same error.
