### ISSUE TITLE
npm: last published version is v4.6.2

### ISSUE THREAD

**Issue by dnalborczyk** [luin/ioredis#823]
not sure if it's done on purpose or a flaw with publishing to npm.

latest available version as of today on npm is **v4.6.2**, latest github release is **v4.9.1**

**Comment by luin** [comment]
Every release on GitHub will be published to npm at the same time under the `next` tag, which can be installed with `npm install ioredis@next`. We merge the `next` tag to `latest` tag (which is now v4.6.2) monthly.

**Comment by luin** [comment]
Just merged 😄
