### ISSUE TITLE
4.9.1 requires git to install

### ISSUE THREAD

**Issue by oznu** [luin/ioredis#824]
Hello,

Commit 93ecd70e0e454541bd4934f9b09f746b3ad7c151 in release 4.9.1 adds `git` as a system dependency to successfully install the package.

Without git installed users can expect this error:

```
npm ERR! code ENOGIT
npm ERR! Error while executing:
npm ERR! undefined ls-remote -h -t ssh://git@github.com/mercadolibre/flexbuffer-node.git
npm ERR! 
npm ERR! undefined
npm ERR! No git binary found in $PATH
npm ERR! 
npm ERR! Failed using git.
npm ERR! Please check if you have git installed and in your PATH.
```

This might break existing automated builds, in my case it was a Docker image that previously had no need for git to be installed.

**Comment by luin** [comment]
Good caught! Just downgrade latest tag to 4.9.0. Will move the dependencies to npm in the next version.

**Comment by kerihenare** [comment]
This is solved in #826. However, I'm also looking at [refactoring out **flexbuffer** entirely](https://github.com/luin/ioredis/compare/master...kerihenare:buffer-refactor?expand=1). It's a real small package, and **ioredis** only uses an even smaller portion of it.

**Comment by gabegorelick** [comment]
A better approach may be to refactor usages of flexbuffer to use Buffer and related JS builtins directly. Especially if it's not used much. 

For example, https://github.com/luin/ioredis/blob/7736c1cf27af1cb991b95f592a5fbe89646facf6/lib/pipeline.ts#L306 appears to [copy an entire Buffer](https://github.com/mercadolibre/flexbuffer-node/blob/1487df393a30872e3e81b246711a4cf6b0b23314/flexbuffer.js#L63) just to write it back out.  It may be possible to make stuff like this zero-copy by switching to using Buffers and/or TypedArrays directly (please correct me if I'm misunderstanding the code).

**Comment by dantman** [comment]
If `arg` is large it may also be more efficient to convert the smaller strings to Buffers, push things onto an array instead of writing them to a flexbuffer, and use Buffer.concat to convert it to a single buffer all at once instead of repeatedly allocating slightly bigger buffers. If you want to super-optimize that, `"\r\n"` and `"$"` could be static buffers that are only allocated once and then shared in all usages (since you won't modify the buffers when making an array of them).

**Comment by dantman** [comment]
Still an important issue. Should not be closed until https://github.com/luin/ioredis/blob/master/package.json#L34 is changed.

**Comment by luin** [comment]
This issue has already been solved with https://github.com/luin/ioredis/releases/tag/v4.9.2. Forgot to close this.
