### ISSUE TITLE
showFriendlyErrorStack affect on performance

### ISSUE THREAD

**Issue by ashkank83** [luin/ioredis#829]
Is it possible that switching on showFriendlyErrorStack affects the performance? I can't say it for sure but it feels like when the showFriendlyErrorStack is set to true the processing spped is reduced. Is this a known behaviour? 
ioredis 4.6.2

**Comment by luin** [comment]
@ashkank83 That's right. Check out the last paragraph here: https://github.com/luin/ioredis#error-handling.

`showFriendlyErrorStack` will catch the calling stack when invoking commands, so it has a little impact on performance. The impact is pretty similar to putting a `new Error()` (without throwing it) before every redis command.

**Comment by ashkank83** [comment]
@luin Thank you very much! and sorry it looks like I missed the last sentence in the paragraph. indeed my answer is already there.

**Comment by jekh** [comment]
@luin - do you know of any benchmarks on the performance impact of `showFriendlyErrorStack`? I'd be curious to see if the impact of the `new Error()` (or equivalent) was significant--especially when compared to the time it takes to round-trip something on the wire to redis.

For some applications, the performance impact in production might be worth it if it makes finding and fixing errors much easier. Some data would help me (and probably others) determine whether it's worth the trade-off.
