### ISSUE TITLE
asCallback errors

### ISSUE THREAD

**Issue by tony-gutierrez** [luin/ioredis#830]
I migrated to 4.9.1 from 4.6.2 and am getting a lot of errors revolving around "asCallback"?

standard_as_callback_1.default is not a function

asCallback is not a function

options: 
```
host: 'xxx.redis.cache.windows.net',
		port: 6380,
		password: 'txxxxxxxxxxxxxxxx=',
		keepAlive: 1000,
		tls: true
```

It is not immediately clear if tls:true is still supported, or what object would replace it (```tls:{}```)

**Comment by luin** [comment]
This error is caused by a mismatched version between asCallback & ioredis. Try installing ioredis again to solve the problem. BTW, it's recommended to use v4.9.0.

**Comment by tony-gutierrez** [comment]
Sorry, I was on 4.9.0. Attempting to remove those two modules and force reinstall.
