### ISSUE TITLE
Why is the performance of ioredis client for redis sharded cluster is slow?

### ISSUE THREAD

**Issue by manojdevs** [luin/ioredis#835]
the latency of reads and writes to redis sharded cluster is very high than expected and it is not consistent, when i try to connect to the redis sharded cluster using a nodejs redis library called "ioredis". for example when i try to read and write about 100 key value pairs it takes about ~10-15 seconds.

i have set up a 6 node redis sharded cluster (3 master & 3 slaves) which is set up in cloud (SCALEWAY CLOUD).when i try to read and write via redis-cli it's quite fast. i observe inconsistency only via node library ioredis

`var ioredis = require('ioredis');
var redisCluster =new ioredis.Cluster([
          {
            host:"redis-server-1",
            port:6379
          },
          {
            host:"redis-server-2",
            port:6379
          },
          {
            host:"redis-server-3",
            port:6379
          },
          {
            host:"redis-server-4",
            port:6379
          },
          {
          host:"redis-server-5",
          port:6379
        },
        {
          host:"redis-server-6",
          port:6379
          }
        ]);

var startDate = new Date();
var total = 0;
//var total2 = 0;
for(var i = 0;i<10000;i++){
redisCluster.set("fookar"+i,"barkar"+i,function(err,res){
if(err){
console.log(err);
}
else{
var endDate   = new Date();
var seconds = (endDate.getTime() - startDate.getTime()) / 1000;
total = total+seconds;
startDate = endDate;
console.log(total+"set");
}
});
}

for(var i = 0;i<10000;i++){
redisCluster.get("fookar"+i,function(err,res){
if(err){
console.log(err);
}
else{
var endDate2   = new Date();
var seconds = (endDate2.getTime() - startDate.getTime()) / 1000;
total = total+seconds;
startDate = endDate2;
console.log(total+"get");
}
});
}`

i expect the latency to be in milliseconds as it can process millions of transaction in a second. Is this the normal behavior, since there will be redirects to the server where key is to be read or written or is there something i have to tune?

**Comment by klinquist** [comment]
You can't put asynchronous code inside of a for loop (which is synchronous) and expect valid results.

**Comment by manojdevs** [comment]
No, This is just an example just to benchmark results. Even when performing single operation on redis sharded cluster with ioredis is taking more than a few seconds than estimated.
