### ISSUE TITLE
AWS ElasticCache/TLS (No cluster) - Connecting but not reading/writing

### ISSUE THREAD

**Issue by klinquist** [luin/ioredis#836]
I can connect to the redis cluster with ioredis via stunnel/localhost, so there shouldn't be any security group issues..

Not running in cluster mode, just a master and two replicas.

My code:
```
var Redis = require('ioredis');
var redis = new Redis({
  port: 6379,
  host: 'master.master-redis.xxxxx.usw2.cache.amazonaws.com',
  redisOptions: {
    tls: {}
  }
});

redis.set('aws', 'kris');
redis.get('aws', (err, res) => {

  if (err) console.log(err);
  if (res) console.log(res);
  redis.disconnect();
});
```

DEBUG:
```
$ DEBUG=ioredis:* node redisTest.js
  ioredis:redis status[master.master-redis.xxxxx.usw2.cache.amazonaws.com:6379]: [empty] -> connecting +0ms
  ioredis:redis status[172.31.45.162:6379]: connecting -> connect +333ms
  ioredis:redis write command[172.31.45.162:6379]: 0 -> info([]) +1ms
  ioredis:redis queue command[172.31.45.162:6379]: 0 -> set([ 'aws', 'kris' ]) +5s
  ioredis:redis queue command[172.31.45.162:6379]: 0 -> get([ 'aws' ]) +2ms
```

(it just sits there)

Any ideas?
Thanks!

**Comment by wong2** [comment]
the problem here is that javascript is async, when the code runs to `redis.get`, there is a chance that the previous `redis.set` hasn't completed, and you'll get `null` as `res`, to the code will log nothing and disconnect redis connection.

**Comment by klinquist** [comment]
There isn't any previous redis.set. I am aware of async, I get the same issue if I put the calls inside an async.waterfall to make sure the previous operation completes.

**Comment by wong2** [comment]
alright, then maybe you should update your code sample, it's a little misleading now
