### ISSUE TITLE
Sentinel: Fallback to slave when no master is available

### ISSUE THREAD

**Issue by silverwind** [luin/ioredis#840]
The `role` option currently accepts `slave` and (presumably) `master` options. I'm thinking of a third option to allow fallback from `master` to `slave` mode (maybe call it `master-slave`) if no master is available. Example scenario:

- redis and sentinel are up and we're connected to the master
- network partition happens and we're left with only slaves and a sentinel reachable
- now, ioredis could switch to a slave while periodically checking the availabilty of the master
- once master is reachable again, switch back to master mode

The same logic could also be used if a user prefers a slave with a fallback to a master (role `slave-master`).

**Comment by luin** [comment]
@silverwind Sorry I missed the issue. Sounds good to me, let's track this in #1458.
