### ISSUE TITLE
`pattern` is not a Buffer in `on('pmessageBuffer', (pattern, channel, message) => undefined)`

### ISSUE THREAD

**Issue by gkubisa** [luin/ioredis#842]
I would expect that the `pattern` argument passed into the listener registered with `redis.on('pmessageBuffer', (pattern, channel, message) => console.log)` would be a Buffer, however, it is a string.

Here's how to reproduce it:

```
const Redis = require('ioredis');
let redis = new Redis();
redis.psubscribeBuffer(Buffer.from('channel*'));
redis.on('pmessageBuffer', console.log);
```

Then publish some messages (I used redis-cli):

```
PUBLISH channel Hello
PUBLISH channel123 Hello
```

The results printed to the console of the JS app are:

```
channel* <Buffer 63 68 61 6e 6e 65 6c> <Buffer 48 65 6c 6c 6f>
channel* <Buffer 63 68 61 6e 6e 65 6c 31 32 33> <Buffer 48 65 6c 6c 6f>
```

I would expect the `"channel*"` strings to be Buffers too.

**Comment by luin** [comment]
It makes sense in some aspect. However, I'd like to know what's the use case for requiring patterns to be returned as buffers, since the patterns are typically utf-8 strings.

**Comment by gkubisa** [comment]
Without going into too much detail, I have some binary IDs in my application which I include in key and channel names. Thanks to ioredis supporting Buffers, I can avoid converting them to strings and make my app a bit more efficient. Besides, Buffer patterns and channels are supported by ioredis, so apparently there have been already some use cases where they were required...

I'm not really suggesting any new functionality or changes required for a specific use case but rather pointing out an inconsistency in the API. In my opinion, passing patterns as Buffers to the 'pmessageBuffer' event listeners would make the API more consistent, as the channels and data are also Buffers and the event name is pmessage**Buffer**. Obviously, the `pmessage` event should still report patterns as strings.

**Comment by jedwards1211** [comment]
@luin what's the use case for the channel to be returned as a buffer though?  I'm used to channels being strings as well.
At first I was just looking at the pattern.  Only later did I start using the channel argument, and since the pattern was a string, I expected the channel to be a string...

**Comment by jedwards1211** [comment]
@luin I guess I wouldn't have run into this if I were using TypeScript, but I'm using Flow and even the flow-typed defs got this wrong:
```js
export type PMessageBufferListener = (
  pattern: string,
  channel: string,
  message: Buffer
) => mixed
```
So the fact that `channel` is a buffer is probably too surprising, and very easy to miss in the README.

**Comment by NickKelly1** [comment]
I'd like to use binary channel names and binary pattern names because I have an application with thousands of pubsub messages per second where id's are cryptographic hashes.

Redis works perfectly fine with binary channel names and binary patterns, for example I can subscribe to any messages to channels prefixed with 0x01 by passing pattern 0x012a (2a being ascii of *). However ioredis doesn't support it them as it converts and returns all received patterns to utf8 which means I can't reliably match psubscribe messages to their listeners as bytes may be lost in conversion. Returning the pattern as the original buffer, without stringifying to utf8, would fix this.
