### ISSUE TITLE
ERR unknown command 'auth'

### ISSUE THREAD

**Issue by pk111and222** [luin/ioredis#843]
你好，当我使用ioredis作redis-sentinel的作用时，我遇到了如下问题
![image](https://user-images.githubusercontent.com/12478570/56293842-7cc9db80-615c-11e9-906c-acf43b237438.png)

我是这样使用他的配置的
{
    name: 'mymaster',
    sentinels: [{
      host: '***',
      port: 26379,
    }],
    keyPrefix: '**',
    db: 5,
    sentinelPassword: '***',
 }
我的express代码如下
![image](https://user-images.githubusercontent.com/12478570/56293781-5a37c280-615c-11e9-9828-459ccf64c61c.png)

我的node版本是8.15，ioredis版本是4.9.0

**Comment by pk111and222** [comment]
Print the log as follows
![image](https://user-images.githubusercontent.com/12478570/56347222-6cfed580-61f6-11e9-9047-67497f519cb9.png)
the same config, My java partner has been docked, so I don't think there is a problem with the config of the sentinel.

**Comment by luin** [comment]
错误就是 ETIMEDOUT，可以排查一下网络连通问题。
