### ISSUE TITLE
Subscriptions lost after reconnection

### ISSUE THREAD

**Issue by tzanko-matev** [luin/ioredis#85]
Steps to reproduce:
1. Start Redis
2. Start a ioredis client with no options given and subscribe to a channel. When we run 'PUBSUB CHANNEL' in redis-cli, the subscription should show
3. Kill the redis process and start it again. Now 'PUBSUB CHANNEL' shows nothing.

After I looked a little bit at the code it seemed that when the client reconnects it checks the property prevCondition.subscriber to see if the client was in subscribe mode and to renew all subscriptions. However the value of this property is 'false', so the subscriptions are not renewed.

**Comment by luin** [comment]
This issue happens when reconnecting failed more than one times. Fixed in the master branch. Thanks for reporting.

**Comment by tzanko-matev** [comment]
Thank you for the quick reaction.
