### ISSUE TITLE
想问下redis.info() 这个api不存在么

### ISSUE THREAD

**Issue by MaxBill** [luin/ioredis#853]
我想获取redis服务的服务信息，像jedis之类的都是redis.info()这样获取，麻烦问下ioredis怎么使用的，在api中没有找到

**Comment by manasa-ei** [comment]
If you are looking for the command as redis-cli info
Below is the way to call and get the output.
Below is the translated by google to chinese.
如果您正在寻找redis-cli info 命令

下面是调用和获取输出的方法。
var Redis = require('ioredis');
var client = new Redis();
client.info((err, res)=> {
  console.log('-----------err is:', err, '\n ---------res is:', res)
})

**Comment by MaxBill** [comment]
@manasa-ei 感谢大佬，是我调用方式不对，我是console.log(redis.info());这样用的，谢谢

**Comment by manasa-ei** [comment]
> 感谢大佬，是我调用方式不对，我是console.log(redis.info());这样用的，谢谢

Glad to listen that. Thanks for your quick verification and response. You can close the issue if you got the solution.
Translated to chinese using googje translator:
很高兴听到这个。感谢您的快速验证和回复。如果您有解决方案，可以关闭该问题
