### ISSUE TITLE
请教下，怎么同步调用

### ISSUE THREAD

**Issue by MaxBill** [luin/ioredis#857]
ioredis的都是异步调用的，我有个需求是：把一个key对应的的ttl、type、值这些数据都查到封装到一个对象中使用，但是这几个方法都是异步执行的，想请教下怎么同步使用

**Comment by luin** [comment]
这个和 ioredis 关系不大，可以参考常见的异步编程范式。建议到问答社区提问，感谢理解。

参考形式：

```javascript
const [ttl, type] = await Promise.all([redis.ttl(xxx), redis.type(xxx)])
return { ttl, type }
```
