### ISSUE TITLE
redis cluster node command shows incorrect value

### ISSUE THREAD

**Issue by capathida** [luin/ioredis#861]
I tried to use the
db = new Redis.Cluster()
db.nodes('slave');  command for cluster, get a list of cluster nodes and their values, but in the response I received seems to say role: 'master', on all and the process_id: '6', seems to be the same.

Is it an error or is it an expected result that  I missunderstood?

**Comment by manasa-ei** [comment]
Can you please highlight an example I tried the below but seems to be not working and getting no response:
var Redis = require('ioredis');

var client = new Redis.Cluster([{
          port: 6380,
          host: '127.0.0.1'
        }, {
          port: 6381,
          host: '127.0.0.1'
        }, {
          port: 6382,
          host: '127.0.0.1'
        }, {
          port: 6383,
          host: '127.0.0.1'
        }, {
          port: 6384,
          host: '127.0.0.1'
        }, {
          port: 6385,
          host: '127.0.0.1'
        }], {
          maxRedirections: 1
        });
console.log(client.nodes('slave'));

Please help me with a proper example @capathida

**Comment by capathida** [comment]
Well, how is your cluster setup?
I assume you do something like: 
var client = new Redis.Cluster([{
port: 6380, 
host: '127.0.0.1'
}, {... 
}
client.on('connect', function() {
    console.log(client.nodes('slave')); **// since the cluster connect is not done directly after the new cluster command right....**
});

**Comment by manasa-ei** [comment]
@capathida I believe the result what you are getting is correct though it says role as master but its readonly is true which means as of now this node is working as a replica.
I have printed below information for better understanding:
client.on('connect', function() {
const slaves = client.nodes('slave');
slaves.forEach(slave => {
  console.log(`Redis Replica Node is:
  readOnly: ${slave.options.readOnly}
  port: ${slave.options.port}
  host: ${slave.options.host}
  role: ${slave.options.role}`);
})
  const masters = client.nodes('master');
  masters.forEach(master => {
  console.log(`Redis Master Node is:
  readOnly: ${master.options.readOnly}
  port: ${master.options.port}
  host: ${master.options.host}
  role: ${master.options.role}`)
})
});

O/P is:
Redis Replica Node is:
  readOnly: true
  port: 6383
  host: 127.0.0.1
  role: master
Redis Replica Node is:
  readOnly: true
  port: 6385
  host: 127.0.0.1
  role: master
Redis Replica Node is:
  readOnly: true
  port: 6384
  host: 127.0.0.1
  role: master
Redis Master Node is:
  readOnly: false
  port: 6380
  host: 127.0.0.1
  role: master
Redis Master Node is:
  readOnly: false
  port: 6381
  host: 127.0.0.1
  role: master
Redis Master Node is:
  readOnly: false
  port: 6382
  host: 127.0.0.1
  role: master

You should rely on readOnly flag to decide whether it is master/replica(i.e slave).

This perfectly matches with the configuration that I setup with the cluster.
To verify you can use cluster nodes with redis-cli also.
