### ISSUE TITLE
请教ioredis关于scan的用法

### ISSUE THREAD

**Issue by MaxBill** [luin/ioredis#863]
我使用redis.scan(cursor) 是可以的，如果我要同时使用pattern和count呢，我尝试了：

redis.scan(cursor, {match: match, count: count}).then(data => {
        console.log(data);
});

redis.scan(cursor, match,  count}).then(data => {
        console.log(data);
});

都报错了，在例子中没找到怎么使用，请教下这个api的正确用法

**Comment by luin** [comment]
和其他命令一样，没有什么特殊的。

```javascript
redis.scan(cursor, 'MATCH', match, 'COUNT', count)
```
