### ISSUE TITLE
blpop first then rpush - deadlocks

### ISSUE THREAD

**Issue by koushikg** [luin/ioredis#864]
1) start BLPOP first
const Redis = require('ioredis');
const redis = new Redis();
const key1 = `k1-${Math.random()}`;
redis.blpop(key1, '600').then(v => console.log('value', v));

2) then do RPUSH for the same key
redis.rpush(key1, '1321').then(v => console.log('rpush success'));

Expectation:
BLPOP should wait for 600 seconds on the key, and when RPUSH sets the value, BLPOP should get unblocked.
This happens if I use redis-cli or nginx redis2.

Whats happening:
The RPUSH call is getting stuck, causing a deadlock. Most likely the ioredis or redis library holding the event thread somewhere!!

**Comment by manasa-ei** [comment]
I don't think so. I tried the below way and worked for me:

I executed the below program:
const Redis = require('ioredis');
const redis = new Redis();
const key1 = `k1-${Math.random()}`;
console.log('key is:', key1);
redis.blpop(key1, '600').then(v => console.log('value', v));

With the above program got the output as :
key is: k1-0.0035760068798507127
I took the consoled key and did rpush using redis-cli as below:
RPUSH k1-0.0035760068798507127 001

Immediately got out put in blpop as below:
value [ 'k1-0.0035760068798507127', '001' ]
![Screenshot 2019-05-13 at 11 53 14 AM](https://user-images.githubusercontent.com/42749655/57599872-c0561080-7575-11e9-80bb-bd0602afb632.png)
![Screenshot 2019-05-13 at 11 53 22 AM](https://user-images.githubusercontent.com/42749655/57599873-c0eea700-7575-11e9-893a-c298c4441d0f.png)

The same wont work if you try to do rpush from the same program as below:
const Redis = require('ioredis');
const redis = new Redis();
const key1 = `k1-${Math.random()}`;
console.log('key is:', key1);
redis.blpop(key1, '600').then(v => console.log('value', v));
redis.rpush(key1, '1321').then(v => console.log('rpush success'));

You need to use separate process to do rpush then only process waiting for blpop will get the key.

**Comment by koushikg** [comment]
Thanks for responding!

Yes, I realized that too! Looks like connection multiplexing is unavailable on BLPOP.

For now, I'm going to create a new connection for each requests - inefficient but will get the job done. Then will see connection pooling option!

Though would be good if we can provide connection multiplexing with BLPOP or any other blocking operation.

**Comment by manasa-ei** [comment]
@koushikg You can close this issue, if you are satisfied with the response and can proceed.

**Comment by koushikg** [comment]
@manasa-ei the problem is true - but most likely requires a broder change by redis! So will close this ticket for ioredis.
