### ISSUE TITLE
ioredis没有连接池但是为什么会同时发送多个命令

### ISSUE THREAD

**Issue by GeniusBrother** [luin/ioredis#865]
本人小白一枚，刚学习redis，可能有哪里有知识盲区，请大家勿见怪，发现了个自认为很奇怪的事情

Redis本身是基于Request/Response协议的，正常情况下，客户端发送一个命令，等待Redis应答，Redis在接收到命令，处理后应答。在这种情况下，如果同时需要执行大量的命令，那就是等待上一条命令应答后再执行

连接远程的redis，然后同步的发送了三个ping命令，打印收到响应的时间差，发现几乎一样，按道理讲一个连接一次只能发送一个命令，为什么ioredis是几乎同时发送全部的命令
let client = new Redis({host: "114.115.234.148", port: 6379, password: "xxxx"});
client.once("error", function (err) {
    console.log(err);
});

client.once("ready", function () {
    console.log("ready");
    let time = Date.now();
    console.log(time);
    client.ping((value) => {
        console.log(Date.now() - time);
    });
    client.ping((value) => {
        console.log(Date.now() - time);
    });
    client.ping((value) => {
        console.log(Date.now() - time);
    });
})

打印结果:
ready
1557753845699
46
46
46

**Comment by luin** [comment]
Please refer to https://redis.io/topics/pipelining for details.

请查看 https://redis.io/topics/pipelining。类似的问题可以发邮件给我，尽量不发到 issue 讨论区，因为有其他代码贡献者也会收到邮件来查看，会打扰到他们。非常感谢理解！
