### ISSUE TITLE
Improve TypeScript support

### ISSUE THREAD

**Issue by ORESoftware** [luin/ioredis#868]
It would be nice to write the lib in TypeScript? I am using:

```
"@types/ioredis": "^4.0.10",
```

 I am looking for TS support for example:

<kbd>
<img width="361" alt="Screen Shot 2019-05-14 at 11 54 01 AM" src="https://user-images.githubusercontent.com/11139560/57724191-104cda00-763f-11e9-8ffa-226693e7e976.png">
</kbd>

not sure how to fix

**Comment by luin** [comment]
This library has been being migrated to TypeScript for a while, but there're still much work remains to be done. Pull requests are welcome :-)

For now, we could contribute to the @types/ioredis library to fix issues.

**Comment by fangedhex** [comment]
It seems that you don't set the compiler option "declaration" to true in your tsconfig.json, it will output definition file (.d.ts). It doesn't look like you publish your ts files on NPM registry so we don't have typescript definition. Maybe I am wrong but I prefer to point this out from what I'm understanding about Typescript compiler options.

**Comment by luin** [comment]
@fangedhex Yes, you're right about the `declaration` option. For now, the declarations are not exported and published to npm is because we've not migrated all the code to TypeScript, especially the `Redis` class. So it would be better to use @types/ioredis until all the code are migrated.

**Comment by JakeCB** [comment]
Unless I'm mistaken the Typescript conversion was recently completed, correct? If it's just a config change, it would be nice to not have to use DefinitelyTyped.
