### ISSUE TITLE
No client.end() or client.close() method

### ISSUE THREAD

**Issue by ORESoftware** [luin/ioredis#869]
I have 

```typescript

import Redis = require('ioredis')
const client = new Redis('redis://ec2-xx-xx-xx-223.us-west-1.compute.amazonaws.com:6379/1');
```

but there is no client.end() or client.close() method (at least according to the typescript typings):

<kbd>
<img width="195" alt="Screen Shot 2019-05-14 at 2 00 23 PM" src="https://user-images.githubusercontent.com/11139560/57731944-bd7c1e00-7650-11e9-8478-b79d8ef51dff.png">
</kbd>

**Comment by luin** [comment]
The typings are correct. There're `client.disconnect()` (end the socket directly) & `client.quit()` (quit the connection gracefully).

**Comment by ORESoftware** [comment]
ok thanks
