### ISSUE TITLE
Support URL/URI option in options

### ISSUE THREAD

**Issue by ajmas** [luin/ioredis#871]
Per the documentation, we can create a new Redis instance via:
```
// Connect to 127.0.0.1:6380, db 4, using password "authpassword":
new Redis('redis://:authpassword@127.0.0.1:6380/4')
```
At the same time there does not appear to be an equivalent solution of passing a URL if we provide options.

Am I missing this option? If not, could this be added in a future version?

Rereading the [docs](https://github.com/luin/ioredis/blob/master/API.md#new_Redis), I see we can do:

```
new Redis(url, options)
```

though it would still be good to allow the url to be specified in the options, so we can directly copy a configuration into the constructor.

Using ioredis 4.9.3.

**Comment by luin** [comment]
I'm curious about the use case why you need to specify the `url` in the options?

**Comment by ajmas** [comment]
It would be for consistency at the very least, since currently both port and host are both available in the argument and the options. It would also allow to have a configuration of the form:

```
var config = {
  url: 'redis://...',
  keyPrefix: 'prefix-',
  lazyConnect: false
}

new Redis(config)
```

**Comment by luin** [comment]
Hi @ajmas, Thanks for the response . This usage may lead to ambiguity I'm afraid, so it will not be added in this time. For example:

```javascript
var config = {
  url: 'redis://xxx:6666',
  port: 7777
}
```

It hard to tell what the port is, 6666 or 7777.

**Comment by ajmas** [comment]
Then again a rule of priority could be defined. At the same time  wouldn’t this be ambiguous too:

```
new Redis(port, host, {
  port: 1234,
  host: ‘...’
})
```

**Comment by luin** [comment]
Yes, that may be. Currently the options resolver follows the rule same as `Object.assign()`, so the latter one take precedence.
