### ISSUE TITLE
Modules DNS and NET needed when using with Vue

### ISSUE THREAD

**Issue by adnanchang** [luin/ioredis#872]
Hi,

So I am currently developing an application with an express/graphql/apollo backend with a vue/apollo frontend.

I have managed to start up the redis instance in the backend through ioredis. I am now trying to start an instance in Vue. but when I import it in the `main.js` file it tells me that I need to install a dependency `dns`. 

I did that but now I am getting this error in the browser console: 
```
defaultable sync:2 Uncaught Error: Cannot find module 'net'
    at webpackEmptyContext (defaultable sync:2)
    at Object.workaround_require (defaultable.js:49)
    at require (defaultable.js:77)
    at server.js:9
    at defaulter (defaultable.js:83)
    at defaultable (defaultable.js:63)
    at good (defaultable.js:174)
    at Object.<anonymous> (server.js:5)
    at Object../node_modules/hbo-dnsd/server.js (server.js:240)
    at __webpack_require__ (bootstrap:723)
```

I dont understand why are these needed only when trying to use ioredis with vue. Or am I using the wrong redis pack for vue

**Comment by luin** [comment]
ioredis only works on the backend side for a web application, so it should have nothing to do with which front-end framework are you using. I guess you may want to require ioredis on the express side.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by adnanchang** [comment]
okay, but how do I *listen* or *subscribe* a client (in my case a vuejs instance) to receive the updates published by a ioredis activated backend?

**Comment by luin** [comment]
It should be more complicated than finding another package. What you are looking for is a way to communicate between server and client, and it has nothing to do with ioredis & Redis. You could check out "websocket".

Closing this issue.
