### ISSUE TITLE
Update redis-commands version to 1.5.0

### ISSUE THREAD

**Issue by borsucok** [luin/ioredis#875]
Please update redis-commands version to 1.5.0, which correctly supports redis streams

**Comment by fas3r** [comment]
Hello @luin ,

could you update also npm ? Or it's on purpose ?

![image](https://user-images.githubusercontent.com/11342586/59140180-99370700-899a-11e9-9c2f-a680f58c43d0.png)


Thanks

**Comment by luin** [comment]
v4.10.0 has been released under latest tag.
