### ISSUE TITLE
"TypeError: Cannot read property 'command' of undefined" in 4.9.5!

### ISSUE THREAD

**Issue by Apollon77** [luin/ioredis#878]
Hi, 

I got this error  sometimes (not everytime!)

```
TypeError: Cannot read property 'command' of undefined
    at Redis.exports.returnReply (/Volumes/Dev/iobroker-redis/node_modules/iobroker.js-controller/node_modules/ioredis/built/redis/parser.js:116:42)
    at JavascriptRedisParser.returnReply (/Volumes/Dev/iobroker-redis/node_modules/iobroker.js-controller/node_modules/ioredis/built/redis/parser.js:23:19)
    at JavascriptRedisParser.execute (/Volumes/Dev/iobroker-redis/node_modules/iobroker.js-controller/node_modules/ioredis/node_modules/redis-parser/lib/parser.js:544:14)
    at Socket.<anonymous> (/Volumes/Dev/iobroker-redis/node_modules/iobroker.js-controller/node_modules/ioredis/built/redis/event_handler.js:107:26)
    at Socket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at Socket.Readable.push (_stream_readable.js:220:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

it sounds comparable to #862 but line numbers are different ones ... and in fact I get the error when using 4.9.5.

I tried to track it down but without any reall success so far

**Comment by luin** [comment]
@Apollon77 Thank you for pointing this out! I have to say it's a little difficult to find the reason for that issue without a reproducible example. Given that, a few questions may help the investigation:

1. What version of the Redis server?
2. Were the line numbers (`ioredis/built/redis/parser.js:116:42`) are same for all the exceptions you got?
3. What commands did the application use?

**Comment by Apollon77** [comment]
Hi @luin 

Ok, when you think it is not connected then it may be on my side, but it would be great to get some more insight in the expectations from code side in this case because it seems to expect that there is at least one item in that "commandQueue". Could you give me more infos?

Yes it is always the same line number, so I would have an assumption that the command is "psubscribe". But I can not nail it down because as soon as I add debug the problem do not happen anymore :-( 

To my setup and your other questions: It is no real redis ... it is a Javascript Redis "server". The project I work on we have since long time an InMem-DB with Socketio protocol and we wanted to replace that and additionally allowing using a real redis (so users can choose, but eg no Reids for Windows users).
I checked the redis protocol infos and real redis traffic and rebuild that ... maybe I did an error while doing this.
For me it more seems to be a timing issue somehow because while digging deeper I found that the case only sometimes happens when "server" and "client" are running in the same process.
I think I understood the code in the meantime and I'm checking my code about potential too many responses for one command ... Would assume this as the problem and already found one place ...

Thank you!

**Comment by charlesetiennepage** [comment]
Hi @luin 

Having the same issue here, using a managed Redislabs setup, Redis 5.0.4 with ioredis 4.10.4

It seems to happen only when Redis is under high load (+50k ops/sec), same callstack as @Apollon77 . 

Not quite sure what could cause this issue, but it can be reproduced consistently under load.

Thanks

**Comment by luin** [comment]
Hi @charlesetiennepage, are you able to reproduce this issue with a minimal example so I can test on my side?

**Comment by charlesetiennepage** [comment]
@luin Sadly no, I've tried reproducing it locally, but have been unable to, it seems to trigger randomly when a Redis shard hit 100% CPU.
