### ISSUE TITLE
geo commander 

### ISSUE THREAD

**Issue by alexosng** [luin/ioredis#886]
i use follow command is ok
redis.geoadd('beijing','116.610774', '39.920352', 'MER_ID')

but use this command is failed
const nearby = redis.georadius('beijing', '116.610774 ', '39.920352 ', '500','m' 'ASC')

i  don't know args is wrong or command is wrong ~~
i can't find example

**Comment by luin** [comment]
What error did you get? `redis.georadius` returns a Promise instead of the result, so that may be the reason. Please submit further questions on StackOverflow with [ioredis] tag.
