### ISSUE TITLE
Memory leak on high frequency data.

### ISSUE THREAD

**Issue by acostaf** [luin/ioredis#891]
Hi All

I am using oiredis to save some data in bulk, around 12k rows every second. the main issue that it happening is that node is not able to recover memory from the ioredis operation growing forever.

I am saving the data in two stages, first one I received several thousand messages that are stored in memory reaching upto 140 mb then once a second I grab part of that data and I pipeline it into redis where grows to 1gb within 4 hours until it crash the process due the memory limitations.

The easy fix it is to use "old --max-old-space-size" trick but everyone know that this does not fix the problem but the symptoms.

Node version 12.4.0
NPM 6.9.0
ioredis 4.9.0
Windows 10

Any idea or recommendation, what is better ? reuse/create new connection, use/avoid await/async ?

AA

**Comment by luin** [comment]
Hi, I suggest you run a heap profile in the production environment to see who holds the memory.

**Comment by acostaf** [comment]
Luin, do you normally use v8-profiler or another tool ?

**Comment by luin** [comment]
@acostaf I don't know whether v8-profiler is still compatible with the Node.js version you're using, but the built-in profiler (https://nodejs.org/en/docs/guides/simple-profiling/) should be enough.

**Comment by danielfroz** [comment]
I am facing same problem. Anyone else still going through this?

I did my implementation using setInterval() to query redis for new messages (xreadgroup()). Turns out that setInterval() is leaving memory for GC; something that you can't control directly... so leading to "memory leaks" ... problem is that memory allocated is not completely freed once GC runs... V8 expert may provide more details here (why?). In the long run ... with many instances running under same server, all memory is consumed...

I did some code changes, to minimize the effects and ended up with something like the following:
```
const xread = () => {
   .. // xreadgroup code... message handler...
}
const emitter = new EventEmitter()
emitter.on('fire', xread)
const interval = setInterval(() => emitter.emit('fire'), 1000)
redis.on('close', () => {
  clearInterval(interval)
  log.info('sub: close()... interval cleared')
})
```
Helped but still did not fix the issue... Eventually my processes are consuming 800MB of memory...  Any suggestions? Anyone running this in real production environment?

**Comment by danielfroz** [comment]
Nevermind to reply.... Removed ioredis from my code.

Nonetheless It's certain that ioredis has a serious memory leak issues. Would revisit DataHandler code ( created a fork of Tedis project with code which may help you to identify the issue and fix it... so suggest you guys look at it - maybe helps). BTW, I am sure it's ok to use ioredis to eventually send a command() SETs GETs, etc...  but would not use it for real production in the backend.

**Comment by Xairoo** [comment]
Have the same.

```
const Redis = require('ioredis');
const { v4: uuidv4 } = require('uuid');

const client = new Redis();

const userLimit = 10000;
const entryLimit = 200;

client.on('ready', function() {
	console.log('redis ready');

	var user = 0;
	var entry = 0;
	var user_uuid;
	while (user < userLimit) {
		user_uuid = uuidv4();

		entry = 0;
		while (entry < entryLimit) {
			client.hmset('something:' + user_uuid, uuidv4(), '');
			entry++;
		}

		user++;
	}

	process.exit();
});
```

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF7457CDD8A v8::internal::GCIdleTimeHandler::GCIdleTimeHandler+4506
 2: 00007FF7457A8886 node::MakeCallback+4534
 3: 00007FF7457A9200 node_module_register+2032
 4: 00007FF745AC30DE v8::internal::FatalProcessOutOfMemory+846
 5: 00007FF745AC300F v8::internal::FatalProcessOutOfMemory+639
 6: 00007FF745CA9804 v8::internal::Heap::MaxHeapGrowingFactor+9620
 7: 00007FF745CA07E6 v8::internal::ScavengeJob::operator=+24550
 8: 00007FF745C9EE3C v8::internal::ScavengeJob::operator=+17980
 9: 00007FF745CA7B87 v8::internal::Heap::MaxHeapGrowingFactor+2327
10: 00007FF745CA7C06 v8::internal::Heap::MaxHeapGrowingFactor+2454
11: 00007FF745DD1EA7 v8::internal::Factory::NewFillerObject+55
12: 00007FF745E4F096 v8::internal::operator<<+73494
13: 000000FEAF9DC5C1

**Comment by wzjjack** [comment]
Likely I have the same issue, and the `commandQueue in Redis` looks very abnormal.

![image](https://user-images.githubusercontent.com/52395237/102185050-694fb480-3eeb-11eb-8744-25a396408617.png)

**Comment by drecchia** [comment]
I have the same issue here while using xread. The main reason is the promise chain, that grows the stack forever.  You may need to break the stack, replacing function self claim like this:

process.nextTick(async () => {
	await listenForMessage( newLastIdEvent );
});

This solved for me! Its not an ioredis bug.

**Comment by Vinayvinayu** [comment]
@drecchia where do we have to add this code?

**Comment by drecchia** [comment]
> @drecchia where do we have to add this code?

Here at stream example https://github.com/luin/ioredis last line inside function has an recursive call, you need to encapsulate with process.nextTick as typed above. 

Regards.

**Comment by viniciusfdev** [comment]
This is still a problem, when submitting ioredis to intense usage, this results in a memory leak, and then, the application crash.
There is any workaround for that?

**Comment by drecchia** [comment]
I process over 2 millions of events per day using ioredis xread consumer, as I said before, the problem has been solved for me while using process.nextTick.  Here is my code:

`'use strict';

const logger = require('node-color-log');
const onDeath = require('death');

const streamControlKey = process.env.STREAM_GTW_CONTROL_KEY || 'streamConsumerKey.lastId';
const streamName = process.env.STREAM_GTW_KEY || 'stream-name';
const blockSize = process.env.STREAM_GTW_BUFFER_SIZE || 10;
let pendingBlocks = 0;
let continuousListener = true;

onDeath(function(signal, err) {
	logger.info('Preparing for death...');
	continuousListener = false;
});

async function listenForMessage( workerService, redisService, lastId = '$' ) {
	if ( ! continuousListener ) {
		process.exit(0);
	}

	logger.debug(`Querying data from redis on stream ${streamName} since ${lastId} ...`);

	const results = await redisService.redisGateway.xread( 'BLOCK', '5000', 'COUNT', blockSize, 'STREAMS', streamName, lastId );

	if ( results ) {
		pendingBlocks += 1;

		const start = Date.now();
		const [ key, messages ] = results[0]; // `key` equals to streamName

		// same until loop
		let newLastId = lastId;
		const proms = [];

		messages.forEach(async function(m) {
			const name = m[1][0];
			const data = m[1][1];

			newLastId = m[0];
			// NOTE: should we save after each processing ?  but... its async, not sequential

			const raw = JSON.parse( data );
			const dataCtx = { 'input': raw, 'aggregations': {}, 'debug': {}, 'tmp': {}, 'callbacks': [], 'alerts': [], 'estimates': {} };

		});

		const promResults = await Promise.allSettled(proms);

		pendingBlocks -= 1;

		const end = Date.now();
		logger.debug(`\tCompleted block of size ${messages.length}, duration ${end - start} ms! Pending blocks ${pendingBlocks}`);

		promResults.map((promise) => {
			// https://javascript.info/promise-api#promise-allsettled
			if ( promise.status == 'fulfilled' ) {
				// logger.info(promise.value);
			} else {
				const err = promise.reason;

				if ( err.message == 'GeocoderLinkException' ) {
					process.exit(2);
				} else if ( err.message != 'EqpNotFoundException' ) {
					logger.warn(err.message);
				}
			}
		});

		redisService.redisEngineControl.set( streamControlKey, newLastId );

		if ( pendingBlocks < 10 ) {
			process.nextTick(async () => {
				await listenForMessage( workerService, redisService, newLastId );
			});
		} else {
			logger.error('Too much pending blocks...');
		}
	} else {
		// no results, lets query same lastId
		process.nextTick(async () => {
			await listenForMessage( workerService, redisService, lastId );
		});
	}
};

module.exports = {
	init: function() {
		// dead code
		return new Promise((resolve, reject) => {
			resolve();
		});
	},
	start: function( workerService, redisService ) {
		redisService.redisEngineControl.get( streamControlKey ).then((result) => {
			if ( result != null ) {
				listenForMessage( workerService, redisService, result );
			} else {
				// listenForMessage( workerService, redisService, '1'); // from start
				listenForMessage( workerService, redisService, '$'); // tail
			}
		});
	},
};
`

**Comment by faxioman** [comment]
process.nextTick didn't solve our problem, removing ioredis did.
Surely we're doing something wrong, but without ioredis, we no longer have the leak.

**Comment by yduman** [comment]
We faced the same issue and our only solution was to replace ioredis with node-redis

**Comment by azerum** [comment]
> Have the same. No problem with Node Redis. Now I'll switch too.
> 
> ```
> const Redis = require('ioredis');
> const { v4: uuidv4 } = require('uuid');
> 
> const client = new Redis();
> 
> const userLimit = 10000;
> const entryLimit = 200;
> 
> client.on('ready', function() {
> 	console.log('redis ready');
> 
> 	var user = 0;
> 	var entry = 0;
> 	var user_uuid;
> 	while (user < userLimit) {
> 		user_uuid = uuidv4();
> 
> 		entry = 0;
> 		while (entry < entryLimit) {
> 			client.hmset('something:' + user_uuid, uuidv4(), '');
> 			entry++;
> 		}
> 
> 		user++;
> 	}
> 
> 	process.exit();
> });
> ```
> 
> <--- Last few GCs --->
> 
> [19064:000002809B3ABA80] 48052 ms: Mark-sweep 1398.6 (1424.8) -> 1398.1 (1425.3) MB, 383.5 / 0.0 ms (average mu = 0.109, current mu = 0.022) allocation failure scavenge might not succeed [19064:000002809B3ABA80] 48447 ms: Mark-sweep 1398.8 (1425.3) -> 1398.4 (1425.8) MB, 383.2 / 0.0 ms (average mu = 0.070, current mu = 0.028) allocation failure scavenge might not succeed
> 
> <--- JS stacktrace --->
> 
> ==== JS stack trace =========================================
> 
> ```
> 0: ExitFrame [pc: 000000FEAF9DC5C1]
> 1: StubFrame [pc: 000000FEAF9DDB86]
> ```
> 
> Security context: 0x02fd6331e6e9 2: toWritable [000000F56111B911] [S:\Projects\test\node_modules\ioredis\built\command.js:~150] [pc=000000FEAFF8F82F](this=0x001f100c10b9 ) 3: /* anonymous */ [000003B712574F41] [S:\Projects\test\node_modules\ioredis\built\redis\index.js:~577] [pc=000000FEAFF9F...
> 
> FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory 1: 00007FF7457CDD8A v8::internal::GCIdleTimeHandler::GCIdleTimeHandler+4506 2: 00007FF7457A8886 node::MakeCallback+4534 3: 00007FF7457A9200 node_module_register+2032 4: 00007FF745AC30DE v8::internal::FatalProcessOutOfMemory+846 5: 00007FF745AC300F v8::internal::FatalProcessOutOfMemory+639 6: 00007FF745CA9804 v8::internal::Heap::MaxHeapGrowingFactor+9620 7: 00007FF745CA07E6 v8::internal::ScavengeJob::operator=+24550 8: 00007FF745C9EE3C v8::internal::ScavengeJob::operator=+17980 9: 00007FF745CA7B87 v8::internal::Heap::MaxHeapGrowingFactor+2327 10: 00007FF745CA7C06 v8::internal::Heap::MaxHeapGrowingFactor+2454 11: 00007FF745DD1EA7 v8::internal::Factory::NewFillerObject+55 12: 00007FF745E4F096 v8::internal::operator<<+73494 13: 000000FEAF9DC5C1


Doesn't this code block the event loop until `userLimit * entryLimit` are written out to Redis, and only then starts to process reply to those commands? Likely, ioredis keeps some state bound to command that is not deleted until the command receives reply. The memory leak is hence due to creating `userLimit * entryLimit` such states

If you instead allow the event loop to process the replies (e.g. by adding delay in-between the loop iterations), such state should be released and eventually garbage collected

This problem still can happen if you send commands to Redis faster then Redis sends replies (so the state of the commands piles up in memory), but, in my opinion, you should handle such cases by using backpressure
