### ISSUE TITLE
ioredis hanging with aws elastic cache redis

### ISSUE THREAD

**Issue by cameljava** [luin/ioredis#894]
I am trying to use ioredis with aws elastic cache redis 5.0, cluster mode disabled. 

const Redis = require('ioredis');

async function createConnection(){

    return new Promise((resolve, reject) => {
        const connectionName = 'test';

        const client = new Redis({
            connectionName,
    	    port: '6379',
            host: 'master.xxxxxxx.seorg1.apse2.cache.amazonaws.com',
            password: 'xxxxxxxx',
        });

        client.on('connect', () => {
            console.log(`Redis has connected for: ${connectionName}`);
            resolve(client);
        });

        client.on('ready', () => {
            console.log(`Redis is ready for: ${connectionName}`);
        });

        client.on('close', () => {
            console.log(`Redis has closed for: ${connectionName}`);
        });

        client.on('reconnecting', () => {
            console.log(`Redis is reconnecting for: ${connectionName}`);
        });

        client.on('end', () => {
            console.log(`Redis has ended for: ${connectionName}`);
        });

        client.on('error', (err) => {
            console.error(err);
        });
    });
}

(async () => {
    try{
        const con = await createConnection();
	console.log('ready to test');
        await con.quit();
    }catch(e){
        console.error(e);
    }
})();

log:

node redis-test.js
  ioredis:redis status[master.redis-dev-drx.seorg1.apse2.cache.amazonaws.com:6379 (test)]: [empty] -> connecting +0ms
  ioredis:redis status[10.170.4.107:6379 (test)]: connecting -> connect +63ms
  ioredis:redis write command[10.170.4.107:6379 (test)]: 0 -> auth([ 'xxxxxxxxx' ]) +1ms
  ioredis:redis write command[10.170.4.107:6379 (test)]: 0 -> info([]) +3ms
Redis has connected for: test
ready to test
  ioredis:redis write command[10.170.4.107:6379 (test)]: 0 -> quit([]) +1ms

app keep hanging there, have to use crtl + C to kill it. 

second test: 
const Redis = require('ioredis');

async function createConnection(){

    return new Promise((resolve, reject) => {
        const connectionName = 'test';

        const client = new Redis({
            connectionName,
    	    port: '6379',
            host: 'master.xxxxxxx.seorg1.apse2.cache.amazonaws.com',
            password: 'xxxxxx',
        });

        client.on('connect', () => {
            console.log(`Redis has connected for: ${connectionName}`);
            resolve(client);
        });

        client.on('ready', () => {
            console.log(`Redis is ready for: ${connectionName}`);
        });

        client.on('close', () => {
            console.log(`Redis has closed for: ${connectionName}`);
        });

        client.on('reconnecting', () => {
            console.log(`Redis is reconnecting for: ${connectionName}`);
        });

        client.on('end', () => {
            console.log(`Redis has ended for: ${connectionName}`);
        });

        client.on('error', (err) => {
            console.error(err);
        });
    });
}

(async () => {
    try{
        const con = await createConnection();
	console.log('ready to test');
let setResult = await con.set('test-key', 'ok');
console.log('setResult: ', setResult);
data = await con.get('test-key');
console.log('get Data: ', data);
        await con.quit();
    }catch(e){
        console.error(e);
    }
})();

log:
node redis-test.js
  ioredis:redis status[master.xxxxxx.seorg1.apse2.cache.amazonaws.com:6379 (test)]: [empty] -> connecting +0ms
  ioredis:redis status[10.170.4.107:6379 (test)]: connecting -> connect +246ms
  ioredis:redis write command[10.170.4.107:6379 (test)]: 0 -> auth([ 'xxxxxxxxx' ]) +1ms
  ioredis:redis write command[10.170.4.107:6379 (test)]: 0 -> info([]) +3ms
Redis has connected for: test
ready to test
  ioredis:redis queue command[10.170.4.107:6379 (test)]: 0 -> set([ 'test-key', 'ok' ]) +1ms

The app hanging there without going any further. Can someone please help on this? Really appreciated.

**Comment by luin** [comment]
The second case is caused by the server didn't respond to the  `info` command, so the client didn't reach the "ready" status, causing the `set` command wasn't sent to the server.

Could you try to send the `info` command manually with redis-cli to see whether you can get the reply?

**Comment by dhanish2k** [comment]
If anyone is experiencing this issue, and if you have in-transit encryption enabled in Elasticache, adding  tls: {} to the redis options solved my issue

**Comment by alexbielen** [comment]
@dhanish2k I had the same issue -- good catch and thanks for the hint! 

For more context, `TransitEncryptionEnabled` was true in AWS Elasticache Redis. I'm using the `BullModule` from `@nestjs/bull` which uses `ioredis`. Leaving this here in case anyone else comes across this issue! Hopefully it'll save you a day of debugging. 

```
const ScannerQueue = BullModule.registerQueueAsync({
  ...
  useFactory: async (configService: ConfigService) => ({
    redis: {
      host: configService.get('redis.host'),
      port: +configService.get<number>('redis.port'),
      password: configService.get('redis.password'),
      tls: {},
    },
   ...
});
```
