### ISSUE TITLE
non-static ReplyTransformer?

### ISSUE THREAD

**Issue by Jonahss** [luin/ioredis#895]
Hi,

I'm the author of [ioredisgraph](https://github.com/jonahss/ioredisgraph), which just wraps ioredis, adds a new parameter to the constructor, and sets a custom ReplyTransformer.

Is there a way to set different ReplyTransformers for different instances of the client? The way that redisgraph works, my ReplyTransformer needs to behave differently depending on which db is being accessed.

**Comment by luin** [comment]
One possible way is to override the instance method directly:

```javascript
const asCallback = require('standard-as-callback').default
const Redis = require('ioredis')

const redis = new Redis()
const { mset } = redis
redis.mset = function (...args) {
  const callback = typeof args[args.length - 1] === 'function' ? args.pop() : null
  return asCallback(mset(...args).then(transformer), callback)
}
```

Haven't tested the code though. 🤣 


```

**Comment by Jonahss** [comment]
Oh okay, that should work fine. I'll just override the `redis.call` method.
