### ISSUE TITLE
Failed to connect to sentinel redis at Compute Engine

### ISSUE THREAD

**Issue by Yosafat1997** [luin/ioredis#897]
I have cloud function at us-central1 and redis instance at asia-southeast1c. I have use vpc, but this error persist every time when i connect to it:

```
[ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 10ms. Last error: Connection is closed.
    at connectToNext (/srv/node_modules/ioredis/built/connectors/SentinelConnector/index.js:55:31)
    at /srv/node_modules/ioredis/built/connectors/SentinelConnector/index.js:93:21
    at client.sentinel (/srv/node_modules/ioredis/built/connectors/SentinelConnector/index.js:127:24)
    at tryCatcher (/srv/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/srv/node_modules/standard-as-callback/built/index.js:30:51)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)
```

this is i have try to connect to sentinel:

```
Redis = require('ioredis')
var redis = new Redis({
    sentinels: [{host: "172.26.11.2", port: "26379"},{host: "172.26.11.3", port: "26379"}],
name: "mymaster"
});
```

```
Redis = require('ioredis')
var redis = new Redis({
    sentinels: [{host: "dev-redis-0", port: "26379"},{host: "dev-redis-1", port: "26379"}],
name: "mymaster"
});
```

Does anyone know how should I do about it? Thanks

**Comment by luin** [comment]
It seems to be an issue related to the network. Please make sure that the destination is reachable.

**Comment by pezzati** [comment]
I have this issue too. All ports (6379, 6380, 26379) are accessible (checked by telnet command). When i run script with `DEBUG=ioredis:*` i get below output.

        ioredis:redis status[localhost:6379]: [empty] -> connecting +0ms
        ioredis:redis status[redis_host_ip:26397]: [empty] -> connecting +6ms
        ioredis:redis queue command[redis_host_ip:26397]: 0 -> sentinel([ 'get-master-addr-by-name', 'mymaster' ]) +2ms

        ioredis:redis queue command[localhost:6379]: 0 -> set([ 'foo', 'bar' ]) +9ms
        ioredis:connection error: Error: connect ETIMEDOUT redis_host_ip:26397 +0ms
        ioredis:redis status[redis_host_ip:26397]: connecting -> close +7s
        ioredis:connection skip reconnecting because `retryStrategy` is not a function +1ms
        ioredis:redis status[redis_host_ip:26397]: close -> end +0ms
        ioredis:SentinelConnector failed to connect to sentinel redis_host_ip:26397 because Connection is closed. +0ms
        ioredis:SentinelConnector All sentinels are unreachable. Retrying from scratch after 10ms. Last error: Connection is closed. +0ms
        [ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 10ms. Last error: Connection is closed.
            at connectToNext (/home/masoud/location-masideh/node_modules/ioredis/built/connectors/SentinelConnector/index.js:55:31)
            at /home/masoud/location-masideh/node_modules/ioredis/built/connectors/SentinelConnector/index.js:93:21
            at client.sentinel (/home/masoud/location-masideh/node_modules/ioredis/built/connectors/SentinelConnector/index.js:127:24)
            at tryCatcher (/home/masoud/location-masideh/node_modules/standard-as-callback/built/utils.js:11:23)
            at promise.then (/home/masoud/location-masideh/node_modules/standard-as-callback/built/index.js:30:51)
            at process._tickCallback (internal/process/next_tick.js:68:7)


My script is:

        const Redis = require('ioredis');

        console.log("hi");
        async function kir(){
                console.log("init redis");
                const redis = new Redis({sentinels: [{port:'26397', host: '172.24.0.117'}], name: 'mymaster'});
                console.log("redis is ready");
                await redis.set('foo', 'bar');
                console.log("set");
                const a = await redis.get('foo');
                console.log(a);
        }

        setTimeout(async () => {
                console.log("SALAM");
                await k();
                console.log("IO");
        }, 1000);
        console.log("bye");
