### ISSUE TITLE
send_command is not a function

### ISSUE THREAD

**Issue by siddo420** [luin/ioredis#90]
I am using metroplex node module that requires a redis connection. When I used ioredis, I got the following error whereas the default Redis client (that comes with metroplex) seems to work fine.

```
/node-web-projects/test3/node_modules/ioredis/node_modules/bluebird/js/main/async.js:43
        fn = function () { throw arg; };
                                 ^
TypeError: leverage._.client.send_command is not a function
```

Any ideas what send_command is and why it is not supported?

FYI: I am using iojs

**Comment by siddo420** [comment]
Looks like metroplex is using https://github.com/mranney/node_redis

**Comment by luin** [comment]
`send_command` is a private method in node_redis.

**Comment by siddo420** [comment]
Ok, so you're saying that metroplex is dependent on that particular node module because of the function/method it uses.

Any chance ioredis would implement a function/feature like that?

**Comment by luin** [comment]
Well, I checked the documentation of node_redis again and it turns out `send_command` is a public method since it's documented [here](https://github.com/mranney/node_redis#clientsend_commandcommand_name-args-callback). I'm going to implement it in ioredis.

BTW, Where does metroplex use `send_command` method? I just checked it out and didn't find it.

**Comment by siddo420** [comment]
Looks like metroplex is using a Redis wrapper named leverage (https://www.npmjs.com/package/leverage) around redis client and that wrapper is using send_command.

I used the following command to list all instances where send_command is used in both leverage and redis client.

egrep -ir "send_command"  node_modules/metroplex/

**Comment by luin** [comment]
Added in 1.5.10

**Comment by 3rd-Eden** [comment]
Thank you.
