### ISSUE TITLE
The documentation and maybe implementation for ScanStream seems wrong

### ISSUE THREAD

**Issue by JamesFaix** [luin/ioredis#908]
The documentation here https://www.npmjs.com/package/ioredis#streamify-scanning and the behavior I see when using this command in `ioredis` seem to not be in line with how `SCAN` is supposed to work in Redis.

See the Redis `SCAN` docs here https://redis.io/commands/scan#the-count-option

SCAN accepts 3 args: `CURSOR`, `MATCH`, `COUNT`
  - `CURSOR` is the offset to start scanning at, which starts at 0.
  - `MATCH` is the pattern to match, which is optional. By default it returns everything.
  - `COUNT` is the number of keys to check for each call to `SCAN`. This default to 10.

The idea is that `SCAN` checks batches of `COUNT` keys at a time so it doesn't block other threads while iterating the whole database.
Each call to `SCAN` returns an array of `[Index to start next SCAN call at, [keys found]]`

So if you called it once like this `SCAN 0 *foo* 1000`,
it might return `[1000, ["foo", "food", "foobar"]]`

The first element of the array tells you to next try `SCAN 1000 *foo* 1000`

When it gets to the end of the database, it will return 0 as the first element.

The `ioredis` documentation linked says that `COUNT` is the number of keys to return at a time, but it is the number to scan at a time. `scanStream` seems to be missing the `cursor` option that should also be available to call repeatedly correctly.

Always passing `Number.MAX_SAFE_INTEGER` as `COUNT` seems to approximate correct behavior, but would also introduce the blocking behavior Redis is trying to avoid.

**Comment by luin** [comment]
Sorry for the late response. Didn't notice this issue.

> The ioredis documentation linked says that COUNT is the number of keys to return at a time, but it is the number to scan at a time.

You are right about `COUNT` isn't the actual number of keys to return at a time, but it's the number that users expecting. Redis will scan `10*COUNT` each time internally in order to provide the expected number of keys (that's what `approximately` means in ioredis documentation).

> scanStream seems to be missing the cursor option that should also be available to call repeatedly correctly.

`scanStream` handles `CURSOR` internally so users don't need to.
