### ISSUE TITLE
Support sentinel with multiple URLs

### ISSUE THREAD

**Issue by ran-eh** [luin/ioredis#910]
This is similar to #557.  The connection stream (URL) feature is useful for configuration via env vars, and it will be nice to have the same capability for sentinel servers.

As you stated in #557, the [redis URI schema](https://www.iana.org/assignments/uri-schemes/prov/redis) does not support this case (yet?), and it is probably not a good idea to invent something non-standard.  As a workaround, we can allow a delimiter separated multi-URI format. e.g. 

```
const uris = "redis://:password@host1:port1,redis://@host2:port2,redis://@host3:port3";
const redis = new Redis(uris);
```

This may break URIs in existing programs that include the separator.  To minimize this problem, the implementation will need to only recognize the separator as such if it is preceded by ```redis://```.

We also need to decide what to do if the URIs contain conflicting passwords.  IMO the connection string should be considered invalid and the library should fail when this happens.  In other words, multiple URIs may contain passwords as long as they are identical.

What are your thoughts on this?  If you like the idea, I may be able to code a PR for it.

-- Ran

**Comment by luin** [comment]
Lettuce offers support for Sentinel URI schema: https://lettuce.io/core/release/reference/index.html#basic.redisuri, which makes sense to me. I think we can adopt the same schema format.

**Comment by Grmiade** [comment]
Hi 👋 Any news about this? It could be great to see that integrated to ioredis.
