### ISSUE TITLE
Connection is Closed

### ISSUE THREAD

**Issue by kunal-til** [luin/ioredis#913]
ioRedis@4.9.0
Redis Server Version: 5 
Using Redis sentinel on production.

Error: Connection is closed.
    at Redis.sendCommand (/nodeApi/node_modules/ioredis/built/redis.js:552:24)

I have specified the retryStragey, which is working if any redis node(master) goes down and I am assuming it should work for this case too. Or do I need to specify some other option?

```javascript
var redis = require('ioredis'),
client = Promise.promisifyAll(redis.createClient( {
	sentinels: config.redis.endpoints,
	name: config.redis.masterName,
	prefix: config.database.redisPrefix,
	pass: config.database.redisPassword,
	role:"slave",
	retry_strategy: function (options) {
		if (options.error.code === 'ECONNREFUSED') {
			// End reconnecting on a specific error and flush all commands with a individual error
			return new Error('The server refused the connection');
		}
		if (options.total_retry_time > 1000 * 60 * 60) {
			// End reconnecting after a specific timeout and flush all commands with a individual error
			return new Error('Retry time exhausted');
		}
		if (options.times_connected > 10) {
			// End reconnecting with built in error
			return undefined;
		}
		// reconnect after
		return Math.max(options.attempt * 100, 500);
	}
})),

client.on("error", function (err) {
	console.log("Error " + err);
});
```

**Comment by luin** [comment]
ioredis supports Promise by default, and the `retry_strategy` should be `retryStrategy`.

```javascript
const Redis = require('ioredis')
const redis = new Redis({
  sentinels: config.redis.endpoints,
  name: config.redis.masterName,
  prefix: config.database.redisPrefix,
  pass: config.database.redisPassword,
  role:"slave",
  retryStrategy() {
    return 10
  }
})
```

**Comment by gajus** [comment]
`retryStrategy ` does not provide "options" parameter. It provides "times" parameter that describes the retry attempt number.

See https://github.com/luin/ioredis#auto-reconnect

@luin the documentation states:

> By default, ioredis will try to reconnect when the connection to Redis is lost except when the connection is closed manually by redis.disconnect() or redis.quit().

How to disable the default?

I want to crash the program in case Redis disconnects.

**Comment by gajus** [comment]
One could do something like this:

```js
const redis = new Redis(redisDsn, {
  connectionName: 'rayman',
  connectTimeout: 1000,
  retryStrategy: () => {
    redis.quit();
  }
});

redis.on('error', (error) => {
  log.error({
    error: serializeError(error)
  }, 'Redis error');

  if (error.code === 'ECONNREFUSED') {
    lightship.shutdown();
  }
});

```

But since it is not documented, it is not clear if that is the canonical way to terminate the service.

**Comment by gajus** [comment]
Right. This strategy is bad. Don't do it.

If the connection is lost after it has been established, then this `redis.on('error')` is never called. This is surprising.

However, this seems to work as expected:

```js
onst redis = new Redis(redisDsn, {
  connectionName: 'rayman',
  connectTimeout: 1000,
  retryStrategy: () => {
    redis.quit();
  }
});

redis.on('error', (error) => {
  log.error({
    error: serializeError(error)
  }, 'Redis error');
});

redis.on('end', () => {
  log.warn('shutting down service due to lost Redis connection');

  lightship.shutdown();
});

```

**Comment by luin** [comment]
Just set `retryStrategy` to `null` will do the trick:

```javascript
const redis = new Redis(redisDsn, {
  retryStrategy: null
});

redis.on('end', () => {
  log.warn('shutting down service due to lost Redis connection');

  lightship.shutdown();
});
```

**Comment by gajus** [comment]
That does work. I don't think it is documented, though.

**Comment by luin** [comment]
@gajus Actually it's documented https://github.com/luin/ioredis#auto-reconnect, but in another format:

> retryStrategy is a function that will be called when the connection is lost. The argument times means this is the nth reconnection being made and the return value represents how long (in ms) to wait to reconnect. When the return value isn't a number, ioredis will stop trying to reconnect, and the connection will be lost forever if the user doesn't call redis.connect() manually.

So besides `retryStrategy: null`, you can also write `retryStrategy() { return false }`. The documentation needs a restructure anyway as it becomes too long to read.
