### ISSUE TITLE
redis keep reconnecting when it was been closed？

### ISSUE THREAD

**Issue by yangzhanmei** [luin/ioredis#916]
```
const redis = new Redis(
  Object.assign({}, config.redis.server, {
    retryStrategy(times) {
      return Math.min(times * 100, 3000);
    }
  })
)

redis.on('error', err => {
  console.log(`redis error:${err.toString()}`);
});
```
I closed the redis to check the err-handle, but it keep reconnecting
err message log:
```
redis error:Error: connect ECONNREFUSED 127.0.0.1:6379
```

**Comment by luin** [comment]
That is the expected behavior. You can disable reconnection by returning a `false` in `retryStrategy`.

**Comment by yangzhanmei** [comment]
> That is the expected behavior. You can disable reconnection by returning a `false` in `retryStrategy`.

**Comment by yangzhanmei** [comment]
> That is the expected behavior. You can disable reconnection by returning a `false` in `retryStrategy`.

I tried this,  when it reconnect 10 times, it does not reconnect, but the server is dead:
```
 retryStrategy(times) {
      if (times > 10) {
        return false;
      }
      return Math.min(times * 100, 3000);
    }
```
I try to use `redis` package, it can catch the error, and the server could not be done.

**Comment by luin** [comment]
没太看懂，说中文吧。你期望的结果是什么？为什么呢？

**Comment by yangzhanmei** [comment]
> 没太看懂，说中文吧。你期望的结果是什么？为什么呢？

哦哦，英文不太好，不好意思哈
我使用刚才那个代码，发现确实是重连十次之后就不再重连了，但是服务挂了
我同样使用`redis`这个包，如下代码，重连10次之后不再重连，服务也没有挂，我理解错误机制应该是一样的叭
```
const redis = Redis.createClient(
  Object.assign({}, config.redis.server, {
    retry_strategy: options => {
      if (options.error && options.error.code === 'ECONNREFUSED') {
        console.log('redis: refused the connection');
      }
      if (options.total_retry_time > 10000) {
        console.log('redis: retry time exhausted');
      }
      if (options.attempt > 10) {
        console.log(`redis: attempt time ${options.attempt}`);
      }
      return Math.min(options.attempt * 100, 3000);
    },
  }),
);
```

**Comment by luin** [comment]
「服务挂了」是指 Redis 服务器挂了？这个不会有影响的。
如果「服务挂了」指进程退出了，那么是正常的，因为不再重连，没有活跃的连接存在了，所以理应退出当前进程的。一般情况下对于 Web 应用，会有其他活跃连接，所以不会退出。

**Comment by yangzhanmei** [comment]
> 「服务挂了」是指 Redis 服务器挂了？这个不会有影响的。
> 如果「服务挂了」指进程退出了，那么是正常的，因为不再重连，没有活跃的连接存在了，所以理应退出当前进程的。一般情况下对于 Web 应用，会有其他活跃连接，所以不会退出。

嗯嗯 是的呢 非常感谢
