### ISSUE TITLE
Please add support for RedisTimeSeries :)

### ISSUE THREAD

**Issue by vgoklani** [luin/ioredis#919]
Could you please add support for RedisTimeSeries

https://oss.redislabs.com/redistimeseries/

thanks!

**Comment by luin** [comment]
ioredis works with arbitrary commands with `Redis#call(commandName: string, ...args: any[]): Promise<any>`, so RedisTimeSeries is already supported:

```javascript
const redis = new Redis()
redis.call('TS.ADD', 'temperature:3:11', 1548149181, 30)
```
