### ISSUE TITLE
打算加连接池api吗?

### ISSUE THREAD

**Issue by ahkimkoo** [luin/ioredis#92]
打算加连接池api吗?  我使用generic poll 来做不能release链接.
```
redis_pool = poolModule.Pool({
        name     : 'redis',
        create   : function(callback) {
            var redis_cli = new Redis({
                port: settings['cache_db_port'],
                host: settings['cache_db_host'],
                family: 4,
//                password: 'auth',
                db: settings['cache_db_name']
            });
            callback(null,redis_cli);
        },
        destroy  : function(client) {
            client.quit();
//            client.disconnect();
        },
        max      : 10,
        min      : 0,
        idleTimeoutMillis : 30000,
        log : true
    });
```

**Comment by luin** [comment]
还没有计划。Redis 是单线程模型，所以多个连接不会有性能提升。你的应用场景是？

**Comment by ahkimkoo** [comment]
我用node-redis和generic poll尝试了连接池. 在高并发的情况下比一次操作连接一次或者多次操作使用一个连接的性能要明显高出很多. 所以我觉得连接池还是有必要的.

**Comment by luin** [comment]
可以提供一个简单的测试代码吗？我周末试一下

**Comment by ahkimkoo** [comment]
我是结合我的业务代码测试的. 我的业务单用户每次访问读写redis约47次. 里面有一些paralle操作, 在发送2万请求的情况下,
分别对一个redis连接和连接池的情况做了测试, 发现使用连接池后的平均响应时间和最长响应时间都比使用单一连接的要短. 我也没搞清楚原因,
当然使用generic poll做redis的连接池有一个bug, 当连接数达到设定的max数量后, 很多连接会僵死, 因为generic
poll将请求callback放在队列里清理idel的时候是清理这些callback, 而调用端一直等待callback.
如果你打算加连接池的话特别留意一下这个陷阱.

2015-07-10 9:56 GMT+08:00 Zihua Li <notifications@github.com>:

> 可以提供一个简单的测试代码吗？我周末试一下
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/luin/ioredis/issues/92#issuecomment-120199700>.
>



-- 
       顺颂
商祺
--------------------------------------------------------------------------------------------------------
>刘成功

>邮箱: successage@gmail.com

>手机:15901977721

>QQ: 419117039
>MSN:successage@gmail.com
>SKYPE:successage
>ICQ:461538512
---------------------------------------------------------------------------------------------------------

**Comment by cfan8** [comment]
连接池能提高性能有可能只是因为缓存变大的原因, 建议把内核参数里的TCP读写缓存选项调大这样比较才公平

**Comment by luin** [comment]
放到 #123 讨论了，这个关掉咯~

**Comment by alsotang** [comment]
总结来看，一般需要pool的情况在我看来是以下：
1. 服务器具备多线程能力
2. 网络io太慢

对于mysql和pg来说，1和2都符合，而且大家的习惯也是开启pool来使用。
对于redis来说，只能是2这个原因，因为redis是单线程的，假如一个scan命令占满了cpu，其他所有connections都卡住。当不信任  redis client 和 redis server 之间的网络连接时，就需要用 pool 来提高 redis server 利用率了。

参考下 https://github.com/coopernurse/node-pool
