### ISSUE TITLE
Encryption support

### ISSUE THREAD

**Issue by wavded** [luin/ioredis#93]
This is more a question than a request as this may not be the best spot for it but I have users of `connect-redis` who would like encryption and decryption support when they set and retrieve data from redis.  Have you given it any thought to this capability built into `ioredis` @luin ?

The idea was sparked from some people who patched `node_redis` to support: (https://gist.github.com/calvinfroedge/080dfba68519bc926124)

**Comment by luin** [comment]
I incline to implement encryption in a wrapper because Redis is designed to be accessed by trusted clients inside trusted environments, it shouldn't be a general requirement to encrypt data in Redis. Besides, it's pretty straightforward to implement it in a wrapper.

**Comment by klinquist** [comment]
I agree with luin.
I'm encrypting data that flows through redis and that is stored in our db.  This is how I do it:
```
var crypto = require('crypto');
var algorithm = "aes-256-ctr";
var password = process.env.TOKEN_ENC_KEY

exports.encrypt = function(text) {
    if (!password){
        console.log("Warning, text is not being encrypted because there is no TOKEN_ENC_KEY env var");
        return text;
    } else {
        var cipher = crypto.createCipher(algorithm,password);
        var crypted = cipher.update(text,'utf8','hex');
        crypted += cipher.final('hex');
        return crypted;
    }
};


exports.decrypt = function(text) {
    if (!password){
        console.log("Warning, text is not being decrypted because there is no TOKEN_ENC_KEY env var");
        return text;
    } else {
        var decipher = crypto.createDecipher(algorithm,password);
        var dec = decipher.update(text,'hex','utf8');
        dec += decipher.final('utf8');
        return dec;
    }
};

```

**Comment by knoxcard** [comment]
There is also this ... https://github.com/Stono/ioredis-encrypted
