### ISSUE TITLE
previously working rediss:// url does not work since 4.14.0

### ISSUE THREAD

**Issue by mkls** [luin/ioredis#940]
Hello,

In 4.14.0 support for rediss:// url was introduced, but trying to connect to an url like this we get:
```
[ioredis] Unhandled error event: Error: unable to verify the first certificate
```
errors.

Before this version we used to have a workaround in our code for connecting to rediss:// urls which looked something like this:
```
const { URL } = require('url');
const redisUri = 'rediss://...'
const options = {
  lazyConnect: true,
  retryStrategy: () => 1000
};
if (redisUri.startsWith('rediss://')) {
  options.tls = { servername: new URL(redisUri).hostname };
}
const connection = new Redis(redisUri, options)
```
which was working fine. (even in local development where we had a regular redis:// url)

With this newly introduced feature I haven't been able to find the right options to make this work.

It looks like the new parser set's `tls: true` in options, and we would need more detailed config here.

**Comment by luin** [comment]
Just submitted a pull request for this issue.

For now, the workaround would be changing the protocol to `redis://` after assigning `tls`:

```javascript
if (redisUri.startsWith('rediss://')) {
  options.tls = { servername: new URL(redisUri).hostname };
  redisUri = redisUri.replace('rediss://', 'redis://')
}
```

After the pull request being merged, you can parse the tls option via URL directly:

```javascript
const redisUri = 'rediss://127.0.0.1/?tls[servername]=127.0.0.1'
const options = {
  lazyConnect: true,
  retryStrategy: () => 1000
};

const connection = new Redis(redisUri, options)
```
