### ISSUE TITLE
ioredis caching host when using a reader endpoint

### ISSUE THREAD

**Issue by fedebrasburg** [luin/ioredis#941]
Hi

I am trying to use the reader endpoint of an aws redis cache (https://aws.amazon.com/about-aws/whats-new/2019/06/amazon-elasticache-launches-reader-endpoint-for-redis/?nc1=f_ls).
I realized when using ioredis with the reader endpoint it always uses the same cache (like it is caching the final host) but when I dig the reader endpoint it works fine (it returns a different cache every time).

Do you know if ioredis is caching the final host? How could I fix it?

Thank you

**Comment by luin** [comment]
ioredis doesn't cache host, but it does keep a long connection to the host. A reconnection (`redis.disconnect(true)`) will force ioredis to re-create a new connection, in which case a new host may be selected.

**Comment by knoxcard** [comment]
@fedebrasburg - close issue?

**Comment by timschlechter** [comment]
I struggled a while with this, but it turned out my expectations where wrong. I thought using the AWS reader endpoint it would evenly split incoming Redis commands over the replica nodes.

But it evenly splits _incoming connections_: https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/Replication.Endpoints.html

**Comment by yurik94** [comment]
We need to add and remove read replicas without code deployes every time, do we need to open and close connections to reader endpoint for every request, so every read replica has a chance to be hit?

**Comment by soryy708** [comment]
@yurik94 churning connections is inefficient. At low volumes that could work fine, but at higher volumes I'd keep a pool of connections client-side, and round-robin between them.

**Comment by yurik94** [comment]
Sorry @soryy708 I think I was talking about code running on lambda. Maybe what we needed was something like RDS Proxy, but for ElastiCache.
