### ISSUE TITLE
pipeline not working with redisearch comands

### ISSUE THREAD

**Issue by autocorrectoff** [luin/ioredis#946]
so I was trying to use pipelining with redisearch, like so 
`await redis.pipeline([['ft.search', 'my_index', '*']]).exec();`
but all I got is
**TypeError: Cannot read property 'apply' of undefined**

**Comment by Sceat** [comment]
This damn bot closing every issues makes ioredis looks well maintained but in fact is not, this issue and many more are still there :-1:

**Comment by Jav3k** [comment]
up

**Comment by Jav3k** [comment]
Solution: https://github.com/luin/ioredis/issues/1313#issuecomment-809402608
