### ISSUE TITLE
Implement transparent key prefixing

### ISSUE THREAD

**Issue by dguo** [luin/ioredis#95]
Hi, I noticed that you have this feature on the roadmap, and I'd like to help implement it. Do you have any ideas about how it will work?

**Comment by luin** [comment]
That will be great. We can give user an option to specify a key prefix:

```javascript
var redis = new Redis({ keyPrefix: 'app1:' });
```

and then the keys of every command sent by this instance should get a prefix of `'app1:'`. For instance:

0. `redis.set('foo', 'bar')` will actually send `SET app1:foo bar`;
0. `redis.blpop('key1', 'key2', 'key3', 0)` will actually send `BLPOP app1:key1 app1:key2 app1:key3 0`;

**Comment by luin** [comment]
We already have a method `Command#getKeys` for getting keys in a command(https://github.com/luin/ioredis/blob/master/lib/command.js#L85).

**Comment by dguo** [comment]
Sounds good. What's your opinion on giving the user flexibility for commands that have multiple keys? So something like:

```js
var redis = new Redis({keyPrefix: ['app1:', 'app2:', 'app3:']});
redis.blpop('key1', 'key2', 'key3', 0);  // BLPOP app1:key1 app2:key2 app3:key3 0
```

Or maybe even allow the user to dynamically set the prefix?

```js
var redis = new Redis({keyPrefix: 'foo:'});
redis.blpop({keyPrefix: ['app1:', 'app2:', 'app3:']}, 'key1', 'key2', 'key3', 0);
``` 

I'm not sure how useful this would be.

**Comment by luin** [comment]
I prefer to keeping this option simple. My intention to add `keyPrefix` option is to allow multiple apps using one Redis server.`keyPrefix` is used as a namespace, so a single string is enough.

**Comment by dguo** [comment]
Ok, that's reasonable. I'll get to work on it.

**Comment by Delagen** [comment]
scanstream match option does not use this prefix

**Comment by luin** [comment]
@Delagen This has already been discussed. Refer to https://github.com/luin/ioredis/issues/239 for more information.
