### ISSUE TITLE
mgetBuffer()

### ISSUE THREAD

**Issue by kirillgroshkov** [luin/ioredis#951]
Is there a way to do `mgetBuffer()`? I want `mget` that returns array of Buffers. Can't find anything in documentation...

UPD: answering my own question. Apparently, there IS `mgetBuffer()`, it's just missing in the typescript typings for some reason!

**Comment by luin** [comment]
Doesn't redis.mgetBuffer() work for you?

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by kirillgroshkov** [comment]
> Doesn't redis.mgetBuffer() work for you? 

I was confused with the lack of typings, `mgetBuffer()` doesn't exist in typings.

Now I also realized that I have types from `@types/ioredis` and not from `ioredis`, despite github showing me that it's written in TypeScript. Either way - issue is with typings.

**Comment by knoxcard** [comment]
@kirillgroshkov - close issue?

**Comment by kirillgroshkov** [comment]
@knoxcard thanks for asking.

I think these's still an issue with typescript typings. But also I see that typings are from external package from DefinitelyTyped (`@types/ioredis`). Then yes, you probably can close this issue.

But just out of curiosity, why doesn't `ioredis` export types in `package.json`, so it can be used without external types from `@types/ioredis`? It should be quite trivial to do.

**Comment by kirillgroshkov** [comment]
Ok, let's close it, since there are other issues about exporting types from this package: 
https://github.com/luin/ioredis/issues/963
https://github.com/luin/ioredis/pull/981

**Comment by Javarome** [comment]
@kirillgroshkov I'm lost. I can't find mgetBuffer anywhere: @types/ioredis doesn't declare it and ioredis doesn't include its own types. What am I missing?

**Comment by kirillgroshkov** [comment]
> @kirillgroshkov I'm lost. I can't find mgetBuffer anywhere: @types/ioredis doesn't declare it and ioredis doesn't include its own types. What am I missing?

Yes, that's the same experience that I had. And the conclusion was that it's indeed missing in Types, but exists in the Runtime (in js). So, I used it despite them being missing in Types.
