### ISSUE TITLE
handle graceful shutdown 

### ISSUE THREAD

**Issue by sophister** [luin/ioredis#959]
Hi, I've used `ioredis` to access the Redis cluster. 

I'm wondering whether I need to close the Redis connection manually when my HTTP server is shutdown?

Recently I've encountered with the Redis problem **ERR max number of clients reached**, I think maybe it's due to I have not closed any Redis connections when my server shutdown. So I write a demo, start a Redis connection and shut down the program, but the `client list` shows that the shutdown-client does not exist anymore. And I've  checked Redis's config, and the `timeout` is set to `0`, so the server will not close any client connections.

So, do we need to close the connection manually, Or the framework has done something for us?

**Comment by knoxcard** [comment]
Try adding this...

```
process.on('SIGINT', () => {
  if(app.get('server'))
    app.get('server').close()
  if(app.get('redis'))
    app.get('redis').quit()
  if(app.get('mail'))
    app.get('mail').close()
  console.log(app.get('colors').whiteBright('[App Exited'))
  process.exit(0)
})
```

**Comment by knoxcard** [comment]
Submitted pull request to update the documentation as well.

https://github.com/luin/ioredis/pull/985

**Comment by tuananh** [comment]
@knoxcard from my experience, all the modern apps should have graceful shutdown logic implemented.

it's not only just redis but database and other kind as well.

shoudln't it be implemented in each application?
