### ISSUE TITLE
[redis.multi]: Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by TENCHIANG** [luin/ioredis#960]
```
TypeError: Cannot read property 'apply' of undefined
    at Pipeline.addBatch (/Users/yy/Desktop/works/jjqshop-server/node_modules/ioredis/built/pipeline.js:176:27)
    at Redis.redis.multi (/Users/yy/Desktop/works/jjqshop-server/node_modules/ioredis/built/transaction.js:26:22)
```

```js
redis.multi([
    ['select', dbIndex],
    ['set', 'aaa', 'empty'] // delete this line and it will works
    ['select', 0],
]).exec()
// it runs well
// redis
// .multi()
// .select(dbIndex)
// .set('set', 'aaa', 'empty')
// .select(0)
// .exec()
```

**Comment by shaharmor** [comment]
Aren't you missing a `,` after the `['set', 'aaa', 'empty']`?

**Comment by TENCHIANG** [comment]
> Aren't you missing a `,` after the `['set', 'aaa', 'empty']`?

sorry, `,` is there before, but still wrong

**Comment by TENCHIANG** [comment]
> Aren't you missing a `,` after the `['set', 'aaa', 'empty']`?

thank you, I made a low-level mistake.

**Comment by AnjaliGupta88** [comment]
Hi,
For those that faced the same issue despite having correct array commands, please try by switching the command name to lowercase. For e.g. instead of ['HSET', 'k1','v1'] write  ['hset', 'k1','v1']. This resolved the same issue I was facing. 
Hope it helps!
