### ISSUE TITLE
How to Realize Counting

### ISSUE THREAD

**Issue by TomorrowCat** [luin/ioredis#966]
I can't find the INCR method. Could you tell me what to do?

**Comment by luin** [comment]
Use redis.incr()

Get Outlook<https://aka.ms/qtex0l> for iOS

________________________________
发件人: TomorrowCat <notifications@github.com>
发送时间: 星期三, 九月 18, 2019 7:58 上午
收件人: luin/ioredis
抄送: Subscribed
主题: [luin/ioredis] How to Realize Counting (#966)


I can't find the INCR method. Could you tell me what to do?

―

**Comment by TomorrowCat** [comment]
Thanks! It has been found.
