### ISSUE TITLE
Question: Is there a way to log commands being sent to redis?

### ISSUE THREAD

**Issue by ThisIsMissEm** [luin/ioredis#968]
I know I could achieve this by wrapping every method, but ideally, I don't want to do that. Essentially, in certain conditions, like development, I'm wanting to have a function called to log every command being sent from node.js to Redis. Is there a way to archive this?

**Comment by ThisIsMissEm** [comment]
@tuananh okay, it looks like the typedefs for sendCommand are incorrect, I can see it used with two signatures:

```
sendCommand(command: IORedis.Command)
sendCommand(command: IORedis.Command, stream: ?, node: ?)
```

I'm not sure what `stream` and `node` are above, as there's no type information in the code for them

**Comment by ThisIsMissEm** [comment]
@tuananh any thoughts on how we should go about fixing the incorrect type definitions for sendCommand?

**Comment by tuananh** [comment]
> @tuananh any thoughts on how we should go about fixing the incorrect type definitions for sendCommand?

I'm not sure. types is located in another repo, not sure if anyone is maintaining it

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/ioredis/index.d.ts

**Comment by ThisIsMissEm** [comment]
@tuananh oh? That's odd for a project that's written in typescript?

**Comment by ThisIsMissEm** [comment]
I guess as a temporary thing I can patch the @types/ioredis package to fix it.

**Comment by tuananh** [comment]
> I guess as a temporary thing I can patch the @types/ioredis package to fix it.

i guess because at first @luin hasn't finished migrating everything to ts so he needs to add an options that `allowJs` in tsc. but using this option, `tsc` is unable to produce `d.ts` files.

now that ioredis is fully migrated to TS, i think we can generate `d.ts` files and publish to npm so that we dont need to maintain types.
