### ISSUE TITLE
Error event listener is not fired when the cluster is not connectable

### ISSUE THREAD

**Issue by Asing1001** [luin/ioredis#969]
## Code :
```js
const redisClient = new Cluster(config.get('server.redis.cluster'))
redisClient.on('error', (err) => console.error('error listener', err))
```

## Step to reproduce
1. Connect to the cluster correctly
2. Turn off network

### As is
Unhandled error occur and the application crash
```
Error: connect ENETUNREACH <ip_address> - Local (0.0.0.0:49664)
    at internalConnect (net.js:858:16)
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:299:19)
    at defaultTriggerAsyncIdScope (net.js:948:9)
    at processTicksAndRejections (internal/process/next_tick.js:74:9)
```

### Expect
The error should be catch by the error event listener

**Comment by ajimix** [comment]
I have the same problem, started happening in a recent update, how come that the error event is not fired in such case?

**Comment by atcheri** [comment]
Hi
same here 
node version 10.16.3
ioredis version: 4.14.1

Any workaround otherwise ?

**Comment by ajimix** [comment]
This issue is still happening in the latest version. Why is the bot closing it? 🤔

**Comment by henrikhaugboelle** [comment]
I'm also encounting this with `iosredis@4.14.1`

**Comment by shameersheik** [comment]
ioredis@4.28

The below got triggered when initially the app wasnot able to reach redis
redisClient.on('error', (err) => {})  

Below got triggered when there was an error after the intial connection.

Some of the errors that didnot trigger redisClient.on('error', (err) => {}) in ioredis but triggered

reconnectOnError: function (err) {
          logger.info(`Got an error when redis tried to connect: ${err.message}`);
          return true;
        },
