### ISSUE TITLE
ERR max number of clients reached

### ISSUE THREAD

**Issue by akaNightmare** [luin/ioredis#972]
Hello.

It seems that `ioredis` does not close connections to the Redis shard and opens new ones. In the project, we have 26 shards, we cannot use them in a cluster mode for some reason and we are opened each connection for each cluster and we have some internal mechanism(similar to the `cluster-key-slot`) to determinate correct shard to send Redis commands, here the code:
```
        Redis._REDIS_CLUSTER_SIZE = redisCluster.length;
        Redis._redisClusterClient = [];

        createRedisClusterClients(0, resolve);

        function createRedisClusterClients(index, finished) {
            if (index >= Redis._REDIS_CLUSTER_SIZE) {
                finished();
                return;
            }

            /**
             * @type {IORedis.Redis}
             */
            const client = new Redis(redisCluster[index]); // redisCluster[index] -> { host: string, port: number  }
            client.on('error', (err) => {
                log.action('redisInit').data({
                    redisOptions: redisCluster[index],
                    total: redisCluster.length,
                    index,
                }).error(err);
                reject(err);
            });
            client.on('ready', () => {
                log.action('redisInit').data({
                    redisOptions: redisCluster[index],
                    total: redisCluster.length,
                    index,
                }).info('redis is ready to use');
                createRedisClusterClients(index + 1, finished);
            });
            client.on('reconnecting', (delay) => {
                log.action('redisInit')
                    .data({
                        delay,
                        redisOptions: redisCluster[index],
                        total: redisCluster.length,
                        index,
                    })
                    .info('reconnecting redis');
            });

            Redis._redisClusterClient[index] = client;
        }
```
all settings are default, no extra options.
Below you can see connections count (~65K, AWS limitations):
![image](https://user-images.githubusercontent.com/4151616/65577051-c32d2d00-df7b-11e9-96d4-9b461f6d1742.png)

here spikes when Redis connections reached to max
![image](https://user-images.githubusercontent.com/4151616/65577590-be1cad80-df7c-11e9-9e28-31d0186fc6c9.png)

After migrating back to the `node_redis`, connections back to normal:
![image](https://user-images.githubusercontent.com/4151616/65577344-49497380-df7c-11e9-9627-7f6c5255c0e1.png)

**Comment by tuananh** [comment]
@akaNightmare how did you solve this problem?
