### ISSUE TITLE
Typescript definition for redis.call is missing

### ISSUE THREAD

**Issue by PhillipWinder** [luin/ioredis#974]
The Typescript definition for redis.call is missing in the index.d.ts of @types/ioredis.

ioredis version: 1.14.1
@types/ioredis version: 4.0.18

![image](https://user-images.githubusercontent.com/17256167/65599477-39428b80-df9e-11e9-9449-5b0942d0c130.png)

**Comment by jwalton** [comment]
This project is written in typescript.  Why doesn't it just export it's own types?  O_o

**Comment by simonmeusel** [comment]
> This project is written in typescript. Why doesn't it just export it's own types? O_o

See https://github.com/luin/ioredis/pull/981#issuecomment-538718567
