### ISSUE TITLE
EXPIRE command support

### ISSUE THREAD

**Issue by kamilwylegala** [luin/ioredis#98]
Hi there,

I wonder if there is a way to invoke EXPIRE command in ioredis. Can I configure it in `set` command or should it be custom command invoked right after `set`? Any ideas? If not is there plan for implementation of it?

Regards.

**Comment by luin** [comment]
ioredis supports all commands of Redis. So you can definitely call: `redis.expire('foo', 10)` or `redis.set('foo', 'bar', 'ex', 10)`

**Comment by kamilwylegala** [comment]
Thanks for that. I'm gonna check it for sure.

**Comment by johnnychen** [comment]
it helps, 3q
