### ISSUE TITLE
poor performance on pipeline with buffers

### ISSUE THREAD

**Issue by GGeorgi** [luin/ioredis#982]
Hi everyone.
I'm trying to insert into redis about 15k buffers but getting poor performance. 
But if I try to insert same amount of data using JSON.stringify it works fast.

```
const pipe = redis.pipeline();
users.map(user => {
   pipe.set(`{users}:${user.id}`, UserModel.encode(user));
});
pipe.exec();
console.log("done");
```

on pipe.exec(); code gets freeze about for 10 seconds.

**Update:**
UserModel is protobuf. But this does not matters: Buffer.from(JSON.stringify(user)) is also same.

**Comment by knoxcard** [comment]
@luin - any thoughts?

**Comment by tuananh** [comment]
I traced it down and it has something to the recently introduced MixedBuffer class that replace the old flex-buffer it seems.

I tried the version 4.9.1 (prior to removing flex-buffer), the performance is much better.

@GGeorgi @knoxcard can you try 4.9.1 to see if it fixes your problem?

**Comment by knoxcard** [comment]
@GGeorgi - which ioredis version are you using?

Also, are you using Yarn or NPM?

**Comment by GGeorgi** [comment]
@knoxcard @tuananh 
ioredis: 4.14.1
npm: 6.4.1

**Comment by knoxcard** [comment]
@tuananh - @GGeorgi is using the latest version.

**Comment by GGeorgi** [comment]
@tuananh performance seems ok at 4.9.1 version

**Comment by luin** [comment]
Hi @GGeorgi, Could you provide a reproducible example so I can test on my machine? I used the following code and the performance is good (v4.14.1):

```javascript
const Redis = require('ioredis')
const faker = require('faker')

const redis = new Redis()

// Create a buffer from an object
function encode(obj) {
  return Buffer.from(JSON.stringify(obj))
}

// Generate some fake users
const users = new Array(150000).fill(0).map(() => (
  {
    id: Math.random() * 100000 | 0,
    name: faker.name.findName(),
    email: faker.internet.email(),
    avatar: faker.internet.avatar(),
    ip: faker.internet.ip(),
    phone: faker.phone.phoneNumber(),
    company: faker.company.companyName(),
    createdAt: faker.date.past()
  }
))

const pipe = redis.pipeline();
users.map(user => {
  pipe.set(`{users}:${user.id}`, encode(user));
});

console.log('Start #exec()')
console.time('exec')
pipe.exec();
console.timeEnd('exec')
```

Prints:

```
Start #exec()
exec: 38.897ms
```

**Comment by tuananh** [comment]
@luin because you did not `await p.exec()` there

in v4.9.1 even if you await p.exec(), it's still a lot faster.

**Comment by knoxcard2** [comment]
https://github.com/luin/ioredis/pull/991
