### ISSUE TITLE
Is there way to use multiple prefixes with a single connection?

### ISSUE THREAD

**Issue by celalo** [luin/ioredis#983]
Maybe something like this?
```javascript
var myRedis = new Redis();
fooRedis = myRedis.keyPrefix("foo:"); //just an example
barRedis = myRedis.clone().keyPrefix = "bar:"; //another example

//so that, fooRedis and barRedis are essentially two pointers to the same connection.
fooRedis.set("a", "1"); //sets foo:a -> 1
barRedis.set("b", "2"); //sets bar:b -> 2
```

**Comment by tuananh** [comment]
I don't think it is possible right now. What's the problem with 2 instance of redis? I never had to worry about no. of connection to redis.

**Comment by celalo** [comment]
You are right connection to redis is very very lightweight but it adds up if you need to open 10 connections with different prefixes in a lambda function that runs in sub 100ms. Also, the issue multiplies when you have a lot of concurrent lambda functions without being able to control container's life-cycle. Redis server ends up with hundreds of connections. It becomes a bit worrying.

**Comment by tuananh** [comment]
I see. connection pooling is still problem in Lambda last i tried.

**Comment by khaledosman** [comment]
Right, another problem is if you have a cap on the number of connections limit. I'm using a free redis instance from redislabs.com which has 30 as a max number of connections that I connect to via an AWS lambda through an apollo graphql server. So I'm facing a similar issue https://github.com/apollographql/apollo-server/issues/3434

**Comment by xanhz** [comment]
You can use native Proxy by Javascript instead
```js
function refix(client, prefix) {
        return new Proxy(client, {
            get(target, prop, receiver) {
                if (prop === 'options') {
                    return {
                        ...target.options,
                        keyPrefix: prefix,
                    };
                }
                return Reflect.get(target, prop, receiver);
            },
        });
}
```
