### ISSUE TITLE
Lua scripts keys array

### ISSUE THREAD

**Issue by shaharmor** [luin/ioredis#99]
Hi,

Is it possible to pass an array of keys to a lua script call?

For example:
```javascript
// define it
cache.defineCommand('doThat', {
    lua: 'return cjson.encode(KEYS)'
});

// then call it like this:
var keys = ['key1', 'key2', 'key3', ...];
cache.doThat(keys.length, keys);
```

What about an array for arguments?

**Comment by lpinca** [comment]
I don't know if there are better ways but I guess this will work:
```js
cache.doThat.apply(cache, keys.unshift(keys.length));
```

**Comment by shaharmor** [comment]
I just checked and my example works :+1:

**Comment by lpinca** [comment]
It's actually written in the [basic-usage](https://github.com/luin/ioredis#basic-usage) section :smile:
