### ISSUE TITLE
[question] How do I know the redis connection established successfully?

### ISSUE THREAD

**Issue by xinkule** [luin/ioredis#990]
I am new to redis, and when I see the document, I am really confused. 

I cannot find an instruction about how to check the successful connection, I expected there is a callback or something in the constructor, but there is not any document about that. And I don't know what methods the redis instance has, maybe you cannot suggest everyone using this lib know redis extremely well.

**Comment by tuananh** [comment]
you can use

```js
redis.on("connect", function() {
    // code on connect go here
})

**Comment by xinkule** [comment]
> you can use
> 
> ```js
> redis.on("connect", function() {
>     // code on connect go here
> })
> ```

Thank you, and I have one more question. Are the operations to redis server synchronized ?
Such as redis.sadd('a', '1'), redis.set('123', '123'), etc. So I shouldn't await them ?

**Comment by tuananh** [comment]
it's a Promise, you will need to await if you want the result to proceed next.

**Comment by xinkule** [comment]
> it's a Promise, you will need to await if you want the result to proceed next.

Thanks, and again, I cannot see that in the doc, it's really confused. The @types/ioredis module doesn't imply it either. Is there any chance some of the maintainers could improve the documentation ?
