### ISSUE TITLE
How to use redis sentinel with npm node_redis.

### ISSUE THREAD

**Issue by mahasheikhignite** [luin/ioredis#994]
how to use redis sentinel with npm node_redis and socket.io-redis i.e. https://github.com/NodeRedis/node_redis i have to ensure high availability when master redis is down for any reason.

**Comment by luin** [comment]
Here's the documentation on how to use Sentinel with ioredis: https://github.com/luin/ioredis#sentinel. For node_redis, there's a module for it though I haven't used it before: https://github.com/ortoo/node-redis-sentinel.

**Comment by mahasheikhignite** [comment]
@luin thanks for the response but how can i pass it to redis connection configuration could not found any article on this how to use it with redis and socket.io-redis.
Waiting for your response.
Thanks
