### ISSUE TITLE
How to execute timeseries command

### ISSUE THREAD

**Issue by satishcodespace** [luin/ioredis#995]
How do we execute TimeSeries commands (TS.CREATE, TS.ADD, etc...)

**Comment by tuananh** [comment]
just use `redis.call()`

```js
redis.call('TS.CREATE', 'temperature', 'RETENTION', '60', 'LABELS', 'sensor_id', '2', 'area_id', '32')
```

**Comment by satishcodespace** [comment]
> you can use `redis.call()`
> 
> ```js
> redis.call('TS.CREATE', 'temperature', 'RETENTION', '60', 'LABELS', 'sensor_id', '2', 'area_id', '32')
> ```

Not able to achieve it, I am trying it from node js client library,

Basically, I have installed Redis and loaded RedisTimeSeries module, But not able to execute TimeSeries command from node js redis client library, Any help is appreciated.

**Comment by tuananh** [comment]
> > you can use `redis.call()`
> > ```js
> > redis.call('TS.CREATE', 'temperature', 'RETENTION', '60', 'LABELS', 'sensor_id', '2', 'area_id', '32')
> > ```
> 
> Not able to achieve it, I am trying it from node js client library,
> 
> Basically, I have installed Redis and loaded RedisTimeSeries module, But not able to execute TimeSeries command from node js redis client library, Any help is appreciated.

what error did you get?
