### ISSUE TITLE
Will this project consider support connection pool?

### ISSUE THREAD

**Issue by machenjie** [luin/ioredis#996]
It is well known that using a single connection is serial blocking. This problem can be solved by constructing an ioredis pool using multiple instances, but I think the better solution should be that the ioredis library supports a similar way to httpagent, with its own connection pool inside to maintain a long connection to the backend redis.

**Comment by tuananh** [comment]
if the command is blocking (eg: `KEYS`), having connection pool doesn't help right? Because the command is blocking the whole redis server anyway?

**Comment by machenjie** [comment]
Why use blocking commands in a production environment? I think if you use the blocking command, then you should know what you are doing, at this time, the caller can choose to close the connection pool, but only with a single connection, of course, whether to use the connection pool is optional.

**Comment by vivialex** [comment]
I think it is betther that support the pool
